Join us page
hackforla/website pull request #1002
Opened 2021-02-04 17:06 UTC by trtincher

This is the new join us page. Access with "localhost:4000/join-us".
This corresponds to issue: #752 (this does not close the issue)
All layouts and styling are in compliance with the [Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=2991%3A0)
![Screen Shot 2021-02-04 at 11 03 58 AM](https://user-images.githubusercontent.com/35665684/106928555-ebcd4700-66d8-11eb-9562-5a09819a36dc.png)
![Screen Shot 2021-02-04 at 11 04 09 AM](https://user-images.githubusercontent.com/35665684/106928562-ed970a80-66d8-11eb-9e1e-48f5d401bc30.png)
![Screen Shot 2021-02-04 at 11 04 20 AM](https://user-images.githubusercontent.com/35665684/106928571-ef60ce00-66d8-11eb-885e-b68248634688.png)
![Screen Shot 2021-02-04 at 11 04 57 AM](https://user-images.githubusercontent.com/35665684/106928577-f1c32800-66d8-11eb-961c-316164488bcd.png)
![Screen Shot 2021-02-04 at 11 05 10 AM](https://user-images.githubusercontent.com/35665684/106928589-f38ceb80-66d8-11eb-85ba-f8c79a3b1f0c.png)
![Screen Shot 2021-02-04 at 11 05 20 AM](https://user-images.githubusercontent.com/35665684/106928600-f556af00-66d8-11eb-963e-eea6f27fe19a.png)

2021-02-05 05:01 UTC, dmcneary requested changes
Mobile view looks good! I see a couple of typos:
- h1 text in the first card ('Advice' vs 'Advise')
- some typos in that card's body text
- top/bottom margins between the buttons in the third card (Partner with us) narrower compared to Figma mock
- top/bottom margins between cards are narrower compared to Figma mock
- 'hero' element in desktop view could probably be moved up towards the main nav a bit

2021-02-07 01:48 UTC, daniellex0 requested changes
This page is looking great, it's really close! I added my notes about changes in the Figma file, to the right of the notes from before: https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=2991%3A0

2021-02-22 17:51 UTC, akibrhast commented
@trtincher Couple of things I have noticed:

1. Almost all the new files created under `_credits` in this commit has spaces in their filename. Maybe do something like this for example: `_credits/building-2.md` .  Since that would conform with the current naming scheme within the _credits folder as well as the entire repo.
2. The changes made to the file `_data/navigation/main.yml` seems to be something that was automatically done by ide/editor. Should it be removed from the commit ?
3. The value of the artist key in all the new md files created does not conform same casing style. Some are camel case some are lower case. Shouldn't they all conform to the same format/casing style ?

Also if someone could please explain to me why this file `_sass/main.scss` is showing to have a merge conflict .. When it looks like @trtincher has just added a new line to it ... ?

@daniellex0 @dmcneary

2021-02-24 03:44 UTC, trtincher commented
Reviewed this in Dev meeting on 02/23/2021 and there where duplicate files from merge process. Will role back to previous commit and access what went wrong.

2021-02-25 01:50 UTC, daniellex0 commented
@trtincher The page looks perfect! 🙌

Just one tiny edit: 
adding **margin-left: 48px**
to (nested):
@media (min-width: 768px) .join-us-card-container .page-card .join-us-donation

And then it should be good to go! Thanks for all of the work on this!

2021-02-28 21:18 UTC, akibrhast commented on _data/navigation/main.yml
> +
There does not seem to have been any change to this file in regards to this pull request. Any chance this could be removed from the pull request?

2021-02-28 21:18 UTC, akibrhast commented on join-us.html
> +        <p class='join-us-remove-p-padding'>
Would it be possible for the content of this paragraph to be inside a liquid for loop?

2021-03-02 15:16 UTC, trtincher commented on join-us.html
> +        <p class='join-us-remove-p-padding'>
Certainly possible. I see what you mean. Could be a good refactor

2021-03-02 15:19 UTC, trtincher commented on _data/navigation/main.yml
> +
Do you know the git command to do that?

2021-03-02 18:16 UTC, akibrhast commented on _data/navigation/main.yml
> +
Not off the top of my head, no. You will have to look into that. But i believe this might be it from the contrrib.md file(Please do double check tough).

> -Use the git reset HEAD command to remove a staged file.

>This command will remove a file that has been staged. This file will not be committed (saved) when you run the next command, git commit. This only works if the wrong files were added, but they were not yet committed. The file will be removed from the staging area, but not actually deleted:

> `git reset HEAD “filename.ext” `

2021-03-03 03:35 UTC, akibrhast commented
We are waiting for @martham0 to nest her classes #1154 and then this will be re-reviewed

2021-03-10 03:56 UTC, akibrhast commented
@trtincher , @martham0 #1154 has now been merged

2021-03-13 07:02 UTC, daniellex0 approved these changes
If everything looks good after Martha fixed her page card class that was affecting this page, then this is approved 👍

2021-03-13 22:02 UTC, jbubar requested changes
few minor request! this looks great!
I would be curious to hear what @daniellex0 has to say about my requests.

2021-03-13 22:02 UTC, jbubar commented on join-us.html
> +            <a href="civicopportunity@hackforla.org">Send and email</a> to our
needs to be `href="mailto:civicopportunity@hackforla.org"` otherwise it wont work..
Like line 149

2021-03-13 22:02 UTC, jbubar commented on join-us.html
> +            <a href="https://www.linkedin.com/in/bonnieawolfe/">Bonnie Wolfe</a>
could you add `target="_blank"` attribute to all of the a tags so that they all open in a new tab?

2021-03-13 22:02 UTC, jbubar commented on join-us.html
> +          <li>Join our slack (if you are comfortable using slack)</li>
Im not a designer.. but is it possible to provide a link to our slack here?

2021-03-15 21:56 UTC, daniellex0 commented on join-us.html
> +            <a href="https://www.linkedin.com/in/bonnieawolfe/">Bonnie Wolfe</a>
@jbubar Yes, good call 👍

2021-03-15 21:57 UTC, daniellex0 commented on join-us.html
> +          <li>Join our slack (if you are comfortable using slack)</li>
@jbubar You are totally right, thank you for catching this- here is the slack self-invite link @trtincher :

https://hackforla-slack.herokuapp.com/

2021-03-15 22:15 UTC, jbubar commented on join-us.html
> +          <li>Join our slack (if you are comfortable using slack)</li>
Thanks!

2021-03-17 01:02 UTC, trtincher commented on join-us.html
> +            <a href="https://www.linkedin.com/in/bonnieawolfe/">Bonnie Wolfe</a>
Do you think I should add it to these @jbubar @daniellex0 ? Seems a bit excessive to me in this instance.
<img width="589" alt="Screen Shot 2021-03-16 at 8 01 09 PM" src="https://user-images.githubusercontent.com/35665684/111398974-5dae8e00-8692-11eb-9024-9a67ee9b4da1.png">

2021-03-17 02:19 UTC, merged