brigade org playbook
hackforla/website pull request #1007
Opened 2021-02-07 12:29 UTC by matthewlee626

Fixes #965

2021-02-07 17:37 UTC, drubgrubby requested changes
I haven't done a close inspection yet, but this looks good on first glance. 

Once you fix the YAML exception you can push the changes and make a note here and in the issue that the changes have been fixed and we can check it and merge it. 

In general, it's best not to create a pull request until you have completely solved the problem and you think the issue is ready to merge.   Until then, you should just keep the comments and questions on the issue itself.

2021-02-07 17:37 UTC, drubgrubby commented on _projects/brigade-organizers-playbook.md
> +alt: 'Brigade Organizer's Playbook Extension Project'
As you stated in the issue, this page is throwing a YAML exception. 

The problem seems to be the apostrophe in line 6 - alt: 'Brigade Organizer's Playbook Extension Project'. It's trying to process the apostrophe as part of the code and throwing a YAML Exception.

You can use an html entity (')in place of the apostrophe in that sentence to solve the problem.

The sentence would look like: alt: 'Brigade Organizer's Playbook Extension Project

2021-02-07 23:11 UTC, matthewlee626 commented
Sorry about that! I'll keep that in mind for future issues.￼

2021-02-10 03:16 UTC, matthewlee626 commented
Addressed the problem in the issue! This should be good to merge.

2021-02-14 03:37 UTC, merged