Community Survey project card
hackforla/website pull request #1009
Opened 2021-02-07 19:16 UTC by danyc23

2021-02-08 00:03 UTC, jbubar commented
@danyc23 This looks great! can you link to the issue and link some photos in it?

2021-02-08 20:08 UTC, danyc23 commented
Issue #932 
- The project card was successfully created.

![Screen Shot 2021-02-08 at 12 05 02 PM](https://user-images.githubusercontent.com/42159475/107275073-20f1d600-6a06-11eb-8459-eeb1233bf9f4.png)

![Screen Shot 2021-02-08 at 12 03 55 PM](https://user-images.githubusercontent.com/42159475/107275215-4e3e8400-6a06-11eb-815d-1b4273bcb933.png)

![Screen Shot 2021-02-08 at 12 04 27 PM](https://user-images.githubusercontent.com/42159475/107275156-3961f080-6a06-11eb-9b00-ef8e2b925ddc.png)

2021-02-08 22:39 UTC, ExperimentsInHonesty commented on _projects/open-community-survey.md
> +
There is a blank line here and a few other places in the file.  I think the convention is to not have any blank lines.  If we have changed that, or you are copying your format from another page that does have blank lines, please reply with that detail.

2021-02-08 22:39 UTC, ExperimentsInHonesty commented on _projects/open-community-survey.md
> +
blank line

2021-02-08 22:39 UTC, ExperimentsInHonesty commented on _projects/open-community-survey.md
> +
blank line

2021-02-08 22:44 UTC, ExperimentsInHonesty commented on _projects/open-community-survey.md
> +  - name: John
Can you remove John.  He has stepped down .  I'll make a note on the issue too.

2021-02-08 22:44 UTC, ExperimentsInHonesty requested changes
See my individual comments for changes

2021-02-09 01:19 UTC, danyc23 commented
Changes are made and committed.

![Screen Shot 2021-02-08 at 5 18 40 PM](https://user-images.githubusercontent.com/42159475/107302145-beaeca80-6a31-11eb-8f78-ace315114875.png)

2021-02-09 20:03 UTC, drubgrubby requested changes
The Open Community Survey card looks great. Nice work.  

In looking at the "Files changed" it looks like there are also changes made to tdm-calculator.md, which is not part of this PR.  I'm guessing that this is because you didn't change back to gh-pages before creating a new branch for this issue.  We need to remove the changes to tdm calculator before we push this.  If you have questions about how to do that, we can go over it at the meeting.

2021-02-09 20:05 UTC, drubgrubby commented
Also, it should say 
```
Fixes #932
``` 
so that the issue is automatically closed when the PR is merged.

2021-02-10 03:08 UTC, closed without merging