Implement filter on wins page (#1030)
hackforla/website pull request #1034
Opened 2021-02-13 23:08 UTC by akibrhast

Fix #1030 

This PR Implements the filtering system on the wins pages.
![issue#1030](https://user-images.githubusercontent.com/32349001/107864017-825ede00-6e26-11eb-9da3-f6ab5657112f.gif)

2021-02-14 04:37 UTC, drubgrubby requested changes
@akibrhast - Really nice work!  I've just done a quick look, but the code looks really clean and the functionality looks like it works as it should.  

A couple of nips and tucks: 
1) At a certain point, on mobile, the "Team" dropdown floats off the screen

<img width="565" alt="Screen Shot 2021-02-13 at 8 12 04 PM" src="https://user-images.githubusercontent.com/68244054/107868278-ef2ea400-6e37-11eb-99fc-09d1a5996db5.png">

I'm not sure what the solution to this is, probably that the size should just get smaller ('cause you can't really stack them (Can you?)).  This is the one that really needs to be fixed before we merge (in my opinion). 

2) The box on the dropdown is wider than the box before it drops down, and it pushes out over the bottom of the other drop-down: 

<img width="571" alt="Screen Shot 2021-02-13 at 8 15 21 PM" src="https://user-images.githubusercontent.com/68244054/107868323-6d8b4600-6e38-11eb-8de4-c93dc9272d4a.png">

It does that on the current frontpage, so maybe that's a feature and not a bug.  I find it sub-optimal, but...what do I know. 

3) On Firefox there's a weird thing that happens where, if I tell it to load an iPhone 6 (or anyother mobile size) screen, the drop-downs don't work.  If I drag the screen to desktop, and then drag it back to the exact same size, they work fine.  I'm not sure if that means anything, or if it's just a browser anomaly, so I'm just mentioning it. (There's a way to check this on an actual phone; I'll see if I can remember how to do that).

4) On Firefox, the dropdowns open and close with a mouseover. In chrome, they open with a click, which is fine.  They close if I click outside the box, or on the other dropdown.  I clicked on the arrow in the dropdown a bunch of times thinking "why isn't this closing?!" before it occurred to me that maybe they weren't supposed to.  Should we have the drop-down close on click also? 

@daniellex0 - Most of these are actually design questions. Can you weigh in?  Thanks.

2021-02-14 06:08 UTC, daniellex0 commented
Looks good!

@drubgrubby - 

2. Yes the dropdown is wider than the box on the homepage as well, and I believe this is because some of the items within the homepage drop down are longer than the top box so they need more room. It would look cleaner if it was the same size, but this does leave some room for longer team names in the future.. I think for the sake of standardization we can leave it like this for now instead of creating a new class with a different size right now, since this works and looks good enough- but maybe down the line I can add a few different sizes of dropdown options to the design system.

4. The dropdowns open and close for me when I scroll over on Chrome!

2021-02-14 17:41 UTC, drubgrubby commented
@daniellex0 - What do you think about question 1, where half of the team drop-down is cut off on mobile.  What a good fix for that?

2021-02-14 17:43 UTC, drubgrubby commented
@akibrhast @jbubar - Just a general question for this, and all of the other pages that we work on.  Is there any javaScript on this page that might be useful on other pages that we should put in a file to be included, so it can be reused rather than having to be re-written on every page we use it on?  For example, since the drop-downs are basically the same on this page and on the homepage, is there any of that code that is re-useable?

2021-02-14 17:53 UTC, jbubar approved these changes
This is really really awesome! I really enjoyed review this code. I learned a lot of new methods and functions! thanks Akib! It works great. One thing is that, as a project, we do not use inline styling. But I think that this can be separated out into a medium sized issue. We will talk about it in the dev meeting today

2021-02-14 18:43 UTC, akibrhast commented
> Just a general question for this, and all of the other pages that we work on. Is there any javaScript on this page that might be useful on other pages that we should put in a file to be included, so it can be reused rather than having to be re-written on every page we use it on? For example, since the drop-downs are basically the same on this page and on the homepage, is there any of that code that is re-useable?

@jbubar The filters that are currently being used in wins-page.html is very similar in what it is doing when comparing to the filter implemented in project-filter.js 

The comment for the class defined in project-filter.js states
```
/**
 * Wraps a Hack for LA project object for filtering
 * @param {Object} data - the object containing all filterable fields for a project 
 */
```
As such it should be possible to create a singular class that can handle that, or maybe subclass from the existing function. Maybe make a new issue/discussion about `Refactoring Filter Methods` . If I am not mistaken #959 could also use this generic functionality,

2021-02-15 00:56 UTC, daniellex0 commented
> @daniellex0 - What do you think about question 1, where half of the team drop-down is cut off on mobile. What a good fix for that?

I think it should be formatted the exact same way the dropdowns on the homepage are in mobile if possible - 

<img width="289" alt="Screen Shot 2021-02-14 at 4 55 56 PM" src="https://user-images.githubusercontent.com/67400366/107894758-8c93e180-6ee5-11eb-82c1-cabb2ab794ec.png">

2021-02-15 01:25 UTC, akibrhast commented
Made changes as requested by @drubgrubby 
> At a certain point, on mobile, the "Team" dropdown floats off the screen
![issue#1030ReworkedFilterCSS](https://user-images.githubusercontent.com/32349001/107895886-cb846000-6f02-11eb-80e4-2a1c15a9e004.gif)

2021-02-15 01:55 UTC, jbubar requested changes
Two small changes. use new classes, and change the breakpoint

2021-02-15 01:55 UTC, jbubar commented on _sass/components/_wins-page.scss
>  ul.filter-list{
you should not change filter-list because it changes the styling on the main page as well... Use a different class
![Screen Shot 2021-02-14 at 5 41 00 PM](https://user-images.githubusercontent.com/53061723/107897074-0f6c6a80-6eed-11eb-81f7-77161b065054.png)

2021-02-15 01:55 UTC, jbubar commented on _sass/components/_wins-page.scss
> +@media (max-width: 659px){
Maybe we want the breakpoint to happen earlier....
how about using:
@media #{$bp-below-tablet}{
}

2021-02-15 02:37 UTC, akibrhast commented on _sass/components/_wins-page.scss
> +@media (max-width: 659px){
Applied the break point as mentioned above.

2021-02-15 02:40 UTC, akibrhast commented on _sass/components/_wins-page.scss
>  ul.filter-list{
Replaced the css from
``` ul.filter-list{ } ``` which broke the filter styles on the project page to ```.wins-page-contain > ul.filter-list{ } ``` which now only overrides the properties of the filter-list that are a child of the element with class `.wins-page-contain`

2021-02-15 03:56 UTC, jbubar approved these changes
Looks good to me!

2021-02-15 03:58 UTC, jbubar commented
A good medium issue will be to change the background color to pink when something is checked
![Screen Shot 2021-02-14 at 5 51 41 PM](https://user-images.githubusercontent.com/53061723/107903779-e654d580-6efe-11eb-9471-ac8def923c59.png)

2021-02-16 02:55 UTC, drubgrubby approved these changes

2021-02-16 02:56 UTC, drubgrubby approved these changes
@akibrhast - Really good work!  This is ready to merge.

2021-02-16 02:56 UTC, merged