#75 removes classname from input and fixes accessibility score on lighthouse
hackforla/website pull request #108
Opened 2019-05-15 03:03 UTC by stu562

Also adds  aria-label property

2019-05-20 18:56 UTC, abregorivas requested changes
Please add back the "sr-only" classes as they are needed to keep the look of the site the same but still accessible.

2019-05-20 18:56 UTC, abregorivas commented on _includes/forms/contact-us.html
> +  <label for="message">
We do not want to remove this class. The text should be hidden but readable for screen readers.

2019-05-20 18:56 UTC, abregorivas commented on _includes/forms/contact-us.html
> +      <label for="contact-email">
Same as above keep class "sr-only"

2019-05-20 18:56 UTC, abregorivas commented on _includes/forms/hero-signup.html
> +    <label for="hero-signup">Enter your email address</label>
keep "sr-only" class

2019-05-22 02:02 UTC, stu562 commented
updated pull request, 
removed label from code. class="sr-only" purpose is to make it not visible. 
the arial label is a text label that is not visible to the screen. Passes audit score and verifying not visible on local enviornment

2019-05-22 23:15 UTC, thekaveman commented
hey @stu562, I think @abregorivas has it right - we should prefer `sr-only` hidden labels vs. `aria-label`. I've only done a small bit of reading, but it seems that ARIA properties aren't actually *required* to be supported in Screen Readers.

Here's an interesting look at this exact issue across a range of Screen Reader + Browser combinations: https://www.powermapper.com/tests/screen-readers/labelling/input-text-aria-label/

The conclusion is:

> A more reliable alternative is wrapping the INPUT with a LABEL element.

2019-05-27 19:16 UTC, ExperimentsInHonesty commented
I have reassigned the issue to @abregorivas, so that he can either test the code, or discuss in person on next hack night with @stu562 Steven.

2019-05-29 19:29 UTC, abregorivas commented
Please remove the label tags for the following 
- contact-us form remove(contact-email, message) label
- hero-signup form remove(hero-signup) label
Add the text that was in labels to an "aria-label" to its corresponding input field.

2019-06-05 03:02 UTC, merged

2024-09-02 09:17 UTC, ajb176 commented
You must be a member of the HFLA website team in order to create pull requests. Please see our page on how to join us as a member at HFLA: https://www.hackforla.org/getting-started.  If you have been though onboarding, and feel this message was sent in error, please message us in the #hfla-site team Slack channel with the link to this PR.