fixes the issue where if clicked the page would stop displaying info…
hackforla/website pull request #1147
Opened 2021-03-01 22:13 UTC by thatguyish

Fixes# 1106

…rmation (like meetup events, and team meetings)

2021-03-01 22:39 UTC, jbubar requested changes
the cute little carrot animation on mobile seemed to have broke. Here is what it looks like on the live page.. I think you might need to add back in the this.classList.toggle("active") some how
<details>
<summary>live site</summary>
<img src='https://user-images.githubusercontent.com/53061723/109568778-3eadda80-7a9c-11eb-9748-42ac2f5b69f9.gif'/>
</details>

2021-03-02 18:52 UTC, akibrhast requested changes

2021-03-02 18:52 UTC, akibrhast commented on events/events.html
> +  function fixDropDown(){
```javascript
function fixDropdown()
```
Please rename your function to what it does and not what it fixes

2021-03-03 01:18 UTC, jbubar approved these changes
Looks good!

2021-03-03 01:24 UTC, jbubar requested changes
Oops. just noticed something...
When you resize from desktop to mobile.. the accordions should start out closed

2021-03-03 01:27 UTC, thatguyish commented
@jbubar okay cool thank you 😁 will make hopefully final changes lol.

2021-03-03 02:11 UTC, thatguyish commented
@jbubar should be good lol sorry about that.

2021-03-03 03:22 UTC, merged