Nesting bleeding classes into overarching class
hackforla/website pull request #1158
Opened 2021-03-03 18:16 UTC by martham0

Fixes #1154 

Nested requested classes. Hopefully fixes the bleeding happening on issue #752

2021-03-07 03:20 UTC, daniellex0 commented
Hey @martham0 (FYI it's definitely possible that I am looking at the wrong file and you have done this already, or I am confusing this in some way, so take what I say with a grain of salt lol)-

But is it possible to move this section in the purple rectangle-

<img width="374" alt="Screen Shot 2021-03-06 at 6 49 07 PM" src="https://user-images.githubusercontent.com/67400366/110227801-ce92c080-7eb0-11eb-8503-641f9769fa45.png">

... and next it under this `.sitemap-page` class as well:

<img width="234" alt="Screen Shot 2021-03-06 at 6 49 15 PM" src="https://user-images.githubusercontent.com/67400366/110227824-0568d680-7eb1-11eb-93d6-c40156f5243b.png">

 ... so that it only affects your page cards and not the ones on Travis' page?

2021-03-07 16:33 UTC, trtincher requested changes

2021-03-07 16:33 UTC, trtincher commented on _sass/components/_sitemap.scss
>  /*---------------------------
So everything below this still is not nested, if I am looking at this correctly. All of this should be nested as well.

2021-03-07 16:33 UTC, trtincher commented on _sass/components/_sitemap.scss
> -    .page-card-lg:nth-child(1n+2){
As this is currently there will still be a bleeding problem I believe.

2021-03-08 21:36 UTC, martham0 commented on _sass/components/_sitemap.scss
>  /*---------------------------
Fixed!

2021-03-09 22:31 UTC, daniellex0 approved these changes
I think this should work... but @trtincher you're the nesting expert - if you think this looks good, maybe we should merge this and see how it affects your page?

2021-03-10 02:15 UTC, trtincher approved these changes
@martham0 Yeah that will do it I think. Thanks!

2021-03-10 03:23 UTC, merged