959 toolkit banner links
hackforla/website pull request #1199
Opened 2021-03-12 20:35 UTC by akibrhast

Closes #959 

- The majority of the features requested(filtering mechanism) in #959 was implemented by @mcspach 
- I just fixed the last issue on this where filtering was causing images to not render

2021-03-12 21:31 UTC, drubgrubby approved these changes
@mcspach @akibrhast - Nice work on these links/filters.  All seems good to me.

2021-03-13 05:01 UTC, jbubar commented
Looks great... I just noticed one inconsistency.
If you click on "All", "Development", or "Design" it has a slightly different behavior than clicking  on "Project Management", and "Project Development"

2021-03-13 05:13 UTC, jbubar requested changes
Could you look over this one line? 
line 20 in toolkit.html
It is inconsistent.
Personally, I would prefer if it did not redirect, as in I prefer the behavior of Project Management, and Professional Development rather than All, Development, Design

2021-03-13 05:13 UTC, jbubar commented on toolkit.html
> +      <a href="#{{category | replace: ' ', '+'}}" id="{{ category }}" class="toolkit-header__banner-item">{{ category }}</a>
This appears to redirect to the guide pages (hiding the menu bar) for All, Development, Design,  but not for Project management, and Professional Development

Maybe do this?

``` diff
-<a href="#{{category | replace: ' ', '+'}}" id="{{ category }}" class="toolkit-header__banner-item">{{ category }}</a>
+<a href="#{{category | replace: ' ', '+'}}" id="{{ category  | replace: ' ', '+'}}}" class="toolkit-header__banner-item">{{ category }}</a>
```

Or.. to be honest. I dont really like the behavior of the <a> tag.. so maybe it would be best to get rid of the href

2021-03-14 16:40 UTC, akibrhast commented on toolkit.html
> +      <a href="#{{category | replace: ' ', '+'}}" id="{{ category }}" class="toolkit-header__banner-item">{{ category }}</a>
> It is inconsistent.
- It is now consistent.

> Personally, I would prefer if it did not redirect, as in I prefer the behavior of Project Management, and Professional Development rather than All, Development, Design 
 - It does not redirect anymore

2021-03-14 17:47 UTC, merged