Standardizing wins page
hackforla/website pull request #1204
Opened 2021-03-14 18:35 UTC by evancchen

Fixes #1166

2021-03-15 16:20 UTC, Lol-Whut commented
It looks like element nesting got shuffled around a little bit during edits. When I pulled the branch to my machine and accepted incoming changes, I got syntactical error warnings for the curly braces on lines 56 and 87, and styling changes did not show up for me in the browser. @akibrhast are you seeing the same, or is this on my end?

2021-03-15 16:41 UTC, akibrhast requested changes
@evancchen 
- Please fix the merge conflicts.
- Please ensures scss nests are properly nested and you can build the changes locally after addressing the merge conflicts

This is what I am seeing on my end when I try to build with `docker-compose up`
```bash
hfla_site    | jekyll 3.9.0 | Error:  Invalid CSS after "...b67d488000a5e71": expected "{", was "}" on line 59
hfla_site    |   Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/main.scss':
hfla_site    |                     Invalid CSS after "...b67d488000a5e71": expected "{", was "}" on line 59
hfla_site    | /usr/gem/gems/jekyll-sass-converter-1.5.2/lib/jekyll/converters/scss.rb:123:in `rescue in convert': Invalid CSS after "...b67d488000a5e71": expected 
"{", was "}" on line 59 (Jekyll::Converters::Scss::SyntaxError)
```

2021-03-16 16:03 UTC, akibrhast commented
@Lol-Whut It seems like @evancchen has updated the PR since our last review. Please re-review this and approve his changes if everything looks good , and nothing breaks.

2021-03-16 20:23 UTC, Lol-Whut commented
This is definitely looking better! No merge problems, the h1 tag is giving the "Let's Celebrate Together!" its styling and the margin-bottom is now 56px. However, it looks like the max-height of the .wins-hero img class still needs to be adjusted to 360px and the color of .wins_see-more-div still needs to be adjusted to $color-red. I think once those changes are in, it'll be perfect!

I think we should be seeing those two changes in these areas:
![image](https://user-images.githubusercontent.com/40847248/111374296-ec0f1980-866a-11eb-94e4-603be0fdcde4.png)

2021-03-16 20:25 UTC, Lol-Whut requested changes
I think once the max-height and color changes I mentioned in my most recent comment are made, we'll be good to go!

2021-03-17 00:45 UTC, akibrhast approved these changes

2021-03-17 02:44 UTC, Lol-Whut requested changes

2021-03-17 02:44 UTC, Lol-Whut commented on _sass/components/_wins-page.scss
> +        height: 360px;
change this to max-height and it'll be perf!

2021-03-17 03:12 UTC, Lol-Whut commented
Looks good to me!

2021-03-17 03:13 UTC, merged