made changes based on figma to events page
hackforla/website pull request #1210
Opened 2021-03-16 18:11 UTC by thatguyish

fixes #1115 

![hackforla](https://user-images.githubusercontent.com/45778144/111359064-72266280-8661-11eb-987d-c13a5c60b135.jpg)
![hackforlapt2](https://user-images.githubusercontent.com/45778144/111359065-72266280-8661-11eb-84c0-f1c62d26c633.jpg)

2021-03-19 00:55 UTC, daniellex0 requested changes
Looks great, and so close- the mobile font is still showing up as 12pm, but I noticed it is probably because of the "verison" (version) type-o. After that it'll be ready!

2021-03-19 00:55 UTC, daniellex0 commented on _sass/components/_events.scss
> +  .mobile-font-verison{
Fix type-o: "version" instead of verison

2021-03-21 20:19 UTC, akibrhast requested changes
Please fix merge conflicts @thatguyish

2021-03-24 18:58 UTC, thatguyish commented
Changed the type-o on the events.scss page and no merge conflicts when commited.

2021-04-01 02:39 UTC, akibrhast commented
@thatguyish  please resolve merge conflicts

2021-04-11 19:27 UTC, closed without merging