Alt text audit
hackforla/website pull request #1355
Opened 2021-04-04 21:01 UTC by qiqicodes

fixed #1192 

Action Items
- [x] Confirm every image has an alt attribute
- [x] Add appropriate descriptions for images

2021-04-05 08:23 UTC, jbubar reviewed
Pretty extensive pull request!
Great work.. just finished my first pass through. 
I read all the changes, and they are all really well written and descriptive.
I will test out all the pages tomorrow.

2021-04-05 08:23 UTC, jbubar commented on _projects/record-clearance-project.md
> +alt: 'Record clearance project logo'
just thought I would point this one out.. lol

2021-04-06 04:19 UTC, martham0 requested changes

2021-04-06 04:19 UTC, ItsLaszlo commented on pages/about.html
> +                                <div class="grid-center"><img src="assets/images/about/sdg-elements/sdg-la.svg" alt="Los Angeles Sustainable Development wheel logo" /><br />
missing the beginning **/** in the src field

`src="/assets/images/about/sdg-elements/sdg-la.svg"`

<img width="980" alt="Screen Shot 2021-04-05 at 8 47 56 PM" src="https://user-images.githubusercontent.com/69860036/113657562-1002c100-9653-11eb-9311-e1920eb4cda9.png">

2021-04-06 04:19 UTC, ItsLaszlo commented on pages/about.html
> +                </div>/
need to remove the **/**

2021-04-11 19:10 UTC, akibrhast commented
@qiqicodes Could you please resolve the merge conflicts and apply the changes as requested by @martham0

2021-04-13 04:20 UTC, qiqicodes commented on _projects/record-clearance-project.md
> +alt: 'Record clearance project logo'
sometimes, logo is all we need xD

2021-04-13 04:20 UTC, qiqicodes commented on pages/about.html
> +                                <div class="grid-center"><img src="assets/images/about/sdg-elements/sdg-la.svg" alt="Los Angeles Sustainable Development wheel logo" /><br />
Thanks Martha, nice catch!

2021-04-13 18:39 UTC, jbubar commented
@qiqicodes could you resolve the merge conflict again?

also, this happened when I pulled it so jekyll did not render the files 
![Screen Shot 2021-04-13 at 11 36 23 AM](https://user-images.githubusercontent.com/53061723/114603484-a08d6280-9c4c-11eb-9105-ab2b2f07538b.png)
not sure why.. I looked at the files and nothing seemed off.  could you run it locally on your machine and see if you get any similar errors?

2021-04-13 20:49 UTC, jbubar approved these changes
Nice! Ready to merge, I looked through all the projects, and pages... I hope..

2021-04-13 20:50 UTC, merged