Standardize events page 1125
hackforla/website pull request #1377
Opened 2021-04-08 03:21 UTC by erikaBell

[Fixies 1125](https://github.com/hackforla/website/issues/1125)

<details>
<summary>Events Page: Banner full length & Icon + Pink Arrow have spacing</summary>

<img width="270" alt="Screen Shot 2021-04-07 at 8 09 36 PM" src="https://user-images.githubusercontent.com/67438372/113963453-749e5700-97de-11eb-8683-b69a5747524d.png">
</details>

2021-04-08 04:11 UTC, akibrhast requested changes

2021-04-08 04:11 UTC, akibrhast commented on pages/events/events.html
> +<section class="events-pag content-section">
Pretty sure its supposed to be  `class="events-page content-section"`

2021-04-08 04:11 UTC, akibrhast commented on _sass/components/_events.scss
> +  background-color: #f2c94d;
The background color #f2c94d is part of our design systems as specified in figma. We should make it into a sass variable that would reside [here](https://github.com/hackforla/website/blob/gh-pages/_sass/variables/_colors.scss).  

Please confirm with @daniellex0 what the name of that variable should be. Also ensure the new variable name for that particular color is propagated to Figma DS docs.

<details>
<summary>Figma DS</summary>

![image](https://user-images.githubusercontent.com/32349001/113967124-5fd1bb80-97fe-11eb-97e4-d83687bcf2eb.png)


</details>

2021-04-08 17:24 UTC, daniellex0 commented on _sass/components/_events.scss
> +  background-color: #f2c94d;
This isn't really relevant to this issue, but sure you could do that if you want @erikaBell ! And I haven't chosen variable names so far, but I guess it could be a dev/designer conversation.. it looks like the standard on our site right now is describing the actual color, so maybe **gold** or something like that? 

(In the future the variables could potentially change to more flexible/descriptive names so that it's easy to make future color changes - with primary/secondary/dark etc instead of actual color names)

2021-04-08 19:39 UTC, akibrhast commented on _sass/components/_events.scss
> +  background-color: #f2c94d;
Hey @daniellex0 the reason I made the above comment was because I was under the impression we are trying to move all raw colors to variables. Is that not correct?

2021-04-08 19:51 UTC, daniellex0 commented on _sass/components/_events.scss
> +  background-color: #f2c94d;
@akibrhast Yes! But maybe that should be its own issue? 

Although if you want to take care of this specific one in this issue, that's fine too

2021-04-08 20:05 UTC, daniellex0 commented on _sass/components/_events.scss
> +  background-color: #f2c94d;
Also sorry you're right @akibrhast because I didn't notice this issue is called "standardize" so I guess this is relevant- sorry, my bad

2021-04-08 20:06 UTC, akibrhast commented on _sass/components/_events.scss
> +  background-color: #f2c94d;
1. I agree with the fact that there needs to be an issue for consolidating raw color names to variable names . 

2. Imho I  think we should also be handling it during/before a merge of a PR . That way we could prevent raw colors codes from being committed to the code base. I would go so far as to say, maybe we should also have an automated test that blocks a PR from being merged if it contains raw colors.

- Will you be making that issue in regards to (1), or would you like me to create it ? 
- What do you think about having an automated script testing for that ?

2021-04-08 20:14 UTC, daniellex0 commented on _sass/components/_events.scss
> +  background-color: #f2c94d;
Can you create the issue for # 1 please? Thank you!

Regarding the script, I have no idea haha, automation is beyond me.. up to you/dev team!

2021-04-08 20:31 UTC, akibrhast commented on _sass/components/_events.scss
> +  background-color: #f2c94d;
Issue created for # 1 mentioned above in https://github.com/hackforla/website/pull/1377#discussion_r610059694  

- The issue: https://github.com/hackforla/website/issues/1378

2021-04-08 21:12 UTC, erikaBell commented on pages/events/events.html
> +<section class="events-pag content-section">
Added the missing 'e'

2021-04-08 21:30 UTC, akibrhast approved these changes
LGTM. Feel free to merge if everything is good on your end @daniellex0

2021-04-10 02:37 UTC, daniellex0 requested changes
Just added one notes about a missing semicolon but otherwise everything looks good, great job!

2021-04-10 02:37 UTC, daniellex0 commented on _sass/components/_events.scss
> +  color: $color-black
I think there is a ";" missing after the $color-black here :)

2021-04-10 02:43 UTC, erikaBell commented on _sass/components/_events.scss
> +  color: $color-black
good catch

2021-04-10 02:49 UTC, daniellex0 commented
Great, btw thanks for detailing all the changes you made above @erikaBell ! Looks good to go 👍

2021-04-10 02:49 UTC, daniellex0 approved these changes

2021-04-10 02:51 UTC, daniellex0 commented
(PS it might be good to change the text to Fixes #1125 (written exactly like that- even though I like 'fixies' lol) because that apparently will cause #1125 to automatically be closed when this PR is merged :) )

2021-04-10 04:53 UTC, merged