Adjust Wins page styling 1336
hackforla/website pull request #1386
Opened 2021-04-10 03:26 UTC by erikaBell

[ Fixes #1336 ](https://github.com/hackforla/website/issues/1336)

Additional style changes were put on "...see more" (appears during mobile view), as the changes from issue #1336 altered their placement. 

<details>
<summary>Adjustments to Wins Page Styling, mobile view</summary>

![image](https://user-images.githubusercontent.com/67438372/114256924-7ba99e80-9971-11eb-89d0-2b9f1cbb5eec.png)

</details>

<details>
<summary>Filter List Re-size, full screen view</summary>

<img width="630" alt="Screen Shot 2021-04-09 at 8 25 12 PM" src="https://user-images.githubusercontent.com/67438372/114256989-b90e2c00-9971-11eb-88a5-b5e40e8e63f3.png">

</details>

2021-04-10 21:37 UTC, erikaBell commented
I think this issue fixes issue #1376 as well? @jbubar

2021-04-11 02:40 UTC, jbubar commented
@erikaBell Nice work!
It would.. Ill go close that issue!
I dont have time to review until after sunday, but it looks great

2021-04-11 14:49 UTC, daniellex0 commented
Looks good @erikaBell ! The only change I have is:

> In mobile only: make the "Team(s)" and "Role(s)" sections the same font size- 15px - use rem units (currently one is 12px and one is 16px)

To make sure these are 15px (in rem) in mobile (instead of 16px) :) - sorry I know it probably would make more sense if I wrote 16px on there lol, but trying to make these less prominent and not push the content in the card too far down/close to its bottom edge

2021-04-11 14:50 UTC, daniellex0 requested changes
Looks good @erikaBell ! The only change I have is:

> In mobile only: make the "Team(s)" and "Role(s)" sections the same font size- 15px - use rem units (currently one is 12px and one is 16px)

To make sure these are 15px (in rem) in mobile (instead of 16px) :) - sorry I know it probably would make more sense if I wrote 16px on there lol, but trying to make these less prominent and not push the content in the card too far down/close to its bottom edge

2021-04-13 18:06 UTC, daniellex0 approved these changes
Sorry about the delay, looks good! 👍

2021-04-13 20:39 UTC, jbubar approved these changes
Nice job

2021-04-13 20:39 UTC, merged