Update join page
hackforla/website pull request #1405
Opened 2021-04-14 19:55 UTC by danyc23

2021-04-14 21:38 UTC, erikaBell reviewed
@danyc23 looking good overall! I do have one question though, if I can pull @daniellex0 into it. I noticed one of the changes in this branch was a change on where a user is redirected when clicking on the "Project Volunteer" button 
<details>
<summary>Project Volunteer Btn</summary>

<img width="989" alt="Screen Shot 2021-04-14 at 2 30 43 PM" src="https://user-images.githubusercontent.com/67438372/114783680-ee7a9700-9d2e-11eb-9ee4-a55ebda4418a.png">

<img width="744" alt="Screen Shot 2021-04-14 at 2 32 34 PM" src="https://user-images.githubusercontent.com/67438372/114782127-6e543180-9d2e-11eb-8736-7cc0dd706ba8.png">
</details> 

On our live site, it redirects the user to "Getting Started"
<details>
<summary>Getting Started</summary>

<img width="1282" alt="Screen Shot 2021-04-14 at 2 30 53 PM" src="https://user-images.githubusercontent.com/67438372/114783492-d3a82280-9d2e-11eb-873f-6fa24a991897.png">
</details>

In Daniel's branch, it redirects the user to "/#projects"
<details>
<summary>Projects</summary>

<img width="1357" alt="Screen Shot 2021-04-14 at 2 31 00 PM" src="https://user-images.githubusercontent.com/67438372/114783639-dd318a80-9d2e-11eb-8b58-3dbbe6296271.png">
</details>

I did not see any mention of this change in the issue itself, or in any comments. I just want to clarify for myself if that change should be there?

If it was mentioned somewhere I didn't catch, feel free to direct me there. 

Besitos ~ ~

2021-04-15 20:32 UTC, qiqicodes requested changes
Changes looks good. 

On one note:
The href link is different from the current master branch, on line 63 is  "https://www.hackforla.org/#projects" 

On master branch is "https://www.hackforla.org/getting-started"

2021-04-17 03:14 UTC, danyc23 commented
I already made the requested changes. Let me know if there is anything else. Thanks!

2021-04-17 03:27 UTC, danyc23 reviewed
The changes from line 63 are done.

2021-04-18 06:32 UTC, daniellex0 requested changes
This looks great, just one additional change, sorry this is new- Please remove the parentheses section "(if you are comfortable using slack)" - Bonnie wants it removed. So this line should just say "Join our Slack." Other than that, looks good, thanks!

2021-04-18 06:32 UTC, daniellex0 commented on pages/join-us.html
> +          <li>Join our <a href="https://hackforla-slack.herokuapp.com/" target="_blank">Slack</a> (if you are
Please remove the parentheses section "(if you are comfortable using slack)" - sorry this is a recent change, Bonnie wants to remove this. So this line should just say "Join our Slack"

2021-04-18 16:19 UTC, danyc23 commented on pages/join-us.html
> +          <li>Join our <a href="https://hackforla-slack.herokuapp.com/" target="_blank">Slack</a> (if you are
Hey, the changes are done

2021-04-18 16:25 UTC, akibrhast approved these changes
LGTM

2021-04-18 16:25 UTC, merged