Project description style
hackforla/website pull request #1419
Opened 2021-04-18 19:30 UTC by evancchen

Fixes #1322

2021-04-18 20:24 UTC, erikaBell requested changes

2021-04-18 20:24 UTC, erikaBell commented on _layouts/project.html
> +                                <p class='leader-description-field'></p>trong>Name: </strong><a href='{{ item.links.linkedin }}' target='_blank' title='Linkedin Profile'>{{ item.name }}</a></p>
Overall your code looks great, Evan! I noticed at this line, the `<strong>` tag is missing the opening carrot `<` and an `s`. Can you fix that. 

```suggestion
 <p class='leader-description-field'></p><strong>Name: </strong><a href='{{ item.links.linkedin }}' target='_blank' title='Linkedin Profile'>{{ item.name }}</a></p>
```

2021-04-18 20:24 UTC, erikaBell commented on _sass/components/_project-page.scss
> +  margin-top: 28px;
For `margin-top: 28px`, I noticed it provides the _correct_ margin between "Project Overview" and "Getting Started", but not between the other cards — refer to Figma design if needed.

<details>
<summary>Evan's Branch</summary>

<img width="806" alt="Screen Shot 2021-04-18 at 1 08 18 PM" src="https://user-images.githubusercontent.com/67438372/115159538-74a51f00-a048-11eb-984e-df254975da4d.png">
</details>

I believe a way to fix this is by removing `margin-top: 28px` from `#getting-started-section`
instead adding `margin-top: 28px` to `.page-card--project-description-page` 

<details>
<summary>Example of Changes, via browser dev tools </summary>

<img width="269" alt="Screen Shot 2021-04-18 at 1 07 27 PM" src="https://user-images.githubusercontent.com/67438372/115159637-07de5480-a049-11eb-8a9b-2138dc7b10c5.png">

<img width="812" alt="Screen Shot 2021-04-18 at 1 07 52 PM" src="https://user-images.githubusercontent.com/67438372/115159640-0b71db80-a049-11eb-8f07-dcf2efa3a782.png">

</details>


Note: Please do a quick look around to ensure this change does not create other issues.

2021-04-20 23:10 UTC, akibrhast requested changes

2021-04-20 23:10 UTC, akibrhast commented on _layouts/project.html
> +        </div> -->
@daniellex0 I noticed that in the issue you mentioned something along the lines of

> Remove Getting Started section from being hidden under button- put in its own page card instead
>  But please just comment out the button/hidden page card functionality for now, don't delete (we may need to reuse this)

Can you please clarify by a bit in regards to what you meant by `we may need to reuse this` ? In what context, when?


Since its not being used right now, and it is a very simple implementation the existence of it is just causing clutter and it should be removed. At the same time. I think we should remove the onClick() javascript function, from wherever it is being defined.

2021-04-20 23:13 UTC, akibrhast requested changes

2021-04-20 23:13 UTC, akibrhast commented on _sass/components/_project-page.scss
> +  color: #333;
Please replace this with the right color-variable

2021-04-20 23:13 UTC, akibrhast commented on _sass/components/_project-page.scss
>    color: #333;
Please replace this with the right color-variable

2021-04-21 00:46 UTC, daniellex0 commented on _layouts/project.html
> +        </div> -->
I'm not sure, Bonnie told me to save it because we may need to reuse it..

2021-04-23 16:27 UTC, erikaBell approved these changes
looks good to me

2021-04-23 16:33 UTC, akibrhast approved these changes
lgtm

2021-04-23 16:34 UTC, merged