Standardize credits header
hackforla/website pull request #1423
Opened 2021-04-20 20:12 UTC by sena-ji

Fixes #1122

2021-04-20 22:45 UTC, akibrhast requested changes
Please remove commented out css styles in the files that you changed as well as commented out html. Also could you please ensure that the raw color in the scss file that you changed are converted to variable names.

Thank you!

2021-04-20 22:45 UTC, akibrhast commented on pages/credits.html
> +  <!-- <div class="credit-hero">
It seems line 13, and 14 were commented out. If there is no need for them can you please delete those lines from this PR

2021-04-20 22:45 UTC, akibrhast commented on pages/credits.html
> +      <!-- </div> -->
Please delete line 17 commented out empty div

2021-04-20 22:45 UTC, akibrhast commented on _sass/components/_credit-items.scss
>    background: #fff;
Please replace raw color with it's contextual variable as described in this file
https://github.com/hackforla/website/blob/gh-pages/_sass/variables/_colors.scss#L9

2021-04-20 22:45 UTC, akibrhast commented on _sass/components/_credit-items.scss
> +    // margin-top: 23%;
Please remove commented out css styles

2021-04-20 23:08 UTC, sena-ji commented
> Please remove commented out css styles in the files that you changed as well as commented out html. Also could you please ensure that the raw color in the scss file that you changed are converted to variable names.
> 
> The issue also mentions
> 
> > Reference the Sitemap Page header code, but try to use both a reusable `.header-container` class and another page-specific class (contact @daniellex0 / daniellenedivi on slack for clarification)
> 
> From what I can tell looking at the code, the `.header-container` was not used. Was there a particular reason for this?
> 
> Thank you!

For the .header-container, it seemed like there was a regular header-container and multiple header-container--<insert page name>. The reusable header-container does not give the wanted style for the page. Should I just make the changes with the header-container class? Or would you like me to make another separate class in the format: header-container--<insert page name>?

2021-04-20 23:23 UTC, akibrhast commented
@sena-ji 
I believe the standardization we are trying to move towards is to use two classes that is you use the .header-container  and you also use another class header-container--page-name . The first is to apply a generic style to it that should be consistent across all pages. The second is to apply the page specific styles to it as needed.

I would hold on before implementing that change tough. Because I would like to confirm this with daniel and the rest of the team first

@daniellex0 @jbubar Please Advise.

2021-04-21 00:50 UTC, daniellex0 commented
Yup exactly Akib, that's correct 👍 . But yeah Sena I mentioned to reach out to me in the comment because I knew it might be confusing, and we are still working on how to document all of these reusable classes for devs (it's causing a lot of confusion everywhere, you're not alone! But hopefully soon we'll have some useful/clear guidelines..)

2021-04-23 14:04 UTC, akibrhast approved these changes
Nice Work Here!

2021-04-23 14:04 UTC, merged