change font size, margin, css class name for homepage filters
hackforla/website pull request #1428
Opened 2021-04-21 04:34 UTC by qiqicodes

Fixed #1415

Changed the following for homepage filters:
1. color of "clear all"
2. font size of filter tags
3. margin between filter tags
4. css class name for filter tags

2021-04-21 17:23 UTC, erikaBell commented
@qiqicodes was there a reason this was put under "draft"? I can't remember what was talked about in the meeting last night on this ticket.

2021-04-22 06:06 UTC, qiqicodes commented
@erikaBell after I made the change, the filter toolbar is missing. I am going to debug the branch on Friday night. Thanks for asking! =]

2021-04-22 21:02 UTC, akibrhast requested changes

2021-04-22 21:02 UTC, akibrhast commented on _includes/current-projects.html
>                    ${filterName}: ${filterValue}
@qiqicodes After speaking with @daniellex0 I realized that changing the filter tag component display from
`looking: development` -> `role:development` is a trivial enough fix. As such please implement that change as was originally requested in the issue

2021-04-28 03:52 UTC, qiqicodes commented on _includes/current-projects.html
>                    ${filterName}: ${filterValue}
add the requested change to the PR.

2021-04-28 04:38 UTC, erikaBell approved these changes
Looks good! @qiqicodes only request would be to add some 'before' and 'after' photos next time (-: Thanks ~ ~

2021-04-28 04:38 UTC, merged