Added the word full to hackforla homepage header area
hackforla/website pull request #1433
Opened 2021-04-22 18:35 UTC by RobertaFricker

Fixes #1414 
Added the word "full" to the hackforla homepage header area in the _include/hero.html file:

![image](https://user-images.githubusercontent.com/81199122/115768140-c27a9980-a35e-11eb-92e8-7c71dbda5476.png)

2021-04-22 20:57 UTC, akibrhast requested changes

2021-04-22 20:57 UTC, akibrhast commented on _projects/metro-ontime.md
>  identification: '155295655'
This file has nothing to do with this PR and its linked issue. Please remove this file from the PR

2021-04-23 19:31 UTC, RobertaFricker commented on _projects/metro-ontime.md
>  identification: '155295655'
@akib I'm not sure how to delete it.  I don't want to inadvertently delete the page.  Please advise.

2021-04-23 19:40 UTC, akibrhast commented on _projects/metro-ontime.md
>  identification: '155295655'
1. Revert your commit by 1 step
    - `git revert HEAD~1`
2. Run `git status` to check for staged and changed files
3. You should be able to then run `git restore _projects/metro-ontime.md `
4. Then `git add` changed files one by one followed by `git commit `, and `git push`

2021-04-23 23:17 UTC, RobertaFricker commented on _projects/metro-ontime.md
>  identification: '155295655'
@akibrhast Thanks for the step-by-step, I used it, however, the terminal message was Hint: waiting for editor to close...."  So, I used `git reset` (a Josh directive from weeks ago) and then `git restore _projects/metro-ontime.md` then `git add _includes/hero.html` then `git commit` and `git push`.
Please confirm this made a rainbow over the code....thanks...!

2021-04-24 04:14 UTC, erikaBell requested changes
Fix:  `image: /assets/images/projects/` should be `image: /assets/images/projects/metro-ontime.png`

and 

<img width="500" alt="Screen Shot 2021-04-18 at 3 29 48 AM" src="https://user-images.githubusercontent.com/67400366/115142636-bf4a7b00-9ff7-11eb-9e76-e2ac8a62f083.png">

2021-04-24 04:14 UTC, erikaBell commented on _projects/metro-ontime.md
> +image: /assets/images/projects/
Hi @RobertaFricker, I'm not sure you necessarily need to restore things, but could just fix what has occurred?

As I see it, the metro-ontime image is broken so you would first need to add `metro-ontime.png` to the end of `/assets/images/projects/`, returning it back to it's full file path: `/assets/images/projects/metro-ontime.png`

Second, you would need to re-do the original change this issue called for, as I don't see any changes to this on my local site.


<img width="500" alt="Screen Shot 2021-04-18 at 3 29 48 AM" src="https://user-images.githubusercontent.com/67400366/115142636-bf4a7b00-9ff7-11eb-9e76-e2ac8a62f083.png">

2021-04-25 16:41 UTC, jbubar commented on _projects/metro-ontime.md
>  identification: '155295655'
Hey @RobertaFricker and @akibrhast 
try this.. if you still want to remove a unnecessary file from your pr...

This will give you the commit hash for the last commit on the upstream/gh-pages branch
`git rev-parse upstream/gh-pages`

then this command
`git checkout <THE COMMIT HASH FROM PREVIOS STEP> -- <PATH OF FILE YOU WANT TO REVERT>`

Here is an exaple
`git checkout 9af8d8c7f34cb4dfda49cd8372236f8b8bd1ea65 -- pages/wins/wins.html `

also... I am pretty sure you only need the first seven digits of the commit hash (also known as SHA value) todo the above commit.. so it can look like this 
`git checkout 9af8d8c -- pages/wins/wins.html`

and you can reference a commit in github!! with the sha hash!! 
check this out
9af8d8c7f34cb4dfda49cd8372236f8b8bd1ea65

2021-04-25 16:51 UTC, jbubar commented on _projects/metro-ontime.md
>  identification: '155295655'
I turned my last comment into a wiki
https://github.com/hackforla/website/wiki/Remove-files-from-your-Pull-Request

2021-04-25 19:31 UTC, RobertaFricker commented on _projects/metro-ontime.md
>  identification: '155295655'
@jbubar Hi Josh, I just saw this, thanks for the info.  I'm going out for awhile today, I'll look at it in detail later.  In the meantime, I just pushed the Issue #1150 to correct what we discussed that it was missing from my branch.  When I put localhost:4000 it shows up per screenshot below:

![image](https://user-images.githubusercontent.com/81199122/116006900-0c16ee80-a5c2-11eb-8c2b-11515b62d7ec.png)

Please confirm this is correct....!...there's a chocolate babka in it for you, thanks!

2021-04-27 05:53 UTC, erikaBell approved these changes
Great! Looks good @RobertaFricker (:

2021-04-27 05:53 UTC, merged

2021-04-27 19:41 UTC, RobertaFricker commented
@erikaBell ...awesome Erika, thanks for getting this one off the stack!