Changed text in Step 6 content area to match text in Step 6 Table of Contents
hackforla/website pull request #1435
Opened 2021-04-22 19:55 UTC by RobertaFricker

Fixes #1434 
Changed text so that it's the same in Step 6 Table of Contents link and in the corresponding area of the document.

Per screenshots below:
![image](https://user-images.githubusercontent.com/81199122/115777277-ed1e1f80-a369-11eb-8ced-0de57e36569d.png)

![image](https://user-images.githubusercontent.com/81199122/115777350-02934980-a36a-11eb-9406-da2ac41249a7.png)

2021-04-22 20:55 UTC, akibrhast requested changes

2021-04-22 20:55 UTC, akibrhast commented on CONTRIBUTING.md
> +#### Step 6:  Work on an issue using git
Can you please ensure that this is a link and not just a clear text.

2021-04-23 03:42 UTC, RobertaFricker commented on CONTRIBUTING.md
> +#### Step 6:  Work on an issue using git
I agree that it's not a true hyperlink.  It's actually referred to as an "anchor jump link."

Per https://coder-coder.com/make-html-anchor-link-jump-specific-part-of-page/, to create this, "you need a link and a target. The target can be any element on the web page that has an “id” attribute."
Also, "If we were on a page and wanted to jump down to a section on the same page, we could create an internal link. An internal link doesn’t require the https://www.WebsiteName.com in the link’s href attribute."

For CONTRIBUTING.md, the internal jump link is: 

![image](https://user-images.githubusercontent.com/81199122/115814623-49089880-a3aa-11eb-866c-3360dff266b0.png)

and the target has the ID per the screenshot below:

![image](https://user-images.githubusercontent.com/81199122/115814784-9422ab80-a3aa-11eb-8c6d-84fd88407d84.png)

The issue is the jump link does not have the same text as the ID text.

2021-04-23 05:31 UTC, akibrhast commented on CONTRIBUTING.md
> +#### Step 6:  Work on an issue using git
> I agree that it's not a true hyperlink


Ah, my bad. I should have clarified... Can you please ensure that it is a true hyperlink. Please refer to the syntax used in step 5.

2021-04-23 16:17 UTC, RobertaFricker commented on CONTRIBUTING.md
> +#### Step 6:  Work on an issue using git
@akibrhast ...lol...href="#step-6-work-on-an-issue-using-git" is not a true hyperlink, it doesn't go anywhere but within the same page to the area that matches its corresponding target.  It doesn't open a new tab and it doesn't have https:// in it's syntax.

2021-04-23 16:37 UTC, akibrhast commented on CONTRIBUTING.md
> +#### Step 6:  Work on an issue using git
My apologies. I was a bit confused initially. Everything looks good!

2021-04-23 16:38 UTC, akibrhast approved these changes
lgtm

2021-04-23 16:49 UTC, merged

2021-04-23 17:49 UTC, RobertaFricker commented
m2...thanks for clarifying, it was a bit sticky when Lara and I were explaining it to each other.