Wins badges and text bubbles
hackforla/website pull request #1448
Opened 2021-04-24 01:58 UTC by erikaBell

Fixes #1313 
Fixes #1431 

I have added the badges and tool tips, but I did not fix issues with "comma" separation on answers in the "Other" category. Below you will find an example of what it is currently causing.

I tried to mess around with the comma bug for a while, but it turned out to be trickier than I thought, so I figured I'd make it into a separate issue.

<details>
<summary>Comma separation issues in the "Other" category</summary>

<img width="176" alt="Screen Shot 2021-04-23 at 8 51 50 AM" src="https://user-images.githubusercontent.com/67438372/115900167-7f7afd80-a414-11eb-939a-a139d82cfcd0.png">
<br>
<br>
<img width="250" alt="Screen Shot 2021-04-23 at 8 51 59 AM" src="https://user-images.githubusercontent.com/67438372/115900179-83a71b00-a414-11eb-8c30-1c9e4e5547f1.png">

</details>

2021-04-24 01:59 UTC, erikaBell commented
@akibrhast Try this new branch and lmk.

2021-04-24 02:08 UTC, akibrhast commented
It's running fine, but that badges do not appear when you click on 'see more..'
![image](https://user-images.githubusercontent.com/32349001/115943875-732c8a00-a480-11eb-80f7-fc7e1fe5809e.png)

2021-04-24 02:29 UTC, akibrhast requested changes
Good Job On Implementing The Functionality! 😄 
I left some review comments requesting some minor changes.

2021-04-24 02:29 UTC, akibrhast commented on _sass/components/_wins-page.scss
> +    /* border-top: 10px solid #00bfb6; */
Remove commented out css line

2021-04-24 02:29 UTC, akibrhast commented on pages/wins/wins.html
> +
I am a bit confused about the existence of this function.
What is the necessity of it?
To get otherIcon can not just do
```javascript
badgeIcons['Other']
```
** _Also this function isn't really being used anywhere._

2021-04-24 02:29 UTC, akibrhast commented on pages/wins/wins.html
> +		getOtherIcon(badgeIcons)
You are calling the function `getOtherIcon()` but not doing anything with the return value.
Possibly get rid of it.

2021-04-24 02:29 UTC, akibrhast commented on pages/wins/wins.html
> +				console.log(item)
Remove `console.log()`

2021-04-24 02:29 UTC, akibrhast commented on pages/wins/wins.html
> +		// cloneCardTemplate.querySelector('.wins-card-info').textContent = card[win];
Remove commented out line of code.

2021-04-24 02:29 UTC, akibrhast commented on pages/wins/wins.html
> +		insertIcons(cloneCardTemplate, card[win])
While this function works great it breaks the flow of code readability with the rest of the stuff this function is doing.

Refactor it in such a way that it maintains readability with the rest of the lines. 
OR
Refactor rest of the lines such that it follows this style of coding.

2021-04-24 02:29 UTC, akibrhast commented on _sass/components/_wins-page.scss
> +    font-weight: normal !important;
Is it not possible to apply font-weight on this without using `!important` ?
That is generally bad practice.

2021-04-24 03:28 UTC, erikaBell commented on pages/wins/wins.html
> +				console.log(item)
I initially kept this as I thought it might help the person, assuming not me, who takes on the new issue I created (mentioned in my PR). As it logs the issue out. 

But I can remove it.

2021-04-24 03:28 UTC, erikaBell commented on pages/wins/wins.html
> +		getOtherIcon(badgeIcons)
The function is called and the return value is used at line 303:
`<img class="wins-badge-icon" alt="${badgeIcons[otherIcon]}" src="${SVG_FILE_PATH}${otherIcon}">`

2021-04-24 03:28 UTC, erikaBell commented on _sass/components/_wins-page.scss
> +    font-weight: normal !important;
Right, I agree it is generally bad practice. I can't with class so I went ahead and added a data-set attribute in my incoming changes and adjusted them that way.

2021-04-24 03:32 UTC, erikaBell commented on pages/wins/wins.html
> +				console.log(item)
I initially kept this as I thought it might help the person, assuming not me, who takes on the new issue I created (mentioned in PR), as it logs the issue out. But I went ahead and removed it from the incoming PR ~

2021-04-24 03:33 UTC, erikaBell commented
@akib regarding the overlay, Josh created a [separate issue](https://github.com/hackforla/website/issues/1425) for it, mentioned in the comments of the [original ticket](https://github.com/hackforla/website/issues/1313).

2021-04-24 03:45 UTC, erikaBell commented on pages/wins/wins.html
> +		insertIcons(cloneCardTemplate, card[win])
If you're talking specifically about the repetition of the HTML:  

`cloneCardTemplate.querySelector('.wins-icon-container').insertAdjacentHTML('beforeend',`
					`<div class='wins-item-container'>
					<img class="wins-badge-icon" alt="${badgeIcons[otherIcon]}" src="${SVG_FILE_PATH}${otherIcon}">
					<div class="wins-text-bubble" data-wins="font-styling">${item}</div>
				</div>`

I would be curious to talk with you, because earlier I had tried to create a dynamic variable to hold that HTML and call it in, but the output becomes this:

<details>
<summary>example</summary>

<img width="593" alt="Screen Shot 2021-04-23 at 8 41 32 PM" src="https://user-images.githubusercontent.com/67438372/115946233-b2ed7480-a474-11eb-873b-bc72ee2fda35.png">

</details>

2021-04-25 15:04 UTC, daniellex0 commented
It's still not working for me, unless I'm doing something wrong on my end (very likely!)..

<img width="350" alt="Screen Shot 2021-04-25 at 8 03 25 AM" src="https://user-images.githubusercontent.com/67400366/115998588-c3990a00-a59c-11eb-8f3f-6421e440abfc.png">

2021-04-25 16:20 UTC, jbubar requested changes
THis is awesome erika! everything looks really great for the most part
The 'see more...' seems to be in the wrong place in mobile'
<details>
    <summary>current</summary>

![Screen Shot 2021-04-25 at 9 11 53 AM](https://user-images.githubusercontent.com/53061723/116000811-94879600-a5a6-11eb-8062-2b23e50d65a6.png)


</details>
compared to 
<details>
    <summary>Figma</summary>

    
![Screen Shot 2021-04-25 at 9 12 13 AM](https://user-images.githubusercontent.com/53061723/116000807-8e91b500-a5a6-11eb-8e3f-650ef10360b6.png)


</details>

I think it might be because the position relative in the css of wins-card-text class is over written.. 

<details>
    <summary>screenshot of dev tools w position overwritten</summary>

![Screen Shot 2021-04-25 at 9 17 47 AM](https://user-images.githubusercontent.com/53061723/116000980-3a3b0500-a5a7-11eb-8706-983fabace2d8.png)


</details>

but i am not 100% sure

2021-04-25 16:22 UTC, jbubar commented
@daniellex0 could you show us a screen shot of your console?
That has happened to me before... but I forgot why.. lol
![Screen Shot 2021-04-25 at 9 21 42 AM](https://user-images.githubusercontent.com/53061723/116001098-bc2b2e00-a5a7-11eb-8586-875921ff9d61.png)

2021-04-25 20:01 UTC, closed without merging