Updated CSS to match COP page with figma design
hackforla/website pull request #1455
Opened 2021-04-24 20:26 UTC by Aveline-art

Fixes #1326 
Adjusted scss file to according to #1326 
[Current site, for reference](https://www.hackforla.org/communities-of-practice)
Updated site, below, in various resolutions

### Mobile Android

GalaxyS9 vertical (360x740)
<img src= "https://user-images.githubusercontent.com/62368440/115971637-6fd7e380-a4fe-11eb-96b3-16512f27638d.png" width="25%" height="25%" />

GalaxyS9 horizontal (740x360)
<img src= "https://user-images.githubusercontent.com/62368440/115971686-b2012500-a4fe-11eb-959c-96936529f6e6.png" width="50%" height="50%" />

### Mobile iphone

iphone6/7/8 Plus vertical (414x736)
<img src= "https://user-images.githubusercontent.com/62368440/115971764-276cf580-a4ff-11eb-9b09-54205c96d6d6.png" width="25%" height="25%" />

iphone6/7/8 Plus horizontal (736x414)
<img src= "https://user-images.githubusercontent.com/62368440/115971790-597e5780-a4ff-11eb-945b-a05971fc7a5f.png" width="50%" height="50%" />

### Tablet

ipad vertical (768x1024)
<img src= "https://user-images.githubusercontent.com/62368440/115971812-83d01500-a4ff-11eb-89dd-9da3921f0f10.png" width="40%" height="40%" />

ipad horizontal (1024x768)
<img src= "https://user-images.githubusercontent.com/62368440/115971847-b4b04a00-a4ff-11eb-88da-610f5703e88f.png" width="50%" height="50%" />

### Laptop

Laptop (1280x950)
<img src= "https://user-images.githubusercontent.com/62368440/115971883-f640f500-a4ff-11eb-9180-594b02ca0d65.png" width="50%" height="50%" />

Laptop HD (1920x1080)
<img src= "https://user-images.githubusercontent.com/62368440/115971892-12dd2d00-a500-11eb-9696-552ef8137636.png" width="50%" height="50%" />

<img src= "" width="50%" height="50%" />

2021-04-24 23:38 UTC, erikaBell approved these changes
Looks good to me. Will wait for @daniellex0 to look over it.

2021-04-25 15:19 UTC, daniellex0 requested changes
This looks really good!

Just a couple edits if possible:

- In desktop view, the slack icon in the slack blurb isn't aligned with the paragraph above it- I think a fix for this might be giving .alert-communities the property max-width: 450px (but make sure this looks good for all viewports etc)

- In mobile view: I'm sorry this wasn't in my original issue because I forgot, but would it be possible to add this? The paragraph in the header should be max-width 300px. Also this might mess up the alignment of the slack blurb on mobile, so can you please make sure it is still somewhat left-aligned with the paragraph?

Thank you!!

2021-04-26 20:26 UTC, Aveline-art commented
Thank you @daniellex0. Will add these changes and prettify the page!

2021-04-28 21:25 UTC, erikaBell commented
@Aveline-art just wanted to say, @ me and Danielle when this is ready for another review!

2021-04-30 02:40 UTC, Aveline-art commented
Updated!

@erikaBell  @daniellex0 

Note: I've also recently moved my directory to improve my docker performance. The commit changes seems to be correct, but please view a copy on your device to make sure that is the case!

iphone6/7/8 Plus vertical (414x736)
<img src= "https://user-images.githubusercontent.com/62368440/116641842-6b5a6300-a922-11eb-8200-37ac00d7dfdc.png" width="25%" height="25%" />

Laptop (1280x950)
<img src= "https://user-images.githubusercontent.com/62368440/116641888-80cf8d00-a922-11eb-8355-9838db0ae436.png" width="50%" height="50%" />

2021-04-30 07:47 UTC, daniellex0 approved these changes
Looks perrrfect, thank you for applying the requested changes so well!!

2021-04-30 16:38 UTC, erikaBell approved these changes
Looks good Ava (-:

2021-04-30 16:38 UTC, merged