Contributing.md changes
hackforla/website pull request #1471
Opened 2021-04-27 03:47 UTC by averdin2

Akib made updates to the Contributing md based on Roberta's suggestions from her document. 

We left off early on inClone the forked repository section.

2021-05-04 00:24 UTC, averdin2 commented
I made some updates based on Akib's changes to the Contributing file. Most of my changes were adding small things that were changed by Akib that I ultimately felt should still be present in the file, and made some wording changes.

In regards to issue #1390, there has still yet to be a decision made on if information for command line shells and text editors should be added to the wiki.

2021-05-05 01:55 UTC, jbubar approved these changes
Looks great. one small typo. Really fantastic changes

2021-05-05 01:55 UTC, jbubar commented on CONTRIBUTING.md
> +      <summary><i>If you accidentally cloned using the repository URL from the HackForLA Github (instead of the fork on your Github)</i>
smart!

2021-05-05 01:55 UTC, jbubar commented on CONTRIBUTING.md
> +   <sub>*No law of physics will break if you don't adhere to this scheme, but laws of git will break if you add spaces.*</sub>
😹😻

2021-05-05 01:55 UTC, jbubar commented on CONTRIBUTING.md
> +      This command saves your work, and prepares it to push to your repository.  Use the `-m` flag to quickly add a message to your commit. Your message should be a short description of the issue you
small typo here.. 'reisst the temptation'

2021-05-05 01:55 UTC, jbubar commented on CONTRIBUTING.md
> +        git push
should we expand here? that if it is your first time pushing from this branch, it will ask you to set upstream??

2021-05-05 01:56 UTC, jbubar commented on CONTRIBUTING.md
> +   <sub>*No law of physics will break if you don't adhere to this scheme, but laws of git will break if you add spaces.*</sub>
love it

2021-05-09 15:42 UTC, averdin2 commented on CONTRIBUTING.md
> +        git push
Yes, I think that should still be in there. 👍

2021-06-06 09:19 UTC, jbubar commented
@averdin2 I went through and tried my best to resolve the merge conflicts. Will you take a look and merge if you like?

2021-06-10 18:17 UTC, alyssabenipayo commented on CONTRIBUTING.md
> +   - Use the `git add` command to stage your changes.
<strike> `git add .`

(Missing the "." to specify which content to add.) </strike>

Nevermind. Just read the next lines. 😂

2021-06-10 18:24 UTC, alyssabenipayo commented on CONTRIBUTING.md
> +      get out of sync with this (upstream) repository from time to time.  (That's what has happend when you see something like "This branch is 1 commit behind hackforla:gh-pages" on the github websit
Typo here - That's what has _happened_

2021-06-10 18:45 UTC, alyssabenipayo commented on CONTRIBUTING.md
> +<p align="center"><i><b>NOTE</b>: After you completed your assignment and committed all of the changes, before moving onto your next issue and creating a new branch, you must leave your current branc
Should we also add a line where they delete the branch they worked on after returning to the `gh-pages`?

Also, rephrase suggestion (added an extra line on how to delete a branch):

<p align="center"><i><b>NOTE</b>: After completing your assignment and committing all of the changes, you must leave your current branch and return to the `gh-pages` branch. The commands to delete your current branch are as follows:

```bash
git checkout `gh-pages`
git branch -d fix-logo-width-311
```
Now you can move on to your next issue and create a new branch. This ensures you don’t accidentally include the changes from your previous branch in your new branch) </i></p>

2021-06-10 18:52 UTC, alyssabenipayo commented on CONTRIBUTING.md
> +Run `git checkout gh-pages` to return to the `gh-pages` branch:
I just read this line. Adding a comment here as a gentle reminder that we still have this line - whether we change it or not depends on what we decide on the previous comment. 🙌

2021-06-10 18:57 UTC, alyssabenipayo requested changes
Hi Team! Just finished reviewing. This update is very well done! I added a few suggestions. We could all discuss together if needed as well. 

Other than that, It looks good to go. Thanks and great job! 🎉🎉🎉

2021-06-11 02:09 UTC, akibrhast commented on CONTRIBUTING.md
> +<p align="center"><i><b>NOTE</b>: After you completed your assignment and committed all of the changes, before moving onto your next issue and creating a new branch, you must leave your current branc
I am in favor of the comment made by @alyssabenipayo above

2021-06-13 17:35 UTC, jbubar commented
@alyssa could you look over it again? Thanks so much for your review!

2021-06-13 23:40 UTC, alyssabenipayo commented on CONTRIBUTING.md
> +   - Use the `git status` command to see what files are staged
Just need to add a "." at the end of this line.

2021-06-13 23:47 UTC, arghmatey commented on CONTRIBUTING.md
> +* [Get started with Docker](https://docs.docker.com/get-docker/)
This should redirect to the getting started page, so link should be `https://docs.docker.com/get-started/`

2021-06-13 23:47 UTC, arghmatey commented on CONTRIBUTING.md
> +<summary>Docker Installation Troubleshooting</summary>
Should this include how to troubleshoot new changes not appearing in when running docker? It was discussed in [this slack thread](https://hackforla.slack.com/archives/C4UM52W93/p1622664961060700?thread_ts=1622662540.048300&cid=C4UM52W93), but that information may be going on another wiki.

2021-06-13 23:51 UTC, alyssabenipayo commented on CONTRIBUTING.md
> +      This command will list the files that have been staged.  These are the files that will be committed (saved) when you run the next command, `git commit`. Please be sure all your staged changes a
This line makes sense when read out loud, but there's still something off about it. (Any thoughts?)

`If you find you have included unrelated changes, please unstage them before making this commit - and then make a new commit for the unrelated changes.`

Suggestion: If you have included unrelated changes, please unstage them before making this commit. Then make a new commit for the unrelated changes.

2021-06-14 00:01 UTC, alyssabenipayo requested changes
Hello! Just finished revewing the request again. Added a couple more suggestions! 

After this, it should be okay. 

If anything, I don't mind looking it over again till we all feel ready to merge the changes.

2021-06-14 00:11 UTC, arghmatey requested changes

2021-06-14 00:11 UTC, arghmatey commented on CONTRIBUTING.md
> +   *(do this anytime Docker or jekyll configuration or other repository settings change)*
Should this include how to troubleshoot new changes not appearing when running docker? It was discussed in [this slack thread](https://hackforla.slack.com/archives/C4UM52W93/p1622664961060700?thread_ts=1622662540.048300&cid=C4UM52W93), but that information may be going on another wiki.

2021-06-14 00:11 UTC, arghmatey commented on CONTRIBUTING.md
> +* [Get started with Docker](https://docs.docker.com/get-docker/)
`Get started with Docker` should redirect to the getting started page, so link should be `https://docs.docker.com/get-started/`

2021-06-18 17:24 UTC, jbubar commented
@akibrhast @arghmatey @alyssabenipayo I went in anded those changes you suggested. but I did it through the resolved conflicts functionality on github.. so it does not show up. I saw akibs new update to the document, so... this might be obsolete. but I think it need one more read through before it is merged

2021-06-18 17:25 UTC, jbubar commented on CONTRIBUTING.md
> +** If you do not see the changes you applied when you run `docker-compose up`, delete `_site` directory and `.jekyll-metadata` file and restart docker. This will force docker to rebuild the whole sit
added it here

2021-06-18 17:26 UTC, jbubar commented on CONTRIBUTING.md
> +* [Get started with Docker](https://docs.docker.com/get-started/)
and here

2021-06-18 17:28 UTC, jbubar commented
also anyone can make these changes I have been making. I have been doing it all in the github ui. I jumped in because nothing was getting done on it a bit ago and there were merge conflicts

2021-06-19 01:17 UTC, alyssabenipayo reviewed
The updates look good! (Going to review it again)

2021-06-19 01:28 UTC, alyssabenipayo commented on CONTRIBUTING.md
> +   - Use the `git status` command to see what files are staged
Update: Added the period

2021-06-19 01:30 UTC, alyssabenipayo commented on CONTRIBUTING.md
> +      This command will list the files that have been staged.  These are the files that will be committed (saved) when you run the next command, `git commit`. Please be sure all your staged changes a
Please disregard my comment above. I think reads fine after revisiting it.

2021-06-19 01:47 UTC, alyssabenipayo approved these changes
Reviewed again and made changes. Looks good.

2021-06-19 02:05 UTC, akibrhast approved these changes
LGTM!

2021-06-19 02:08 UTC, merged

2021-06-19 02:33 UTC, arghmatey commented
Wasn't able to approve before merge, but thanks for adding those changes in @jbubar !