Adjust toolkit page
hackforla/website pull request #1484
Opened 2021-04-28 03:54 UTC by evancchen

Fixes #1463

2021-04-28 04:32 UTC, erikaBell commented on _sass/components/_toolkit.scss
> +                color: $color-mediumvioletred;
Overall, changes look good! Just want to confirm with @daniellex0  if this is supposed to be _pink_ instead of _mediumvioletred_?

Basing this question of off Danielle's comment in the issue:

- "Make the default selected filter All - so when you arrive at the page, All should be pink and bolded"

My one other comment, @evancchen would be to please show before and after photos so it's easier for the review to know what changes to look for on the local site. Thanks ~

2021-04-28 08:02 UTC, daniellex0 commented on _sass/components/_toolkit.scss
> +                color: $color-mediumvioletred;
Yes, good catch @erikaBell - @evancchen please change $color-mediumvioletred to $color-red here (I know it's called red but it's actually pink, it's confusing..!)

And agreed, screenshots would be great next time!

2021-04-28 08:04 UTC, daniellex0 commented
This looks great Evan! Just make the variable change @erikaBell mentioned above and this should be good to go 👍

2021-04-28 21:17 UTC, erikaBell requested changes
Change color of `.selected-category` — use comments above for reference.

2021-05-02 16:12 UTC, erikaBell approved these changes
Thanks Evan. looks good.

2021-05-02 16:12 UTC, merged