cards aligned as the design
hackforla/website pull request #1492
Opened 2021-04-29 19:00 UTC by danyc23

The cards are now like Figma mockups.

- Before:
![Screen Shot 2021-04-29 at 11 59 04 AM](https://user-images.githubusercontent.com/42159475/116603997-71c8ea80-a8e2-11eb-8226-f2a1df6dfabe.png)

- After:
![Screen Shot 2021-04-29 at 11 56 37 AM](https://user-images.githubusercontent.com/42159475/116603780-2ca4b880-a8e2-11eb-9999-a4262d87fb04.png)

2021-04-30 18:18 UTC, erikaBell commented
@danyc23 which issue does this close?

2021-04-30 18:34 UTC, danyc23 commented
> @danyc23 which issue does this close?
 Hey Erika, just added the issue number to the PR description

2021-04-30 22:01 UTC, averdin2 requested changes, later dismissed
@danyc23 Just fix some of these, and we'll run some questions by the design team to see what they think about adding some extra px to some of the styles.

2021-04-30 22:01 UTC, averdin2 commented on _sass/components/_program-areas.scss
> +    height: 129px;
@danyc23 As per the Figma design, let's leave the width at 92px and height at 120px for now. I see the issues you ran into with text overflowing the cards, but I have some suggestions. I do think the cards may look a little cramped, but let's discuss potential changes with @daniellex0 and the design team before changing this.

2021-04-30 22:01 UTC, averdin2 commented on _sass/components/_program-areas.scss
> +    margin: 10px 20px 10px 0px;
The design document has 26px of space between these mini cards, so let's make the margin: 13px 26px 13px and 0px to meet that requirement.

2021-04-30 22:01 UTC, averdin2 commented on _sass/components/_program-areas.scss
> +    font-size: 13px;
After line 156, adding a line spacing style (line-spacing: 15.23px;) will alleviate some of the text-overflow you were seeing.

2021-04-30 22:01 UTC, averdin2 commented on _sass/components/_program-areas.scss
> +        margin-bottom: 3.5px;
I understand where you were coming from adding some margin to the bottom of the mini card image so that the text isn't so cramped, but this is also causing some of the text-overflow. Let's again run this change by @daniellex0 and the design team. Btw @danyc23 good work on this issue 👍, the alignment of the mini cards looks great!

2021-05-02 01:52 UTC, danyc23 commented on _sass/components/_program-areas.scss
> +        margin-bottom: 3.5px;
Hey, thanks for the observations! I applied that 3.5 px margin because the title will be too close to the image and doesn't look like the Figma document and to avoid the overflow I increased the size of the card. I am going to make the changes and let's see if @daniellex0 has some suggestions. Thanks, Alex!

2021-05-02 01:55 UTC, danyc23 commented on _sass/components/_program-areas.scss
> +    font-size: 13px;
That suggestion really helped! Thanks!!

2021-05-02 16:14 UTC, daniellex0 commented on _sass/components/_program-areas.scss
> +        margin-bottom: 3.5px;
@averdin2 @danyc23 I'll check and add any suggestions right after the meeting if that's ok!

2021-05-04 06:11 UTC, daniellex0 commented on _sass/components/_program-areas.scss
> +        margin-bottom: 3.5px;
@averdin2 @danyc23 Sorry about the delay, finally got to this- yeah I think this is a good solution! If we need to make any design changes to the cards we can do that later on, but for now this is definitely a good way to fit all the words in- thanks for figuring this out Daniel!

2021-05-04 22:30 UTC, averdin2 commented
Please do not merge this PR until I re-review. Thanks 😄

2021-05-05 02:53 UTC, Lol-Whut approved these changes
Looks great! :)

2021-05-05 02:57 UTC, Lol-Whut requested changes, later dismissed
@danyc23 actually, we need to add back the hfla-donate.gif that got deleted :0 thank youuuu!! (if you need help, contact @jbubar)

2021-05-07 02:28 UTC, danyc23 commented
> @danyc23 actually, we need to add back the hfla-donate.gif that got deleted :0 thank youuuu!! (if you need help, contact @jbubar)

I added the gift back. Thanks

2021-05-07 20:05 UTC, qiqicodes approved these changes
lgtm

2021-05-07 20:13 UTC, averdin2 approved these changes
@danyc23 Awesome Job! 🔥

2021-05-07 20:14 UTC, merged