Updated Expunge Assist Project Profile
hackforla/website pull request #1493
Opened 2021-04-29 20:59 UTC by pascuas

Closes #1249

2021-04-30 18:14 UTC, erikaBell reviewed
Things look good overall ~ @pascuas moving forward, please attach 'before' and 'after' photos on your pull requests (-: this makes it easier for reviewers to know what we are looking for. 

@averdin2 @jbubar I'm noticing two things on @pascuas's branch, I'm not exactly sure why it's occurring. Curious if you guys think these bugs should be created into a new issue OR if it is something that should be done on this branch?

<details>
<summary>Issue 1: image height on main page</summary>

<img width="924" alt="Screen Shot 2021-04-30 at 10 48 16 AM" src="https://user-images.githubusercontent.com/67438372/116736396-af8e4780-a9a4-11eb-95ea-a229f03b1add.png">

</details>

<details>
<summary>Issue 2: project title appearing twice</summary>

<img width="959" alt="Screen Shot 2021-04-30 at 10 50 01 AM" src="https://user-images.githubusercontent.com/67438372/116736412-b74dec00-a9a4-11eb-8ecf-2484b97b5ecf.png">

vs 

<img width="872" alt="Screen Shot 2021-04-30 at 10 50 08 AM" src="https://user-images.githubusercontent.com/67438372/116736451-c2088100-a9a4-11eb-9a44-9ba2c94118a3.png">

</details>

2021-04-30 23:58 UTC, averdin2 commented
@erikaBell 
Regarding issue 1; This is a result of the image not being sized properly. This is an issue for design and should be made a new issue. 
Regarding issue 2; Again, I think this is a question for design on whether that title should be in the image or not.
I think that both of these can be made into the same issue for the design team.

2021-05-01 00:06 UTC, averdin2 requested changes
@pascuas Good job on this PR. I think this one was a little more complicated than a good first issue, but you did great. Just make some of the changes I recommended and you should be good to go. Feel free to reach out to me on Slack if you are confused about any of the changes I requested.

2021-05-01 00:06 UTC, averdin2 commented on _projects/civic-tech-structure.md
> +    url: "https://cfa.slack.com/archives/C019RCM15FE"
@pascuas I am not sure if you accidentally made these changes or if something came in from a merge, but I am pretty sure these changes are unrelated to this issue and I actually think they are wrong. There are a couple of ways to remove this file from the PR, but my suggestion is to just copy the same file from the website repo and paste that into this branch and push those changes. That should fix the file.

2021-05-01 00:06 UTC, averdin2 commented on _projects/record-clearance-project.md
>  ---
Regarding the record-clearance-project.md file, I think that the name should probably be changed to expunge-assist.md. @jbubar @erikaBell what do you think?

2021-05-01 00:06 UTC, averdin2 commented on _projects/record-clearance-project.md
> -alt: 'Record clearance project logo'
I believe that record-clearance.jpg and record-clearance-hero.png files should also be removed.

2021-05-02 15:45 UTC, pascuas commented on _projects/civic-tech-structure.md
> +    url: "https://cfa.slack.com/archives/C019RCM15FE"
@averdin2 made the requested changes.

2021-05-02 16:16 UTC, erikaBell approved these changes
Looks good.


Will make issue regarding the earlier, resolved, comments.

2021-05-02 16:17 UTC, merged