chevron bug on About page #1481
hackforla/website pull request #1514
Opened 2021-05-05 03:47 UTC by josiehandeveloper

https://user-images.githubusercontent.com/63170710/117094818-ac36eb00-ad19-11eb-9da3-0bb6287819b7.mov

fixes #1481

2021-05-05 07:47 UTC, akibrhast requested changes

2021-05-05 07:47 UTC, akibrhast commented on assets/js/about.js
> +    console.log("window width less")
remove console log please

2021-05-05 07:47 UTC, akibrhast commented on assets/js/about.js
> +    console.log("window width greater");
remove console log please

2021-05-05 07:47 UTC, akibrhast commented on assets/js/about.js
> +
If `new code` works please delete `complicated old code` from the file instead of just commenting it out

2021-05-05 21:45 UTC, josiehandeveloper commented
![Screen Shot 2021-05-05 at 2 43 09 PM (2)](https://user-images.githubusercontent.com/63170710/117213395-6bd67c00-adb0-11eb-9237-7832dc5a43b7.png)
console.logs removed
![Screen Shot 2021-05-05 at 2 44 21 PM (2)](https://user-images.githubusercontent.com/63170710/117213463-7e50b580-adb0-11eb-9c28-c30a468100f0.png)
Commented code deleted

2021-05-06 11:15 UTC, akibrhast approved these changes
lgtm. Nice work on refactoring out old complicated code! 👍

2021-05-06 11:16 UTC, merged