Update Engage project profile
hackforla/website pull request #1603
Opened 2021-05-22 15:56 UTC by glenflorendo

- Update project details on Engage project page
- Update meeting times in VRMS
- Import two new images to replace photo in the project page and the hero image in the Engage project page

Resolves: #1031
See also: #1033

![Screenshot_2021-05-22 Engage by Hack for LA](https://user-images.githubusercontent.com/9373317/119232747-3b465000-badb-11eb-8fa8-ba5dd292f94e.png)
![Screenshot_2021-05-22 Hack for LA](https://user-images.githubusercontent.com/9373317/119232751-3da8aa00-badb-11eb-97f4-685c64f35560.png)

2021-05-23 01:19 UTC, qiqicodes commented on _projects/engage.md
> +alt: 'Engage logo.'
Is the illustration also part of the Engage logo? if not, we should elaborate on the alt text for this image.

2021-05-23 01:20 UTC, qiqicodes commented on _projects/engage.md
> +vertical: 'Citizen Engagement'
a recent Merged PR changed the `vertical` to `program area`, please change accordingly.

2021-05-23 01:22 UTC, qiqicodes commented on _projects/engage.md
>  alt-hero: 'Neon sign for the Santa Monica pier. Palm trees and sunset in the background.'
Is the illustration also part of the Engage logo? if not, we should elaborate on the alt text for this image.

2021-05-23 01:23 UTC, qiqicodes requested changes
Please do the following:
- [ ] edit the alt text for engage-hero-2.png
- [ ] change the  `vertical` to `program area`.

2021-05-28 07:35 UTC, glenflorendo commented
On hold. Pending alternative hero image from Engage team.

2021-06-06 18:54 UTC, jbubar reviewed
Hey Glen, So sorry about the insane delay on this issue. 
everything looks good. The Test Site, and Site links are broken... but this is not your fault.
I think we should merge this. Ill write a message on the original issue asking for an updated site link

2021-06-06 19:16 UTC, glenflorendo commented
> Hey Glen, So sorry about the insane delay on this issue.
> everything looks good. The Test Site, and Site links are broken... but this is not your fault.
> I think we should merge this. Ill write a message on the original issue asking for an updated site link

Hey @jbubar . Thanks for reviewing! I think the links are working, but there's something going on with the certs with the sites. I think you can bypass the screen by going through `Advanced` and continuing from there.

2021-06-09 01:19 UTC, merged