Standardize events mobile
hackforla/website pull request #1609
Opened 2021-05-23 05:24 UTC by Aveline-art

Fixes #1595 

- Adjusted Font-size of event header titles (specifically white text of string, "our events" and "our location") for mobile and tablet
- Adjusted top margin of event header titles for mobile

before mobile (iphone 6)
<img src="https://user-images.githubusercontent.com/62368440/119249231-c8c18880-bb4b-11eb-9c7f-8e1424e5141d.png" width="300px" height="600px" />

after mobile (iphone 6)
<img src="https://user-images.githubusercontent.com/62368440/119249229-c7905b80-bb4b-11eb-8a9c-88b3d17f6397.png" width="300px" height="600px" />

before tablet (ipad)
<img src="https://user-images.githubusercontent.com/62368440/119249232-c95a1f00-bb4b-11eb-9650-8b2d54e3658f.png" width="450px" height="600px" />

after tablet (ipad)
<img src="https://user-images.githubusercontent.com/62368440/119249238-cd863c80-bb4b-11eb-9a39-2f4ae2ba9447.png" width="450px" height="600px" />

2021-05-29 18:34 UTC, erikaBell reviewed
Hey @Aveline-art ~ just a friendly reminder to assign "reviewers" to your PR requests (-: 

So this looks good overall. My initial thought is that @daniellex0's request of ensuring `margin: 44px` in mobile view meant also removing the extra padding and general space being applied? @daniellex0 please let me know if I'm wrong about this. 

What I mean is: 

<details>
<summary>Ava's Branch, margin-top: 44px + extra padding/spacing</summary>

<img width="307" alt="Screen Shot 2021-05-29 at 11 20 58 AM" src="https://user-images.githubusercontent.com/67438372/120081199-34868280-c071-11eb-9279-f4bafd6db1e4.png">
</details>

<details>
<summary>Ava's Branch with some extra edits via devtools, purely margin-top: 44px </summary>

<img width="305" alt="Screen Shot 2021-05-29 at 11 20 44 AM" src="https://user-images.githubusercontent.com/67438372/120081213-51bb5100-c071-11eb-9d46-ec0fde5a2ef7.png">
</details>

I personally found the extra spacing coming from `min-height: 100vh` and `padding-top` under `<section class="events-page content-section content-section--events">`

2021-05-30 06:40 UTC, Aveline-art commented
@erikaBell Thank you! 😄

2021-06-02 07:56 UTC, daniellex0 requested changes
@Aveline-art @erikaBell So sorry about the delayed response y'all- yes that's exactly right @erikaBell thank you for catching that! Really sorry @Aveline-art , as always I could have been a little more clear! 

To match the design system guidelines, the spacing between the header and the "our Events" sub-heading below it should be 44px total. However we definitely want to keep the automatic 32px padding that is in there because of the standard ".content-section" class (which will probably need to be changed to 44px in mobile down the line tbh...).. but in the meantime is it possible to mess with the other margins to make the total add up to about 44px?

2021-06-04 02:21 UTC, Aveline-art commented on _sass/components/_events.scss
> +}
@daniellex0 I've managed to make the changes, but I had to override the 32px padding from '.content-section' through a very specific css selector, as shown. Is this acceptable?

Another option would be to use an equally specific css selector to select the first heading (the one titled 'Our Events') and setting the top padding to 12px (or 44px-32px).

<img src="https://user-images.githubusercontent.com/62368440/120736133-8d568080-c4a0-11eb-8d6c-7e6d27be3a8b.png" width="50%" length="50%" />

2021-06-06 05:16 UTC, daniellex0 commented on _sass/components/_events.scss
> +}
> Another option would be to use an equally specific css selector to select the first heading (the one titled 'Our Events') and set its top padding to 12px (or 44px-32px).

This option would be better if possible! Sorry to be so nit-picky but I'm trying to make all of the pages as standard as possible so that when new developers look at any page, if they follow its example they're likely to be following the design system.. Thank you!!

2021-06-09 01:57 UTC, jbubar approved these changes

2021-06-09 04:34 UTC, Aveline-art commented on _sass/components/_events.scss
> +}
Hi @daniellex0 ! I have made the changes as requested by using an alternate selector. No image provided, because it is visually the same as the last one. Please let me know if you have any additional concerns before approving and merging this PR. Thank you!

<details>
<summary>Last one.</summary>
<br>
<img src="https://user-images.githubusercontent.com/62368440/120736133-8d568080-c4a0-11eb-8d6c-7e6d27be3a8b.png" width="50%" length="50%" />
</details>

2021-06-11 03:34 UTC, daniellex0 approved these changes
Approved, thanks @Aveline-art ! 💯

2021-06-11 03:34 UTC, daniellex0 commented on _sass/components/_events.scss
> +}
@Aveline-art sounds great!

2021-06-11 13:46 UTC, merged