Standardize About page header and body in mobile
hackforla/website pull request #1624
Opened 2021-05-24 02:24 UTC by erikaBell

Fixes #1605 

<details>
<summary>Before & After: 1</summary>

<img width="307" alt="Screen Shot 2021-05-23 at 7 22 09 PM" src="https://user-images.githubusercontent.com/67438372/119287867-4e047600-bbfc-11eb-8ae1-105403a09adb.png">

<img width="303" alt="Screen Shot 2021-05-23 at 7 22 16 PM" src="https://user-images.githubusercontent.com/67438372/119287871-50ff6680-bbfc-11eb-8ea2-aede7d9f21b2.png">

</details>

<details>
<summary>Before & After: 2</summary>

<img width="305" alt="Screen Shot 2021-05-23 at 7 22 26 PM" src="https://user-images.githubusercontent.com/67438372/119287899-5d83bf00-bbfc-11eb-9d04-da1344b215fc.png">

<img width="306" alt="Screen Shot 2021-05-23 at 7 22 41 PM" src="https://user-images.githubusercontent.com/67438372/119287907-5fe61900-bbfc-11eb-9ac6-e12dd7f3b886.png">

</details>

2021-05-25 22:15 UTC, averdin2 commented
@daniellex0 The issue specifies that the text font size for the About header be 16px, but this seems a bit small to me. The Figma file has it at 24px and that looks better to me. Should it be 24px instead of 16px? Also, @erikaBell what do you think?

2021-05-25 22:31 UTC, daniellex0 commented
@averdin2 Yes I'm so sorry, I wrote that in a really confusing way- I meant that the paragraph text in the header should be 16px, not the heading- sorry about that!! The "About" heading text should stay 32px. I should have included an image of how it should look for reference, my bad!!

2021-05-25 22:38 UTC, daniellex0 requested changes

2021-05-25 22:38 UTC, daniellex0 commented on _sass/components/_about.scss
> +    font-size: 1rem; // equal to 16px
2rem instead of 1rem, sorry about the confusion

2021-05-25 23:25 UTC, averdin2 requested changes
@erikaBell Good job on this issue. I found that around lines 604 to 614, this seems like the best place (code readability wise) in the _about.scss file to actually place the code you wrote. 

I also noticed that the first part of the fourth action item on the issue to "Figure out why '.page-content-container-grid' class is adding extra margin below the header illustration" wasn't completed. I think removing margin-top: 20px on line 51 might be the solution.

2021-05-25 23:56 UTC, erikaBell commented
Ah, good catch on the header margin @averdin2, had missed that when reading through the fixes. 

I went ahead and moved some of the code up to where you suggested, the rest of it I had to keep below in order for it to work, due to the hierarchy of the CSS structure.

I believe everything should be good now? Lmk!

2021-05-28 09:28 UTC, daniellex0 requested changes
This looks really great, thank you so much @erikaBell !! And thanks for the catches as always @averdin2 !

Ok so the only small change is that when margin-bottom: 36px is added, it looks like it adds the 36px margin below each paragraph- but it's only supposed to be 36px below the bottom paragraph and above the illustration (the margin between the two paragraphs should just stay the automatic one that comes with the <p> tags). I think the solution for this might be to remove the margin-bottom: 36px from .header-text--about-us, and instead put both of the <p>'s with class "header-text--about-us" in a div with its own margin-bottom:36px property? Is that too many layers? 

Anyhow you can decide however you think is best to solve it..! Let me know if any of this doesn't make sense. And sorry that I left these specifications out! This is just what happens when I get lazy and don't add an annotated image lmaoo

2021-05-28 18:13 UTC, erikaBell commented
@daniellex0 good catch ~ I believe it's all in order now (-: again, just lmk

2021-06-02 07:41 UTC, daniellex0 approved these changes
I'm so sorry about the delay- this looks perfect, thank you! 🥇

2021-06-02 19:11 UTC, erikaBell commented
@averdin2 Can't merge this myself, so reaching out to you.

2021-06-03 18:43 UTC, averdin2 approved these changes
@erikaBell These changes look good to me. Great job! I will merge 👍

2021-06-03 18:44 UTC, merged