Footer project section 1427
hackforla/website pull request #1677
Opened 2021-06-01 01:54 UTC by GLRJr

Added the footer to the project section, but it needs approval from design team because not exactly like figma.

Before I pushed I checked upstream and I had to fix merge conflicts, the CONTRIBUTION documentation for section 7a should to have a step added on what to do after merges are fixed because they are unclear.

Also, do we delete, branches after they are merged?  because in the contribution section doesn't have anything after completing a push.

2021-06-06 15:18 UTC, akibrhast commented
Hey @GLRJr I am getting the following errors, when I checkout your pr and try to run it locally. Could you please delete your `_site` directory and `jekyll-metadata` file and see/fix the issue on your end.

<details>
<summary>Error Message</summary>

```bash
C:\Users\akibr\Desktop\SpringBoardProjects\website>docker compose up
[+] Running 2/2
 - Network website_default  Created                                                        0.0s
 - Container hfla_site      Created                                                        0.8s
Attaching to hfla_site
hfla_site  | ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux-musl]
hfla_site  | Configuration file: _config.yml
hfla_site  | Configuration file: _config.docker.yml
hfla_site  |             Source: .
hfla_site  |        Destination: /srv/jekyll/_site
hfla_site  |  Incremental build: enabled
hfla_site  |       Generating... 
hfla_site  | jekyll 3.9.0 | Error:  Invalid CSS after "}": expected "}", was "" on line 208
hfla_site  |   Conversion error: Jekyll::Converters::Scss encountered an error while converting 
'assets/css/main.scss':
hfla_site  |                     Invalid CSS after "}": expected "}", was "" on line 208        
hfla_site  | /usr/gem/gems/jekyll-sass-converter-1.5.2/lib/jekyll/converters/scss.rb:123:in `rescue in convert': Invalid CSS after "}": expected "}", was "" on line 208 (Jekyll::Converters::Scss::SyntaxError)
hfla_site  |    from /usr/gem/gems/jekyll-sass-converter-1.5.2/lib/jekyll/converters/scss.rb:118:in `convert'
hfla_site  |    from /usr/gem/gems/jekyll-3.9.0/lib/jekyll/renderer.rb:101:in `block in convert'hfla_site  |    from /usr/gem/gems/jekyll-3.9.0/lib/jekyll/renderer.rb:99:in `each'
hfla_site  |    from /usr/gem/gems/jekyll-3.9.0/lib/jekyll/renderer.rb:99:in `reduce'
hfla_site  |    from /usr/gem/gems/jekyll-3.9.0/lib/jekyll/renderer.rb:99:in `convert'
hfla_site  |    from /usr/gem/gems/jekyll-3.9.0/lib/jekyll/renderer.rb:83:in `render_document'  
hfla_site  |    from /usr/gem/gems/jekyll-3.9.0/lib/jekyll/renderer.rb:62:in `run'
hfla_site  |    from /usr/gem/gems/jekyll-3.9.0/lib/jekyll/site.rb:479:in `render_regenerated'  
hfla_site  |    from /usr/gem/gems/jekyll-3.9.0/lib/jekyll/site.rb:472:in `block in render_pages'
hfla_site  |    from /usr/gem/gems/jekyll-3.9.0/lib/jekyll/site.rb:471:in `each'
hfla_site  |    from /usr/gem/gems/jekyll-3.9.0/lib/jekyll/site.rb:471:in `render_pages'        
hfla_site  |    from /usr/gem/gems/jekyll-3.9.0/lib/jekyll/site.rb:192:in `render'
hfla_site  |    from /usr/gem/gems/jekyll-3.9.0/lib/jekyll/site.rb:71:in `process'
hfla_site  |    from /usr/gem/gems/jekyll-3.9.0/lib/jekyll/command.rb:28:in `process_site'      
hfla_site  |    from /usr/gem/gems/jekyll-3.9.0/lib/jekyll/commands/build.rb:65:in `build'      
hfla_site  |    from /usr/gem/gems/jekyll-3.9.0/lib/jekyll/commands/build.rb:36:in `process'    
hfla_site  |    from /usr/gem/gems/jekyll-3.9.0/lib/jekyll/commands/serve.rb:93:in `block in start'
hfla_site  |    from /usr/gem/gems/jekyll-3.9.0/lib/jekyll/commands/serve.rb:93:in `each'       
hfla_site  |    from /usr/gem/gems/jekyll-3.9.0/lib/jekyll/commands/serve.rb:93:in `start'      
hfla_site  |    from /usr/gem/gems/jekyll-3.9.0/lib/jekyll/commands/serve.rb:75:in `block (2 levels) in init_with_program'
hfla_site  |    from /usr/gem/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
hfla_site  |    from /usr/gem/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'       
hfla_site  |    from /usr/gem/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'    
hfla_site  |    from /usr/gem/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
hfla_site  |    from /usr/gem/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
hfla_site  |    from /usr/gem/gems/jekyll-3.9.0/exe/jekyll:15:in `<top (required)>'
hfla_site  |    from /usr/gem/bin/jekyll:23:in `load'
hfla_site  |    from /usr/gem/bin/jekyll:23:in `<main>'
hfla_site  | /srv/jekyll/_sass/components/_program-areas.scss:208: Invalid CSS after "}": expected "}", was "" (Sass::SyntaxError)
hfla_site  |    from /srv/jekyll/_sass/main.scss:58
hfla_site  |    from (sass):3
hfla_site  |    from /usr/gem/gems/sass-3.7.4/lib/sass/scss/parser.rb:1308:in `expected'        
hfla_site  |    from /usr/gem/gems/sass-3.7.4/lib/sass/scss/parser.rb:1238:in `expected'        
hfla_site  |    from /usr/gem/gems/sass-3.7.4/lib/sass/scss/parser.rb:1233:in `tok!'
hfla_site  |    from /usr/gem/gems/sass-3.7.4/lib/sass/scss/parser.rb:690:in `block'
hfla_site  |    from /usr/gem/gems/sass-3.7.4/lib/sass/scss/parser.rb:681:in `ruleset'
hfla_site  |    from /usr/gem/gems/sass-3.7.4/lib/sass/scss/parser.rb:707:in `block_child'      
hfla_site  |    from /usr/gem/gems/sass-3.7.4/lib/sass/scss/parser.rb:700:in `block_contents'   
hfla_site  |    from /usr/gem/gems/sass-3.7.4/lib/sass/scss/parser.rb:137:in `stylesheet'       
hfla_site  |    from /usr/gem/gems/sass-3.7.4/lib/sass/scss/parser.rb:41:in `parse'
hfla_site  |    from /usr/gem/gems/sass-3.7.4/lib/sass/engine.rb:414:in `_to_tree'
hfla_site  |    from /usr/gem/gems/sass-3.7.4/lib/sass/engine.rb:321:in `to_tree'
hfla_site  |    from /usr/gem/gems/sass-3.7.4/lib/sass/tree/visitors/perform.rb:323:in `block in visit_import'
hfla_site  |    from /usr/gem/gems/sass-3.7.4/lib/sass/stack.rb:88:in `block in with_import'    
hfla_site  |    from /usr/gem/gems/sass-3.7.4/lib/sass/stack.rb:135:in `with_frame'
hfla_site  |    from /usr/gem/gems/sass-3.7.4/lib/sass/stack.rb:88:in `with_import'
hfla_site  |    from /usr/gem/gems/sass-3.7.4/lib/sass/tree/visitors/perform.rb:322:in `visit_import'
hfla_site  |    from /usr/gem/gems/sass-3.7.4/lib/sass/tree/visitors/base.rb:36:in `visit'      
hfla_site  |    from /usr/gem/gems/sass-3.7.4/lib/sass/tree/visitors/perform.rb:158:in `block in visit'
hfla_site  |    from /usr/gem/gems/sass-3.7.4/lib/sass/stack.rb:79:in `block in with_base'      
hfla_site  |    from /usr/gem/gems/sass-3.7.4/lib/sass/stack.rb:135:in `with_frame'
hfla_site  |    from /usr/gem/gems/sass-3.7.4/lib/sass/stack.rb:79:in `with_base'
hfla_site  |    from /usr/gem/gems/sass-3.7.4/lib/sass/tree/visitors/perform.rb:158:in `visit'  
hfla_site  |    from /usr/gem/gems/sass-3.7.4/lib/sass/tree/visitors/perform.rb:325:in `block (2 levels) in visit_import'
hfla_site  |    from /usr/gem/gems/sass-3.7.4/lib/sass/tree/visitors/perform.rb:325:in `map'    
hfla_site  |    from /usr/gem/gems/sass-3.7.4/lib/sass/tree/visitors/perform.rb:325:in `block in visit_import'
hfla_site  |    from /usr/gem/gems/sass-3.7.4/lib/sass/stack.rb:88:in `block in with_import'    
hfla_site  |    from /usr/gem/gems/sass-3.7.4/lib/sass/stack.rb:135:in `with_frame'
hfla_site  |    from /usr/gem/gems/sass-3.7.4/lib/sass/stack.rb:88:in `with_import'
hfla_site  |    from /usr/gem/gems/sass-3.7.4/lib/sass/tree/visitors/perform.rb:322:in `visit_import'
hfla_site  |    from /usr/gem/gems/sass-3.7.4/lib/sass/tree/visitors/base.rb:36:in `visit'      
hfla_site  |    from /usr/gem/gems/sass-3.7.4/lib/sass/tree/visitors/perform.rb:158:in `block in visit'
hfla_site  |    from /usr/gem/gems/sass-3.7.4/lib/sass/stack.rb:79:in `block in with_base'      
hfla_site  |    from /usr/gem/gems/sass-3.7.4/lib/sass/stack.rb:135:in `with_frame'
hfla_site  |    from /usr/gem/gems/sass-3.7.4/lib/sass/stack.rb:79:in `with_base'
hfla_site  |    from /usr/gem/gems/sass-3.7.4/lib/sass/tree/visitors/perform.rb:158:in `visit'  
hfla_site  |    from /usr/gem/gems/sass-3.7.4/lib/sass/tree/visitors/base.rb:52:in `block in visit_children'
hfla_site  |    from /usr/gem/gems/sass-3.7.4/lib/sass/tree/visitors/base.rb:52:in `map'        
hfla_site  |    from /usr/gem/gems/sass-3.7.4/lib/sass/tree/visitors/base.rb:52:in `visit_children'
hfla_site  |    from /usr/gem/gems/sass-3.7.4/lib/sass/tree/visitors/perform.rb:167:in `block in visit_children'
hfla_site  |    from /usr/gem/gems/sass-3.7.4/lib/sass/tree/visitors/perform.rb:179:in `with_environment'
hfla_si [...]

2021-06-06 15:20 UTC, akibrhast requested changes
I am unable to run this locally during review, I have posted the error messages I am receiving. Could you please confirm that the errors are fixed.

2021-06-17 04:28 UTC, akibrhast commented
@GLRJr Could you please provide any updates regarding this ?

2021-06-21 16:08 UTC, akibrhast submitted a review, later dismissed
LGTM! 👍 

@GLRJr  Please turn of your IDE's auto format features for the website repo, its causing unnecessary line changes in the PRs and making it very difficult to figure out which was the pertinent lines that was really changed.

2021-06-21 16:26 UTC, akibrhast requested changes
Requested changes and tagged UI in the above comment

2021-06-23 17:04 UTC, akibrhast commented
Moved this to Development meeting board to discuss why it has been sitting in PR for so long, and what can we do about it

2021-06-25 02:52 UTC, akibrhast commented
@jbubar reached out to @GLRJr on slack, going to touch base tomorrow.

2021-06-25 23:07 UTC, GLRJr commented
@jbubar and I worked on this, I have to do little bit of editing margins.
ETA: Tomorrow

2021-06-27 01:10 UTC, GLRJr commented
Made changes to margins, I think my browser settings were making things weird. but hopefully you guys think this looks good lol

![image](https://user-images.githubusercontent.com/29311777/123529867-8ab70780-d6a9-11eb-8639-ebc50985e39d.png)

2021-06-29 18:37 UTC, akibrhast commented
Based on the figma design I think the foot of the person is supposed to be aligned with the text on the right that does not seem to be the case in this pull request.

<details>
<summary>Figma Design</summary>

![image](https://user-images.githubusercontent.com/32349001/123849862-4e70ea80-d8e7-11eb-97d4-bcbda66b799a.png)

</details>


<details>
<summary>Your PR</summary>

![image](https://user-images.githubusercontent.com/32349001/123849991-73655d80-d8e7-11eb-8781-e58f1327ac34.png)


</details>

2021-06-29 18:47 UTC, akibrhast submitted a review, later dismissed
Based on the figma design I think the foot of the person is supposed to be aligned with the text on the right that does not seem to be the case in this pull request. There also seems to be an unusual amount of space between the two paragraphs on the right.

This was just a preliminary check, I will update this comment with a few more things that caught my eye later tonight

<details>
<summary>Figma Design</summary>

![image](https://user-images.githubusercontent.com/32349001/123849862-4e70ea80-d8e7-11eb-97d4-bcbda66b799a.png)

</details>


<details>
<summary>Your PR</summary>

![image](https://user-images.githubusercontent.com/32349001/123849991-73655d80-d8e7-11eb-8781-e58f1327ac34.png)


</details>

2021-06-29 21:50 UTC, GLRJr commented
I think we might be looking at two different things because my figma isn't aligned, if you have some time today we can look at this together
![image](https://user-images.githubusercontent.com/29311777/123871938-3601cf80-d8e9-11eb-8fde-4ececb51ccc8.png)

2021-06-29 23:13 UTC, GLRJr commented
I made changes to the margins this should to remove the space in  between the paragraphs and image, how does it look? I'm going to push this now
![image](https://user-images.githubusercontent.com/29311777/123878880-c85ba080-d8f4-11eb-98ae-437ba915a8fb.png)

2021-06-30 00:51 UTC, akibrhast commented
> I think we might be looking at two different things because my figma isn't aligned, if you have some time today we can look at this together

@GLRJr You are right, I was looking at the wrong figma design. I am going to dismiss the review and redo it.

My apologies.

2021-07-02 15:02 UTC, merged

2021-07-06 17:57 UTC, jbubar commented on pages/program-areas.html
> -        {% include svg/program-areas-hero.svg %}
Was this line supposed to be deleted?

2021-07-07 02:17 UTC, GLRJr commented on pages/program-areas.html
> -        {% include svg/program-areas-hero.svg %}
is this for me, because I didn't do anything with the header