Wins page modal a11y
hackforla/website pull request #1679
Opened 2021-06-01 23:27 UTC by grhhhh

fixes #1531

-Makes "see more..." tab-able. 
-Makes modal close when `ESC` key is pressed. 
-Captures focus so that modal content is tab-able and background content is ignored while the modal is open.

Note: this fix requires the use of the inert polyfill

2021-06-05 02:33 UTC, Aveline-art commented
@grhhhh I can't seem to tab-focus inside the modal. Am I doing it right? This is what I have tried.

1. Click 'see more' to open modal.
2. Press tab.
3. Tab scrolls focus over 'linkedin' and 'github' links.

<details>
<summary>Am I supposed to tab when the state of the page is like this?</summary>
<img src="https://user-images.githubusercontent.com/62368440/120877378-0ae6c300-c56b-11eb-8b6f-d2184bb69c4d.png" />
</details>

For specs, I use the latest version of Firefox on Windows.

2021-06-05 21:47 UTC, grhhhh commented
@Aveline-art can you be specific regarding which 'linkedin' and 'github' links are focused by tab as you described? Specifically whether tab focuses on the links inside of the modal or outside of it.

The intended function and the functionality that I observed (macbook pro, chrome) is that tab focuses on the modal content, in this case the 'linkedin' and 'github' links, while ignoring all things outside of the modal.

2021-06-05 22:38 UTC, Aveline-art commented
@grhhhh Sorry for not being more clear. To clarify: when I press tab, the focus scrolls to the links inside the modal. Once those options are exhausted, the focus returns to behind the modal. At a certain point the focus cycles back to the modal, before continuing behind the modal, and so on and so on.

2021-06-06 15:05 UTC, akibrhast requested changes

2021-06-06 15:05 UTC, akibrhast commented on pages/wins/wins.html
> +<script src="/node_modules/wicg-inert/dist/inert.min.js"></script>
I noticed that you have added a node-modules in our project folder in this PR. And you are importing the package by referencing from the node-modules folder. Which in turns results in the addition of the package-lock.json file.

Could you please remove the node-modules folder, and the package-lock.json and instead download the inert.min.js package directly and place in the `assets/js` directory.
Such that the path of the package becomes `assets/js/inert.min.js` , and you can then modify this line to

<script src="/assets/min/inert.min.js"></script>

2021-06-06 15:05 UTC, akibrhast commented on pages/wins/wins.html
> +		// icon.setAttribute("tabindex", 0);
Remove this commented line if not needed

2021-06-06 15:05 UTC, akibrhast commented on pages/wins/wins.html
> +	// console.log(modal);
Remove these commented line if not needed

2021-06-06 15:05 UTC, akibrhast commented on _sass/components/_wins-page.scss
> +
Remove commented lines if not needed.

2021-06-09 00:41 UTC, grhhhh commented
@akibrhast 
Latest commit removes package-lock.json and commented code as requested. Also, inert.min.js was added to `js/assets` directory and linked in wins.html

@Aveline-art 
I was unable to recreate the issues you described using the latest version of Firefox on my machine.

2021-06-09 02:20 UTC, Aveline-art approved these changes
Update June 8th, 2021. I have discovered an error on my end that was causing the problems. @grhhhh Everything is good. Great job on this!

2021-06-10 14:07 UTC, akibrhast commented
@grhhhh Hey, were you able to resolve that issue in regards to the see more, see less button that occurs at a certain screen width.... ?

2021-06-10 21:50 UTC, grhhhh commented
A bug was discovered while working on this issue: the ‘see more’ link changes to read ‘see less’ when opened, but does not change back to ‘see more’ after being closed. A fix falls outside of the scope of this PR.

2021-06-15 04:24 UTC, akibrhast approved these changes
lgtm

2021-06-15 04:24 UTC, merged