Update program areas page to reflect correct mini project cards
hackforla/website pull request #1684
Opened 2021-06-03 23:52 UTC by arghmatey

Fixes #1614 

Replaced incorrect project card information to match the Program Areas page Figma file.

2021-06-06 09:10 UTC, jbubar requested changes
Great job so far on this pr.
I noticed the the project-in-formation.png image has not been added to the repo... Is that right?
could you add it?

2021-06-09 21:00 UTC, arghmatey commented
@jbubar Added placeholder image to the repo and updated any cards that had the old placeholder image on them. 

Thank you for helping me!

2021-06-11 20:34 UTC, jbubar requested changes

2021-06-11 20:34 UTC, jbubar commented on _data/internal/program-areas/justice-card.yml
> +    image: /assets/images/projects/project-in-formation.png
this is not the right path. it looks like the image is in /assets/images/projects/project-in-formation.png

2021-06-11 21:06 UTC, arghmatey commented on _data/internal/program-areas/justice-card.yml
> +    image: /assets/images/projects/project-in-formation.png
I believe that's the path I have currently in the commit. Can you double-check and point me in the right direction if not?

2021-06-15 23:58 UTC, jbubar commented on _data/internal/program-areas/justice-card.yml
> +    image: /assets/images/projects/project-in-formation.png
OMG! hahhahaha. what did I write? So sorry about that. not sure what I was thinking.

2021-06-15 23:59 UTC, jbubar commented on _data/internal/program-areas/justice-card.yml
> +    image: /assets/images/projects/project-in-formation.png
This is perfect

2021-06-15 23:59 UTC, merged