Standardize join us page mobile
hackforla/website pull request #1731
Opened 2021-06-13 03:22 UTC by josiehandeveloper

fixed issue #1607

2021-06-13 11:59 UTC, qiqicodes requested changes
Join Us page looks good, please resolve the conflict on engage.md

<details>
<summary>engage.md conflict</summary>
<img src="https://user-images.githubusercontent.com/68657634/121806255-fc03ae80-cc03-11eb-974f-5ca20f780cb8.png">
</details>

2021-06-16 03:44 UTC, aliibsin commented
@josiehandeveloper, if you need help resolving merge conflict, reach out to the HfLA slack channel

2021-06-18 04:53 UTC, Aveline-art reviewed
Everything for the most part looks good, but I'm a little bothered that these changes do not match the design in [figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=2991%3A0). @daniellex0 Can you give me some guidance on whether changes to the website should appear as they are on the figma page?

<details>
<summary>Website's appearance after changes in desktop</summary>
<br>
<img src="https://user-images.githubusercontent.com/62368440/122509268-54e29680-cfb8-11eb-89e5-870735f73b98.png" width="600" length="300" />
<br>
</details>

2021-06-18 04:56 UTC, Aveline-art commented on _sass/components/_join-us.scss
> +      }
I think there is a specific @media that we use for mobile only. It can be found in the _layout.scss file. In the interest of being consistent, can you use the @media there instead?

2021-06-18 04:56 UTC, Aveline-art commented on _sass/components/_join-us.scss
> +      }
Same as above!

2021-06-18 04:58 UTC, Aveline-art requested changes
Left some notes above @josiehandeveloper . Let me know if you have any questions

2021-06-20 06:51 UTC, daniellex0 commented
@Aveline-art Hmm yeah the desktop version shouldn't be changing at all from this issue

I have no idea why but for some reason I can't pull the changes - it just shows up the same as the current site for me. 

@josiehandeveloper can you please include screenshots of how it looks after your changes (both mobile and desktop)? Thanks!

Also just from looking at the code, it looks like the standard ".header-container" class hasn't been added- can that please be added in? I'm sorry if the instructions weren't clear... there is supposed to be both a ".header-container" class and ".header-container--join"

2021-06-20 17:08 UTC, Aveline-art approved these changes
@daniellex0 Thank you for your guidance!

Everything looks good! @qiqicodes If you agree, please approve and merge!

2021-06-22 00:36 UTC, josiehandeveloper commented
<img width="494" alt="Screen Shot 2021-06-20 at 12 44 42 AM" src="https://user-images.githubusercontent.com/63170710/122666287-3ec40a00-d161-11eb-9b95-f99548228106.png">
<img width="499" alt="Screen Shot 2021-06-20 at 12 44 34 AM" src="https://user-images.githubusercontent.com/63170710/122666290-408dcd80-d161-11eb-820b-bb3a23aa183a.png">
<img width="1427" alt="Screen Shot 2021-06-20 at 12 44 00 AM" src="https://user-images.githubusercontent.com/63170710/122666291-42579100-d161-11eb-8df3-1ae599db4357.png">

2021-06-23 17:06 UTC, akibrhast approved these changes
LGTM!

2021-06-23 17:06 UTC, merged