toggle see more/see less on wins card
hackforla/website pull request #1732
Opened 2021-06-13 11:37 UTC by qiqicodes

fixes #1549 

1. toggles `see more`/`see less` on the bottom right of the wins card
2 `see more` has ellipsis, sticking with same Figma design

https://user-images.githubusercontent.com/68657634/121805548-93ff9900-cc00-11eb-9d1d-21183bd2d3b7.mov

2021-06-13 15:43 UTC, akibrhast commented on _sass/components/_wins-page.scss
> +        // }
Please remove commented out code

2021-06-13 15:43 UTC, akibrhast commented on pages/wins/wins.html
> +		// new ResizeObserver(addSeeMore).observe(winText)
Please remove commented out code

2021-06-13 15:59 UTC, akibrhast requested changes
### Bugs

- There seems to some problems with the `See more` , `See Less` button in regards to styling. Please look at the below image for reference.

<details>
<summary>Styling Error</summary>

![image](https://user-images.githubusercontent.com/32349001/121813947-76502500-cc3c-11eb-9e44-b05095eba8d4.png)


</details>


- Also when I am in mobile view and click on `See More` -> which causes the button to toggle to `See Less`  -> and then i transition to desktop view. The text stays at `See Less` and does not go back to default.
<details>
<summary>Image Of See Less button not toggling back to See More on mobile to desktop transition</summary>

![image](https://user-images.githubusercontent.com/32349001/121814063-1dcd5780-cc3d-11eb-9b56-1ddf5efc3187.png)

</details>

- There seems to be a bug in the `See Less ` button where its not clicking at these dimension for some reason

<details>
<summary>See Less Button Not Clickable</summary>

![image](https://user-images.githubusercontent.com/32349001/121814256-080c6200-cc3e-11eb-89c3-ffc6971bcca4.png)

</details>

### Side Notes 
 
[ @daniellex0 - Could you please give your thoughts on these? ]
- The position of the see more/ see less button seems haphazardly placed. Imho, this looks aesthetically unpleasant.
- The inconsistency of some cards having a  linkedin icon only, some having a github icon only also seems very messy aesthetically speaking.

2021-06-13 21:30 UTC, qiqicodes commented
I will work on the styling some more. Thanks for reviewing @akibrhast

2021-06-16 17:47 UTC, akibrhast commented
this is a test comment #1755

2021-06-17 04:24 UTC, qiqicodes commented
@akibrhast The styling error is fixed, and the `see more/see less` is clickable.

In regards to "See Less button not toggling back to See More on mobile to desktop transition", this is a logic we have to add in. We can file an issue regarding this feature.

Currently the mobile has  the option to `see more` and `see less`, and desktop only has `see more`, should we have consistent design and add `see less` on the modal? And disable the close via click on grayed out background? @daniellex0

2021-06-18 01:38 UTC, daniellex0 commented
> The position of the see more/ see less button seems haphazardly placed. Imho, this looks aesthetically unpleasant.

Could you be more specific please?

> The inconsistency of some cards having a linkedin icon only, some having a github icon only also seems very messy aesthetically speaking.

This was part of the original design by a previous designer that was approved by Bonnie. But future iterations might be able to include a different layout.

One of our designers did notice that these icons are sharp black ( # 000 ) when they are supposed to be dark gray like the text (# 333), so that would be a good issue for someone to figure out how to fix and I think might make the logos pop out less. Could you please make a dev issue for this?

2021-06-21 16:54 UTC, akibrhast commented
My apologies for not being specific @daniellex0 

<details>
<summary>Images featuring the haphazard placing of see more/see less button</summary>

1. ![image](https://user-images.githubusercontent.com/32349001/122797337-60baab00-d28d-11eb-9838-a633a83b2845.png)
2. ![image](https://user-images.githubusercontent.com/32349001/122797728-c9a22300-d28d-11eb-97c6-9e229dbdf26a.png)
</details>

---

@qiqicodes There seems to be still some styling error with the see less button on mobile. Please look at image 2 above, at the "Sean Flores" and "Josh Robins" cards


--- 

Some food for thought:
We need to ensure that the user submitting their win story is required to submit their github information. On top of that, we also need to ensure that we use their github profile picture by default. Every project contributor in HFLA in every is already being displayed with their github image and github link on ALL of your projects pages(All-time contributor sections) . https://www.hackforla.org/projects/website . At the start of joining hackforla we also require an individual to make their HFLA membership public.

I am going to move this PR to the dev discussion board to have the chance to bring it during tomorrow's developer meeting to get everyone's feedback and opinions on this matter.

2021-06-23 17:11 UTC, akibrhast commented
Discussed on Tuesday developer meeting, @jbubar  will reach out to @qiqicodes to discuss and resolve. Moving this to draft until a resolution is reached and changes implemented from their discussion.

2021-06-27 19:28 UTC, akibrhast commented
@jbubar to close this draft pull request when he makes a new pull request

2021-07-12 04:08 UTC, closed without merging