Zak234
hackforla/website pull request #1773
Opened 2021-06-18 02:42 UTC by Zak234

Fixes #1694 
Created a new button class xl-long which is the same as the xl class but with more padding. I then applied this new class to the CTA "Join US" home page button. This was done to increase the visibility of the button due to the shorter text inside.

New:
![IMG-1405 (2)](https://user-images.githubusercontent.com/85966467/122498268-a7658800-cfa3-11eb-925a-35d165b30005.jpg)

Old:
![IMG-1406](https://user-images.githubusercontent.com/85966467/122498454-00352080-cfa4-11eb-9f47-4eda6a3ec818.jpg)

2021-06-19 00:37 UTC, akibrhast approved these changes
Very Nicely Done!

@Zak234   Feel free to pick up a suitable issue next!!

- Mature team members, do not merge this PR and leave this for reviewing by at least one new member
- New team members about to review , here is a guide on [How To Review A PR](https://github.com/hackforla/website/wiki/How-to-Review-Pull-Requests)

2021-06-22 05:31 UTC, akibrhast commented
I am closing this PR temporarily for testing reasons this will be reopened soon

2021-06-22 05:48 UTC, abuna1985 requested changes
Please remove the closing curly brace ( } ) on line 192 and 271 within _sass/elements/_typography.scss. They not connected to any opening curly brace and they are breaking the docker build.

<details>
    <summary>Docker Build Errors</summary>
    <img src="https://user-images.githubusercontent.com/21162229/122871626-27f9f080-d2e4-11eb-8b99-c2db628560cb.jpg" />
   <br/>
   <br/>
   <img src="https://user-images.githubusercontent.com/21162229/122871737-4b24a000-d2e4-11eb-8726-997664b97208.jpg" />
</details>

2021-06-22 14:22 UTC, akibrhast approved these changes
## Requesting Changes
@Zak234 There seems to be a lot of things in this PR that is not related to this issue.
In particular, the addition of all the `title` classes. From the looks of it, I believe this was a result of you trying to implement some of the design systems from figma possibly for another [issue](https://github.com/hackforla/website/pull/1814/files), but somehow they got pushed into this issue. Could you please rectify this.. Thanks!

2021-06-22 14:22 UTC, akibrhast commented on _sass/core/_print.scss
> +
@Zak234 I am not sure why these changes were made. It does not seem related to the linked issue, nor do I see any mention of this in the PR description. Could you please provide feedback in regards to this

2021-06-22 14:22 UTC, akibrhast commented on _sass/elements/_typography.scss
> + {
@Zak234 I am not sure why these changes were made. It does not seem related to the linked issue, nor do I see any mention of this in the PR description. Could you please provide feedback in regards to this

2021-06-22 14:22 UTC, akibrhast commented on _sass/elements/_typography.scss
> +
@Zak234 I am not sure why these changes were made. It does not seem related to the linked issue, nor do I see any mention of this in the PR description. Could you please provide feedback in regards to this

2021-06-22 14:22 UTC, akibrhast commented on _sass/elements/_typography.scss
> +
@Zak234 I am not sure why these changes were made. It does not seem related to the linked issue, nor do I see any mention of this in the PR description. Could you please provide feedback in regards to this

2021-06-22 14:22 UTC, akibrhast commented on _sass/elements/_typography.scss
> +
@Zak234 I am not sure why these changes were made. It does not seem related to the linked issue, nor do I see any mention of this in the PR description. Could you please provide feedback in regards to this

2021-06-22 14:22 UTC, akibrhast commented on _sass/variables/_typography.scss
> +
@Zak234 I am not sure why these changes were made. It does not seem related to the linked issue, nor do I see any mention of this in the PR description. Could you please provide feedback in regards to this

2021-06-22 14:22 UTC, akibrhast commented on _sass/elements/_buttons.scss
> +  The following class names style all buttons on the HfLA site.
Please turn of the auto formatting feature on your work space. These line changes seems to be result of auto format

2021-06-22 14:22 UTC, akibrhast commented on _sass/elements/_buttons.scss
> +/*
Please turn of the auto formatting feature on your work space. These line changes seems to be result of auto format

2021-06-22 14:22 UTC, akibrhast commented on _sass/elements/_buttons.scss
> +- Page-specific class names should live in that specific page's .scss file.
Please turn of the auto formatting feature on your work space. These line changes seems to be result of auto format

2021-06-22 14:22 UTC, akibrhast requested changes
Meant to 'request changes ' in the previous comment

2021-06-22 16:00 UTC, Zak234 commented
Yeah, sorry. Those other changes were for a different issue and I accidentally put them in the same branch. They should be removed.

2021-06-23 16:52 UTC, akibrhast approved these changes
LGTM!

2021-06-23 16:58 UTC, merged