Adjusts Program Areas page image cards in mobile
hackforla/website pull request #1774
Opened 2021-06-18 03:29 UTC by arghmatey

Fixes #1610 

### What changes did you make and why did you make them ?

  - Pulled desired image dimensions from Figma file
  - Updated height of image card from `auto` to `213px`

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Program Areas page's image card</summary>

![Screen Shot 2021-06-17 at 8 06 13 PM](https://user-images.githubusercontent.com/40401149/122501916-72a8ff00-cfaa-11eb-81f9-1455c0fce199.png)

</details>

2021-06-18 05:25 UTC, Aveline-art approved these changes

2021-06-18 05:25 UTC, Aveline-art commented on _sass/components/_program-areas.scss
> +        height: 213px;
It looks good to me, but out of curiosity, @arghmatey , where did you get the 213px from? Was it arbitrarily chosen?

2021-06-18 05:45 UTC, arghmatey commented on _sass/components/_program-areas.scss
> +        height: 213px;
@Aveline-art Thanks! Pulled that figure from the Program Area page Figma file.

2021-06-18 22:58 UTC, Aveline-art commented on _sass/components/_program-areas.scss
> +        height: 213px;
Just thought you might want to know that the Figma size appears to be a height of 231px rather than 213px.

<details>
<summary>Figma</summary>
<br>
<img src="https://user-images.githubusercontent.com/62368440/122622557-f2d47080-d04d-11eb-9b56-edd4e27a3a30.png" width="600" length="300" />
<br>
</details>

2021-06-18 23:01 UTC, arghmatey commented on _sass/components/_program-areas.scss
> +        height: 213px;
@Aveline-art Thank you for catching that! I'll make the change and send a new commit.

2021-06-18 23:41 UTC, arghmatey commented on _sass/components/_program-areas.scss
> +        height: 213px;
@Aveline-art New commit submitted with correct Figma figure.

2021-06-19 00:04 UTC, akibrhast requested changes
These few files should not appear in this pull request. Could you please cleanup the PR and remove these files from it.
- _data/external/wins-data.json
- _data/external/vrms_data.json
- _data/external/github-data.json

@arghmatey

2021-06-19 01:05 UTC, arghmatey commented
@akibrhast Sure - let me take a look at that. Just for my knowledge, what are those files and do you know how they made it into my PR?

2021-06-19 01:21 UTC, akibrhast commented
@arghmatey 

- _data/external/wins-data.json
   - Is the data that is used to display the cards in the [wins page](https://www.hackforla.org/wins/)
- _data/external/vrms_data.json
   -  Is the data that is used to display the event times on the [events page](https://www.hackforla.org/events/)(It is the right column card)
- _data/external/github-data.json
   - Is the data that is used to display the people who are contributing to a particular project for each individual projects page. For example - https://www.hackforla.org/projects/website (Its the images in the All Time Contributor Section)

---

In regards to how they made into your PR, I am not 100% sure. I am **assuming** what happened was ,
1. You made your PR
2. Changes was requested
3. Bot made changes to the hfla repo
4. Before you made changes you merged changes from upstream into your branch
5. As such , you ended up with those changes as part of the branch

Am I able to remove those commits?
Yes. Google is going to be your help here in regards to exact commands. Although I do believe you just rebase it off off from gh-pages it should be fine. I think @jbubar has actually handled a couple of similar incidents, he might be great source of help in regards to the exact steps

2021-06-19 01:25 UTC, arghmatey commented
@akibrhast Interesting! Thanks for the info. I'll see what I can do and reach out to Josh if I have any questions.

2021-06-19 02:47 UTC, arghmatey commented
@akibrhast The 4 commits from HackforLABot have been removed, and pixel size has been corrected.

2021-06-21 16:01 UTC, akibrhast approved these changes
LGTM 👍

2021-06-21 16:02 UTC, merged