Add x modal wins page
hackforla/website pull request #1775
Opened 2021-06-18 07:04 UTC by marcobarrera

Fixes #1552 

### What changes did you make and why did you make them ?

  - Added closing 'x' icon to modal overlay in wins page so that user can exit modal in another way other than clicking on the background.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Modal image from wins page with closing 'x' icon</summary>

<img width="591" alt="Screen Shot 2021-06-17 at 11 56 56 PM" src="https://user-images.githubusercontent.com/24802803/122520212-2ff61f80-cfc8-11eb-8ef8-ce67a661bccf.png">

</details>

2021-06-21 16:03 UTC, akibrhast approved these changes
This looks good to me, 👍 , but going to hand of to @jbubar for the final say cause he is the primary code owner of the wins page!

2021-06-22 17:01 UTC, jbubar commented
This might cause some merge conflicts with the wins-feature-1 branch when we merge it. but otherwise it looks good

2021-06-22 18:54 UTC, jbubar commented
Actually @marcobarrera would you be down to use an svg icon instead of the letter x? Ill send you one in slack

2021-06-24 16:01 UTC, akibrhast commented
any updates on this ? @jbubar @marcobarrera  ?

2021-06-24 16:08 UTC, jbubar commented
I sent a slack message to @marcobarrera and have not heard back yet. @akibrhast do you agree that it would look better with a svg rather than the letter X?

2021-06-24 16:12 UTC, jbubar commented
<details>
    <summary>here is the svg I sent him</summary>

<svg xmlns="http://www.w3.org/2000/svg" stoke="#333" fill="#333" width="18" height="18" viewBox="0 0 18 18"><path d="M14.53 4.53l-1.06-1.06L9 7.94 4.53 3.47 3.47 4.53 7.94 9l-4.47 4.47 1.06 1.06L9 10.06l4.47 4.47 1.06-1.06L10.06 9z"/></svg>    


</details>

You can see the svg tag if you edit the comment. for some reason github is not letting me drag and drop it..

2021-06-27 16:54 UTC, jbubar requested changes
Please get the svg from the figma for the "x" and use that instead of the letter "X"

2021-06-29 18:49 UTC, akibrhast commented
Changing to draft. Please undraft it when the changes requested have been made @marcobarrera fee

2021-06-30 00:18 UTC, marcobarrera commented
### What changes did you make and why did you make them ?

  - Added 'x' svg to modal overlay in wins page so that user can exit modal in another way other than clicking on the background.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Modal image from wins page with closing 'x' svg icon</summary>

<img width="876" alt="Screen Shot 2021-06-29 at 5 16 35 PM" src="https://user-images.githubusercontent.com/24802803/123883518-08735100-d8fe-11eb-8a53-c125fc5d455e.png">

</details>

2021-06-30 02:18 UTC, jbubar approved these changes
looks Great!
Thanks Marco

2021-06-30 02:19 UTC, merged