Implementing new design system heading typography in the code base
hackforla/website pull request #1814
Opened 2021-06-22 08:34 UTC by Zak234

Fixes #1743 

Added six new classes of heading: Title1, Title2, Title3, Title4, Title5 and Title6. Each one was only given size attributes as specified by the issue. These have not been applied yet to any text as this will be done in a different issue. The goal of these changes was so that our heading sizes are no longer attached to h1/h2/h3 tags etc and can no longer negatively affect the accessibility/hierarchy of the web pages for people using screen readers

2021-06-24 15:56 UTC, akibrhast commented
Update: This will be reviewed and potentially discussed in tonight's backend meeting

2021-06-25 04:23 UTC, akibrhast commented
### Update
This was discussed and and reviewed in group during the thursday meeting. Majority approval in that everything looks good and this should not break anything. However individual developers assigned to review this issue has yet to test this out locally on their systems. 

- The people tagged on this issue could you all please review the changes with respect to the design system as linked in the issue, and ensure that none of the existing pages has any weird behaviour(It shouldn't).

- Also please double check the compiled css of these title classes that is generated within the `_site` directory and ensure that everything is compiling down to as expected.

2021-06-25 04:23 UTC, Aveline-art reviewed
Hey @Zak234! Overall, great work on adding the new typography and maintaining the structure of the website. The team had reviewed your work in the backend meeting and we are very impressed with your speed and accuracy. Please check my comments (which are my own, not the team's). Once they have been addressed, I can begin to test out the new typography!

2021-06-25 04:23 UTC, Aveline-art commented on _sass/elements/_typography.scss
> +
From the pattern of the code above and below, it looks like a comma was missed between the tag and the class.

2021-06-25 04:23 UTC, Aveline-art commented on _sass/variables/_typography.scss
> +);
Out of curiosity, where was the print values puled from? I could not find the 36pt from the Figma design.

2021-06-25 19:49 UTC, Zak234 commented on _sass/elements/_typography.scss
> +
Done

2021-06-25 19:50 UTC, Zak234 commented on _sass/variables/_typography.scss
> +);
I calculated it from the desktop px size.

2021-06-27 18:48 UTC, akibrhast requested changes
- Add . infront of the the title class
- make the title class names lower cases , example: `.title1`

2021-06-29 04:54 UTC, Aveline-art requested changes
I have checked out the new design on some of the pages and it looks awesome! Thank you for doing this @Zak234 . There is only one fix left before I approve of this. Cannot wait to start implementing this everywhere.

2021-06-29 04:54 UTC, Aveline-art commented on _sass/elements/_typography.scss
> +
".type-Title" is still uppercase.

2021-06-29 05:01 UTC, Zak234 commented on _sass/elements/_typography.scss
> +
Done

2021-06-30 00:35 UTC, Aveline-art approved these changes
Everything looks good! Great work!

2021-06-30 03:37 UTC, jbubar approved these changes
I pulled this to my machine, everything looks great. Sakari, Nice job. Stelllar.

2021-06-30 03:38 UTC, merged