1748, civic index profile page
hackforla/website pull request #1832
Opened 2021-06-25 00:50 UTC by anonymousanemone

Fixes #1748 

### What changes did you make and why did you make them ?

  - updated current project team
  - removed open roles

2021-06-27 13:52 UTC, Zak234 approved these changes
Everything looks good. Great job!

2021-06-28 22:26 UTC, Sihemgourou commented
@hackforla/website-merge

2021-06-29 04:25 UTC, Aveline-art commented
@anonymousanemone Please add images of the web page before and after your changes! This allows the team (especially the designers) to quickly orient themselves!

2021-06-29 04:35 UTC, Aveline-art requested changes

2021-06-29 04:35 UTC, Aveline-art commented on _projects/civic-tech-index.md
> +    links:
Good work on getting this done! It looks like you've missed parentheses marks around the link in 'picture:', which caused the files to not load. Please fix that so that I can see your updates! Thank you!

2021-06-29 22:18 UTC, anonymousanemone commented
changed: 
![image](https://user-images.githubusercontent.com/86015625/123874492-1ff60e00-d8ed-11eb-9ef2-50f5de322d72.png)
![image](https://user-images.githubusercontent.com/86015625/123874507-27b5b280-d8ed-11eb-9307-76b6e5297f3d.png)
![image](https://user-images.githubusercontent.com/86015625/123874521-2d12fd00-d8ed-11eb-92dc-17faf6f84917.png)
old version: 
![image](https://user-images.githubusercontent.com/86015625/123874539-33a17480-d8ed-11eb-88d0-3e4a5a813dea.png)
![image](https://user-images.githubusercontent.com/86015625/123874553-38662880-d8ed-11eb-8f61-b6b84091c06c.png)

2021-06-29 22:29 UTC, closed without merging