Projects page
hackforla/website pull request #1837
Opened 2021-06-27 14:33 UTC by wendywilhelm10

Fixes #1671 

### What changes did you make and why did you make them ?
This is to develop the new projects page
 
### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Images of new projects page and updated credits page</summary>

New Project Page:
![newprojectspage](https://user-images.githubusercontent.com/44912633/123548522-0d37d980-d733-11eb-9acd-9dcb27940948.PNG)

Credits Page Before:
![credits-before](https://user-images.githubusercontent.com/44912633/123548525-10cb6080-d733-11eb-8f20-71addc10187a.PNG)

Credits Page After:
![credits-after](https://user-images.githubusercontent.com/44912633/123548529-13c65100-d733-11eb-8e8a-4b95594c8b53.PNG)

</details>

2021-06-30 20:53 UTC, averdin2 requested changes
@wendywilhelm10 I am about to write a larger comment on some issues I think need to be discussed regarding this PR that may result in more changes needed, but for now, just fix this typo. Great job on this issue so far!

2021-06-30 20:53 UTC, averdin2 commented on pages/new-projects.html
> +          services across a number of skill levels and practive areas.
On line 11 I believe 'practive' should be 'practice'.

2021-06-30 21:13 UTC, averdin2 commented
There are a few things going on with this PR that I think need to be discussed and possibly changed before merging.
1. I am not familiar with the design and overall administrative reasoning for adding this page, but I thought the naming of this page being called 'new-projects' doesn't really make sense. Not sure if this name has been discussed already with the team, but I think it may need more discussion.
2. This is more of a dev thing, but I saw that there are some duplicate style classes from other files in _new-projects.scss from line 47 down. I know this is a larger issue regarding our styles refactoring, but for this issue, I want to know if these duplicate styles should be removed? Personally, I would say to remove these styles as there is no reason to have these styles here since they are already in other files, but maybe we are thinking otherwise.
3. I am making a separate comment for this issue as to not clutter this comment, but there seems to be an issue with the way the image files are being used in this PR. See comment:

2021-06-30 21:42 UTC, averdin2 commented
@daniellex0 There seems to be an issue in regards to the use of the image files in this PR. I see that the implementation of this new 'design-team' image and this new page's header style is supposed to mimic the credits page, but I don't think the two new files, 'design-team.svg' and 'projects-hero.svg' are being used correctly. I believe that the difference between the two files is that one is supposed to be used on larger screens and the other is supposed to be used on mobile (please let me know if this is wrong). As of right now, only the 'projects-hero.svg' file is being used in the actual page. The size of this file is then being changed when in mobile view within the code (the file itself is not being changed to the smaller 'design-team.svg' image). The only place the 'design-team.svg' file is being used is in the credits page as a credit to that image. I am also seeing that the credits page is only using one image file rather than two, which I think is causing confusion on what to do with the two different-sized files. My question is, how should the implementation of this page be done in regards to the use of these two images? I have some proposed changes myself which I will detail below:
1. Perhaps we should completely disregard the smaller image file given that it seems to resize perfectly fine with the image being used now. This follows how the credit page is implemented.
2. We should use both images, in which case we need to fix how the code is resizing only one image. (If we go this way, do we want to make an issue to do the same with the credits page?)

Personally, I think option 1 is easier and quicker, but maybe 2 is better.

Danielle, this is probably more of a dev issue, but I want to make a note that I think that the places where these two files are being stored could be fixed. It doesn't really make sense for the 'projects-hero.svg' file to be in the projects images folder. The 'design-team.svg' also does not make sense being placed in the join-us image folder. Depending on what implementation we go with, I might have different suggestions as to where the file(s) should go, but I think we may just want to make another folder for the image(s).

2021-07-04 03:54 UTC, daniellex0 commented
For some reason I am having a hard time figuring out how to access this page to review it when I pull it onto my machine- what is the url? I tried 'new-projects,' 'projects' etc but they're not working. 

@averdin2 :

1. This page is basically being added because visitors that go to our current homepage just scroll down forever through our project cards, so now there will be a dedicated page for projects and the homepage can include more information about HfLA overall (hence the current homepage redesign work). Agreed that 'new-projects' doesn't really fit as the name for this page because it is for all projects, not just new ones. I probably caused the confusion though because I kept calling it the new projects page (but I meant that's it a new page heh). Just 'Projects' would make more sense, but I noticed it leads to a weird page listing all of the links to project card markdown files.. hmm..

2. I may be misunderstanding this point, but FYI @averdin2  since this page is going to be completely replacing the project cards in the homepage, these styles would probably all need to move to this new file- so they won't be duplicates anymore because this is the only place where they will exist. Unless I'm misunderstanding! 

3. I don't really understand this, I think because I haven't figured out what the URL is so I can't view it for myself... someone please help but letting me know what the URL is, or how I can find it :P. but what I am understanding is that multiple image files are being used for the same image? That shouldn't be the case for SVG because they are infinitely scalable and always stay the same file size... so as I understand it, the same image file should be used everywhere, just with CSS adjusting its size in each instance. But again, I might be totally misunderstanding. Once I have the right URL I'll be able to check all of this out!

Yeah I don't know much about where the images are supposed to be saved, I defer to the dev team with that!

2021-07-04 12:53 UTC, wendywilhelm10 commented
@averdin2 
I changed the word you pointed out and now it's correct.
@daniellex0 
I believe the url is newprojects without the '-'.  Try that.  And then I'll wait to decide what to do with the different .svg files.  If it's decided to use two different sizes or just use the one size and let the css handle the resize of the svg file.  I did notice in mobile view it appears to resize and looked fine to me.

2021-07-05 17:34 UTC, averdin2 commented
@daniellex0 The page is accessed at /newprojects I believe. In regards to number 3, I think you answered my question in that there should only be one image file. As for number 2 and where the file should be placed, thanks for the heads up that the home page style files are going to be removed. It will probably be best to leave some of those styles in the files of this PR. I will bring up this topic in Tuesday's meeting and get back to @wendywilhelm10 on how to proceed.

2021-07-07 01:48 UTC, daniellex0 commented
> If it's decided to use two different sizes or just use the one size and let the css handle the resize of the svg file. I did notice in mobile view it appears to resize and looked fine to me.

Yes, please just use the one size! As far as I'm aware that's usually the case (but feel free to check out other header images on other pages, like Join Us, for reference)

2021-07-07 23:05 UTC, averdin2 requested changes
@wendywilhelm10 I spoke with the team regarding the issues I had brought up. Here are the changes we discussed. I also want to reiterate that when you make changes to file names and their locations, remember to update the references to them in the other files.

2021-07-07 23:05 UTC, averdin2 commented on _data/internal/credits/design-team.yml
> +image-url: /assets/images/join-us/design-team.svg
In regards to the multiple design-team image files, we are going to just use the projects-hero.svg image. Make sure to remove the design-team.svg file from the files. We also need the projects-hero.svg file to be in a new folder called "projects-page" within the images folder. It is currently placed within the projects folder, but this folder is for the individual projects' images. We want to have a distinction between these project images and the images used specifically for the projects page.

2021-07-07 23:05 UTC, averdin2 commented on _sass/components/_new-projects.scss
> +}
Lines 1 - 55 are really similar to lines 14 - 68 in the "_credit-items.scss" file. We want to avoid having duplicate classes that are just named differently. If the same classes are being used in two different places, then we should standardize these classes in case they may be used elsewhere. I suggest that these classes could possibly be placed into the "elements/_containers.scss" folder.

2021-07-07 23:05 UTC, averdin2 commented on _sass/components/_new-projects.scss
> +
Lines 57 - 171 are duplicated below from lines 172 to the bottom. We can remove these duplicate lines starting from line 172. 

I also noticed that these lines are in two other files, "components/_projects.scss" and "components/_home.scss". You don't need to worry about these files for now as I am going to write an issue regarding these duplicate styles.

2021-07-13 23:22 UTC, jbubar reviewed
Maybe name the files projects-page?? This looks great! nice work! 🔥

2021-07-13 23:22 UTC, jbubar commented on pages/new-projects.html
> +permalink: /newprojects/
lets change this to 
```yaml
permalink: /projects/
```

2021-07-25 13:14 UTC, wendywilhelm10 commented on _data/internal/credits/design-team.yml
> +image-url: /assets/images/join-us/design-team.svg
Removed design-team.svg and created new folder called 'projects-page' and project-hero.svg is in this folder.

2021-07-25 13:15 UTC, wendywilhelm10 commented on _sass/components/_new-projects.scss
> +}
I put these classes in the suggested folder "elements/_containers.scss" and removed from here.

2021-07-25 13:16 UTC, wendywilhelm10 commented on _sass/components/_new-projects.scss
> +
I removed the duplicated lines

2021-07-25 13:16 UTC, wendywilhelm10 commented on pages/new-projects.html
> +permalink: /newprojects/
I did change to /projects/

2021-07-26 17:51 UTC, jbubar submitted a review, later dismissed

2021-07-26 17:51 UTC, jbubar commented on _sass/components/_credit-items.scss
> +<<<<<<< HEAD
Hey @wendywilhelm10 you have to delete lines 14, 15, and 97. they are remnants of fixing merge conflicts, and they will break the css

2021-08-04 00:14 UTC, averdin2 commented on _sass/components/_credit-items.scss
> +<<<<<<< HEAD
@wendywilhelm10 Good job on fixing the leftover merge conflict text.

2021-08-04 00:15 UTC, averdin2 submitted a review, later dismissed
@wendywilhelm10 Good job on this issue Wendy. Everything looks great now. Should be good to go!

2021-08-04 19:52 UTC, Aveline-art commented
Right before merging this issue, there needs to be a new issue that preserves the work done in #2012 . The new issue should have a dependency which is for this issue to merge. Before making the issue, please make sure that it does not exist first. Thank you!

2021-08-07 05:01 UTC, Aveline-art commented
@wendywilhelm10 I've noticed that there are several merge conflicts that popped up. This is happening because our pacing was really fast this week. Since @averdin2 has approved this, I want to merge this as soon as the conflicts are resolved and get this out of review. I can also resolve the conflicts from my end, if you'd like. Let me know what your plans are, as getting this page out is one of our current top priorities.

2021-08-08 19:24 UTC, averdin2 approved these changes
Looks good!

2021-08-08 19:24 UTC, merged

2021-08-08 19:25 UTC, averdin2 commented
@wendywilhelm10 Really awesome job with this PR! Thanks for hanging in there 🔥

2021-08-08 19:26 UTC, averdin2 commented
@Sihemgourou We can make a new issue to hide the looking for filter.