Header mobile
hackforla/website pull request #1861
Opened 2021-06-30 01:01 UTC by Abel-Zambrano

Fixes #1596 

  - Decreased the margin between heading and top nav bar to 32px (2rem) - only in mobile
  - Increased margin between heading and paragraph to 28px total - only in mobile
  - Increased margin between header paragraph and illustration to 36px total - only in mobile
  - Decreased the size of the header illustration to max-width 256px - only in mobile

### Screenshots of Proposed Changes Of The Website
<details>
<summary>Changes</summary>
<summary>Before</summary>
<img width="376" alt="Screen Shot 2021-06-29 at 5 57 44 PM" src="https://user-images.githubusercontent.com/67209686/123886215-d238d000-d903-11eb-9786-d23a309846f8.png">
<summary>After</summary>
<img width="335" alt="Screen Shot 2021-06-29 at 5 59 30 PM" src="https://user-images.githubusercontent.com/67209686/123886223-d5cc5700-d903-11eb-8762-84a9a40a49a8.png">

Paste_Your_Image_Link_Here

</details>

2021-06-30 14:16 UTC, Zak234 reviewed
There seems to be some problems with the issue as #1596 and #1825 seem to both be requesting similar changes to the header illustration. Additionally, the margin in between the paragraph text and header illustration seems to be much larger than shown in the mock up photo shown in #1596 and I think this may be due to you using rem instead of px but I am unsure.

2021-06-30 23:35 UTC, Aveline-art commented
Per @Zak234 's comment, #1596 and #1825 appears to be overlapping issues. @daniellex0 Can you clarify if one issue supersedes the other or if both should be reviewed and merged?

2021-07-01 06:14 UTC, jbubar requested changes
@Abel-Zambrano you did a great job with this one. you did everything written on the issue. I do have one request. 

Could you use percentage for the max-width of the image, instead of pixes?
I know the issue says otherwise, but if you do 70% it should be around 256px; for the small view that danielle had in the issue. 
<details>
    <summary>how it looks on resizing as compared to the join us page</summary>

![abel's-css-thing](https://user-images.githubusercontent.com/53061723/124074691-b82ce980-d9f8-11eb-8bb7-4cb635148db0.gif)


</details>

2021-07-01 06:14 UTC, jbubar commented on _sass/components/_program-areas.scss
> +      max-width: 256px;
Hey @Abel-Zambrano could you actually use percentage here? use `max-width: 70%`

2021-07-01 06:17 UTC, jbubar commented
@Aveline-art @Zak234. Thanks for noticing the redundancy. I took the liberty to separate out the issues and issue #1825 should not include this. @daniellex0 I hope this is ok.

2021-07-02 02:27 UTC, Abel-Zambrano commented
@jbubar the requested changes are complete.

2021-07-04 04:02 UTC, daniellex0 commented
@jbubar yup that's fine!

2021-07-04 20:18 UTC, Abel-Zambrano commented on _sass/components/_program-areas.scss
> +      max-width: 70%;
Made the changes requested @jbubar

2021-07-04 22:30 UTC, jbubar commented
@Abel-Zambrano this is ready to merge, but there are some minor merge conflicts, Let me know if you need a hand with it

2021-07-05 19:21 UTC, Abel-Zambrano commented
@jbubar I resolved the conflicts, ready for review.

2021-07-06 18:27 UTC, jbubar commented
@Abel-Zambrano This looks ready to merge, but there was a mistake with another merge, so I want to revert that and check before merging this.. You can feel free to pick up another issue

2021-07-07 17:53 UTC, jbubar commented
sorry @Abel-Zambrano, there are merge conflict again. there was a mix up with another issue, which should not have been merged and needed to be reverted.

2021-07-07 17:53 UTC, jbubar commented
It caused the merge conflicts the first time, and it is causing them again because we reverted it

2021-07-08 00:56 UTC, Abel-Zambrano commented
@jbubar conflicts fixed.

2021-07-09 03:03 UTC, jbubar requested changes
Hey. did you notice the duplicate code? ![Screen Shot 2021-07-08 at 7 29 01 PM](https://user-images.githubusercontent.com/53061723/125014596-db701e00-e022-11eb-93a5-3eee29483a64.png)
 also there is a missing "}"

2021-07-09 16:22 UTC, Abel-Zambrano commented
I removed the duplicate code. @jbubar

2021-07-10 18:30 UTC, jbubar requested changes

2021-07-10 18:30 UTC, jbubar commented on _sass/components/_program-areas.scss
>  .program-areas-hero-svg {
The opening bracket on this line is never closed.

2021-07-10 18:39 UTC, jbubar commented on _sass/components/_program-areas.scss
>  .program-areas-hero-svg {
<details>
    <summary>error that I got when I ran `docker compose up`</summary>

![Screen Shot 2021-07-10 at 11 38 19 AM](https://user-images.githubusercontent.com/53061723/125173301-75df7700-e173-11eb-9205-a8888e6d3314.png)


</details>

2021-07-10 19:21 UTC, closed without merging