Standardize Program Areas for Mobile
hackforla/website pull request #1863
Opened 2021-06-30 03:21 UTC by Zak234

Fixes #1825
### What changes did you make and why did you make them ?

  -Added a mobile media query that sets the .program-areas-hero-svg max width to 300px and its height at 180.17px as per the figma mockup. This was done to resize the image to fit on the mobile page.
  -Added a mobile media query that sets padding-inline-start to 58px for &-list-alignment as per the figma mockup. This was done to center the mini project cards instead of having them left aligned.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
-Before
![IMG-1414](https://user-images.githubusercontent.com/85966467/123896829-2bf6c580-d917-11eb-895a-d9ad8cf8d284.jpg)
![IMG-1415](https://user-images.githubusercontent.com/85966467/123896848-344f0080-d917-11eb-9ada-b6fc2e03355e.jpg)
-After
![IMG-1412](https://user-images.githubusercontent.com/85966467/123896862-3ca73b80-d917-11eb-9c70-3b444c7670e4.jpg)
![IMG-1413](https://user-images.githubusercontent.com/85966467/123896883-4466e000-d917-11eb-9f87-f9b0edae0e3f.jpg)

2021-06-30 14:19 UTC, Zak234 commented
There may be a conflict between issues #1825 and #1596, so hold off on merging this issue.

2021-07-01 04:55 UTC, Aveline-art commented
Hi @Zak234 . Would it be possible to use the screenshot feature through your browser rather than through an outside lens to capture the before/after photos? Also, if there is no special reason, it is nice to have the photos sized smaller, and surrounded with a ```<details>/<summary>``` tag. The way to resize them is to use ``` <img src="" width="" length="" />``` tags.

2021-07-01 05:43 UTC, jbubar requested changes
Hey @Zak234 great job so far!
I have a few request. Can you delete the css you have for the header/hero, and use a different method for centering?

2021-07-01 05:43 UTC, jbubar commented on _sass/components/_program-areas.scss
> +    @media #{$bp-below-tablet} {
Lets delete this whole media query and let @Abel-Zambrano take care of it in his issue. #1596

2021-07-01 05:43 UTC, jbubar commented on _sass/components/_program-areas.scss
> +        padding-inline-start: 58px;
This is a clever way of faking it to be centered in some views, but it does not work for every view..  I recommend using flexbox for centering. 
Check out [this article](https://css-tricks.com/snippets/css/a-guide-to-flexbox/).. its kinda the flexbox bible.

2021-07-02 18:34 UTC, akibrhast commented
Side Note:
It looks like "screen shots" are not screen shots but rather photos taken by a mobile device. Please ensure that you do screen shots. It provides better image clarity

2021-07-04 18:43 UTC, Zak234 commented
Got it.

2021-07-04 23:44 UTC, jbubar commented
@Zak234 it will probably just be 
`justify-content: center;` 
inside of the below tablet media query. 
The margins that are on the mini project cards might cause some problems. maybe you balance that out with. padding-inline-start?

Let me know if you are stuck on this

2021-07-06 06:36 UTC, closed without merging