Update Wins About page,1835
hackforla/website pull request #1870
Opened 2021-07-01 04:27 UTC by anonymousanemone

Fixes #1835 

### What changes did you make and why did you make them ?

  - Remove 'coming soon' in the Wins section and replace it with a link to the Wins page (see image below)
  - Change the Wins title to black (use the variable for black # 333, and keep the icon pink) because user testing in the past showed hfLA users confuse pink titles for links
  - Evenly align the Wins title and the icon- see image below for reference and/or
 

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

![image](https://user-images.githubusercontent.com/86015625/124064557-e1924900-d9e9-11eb-8064-18fbb4ad2017.png)

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
![image](https://user-images.githubusercontent.com/86015625/124064516-caebf200-d9e9-11eb-9b13-c5c3b8fbc1a1.png)

</details>

2021-07-02 04:24 UTC, Zak234 approved these changes
Everything looks good!

2021-07-02 17:04 UTC, akibrhast commented
@hackforla/website-merge What is the next step here ?

2021-07-02 18:13 UTC, Aveline-art commented
> @hackforla/website-merge What is the next step here ?

This needs a second reviewer, ideally not me, since I do need to leave space for other members to also practice reviewing PRs. If the issue is not particularly urgent, could this be left for another day? Is there a soft or hard time frame for a second review after the approval of a first reviewer?

2021-07-02 18:26 UTC, akibrhast commented
> If the issue is not particularly urgent, could this be left for another day? 

It definitely can be, but it would decrease overall velocity.

> Is there a soft or hard time frame for a second review after the approval of a first reviewer?

Not that I am aware of. 24 hours ?


imho, 
- I think this sort of situation is very subjective and needs to be dealt on a case by case basis. Particularly, in regards to the group of people here doing the internship. @Zak234 @anonymousanemone and a few others. I believe bonnie wants them to be on the fast track and get a lot of experience. I have also noticed them making pull requests very often , as such I am of the opinion that holding them up is not doing them any favors since they are here for a limited time.

2021-07-03 09:05 UTC, abuna1985 requested changes
You did a really good job matching the Figma design for the desktop view. I just have one suggestion.

This is the figma design in mobile view (iPhone X)
<details>
  <summary>About Page (mobile view) figma design</summary>
  <img src="https://user-images.githubusercontent.com/21162229/124348974-bc483b00-dba1-11eb-9b67-e2bc98bb6131.jpg" />
</details>

This is the same section in mobile view (iPhone X) on your branch
<details>
  <summary>About Page (mobile view) your branch</summary>
  <img src="https://user-images.githubusercontent.com/21162229/124348909-81460780-dba1-11eb-8c5b-44a5669cd58d.jpg" />
</details>

@anonymousanemone notice the card on your branch is currently shorter on the left/right side and not the same length as the text above it? Can you make sure the card matches the [Figma design](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=1803%3A13692) in mobile (iPhone 8-11)? It looks you may need to decrease the card margin (left/right) in mobile view.

Thank you.

2021-07-07 00:18 UTC, abuna1985 commented
@anonymousanemone. After doing a bit of research, I may have found the reason why it looks shrunk. The `<svg>` for mobile card view comes in like this:

<details>
  <summary>Screenshot of img/svg element</summary>
  <img src="https://user-images.githubusercontent.com/21162229/124677398-37953f80-de75-11eb-83cf-f1b3eca5afe1.jpg" />
</details>

As you can see, the width of this element is 307px. But the intrinsic size for this is 338px. so it seems like we have a 30px border of extra space. We basically need to remove it. From my research [within this CSS tricks article on svg](https://css-tricks.com/using-svg/), it seems like we don't have very much control of the styling an SVG when it is nested in a `<img>`. But we do have control of the `<img>` element.

We can discuss a solution with @akibrhast @Aveline-art @averdin2 and @jbubar tonight to see if we can come up with a solution at the meeting tonight.

2021-07-09 15:41 UTC, abuna1985 approved these changes
It seems like the svg space is a medium separate issue. All your current changes look good. Thank you for your patience and understanding.

2021-07-09 23:23 UTC, merged