Added link to credits and join us page in footer
hackforla/website pull request #1880
Opened 2021-07-02 07:49 UTC by marcobarrera

Fixes #1871 

### What changes did you make and why did you make them ?

  - I added a link to the credits and join us pages in the footer
  - I rearranged the footer to fit the figma design

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

<img width="1437" alt="Screen Shot 2021-07-02 at 12 46 09 AM" src="https://user-images.githubusercontent.com/24802803/124239813-f399e780-dace-11eb-96e6-186729a39d47.png">

<img width="309" alt="Screen Shot 2021-07-02 at 12 47 10 AM" src="https://user-images.githubusercontent.com/24802803/124239961-1926f100-dacf-11eb-9f06-ad5474d6bd6b.png">

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
<img width="1439" alt="Screen Shot 2021-07-02 at 12 44 30 AM" src="https://user-images.githubusercontent.com/24802803/124239621-c0efef00-dace-11eb-9861-b034390aaf7e.png">

<img width="309" alt="Screen Shot 2021-07-02 at 12 48 08 AM" src="https://user-images.githubusercontent.com/24802803/124240051-36f45600-dacf-11eb-85bf-4d724f449e33.png">

</details>

2021-07-08 02:38 UTC, Aveline-art requested changes
Great work on this. The new footer looks great. There are a couple of fixes that needs to happen, but I think this should be good after fooling around with the CSS a bit more.

Just to note while I was testing the responsiveness of the website, there's a certain resolution where the lack of margins made footer elements seem compressed. Using the mobile variable might fix it, but be sure to check for responsiveness!

<details>
<summary>Example of compressed elements</summary>
<br>
<img src="https://user-images.githubusercontent.com/62368440/124853273-73ee9b80-df5a-11eb-9ba1-3e5d9e26aa94.jpg" width="600" length="300" />
<br>
</details>

2021-07-08 02:38 UTC, Aveline-art commented on _sass/components/_footer.scss
> +
I have a couple of things to note:

1) I think it is better to use our variables for device breakpoints rather than hard code a max-device-width. If you scroll up on this file, you can see an example ```$bp-tablet-up```.

2) ``!important``` might not be best to use here, even though these are new classes, if we ever expand on them or want to change things around them, ```!important``` might prove to be more of a hassle down the line. Can you play around with the CSS a little more and see what options there are to adjust the donate button and the links?

3) Less of a fix and more because I am curious, but why .btn--donate-footer and .footer-links?

2021-07-08 07:52 UTC, marcobarrera commented on _sass/components/_footer.scss
> +
Thanks for the suggestions. I fixed the responsiveness using the variables you suggested.

Regarding the class names, the class `.btn--donate-footer` was already there and I named the class `.footer-links` because it represents the links except for the donate button.

2021-07-09 23:22 UTC, Aveline-art approved these changes
Thank you @marcobarrera ! Everything looks great!

2021-07-09 23:22 UTC, merged