Standardized credits page header in mobile
hackforla/website pull request #1896
Opened 2021-07-07 00:43 UTC by marcobarrera

Fixes #1598 

### What changes did you make and why did you make them ?

  - I changed the padding and margin to the header in the Credits page in mobile to make it consistent with other pages and our design system.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

<img width="286" alt="Screen Shot 2021-07-06 at 5 39 55 PM" src="https://user-images.githubusercontent.com/24802803/124683144-3ff37780-de81-11eb-9dbe-d1ffaddb0b44.png">

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
<img width="285" alt="Screen Shot 2021-07-06 at 5 41 02 PM" src="https://user-images.githubusercontent.com/24802803/124683225-64e7ea80-de81-11eb-9740-fe7944af1399.png">

</details>

2021-07-07 03:46 UTC, arghmatey requested changes

2021-07-07 03:46 UTC, arghmatey commented on _sass/components/_credit-items.scss
> +      font-size: 40px;
Use rem instead of px here. It should be 2.5rem

2021-07-07 03:47 UTC, arghmatey commented
Looks great, @marcobarrera! I've requested one change, but this should be good for a second review and merge after that's fixed.

2021-07-07 04:31 UTC, marcobarrera commented
@arghmatey Good catch! I just fixed that issue

2021-07-08 01:30 UTC, arghmatey approved these changes

2021-07-08 01:31 UTC, arghmatey commented
This needs a second reviewer, then is good to merge. 👍

2021-07-09 03:48 UTC, merged