Create newcomers redirection file
hackforla/website pull request #1913
Opened 2021-07-10 06:06 UTC by vickiychung

Fixes #1890 

### What changes did you make and why did you make them ?

  - Created `newcomers.md` in the `redirections` directory

2021-07-10 11:21 UTC, Zak234 submitted a review, later dismissed
Everything seems to be working. Good job!

2021-07-10 16:08 UTC, macho-catt requested changes
Looks good and the redirection works for me as well! A couple of things (very minor typos/grammar), newcomer is one word, so the title should be Newcomers, not New Comers. Also, in the comment, 'redirections' should be 'redirects.'
Otherwise, it's good.

2021-07-10 16:09 UTC, macho-catt commented on redirections/newcomers.md
> +title: New Comers
should be Newcomers (one word)

2021-07-10 16:12 UTC, macho-catt commented on redirections/newcomers.md
> +# https://www.hackforla.org/newcomers redirections to -> https://github.com/hackforla/website/wiki/Being-a-Part-of-the-Hack-For-LA-Team
'redirections' here should be 'redirects' instead

2021-07-11 06:26 UTC, vickiychung commented on redirections/newcomers.md
> +title: New Comers
Updated! Thanks

2021-07-11 06:27 UTC, vickiychung commented on redirections/newcomers.md
> +# https://www.hackforla.org/newcomers redirections to -> https://github.com/hackforla/website/wiki/Being-a-Part-of-the-Hack-For-LA-Team
Updated

2021-07-11 16:41 UTC, macho-catt approved these changes
lgtm!

2021-07-12 01:25 UTC, merged