Adding design system heading classes to Sitemap page
hackforla/website pull request #1918
Opened 2021-07-11 10:52 UTC by aliibsin

Fixes #1877 

  - Added header classes `title1` and `title4` to headers `h1` and `h3`, respectively, on Sitemap page per [figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3164%3A18)
  - Replaced header tags with their respective classes on sitemap.scss to make header selection more specific. Can be changed back to their original `h1` and `h3` if needed.
  - Removed any `font-size` changes for headers on sitemap.scss so they do not overwrite the design system heading class font sizes.

<details>
<summary>Figma screenshot</summary>

![image](https://user-images.githubusercontent.com/77088922/125191369-df549980-e1f6-11eb-91b8-c2fb99ddab64.png) 

</details> 

<details>
<summary>Visuals before changes are applied</summary>

![image](https://user-images.githubusercontent.com/77088922/125191616-3870fd00-e1f8-11eb-8e35-9b0a0b5f15a1.png)
![image](https://user-images.githubusercontent.com/77088922/125191621-3f980b00-e1f8-11eb-8b3d-893cc19e0193.png)

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
![image](https://user-images.githubusercontent.com/77088922/125191582-11b2c680-e1f8-11eb-8036-f4703d583ca6.png)
![image](https://user-images.githubusercontent.com/77088922/125191597-242d0000-e1f8-11eb-923a-e72c44576b41.png)

</details>

Please note that the original desktop font size for the `h1` is 40px whereas the design system heading class `title1` font size is 48px. This explains the discrepancies for the main title.

2021-07-14 16:45 UTC, Zak234 approved these changes
Everything seems to be working. Good job!

2021-07-15 21:54 UTC, macho-catt commented
I took a quick look at this PR, and it looks like it might conflict with my PR for issue  #1887.
@jbubar @abuna1985 @aliibsin @Aveline-art  any suggestions on what we can do?
Thanks.

2021-07-15 22:02 UTC, averdin2 commented
@macho-catt I am currently reviewing this. Based on what PR gets merged first, if there are merge conflicts with either PR, then I can help either of you sort them out.

2021-07-15 22:15 UTC, averdin2 requested changes
@aliibsin Good job on this issue! I saw some old commented-out code in _sass/components/_sitemap.scss (lines 24 - 28) that could be removed. After you clean that up everything will be ready to merge. As per @macho-catt's comment, we may also need to fix merge conflicts if that PR #1912 gets merged first.

2021-07-15 22:15 UTC, averdin2 commented on _sass/components/_sitemap.scss
>      margin-top: 8px;
Lines 24 - 28 seem to be old commented-out code that isn't needed anymore. Let's just clean that up and everything looks good to merge.

2021-07-15 22:23 UTC, averdin2 approved these changes
@aliibsin Disregard the previous comment https://github.com/hackforla/website/pull/1918#pullrequestreview-707861955. I saw that @macho-catt's PR #1912 fixes what I told you to fix, so I am going to merge this and help @macho-catt deal with any merge conflicts.

2021-07-15 22:24 UTC, merged