Wins mobile margins
hackforla/website pull request #1928
Opened 2021-07-12 19:46 UTC by anonymousanemone

Fixes #1908 

### What changes did you make and why did you make them ?

  - replaced wins-card-mobile.svg with a new svg that does not include shadows as part of the .svg
  - added shadows to wins-card-mobile.svg using css in _about.scss instead
  - added </a> about-card-accomplishments because wins-card-desktop had it, but mobile didn't

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals after changes are applied</summary>

![after](https://user-images.githubusercontent.com/86015625/125346567-c6d7a280-e30e-11eb-9a7a-dacf81ca7ccb.png)

</details>

<details>
<summary>Visuals before changes are applied</summary>
  
![Screen Shot 2021-07-12 at 12 44 44 PM](https://user-images.githubusercontent.com/86015625/125346745-f4245080-e30e-11eb-8faf-3344272267ee.png)

</details>

2021-07-12 23:38 UTC, jbubar submitted a review, later dismissed

2021-07-12 23:38 UTC, jbubar commented on _sass/components/_about.scss
> +  color: #333;
could you use `$color-black` instead of `#333`. it is the same

2021-07-12 23:40 UTC, jbubar commented on _sass/components/_about.scss
> +  color: #333;
ooh. actually, I think you can just delete that line, because that is the default color

2021-07-13 21:53 UTC, anonymousanemone commented on _sass/components/_about.scss
> +  color: #333;
fixed

2021-07-14 16:23 UTC, anonymousanemone commented on _sass/components/_about.scss
> +  color: #333;
@jbubar

2021-07-16 17:07 UTC, Zak234 submitted a review, later dismissed
The changes you made look good and seem to be working. I'm pretty sure this isn't related to your issue but I noticed when I was checking your code changes through different phone resolutions that for a lot of the other phone resolutions besides iphone X that the wins-card is off-center. Should this be a new issue?

2021-07-16 17:58 UTC, Aveline-art commented
@Zak234 Can you attach screenshots of what you are seeing vs the appearance of the mobile view on Figma?

2021-07-17 19:40 UTC, abuna1985 commented on pages/about/about-card-accomplishments.html
> +                <div class="wins-card-mobile"><a href="https://hackforla.org/wins" target="_blank" rel="noopener noreferrer"><img src="/assets/images/about/wins-card-mobile.svg" alt="The wins card di
Good catch. I kept trying to figure out why when I hovered over the `<a>` tag why it didn't cover the image. This is why.

2021-07-17 21:41 UTC, abuna1985 requested changes
Following up on @Zak234 comment. It's looks great on desktop/mobile view. It seems the tablet view just aligns to the left.

<details>
  <summary>Tablet view (iPad) of About page (Accomplishments)</summary>
  <img src="https://user-images.githubusercontent.com/21162229/126049751-473a957d-01fa-45da-b2bb-c2156d0bbe9b.jpg" />
</details>

It looks like the the card flexbox converts to column in tablet view and since we are providing a width to the svg, it aligns to the left (start). So maybe add styling for tablet view (line 604-618).

2021-07-21 00:46 UTC, Zak234 commented
<img width="1406" alt="Screen Shot 2021-07-21 at 1 29 14 AM" src="https://user-images.githubusercontent.com/85966467/126412259-da4ac42e-7e58-409f-a1d2-c68462ae5764.png">
<img width="1411" alt="Screen Shot 2021-07-21 at 1 29 57 AM" src="https://user-images.githubusercontent.com/85966467/126412368-84e430bc-c8f1-40f0-8675-7bda892bbc9f.png">
<img width="1413" alt="Screen Shot 2021-07-21 at 1 30 23 AM" src="https://user-images.githubusercontent.com/85966467/126412484-e94b91ff-2c68-40ee-a28f-9083d846d26b.png">
<img width="1411" alt="Screen Shot 2021-07-21 at 2 23 46 AM" src="https://user-images.githubusercontent.com/85966467/126412941-7abd795e-1486-42ad-b48b-67c90450d360.png">

2021-07-29 16:21 UTC, anonymousanemone commented
I've centered the image for "below tablet" which is when the screen is under 768px, but should I also center the image for when it is "bigger than tablet" but less than desktop? Here's how it looks:
Below tablet: 
![image](https://user-images.githubusercontent.com/86015625/127528782-aa628e6b-46b5-4723-8e98-7b5f97757064.png)
Over tablet: 
![image](https://user-images.githubusercontent.com/86015625/127528797-b1bd8138-1052-42ba-984c-a5a62786e90f.png)

2021-08-01 18:16 UTC, anonymousanemone commented
Ask design team about whether to center or do something else

2021-08-05 18:57 UTC, kristine-eudey commented
@anonymousanemone thanks for checking in about this. Please center the card for the "bigger than tablet" view as well.

2021-08-06 16:10 UTC, anonymousanemone commented
I've made both of the changes requested above, please re-review! @jbubar @abuna1985

2021-08-08 17:04 UTC, Zak234 approved these changes
Looks good!

2021-08-08 21:49 UTC, macho-catt commented
For the most part, changes on the page card itself looks good. Good job!

I also noticed that you've been working on this for a while, so props to you on that. However, I noticed one other thing that may not be in the jurisdiction of your issue/PR.

@Zak234 noticed it in one of his previous posts, but at a certain BP the parent cards are cutting off. This is due to the fact that flex (or any mobile responsive query) is not applied to the parent divs at specific BPs:
<details>
<summary>Click to see example</summary>

![cut off below a certain bp](https://user-images.githubusercontent.com/48004150/128646593-fe55eb40-8e86-406d-9039-8ff5f5dc95ea.png)

 </details>

The fix would be to apply flex (or some sort of media query) on the parent divs for each section of the About page.

@Aveline-art @abuna1985 is it better to open up a new issue for this? Otherwise, I would be inclined to approve this issue.

2021-08-08 21:50 UTC, macho-catt reviewed
For the most part, changes on the page card itself looks good. Good job!

I also noticed that you've been working on this for a while, so props to you on that. However, I noticed one other thing that may not be in the jurisdiction of your issue/PR.

@Zak234 noticed it in one of his previous posts, but at a certain BP the parent cards are cutting off. This is due to the fact that flex (or any mobile responsive query) is not applied to the parent divs at specific BPs:
<details>
<summary>Click to see example</summary>

![cut off below a certain bp](https://user-images.githubusercontent.com/48004150/128646593-fe55eb40-8e86-406d-9039-8ff5f5dc95ea.png)

 </details>

The fix would be to apply flex (or some sort of media query) on the parent divs for each section of the About page.

@Aveline-art @abuna1985 is it better to open up a new issue for this? Otherwise, I would be inclined to approve this issue.

2021-08-09 07:19 UTC, abuna1985 commented
@macho-catt Go ahead and create a new issue for adding margin to the parent divs of the About page. Once that is complete, add it to this or as a comment and approve the pull request. Then I will merge it. Thank you.

2021-08-10 05:10 UTC, macho-catt commented
Opened a separate issue for the cutting off bug: #2077

2021-08-10 05:10 UTC, macho-catt approved these changes

2021-08-10 18:40 UTC, merged