Fix join us footer 1427
hackforla/website pull request #1951
Opened 2021-07-15 20:47 UTC by GLRJr

Fixes #replace_this_text_with_the_issue_number

### What changes did you make and why did you make them ?

  -My previous pull request accidentally deleted an image, this pull request replaces image
  -
  -

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

![image](Paste_Your_Image_Link_Here_After_Attaching_Files)

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
![image](Paste_Your_Image_Link_Here_After_Attaching_Files)

</details>

2021-07-18 01:55 UTC, abuna1985 reviewed
@GLRJr  Good job implementing the element within the Program Areas page. I know this is a 2nd pull request, but for future reference, please fill out the pull request or link the previous pull request for the reviewer.

The mobile view is missing some CSS. I will add a comment in the code with more details.

2021-07-18 02:32 UTC, abuna1985 requested changes
Changes have been requested.  As soon as it is resolved, I will complete another review. Good job so far.

2021-07-18 02:32 UTC, abuna1985 commented on _sass/components/_program-areas.scss
> +  @media #{$bp-below-tablet} {
So the Mobile CSS is not being applied because of the structure

```
/* What is currently in your pull request */
/* line 237 */
...
 @media #{$bp-below-tablet} {
    .join-us-footer-description {
      display: flex;
      flex-direction: column;
      align-items: center;
    }

   /* This is not being read*/
    .join-us-footer-body {
      display: flex; /* This can be removed because it is already flex*/
      flex-direction: row; /* Also it is still row, so this can be removed to */
      justify-content: space-evenly;
      align-items: center;
      min-height: 314px;
      margin: 36px auto; /* I don't think you need top/bottom margin */
    }
...
```

This is nested in the `.join-us-footer-body` so you just need to apply the styling within `@media #{$bp-below-tablet}` . I was able to fix this by doing the following:

```
...
   /* remove .join-us-footer-body  and nest the following within media */
   /* line 237 */   
  @media #{$bp-below-tablet} {
     justify-content: space-evenly;
     align-items: center;
     min-height: 314px;
     margin: 0 auto;

     .join-us-footer-description {
        display: flex;
        flex-direction: column;
        align-items: center;
     }   
...
```

<details>
  <summary>Visual result of my changes with CSS</summary>
  <img src="https://user-images.githubusercontent.com/21162229/126053545-cf22d3f9-0081-41ff-b342-6a5f0a4a1d6c.jpg" />

</details>

2021-07-21 02:38 UTC, GLRJr commented
Made all recommended changes

2021-07-21 15:05 UTC, Aveline-art requested changes
Hi @GLRJr, the footer looks great, the positioning is very close to the Figma design, and is very responsive to resolution changes! I have noticed that the p in projects is capitalized, and the last bit is bolded. I am not sure if they are supposed to be that way, so please confirm if they are.

<details>
<summary>Changes in this pull request</summary>
<br>
<img src="https://user-images.githubusercontent.com/62368440/126510495-c3bfec48-1e04-4e91-8462-b5299fb30cbe.png" width="600" length="300" />
<br>
</details>

<details>
<summary>Figma design</summary>
<br>
<img src="https://user-images.githubusercontent.com/62368440/126510502-6c0427e9-3be0-47a6-8c0b-f947ab61b210.png" width="600" length="300" />
<br>
</details>

Note: The Figma also has, "click through to their project pages", which sounds awkward. Can @hackforla/website-design confirm whether this is correct?

2021-07-27 05:15 UTC, abuna1985 approved these changes

2021-07-27 05:19 UTC, abuna1985 approved these changes, later dismissed
@GLRJr Thank you for making the changes. It looks good. If you could, please address @Aveline-art request and change the `Project` in the second paragraph to `project`.  Keep up the good work!

2021-08-01 17:04 UTC, GLRJr commented
Made changes to text, removed capital 'P' and bold text

2021-08-01 21:23 UTC, Aveline-art commented on pages/program-areas.html
> +            channel name.
Hi, @GLRJr ! Can you add a space after the `</a>`?

It should be:
`connect with the current project team <a href="https://hackforla-slack.herokuapp.com/"> join our slack </a> and browse for their`

2021-08-01 21:24 UTC, Aveline-art commented on pages/program-areas.html
> +            connect with the current project team <a href="https://hackforla-slack.herokuapp.com/"> join our slack </a>and browse for their
Hi, @GLRJr ! Can you add a space after the `</a>`?

It should be:
`connect with the current project team <a href="https://hackforla-slack.herokuapp.com/"> join our slack </a> and browse for their`

2021-08-05 18:35 UTC, Aveline-art approved these changes
LGTM! Thanks for sticking with this!

2021-08-05 18:35 UTC, merged