fix header image width for mobile screens
hackforla/website pull request #1953
Opened 2021-07-16 01:55 UTC by Abel-Zambrano

Fixes #1596 

  - changed image "width" + "max-width" to match other pages - mobile screen only

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>
<img width="423" alt="Screen Shot 2021-07-15 at 6 54 11 PM" src="https://user-images.githubusercontent.com/67209686/125879718-a55ba408-04ee-45ad-ab50-776e63b552fb.png">

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
<img width="418" alt="Screen Shot 2021-07-15 at 6 54 59 PM" src="https://user-images.githubusercontent.com/67209686/125879768-b0b1964f-4724-49ef-9f3e-1d9c5247a709.png">

</details>

2021-07-17 07:13 UTC, jbubar requested changes
Hey it looks good in mobile now.. but needs a little help on tablet. specifically between the 850px - 960px screen width range

sorry for continuing to give you more info on this issue. I hope we have not scared you away. lol. great work so far. keep it up

2021-07-17 07:13 UTC, jbubar commented on _sass/components/_program-areas.scss
> +      width: 80%;
This looks great. 
One more request...
can you make the desktop look like the join us page as well? the breakpoint is currently at  850px. It should probably be 960. which is `@media #{$bp-below-desktop}`.

2021-07-19 19:49 UTC, Abel-Zambrano commented on _sass/components/_program-areas.scss
> +      width: 80%;
Hey Josh, this actually should have been #{$bp-below-tablet}, to make the changes on mobile screens. I changed the breakpoint on another media query (on line 73). The page now works identical to the "Join Us" page.

2021-07-19 19:51 UTC, Abel-Zambrano commented
No, not at all. I enjoy this!

I made the changes, please take a look when you get a chance.

Thanks, Josh.

2021-07-21 01:35 UTC, jbubar approved these changes
Looks great!
Nice work

2021-07-21 01:36 UTC, merged