remove tablet view and fix responsiveness issues
hackforla/website pull request #1954
Opened 2021-07-16 06:30 UTC by jbubar

Fixes #1950

### What changes did you make and why did you make them ?

  - Removed the tablet view by expanding the mobile view to desktop

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

![Screen Shot 2021-07-15 at 11 30 02 PM](https://user-images.githubusercontent.com/53061723/125902597-4d458b64-ae3c-4b78-a06e-9ae847067386.png)

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
![Screen Shot 2021-07-15 at 11 27 32 PM](https://user-images.githubusercontent.com/53061723/125902352-0f60cb92-a619-433d-bce7-894f539ec147.png)

</details>

2021-07-17 07:46 UTC, jbubar commented
If you do not already have a `wins-feature-1` branch. please use this guide to create one...
https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch

2021-07-17 19:05 UTC, erikaBell requested changes
Great new tablet view!

I saw on Issue #1950 one of the check items was to make sure see less/see more functionality still worked, however I have found a bug where the "see more" functionality stops working, and "see less" gets stuck on desktop view, if it was already previously opened on smaller screen size. Everything returns to functionality when the page is refreshed. 

Video below showcases bug.

<details>
<summary>see more / see less bug</summary>


https://user-images.githubusercontent.com/67438372/126047127-e2b5131f-3447-45ac-b183-8f1a6bcddd33.mov


</details>

<details>
<summary>separate, CSS formatting</summary>

<img width="753" alt="Screen Shot 2021-07-17 at 11 38 17 AM" src="https://user-images.githubusercontent.com/67438372/126047137-99ea8804-9f7f-4d02-8f9f-e3e725311e3b.png">

</details>

2021-07-18 05:43 UTC, jbubar commented
Still working on this. I will ask for another review after I am done. thanks A bunch @erikaBell

2021-07-19 05:56 UTC, jbubar commented on pages/wins/wins.html
> +			  hideOverlay(e)
This fixed the unclickability on desktop

2021-07-19 05:57 UTC, jbubar commented on _sass/components/_wins-page.scss
> +.win-list{
This was to remove tablet view

2021-07-19 05:58 UTC, jbubar commented on pages/wins/wins-card-template.html
> +    <div class="wins-icon-container" id="icons-0"></div>
Added this to make the div more accessible... so you dont have to do element.parent.parent.parent.nextsibling or whatever

2021-07-19 05:59 UTC, jbubar commented on pages/wins/wins.html
> +	function insertIcons(cardSelector, cardString, viewType, cloneCardTemplate = document) {
REfactored this function to work with insertingIcons on the wins cards, and the overlay

2021-07-19 06:00 UTC, jbubar commented on pages/wins/wins.html
> -  	screenWidth = window.innerWidth;
changed this, because we should not be using global variables

2021-07-19 06:00 UTC, jbubar commented on pages/wins/wins.html
> +  document.addEventListener("DOMContentLoaded", winsBelowDesktop);
Added back in the clickability of the icons in mobile view

2021-07-19 06:23 UTC, abuna1985 approved these changes
@jbubar. Great job. I like the DRY approach you took to refactor the `insertIcons` function so it to work for overlay/mobile view.

 I have verified the tablet view now uses the mobile view. The show more/show less functionality also works in desktop, tablet, and mobile view properly.

My only recommendation would be to comment out line 525 within `pages/wins/wins.html` (console.log within the `hideOverlay` function. Other than that, this is ready to be merged.

2021-07-19 06:23 UTC, abuna1985 commented on pages/wins/wins.html
> +		console.log("in the hide overlay")
You may want to comment out this console.log

2021-07-19 23:54 UTC, averdin2 commented
@jbubar I am not sure if this issue was already there before you made changes, but I am seeing that when in tablet/mobile view if you click on a badge icon it opens up the see more view. If you click on the badge icon again, it closes the see more view and shows the text bubble/tooltip. This behavior seems a bit weird, I am not sure if we want the page to act this way. See the gif below for the visual.

<details>
<summary>Mobile View Tooltip Behavior</summary>

![Screen Recording 2021-07-19 at 4 27 36 PM](https://user-images.githubusercontent.com/10714770/126241235-bad7b03e-2c50-4ffa-9517-43c72bca0780.gif)
</details>

2021-07-19 23:58 UTC, marcobarrera approved these changes
The responsiveness is working. In tablet view (under 960px), it now has the same view as mobile. The see more/less links are also working fine on all cards.

2021-07-20 19:05 UTC, erikaBell commented
@jbubar Great, see more/less is working as expected now. I do agree with @averdin2's comment above. But that could be a separate issue, unless you want to handle it. Or if we want to check in with @daniellex0 first. 

Either way, nice work 🐸

2021-07-21 01:39 UTC, jbubar commented
@averdin2 cool idea. I will do that right now. @erikaBell Thanks for reviewing this! yes, I think I would like to put the styling in another issue. it will be a bit of a refactor.

2021-07-21 02:01 UTC, jbubar commented on pages/wins/wins.html
> +		console.log("in the hide overlay")
Thank you!!!

2021-07-21 06:44 UTC, erikaBell approved these changes
lg

2021-07-21 06:45 UTC, merged