Setting up GitHub Action for CSS and future linting
hackforla/website pull request #1957
Opened 2021-07-16 21:06 UTC by averdin2

Fixes #1441 

### What changes did you make and why did you make them?
 - I created a new file in .github/workflows called linter.yml, to make a new GitHub action for the website repo to act as a code linter.
 - This specific issue is dealing with setting up CSS linting for our repo, but this same GitHub action can be used for JavaScript linting as well.
 - I also added a stylelintrc.json file in the root of the project which is a configuration file for the CSS linting rules we want the GitHub action to run.

### Resources Used
 - The specific resource I used for the GitHub action is called [SuperLinter](https://github.com/marketplace/actions/super-linter). It is an official GitHub action for linting code made by Github themselves.
 - A list of the stylelint rules (including the ones in the .stylelintrc.json file) can be found [here](https://stylelint.io/user-guide/rules/list/).

### Notes
 - In the linter.yml file, on line 22 the `VALIDATE_ALL_CODEBASE: false` means that the GitHub action only checks committed files to the repo. The reason why I am not checking the entire codebase is that I do not believe it is necessary to run a check on the entire codebase for every pull request. I am going to make an issue and deal with all the errors that are in the current codebase as a result of running `VALIDATE_ALL_CODEBASE: true`. I believe after fixing these issues, only checking the files in new pull requests should be sufficient for linting the codebase.
 - The types of rules I implemented are only those whose failure would likely result in actual style errors like not enacting the proper styles. I did not add any rules that limit features or require more strict enforcement of particular code formatting rules. If linting rules like these wanted to be added in the future, we can do this by adding rules to the .stylelintrc.json file.
 - To add linting for another language (like JavaScript), we can use the same GitHub action to do so. (See [here](https://github.com/github/super-linter/blob/master/docs/using-rules-files.md))

2021-07-16 23:13 UTC, averdin2 commented
I made this pull request a draft because I ran into some potential linting annoyances when working on issue #1958. I want to see if I can configure some of the style rules to stop the problem I ran into before merging.

2021-08-01 18:21 UTC, GLRJr commented
@averdin2  will make review steps

2021-08-14 17:50 UTC, Aveline-art commented
@averdin2 Can we schedule a time to do a demo either on a Tuesday or Thursday meeting?

2021-08-27 03:24 UTC, averdin2 commented
@averdin2 Add on push back into linter config file.

2021-09-01 17:25 UTC, Aveline-art commented
@averdin2 From testing, I had found that the linting config files needs to be in both the incoming branch and the merge into branch. Without the files existing in both, I get this error:

```
Error: ENOENT: no such file or directory, open '/github/workspace/github/workspace/.stylelintrc.json'
```

Can you confirm that this is the case?

Also, the output from the linter is very useful, so I am wondering if the linter module provides a way of gathering or caching the data into a variable(preferred) or an artifact(less preferred)? That way, we can output it as a comment. If not, we might need a follow-up issue to add documentation on resolving linting issues.

2021-09-01 17:32 UTC, Aveline-art submitted a review, later dismissed
Just one small architectural change. Everything else is awesome!

2021-09-01 17:32 UTC, Aveline-art commented on .stylelintrc.json
> +    "property-no-unknown": true,
This file ideally needs to belong in a directory named linter inside the github-actions directory.

2021-09-03 16:06 UTC, macho-catt requested changes
Awesome work on this Alex! Just an additional thing after the backend meeting yesterday, we decided on a new structure for our Github actions. [Click here for google sheet](https://docs.google.com/spreadsheets/d/12NcZQoyGYlHlMQtJE2IM8xLYpHN75agb/edit#gid=1231634015).

Basically linters will be on their own files (so SCSS linting will be on its own, JS linting on its own, etc.)

To reflect that changes, could you edit the name of this action to something like "Lint SCSS" and rename the yml file to something like "lint-scss.yml"? Could you also update any other names in the workflow to reflect that.

Other than that, good job again on this.

2021-09-03 16:07 UTC, macho-catt commented on .github/workflows/linter.yml
> +name: Lint Code Base
Rename to Lint SCSS

2021-09-03 16:07 UTC, macho-catt commented on .github/workflows/linter.yml
> +    name: Lint Code Base
Rename to Lint SCSS

2021-09-03 16:08 UTC, macho-catt commented on .github/workflows/linter.yml
> +      - name: Lint Code Base
Rename to Lint SCSS

2021-09-19 17:23 UTC, abuna1985 commented
@Aveline-art will contact @averdin2 regarding the changes for pull request. @Aveline-art will complete the changes if needed.

2021-09-20 22:48 UTC, averdin2 commented on .stylelintrc.json
> +    "property-no-unknown": true,
@Aveline-art I purposely put this file in the root directory in the case that anyone has the stylelint extension in their text editor. This extension will allow you to see the CSS linting errors in your text editor. If members of our team have this extension, they won't have to wait to submit a PR to see the linting errors. If this config file is located elsewhere, the extension doesn't work.

2021-09-21 00:35 UTC, Aveline-art commented on .stylelintrc.json
> +    "property-no-unknown": true,
From looking briefly at [the extension settings](https://marketplace.visualstudio.com/items?itemName=stylelint.vscode-stylelint#extension-settings), it seems like the extension, at least for VScode, can be configured to read files that are not in the root directory. Can you verify if this is the case? If so, we can leave a comment on the GHA on how to use and configure it for VSCode.

2021-09-23 02:05 UTC, macho-catt approved these changes
I tested this once more in my environment, and it looks good to me. I do agree with @Aveline-art about finding a way to logging the outputs into a comment, or writing a doc on how to resolve linting errors. However, I think that is something we can open as a new issue.

2021-09-23 15:39 UTC, merged