Wins Spacing, between text and badge icons #1551
hackforla/website pull request #1964
Opened 2021-07-17 20:34 UTC by erikaBell

Fixes #1551 

### What changes did you make and why did you make them ?

  - remove extra spacing between the wins-text and wins-badge icons, as it was inconsistent between wins cards
  - refer to Danielle's screenshots in #1551 

### Screenshots of Proposed Changes Of The Website 

<details>
<summary>Visuals before changes are applied</summary>

<img width="938" alt="Screen Shot 2021-07-17 at 1 33 02 PM" src="https://user-images.githubusercontent.com/67438372/126048751-7c18c992-f28b-4320-acc9-c2239d64ff82.png">

<img width="362" alt="Screen Shot 2021-07-17 at 1 32 55 PM" src="https://user-images.githubusercontent.com/67438372/126048753-fc252753-a190-403d-8f89-b61e37629a43.png">

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
<img width="1295" alt="Screen Shot 2021-07-17 at 1 31 35 PM" src="https://user-images.githubusercontent.com/67438372/126048720-70e86624-6b38-4fb5-959f-db2bb02ac288.png">

<img width="356" alt="Screen Shot 2021-07-17 at 1 31 47 PM" src="https://user-images.githubusercontent.com/67438372/126048722-417d5d42-a284-44e9-9642-4a6e8d6cae40.png">

</details>

2021-07-20 03:03 UTC, Aveline-art commented
Good work @erikaBell ! I have noticed that there is a bit of spacing between the badges and paragraph in Figma. If it is not too hard, can you add a little bit of spacing back. It looks to be about "1 row of badges" worth of space.

<details>
<summary>Figma</summary>
<br>
<img src="https://user-images.githubusercontent.com/62368440/126255436-665cfd18-cddf-4447-930b-dc9a20d4df7c.png" width="600" length="300" />
<br>
</details>

<details>
<summary>wins-feature-1 after changes</summary>
<br>
<img src="https://user-images.githubusercontent.com/62368440/126255432-c41f64b4-ef3d-4f19-a202-1ee0d6ba9bf0.png" width="600" length="300" />
<br>
</details>

2021-07-20 03:04 UTC, Aveline-art requested changes
Good work @erikaBell ! I have noticed that there is a bit of spacing between the badges and paragraph in Figma. If it is not too hard, can you add a little bit of spacing back. It looks to be about "1 row of badges" worth of space.

<details>
<summary>Figma</summary>
<br>
<img src="https://user-images.githubusercontent.com/62368440/126255436-665cfd18-cddf-4447-930b-dc9a20d4df7c.png" width="600" length="300" />
<br>
</details>

<details>
<summary>wins-feature-1 after changes</summary>
<br>
<img src="https://user-images.githubusercontent.com/62368440/126255432-c41f64b4-ef3d-4f19-a202-1ee0d6ba9bf0.png" width="600" length="300" />
<br>
</details>

2021-07-20 16:49 UTC, daniellex0 commented
^Yes agreed with @Aveline-art , my only note is to add a little more space between the badges and paragraph text. The spacing is correct right now when there are 4 lines of a paragraph text, so however much is between the badges and the paragraph in those cases can be the norm. 

But other than that this looks perfect, thank you so much for figuring this out @erikaBell !!!! 💯

2021-07-20 16:49 UTC, daniellex0 commented
Tagging @kristine-eudey to see PR reviews :)

2021-07-20 18:50 UTC, erikaBell commented
@Aveline-art @daniellex0 Thanks (-: have gone ahead and added some more spacing. Lmk if this feels good for yeah!

2021-07-21 14:45 UTC, Aveline-art commented
@erikaBell Everything look perfect! There is a merge conflict, so once that is resolved, this is ready to merge!

2021-07-21 14:46 UTC, Aveline-art approved these changes
@erikaBell Everything look perfect! There is a merge conflict, so once that is resolved, this is ready to merge!

2021-07-21 15:06 UTC, daniellex0 commented
@erikaBell Yeah that looks great!

2021-07-21 18:55 UTC, jbubar commented
THis is great! These changes will make it easier to do the css fixes we need to do

2021-07-21 19:02 UTC, jbubar commented
@erikaBell I fixed the merge conflict, but I think it kinda messed things up. 

before working on it pull from your origin branch
```
git pull origin wins-badge-spacing
```

2021-07-21 19:02 UTC, jbubar commented
I have got to go to lunch, but I will message you after

2021-07-21 20:13 UTC, jbubar commented
Sorry I got a little excited...
You might want to also merge the wins-feature-1 changes...
```
git checkout wins-feature-1
git pull upstream wins-feature-1
git checkout wins-badge-spacing
git merge wins-feature-1

```

2021-07-21 21:34 UTC, jbubar approved these changes
Yay

2021-07-21 21:38 UTC, merged