GitHub action trim contributors
hackforla/website pull request #1986
Opened 2021-07-20 04:04 UTC by alexeysergeev-cm

Fixes #1710

### What changes did you make and why did you make them?

  - Created GitHub Action, yml file that runs every day at 3 am PST. The yml file checks out the repository, installs dependencies, and runs contributors-data.js using HACKFORLA_BOT_PA_TOKEN. 
  - Created contributors-data.js where the logic for removing inactive members lives.

### Checklist:

- [ ] HACKFORLA_BOT_PA_TOKEN works and allows authorized requests to GitHub API such as removing a member from a team.
- [ ] Output: list of active contributors since 'date', list of current members, array of removed members.

### Questions/Clarification:

- I could **not** find how and where to fetch data about WIKI contributors, Github seems to have **no** API for that. If a member only contributed to Wiki and never committed, commented, or created/assigned to issue, the member will be removed.
- Logic does not remove a member with a maintainer role, is that correct? 
- Some code needs adjustment such as fetching team members. Github allows to fetch max 100 items per request, once the team grows beyond 100 members, the code needs adjustment.
- I assumed that a member who cloned the repo within the last 30 days from today, considered to be a new member and not going to be removed from a team. This solves the next problem: imagine a user joined a team on the 15th of July, downloaded the repo, and currently works on setting up the environment. Code runs on the 16th of July and avoids removing the member.
- Code only works with **website-write** team, do we want to work it for **website** team as well?  
- Code runs every day, is that okay?

_Open to suggestions and ideas._

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

![image](Paste_Your_Image_Link_Here_After_Attaching_Files)

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
![image](Paste_Your_Image_Link_Here_After_Attaching_Files)

</details>

2021-07-20 15:03 UTC, Aveline-art requested changes
Splendid work on this @alexeysergeev-cm . This must have taken a lot of time and thoughts, and I am digging all the things you have considered. The changes are mostly stylistic changes and a number of them can be optional if you decide they are not a concern. I hope they are not too much? Some of the questions you proposed...I would need to get back to you later this week on them. I made this review so that there is something to work on in the meantime. Overall, this is amazing work! Glad to have you on the team.

2021-07-20 15:03 UTC, Aveline-art commented on .github/workflows/update-team-members.yml
> +
Let's actually run it every 2, or even every 3 weeks. When talking about designing the action, @akibrhast and I had considered up to 3 months to be the limit before settling on 1 month. If someone ends up being removed at say 1.3 months of inactivity, it is not a big deal. Running it everyday would create logs that pollute our log space.

2021-07-20 15:03 UTC, Aveline-art commented on .github/workflows/update-team-members.yml
> +
Should this be commented out? If this is required, there needs to be a comment.

2021-07-20 15:03 UTC, Aveline-art commented on .github/workflows/update-team-members.yml
> +
I believe this might be a spelling error? I hope the rest of the script was not made under the assumption that ```hackforla/website``` was spelled correctly 😓

2021-07-20 15:03 UTC, Aveline-art commented on .github/workflows/update-team-members.yml
> +        working-directory: ./github-actions/github-data
This is more of an optional, personal thing, but I want to try to avoid using third party actions whenever possible. Do you know of some way to replicate the same action? Do you believe this [would help ](https://github.com/actions/setup-node)or only muddle the code? Don't stress too much on this if the solution is more work than it is worth.

2021-07-20 15:03 UTC, Aveline-art commented on github-actions/github-data/contributors-data.js
> +
I could have missed something but I do not see ```core``` or ```_``` ever used in the script. Can you explain how they are being used?

2021-07-20 15:03 UTC, Aveline-art commented on github-actions/github-data/contributors-data.js
> +
I am wondering if we might want to move the limit setter (aka the limit for when we remove a contributor from the team) into a variable on top of the file. I am imagining we would want that if we ever want to tailor the time. Any thoughts?

2021-07-20 15:03 UTC, Aveline-art commented on github-actions/github-data/contributors-data.js
> +        repo: 'website',
I found the break condition for the loop a little unclear. Can you add a comment, so maintainers can immediately understand the workings of this loop.

2021-07-20 15:03 UTC, Aveline-art commented on github-actions/github-data/contributors-data.js
> +      }
This is fine as is, but ```result.push(contributors.data)``` might work better since the new list is being added back into the variable? Please let me know your thoughts! 🙂

2021-07-20 15:03 UTC, Aveline-art commented on github-actions/github-data/contributors-data.js
> +    }
Not sure what this is doing at first glance. Can you add a comment? Also, is it possible to merge the multiple if statements under one line? The nested if on the last ```else``` might require a little bit of extra magic if you decide to refactor.

2021-07-20 15:03 UTC, Aveline-art commented on github-actions/github-data/contributors-data.js
> +        per_page: 100
See next comment.

2021-07-20 15:03 UTC, Aveline-art commented on github-actions/github-data/contributors-data.js
> +      }
See next comment.

2021-07-20 15:03 UTC, Aveline-art commented on github-actions/github-data/contributors-data.js
> +
All these checks somewhat muddle the role of this function. If the variables needed to do these checks are not too much, consider moving this logic into a helper function. This would also help with all the nested `if` statements that further muddle the code.

2021-07-20 15:09 UTC, Aveline-art commented on github-actions/github-data/contributors-data.js
> +        repo: 'website',
Just to also add: 'hackforla' and 'website' (and other iterations of such) are hard-coded here, but might work better as a global variable on top of the file. Any thoughts on that?

2021-07-22 00:40 UTC, alexeysergeev-cm commented on .github/workflows/update-team-members.yml
> +
Done:
- [ ] Running every 2 weeks

2021-07-22 00:41 UTC, alexeysergeev-cm commented on .github/workflows/update-team-members.yml
> +
That was used to test. Removed.

2021-07-22 00:42 UTC, alexeysergeev-cm commented on github-actions/github-data/contributors-data.js
> +
Removed `core` an `_`

2021-07-22 00:44 UTC, alexeysergeev-cm commented on github-actions/github-data/contributors-data.js
> +        repo: 'website',
Added comments and created variables on top of the file

2021-07-22 00:51 UTC, alexeysergeev-cm commented on github-actions/github-data/contributors-data.js
> +      }
result  = []

`contributors.data` is and array of objects => `[ {}, {}, {} ]`, so if I push it, result will look as 2d array `[ [ {},{},... ] ]`.
We are fetching data per page ( page 1, page 2, ... ) as an array of objects `.concat` looks good to me. Another option would be `result.push(...contributors.data)` but that seems to be reindexing as well. 

Let me know if you know the better way 🙂

2021-07-22 00:51 UTC, alexeysergeev-cm commented on github-actions/github-data/contributors-data.js
> +    }
Fixed and added comments

2021-07-22 00:52 UTC, alexeysergeev-cm commented on github-actions/github-data/contributors-data.js
> +
Created a helper function that does additional checks.

2021-07-22 00:59 UTC, alexeysergeev-cm commented on .github/workflows/update-team-members.yml
> +        working-directory: ./github-actions/github-data
I can explore that later.

2021-07-31 20:22 UTC, Aveline-art reviewed
Great work @alexeysergeev-cm. I am ready to merge this as soon as the below points are clarified!

2021-07-31 20:22 UTC, Aveline-art commented on .github/workflows/update-team-members.yml
> +        working-directory: ./github-actions/github-data
Is there an update on this?

2021-07-31 20:22 UTC, Aveline-art commented on github-actions/github-data/contributors-data.js
> +
Are the index 1 item (the numbers following the API links) of every inner Array used at all?

2021-07-31 20:22 UTC, Aveline-art commented on github-actions/github-data/contributors-data.js
> +
Our of curiosity, why store contributors as an object over another data type?

2021-08-02 03:54 UTC, alexeysergeev-cm commented on github-actions/github-data/contributors-data.js
> +
Oops, my mistake. I forgot to remove those. Fixed.

2021-08-02 03:56 UTC, alexeysergeev-cm commented on .github/workflows/update-team-members.yml
> +        working-directory: ./github-actions/github-data
Yes, completely replaced `bahmutov/npm-install@v1` to use `actions/setup-node@v2` && `npm install`.

2021-08-02 04:27 UTC, alexeysergeev-cm commented on github-actions/github-data/contributors-data.js
> +
We use an object (or [hash table](https://en.wikipedia.org/wiki/Hash_table)) to leverage O(1) time complexity for `Search`, `Insert` and `Delete` operations (on average). 
We quickly build up our `allContributorsSince` object in O(1) time. The main reason though is to quickly `Lookup/Search` in O(1) time if a team member is a recent contributor as shown on line `126` in the picture below.

![Screen Shot 2021-08-01 at 9 17 17 PM](https://user-images.githubusercontent.com/74341752/127803682-af2e6c49-5e0a-4453-b08b-9d897934f7a5.png)

2021-08-03 14:51 UTC, Aveline-art commented on github-actions/github-data/contributors-data.js
> +
I am not sure we are handling data at a volume that warrants doing this (or in business terms, I do not quite see this solving a relevant problem). I am concerned that the code might be harder to maintain in the long run... In any case, I am ready to merge and test this on our own repo. Will let you know if further edits need to be made.

2021-08-03 14:52 UTC, merged

2021-08-03 15:03 UTC, Aveline-art commented
I just ran it for the first time and everything looks as they should be. As for the readability, I am inclined to make it into a new issue if someone brings it up. Great work on this and thank you for sticking with this for so long!