Change alt text for Business Image on Credit Page
hackforla/website pull request #2001
Opened 2021-07-23 01:57 UTC by blakes24

Fixes #1561

### What changes did you make and why did you make them ?

  -  Changes the alt attribute value in business.yml to 'One-on-one video conference concept illustration'

2021-07-25 23:26 UTC, abuna1985 requested changes
@blakes24 Good job on your first pull request. I would remove the changes made within `pages/credits.html`. Remember that you only make changes within the `Action Items` of your issue. Those changes would resolve #1970, but we try to match 1 pull request to 1 issue.

@Aveline-art @ExperimentsInHonesty How should we proceed with this pull request?

2021-07-26 15:30 UTC, abuna1985 commented on pages/credits.html
> +                            <img src={{ item[1].image-url | absolute_url }} alt="{{item[1].alt}}"/>
After talking with @Aveline-art, let's remove this change. The guideline is 1 pull request for 1 issue.

2021-07-26 18:24 UTC, blakes24 commented on pages/credits.html
> +                            <img src={{ item[1].image-url | absolute_url }} alt="{{item[1].alt}}"/>
Ok, I have removed the change.

2021-07-28 02:43 UTC, JackRichman approved these changes
This is great! I ran it on docker from my local repository and it looks good.

2021-07-29 22:09 UTC, merged