Comment out 'looking' in project files
hackforla/website pull request #2012
Opened 2021-07-27 01:13 UTC by vickiychung

Fixes #1997 

### What changes did you make and why did you make them ?

  - Commented out `looking` for all `.md` files in `_projects` directory
  - Considered but haven't commented out `project.looking` in `current-projects.html` because it seems that they have to be deleted instead of commented out. It doesn't affect the output but we can remove them if we want the code to be cleaner => open to suggestions
  - Haven't worked on the "Looking filter" part of the issue (this can be done after UI/UX mockups are made)

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

<img width="852" alt="image" src="https://user-images.githubusercontent.com/72854605/127078996-9c966819-714d-4865-8ed7-86bea5f067d1.png">

<img width="887" alt="image" src="https://user-images.githubusercontent.com/72854605/127079164-dc081c87-cd0c-4acf-8c60-d3dce6c45273.png">

</details>

<details>
<summary>Visuals after changes are applied</summary>

 <img width="836" alt="image" src="https://user-images.githubusercontent.com/72854605/127079054-5c12a912-712a-444c-ac0a-417c168f7b74.png">

<img width="906" alt="image" src="https://user-images.githubusercontent.com/72854605/127079220-fe46436a-5288-4e56-bc4b-e2137d665ab7.png">

</details>

2021-07-29 22:30 UTC, Aveline-art requested changes
Hi @vickiychung ! Thank you for going through all the work to comment out all the md files. I have ran a few tests myself, and can confirm that it is possible to comment out `project.looking` in `current-projects.html` and I suspect it is also possible in `projects.html` as well. You might have had trouble viewing the changes due to your files being cached by jekyll?

On another note, the issue had the `role: design` tag which might mean that the issue is not ready to be worked on by a developer. I think I can still safely merge this, but @kristine-eudey, any thoughts?

2021-07-29 22:56 UTC, vickiychung commented
> Hi @vickiychung ! Thank you for going through all the work to comment out all the md files. I have ran a few tests myself, and can confirm that it is possible to comment out `project.looking` in `current-projects.html` and I suspect it is also possible in `projects.html` as well. You might have had trouble viewing the changes due to your files being cached by jekyll?
> 
> On another note, the issue had the `role: design` tag which might mean that the issue is not ready to be worked on by a developer. I think I can still safely merge this, but @kristine-eudey, any thoughts?

2021-07-29 22:58 UTC, vickiychung commented
Hi @Aveline-art !
Oops you might be right. The changes weren't reflecting on my end when I tried commenting them out. Thanks so much for checking! And double-oops......wasn't aware of the `role: design` tag. Sorry about that!

2021-07-30 19:05 UTC, Aveline-art commented
No problem! I think the tag was made recently, and with so many changes, it is difficult to keep up.

While we wait for a designer, would you mind editing your changes to comment out the code rather than the .md files? I think I was not clear about that earlier. Sorry!

2021-07-30 21:10 UTC, vickiychung commented
@Aveline-art Updated! Thank you :)

2021-07-31 13:24 UTC, kristine-eudey commented
@vickiychung @Aveline-art - The design portion of this (removing "Looking For" in the filter bar) will be finished by tomorrow! I'll update to let you know when that's completed.

2021-08-01 16:38 UTC, Aveline-art commented
@vickiychung I have just taken a peek and saw that the issue have been updated. I have added you back to the issue. Please update your pull request with the new changes outlined in the issue. Thank you!

2021-08-01 21:30 UTC, vickiychung commented
@kristine-eudey Thanks for the mock up!
@Aveline-art Changes are pushed up. Screenshots updated as well! Thank you!

2021-08-02 06:33 UTC, Aveline-art requested changes
Everything looks great @vickiychung . I only have some minor edits below. Also, in order to properly document this, so future developers will not be confused by your work, can you add comments above all the commented out code? I think something as simple as `See issue #xyz for more info on why this is commented out` will suffice, but do what you feel is best.

@kristine-eudey Thank you for getting the mockup done!

2021-08-02 06:33 UTC, Aveline-art commented on _projects/not-today.md
> +# looking:
I am not sure why this is commented out (here, and elsewhere as well, in similar files). Is there a reason for this?

2021-08-02 22:44 UTC, vickiychung commented on _projects/not-today.md
> +# looking:
I just commented it out when I went through the project md files earlier because there are no values for them. Not to do anything specifically. Should I leave them there?

2021-08-03 03:05 UTC, Aveline-art approved these changes
This looks perfect! Thank you for sticking with this!

2021-08-03 03:06 UTC, merged