Wins refactor js
hackforla/website pull request #2019
Opened 2021-07-29 01:24 UTC by Abel-Zambrano

Fixes #1818

### What changes did you make and why did you make them ?

- Clarified comment on line 107
- Change function to arrow function
- removed extra spaces

2021-08-01 16:05 UTC, abuna1985 requested changes
Good job @Abel-Zambrano. The changes look good. I only have a few formatting requests. To keep consistent with the rest of the code, can you please remove the space in the arrow functions so the argument is right next to the opening parenthesis. I have noted which lines to change. Thank you.

2021-08-01 16:05 UTC, adam-abundis commented on pages/wins/wins.html
> +  	rawData.slice(1).forEach( data => {
please remove the space between `(` and `data` so they are next to each other

2021-08-01 16:05 UTC, adam-abundis commented on pages/wins/wins.html
> +  	incomingFilterData.forEach( e => {
Please remove the space between `(` and `e`  so they are next to each other

2021-08-01 16:05 UTC, adam-abundis commented on pages/wins/wins.html
> +		cardList.forEach( item => {
Please remove the space between `(` and `item`  so they are next to each other

2021-08-01 16:34 UTC, Abel-Zambrano commented
@abuna1985 The changes are done.

2021-08-02 01:04 UTC, Zak234 approved these changes
Everything looks good!

2021-08-02 07:10 UTC, abuna1985 approved these changes
@Abel-Zambrano Thank you for making the changes. Everything looks good to me.

2021-08-02 07:10 UTC, merged