Develop updated getting started page
hackforla/website pull request #2059
Opened 2021-08-04 01:38 UTC by aalieu

Fixes #1619 

### What changes did you make and why did you make them ?

-   Revamped the 'Getting Started' page according to the designs on Figma to the best of my ability. Could not get everything pixel perfect due to differences in font-styles and font-weight differences between our default styles and Figma styles.
-   Added 11 images to be used as icons in the 'Getting-Started' page
-   Added 10 .yml credit files to credit the images/icons added. Did not credit 1 icon because a hackforla designer created it (and she said no need for citation). 

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

![Before Desktop View](https://user-images.githubusercontent.com/28831668/128107942-01186579-7c66-4f6d-bfec-c59aeadb96ad.jpg)

![Before Mobile View](https://user-images.githubusercontent.com/28831668/128107975-cac8c983-a951-4283-b59d-98b123283b84.jpg)

</details>

<details>
<summary>Visuals after changes are applied</summary>

![Desktop View](https://user-images.githubusercontent.com/28831668/128107986-1351e3c3-660c-40fe-aa75-1c06c81e2846.jpg)

![Mobile View](https://user-images.githubusercontent.com/28831668/128107998-b2c4cfc0-a197-4843-b7d7-7aa88ea87cae.jpg)

</details>

2021-08-22 04:29 UTC, arghmatey requested changes
Great work so far! I've requested a few changes.

I also found the [header svgs](https://user-images.githubusercontent.com/40401149/130341848-a6fa5d1e-6d2b-46aa-8065-f77e837018d0.png) get a little stretched out when testing for tablet. This may have to do with their set height, and could be fixed with a media query.

2021-08-22 04:33 UTC, arghmatey commented on _sass/components/_getting-started-page.scss
> + }
The Figma file has the info icons as 14px on both mobile and desktop. Update this to .875rem. This will base it off of the root font size to keep the size consistent regardless of screen or parent font size.

2021-08-22 04:34 UTC, arghmatey commented on _sass/components/_getting-started-page.scss
> +  font-weight: 500;
Font weight should be 700 here.

2021-08-22 09:16 UTC, alyssabenipayo requested changes
Looks good to me so far. Please see below for my comments:

- I agree with Sarah. I got the same result for the [header svgs](https://user-images.githubusercontent.com/38295612/130349411-b493590a-1e18-41f8-beec-1b1986fcde1f.png) when I tested the tablet.  Replacing `height: 100px` with `max-height: 100%;` and `max-width: 100%;` may resolve the issue in the icons looking compressed. (I'll suggest the change in the file as well.) However, the [icon for step 2](https://user-images.githubusercontent.com/38295612/130349490-7c68611d-bcbc-430f-ac16-058b542c13d7.png) is larger than the rest of the icons desktop. Is this the icon we chose for this step? If the icon for step 2 is what we want, then maybe replacing `height: 100px` with `max-height: 100px` and `max-width:100px` would resolve the issue.

- The icon in Step 2 looks faded/orange (both on desktop and mobile) compared to what we have in the [Figma file](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=11987%3A91947). Is this what we want our icon to look?
![image](https://user-images.githubusercontent.com/38295612/130347269-d3db7ebc-78e0-465b-afab-8105eeb14241.png)
![image](https://user-images.githubusercontent.com/38295612/130347246-57582453-060c-42dc-989b-e0b74fe162bf.png)

2021-08-22 09:25 UTC, alyssabenipayo commented on _sass/components/_getting-started-page.scss
> +.step-img-intro {
Replacing `height: 100px` with `max-height: 100%;` and `max-width: 100%;` may resolve the issue in the icons looking compressed. 

However, the [icon for step 2](https://user-images.githubusercontent.com/38295612/130349490-7c68611d-bcbc-430f-ac16-058b542c13d7.png) is larger than the rest of the icons desktop.

Is this the icon we chose for this step? 

If the icon for step 2 is what we want, then replacing `height: 100px` with `max-height: 100px` and `max-width:100px` may resolve the issue.

2021-08-22 09:26 UTC, alyssabenipayo commented on _sass/components/_getting-started-page.scss
> +.step-img-intro {
(Sorry! I commented the wrong line) Replacing `height: 100px` with `max-height: 100%;` and `max-width: 100%;` may resolve the issue in the icons looking compressed. 

However, the [icon for step 2](https://user-images.githubusercontent.com/38295612/130349490-7c68611d-bcbc-430f-ac16-058b542c13d7.png) is larger than the rest of the icons desktop.

Is this the icon we chose for this step? 

If the icon for step 2 is what we want, then replacing `height: 100px` with `max-height: 100px` and `max-width:100px` may resolve the issue.

2021-08-22 09:28 UTC, alyssabenipayo commented on _sass/components/_getting-started-page.scss
>    height: 100px;
(Sorry! I commented the wrong line) Replacing `height: 100px` with `max-height: 100%;` and `max-width: 100%;` may resolve the issue in the icons looking compressed. 

However, the [icon for step 2](https://user-images.githubusercontent.com/38295612/130349490-7c68611d-bcbc-430f-ac16-058b542c13d7.png) is larger than the rest of the icons desktop.

Is this the icon we chose for this step?

2021-08-22 18:14 UTC, abuna1985 commented
@aalieu Replace the Step 2 image (.png) so it matches the [Figma file](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=11987%3A91947). @arghmatey will create separate styling issues for the page. 

As soon as the image is replaced, we will be able to merge this pull request.

Thank you.

2021-08-25 04:44 UTC, aalieu commented
@arghmatey @alyssabenipayo 

Thank you so much for your reviews! 

@abuna1985 

Hey Adam, sorry but I will be out of town until the 29th so I won't be able to update my PR until right before the Tuesday meeting on the 31st. 

There's a slight problem though with replacing the step 2 image — I got the icon straight from the links provided in Figma so I'm not sure why it looks faded and orange. I'm not sure what can be done about it since it's an icon from another source. This is the link for the icon where it is faded and orange compared to Figma: 

https://www.freepik.com/free-vector/solidarity-concept-illustration_14562369.htm#page=5&position=24

2021-08-25 05:39 UTC, abuna1985 commented
@aalieu There seems to be a miscommunication. You can download images directly from the Figma design
https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=13%3A0

<details>
  <summary>Visual steps to download images from Figma design</summary>
  <br>
  <p>Step 1: Select the image from the figma design. Then select the `Export` tab (highlighted in red)</p>
  <img src="https://user-images.githubusercontent.com/21162229/130732304-0de940ef-f6da-4e8a-8286-35389c483812.jpg" />
  <br>
  <p>Step 2: Select the `Export` button which will download the selected image in a zip folder</p>
  <img src="https://user-images.githubusercontent.com/21162229/130732603-132ababe-55f6-4ace-a66b-c8f85e21f3b5.jpg" /> 
</details>

2021-08-25 06:21 UTC, aalieu commented
@abuna1985 

Awesome, thanks for the clarification! Thanks for the step-by-step instruction too. I had no idea that you could export images from Figma so I definitely learned something new and useful today.

2021-08-31 04:18 UTC, aalieu commented
Changed the step 2 image to the correct version. Also resolved the changes requested by @alyssabenipayo and @arghmatey. Should be ready to merge @abuna1985!

2021-09-03 19:21 UTC, arghmatey approved these changes

2021-09-04 01:07 UTC, alyssabenipayo approved these changes
Looks good.

2021-09-04 03:14 UTC, merged