GH-Actions: Add missing labels
hackforla/website pull request #2060
Opened 2021-08-04 02:04 UTC by macho-catt

Fixes #2013

### What changes did you make and why did you make them ?

  - Added gh-action to add the required missing labels on an issue if a user forgets them.
  -  The gh-action also removes a "missing label" if the required label is actually filled out. (i.e. I accidentally added the "role missing" label even though I added the "role: front end" properly. The gh-action will remove the "role missing" label and keep the proper label)
  - The gh-action also posts a comment depending on if the user added the required labels or not

### Screenshots of example issues on my fork

<details>
<summary>Issue with no labels</summary>

![Screenshot from 2021-08-03 19-03-39](https://user-images.githubusercontent.com/48004150/128110089-1bd9da05-213f-4813-8cdc-65f3bfa6614c.png)

</details>

<details>
<summary>Issue with required labels</summary>
  
![Screenshot from 2021-08-03 19-03-59](https://user-images.githubusercontent.com/48004150/128110119-cccc3ac8-0fbb-4843-b072-a3c00b57f3bc.png)

</details>

<details>
<summary>Issue with extraneous labels</summary>
  
![Screenshot from 2021-08-03 19-04-15](https://user-images.githubusercontent.com/48004150/128110131-c4849dee-87d2-414e-89e3-8a02cf01b780.png)

</details>

2021-08-06 20:14 UTC, alexeysergeev-cm reviewed
Hi @macho-catt, amazing work! I like how the code is easy to read!

2021-08-06 20:14 UTC, alexeysergeev-cm commented on github-actions/issue-labels/check-labels.js
> +  const filteredLabels = await filterLabels(labels)
Is this function `async` at all? It seems it does not need `await` or am I missing something?

2021-08-06 20:14 UTC, alexeysergeev-cm commented on github-actions/issue-labels/post-labels-comment.js
> +}
Is there an option we can put this in a separate `.MD` file and just pass the username to avoid touching code if the change in the message is needed? 

Can we also remove spaces in the ` ' ${LABELS_OBJ[label]}  '` on line 49 to avoid the spacing in the comment, or is that necessary?

2021-08-08 00:35 UTC, macho-catt commented on github-actions/issue-labels/check-labels.js
> +  const filteredLabels = await filterLabels(labels)
I can remove the async. Previously it was an async function that I refactored, but I missed removing this part. Good catch.

2021-08-08 00:35 UTC, macho-catt commented on github-actions/issue-labels/post-labels-comment.js
> +}
I can do that.

2021-08-08 04:44 UTC, macho-catt commented
Updates based on @alexeysergeev-cm suggestions

### Additional changes

  - Changed the filterLabels function under check-labels.js to be synchronous
  - Added new MD files for comment templates, instead of only having one:
    - labels-instructions-template.md - overall comment to be posted
    - add-labels-template.md - instructions template for labels that need to be added
    - no-labels-template.md - comment if required labels are added
  - Updated logic for creating a comment
  - Updated formatComment function to be more usable outside of this issue
  - Updated postComment function to be more usable outside of this issue
  - Separated the two functions above into the utils folder so other files can use them

### Some comments
Since the format comment and post comment are used in other gh-action js files, (the overall function and result are the same), I extracted them into their own files. I noticed that other js files (such as post-comment.js under pr-instructions and add-label.js under add-update-label-weekly) use them as well. They might need to be re-edited a bit, but I think it'll be good moving forward to use this. What do you think @Aveline-art ? Also, I saw two labels that don't follow the format of other labels in the same group: "Role: Administrative" and "Role: Product". Can these be changed to follow the format "role: xxxx" since that's how the other roles are formatted?

It should also be noted that if any of the size, roles, or features labels are edited / updated in the feature, the new code stemming from this PR should be noted since the code uses the pattern of how the current labels are.

### Screenshots of example issues on my fork

<details>
<summary>Updated issue with no labels</summary>

![no labels](https://user-images.githubusercontent.com/48004150/128620830-0a9dae71-f06f-46c7-a7de-85c44b06f2f1.png)


</details>

<details>
<summary>Updated issue with required labels</summary>
  
![with-labels](https://user-images.githubusercontent.com/48004150/128620838-e760d59b-f0f0-4caf-a594-b2a1a5a37d69.png)


</details>

2021-08-09 00:19 UTC, Aveline-art requested changes
Great work on this! Just a couple of aesthetic changes for this one. Once those are addressed, I can start testing these changes.

2021-08-09 00:19 UTC, Aveline-art commented on github-actions/utils/comments.js
> +
I am going to veto this, since it also requires a lot of parameters, and the catch function should be customizable according to the preferred performance of the function. API calls itself, by it nature already reduce the needed parameters as much as possible, so I think trying to reduce it even more takes away some of the flexibility of it.

2021-08-09 00:19 UTC, Aveline-art commented on github-actions/utils/comments.js
> +}
I can see why this should be here, but I also hesitate since 4 required parameters seem to defeat the purpose of making an outside function. I think a utility function should be easy to understand, and does one task very well. I can also envision the need for multiple placeholders, which this does not account for. Not sure if either of those concerns can be addressed, but if not, just put this back into the main folder..

2021-08-09 00:19 UTC, Aveline-art commented on github-actions/issue-labels/labels-instructions-template.md
> +Wiki: How to create issues (_WIP. Link will be updated when the wiki is done_)
I think we would prefer to have two files, rather than a template file that can be adjusted with another file. The idea behind the outside md file is so that a user can clearly see what message the client is seeing (or in other words, a PM, with no programming experience, can adjust their message and get a clear idea of what their message is). Can this be moved into the other templates? It is okay if the files are very similar; it is much more important that we get a grasp of what message we are sending.

2021-08-09 00:19 UTC, Aveline-art commented on github-actions/issue-labels/check-labels.js
> +
I've noticed an issue with the role vs Role labels. I think the [i modifier ](https://www.w3schools.com/jsref/jsref_regexp_i.asp)would help with that? I am not sure if there could be another edge case, but if so, let me know so I can make adjustments.

2021-08-09 00:19 UTC, Aveline-art commented on github-actions/issue-labels/check-labels.js
> +
Not sure why the set object needs to be unpacked. Does the API not take a set object?

2021-08-09 03:19 UTC, macho-catt commented on github-actions/utils/comments.js
> +
Okay, I can move it back to the original folder

2021-08-09 03:20 UTC, macho-catt commented on github-actions/utils/comments.js
> +}
I'll also move this back as well.

2021-08-09 03:20 UTC, macho-catt commented on github-actions/issue-labels/labels-instructions-template.md
> +Wiki: How to create issues (_WIP. Link will be updated when the wiki is done_)
I'll consolidate them into two files.

2021-08-09 03:21 UTC, macho-catt commented on github-actions/issue-labels/check-labels.js
> +
I could try that, that might actually make it easier

2021-08-09 03:27 UTC, macho-catt commented on github-actions/issue-labels/check-labels.js
> +
I only wanted to use the Set object to clear duplicates when I merge the two arrays, and initially when I wrote this and passed it on I wanted to retain it as an array so I can use any properties that come with it. I also wanted to remove any unforeseen effects in using a Set object, so to make my life easier I made it an array.

I could change it back to just a Set if there's a need for that, but otherwise I think using it as an array will make it easier to use.

2021-08-09 03:37 UTC, macho-catt commented
### Additional changes

  - Removed the utils/comment.js file and added the two functions there back to post-labels-comment.js
  - Removed the labels-instructions-template.md file and added the body from that into the two other md files
  - Changed the input parameters for formatComment to take an object instead of four parameters.
    - Pros and Cons of using multiple parameters vs an options object: https://stackoverflow.com/questions/12826977/multiple-arguments-vs-options-object
 - Added i flag to regex to ignore character case
 - Updated logic for makeComment function to accommodate the changes for formatComment

2021-08-10 19:33 UTC, Aveline-art submitted a review, later dismissed

2021-08-10 19:33 UTC, Aveline-art commented on github-actions/issue-labels/add-labels-template.md
> +
I just realized that there is a use case for not using a label (a PM or designer might not know the size of a development issue, for example, and vice versa). In such a case, we would not want to encourage adding a label and hoping for the best, but rather allow someone from the team with the required experience to add the labels instead. For now, let's comment out the function that posts this template (and leave the other template as is) and make a new issue for product to brainstorm the desired behavior and message

2021-08-10 19:34 UTC, Aveline-art commented on github-actions/issue-labels/add-labels-template.md
> +
@macho-catt Just comment out the code and this will be ready to merge :) Great work!

2021-08-10 23:53 UTC, macho-catt commented on github-actions/issue-labels/add-labels-template.md
> +
@Aveline-art so just comment out lines 5-8 of add-labels-template.md (and accompanying code that maps the labels into this template) until we figure out what PMs want?

2021-08-11 00:28 UTC, Aveline-art commented on github-actions/issue-labels/add-labels-template.md
> +
Mmm, do it from the js side, so add-labels-template is never posted in the first place.

2021-08-11 00:31 UTC, macho-catt commented on github-actions/issue-labels/add-labels-template.md
> +
Ok, so if no labels were added in the first place, don't have the bot comment anything and just add the three missing labels. Is that correct?

2021-08-11 00:32 UTC, Aveline-art commented on github-actions/issue-labels/add-labels-template.md
> +
Yep

2021-08-11 01:56 UTC, macho-catt commented
### Additional changes

  - Commented out the code where the action will post when the required labels are not added. The action will end (instead of posting something)
  - Added a comment in the code that details why we did this

2021-08-11 03:54 UTC, Aveline-art reviewed
LGTM!

2021-08-11 03:54 UTC, merged

2021-08-11 04:04 UTC, Aveline-art commented
The GHA works beautifully! Thanks for making this!