Update CONTRIBUTING.md
hackforla/website pull request #2074
Opened 2021-08-09 05:34 UTC by JasonUranta

Suggested an alternate way to download Homebrew, which becomes relevant in one of the possible ways to download an up-to-date version of Git on MacOS (under the "Clone the forked repository" section of the directions) because the current suggested way was gave a version of Homebrew that was to big and took up a lot of storage on Macs.

Fixes #2008

### What changes did you make and why did you make them ?

  - Suggested an alternate way to download Homebrew, which becomes relevant in one of the possible ways to download an up-to-date version of Git on MacOS (under the "Clone the forked repository" section of the directions) because the current suggested way was gave a version of Homebrew that was to big and took up a lot of storage on Macs. 

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

![image](Paste_Your_Image_Link_Here_After_Attaching_Files)

![Screen Shot 2021-08-08 at 10 14 05 PM](https://user-images.githubusercontent.com/86503503/128663591-16698863-1017-442a-a3c9-6242db763966.png)
</details>

<details>
<summary>Visuals after changes are applied</summary>
  
![image](Paste_Your_Image_Link_Here_After_Attaching_Files)

![Screen Shot 2021-08-08 at 10 15 32 PM](https://user-images.githubusercontent.com/86503503/128663613-d88f5ab0-9f5d-4da4-a3a5-de056397b030.png)

![Screen Shot 2021-08-08 at 10 15 41 PM](https://user-images.githubusercontent.com/86503503/128663633-567f2f0b-43de-4268-a57c-eb56b6acf789.png)

</details>

2021-08-09 20:12 UTC, blakes24 reviewed
It looks good, just one minor issue I noticed.

In your after picture, it looks like the link you added isn't displaying properly. You have the markdown for the link formatted correctly so I think the issue is that it's inside an HTML element so you might have to use an `<a>` tag instead.

2021-08-10 17:50 UTC, Aveline-art commented
@JasonUranta These edits are not on the fork from your repository. Please put all your changes to the your fork and close this PR.

2021-08-14 19:45 UTC, abuna1985 requested changes
Per @Aveline-art request above
```
These edits are not on the fork from your repository. 
Please put all your changes to the your fork and close this PR. Then reopen a new PR with your fork. 
Thank you!
```

2021-08-15 06:27 UTC, JasonUranta commented
> @JasonUranta These edits are not on the fork from your repository. Please put all your changes to the your fork and close this PR. Then reopen a new PR with your fork. Thank you!

So sorry for the late response. I am doing that now.

2021-08-15 06:28 UTC, closed without merging