Add GreenEarthOS Project Card and Page
hackforla/website pull request #2118
Opened 2021-08-15 00:07 UTC by grhhhh

Fixes #2064

  - Adds green-earth-os.md to the _projects folder using information provided by the GreenEarthOS team [here](https://github.com/hackforla/GreenEarthOS/issues/3#issuecomment-893120885)
  - Adds [green-earth-os-hero.png and green-earth-os.png](https://github.com/hackforla/GreenEarthOS/issues/3#issuecomment-884618633) to the assets>images>projects folder
  
Adding the GreenEarthOS project markdown file as well as the GreenEarthOS image files creates a new project card and new project site for the GreenEarthOS project on the website.

<img width="50%" alt="Screen Shot 2021-08-14 at 4 09 01 PM" src="https://user-images.githubusercontent.com/79604590/129462958-869e7391-1690-4de8-a646-582e528dda92.png">
<img width="75%" alt="Screen Shot 2021-08-14 at 4 10 31 PM" src="https://user-images.githubusercontent.com/79604590/129462960-1e698b6b-5533-44f0-af41-980e2324ed20.png">

2021-08-15 22:42 UTC, blakes24 requested changes
Looks good, there are just a few issues I noticed.
- The text on the card doesn't line up with the other cards. It looks like all the other project images have a 3:2 ratio while the green earth image is 4:3, if you crop out some of the white space it should line up with the rest of the cards
- The links for the readme and project overview are missing
- The pictures for the project leaders are missing

2021-08-15 22:42 UTC, blakes24 commented on _projects/green-earth-os.md
> +image-hero: /assets/images/projects/green-earth-os.png
Should image-hero be `green-earth-os-hero.png`?  Looks like you referenced `green-earth-os.png` twice, but never used `green-earth-os-hero.png`

2021-08-15 22:42 UTC, blakes24 commented on _projects/green-earth-os.md
> +    picture:
To get a user's picture you just need  to add `https://avatars.githubusercontent.com/<insert github name here>`

2021-08-17 16:52 UTC, Aveline-art commented
> 
> 
> Looks good, there are just a few issues I noticed.
> 
>     * The text on the card doesn't line up with the other cards. It looks like all the other project images have a 3:2 ratio while the green earth image is 4:3, if you crop out some of the white space it should line up with the rest of the cards
> 
>     * The links for the readme and project overview are missing
> 
>     * The pictures for the project leaders are missing

@grhhhh Just to let you know, the images comes with a specific ratio (or a specific size) that must be met to appear properly aligned, as per @blakes24 . You need to let the GEOS team know how their current assets appear on our site and return this back to the GEOS project team to redo the image.

2021-08-18 05:23 UTC, aalieu commented
@grhhhh 

I was assigned to review this PR I think because there was a new commit after the previous review from @blakes24. I looked through the files changed and viewed the feature on my own computer but I didn't see any changes from what was requested in the last review by Blakely so I will hold off on reviewing for now until I hear back from you!

2021-08-18 18:45 UTC, grhhhh commented on _projects/green-earth-os.md
> +image-hero: /assets/images/projects/green-earth-os.png
@blakes24 Thanks for catching this! My most recent commit fixes this issue.

2021-08-18 18:46 UTC, grhhhh commented on _projects/green-earth-os.md
> +    picture:
@blakes24 Thanks for your help with this! My most recent commit addresses this.

2021-08-18 18:46 UTC, grhhhh commented
@blakes24 @Aveline-art @aalieu Thanks for your feedback. I've made the following changes in my most recent commit:

- added the `green-earth-os-hero.png` to the `green-earth-os.md` file
- added the project leaders' gh avatar images
- added the project overview and readme

I am waiting to receive a new `green-earth-os.png` image with the correct size ratio from the GEOS team. I've also asked for their input regarding the background image of the project page which is currently a blank green background.

2021-08-20 15:25 UTC, blakes24 approved these changes
Nice job with all the changes. The card image looks good and all the links are present. Everything looks great.

2021-08-21 21:58 UTC, macho-catt requested changes
Good job @grhhhh. You're almost there! However, I have a simple change request. Is it possible to put a copy of the project's pdf (GreenEarthOS one sheet.pdf) under assets/pdfs, then update the md file so that both overviews on the project card and project page open a new tab with that pdf (instead of currently opening as a github page with a pdf file)?

We are currently in the process of making new issues to restructure our pdf files. Thanks!

2021-08-22 15:31 UTC, Aveline-art commented
@macho-catt That's out of the purview of this issue. Let's do the pdf migration as a separate issue, so that @grhhhh would not have to keep working on an issue as requirements changes. If everything else is ready, consider merging it.

2021-08-22 16:51 UTC, macho-catt approved these changes
Then this is good to go. GJ!
By the way, there is a separate issue on the projects page that I will create later where url with spaces do not link properly under the a tag. The fix is to enclose the value of the href parameter with double quotes. This seems to be a separate issue from this.

2021-08-22 16:51 UTC, merged