Changing text for the submit your pitch button
hackforla/website pull request #2119
Opened 2021-08-15 05:45 UTC by SAUMILDHANKAR

Fixes #1975 

### What changes did you make and why did you make them ?

  - Changed the text to be displayed on a button on the homepage inviting pitches.
  - Change was required as part of the issue.
  

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

![image](https://user-images.githubusercontent.com/843538/129468354-42c642ef-033b-48f9-abb1-4e44664458a7.PNG)

</details>

<details>
<summary>Visuals after changes are applied</summary>
  

![image](https://user-images.githubusercontent.com/843538/129468362-b2b3eda8-3363-47b5-9e57-0b9e2cd4e48e.PNG)

</details>

2021-08-17 07:39 UTC, Zhu-Joseph submitted a review, later dismissed
Clears issue

2021-08-18 01:03 UTC, macho-catt requested changes
Hi @SAUMILDHANKAR. Good job on properly checking the action items on the issue and detailing the changes you made and adding screenshots to the PR.

However, it looks like the 'ask' from the issue was different. In your PR, you changed the text of the button, but the ask was to change the subject line instead.

The example code shows how to do a subject line:

```
<a href="mailto:test@example.com?subject=Testing out mailto!">First Example</a>
```

So for this example, you don't change the title, which is "First Example." That should remain. What you need to change is "Testing out mailto," which is the subject line.

Let me know if you have any questions.

2021-08-18 01:05 UTC, macho-catt commented on _includes/current-projects.html
> +        >Submitting my pitch to Hack for LA</a
Revert this since the title of the button should stay the same

2021-08-18 01:06 UTC, macho-catt commented on _includes/current-projects.html
>        <a href="mailto:team@hackforla.org" class="btn btn-primary btn-md-narrow"
Subject line would go here. For example:
```
<a href="mailto:test@example.com?subject=Testing out mailto!">First Example</a>
```
Where the subject line is "Testing out mailto"

2021-08-18 01:39 UTC, SAUMILDHANKAR commented on _includes/current-projects.html
>        <a href="mailto:team@hackforla.org" class="btn btn-primary btn-md-narrow"
@macho-catt Thanks for your review and suggestions. I will make the changes and let you know if I have any more questions. Thanks.

2021-08-19 00:13 UTC, SAUMILDHANKAR commented
@macho-catt I have made the changes as suggested in my latest commit. Please let me know if more changes are required before merging. Thank you.

2021-08-19 03:08 UTC, macho-catt approved these changes
Looks good to me. New subject line appears in my environment. Good job!

2021-08-19 03:09 UTC, merged

2021-08-19 19:18 UTC, SAUMILDHANKAR commented
Thank you.