Moving html files from pages/about to _includes folder
hackforla/website pull request #2121
Opened 2021-08-15 23:52 UTC by benrempel

Fixes #2109

### What changes did you make and why did you make them ?

  - Create a new directory under _includes called about-page
  - Moved 9 html files to _includes/about-page 
  - Edit the code for about.html so that the liquid uses include instead of include relative and make sure it points to the files under _include/about-page

2021-08-15 23:59 UTC, benrempel commented
I just realized that this pull request also includes commits from another pull request I just submitted (#2120), which is totally unrelated. Oops! I know how to avoid this next time. Let me know if I need to redo this.

2021-08-16 05:20 UTC, Aveline-art commented
@benrempel Please do not work on multiple issues or submit multiple pull requests. Abstain from working on any more issues until they merge. If you wish to contribute to the team, you are free to review pull requests, create issues, or ask a lead for any critical tasks that needs to be done.

2021-08-19 05:10 UTC, macho-catt requested changes
For the most part this looks good to me. Nice job!

However, I noticed that the yml file has changes from your previous PR. Since that PR has already been merged, could you make sure that this PR does not include this yml file by merging the latest updates from gh-pages with this branch?

Additionally, since about.html will be the only file left under the directory pages/about, you can move it up to the pages directory and delete pages/about directory (if that makes sense).

Let me know if you have any questions.

2021-08-19 05:13 UTC, abuna1985 requested changes
@benrempel Great job! The rest of the pr looks good. I was able to confirm the following pages are not available after your changes:
  1. pages/about/about-card-accomplishments.html
  2. pages/about/about-card-donations.html
  3. pages/about/about-card-executive-letter.html
  4. pages/about/about-card-metrics.html
  5. pages/about/about-card-news.html
  6. pages/about/about-card-partners.html
  7. pages/about/about-card-platform.html
  8. pages/about/about-card-sponsors.html
  9. pages/about/about-card-sustainability.html
  
I just have a few suggestions:
* Per the request above, please remove changes from `_data/internal/credits/sustainability.yml`. 
  
  * When you make your next pull request, it would be a good idea to provide before/after pictures to show proof of your changes. I have  provided an example of one of the template views below:

<details>
  <summary>Current template view for `about-card-acommplishments` (hackforla.org)</summary>
  <br>
  <img src="https://user-images.githubusercontent.com/21162229/130011173-ace52ce5-40e5-438c-843d-e11b4d837294.jpg" />
</details>

<details>
  <summary>After changes made for `about-card-acommplishments` (http://localhost)</summary>
  <br>
  <img src="https://user-images.githubusercontent.com/21162229/130011218-a21f738a-c3c0-40ec-9160-fabd8572d4ea.jpg" />
</details>

Thank you!

2021-08-19 05:13 UTC, adam-abundis commented on _data/internal/credits/sustainability.yml
> +title-link: https://thenounproject.com/term/sustainability/219630/
revert (remove change) this since it is unrelated to #2109

2021-08-19 05:13 UTC, adam-abundis commented on _data/internal/credits/sustainability.yml
> +---
revert (remove change) this since it is unrelated to #2109

2021-08-20 00:32 UTC, benrempel commented
thanks @macho-catt and @abuna1985 for the tips! I made the requested changes.

2021-08-20 15:56 UTC, macho-catt approved these changes
LGTM

2021-08-22 00:59 UTC, abuna1985 approved these changes
Thank you for your edits @benrempel . Everything looks good to me. Keep up the good work.

2021-08-22 00:59 UTC, merged