Updating hands image credit link, changing credit name to unity and c…
hackforla/website pull request #2157
Opened 2021-08-21 23:01 UTC by SAUMILDHANKAR

…hanging credit artist

Fixes #2092 

### What changes did you make and why did you make them ?

  - Replaced the generic Noun Project link for the image titled “Hands” in the credits page with this specific link - https://thenounproject.com/search/?q=unity&i=2334876 instead in the ‘Name’ category
  - Changed the credit Name of the icon from Hands to “Unity”
  - Changed the credit Artist of the icon from Lucky Day to “Kiran Shastry”
  - These changes have been made as required by the issue.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

![before](https://user-images.githubusercontent.com/843538/130336837-1851e9ed-3213-4b18-85ec-80c8644162b9.PNG)

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
![after](https://user-images.githubusercontent.com/843538/130336859-4e79d547-a1ed-4851-a21d-25eb065facce.PNG)

</details>

2021-08-23 22:14 UTC, blakes24 approved these changes, later dismissed
Nice job @SAUMILDHANKAR. The changes look good. 

On a separate note, I would try to avoid using quotes in your branch names in the future. When I first tried to pull the changes from your branch I got a ref not found error from git. Because the branch name included quotes around 'Hands' I had to wrap the whole branch name in double quotes to pull the branch. Not a big deal, but it's easier for people to review pull requests if they don't have to worry about why they're getting an error when they copy the correct branch name.

2021-08-24 02:55 UTC, adrian-zaragoza requested changes
Hey @SAUMILDHANKAR  thank you for working on this issue! I found one tiny problem. After looking at issue [2092](https://github.com/hackforla/website/issues/2092) this [link](https://thenounproject.com/search/?q=unity&i=2334876) should be in the Name category (the title-link). Currently, the link is in the Provider category(provider-link). The provider-link should be changed back to https://thenounproject.com/

![image](https://user-images.githubusercontent.com/77212035/130548073-0ee56d75-eae0-4cb8-be93-3118434d43c0.png)

Other than that every thing else looks good!

2021-08-26 23:11 UTC, SAUMILDHANKAR commented
@blakes24 Thanks Blakely. Sure, I will avoid quotes in branch names in future. Thanks for your review.

@adrian-zaragoza Thanks Adrian. I have made the changes. Thanks so much for letting me know.

2021-08-27 18:09 UTC, adrian-zaragoza approved these changes
Everything looks good on my end. Thank you @SAUMILDHANKAR

2021-08-28 01:14 UTC, blakes24 approved these changes
Everything looks good.

2021-08-28 01:39 UTC, merged