refactored the lines for button styling in join-us page
hackforla/website pull request #2196
Opened 2021-08-28 19:50 UTC by mehmehmehlol

Fixes #2165 

### What changes did you make and why did you make them ?

  - I refactored the lines that are stated in the issue 
  - Added an additional variable, `.btn--default` on `_buttons.scss` from `website/_sass/elements` after inquiring @abuna1985 
  - Note: After refactoring, the buttons did not appear as they were originally on my browser. I would attach the screenshot under the section of "visuals after change". I had reached out to @abuna1985 with my concerns. It appeared the refactoring did not make the drastic change on Adam's browser like on my browser -- as in the newly added variable on scss did not show up in my inspect. It might just be a minor issue on my end.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

![Join Us Page Before Refactoring](https://user-images.githubusercontent.com/63900848/131229385-0fe4b9e9-f322-46fd-a20d-175056ae28fe.png)

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
![Join Us Page after Refactoring on my browser](https://user-images.githubusercontent.com/63900848/131229405-6ef67a4f-aef0-4a62-a06e-562ac14a7f6f.png)

</details>

2021-08-29 07:01 UTC, abuna1985 requested changes
@mehmehmehlol Great job. Thank you for helping with the button implementation and working with me on a resolution to apply the style changes. I only have one request:
- It seems the class name in the `<a>` is `btn-defualt`. Please change it to `btn--default` and commit/push your changes to update this pull request.

Thank you.

2021-08-29 07:01 UTC, adam-abundis commented on pages/join-us.html
> +        <a href="./survey4" target="_blank" class="btn btn-primary btn-md btn-partner-with-us btn--defualt" title="Government Contact Form">Government</a>
please change from `btn--defualt` to `btn--default`

2021-08-29 07:01 UTC, adam-abundis commented on pages/join-us.html
> +        <a href="./survey3" target="_blank" class="btn btn-primary btn-md btn-partner-with-us btn--defualt" title="Non-profit Contact Form">Non-Profit</a>
please change from `btn--defualt` to `btn--default`

2021-08-29 07:01 UTC, adam-abundis commented on pages/join-us.html
> +        <a href="./survey6" target="_blank" class="btn btn-primary btn-md btn-partner-with-us btn--defualt" title="General Contact Form">Other</a>
please change from `btn--defualt` to `btn--default`

2021-08-30 05:40 UTC, mehmehmehlol commented on pages/join-us.html
> +        <a href="./survey6" target="_blank" class="btn btn-primary btn-md btn-partner-with-us btn--defualt" title="General Contact Form">Other</a>
Thanks @abuna1985 for spotting that! No wonder the buttons didn't look the way they were supposed to be, because of the typos!

2021-08-30 19:01 UTC, abuna1985 approved these changes
@mehmehmehlol I see the update and everything looks good on the Join page buttons. Great work! 🥳 🥳 🥳 

Thank you for helping us with the system design implementation.

2021-08-31 03:35 UTC, adrian-zaragoza approved these changes
These changes look good! Thank you!

2021-08-31 03:42 UTC, macho-catt approved these changes
LGTM. Good job on this!

2021-08-31 03:42 UTC, merged