adding inactive label to in progress issues with no comment or PR by …
hackforla/website pull request #2217
Opened 2021-09-03 06:31 UTC by SAUMILDHANKAR

…assignee in last 14 days

Fixes #1977 

### What changes did you make and why did you make them ?

  - Added new functions isInactiveTimelineOutdated and isInactiveMomentRecent to check if the assignee made a comment or PR in the last 14 days.
  - Added inactiveCutoff time to check for assignee activity in last 14 days
  - Reused other functions to update and remove inactive label as required.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

N/A

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
N/A

</details>

2021-09-06 16:41 UTC, Aveline-art requested changes
Hi @SAUMILDHANKAR . I have finished looking over the code. There are a few points that needs work. Please let me know your thoughts!

2021-09-06 16:41 UTC, Aveline-art commented on github-actions/add-update-label-weekly/add-label.js
> +      console.log(`No updates needed for issue #${issueNum}`);
I'm not sure this log is needed since the above already posts this log. Consider whether it is preferable to have both, or if one can be safely removed.

2021-09-06 16:41 UTC, Aveline-art commented on github-actions/add-update-label-weekly/add-label.js
> + */
The comments do not really describe what this function is about. It sounds like it does the same thing as the one above? In that case, can we combine the functions somehow?

2021-09-06 16:41 UTC, Aveline-art commented on github-actions/add-update-label-weekly/add-label.js
> +        return false
Is this the check for linked pull requests? If so, the cut off for pull requests is off. The issue calls for a 14 day no-comment cut off AND a 3 day no linked PR cutoff.

2021-09-06 16:41 UTC, Aveline-art commented on github-actions/add-update-label-weekly/add-label.js
> +
This function is really similar to the one above. Can the two functions be combined into something a bit more general?

2021-09-07 06:36 UTC, SAUMILDHANKAR commented on github-actions/add-update-label-weekly/add-label.js
> +
@Aveline-art Thanks a lot for your comments and review. I will be working on the changes tomorrow after team meeting.

2021-09-09 23:11 UTC, SAUMILDHANKAR commented on github-actions/add-update-label-weekly/add-label.js
> +      console.log(`No updates needed for issue #${issueNum}`);
I agree this log is not very helpful and I have removed it.

2021-09-09 23:17 UTC, SAUMILDHANKAR commented on github-actions/add-update-label-weekly/add-label.js
> + */
I have added a new comment which describes the role of this function. It checks if the comment was made more than 14 days ago.

2021-09-09 23:19 UTC, SAUMILDHANKAR commented on github-actions/add-update-label-weekly/add-label.js
> +        return false
I have modified the code so that it checks for 14 day no-comment and 3 day no linked PR. Thank you.

2021-09-09 23:22 UTC, SAUMILDHANKAR commented on github-actions/add-update-label-weekly/add-label.js
> +
I have made some changes to these two functions. Please let me know what you think. Thanks.

2021-09-10 04:23 UTC, Aveline-art requested changes, later dismissed
Great work on getting fixes on this. I have looked at it and it's getting pretty close! I am mostly ask for aesthetic changes because the code needs to be managed in the long run.

2021-09-10 04:23 UTC, Aveline-art commented on github-actions/add-update-label-weekly/add-label.js
> +	  await removeLabels(issueNum, inactiveLabel);
Not a big deal, per se, but GitHub does have an API call limit, so calling addLabels and removeLabels multiple times somewhat bothers me. Do you think there can be a fix for that (maybe an if else statement) such that api functions are called less?

2021-09-10 04:23 UTC, Aveline-art commented on github-actions/add-update-label-weekly/add-label.js
> +	return false
Is there a reason why this needs to be a nested function? Both the nested function and the outer function are off by only one variable. Can that variable be refactored as a parameter, and condense this function further?

For example:

```python
func(param1, param2):
  if param1 >= param2:
    return True
  else:
    return False
```

2021-09-10 04:24 UTC, Aveline-art commented on github-actions/add-update-label-weekly/add-label.js
> +	return false
Actually, thinking further, we can probably do something fancy, such as:

```python
func(param1, param2):
  return param1 >= param2
```

Not sure if that is clear, so it will need a bit of comments.

2021-09-10 08:27 UTC, SAUMILDHANKAR commented on github-actions/add-update-label-weekly/add-label.js
> +	return false
Thank you so much for your time on this and valuable review. Sure, I will be starting on the changes.

2021-09-14 02:43 UTC, macho-catt commented on github-actions/add-update-label-weekly/add-label.js
> +	  await removeLabels(issueNum, inactiveLabel);
If you find yourself calling the add / remove github api repeatedly, it might be simpler to use the setLabels function API call. I used it for one of my API calls. You can check /github-actions/issue-labels/check-label.js lines 90-96 for reference.

2021-09-14 02:49 UTC, macho-catt commented on github-actions/add-update-label-weekly/add-label.js
> +      if (moment.event == 'commented' && isCommentByAssignees(moment, assignees)) {
Very small thing, but when using 'equality' operators for javascript, it is often good practice to use strict equality (i.e. ===) to ensure no type conversions between the two things you're comparing I don't think it matters for this case, but generally it is good practice to follow. Check out this [article](https://stackoverflow.com/questions/359494/which-equals-operator-vs-should-be-used-in-javascript-comparisons) (and other similar articles) for topics on the matter.

2021-09-14 03:00 UTC, Aveline-art commented on github-actions/add-update-label-weekly/add-label.js
> +	  await removeLabels(issueNum, inactiveLabel);
@macho-catt I vaguely recall making this choice because retrieving the labels will require an api call anyways, so keeping tracking of the pre-existing labels was a hassle. That said, there might be another api call here that already retrieves the labels.

2021-09-14 06:53 UTC, SAUMILDHANKAR commented on github-actions/add-update-label-weekly/add-label.js
> +      if (moment.event == 'commented' && isCommentByAssignees(moment, assignees)) {
Thanks for sharing. Sure, I will keep that in mind.

2021-12-05 04:53 UTC, SAUMILDHANKAR commented on github-actions/add-update-label-weekly/add-label.js
> +	return false
Removed the nested function.

2021-12-05 05:00 UTC, SAUMILDHANKAR commented on github-actions/add-update-label-weekly/add-label.js
> +	  await removeLabels(issueNum, inactiveLabel);
Made changes to the code logic.

2021-12-10 04:09 UTC, macho-catt commented on github-actions/add-update-label-weekly/add-label.js
> +			await addLabels(issueNum, statusUpdatedLabel);
Change statusUpdatedLabel to responseObject.labels

2021-12-10 04:09 UTC, macho-catt commented on github-actions/add-update-label-weekly/add-label.js
> +				return {result: false, labels: toUpdateLabel}
Change toUpdateLabel to statusUpdatedLabel

2021-12-10 09:43 UTC, SAUMILDHANKAR commented on github-actions/add-update-label-weekly/add-label.js
> +				return {result: false, labels: toUpdateLabel}
Changed to statusUpdatedLabel

2021-12-10 09:44 UTC, SAUMILDHANKAR commented on github-actions/add-update-label-weekly/add-label.js
> +			await addLabels(issueNum, statusUpdatedLabel);
Changed to responseObject.labels

2021-12-16 05:55 UTC, macho-catt commented
Hi @SAUMILDHANKAR, I was testing this today and there are still some issues. You can see the logs from my test here: 
https://github.com/macho-catt/website/runs/4543633120?check_suite_focus=true

Specifically, for my own issue number 189 which is currently 2 weeks inactive, it is returning an error: Error: Unhandled error: TypeError: Cannot read property 'result' of undefined

The reason for this is because the last event:
```
  event: 'subscribed',
  commit_id: null,
  commit_url: null,
  created_at: '2021-12-10T07:17:23Z',
  performed_via_github_app: null
}
```
Was created on Dec 10, which will fall under the if statement on line 159 (7-day cutoff time). Since there are no if statements to catch this, the action fails.

I think for the 7-day cutoff time, 14-day cutoff time and the last else statement for anything past 14 days, you need these conditionals as well:
```
			else if (index === timeline.length-1 && (Date.parse(timeline[0].created_at) < fourteenDayCutoffTime.valueOf())) { // returns true if issue was created before 14 days after comparing the two dates in millisecond format  
				return {result: true, labels: inactiveLabel}
			}
			else if (index === timeline.length-1 && (Date.parse(timeline[0].created_at) < threeDayCutoffTime.valueOf())) { // returns true if issue was created before 3 days
				return {result: true, labels: toUpdateLabel}
			}
```

Let me know what you think. Thanks

2021-12-16 05:58 UTC, macho-catt submitted a review, later dismissed
Please see above comment. Thanks

2021-12-17 00:59 UTC, SAUMILDHANKAR commented
@macho-catt: Thanks Mathew for testing this. I was not able to generate this scenario earlier since I was moving the issues to the right column before running the test (and therefore that event would become the latest one). I have added the conditions in all the loops that would make sure it doesn't fail. We can check if it works during the office hours today. 
Also, one workaround for not moving the issue I could think of was to change the column name as well as the secret. 
Thank you.

2021-12-17 03:11 UTC, macho-catt approved these changes
LGTM

2021-12-17 03:11 UTC, merged