Hamburger nav 2117
hackforla/website pull request #2250
Opened 2021-09-12 19:52 UTC by GLRJr

Fixes #replace_this_text_with_the_issue_number

### What changes did you make and why did you make them ?

  -
  -
  -

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

![image](Paste_Your_Image_Link_Here_After_Attaching_Files)

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
![image](Paste_Your_Image_Link_Here_After_Attaching_Files)

</details>

2021-09-14 02:28 UTC, macho-catt requested changes
For the most part, this is good! Good job. Just one change that I recommend, the title of the front matter for hamburger-nav.js should be more descriptive than just "my js file." Could you change it to something like "Hamburger Nav?"
Additionally, your PR post has broken image links.
Thanks

2021-09-14 02:29 UTC, macho-catt commented on assets/js/hamburger-nav.js
> +title: my js file
Change title to be more descriptive

2021-09-14 03:52 UTC, Aveline-art commented on assets/js/hamburger-nav.js
> +title: my js file
I think the title can actually be removed since it is not used in the code, as far as I can tell?

2021-09-24 22:33 UTC, GLRJr commented
Sorry I made the changes earlier in the week but didn't actually push it.

2021-09-25 01:24 UTC, macho-catt approved these changes
Looks good. Great job!

2021-09-25 01:24 UTC, merged