Sort closed issues into correct column
hackforla/website pull request #2252
Opened 2021-09-12 22:15 UTC by blakes24

Fixes #2206

### What changes did you make and why did you make them?

  - Added a GitHub action to sort issues by their labels and move them to the correct column when closed
  - Moves issues with visual changes to UAT and those with no visual changes to Done

### To Review
 - The GitHub action will only work after it is merged
 - After merging, test that the board automation does not intercept or supersede this GHA
 - When testing in my own repo the board automation moved all issues into UAT first, then after about 15 seconds the GHA would move the issue into the correct column

2021-09-13 03:00 UTC, Aveline-art commented
This is converted to draft because PM requirements is currently in flux. Until it has been resolved, this item cannot be reviewed meaningfully or merged.

2021-09-23 02:53 UTC, macho-catt requested changes
This is awesome! I tested it in my environment, and it works. Good job. However, I have a couple of comments/change requests regarding the architecture so that it will be easier to update in the future (if needed). Additionally, we are also in the process of refactoring all the github actions, so I want to make that process as smooth as possible.

2021-09-23 02:54 UTC, macho-catt commented on github-actions/sort-closed-issues.js
> +function obtainLabels(context) {
It looks like this function is pretty useful and being reused in other github actions. Is it possible to extract this into the github-actions/utils folder? Additionally, can you note the other scripts that use this function so we can make issues out of them?

2021-09-23 02:55 UTC, macho-catt commented on github-actions/sort-closed-issues.js
> +    return "Done";
can "Done" and "UAT" both be put in some kind of const variables at the top and used here instead? That way, if we ever need to change these (or add more stuff), we can update the variables instead. It'll make it maintainable in the long run.

2021-09-23 02:59 UTC, macho-catt commented on github-actions/sort-closed-issues.js
> +/**
Can you create a new subdirectory called "move-closed-issues" under 'github-actions' and store sort-closed-issues.js under /github-actions/move-closed-issues? This will make refactoring this action in the future easier.

2021-09-23 03:00 UTC, macho-catt commented on github-actions/sort-closed-issues.js
> +  if (issueLabels.some(includesOverrideLabel)) {
Is there a reason why you're specifically using multiples ifs here, instead of an if/else conditional? I know the results are mutually exclusive so it really doesn't matter which one you use, I just want to know your reasoning.

2021-09-23 03:10 UTC, Aveline-art requested changes, later dismissed
Hi @blakes24 . Just a couple of comments for this one! Please let me know your thoughts!

2021-09-23 03:10 UTC, Aveline-art commented on github-actions/sort-closed-issues.js
> +    return "Done";
Column name strings are viable to change over time. Does the alex-page/github-project-automation-plus@v0.8.1 accept column id rather than column string? Regardless, consider moving the column names into a variable on the top of the file, so that in the scenario that names do change, we only need to perform edits on a single variable.

2021-09-23 03:10 UTC, Aveline-art commented on github-actions/sort-closed-issues.js
> +
This is simple, but might be hard to read for those weaker with OoP concepts. Consider whether this brevity is worth the a lowered readability.

2021-09-23 22:41 UTC, blakes24 commented on github-actions/sort-closed-issues.js
> +  if (issueLabels.some(includesOverrideLabel)) {
It's just a style preference. Since all the ifs have returns using else seems redundant, and it just feels more readable to me this way than a chain of else ifs, but I can change it to an if-else if you prefer.

2021-09-23 22:42 UTC, blakes24 commented on github-actions/sort-closed-issues.js
> +/**
Will do

2021-09-23 22:44 UTC, blakes24 commented on github-actions/sort-closed-issues.js
> +function obtainLabels(context) {
Done. It looks like the only other file using it is `issue-labels/check-labels.js`

2021-09-23 22:47 UTC, blakes24 commented on github-actions/sort-closed-issues.js
> +    return "Done";
The action doesn't accept column ids, but I have assigned the column names to variables.

2021-09-23 22:52 UTC, blakes24 commented on github-actions/sort-closed-issues.js
> +
Would it be more readable if I made them standard functions instead of arrow functions?

2021-09-24 06:23 UTC, Aveline-art commented on github-actions/sort-closed-issues.js
> +
I am not sure how it can be more readable, but stray observations:

1. Each function basically accomplishes the same thing.
2. Is this the best way to create these helper functions? What if requirements change again?
3. The main reason why this is hard to read is because it is not immediately clear the purpose of these lines, and why there needs to be a 121 correspondence with each array rather than one function that takes in that array.
4. A function that returns a function might be briefer?
5. Comments?

2021-09-24 21:14 UTC, blakes24 commented on github-actions/sort-closed-issues.js
> +
Would something like this be clearer?
```
/** Returns a function that checks if a label is in the given array */
function checkLabels(labelArray) {
    return (label) => labelArray.includes(label);
  }
```
then it would be used like this:
```
if (issueLabels.some(checkLabels(hardLabels))) {
    return doneColumn;
  }
```

2021-09-26 03:44 UTC, Aveline-art commented on github-actions/sort-closed-issues.js
> +
I'm not too sure if this is clearer per se... Let's abandon this line for the time being, and just add clarifying comments.

2021-09-26 20:16 UTC, Aveline-art commented on .github/workflows/move-closed-issues.yaml
> +jobs:
Hi @blakes24 . This is not a fault of your own, but we want to transition our GHAs into something more manageable. Specifically, we want to move all issue triggers into [one file](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/issue-trigger.yml), with if else clauses in the file differentiating different types of triggers. @macho-catt, please clarify and confirm if @blakes24 should transition this to our issue mega file.

2021-09-26 20:35 UTC, macho-catt commented on .github/workflows/move-closed-issues.yaml
> +jobs:
I am okay with approving this and creating a new issue to refactor into that file. It might add more work, but I probably will take the issue and put another job in that file first (add-issue-labels) so other developers can just look at it and know how the structure with if conditionals will work.

2021-09-28 05:12 UTC, macho-catt approved these changes
Worked in my environment. Good job!

2021-09-28 05:12 UTC, merged