Program Area Filter
hackforla/website pull request #2259
Opened 2021-09-14 03:50 UTC by Abel-Zambrano

Fixes #2076

### What changes did you make and why did you make them ?

  - Added Program Areas Filter to better filter through the list of projects.
  - Removed Locations Filter per another [issue](https://github.com/hackforla/website/projects/7#card-66864847)
  - Restructured MD files to work properly with the filtering functionality and for URL compatability.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

![Firefox_Screenshot_2021-09-14T03-47-46 043Z](https://user-images.githubusercontent.com/67209686/133191963-eab7f874-4a77-42fb-8218-1eca4f9c96f6.png)

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
![Firefox_Screenshot_2021-09-14T03-46-44 477Z](https://user-images.githubusercontent.com/67209686/133192008-a6221a6f-ea51-410a-a369-4a01031ef023.png)

</details>

2021-09-14 04:35 UTC, macho-catt commented
@Abel-Zambrano looks like there's a merge conflict that needs to be resolved. Could you work on that as well? Thanks!

2021-09-14 20:12 UTC, Abel-Zambrano commented
@macho-catt I resolved the merge conlict. Thank you.

2021-09-16 22:07 UTC, aalieu reviewed
Great job @Abel-Zambrano! I went through and tried all the functions and new filter and nothing broke so it works nicely on my end. I'm not approving this just yet though because I know we're trying to refactor our JS by having it all in the assets/js directory (mentioned at the bottom of #2076) but I don't know if there were any exceptions to this rule so I will get the opinion of the others. 

@Sihemgourou @Aveline-art @abuna1985 
Sorry for the ping, but since I don't know enough of the scope of our refactoring efforts, could one of you chime in on whether or not Abel should move his JS code?

2021-09-17 01:18 UTC, Aveline-art commented
> Sorry for the ping, but since I don't know enough of the scope of our refactoring efforts, could one of you chime in on whether or not Abel should move his JS code?

All JS code (baring exceptions, like google analytics) needs to be in our assets folder with an appropriate name. @Abel-Zambrano Please move the script in accordance to the architecture notes in #2076

2021-09-17 05:10 UTC, abuna1985 requested changes, later dismissed
@Abel-Zambrano Great job working on this pull request. Per the Architecture Notes within https://github.com/hackforla/website/issues/2076#issue-964466087, please do the following:

1. Move the contents in between `<script>` `</script>` to a new file you create in the `assets/js/` (per the standard `assets/js/current-projects.js`).
2. replace the `<script>`  within `_includes/current-projects.html` with a new `<script>` that has a `src` attribute that points to the newly created file.

2021-09-23 01:46 UTC, Abel-Zambrano commented
Updates are done. Thank you for the help! @abuna1985

2021-09-24 21:00 UTC, aalieu approved these changes
Everything still works after the JS code move. Great job!

2021-09-24 22:32 UTC, macho-catt commented on assets/js/current-projects.js
> +            let arr = projectdata.filter(function(item){
Since you're already using arrow functions for .sort, why not use it here as well? It will also improve readability.

2021-09-24 22:55 UTC, macho-catt commented on assets/js/current-projects.js
> +            'programs': [...new Set(sortedProjectData.map(item => item.project.programs ? item.project.programs.map(program => program) : '').flat() ) ].filter(v=>v!='').sort(),
While it's nice to chain javascript functions into one line, I wonder if this sacrifices readability and maintainability for the future? It makes it harder to decipher for future devs that may stumble across this in the future, and they may need to spend some time to debug this part.

It may be a good idea to break this down into multiple lines before the "return" call and place the final resulting array here instead.

2021-09-24 22:55 UTC, macho-catt commented on assets/js/current-projects.js
> +            'technologies': [...new Set(sortedProjectData.map(item => item.project.technologies ? item.project.technologies.map(tech => tech) : '').flat() ) ].filter(v=>v!='').sort(),
Same as above

2021-09-24 22:55 UTC, macho-catt commented on assets/js/current-projects.js
> +            'status': [... new Set(sortedProjectData.map(item => item.project.status))].sort(),
This one is shorter so it's easier to understand, but it may be worth to separate as well

2021-09-24 23:05 UTC, macho-catt commented
Looks good for the most part! I added some comments, but then I realized that some are already existing code. Feel free to apply the changes, or just resolve the convo.

2021-09-26 20:57 UTC, macho-catt approved these changes
Looks good to me. GJ!

2021-09-29 15:47 UTC, merged