Fix header bug
hackforla/website pull request #2281
Opened 2021-09-16 00:37 UTC by glenflorendo

Fixes #2269

### What changes did you make and why did you make them ?
  - Remove margins for `header-text` class to properly center the header description and image

Please note that this change affects the following:
| File                               | Web Page                                          |
|------------------------------------|---------------------------------------------------|
| pages/about.html                   | https://www.hackforla.org/about                   |
| pages/communities-of-practice.html | https://www.hackforla.org/communities-of-practice |
| pages/credits.html                 | https://www.hackforla.org/credits                 |
| pages/join-us.html                 | https://www.hackforla.org/join                    |
| pages/program-areas.html           | https://www.hackforla.org/program-areas           |
| pages/project-meetings.html        | https://www.hackforla.org/project-meetings        |
| pages/sitemap.html                 | https://www.hackforla.org/sitemap                 |
| pages/toolkit.html                 | https://www.hackforla.org/toolkit                 |

### Screenshots of Proposed Changes (Before vs After)

<details>
<summary>about</summary>

<img width="1883" alt="about" src="https://user-images.githubusercontent.com/9373317/133529665-b0883ca8-57af-49bf-9547-eefb344442ec.png">

![about_change](https://user-images.githubusercontent.com/9373317/133529742-d20e5201-500d-43c8-bfa4-c47b8eeaa606.png)

</details>

<details>
<summary>communities-of-practice</summary>

![communities-of-practice](https://user-images.githubusercontent.com/9373317/133529666-65090b3c-ea2f-451d-93e2-d660ee7b47db.png)

![communities-of-practice_change](https://user-images.githubusercontent.com/9373317/133529746-26245f9d-08f1-4c05-911e-6da52208a66a.png)

</details>

<details>
<summary>credits</summary>

![credits](https://user-images.githubusercontent.com/9373317/133529669-2d0decaa-ba73-484e-819c-f551beffaffe.png)

![credits_change](https://user-images.githubusercontent.com/9373317/133529749-f8442670-7a77-46b6-945f-e2c501c4c600.png)

</details>

<details>
<summary>join</summary>

![join](https://user-images.githubusercontent.com/9373317/133529671-c74d40cc-b43f-4f80-b446-5093a23b1eb9.png)

![join_change](https://user-images.githubusercontent.com/9373317/133529751-35b8df16-e43e-4b71-aa3b-031a2d604f32.png)

</details>

<details>
<summary>program-areas</summary>

![program-areas](https://user-images.githubusercontent.com/9373317/133529673-f6c70a8b-a7ca-428a-9b82-ede9f50d1490.png)

![program-areas_change](https://user-images.githubusercontent.com/9373317/133529752-082b1fea-fe42-4d94-b2dd-8dc809f8cf90.png)

</details>

<details>
<summary>project-meetings</summary>

![project-meetings](https://user-images.githubusercontent.com/9373317/133529676-d2575661-6745-459a-8131-c19d47ff86cd.png)

![project-meetings_change](https://user-images.githubusercontent.com/9373317/133529753-d86e35ec-dfb8-4cd8-96fe-4d9bb3a36960.png)

</details>

<details>
<summary>sitemap</summary>

![sitemap](https://user-images.githubusercontent.com/9373317/133529677-d4fba381-e42e-47db-8716-64f40eb3d260.png)

![sitemap_change](https://user-images.githubusercontent.com/9373317/133529755-b3f761ba-46da-45a8-a814-00ffb7d5983d.png)

</details>

<details>
<summary>toolkit</summary>

![toolkit](https://user-images.githubusercontent.com/9373317/133529679-e8fd9a54-41ff-4fa1-b63e-09e620e91d31.png)

![toolkit_change](https://user-images.githubusercontent.com/9373317/133529756-e33f511b-539b-4e0d-ba1c-19ad6cd83b97.png)

</details>

2021-09-16 23:59 UTC, abuna1985 approved these changes, later dismissed
@glenflorendo Great work. I was able to pull the changes locally and verify the hero/header sections are centered again on the 8 pages listed. Great work. Thank you for your efficient solution! 🎉 🎉 🎉

2021-09-17 00:32 UTC, abuna1985 requested changes
@glenflorendo Great job on creating a solution to resolve the header/hero alignment. I have added comments within the pull request changes. But to reiterate:

1. revert the change from line 14 of `_sass/elements/containers.scss` and add back `margin-right: 5em`;
2. Delete `.header-text` styling from line 83-91

https://github.com/hackforla/website/blob/62efccdf474e283ce8ea202d927706605f79f2e5/_sass/elements/_containers.scss#L83-L91

As soon as these changes are made, I will review the changes.

Thank you!

2021-09-17 00:32 UTC, abuna1985 commented on _sass/elements/_containers.scss
Let's add this back. @arghmatey brought up that this margin works as a space between the image and the text, so it is needed for wide pages so that it matches the Figma design.

2021-09-17 00:32 UTC, abuna1985 commented on _sass/elements/_containers.scss
>    max-width: 895px;
Apparently is whole class `.header-text` is a redundant block line 83-91. Let's remove the whole `.header-text` stylings (line 83-91). 
https://github.com/hackforla/website/blob/62efccdf474e283ce8ea202d927706605f79f2e5/_sass/elements/_containers.scss#L83-L91

2021-09-17 00:55 UTC, glenflorendo commented on _sass/elements/_containers.scss
>    max-width: 895px;
Yesterday, I saw that `.header-text` was defined twice, but I didn't question further in case that was on purpose. lol.

2021-09-17 02:11 UTC, glenflorendo commented
> @glenflorendo Great job on creating a solution to resolve the header/hero alignment. I have added comments within the pull request changes. But to reiterate:
> 
> 1. revert the change from line 14 of `_sass/elements/containers.scss` and add back `margin-right: 5em`;
> 2. Delete `.header-text` styling from line 83-91
> 
> https://github.com/hackforla/website/blob/62efccdf474e283ce8ea202d927706605f79f2e5/_sass/elements/_containers.scss#L83-L91
> 
> As soon as these changes are made, I will complete another review.
> 
> Thank you!

@abuna1985 @arghmatey Changes done!

2021-09-17 05:18 UTC, abuna1985 approved these changes

2021-09-17 05:29 UTC, abuna1985 approved these changes
@glenflorendo Excellent work. I was able to verify the changes have corrected the header title/text/image sections for the 8 pages listed. Thank you for responding so quickly! 🎉 🎉 🎉

2021-09-17 05:30 UTC, merged