Update global image info and change file name
hackforla/website pull request #2300
Opened 2021-09-22 07:19 UTC by Zhu-Joseph

Fixes #2095 

### What changes did you make and why did you make them ?

  - Replaced generic Noun Project link with [specific link](https://thenounproject.com/search/?q=impact&i=1710368)
  - Update title from Global to Environmental Impact
  - Update artist to Made x Made
  - Changed name of global.yml file to environmental-impact.yml

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

![Before-Global](https://user-images.githubusercontent.com/76148970/134299728-25f51c04-13bb-4dfe-a6ca-bc5b21691e24.png)

</details>

<details>
<summary>Visuals after changes are applied</summary>

![After-Global](https://user-images.githubusercontent.com/76148970/134299751-51d8f7dd-6ad2-408b-a1d2-6a5acf45c552.png)
aching_Files)

</details>

2021-09-23 03:33 UTC, macho-catt requested changes
Hi Joseph. For the most part, changes look good! However, you swapped title-link and provider-link. It should be the other way around. You can reference another yml file in the code (like care.yml).

2021-09-23 03:34 UTC, macho-catt commented on _data/internal/credits/environmental-impact.yml
> +provider-link: https://thenounproject.com/search/?q=impact&i=1710368
This should stay to https://thenounproject.com/

2021-09-23 03:34 UTC, macho-catt commented on _data/internal/credits/environmental-impact.yml
>  title-link: https://thenounproject.com/
Title link should be: https://thenounproject.com/search/?q=impact&i=1710368

2021-09-23 04:44 UTC, Zhu-Joseph commented on _data/internal/credits/environmental-impact.yml
> +provider-link: https://thenounproject.com/search/?q=impact&i=1710368
Hi Matt, I swapped and updated the links. They should be correct now.

2021-09-23 04:44 UTC, Zhu-Joseph commented on _data/internal/credits/environmental-impact.yml
>  title-link: https://thenounproject.com/
Hi Matt, I swapped and updated the links. They should be correct now.

2021-09-24 04:06 UTC, macho-catt approved these changes
LG. Good job!

2021-09-24 04:06 UTC, merged