New citizen engagement page
hackforla/website pull request #2324
Opened 2021-10-01 22:05 UTC by R-Tomas-Gonzalez

Fixes #2180 

### What changes did you make and why did you make them ?

  -
  -
  -

<summary>
This is a developed webpage of the figma design for Citizen Engagement. We originally discussed using liquid to pull data to fill each card, however, there is not enough data to implement that task. At the moment, all cards are static. I have left detailed comments in both the html and css files, but please reach out to me with any questions. 
</summary>

2021-10-05 20:57 UTC, abuna1985 requested changes
@R-Tomas-Gonzalez Thank you so much for taking on this large project and delivering a visual prototype. Can I have you make 2 changes:
1. Can you move up the bullet points in your pull request under the title `What changes did you make and why did you make them ?`. This is formatting for the review team and project managers. 
2. Can you also add an image to the PR. This can be done with the [GoFullPage Chrome extension](https://chrome.google.com/webstore/detail/gofullpage-full-page-scre/fdpohaocaechififmbbbbbknoalclacl?hl=en). I would spin up the Docker build and take a full-page screenshot. You can drop the image into the textbox and it will create a markdown version of the image (hosted by GitHub).

**If you want to go above and beyond:** you can move the markdown image like:

```
![](https://via.placeholder.com/150)
```

![](https://via.placeholder.com/150)

to an HTML `<img>` and wrap that in a `<details>/<summary>` tag like so:

```
<details>
   <summary>Click here to see my picture</summary>
   <img src="https://via.placeholder.com/150" />
</details>
```

<details>
   <summary>Click here to see my picture</summary>
   <img src="https://via.placeholder.com/150" />
</details>

**Note**: the `<details>/<summary>` tags are a built-in Accordion element. As you can see, `<summary>` is what will be placed next to the arrow and anything between `<details>` is shown. We do this so we keep the page clean and less distracting.

Thank you again for all your work on this. I am going to approve this PR and make some issues integrating liquid logic into the page after the PR is properly formatted. Great work! ⭐ ⭐ ⭐

2021-10-05 23:33 UTC, R-Tomas-Gonzalez commented
> @R-Tomas-Gonzalez Thank you so much for taking on this large project and delivering a visual prototype. Can I have you make 2 changes:
> 
> 1. Can you move up the bullet points in your pull request under the title `What changes did you make and why did you make them ?`. This is formatting for the review team and project managers.
> 2. Can you also add an image to the PR. This can be done with the [GoFullPage Chrome extension](https://chrome.google.com/webstore/detail/gofullpage-full-page-scre/fdpohaocaechififmbbbbbknoalclacl?hl=en). I would spin up the Docker build and take a full-page screenshot. You can drop the image into the textbox and it will create a markdown version of the image (hosted by GitHub).
> 
> **If you want to go above and beyond:** you can move the markdown image like:
> 
> ```
> ![](https://via.placeholder.com/150)
> ```
> 
> ![](https://camo.githubusercontent.com/f1c7ecc48cac77c6c7d404820b1cb402cd8ccb128470e252ccf9a22002bf4b67/68747470733a2f2f7669612e706c616365686f6c6465722e636f6d2f313530)
> 
> to an HTML `<img>` and wrap that in a `<details>/<summary>` tag like so:
> 
> ```
> <details>
>    <summary>Click here to see my picture</summary>
>    <img src="https://via.placeholder.com/150" />
> </details>
> ```
> 
> Click here to see my picture
> **Note**: the `<details>/<summary>` tags are a built-in Accordion element. As you can see, `<summary>` is what will be placed next to the arrow and anything between `<details>` is shown. We do this so we keep the page clean and less distracting.
> 
> Thank you again for all your work on this. I am going to approve this PR and make some issues integrating liquid logic into the page after the PR is properly formatted. Great work! ⭐ ⭐ ⭐

Thanks so much! I made the changes to the pr description. I need to mention that the "LA’s Sustainable Development Goals." needs to be linked in the third paragraph of the header. I have the link given to me by the designer -> " https://sdg.lamayor.org/about/global-goals" which was given to me after I made this pull request. I can add this and make the change, or we can create a new issue for this. Please let me know and I will adjust!

Thanks again!

2021-10-12 07:52 UTC, adam-abundis requested changes
@R-Tomas-Gonzalez Thank you for your patience. I have made one more request so it can be accessed within the site. Once that is complete, I will approve this PR.

2021-10-12 07:52 UTC, adam-abundis commented on pages/citizen-engagement.html
> +---
@R-Tomas-Gonzalez Can you add a new line under line 3 (title: Citizen Engagement) and add the permalink property
`permalink: /citizen-engagement`

This is needed to make the page available within Jekyll

2021-10-12 19:55 UTC, R-Tomas-Gonzalez commented on pages/citizen-engagement.html
> +---
Hey @abuna1985, 

I went ahead and added the permalink front matter. I also went ahead and added alt text for all images in the file as well. Please let me know if anything else is needed on my end! Thanks!

2021-10-14 00:04 UTC, adam-abundis approved these changes
@R-Tomas-Gonzalez Thank you again for all your help on this. I was able to see the updated changes. I will create a separate issue to implement project data and liquid template to make the projects dynamic.

Keep up the good work! ⭐  ⭐  ⭐

2021-10-14 03:13 UTC, macho-catt approved these changes
This looks good. Good job @R-Tomas-Gonzalez!

2021-10-14 03:13 UTC, merged

2021-10-14 03:39 UTC, macho-catt commented
@R-Tomas-Gonzalez huge oversight on my part, after the merge it changed the CSS on the main page and the projects pages, so I had to revert your PR to fix it. Basically, the main page page cards changed and became larger when they were not supposed to:

<details>
<summary>Original</summary>

![original](https://user-images.githubusercontent.com/48004150/137246726-a71f84e5-69d5-40e5-9bb5-510a7d13c544.png)

</details>

<details>
<summary>Main page after PR</summary>

![cards-are-bigger](https://user-images.githubusercontent.com/48004150/137246763-ac79350f-f381-406d-b42f-3294fdb04fa4.png)

</details>

And the project pages changed as well:

<details>
<summary>Original</summary>

![original-projects](https://user-images.githubusercontent.com/48004150/137246813-1aba81df-c30f-4495-a0c7-1677a675e8c2.png)

</details>

<details>
<summary>Projects after PR</summary>

![projects-messed](https://user-images.githubusercontent.com/48004150/137246838-b477e0ec-f357-4c3d-8277-95f587e23284.png)

</details>

And I believe that's because you updated the default classes in your file changes. Instead, you should add in a new class for this page specifically without editing the default classes. For example, you edit the .page-card class in citizen_engagement.scss, which actually overrides the page-card classes in other pages as well. What you need is to create a new class and add that new class along with .page-card, and edit the new class instead so the page cards in other pages don't get affected. Same goes with the other classes in the projects pages.

Does that make sense? Apologies again for missing this. Please reach out to me if you have questions. Thanks.