Fix Wins Tablet Icon Styling
hackforla/website pull request #2340
Opened 2021-10-06 05:33 UTC by adrian-zaragoza

Fixes #2176 

### What changes did you make and why did you make them ?
  - Created a media query for a max with of $screen-tablet and a min-width of $screen-mobile because this is the view of tablets.
  - Added grid to the .wins-tablet class with 2 columns at 50% each.
  - increased the width of the wins text bubble to 70% to make the text less clunky.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

![image](https://user-images.githubusercontent.com/77212035/136145819-a5d64ea6-5105-4e53-bda9-fafbcc0f8f0f.png)

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
![image](https://user-images.githubusercontent.com/77212035/136145701-6bcd96d7-cf04-46d8-a050-f0c5d8d44c13.png)

</details>

2021-10-12 06:52 UTC, adam-abundis requested changes
@adrian-zaragoza Thank you for your pull request. I was able to see the changes made. I made 1 suggestion to add a CSS property so the icons and text-align to the top. 

Once the changes are updated, I will review the PR again. Let me know if you have any questions. Thank you! 👋 👋 👋

2021-10-12 06:52 UTC, adam-abundis commented on _sass/components/_wins-page.scss
> +        display: grid;
Can you add a new line in between 531-532 (under .wins-tablet{) and add the CSS property:
`align-items: flex-start;`

2021-10-13 01:31 UTC, adrian-zaragoza commented on _sass/components/_wins-page.scss
> +        display: grid;
@abuna1985  thanks for the suggestion! The wins icons look so much better now with the align-items property. 

<details>
<summary>Visuals after changes are applied</summary>
  
![image](https://user-images.githubusercontent.com/77212035/137051225-df0cea0a-7682-43f6-9cb2-82047a7b6ca8.png)

</details>

2021-10-13 23:47 UTC, adam-abundis requested changes
@adrian-zaragoza My apologies for the multiple edit requests. Once you update line 530, I will merge it. Thank you again for helping us with this issue.

2021-10-13 23:47 UTC, adam-abundis commented on _sass/components/_wins-page.scss
> +@media screen and (max-width: $screen-tablet) and (min-width: $screen-mobile){
@adrian-zaragoza Can you please do me one more favor? Can we switch to `(max-width: $screen-desktop)` on line 530. The value (960px) will also fill the tablet view with the new styling you added. Thank you.

2021-10-18 23:57 UTC, adrian-zaragoza commented on _sass/components/_wins-page.scss
> +@media screen and (max-width: $screen-tablet) and (min-width: $screen-mobile){
@abuna1985 I have updated the max-width to $screen-desktop.

2021-10-19 22:58 UTC, adam-abundis approved these changes
@adrian-zaragoza Thank you so much for the changes and for working on this. I was able to view the changes and see the changes for the Wins page in tablet view. I will approve this and merge it. Excellent work! ⭐ ⭐ ⭐

2021-10-19 22:59 UTC, merged