Add design systems project info for display
hackforla/website pull request #2365
Opened 2021-10-12 05:11 UTC by adam-abundis

Fixes #2255 

### What changes did you make and why did you make them?

  - Added `assets/images/projects/design-systems-hero.jpg`  & `assets/images/projects/design-systems.jpg` for the design system project
  - Added `_projects/design-systems.md` with the relevant information provided in the issue

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
 <summary>Visuals <strong>after</strong> changes are applied (<strong>desktop</strong>)</summary>
  <h3>Hack for L.A. projects design systems page - desktop version</h3>
  <img alt="Hack for L.A. projects design systems page - desktop version" src="https://user-images.githubusercontent.com/21162229/136894703-5e9c71d7-09e4-4fae-b12b-017e29726ffc.png" />
  <h3>Hack for L.A. projects design systems card - desktop version</h3>
  <img alt="Hack for L.A. projects design systems card - desktop version" src="https://user-images.githubusercontent.com/21162229/136894662-927a96f3-d549-4639-a423-45e9aa3332cc.jpg" />
</details>

<details>
  <summary>Visuals <strong>after</strong> changes are applied (<strong>mobile</strong>)</summary>
  <h3>Hack for L.A. projects design systems page - mobile version</h3>
  <img alt="Hack for L.A. projects design systems page - mobile version" src="https://user-images.githubusercontent.com/21162229/136895239-841c8251-a635-463d-a5a0-05c5ce23204d.png" />
  <h3>Hack for L.A. projects design systems card - mobile version</h3>
  <img alt="Hack for L.A. projects design systems card - mobile version" src="https://user-images.githubusercontent.com/21162229/136895204-3fe78d2c-aeaa-4908-a443-074a39e82a4a.jpg" />
</details>

2021-10-12 15:36 UTC, macho-catt requested changes

2021-10-12 15:36 UTC, macho-catt commented on _projects/design-systems.md
> +program area: Civic Tech Infrastructure
Looks good overall! Good job! Just one change. Update this to:
```
program-area:
  - Civic Tech Infrastructure
```
So it appears in the filter and conforms with the structure of the other project md files.

2021-10-12 19:18 UTC, adam-abundis commented on _projects/design-systems.md
> +program area: Civic Tech Infrastructure
@macho-catt Thanks for catching this. I have pushed a commit that updates the `program-area` property format.

2021-10-14 03:09 UTC, macho-catt approved these changes
lgtm. Good job as always!

2021-10-14 03:10 UTC, merged