fix footer for 404 and redirect page
hackforla/website pull request #2390
Opened 2021-10-22 20:44 UTC by Abel-Zambrano

Fixes #2125

### What changes did you make and why did you make them ?

  - Fixed footer positioning to the bottom of the page, so we can have a consistent look for the page footer no matter the width of the page (all breakpoints) 
  - Fixed 404 page
  - Fixed redirect page
  - Removed extra closing div from projects page which was pushing the footer out of the HTML structure

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

<img width="1436" alt="prev_redirect" src="https://user-images.githubusercontent.com/67209686/138520404-1fdaed54-48fe-499e-9b45-48add23e9b26.png">

<img width="505" alt="prev_404" src="https://user-images.githubusercontent.com/67209686/138520420-918636c5-6ba4-45de-8d77-30d0fc959fc2.png">

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
![redirect](https://user-images.githubusercontent.com/67209686/138520612-8cbb8038-16e9-44b3-b784-732796c076a1.png)
![404](https://user-images.githubusercontent.com/67209686/138520621-4e27a208-4de8-4d76-9863-ebc9990fbf04.png)

</details>

2021-10-23 04:27 UTC, adam-abundis requested changes
@Abel-Zambrano I found the following issues with both the projects page & wins page

<details>
  <summary>Click here to see projects page gif</summary>
<p>Noitice when there is 1 card, the footer goes under the card and the height stays as long as the dropdown filter menu</p><strong>The footer is not at the bottom</strong>

![Projects - Hack for LA](https://user-images.githubusercontent.com/21162229/138542073-3cae4b72-300e-4e25-a8de-342230fd9de7.gif)

<p>screenshot of footer display error (wins page)</p>

![screencapture-hackforla-org-projects-2021-10-22-21_22_24](https://user-images.githubusercontent.com/21162229/138542142-ffaf7f45-c173-424d-966a-3c7e0bfc3070.png)
</details>

<details>
  <summary>Click here to see wins page gif</summary>
<p>Noitice when there is 0card, the footer goes under the blank space and the height stays as long as the dropdown filter menu</p><strong>The footer is not at the bottom</strong>

![Wins - Hack for LA](https://user-images.githubusercontent.com/21162229/138542178-ff07a2ae-9810-4ac0-93bf-cfbcf15728c6.gif)

<p>screenshot of footer display error (wins page)</p>

![screencapture-hackforla-org-wins-2021-10-22-21_21_36](https://user-images.githubusercontent.com/21162229/138542185-9fd6b402-ee3f-4d1a-81a6-35ab6e8c1fe2.png)
</details>

2021-10-26 03:56 UTC, Abel-Zambrano commented
> @Abel-Zambrano I found the following issues with both the projects page & wins page
> Click here to see projects page gif
> **The footer is not at the bottom**
> Click here to see wins page gif
> **The footer is not at the bottom**

@abuna1985 Were you able to pull my branch for testing? I'm not seeing the issues locally.

2021-10-26 07:41 UTC, adam-abundis requested changes
@Abel-Zambrano I pull ed your changes and experienced the following issues

**Wins Page**

Even with absolute positioning, the Team dropdown menu is pushing the page down. So when there is no cards selected the footer has whitespace under it.

<details>
  <summary>Click here to see screenshots after selecting 'role' of <strong>Data</strong> and 'Team' of <strong>Data</strong> </summary>

![wins-data-engage-selected](https://user-images.githubusercontent.com/21162229/138829934-dbfadcd1-b4c9-46fb-9278-e37682357a65.jpg)
</details>

**Projects Page**

I selected `Adobe CC` within the Technologies dropdown. The Technologies dropdown menu pushes the page down and there is scrollable whitespace between the gray background and the footer.
<details>
  <summary>Click here to see gif of Projects page selecting <strong>Abobe CC</strong> within 'Technologies' dropdown</summary>

![projects-adobe-cc](https://user-images.githubusercontent.com/21162229/138830581-aa7940de-1d1d-4d93-b9a9-70cfc8f9f469.gif)

</details>

2021-10-27 02:29 UTC, Abel-Zambrano commented
@abuna1985 Thanks for the help. I was able to replicate the issue for the wins page and fix it. As for the projects page, I'm unsure of what changes need to be made, if you could provide more info that would be great. The footer is at the bottom of the projects page.

2021-10-28 06:08 UTC, adam-abundis requested changes
I have some more suggestions. I am going to remove the wins page in the issue requirement and create a separate issue.

2021-10-28 06:08 UTC, adam-abundis commented on _sass/components/_wins-page.scss
> +.wins-section {
This is not going to work. Now the gray background only lasts a bit past the page. We should not set a specific height to content that is changing height depending on how many cards it has. Please remove `.wins-section` styling and undo any changes in the wins page CSS. The wins page will not be a part of this issue anymore. Thank you.

2021-10-28 20:48 UTC, adam-abundis requested changes
@Abel-Zambrano There seems to be a merge conflict that needs to be resolved. Once this has been resolved, I will approve this and merge the changes.

Thank you.

2021-10-28 20:48 UTC, adam-abundis commented on pages/wins/wins.html
> +<section class="content-section projects wins-section">
Can you remove `wins-section` since we are not using it at all.

2021-10-28 20:49 UTC, adam-abundis submitted a review, later dismissed

2021-10-28 21:28 UTC, Abel-Zambrano commented
@abuna1985 The changes have been made. Thank you.

2021-11-05 17:00 UTC, macho-catt requested changes
Hi @Abel-Zambrano, thank you on working on this and I apologize for the delay. I checked the changes on my environment and saw some problems on my end. 

For this issue, let's focus on the 404 page and the redirection page. The problem with the projects page and wins page are separate and looks like they occur on the production website anyway, so you can ignore them and we can create an issue to address those :)

So the problems I saw on my end. Since you set the height to the 404 container and redirect container to 100vh, it almost works in terms of fixing the footer to a certain part of the page. However, it also makes it so that on certain devices, the 404 container (and redirect container) will fill up 100% of the viewport page, then you have to scroll down to see the footer. How does that look like?

<details>
<summary> Click to see gif for 404 </summary>

![404](https://user-images.githubusercontent.com/48004150/140548779-b7bf53c6-05b3-46d9-ac90-6a053d71e84c.gif)

</details>

<details>
<summary> Click to see gif for redirect </summary>

![redirect](https://user-images.githubusercontent.com/48004150/140548865-ad88f38c-f7d7-4a65-a955-ed2ffbb4b5bd.gif)

</details>

If the content on the page is small enough that you should see everything (including the footer) without scrolling, then setting the container to 100vh would result in scrolling. We don't want this.


I tried playing around to see what the best way to fix this would be, and I think setting the height for 404 to 100% instead of 100vh fixes it for that page. However, that won't work for the redirect page because the contents are so tiny so you may have to play around with that to get the correct solution.

Just a note, setting the footer to position absolute would work 99% of the time. For our case it doesn't work because the footer does not share the same parent element as the container for 404 and redirect (and any other containers in the page). Unfortunately, that's how this was set up before we came in and to fix that would introduce a whole new set of issues....

I also saw this [article](https://www.freecodecamp.org/news/how-to-keep-your-footer-where-it-belongs-59c6aa05c59c/) that I think is the solution to the problem, but it involves reorganizing the html structure. If you're up to that, go for it, but be aware that we would have to triple-check each individual pages to ensure it doesn't break anything.

2021-11-05 17:03 UTC, macho-catt commented on _sass/components/_404.scss
> +  height: 100vh;
almost works, but makes it so that you have to scroll down on desktop view to see the footer. This will need adjustment. Consider setting it to 100% and double check that on all viewports it looks fine

2021-11-05 17:06 UTC, macho-catt commented on _sass/layouts/_redirect.scss
> +    height: 100vh;
almost works as well, but you will have to scroll to see the footer as well. This needs adjustment too, but since the content is so small setting this to 100% doesn't work. You may need to consider a different option for this...

2021-11-18 20:10 UTC, Abel-Zambrano commented
@macho-catt I was able to reorganize the HTML structure. Thanks for the help!

2021-12-04 23:33 UTC, macho-catt requested changes
Hi @Abel-Zambrano. Sorry for the delay. I looked at this in my local dev and the 404 and redirect pages look fine now. However, I noticed that the footer for other pages have a white gap now. Specifically, Events, Join Us, Toolkit, Wins, Sitemap, Citizen Engagement, etc. I believe it just needs some small adjustments and they should be good.

If you look closely, a white space is now added for each page at the bottom (example: Join Us page should be the gray background then immediately the blue footer. Now it's gray, then white, then blue. Toolkit page should be a solid blue throughout, now there's a white gap). 

<details>
<summary>Bottom of Join Us</summary>

![1](https://user-images.githubusercontent.com/48004150/144727789-e3cf07d7-8f0d-4c73-81e6-250ca7f039bd.png)

</details>

<details>
<summary>Bottom of Toolkit</summary>

![2](https://user-images.githubusercontent.com/48004150/144727790-b40f8479-6a1a-4ade-905b-ca3bd5ca0e1b.png)

</details>

And if you look at the Credits Page, the footer is not stuck to the bottom. Instead, it's floating in the middle. Could you take a look at this as well?

<details>
<summary>Footer is stuck in the middle of Credits Page</summary>

![3](https://user-images.githubusercontent.com/48004150/144727791-c9075683-c0ae-4c3e-9081-1b2242bac76e.png)

</details>

Tablet view show all the problems listed above, while Mobile view only shows the Credits page problem.

Thanks for all your work!

2021-12-05 04:37 UTC, Abel-Zambrano commented
@macho-catt the extra white spaces have been removed and the credits page has been fixed. There is an issue with the dashboard page having white space at the bottom but that is more related to the page design, not the footer placement, if that can be opened into its own separate issue that would be great. Thank you.

2021-12-10 01:54 UTC, macho-catt approved these changes
This looks good to me. Thanks for all your work and patience @Abel-Zambrano.

2021-12-10 01:55 UTC, merged