Refactor GitHub Action for setting PR labels
hackforla/website pull request #2453
Opened 2021-11-05 04:24 UTC by glenflorendo

Resolves #1892 

### What changes did you make and why did you make them?
- Move JavaScript code to `github-actions/set-pr-labels.js` to separate yaml and JavaScript for modularity
- Reimplement JavaScript logic
- Enhance the code to allow for more than one linked issue in the same repo
- Bread down yaml workflow logic into smaller steps for clarity
- Rename workflow and files to "set labels" instead of "add labels" since the action explicity sets the labels of the pull request instead of just adding labels
- Other changes

### Screenshots of Successful Run

![Screen Shot 2021-11-04 at 21 17 20](https://user-images.githubusercontent.com/9373317/140457622-6239eb63-14d3-4080-b5f7-43c04754e1eb.png)
![Screen Shot 2021-11-04 at 21 17 45](https://user-images.githubusercontent.com/9373317/140457623-276d4b2b-14a9-4cca-a7f0-98a7d26065a6.png)
![Screen Shot 2021-11-04 at 21 18 09](https://user-images.githubusercontent.com/9373317/140457626-b74586f1-3cfd-4ecc-8051-03c13ee9a449.png)

2021-11-13 04:55 UTC, macho-catt requested changes
This is awesome @glenflorendo! Great work. The code is clean and easy to read, and I like your usage of the reduce function. I also like the way you structured your js file and exported the functions.
I just have a couple of change requests on the yml file and the location of the js file. Overall, this is great.

2021-11-13 04:55 UTC, macho-catt commented on .github/workflows/set-pr-labels.yaml
> +    - 'wins-feature-1'
You can actually remove this since this branch was already merged to gh-pages

2021-11-13 04:58 UTC, macho-catt commented on .github/workflows/set-pr-labels.yaml
> +on: pull_request
When I ran the workflow on my repo, this structure did not work. I had to write it as:
```
on: 
  pull_request:
    types: [opened, edited]
    branches:
      - 'gh-pages'
```
Could you update this to follow that format so the workflow would run?
[Source](https://github.com/macho-catt/website/blob/0d38e1d5f12e41170ca2317b8c044354f0cbf792/.github/workflows/set-pr-labels.yaml#L3-L7)

2021-11-13 05:00 UTC, macho-catt commented on .github/workflows/set-pr-labels.yaml
> +      SCRIPT_PATH: './github-actions/set-pr-labels.js'
Is it possible to store the js file under `github-actions/trigger-pr/set-pr-labels` and update the paths in the workflow file to reflect the new directory?
I am in the process of restructuring the GitHub actions and this would help a lot.

2021-11-13 05:05 UTC, macho-catt commented on .github/workflows/set-pr-labels.yaml
> +      ARTIFACT_PATH: './artifacts/pr-labels.json'
Is it possible to update the path and name of the artifact to `'./set-pr-labels/artifacts/set-pr-labels.json'` so that it follows the name of the workflow that generated it?

2021-11-14 03:22 UTC, glenflorendo commented
> This is awesome @glenflorendo! Great work. The code is clean and easy to read, and I like your usage of the reduce function. I also like the way you structured your js file and exported the functions. I just have a couple of change requests on the yml file and the location of the js file. Overall, this is great.

All done, @macho-catt! I implemented your review points. I also tested the changes in an isolated repo/env and verified that the workflow still works.

2021-11-16 04:24 UTC, macho-catt approved these changes
LGTM. Good job!

2021-11-16 04:24 UTC, merged