Add files via upload
hackforla/website pull request #2470
Opened 2021-11-10 19:08 UTC by chrisfoose

Fixes #replace_this_text_with_the_issue_number

### What changes did you make and why did you make them ?

  -  Added requested text to bottom of the document.
  -  No screenshot.
  -

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

![image](Paste_Your_Image_Link_Here_After_Attaching_Files)

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
![image](Paste_Your_Image_Link_Here_After_Attaching_Files)

</details>

2021-11-11 01:47 UTC, glenflorendo requested changes
Really great work! I especially like the image. 🤗

Just small nit picks, and you're good to go!

2021-11-11 01:47 UTC, glenflorendo commented on README.md
> +## We love our Stars ⭐⭐⭐
nit. I believe headings should be surrounded by blank lines, similar to how `##Contributing` (line 16) has newlines before and after it (line 15 and line 17).

2021-11-11 01:47 UTC, glenflorendo commented on README.md
> +## We love our Stars ⭐⭐⭐
nit. Just wondering if we should capitalize all of the words here, since it's a heading title. 🤔

2021-11-13 19:01 UTC, adrian-zaragoza submitted a review, later dismissed
This looks good to me! Thank you @chrisfoose !

2021-11-17 00:10 UTC, glenflorendo requested changes
Great work on adding the spacing, and I'm really sorry for being unclear about the capitalization previously.

nit. Could you please update the headings for "Contributing" and "We Love Our Stars ⭐⭐⭐".

2021-11-17 00:10 UTC, glenflorendo commented on README.md
> +## CONTRIBUTING
nit. Oh, sorry! I didn't mean all caps / uppercase. I meant like "Contributing".

2021-11-17 00:10 UTC, glenflorendo commented on README.md
> +## WE LOVE OUR STARS ⭐⭐⭐
nit. Same as above. I meant like "We Love Our Stars ⭐⭐⭐". Sorry for being unclear!

2021-11-17 02:17 UTC, glenflorendo approved these changes
@chrisfoose Awesome work!

2021-11-17 16:37 UTC, macho-catt approved these changes
LGTM

2021-11-17 16:37 UTC, merged