Update citizen engage 2474
hackforla/website pull request #2603
Opened 2021-12-18 22:59 UTC by anthonysim

Fixes #2474 

### What changes did you make and why did you make them ?

- For each of the projects that are currently in the [Citizen Engagement page](https://www.hackforla.org/citizen-engagement), edit the corresponding md file under the [_projects collection directory](https://github.com/hackforla/website/tree/gh-pages/_projects) so that the data lives there
    - Add a new property "problem" and copy the Problem description from the specific project in the Citizen Engagement page to the markdown file
    - Add a new property "solution" and copy the Solution description from the specific project in the Citizen Engagement page to the markdown file
    - Add a new property "Impact" and copy the Impact description from the specific project in the Citizen Engagement page to the markdown file
    - Add a new property "sdg" and copy the Sustainable Development Goal description from the specific project in the Citizen Engagement page to the markdown file
    - Add a new property "sdg-image" and copy the destination of the asset used to the markdown file
- Update the [citizen-engagement.html](https://github.com/hackforla/website/blob/gh-pages/pages/citizen-engagement.html) file so that instead of statically rendering the data, it uses liquid to loop through the [_projects collections](https://github.com/hackforla/website/tree/gh-pages/_projects). If the project has the value "Citizen Engagement" for the program-area property, it should render it
    - Use the new properties declared above to render the data for each project
- Ensure that the page still looks and functions the same after the change

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>
<img src="https://user-images.githubusercontent.com/31682285/146657051-e5e37882-0d4a-4203-bd1d-b4faef5a63c5.png" width="500" length="500" /> 
</details>

<details>
<summary>Visuals after changes are applied</summary>
<a href="https://github.com/anthonysim/website/blob/1b9ccb3772349173bfe614092c818cf0ec563086/pages/citizen-engagement.html#L52" >Reference to Changes</a>
<p>There are no "visual" changes, the data is dynamically rendered instead of typed out on the html page.</p>

<img src="https://user-images.githubusercontent.com/31682285/146657051-e5e37882-0d4a-4203-bd1d-b4faef5a63c5.png" width="500" length="500" /> 
</details>

2021-12-18 23:03 UTC, anthonysim commented
For <a href="https://www.hackforla.org/citizen-engagement" target="_blank">Open Community Survey</a> under "Impact" its just Lorem Ipsum text, there wasn't anything written there and its currently like that live on the site. I'm going to bring this up in the next meeting. 

![Screen Shot 2021-12-18 at 2 34 37 PM](https://user-images.githubusercontent.com/31682285/146657273-a2401ef8-ae26-44f1-87df-d450547c9436.png)

2021-12-19 18:43 UTC, R-Tomas-Gonzalez commented
@R-Tomas-Gonzalez Bring up the lorem ipsum to design on Dec. 19 meeting! Thanks @anthonysim

2021-12-20 00:10 UTC, anthonysim commented
@ExperimentsInHonesty @R-Tomas-Gonzalez 

- WHAT I DID?
@ExperimentsInHonesty @R-Tomas-Gonzalez, I created a resuseable card in the `_includes` folder that iterates through the md files in `_projects` and generates a card for each item that has a program-area of Citizen Engagement and visible of true. 

- WHAT IS THE ISSUE?
The src and alt in the img tags are not dynamic because properties for these items are not in the md files currently. The issue write-up above did not address this. 

- QUESTION THAT I HAVE/SOLUTION?
The src links and alt descriptions need to be dynamic as well for the img tags. Should these be added as properties in the md files that have to do with Citizen Engagement? If so, what would these property names be (src-card, alt-card, alt-card-sdg)? Currently there are properties with the names images and alt that are in these md files for other use. 

- REFERENCE TO THE ISSUE.
Please see the img tags below, there are 2 where I placed the notes - QUESTIONS HOW TO MAKE THIS REUSEABLE.

```
{% assign visible_projects = site.projects | where: "program-area", "Citizen Engagement" | where: "visible", "true" %}
             {% for item in visible_projects %}
                   <div class="page-card card-primary page-card-lg card-body card-width program-area" data-dropdown>

                     <!-- QUESTIONS HOW TO MAKE THIS REUSEABLE-src alt  -->

                        <img class="card-image" src="/assets/images/projects/311.jpg" alt="311 project card"/>
                           <div class="mobile-card-info-container">
                               <div class="mobile-card-nav">
                                   <h3>{{ item.title }}</h3>
                                   <input class="dropdown-arrow" data-dropdown-arrow type="image" src="/assets/images/citizen-engagement/arrow-button-icon.svg" alt="dropdown-arrow">
                               </div>
                               <div class="project-dropdown">
                                           <div class="problem-info">
                                               <h4>Problem</h4>
                                               <p>{{ item.problem }}</p>
                                           </div>
                                           <div class="solution-info">
                                               <h4>Solution</h4>
                                               <p>{{ item.solution }}</p>
                                           </div>
                                           <div class="impact-info">
                                               <h4>Impact</h4>
                                               <p>{{ item.impact }}</p>
                                           </div>
                               </div>
                           </div>
                       <div class="sustainable-dev-goal">
                           <h4>Sustainable Development Goal</h4>
                           <div class="card-bottom-info">

                            <!-- QUESTIONS HOW TO MAKE THIS REUSEABLE-alt -->

                               <img class=src="{{ item.sdg-image }}" alt="peace justice bottom sustainable dev goal"/>
                                       <p>{{ item.sdg }}</p>
                           </div>
                       </div>
                   </div>
            {% endfor %}
```

2021-12-20 14:48 UTC, JimGeist commented
Hi Anthony, I hope to review this pull request sometime today (Monday, Dec. 20, 2021).

2021-12-20 19:53 UTC, anthonysim commented
@JimGeist it's actually not done yet. I wrote about an additional that the original issue ticket didn't address above. Waiting for direction from the powers that be.

2021-12-20 19:54 UTC, anthonysim commented
> Hi Anthony, I hope to review this pull request sometime today (Monday, Dec. 20, 2021). 

@JimGeist it's actually not done yet. I wrote about an additional that the original issue ticket didn't address above. Waiting for direction from Bonnie and Tomas.

2021-12-21 03:16 UTC, R-Tomas-Gonzalez commented
Quick note on this issue: Anthony and I zoomed and discussed how we should tackle the images and alt tags. We have decided to put them in the markdown file that will generate the project cards on the citizen-engagement page.

2021-12-21 03:36 UTC, anthonysim commented
@JimGeist

Hey @R-Tomas-Gonzalez, I finished up with the changes we discussed.

Note <a href="https://github.com/anthonysim/website/blob/4fc19828b08421af64ad392b8d7f154caeb07925/_includes/citizen-engagement-cards.html#L33">Click Here</a>, I had to change the class name back from card-bottom-icon from what we discussed earlier (sdg-image) because there is specific styling associated with that class name and it messed everything up when I used sdg-image.

2021-12-21 03:38 UTC, anthonysim commented
> @JimGeist
> 
> Hey @R-Tomas-Gonzalez, I finished up with the changes we discussed.
> 
> Note [Click Here](https://github.com/anthonysim/website/blob/4fc19828b08421af64ad392b8d7f154caeb07925/_includes/citizen-engagement-cards.html#L33), I had to change the class name back from card-bottom-icon from what we discussed earlier (sdg-image) because there is specific styling associated with that class name and it messed everything up when I used sdg-image.

@JimGeist

Hey @R-Tomas-Gonzalez, I finished up with the changes we discussed.

Note <a href="https://github.com/anthonysim/website/blob/4fc19828b08421af64ad392b8d7f154caeb07925/_includes/citizen-engagement-cards.html#L33">Click Here</a>, I had to change the class name back from card-bottom-icon from what we discussed earlier (sdg-image) because there is specific styling associated with that class name and it messed everything up when I used sdg-image.

2021-12-22 04:23 UTC, anthonysim commented
@JimGeist, I updated the class names in the <a href="https://github.com/anthonysim/website/blob/7bc2dac7d6e882f6d12adb99354b2683262c5f3a/_includes/citizen-engagement-cards.html#L28">image tags</a> and <a href="https://github.com/anthonysim/website/blob/7bc2dac7d6e882f6d12adb99354b2683262c5f3a/_sass/components/_citizen_engagement.scss#L128">scss</a> per discussion with @R-Tomas-Gonzalez. 

Everything is good to go for the review!

2021-12-23 02:16 UTC, JimGeist commented on _projects/lucky-parking.md
> +problem: Parking citations are distributed unevenly across different socio-economic strata of the cities residents as they use public parking during the course of business or because enough off-stree
I know the text was pulled from the website, but can you change "cities" to "city's"? We need possessive noun, not a plural noun.
Parking citations are distributed unevenly across different socio-economic strata of the cities residents as they use public parking ...
to 
Parking citations are distributed unevenly across different socio-economic strata of the city's residents as they use public parking ...

2021-12-23 03:12 UTC, anthonysim commented on _projects/lucky-parking.md
> +problem: Parking citations are distributed unevenly across different socio-economic strata of the cities residents as they use public parking during the course of business or because enough off-stree
@JimGeist, updated cities to city's.

2021-12-23 03:19 UTC, JimGeist commented on _projects/open-community-survey.md
> +# citizen engagement card data
Thank you Anthony for making these changes. Looks like Open Community Survey was added to the Citizen Engagement page by mistake because it's project area is 'Vote / Representation'

2021-12-23 03:25 UTC, JimGeist requested changes
Hi Anthony, Everything looks great and on this. I am requesting a minor change to an existing typo in Lucky Parking. In the problem statement, "cities residents" should be "city's residents". Awesome job by the way!!

2021-12-23 03:25 UTC, JimGeist commented on _projects/lucky-parking.md
> +problem: Parking citations are distributed unevenly across different socio-economic strata of the cities residents as they use public parking during the course of business or because enough off-stree
I know the text was pulled from the website, but please change "cities" to "city's"? 
Parking citations are distributed unevenly across different socio-economic strata of the cities residents as they use public parking ...
to
Parking citations are distributed unevenly across different socio-economic strata of the city's residents as they use public parking ...

2021-12-23 03:30 UTC, anthonysim commented on _projects/lucky-parking.md
> +problem: Parking citations are distributed unevenly across different socio-economic strata of the cities residents as they use public parking during the course of business or because enough off-stree
> I know the text was pulled from the website, but please change "cities" to "city's"? Parking citations are distributed unevenly across different socio-economic strata of the cities residents as they use public parking ... to Parking citations are distributed unevenly across different socio-economic strata of the city's residents as they use public parking ...

@R-Tomas-Gonzalez @JimGeist , good to go! Cities was changes to city's!

2021-12-23 04:23 UTC, JimGeist approved these changes
Everything looks great Anthony and thank you for the quick turn around with correcting an existing typo in Lucky Parking's Problem statement. I have verified the changes locally and this pull request is OK to merge.

2021-12-23 16:32 UTC, R-Tomas-Gonzalez commented on _projects/open-community-survey.md
> +# citizen engagement card data
@JimGeist  @anthonysim Before merging, let's bring this up to Bonnie on Sunday. I'd like to go through with her each project to see if all program-areas are correct in regards to citizen-engagement

2021-12-23 16:36 UTC, R-Tomas-Gonzalez reviewed
Very nice job, @anthonysim! This looks fantastic. I want to wait to merge this issue to see if we can figure out which program areas we are wanting to add. We did have the open-community-survey in the figma design. Let's wait and see what @ExperimentsInHonesty says

2021-12-23 16:38 UTC, R-Tomas-Gonzalez commented
@ExperimentsInHonesty Looks to me like @anthonysim has finished up all that we have asked of him. I had a question on the open-community-survey project. It was listed on the figma design and there is copy for it. The program area is listed as "Vote / Representation"... Is this correct?

2021-12-23 16:40 UTC, anthonysim commented
> @ExperimentsInHonesty Looks to me like @anthonysim has finished up all that we have asked of him. I had a question on the open-community-survey project. It was listed on the figma design and there is copy for it. The program area is listed as "Vote / Representation"... Is this correct? 

Yea that's the program area, it looks like it was mistakenly placed as citizen engagement on the live site. After the conditions were applied for program area, it doesn't include open community survey anywhere.

2021-12-23 16:57 UTC, R-Tomas-Gonzalez commented
> > @ExperimentsInHonesty Looks to me like @anthonysim has finished up all that we have asked of him. I had a question on the open-community-survey project. It was listed on the figma design and there is copy for it. The program area is listed as "Vote / Representation"... Is this correct?
> 
> @R-Tomas-Gonzalez Yea that's the program area (I didn't change it), it looks like it was mistakenly placed in citizen engagement on the live site. After the conditions were applied for program area, it doesn't include open community survey anywhere. If the program area is wrong, let me know and I can change it accordingly.

For sure. Yeah, that's what I had thought – that it is actually the vote / representation program area, and they accidentally placed it in the figma design. I just want to make sure with Bonnie, so we don't have to close and reopen this issue! Great work :)

2021-12-26 18:59 UTC, ExperimentsInHonesty commented
- I made a new issue to change the program area on the open community survey so its properly reflected as citizen engaement https://github.com/hackforla/website/issues/2631

2021-12-30 00:25 UTC, SAUMILDHANKAR commented
@R-Tomas-Gonzalez I am planning to merge this. Looks like all concerns have been addressed.

2021-12-30 08:31 UTC, merged