solving issue 2544... changing team leadership
hackforla/website pull request #2620
Opened 2021-12-22 20:28 UTC by Georgema20

Fixes #2544 

### What changes did you make and why did you make them ?

I removed Mathew Cacho, Sihem Gourou, Kristine Eudey and add Tomas Gonzalez, Saumil Dhankar, Isaac Cruz, and Simone Campbell on the Website team project page leadership section.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

<img width="910" alt="Screen Shot 2021-12-22 at 3 27 10 PM" src="https://user-images.githubusercontent.com/83432699/147151441-6df0bde1-05ac-4b44-96e8-9591f9732c08.png">

</details>

<details>
<summary>Visuals after changes are applied</summary>
  

<img width="919" alt="Screen Shot 2021-12-22 at 3 26 56 PM" src="https://user-images.githubusercontent.com/83432699/147151450-95276812-5672-4145-a0dd-7d07588fc1de.png">

</details>

2021-12-24 21:37 UTC, JessicaLucindaCheng commented on _projects/website.md
> +    picture: https://avatars.githubusercontent.com/sacamp
Needs single quotes around https://avatars.githubusercontent.com/sacamp

2021-12-24 21:38 UTC, JessicaLucindaCheng commented on _projects/website.md
> +    picture: https://avatars.githubusercontent.com/mmaecruz
Needs single quotes around https://avatars.githubusercontent.com/mmaecruz

2021-12-24 21:53 UTC, Georgema20 commented
@JessicaLucindaCheng I do not see your comments anymore, but I saw your email. You said all the pictures need "" around them? True?

2021-12-24 22:24 UTC, JessicaLucindaCheng requested changes
- All double quotes need to be changed to single quotes.
- I think the contact information for Isaac Cruz is incorrect. Isaac's GitHub is https://github.com/IsaacDesigns and Slack id is U0255408P8Q.
- Also, please add your pull request to the project board. Thank you.

2021-12-24 22:25 UTC, JessicaLucindaCheng commented
> @JessicaLucindaCheng I do not see your comments anymore, but I saw your email. You said all the pictures need "" around them? True?

Sorry, that was my mistake. The pictures don't need quotes. The pictures are fine as is. See my review above requesting changes.

2021-12-24 22:28 UTC, Georgema20 commented
@JessicaLucindaCheng  making all changes right now.

2021-12-24 22:30 UTC, Georgema20 commented
@JessicaLucindaCheng 

Do you mean every single double quote needs to be changed to single quote? Before in the original, there were double quotes in some things prior to me.

2021-12-24 22:39 UTC, JessicaLucindaCheng commented
@Georgema20 I think your IDE is automatically changing the quotes. If you look at the Files changed tab, you can see the single quotes on each line are changed to double quotes.

2021-12-24 22:49 UTC, Georgema20 commented
@JessicaLucindaCheng  DOne! I realized that it was an extension I had on github that was doing that... my bad. Turned that off so it won't be a problem in the future.

2021-12-25 00:14 UTC, JessicaLucindaCheng requested changes
@Georgema20 Thanks for making the requested changes! The code looks good now.

Could you update the image for the "Visuals after changes are applied" in your initial post/comment? I see something different now.

2021-12-25 02:23 UTC, Georgema20 commented
@JessicaLucindaCheng Done!

2021-12-25 03:12 UTC, JessicaLucindaCheng approved these changes
@Georgema20 Looks good to me! Good job!

2021-12-27 06:25 UTC, SAUMILDHANKAR approved these changes
@Georgema20 Thanks for working on this issue. Changes look good in my environment.

2021-12-27 06:27 UTC, merged