Changing titles for issue 2604
hackforla/website pull request #2640
Opened 2021-12-28 16:53 UTC by Georgema20

Fixes #2604

### What changes did you make and why did you make them?

  
 Changed the words from "Current Project Team" to "Project Team" on completed projects because these words need to be changed when projects are completed. 

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

<img width="879" alt="Screen Shot 2021-12-28 at 11 05 55 AM" src="https://user-images.githubusercontent.com/83432699/147586538-a5cdf5e6-8c75-43d0-a357-34b71201e0fc.png">
<img width="741" alt="Screen Shot 2021-12-28 at 11 06 37 AM" src="https://user-images.githubusercontent.com/83432699/147586540-38db459c-be51-49b5-8f98-98cf2a37134a.png">
<img width="899" alt="Screen Shot 2021-12-28 at 11 06 06 AM" src="https://user-images.githubusercontent.com/83432699/147586541-fcab77d0-a550-4b4d-b288-8484ecba9d44.png">
<img width="901" alt="Screen Shot 2021-12-28 at 11 05 39 AM" src="https://user-images.githubusercontent.com/83432699/147586543-d58b85f9-d902-4ad1-bb3f-3a69c2f62f54.png">
<img width="411" alt="Screen Shot 2021-12-28 at 11 06 46 AM" src="https://user-images.githubusercontent.com/83432699/147586545-f43078c3-8528-4798-9470-3d70b8fbc837.png">
<img width="844" alt="Screen Shot 2021-12-28 at 11 06 19 AM" src="https://user-images.githubusercontent.com/83432699/147586546-670cf43f-dd6f-48f3-b020-0d44f4b98870.png">
<img width="665" alt="Screen Shot 2021-12-28 at 11 06 29 AM" src="https://user-images.githubusercontent.com/83432699/147586547-1f4834db-ff36-4cc7-b607-e82fdbdaf743.png">

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
<img width="795" alt="Screen Shot 2021-12-28 at 11 21 35 AM" src="https://user-images.githubusercontent.com/83432699/147586558-f89cfe3d-6873-49c6-9f89-73a1a1503cb2.png">
<img width="734" alt="Screen Shot 2021-12-28 at 11 21 46 AM" src="https://user-images.githubusercontent.com/83432699/147586560-e8986136-c4b8-460e-84fb-f2d41d06e5ef.png">
<img width="848" alt="Screen Shot 2021-12-28 at 11 22 06 AM" src="https://user-images.githubusercontent.com/83432699/147586563-52f68b4e-c53a-400e-b653-0d66f3844a99.png">
<img width="498" alt="Screen Shot 2021-12-28 at 11 22 37 AM" src="https://user-images.githubusercontent.com/83432699/147586565-2b804572-a87c-4d4b-9bb5-4f5510b43f7c.png">
<img width="813" alt="Screen Shot 2021-12-28 at 11 21 56 AM" src="https://user-images.githubusercontent.com/83432699/147586566-331754c5-6002-4906-bd66-b5ad8d036e87.png">
<img width="476" alt="Screen Shot 2021-12-28 at 11 22 44 AM" src="https://user-images.githubusercontent.com/83432699/147586567-fa3f3b03-eeff-4357-85fe-b844d8c364f7.png">
<img width="509" alt="Screen Shot 2021-12-28 at 11 22 29 AM" src="https://user-images.githubusercontent.com/83432699/147586569-2460c439-115b-40e0-8545-8c87b1aa30d9.png">

</details>

2021-12-29 01:22 UTC, JessicaLucindaCheng commented
Review ETA: Thurday, December 30, 2021

2021-12-29 23:23 UTC, sydneywalcoff commented
Review ETA: tomorrow, thursday Dec 30, 2021

2021-12-30 01:22 UTC, JessicaLucindaCheng requested changes
Please make the requested changes in my line comments.

2021-12-30 01:22 UTC, JessicaLucindaCheng commented on _projects/ems-triage-tracker.md
> +alt: ' EMS Triage Tracker Logo'
Remove the extra space between the single quote and EMS, so it looks like this 
```
alt: 'EMS Triage Tracker Logo'
```

2021-12-30 01:22 UTC, JessicaLucindaCheng commented on _projects/ems-triage-tracker.md
> +alt-hero: ' EMS Triage Tracker dashboard with breakdown of casualty numbers and a satellite view of the street grid with blue casualty location markers.'
Remove the extra space between the single quote and EMS, so it looks like this 
```
alt-hero: 'EMS Triage Tracker dashboard with breakdown of casualty numbers and a satellite view of the street grid with blue casualty location markers.'
```

2021-12-30 01:22 UTC, JessicaLucindaCheng commented on _layouts/project.html
> +        <h2 class='project-page-card-title title6'>Project Team</h2>
Indent this line to make the code easier to read.

2021-12-30 01:22 UTC, JessicaLucindaCheng commented on _layouts/project.html
>          <h2 class='project-page-card-title title6'>Current Project Team</h2>
Indent this line to make the code easier to read.

2021-12-30 01:22 UTC, JessicaLucindaCheng commented on _layouts/project.html
> +         {% if page.status=="Completed" %}
Remove a space before { so that this line is indented the same amount as line 110 and 112. Also, add a space before and after ==, so it looks like this
```
{% if page.status == "Completed" %}
``` 
This helps make the code easier to read.

2021-12-30 21:26 UTC, JessicaLucindaCheng requested changes
@Georgema20 Thanks for making the changes! We're almost there. In _layouts/project.html, can you also indent lines 109 and 111? This will help make it easier to read the code.

2021-12-30 22:03 UTC, sydneywalcoff reviewed
The corrected "Project Team" titles look great. Once we get that small indent corrected that @JessicaLucindaCheng pointed out, I'm good to approve :)

2021-12-31 00:45 UTC, Georgema20 commented
Done!

2021-12-31 01:52 UTC, JessicaLucindaCheng requested changes
In lines 109 and 111, remove a space before <h2 class='project-page-card-title title6'>. This will make the amount of indentation consistent with the rest of the code.

2021-12-31 02:09 UTC, Georgema20 commented
Done! I hope. Sorry about all that. My bad.

2021-12-31 17:04 UTC, sydneywalcoff approved these changes
Looks good to me!

2021-12-31 20:31 UTC, JessicaLucindaCheng approved these changes
@Georgema20 Thanks for making all those changes! Good job! It looks good to me now.

2022-01-01 20:57 UTC, SAUMILDHANKAR commented
@Georgema20: Looks like you picked an issue from the new issue approval column. As per the [comment](https://github.com/hackforla/website/issues/2604#issuecomment-997490870) this issue needs a rewrite and is not ready to be worked upon. In future, please pick an issue from the Prioritized Column and not the New Issue Approval column. I am planning to close this PR. Once the issue is ready you can work on it. Thank you.

2022-01-01 23:46 UTC, closed without merging