Apply Title heading class to Events page #2081
hackforla/website pull request #2645
Opened 2021-12-30 04:23 UTC by lindseyindev

Fixes #2081

### What changes did you make and why did you make them ?

  -Added appropriate Title classes to events page headings per [figma design file](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=8552%3A0)

  -Updated heading elements to be more semantically correct for screen readers because the styling is now through the Title class.
  

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals after changes are applied</summary>
  
![image](https://gyazo.com/1b698a2ddd07488faf978124f2fc2823.png)
(No drastic change, I checked my work using the inspector)
</details>

2021-12-30 15:20 UTC, Georgema20 commented
Everything looks good, but when I pull it up, there is a visual change in the left column as a result of the class change put in onboarding and those titles. Please make sure to reflect this properly in the visuals after change section with screenshots. Also, please put in a before screenshot as well. 

Everything else looks pretty good. Keep it up! Make the changes then I can approve PR.

2022-01-01 18:43 UTC, lindseyindev commented
@Georgema20 thank you for letting me know, I updated the PR comment for your review!

2022-01-01 19:38 UTC, Georgema20 approved these changes, later dismissed

2022-01-01 19:38 UTC, Georgema20 commented
Nice work!

2022-01-04 12:14 UTC, SAUMILDHANKAR commented
Review ETA: EOD 1/5/22
Availability: 6 hrs

2022-01-05 01:23 UTC, SAUMILDHANKAR requested changes, later dismissed
@lindseyindev Hi Lindsey, thanks for taking up this issue. I have been comparing your events page with that at Figma and I see that the titles onboarding, workshop, happy hour should be dark gray whereas in your branch they don't appear so. As per the design in Figma, they should be dark gray.

2022-01-05 02:49 UTC, lindseyindev commented
I updated the scss for the title-meetup class which applies to just those titles that were showing as pink from styling on the h4 element, I updated the color to #33333 per the figma file and I also updated the after picture in my submission!

2022-01-07 12:17 UTC, SAUMILDHANKAR commented
Revised review ETA: EOD 1/8
Availability: Saturday 2-5 PM

2022-01-10 10:46 UTC, SAUMILDHANKAR commented
Revised review ETA: EOD 1/10
Availability: Monday 2-4 PM

2022-01-11 12:08 UTC, SAUMILDHANKAR reviewed
title1, title2 etc in lower case.

2022-01-11 12:08 UTC, SAUMILDHANKAR commented on _includes/events-page/header-container-content.html
> +      <h1 class="Title1">Events</h1>
Hi @lindseyindev, please make all title lower case, example: title1, title2 and so on

2022-01-11 12:13 UTC, SAUMILDHANKAR commented
> I updated the scss for the title-meetup class which applies to just those titles that were showing as pink from styling on the h4 element, I updated the color to #33333 per the figma file and I also updated the after picture in my submission!

Great job in catching the color of h4. As per design system on Figma, text color should be black or white and red is reserved for links, so just wondering if we should remove red color from h4. This can be part of future issue, we can confirm with design in sunday meeting.

2022-01-13 00:42 UTC, lindseyindev commented
Updated the title classes to be lower case & submitting for re-review!

Would definitely recommend a suggestion for design & for other new developers, like how we mentioned in the meeting differences between design and codebase, that the figma class should be text-cased to match what will be coded especially if that's the reference for devs 
or it's noted in the issue if for some reason figma classes can't be lowercased

2022-01-16 15:56 UTC, JessicaLucindaCheng commented
- Availability: 6 hours
- Review ETA: Tue, Jan 18, 2022

2022-01-18 23:26 UTC, JessicaLucindaCheng requested changes
@lindseyindev Thanks for working on this issue for so long! In addition to my inline comments, could you update your before and after images with a full screen shot of the page?
 
You can use this extension: https://chrome.google.com/webstore/detail/gofullpage-full-page-scre/fdpohaocaechififmbbbbbknoalclacl?hl=en

2022-01-18 23:26 UTC, JessicaLucindaCheng commented on _includes/events-page/right-col-content.html
> +            <h5 class="day-header-1 title7">{{day}}</h5>
Line 25 _includes/events-page/right-col-content.html should be an `h4` html header tag, not `h5`.

2022-01-18 23:26 UTC, JessicaLucindaCheng commented on _sass/components/_events.scss
> +  color: #333333;
Instead of adding the line `color: #333333`, could you apply the class `color-black` to the header html tags that need it?

For your reference, the `color-black` class comes from here: https://github.com/hackforla/website/blob/508dc989cf45a8b339fb430e87e22f751bc17db1/_sass/elements/_color-styles.scss

2022-01-24 20:33 UTC, JessicaLucindaCheng commented
@lindseyindev Please provide your availability and ETA for working on the requested changes above.

2022-01-26 03:00 UTC, lindseyindev commented
> @lindseyindev Please provide your availability and ETA for working on the requested changes above.

I did not see this until now, I should have this updated within 24 hours!!!

2022-01-26 21:27 UTC, JessicaLucindaCheng commented
- Availability: 6 hours
- Review ETA: Thursday, January 27, 2022

2022-01-28 01:25 UTC, JessicaLucindaCheng commented
@lindseyindev Sorry, I don't have time to review it today. So, I will be delaying my review by one day.
- Availability: 6 hours
- ETA: Friday, January 28, 2022

2022-01-28 21:42 UTC, JessicaLucindaCheng requested changes
@lindseyindev Thanks for making the requested changes! I think we are almost there with this pull request. Once you make changes based on my in-line request for a change, can you update your before and after images in your [original post/comment](https://github.com/hackforla/website/pull/2645#issue-1090867092)? The before should look like the current webpage. Thank you for all your hard work!

2022-01-28 21:42 UTC, JessicaLucindaCheng commented on _includes/events-page/right-col-content.html
> +            <h4 class="day-header-1 title7">{{day}}</h4>
Add the class `color-black` to this header so that the color of the font for days of the week headers match the current website.

The SCSS class `.color-black` is defined in [line 50 in _sass/elements/_color-styles.scss](https://github.com/hackforla/website/blob/713e9504e59ae8c4f3a1575e118f49376a40ec15/_sass/elements/_color-styles.scss#L50) as `.color-black { color: $color-black; }`

2022-01-31 05:27 UTC, lindseyindev commented
I didn't realize changing the h5 tag to h4 undid the previous fix I did to make the color adhere to the figma so I fixed it by targetting the day heading class.

Also somehow a pull request I reviewed is being added as a commit when I pushed my code even though that was on a separate branch and I never committed it

The code with the <strong> tags in the commit history.. https://github.com/hackforla/website/pull/2718 not sure how to undo that on my end -- I dont see a way to remove that part of the commit

2022-02-01 23:52 UTC, JessicaLucindaCheng commented
- Availability: 3 hours
- Review ETA: Thu, Feb 3, 2022

2022-02-02 23:18 UTC, SAUMILDHANKAR commented
Revised review ETA: 2/3/22
Availability: 6-8 PM Thursday

2022-02-02 23:51 UTC, JessicaLucindaCheng requested changes
@lindseyindev 
> The code with the ** tags in the commit history.. #2718 not sure how to undo that on my end -- I dont see a way to remove that part of the commit**

I'm wondering if doing the following would fix the problem you are having:
i. Update your forked gh-pages so that it is in sync with the hackforla/website gh-pages. Here are instructions for [how to update your forked gh-pages](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#27e-working-on-an-issue-5-incorporating-changes-from-upstream).
ii. Then merge your gh-pages into your topic branch locally.
iii. Then push the merged changes in your topic branch locally to your remote topic branch in your forked repo.

2022-02-06 16:35 UTC, lindseyindev commented
I think it worked but I'm not entirely sure how.. like how pushing to my remote fork also pushes to this PR at the same time

2022-02-07 01:05 UTC, JessicaLucindaCheng commented
- Availability: 6 hours
- Re-review ETA: Mon, Feb 7, 2022

2022-02-07 21:08 UTC, JessicaLucindaCheng approved these changes
@lindseyindev Thanks for updating your topic branch!
> I think it worked but I'm not entirely sure how.. like how pushing to my remote fork also pushes to this PR at the same time

To answer your question, your pull request is connected to your topic branch:
<img width="437" alt="image" src="https://user-images.githubusercontent.com/31293603/152871921-0cc036c2-e6d4-4fe5-bff9-b2ab3287da70.png">

Thus, any changes to your topic branch will show up in your pr.

2022-02-07 21:10 UTC, merged