first attempt at issue 2598
hackforla/website pull request #2665
Opened 2022-01-07 03:45 UTC by Georgema20

Fixes #2598

### What changes did you make and why did you make them ?

  - Changed @media from below mobile to below tablet bc things that were in between tablet and mobile were leading to bad display (ie things were being cut off). 
  -
  -

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

<img width="436" alt="Screen Shot 2022-01-06 at 10 40 38 PM" src="https://user-images.githubusercontent.com/83432699/148488106-7614dfb1-23ed-485e-87b2-484bcb457c4d.png">

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
<img width="402" alt="Screen Shot 2022-01-06 at 10 40 07 PM" src="https://user-images.githubusercontent.com/83432699/148488124-75f6593f-b064-4007-aaa7-7fcc8adff6c9.png">

</details>

2022-01-10 23:59 UTC, lopezpedres commented
Availability: 6 hours
Review ETA: Wed, Jan 12, 2022

2022-01-11 21:06 UTC, sydneywalcoff requested changes
Hi George! Once you get that small adjustment done, this LGTM!

2022-01-11 21:06 UTC, sydneywalcoff commented on _sass/variables/_layout.scss
> +
Hey George! Let's delete this extra space as you didn't edit this page :)

2022-01-11 22:40 UTC, lopezpedres requested changes
Hi @Georgema20 great job. Ready to be merge once you make the correction that @sydneywalcoff  pointed out.

2022-01-11 23:01 UTC, Georgema20 commented
Done! Check my commit! :) Thanks so much!

2022-01-11 23:12 UTC, lopezpedres approved these changes
Cool, LGTM :) @Georgema20

2022-01-14 02:03 UTC, sydneywalcoff approved these changes
LGTM!

2022-01-19 00:39 UTC, JessicaLucindaCheng requested changes
@Georgema20 Thanks for working on the issue! Could you take full page screenshots of the before and after pictures for what it looks like on the Surface Duo size screen and update your original post with them? You can use this Chrome extension to do so: https://chrome.google.com/webstore/detail/gofullpage-full-page-scre/fdpohaocaechififmbbbbbknoalclacl?hl=en

2022-01-20 01:08 UTC, Georgema20 commented
Updated! Please merge :)

2022-01-20 18:28 UTC, JessicaLucindaCheng approved these changes
@Georgema20 Looks good to me!

2022-01-20 18:30 UTC, merged