Update tech dropdown 2397
hackforla/website pull request #2672
Opened 2022-01-08 03:18 UTC by anthonysim

Fixes #2397 

### What changes did you make and why did you make them ?

  - Added media query for min-width 768px. I added css grid at a width of 748px so the new dropdown would fit properly on an IPAD and IPAD Pro. The original issue did not account for other sizes except a desktop so I had to make sure everything "looked" good on an IPAD and IPAD Pro.
  - Added media query for min-width 1024px. I added a width of 768px as the original issue stated.
  - Ensure the dropdown matches [Version A of the Projects page Figma design](https://github.com/hackforla/website/issues/2069#issuecomment-927388942)
  - Mobile was not changed from the original since there was a discussion on slack that a new issue would be made to create a scrollbar box. 

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>
<img src="https://user-images.githubusercontent.com/31682285/148629599-cc6dba42-e6ab-4c15-92ed-cca9ca3eb708.png" width="750" length="750" />
</details>

<details>
<summary>Visuals after changes are applied</summary>
  <img src="https://user-images.githubusercontent.com/31682285/148629626-2506aed3-b1b0-4dd3-9458-661a5d34d91a.png" width="750" length="750" />
</details>

2022-01-08 11:29 UTC, JessicaLucindaCheng commented
- Availability: 6 hours
- Review ETA: Wed, Jan 12, 2021

2022-01-10 23:04 UTC, lopezpedres commented
Availability: 10 hours
Review ETA: Wed, Jan 11, 2022

2022-01-10 23:52 UTC, lopezpedres commented
Hi @anthonysim ! REALLY GOOD JOB. The dropdown looks really well. It ran really nice on the desktop, iPad, and iPad Pro view.
There are two main points that I just want to highlight (I am not entirely sure If they are part of this issue, we might need to create new ones)

1. According to the version A of the Figma design, the dropdown arrow should be pointing up when the dropdown is selected

    <details>
    <summary>Figma Version A</summary>
   
    ![Dropwdown Arrow](https://user-images.githubusercontent.com/63615112/148855904-2a674b1d-247b-4457-b643-af1e54c6ba24.png)

    </details>
    <details>
    <summary>Antony's version</summary>
  
    ![PR version](https://user-images.githubusercontent.com/63615112/148856813-6c5ddcb8-5fc6-457c-a037-0e51addae8c7.png)

    </details>

2. The mobile view should have a scrolling bar once the dropdown menu is active
     <details>
    <summary>Figma Mobile Version</summary>
       
    ![image](https://user-images.githubusercontent.com/63615112/148857097-2b765291-a4f6-4181-9801-1412a30390eb.png)

    </details>
    <details>
    <summary>Antony's version</summary>
  
    ![mobile dropdown](https://user-images.githubusercontent.com/63615112/148857267-e0c677a5-3cdc-4b38-94a0-86c5e1e80bce.png)

    </details>

@JessicaLucindaCheng please let me know what you think about these points. Otherwise, ILGTM and ready to be merged :)

2022-01-10 23:55 UTC, lopezpedres commented
> Hi @anthonysim ! REALLY GOOD JOB. The dropdown looks really well. It ran really nice on the desktop, iPad, and iPad Pro view. There are two main points that I just want to highlight (I am not entirely sure If they are part of this issue, we might need to create new ones)
> 
> 1. According to the version A of the Figma design, the dropdown arrow should be pointing up when the dropdown is selected
>     
>     Figma Version A
>    ![Dropwdown Arrow](https://user-images.githubusercontent.com/63615112/148855904-2a674b1d-247b-4457-b643-af1e54c6ba24.png)
>     
>     
>     Antony's version
>    ![PR version](https://user-images.githubusercontent.com/63615112/148856813-6c5ddcb8-5fc6-457c-a037-0e51addae8c7.png)
> 2. The mobile view should have a scrolling bar once the dropdown menu is active
>      
>     Figma Mobile Version
>    ![image](https://user-images.githubusercontent.com/63615112/148857097-2b765291-a4f6-4181-9801-1412a30390eb.png)
>     
>     
>     Antony's version
>    ![mobile dropdown](https://user-images.githubusercontent.com/63615112/148857267-e0c677a5-3cdc-4b38-94a0-86c5e1e80bce.png)
> 
> @JessicaLucindaCheng please let me know what you think about these points. Otherwise, ILGTM and ready to be merged :)

Sorry guys! I just saw Anthony's comment about the mobile version. Please ignore the second point :) @anthonysim @JessicaLucindaCheng

2022-01-11 02:53 UTC, JessicaLucindaCheng commented
@lopezpedres In the current website, all the dropdowns (Status, Technologies/Languages, Program Areas) have the arrows pointing down. I think the arrow of the dropdown is fine as is in terms of this issue. However, we can bring it up with the design team and ask them. We may want to ask design for an updated projects page, so all of us are on the same page in terms of what is wanted currently, including with the addition of languages from pr https://github.com/hackforla/website/pull/2646.

2022-01-11 03:44 UTC, lopezpedres commented
@JessicaLucindaCheng Awesome! Thanks for replying :)

2022-01-11 03:46 UTC, lopezpedres approved these changes, later dismissed
Nicely done @anthonysim !

2022-01-11 05:37 UTC, JessicaLucindaCheng requested changes
Thank you for working on this issue! Your changes along with the recent inclusion of languages into the technologies dropdown looks like this:

![wider-dropdown-anthony-sim-update-tech-dropdown-2397](https://user-images.githubusercontent.com/31293603/148887290-47114abd-eac7-4777-833c-72c18e08240a.png)

Please update your forked repo and then merge those updates into your branch. Then, please make changes so that the menu includes the languages and is still 4 columns. Thank you.

2022-01-11 05:37 UTC, JessicaLucindaCheng commented on _sass/components/_project-filter.scss
> +  display: grid;
This was originally on lines 10 and 11. Just wondering why did you decide to move them?

2022-01-11 05:37 UTC, JessicaLucindaCheng commented on _sass/components/_project-filter.scss
> +@media (min-width: 768px) {
From https://github.com/hackforla/website/blob/gh-pages/_sass/variables/_layout.scss, please use one of the variables there for creating your media queries. For example, this line of code becomes `@media ($bp-below-tablet) {`.

2022-01-11 05:37 UTC, JessicaLucindaCheng commented on _sass/components/_project-filter.scss
> +@media (min-width: 1024px) {
Would it be possible to use one of the variables in https://github.com/hackforla/website/blob/gh-pages/_sass/variables/_layout.scss for writing this media query?

2022-01-11 05:44 UTC, JessicaLucindaCheng commented
@lopezpedres You said you saw 4 columns for the technologies dropdown. Did yours include languages?

2022-01-11 06:11 UTC, anthonysim commented on _sass/components/_project-filter.scss
> +@media (min-width: 768px) {
@JessicaLucindaCheng , I just thought keeping all the stuff related to css grid close together made more sense. To see the grid, column gap, then grid template columns.

2022-01-11 06:22 UTC, anthonysim commented on _sass/components/_project-filter.scss
> +@media (min-width: 1024px) {
@JessicaLucindaCheng, yeah, I can try and use one of the variables. I'll give it a shot and push up the change.

2022-01-11 06:24 UTC, anthonysim commented on _sass/components/_project-filter.scss
> +  display: grid;
@JessicaLucindaCheng , I just thought keeping all the stuff related to css grid close together made more sense. To see the grid, column gap, then grid template columns. It doesn't change anything, but made it easier to read.

2022-01-11 06:32 UTC, anthonysim commented
@JessicaLucindaCheng @lopezpedres, I just changed the media queries to use variables.

2022-01-11 06:50 UTC, JessicaLucindaCheng commented on _sass/components/_project-filter.scss
> +@media (min-width: 768px) {
My bad. You are correct it should be $bp-table-up

2022-01-11 06:54 UTC, anthonysim commented
> Thank you for working on this issue! Your changes along with the recent inclusion of languages into the technologies dropdown look like this:
> 
> ![wider-dropdown-anthony-sim-update-tech-dropdown-2397](https://user-images.githubusercontent.com/31293603/148887290-47114abd-eac7-4777-833c-72c18e08240a.png)
> 
> Please update your forked repo and then merge those updates into your branch. Then, please make changes so that the menu includes the languages and is still 4 columns. Thank you.

So with the inclusion of the new technologies, I don't think I can follow Version A 
[Figma- Projects page dropdown (Version A)](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=15313%3A103303) as the original issue (#2397) stated. I'm assuming I should do Version C now?

2022-01-11 06:59 UTC, JessicaLucindaCheng commented
@anthonysim I realized I gave you the wrong formatting for using the variables in the media queries. Sorry for the confusion. As for which Figma version to follow, let's hold off on making changes until we can get some clarification.

2022-01-11 22:04 UTC, JessicaLucindaCheng commented
@SAUMILDHANKAR @R-Tomas-Gonzalez
See comment above: https://github.com/hackforla/website/pull/2672#issuecomment-1009649128

2022-01-11 22:47 UTC, lopezpedres commented
> @lopezpedres I see in your screenshots that you see 4 columns for the technologies dropdown. When you were viewing it, did it include languages?

@JessicaLucindaCheng It did not. I'll attach the full screenshot:

![image](https://user-images.githubusercontent.com/63615112/149033555-eb9f6cbf-e1d8-4850-9adf-4ca367499f1f.png)

2022-01-11 23:00 UTC, JessicaLucindaCheng commented
> > @lopezpedres I see in your screenshots that you see 4 columns for the technologies dropdown. When you were viewing it, did it include languages?
> 
> @JessicaLucindaCheng It did not. I'll attach the full screenshot:
> 
> ![image](https://user-images.githubusercontent.com/63615112/149033555-eb9f6cbf-e1d8-4850-9adf-4ca367499f1f.png)

@lopezpedres Okay. The languages were recently merged into the Hack for LA repo and I updated my forked gh-pages before using the git commands (see comment: https://github.com/hackforla/website/pull/2672#issuecomment-1007876122) to do it. I think that's why we are seeing different things.

2022-01-16 16:13 UTC, JessicaLucindaCheng commented
> So with the inclusion of the new technologies, I don't think I can follow Version A [Figma- Projects page dropdown (Version A)](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=15313%3A103303) as the original issue (#2397) stated. I'm assuming I should do Version C now and just do the scrollbar for mobile and desktop?

@anthonysim
@SAUMILDHANKAR spoke with @IsaacDesigns and Isaac said to go ahead with implementing Version C with the scrollbar for mobile and desktop in the Figma design.

2022-01-16 18:51 UTC, anthonysim commented
@JessicaLucindaCheng @lopezpedres, I added the scrollbars for the mobile and desktop. 

<img width="1440" alt="Screen Shot 2022-01-16 at 10 46 22 AM" src="https://user-images.githubusercontent.com/31682285/149673643-de6cad9c-cf15-4951-b8cc-5938d022f819.png">
<img width="369" alt="Screen Shot 2022-01-16 at 10 47 19 AM" src="https://user-images.githubusercontent.com/31682285/149673648-381336f1-ba36-4f28-b005-08361e749f63.png">

2022-01-18 00:33 UTC, lopezpedres approved these changes, later dismissed
@anthonysim Nicely done! LGTM Thanks for working in this issue Anthony!

2022-01-19 03:28 UTC, JessicaLucindaCheng commented
- Availability: 6 hours
- Re-review ETA: Thu, Jan 20, 2022

2022-01-20 18:58 UTC, JessicaLucindaCheng requested changes
@anthonysim Thanks for all your work on this issue! In developer tools on my browser, the Surface Duo size screen (540px wide) shows the desktop version of the `Languages / Technologies` dropdown. It should show the mobile version. Please fix this.

This is what I see:
<img width="318" alt="tech-dropdown-surface-duo-540px-screen" src="https://user-images.githubusercontent.com/31293603/150404107-3240a7bc-f787-4531-a593-b8a6ed72bf01.png">

2022-01-22 03:04 UTC, anthonysim commented
> > So with the inclusion of the new technologies, I don't think I can follow Version A [Figma- Projects page dropdown (Version A)](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=15313%3A103303) as the original issue (#2397) stated. I'm assuming I should do Version C now and just do the scrollbar for mobile and desktop?
> 
> @anthonysim @SAUMILDHANKAR spoke with @IsaacDesigns and Isaac said to go ahead with implementing Version C with the scrollbar for mobile and desktop in the Figma design. @JessicaLucindaCheng will update the issue to reflect this change.

@lopezpedres @JessicaLucindaCheng, I made changes to account for the Surface Duo 540px screen size. 
![Screen Shot 2022-01-21 at 7 04 29 PM](https://user-images.githubusercontent.com/31682285/150622528-6c4cc7e8-2231-4937-adf6-ac6bc921b6b0.png)

2022-01-24 20:35 UTC, JessicaLucindaCheng commented
- Availability: 6 hours
- Review ETA: Tuesday, January 25, 2022

2022-01-25 18:55 UTC, JessicaLucindaCheng requested changes
@anthonysim Besides my inline comment request for change, good job implementing Version C and mobile designs!

2022-01-25 18:55 UTC, JessicaLucindaCheng commented on _sass/components/_project-filter.scss
> +@media #{$bp-ipadair-up} {
Could you use $bp-desktop-up instead?

2022-01-25 21:11 UTC, anthonysim commented on _sass/components/_project-filter.scss
> +@media #{$bp-ipadair-up} {
@lopezpedres @JessicaLucindaCheng, sounds good, changed `$bp-ipadair-up` to `$bp-desktop-up`!

2022-01-25 22:53 UTC, JessicaLucindaCheng commented
- Availability; 6 hours
- Re-review ETA: Thursday, January 27, 2022

2022-01-28 01:26 UTC, JessicaLucindaCheng commented
@anthonysim Sorry, I don't have time to review it today. So, I will be delaying my review by one day.
- Availability: 6 hours
- ETA: Friday, January 28, 2022

2022-01-29 04:26 UTC, JessicaLucindaCheng requested changes
@anthonysim The work you did to make the menus work for desktop, tablet, and mobile look fantastic. Thank you for all your hardwork!

However, I have a few more requested changes:
1) We use PR descriptions/posts to look back at the codebase commit history and see when and why changes were made. With that in mind, could you clarify the actions you took in https://github.com/hackforla/website/pull/2672#issue-1096819720? Also, can you just have one final picture instead of two after pictures? Also, I noticed you used `em` for the SCSS property `left` instead of `px` you may want to include info for your reasoning for that. Also, you may want to include your reasoning for choosing a shorter height than 493px that was recommended for the desktop dropdown in the Figma design. (I think they were good choices but I'm just wondering your reasons for doing so.) 

2) For the _sass/variables/_layout.scss, I like how you are thinking for making this easier to understand but it may be confusing to include those changes with this issue because the issue has nothing to with the layouts.scss page. If you are interested, you could write up a small issue to include comments to make that page easier to read for developers and we can discuss this further if you are interested in doing so.  For now, could you remove the comments you added to the layout.scss file so it was the way it was before?

If you have questions about or want to discuss any of the above, please let me know and we can find a time to meet. Again, thank you for all your hard work.

2022-01-29 07:20 UTC, anthonysim commented
@lopezpedres @JessicaLucindaCheng, hi guys, I'm just going to close out the PR at this point and place the issue associated with this PR back to the backlog.

2022-01-29 08:42 UTC, JessicaLucindaCheng commented
@anthonysim I apologize if my request for changes suggested your solution did not work because your solution does work. I appreciate your feedback to me in letting me know how you are feeling about it and I can understand that you are frustrated since it has been so long you've been working on this issue. However, I think we can use what you have in your original pull request and I can write another issue to fix whatever problems still exist. I just don't want your hard work to be wasted. Let me know if you are okay with me reopening your pr and merging what you have.

2022-01-29 17:52 UTC, JessicaLucindaCheng approved these changes
Merging pr as is and will be fixing it in a different branch.

2022-01-29 17:53 UTC, merged

2022-02-02 00:40 UTC, JessicaLucindaCheng commented
**Notes from merger**
- Desktop version C and the mobile version were implemented by Anthony Sim.
<details>
  <summary>Images of the implemented Version C and the mobile version</summary>
  
 </details>

Differences I noticed from the Figma design
- For the desktop version, I noticed em for the SCSS property left instead of using px for centering the tech dropdown.
- Also, for the desktop version,  may want to include your reasoning for choosing a shorter height than 493px that was recommended for the desktop dropdown in the Figma design. (I think they were good choices but I'm just wondering your reasons for doing so.)