Fix so jQuery is Alphabetized correctly in technologies drop down
hackforla/website pull request #2682
Opened 2022-01-10 01:07 UTC by sydneywalcoff

Fixes #2629

### What changes did you make and why did you make them ?
  - created a lowercase sorted technologies and languages list to get the correct position of jQuery (I guess the array prototype sort method is based on the first capital letter it finds? so jQuery was sorted as 'Q')
  - removed incorrectly placed jQuery using splice
  - spliced 'jQuery' into the correct place in the original filterValues array

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

<img width="1440" alt="Screen Shot 2022-01-09 at 5 03 38 PM" src="https://user-images.githubusercontent.com/75542938/148708518-72697884-1cf8-49fb-b646-072b06d173a6.png">

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
<img width="1440" alt="Screen Shot 2022-01-09 at 5 00 29 PM" src="https://user-images.githubusercontent.com/75542938/148708458-967a6e56-f24a-4843-995f-cf62ef3d2ffe.png">

</details>

2022-01-10 16:42 UTC, sydneywalcoff commented
I noticed that a branch I reviewed made it into this somehow? How should I fix?

2022-01-11 19:45 UTC, Aveline-art commented on assets/js/current-projects.js
> +                lowercaseValues.sort()
@sydneywalcoff I'm unsure if you have tried it yet, but `sort()` takes an optional [comparison function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#description) as an argument to customize sort order.  If it works, it should future-proof further additions to the `filterValue` object, and prevent this from happening again in the long run.

2022-01-11 20:52 UTC, sydneywalcoff commented on assets/js/current-projects.js
> +                lowercaseValues.sort()
@Aveline-art Thanks! I didn't even think to adventure down that rabbit hole, but that's a *much* cleaner solution.

2022-01-13 02:53 UTC, SAUMILDHANKAR commented
Review ETA: 1/14/22
Availability: Thursday 6-9 pm

2022-01-13 09:53 UTC, SAUMILDHANKAR requested changes
Great work on sorting jQuery in technology dropdown, however we need to remove the commit with changes to the wins page.

2022-01-13 09:53 UTC, SAUMILDHANKAR commented on _sass/components/_wins-page.scss
> +            bottom: 0px;
Hi @sydneywalcoff, thanks for working on this issue. The changes made in _wins-page.scss file shouldn't be part of this PR. Please remove this commit.

2022-01-13 18:29 UTC, lopezpedres reviewed
@sydneywalcoff ! LGTM. I'll just wait until the changes request from @SAUMILDHANKAR are done.  Great job!

2022-01-14 16:52 UTC, sydneywalcoff commented on _sass/components/_wins-page.scss
> +            bottom: 0px;
@SAUMILDHANKAR what would be the easiest way to do this? Revert? Rebase?

2022-01-19 00:30 UTC, Aveline-art commented
@sydneywalcoff Please resolve [merge conflicts ](https://github.com/hackforla/website/pull/2682/conflicts)that had resulted from your force push

2022-01-20 07:37 UTC, SAUMILDHANKAR requested changes

2022-01-20 07:37 UTC, SAUMILDHANKAR commented on assets/js/current-projects.js
> +                filterTitle = "program areas"
@sydneywalcoff Good job in removing the unwanted commit as suggested earlier. 
In line 37 of your code, filterTitle shouldn't be set to "program areas" as it has already been done above.

2022-01-20 07:37 UTC, SAUMILDHANKAR commented on assets/js/current-projects.js
>                  filterTitle = 'languages / technologies'
this else if looks like a repeat of line 27, 28

2022-01-20 19:28 UTC, sydneywalcoff commented
@SAUMILDHANKAR git is a ~lot~ of fun haha. Should be good now

2022-01-23 07:04 UTC, SAUMILDHANKAR approved these changes

2022-01-23 07:06 UTC, SAUMILDHANKAR commented
@sydneywalcoff Thanks for working on this issue and making all the changes. Looks good in my environment.

2022-01-23 07:06 UTC, merged