Change Open Community Survey's program area from 'Vote / Represent…
hackforla/website pull request #2700
Opened 2022-01-19 03:45 UTC by tamara-snyder

…ation' to 'Citizen Engagement'

Fixes #2631

### What changes did you make and why did you make them ?

  - Revised program area information for the Open Community Survey project so that it would show up under "citizen engagement" when filtered on the site's "Projects" page
  - In open-community-survey.md, changed program-area from "Vote / Representation" to "Citizen Engagement"

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

![image](https://user-images.githubusercontent.com/57715733/150059826-89ea81cf-f3b8-45a3-bb34-d74623d3994e.png)

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
![image](https://user-images.githubusercontent.com/57715733/150059850-b58ade37-7270-465f-8d3e-95a1cd051358.png)

</details>

2022-01-21 03:39 UTC, lindseyindev approved these changes
Looks good to me! Congrats on your first pull request!!

2022-01-24 20:56 UTC, JessicaLucindaCheng commented
- Availability: 6 hours
- Review ETA: Monday, January 24, 2022

2022-01-24 22:11 UTC, JessicaLucindaCheng requested changes
@tamara-snyder 
Please add your pull request to the project board. Otherwise, your changes look good to me.
<img width="297" alt="Add-to-project-board" src="https://user-images.githubusercontent.com/31293603/150872571-d6b0a9a4-43fd-4357-a875-082f680e29c1.png">

2022-01-27 23:45 UTC, JessicaLucindaCheng approved these changes
@tamara-snyder Looks good to me!

2022-01-27 23:45 UTC, merged

2022-01-28 15:37 UTC, tamara-snyder commented
@JessicaLucindaCheng 
Is it supposed to go in the "Done" column? Thank you!