first attempt at issue 2604
hackforla/website pull request #2710
Opened 2022-01-21 03:34 UTC by Georgema20

Fixes #2604 

### What changes did you make and why did you make them ?

 I found the h1 tag that is attributed to the "Current Project Team" header in the project template, used liquid if statement to check if the status of the project is completed, and made sure to use this methodology: if the project status is completed, h1 tag should say "Project Team", else h1 tag should say "Current Project Team". 

I did this because completed projects should have "Project Team" instead of "Current Project Team" as their title. 

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

![screencapture-hackforla-org-projects-hellogov-2022-01-20-19_13_09](https://user-images.githubusercontent.com/83432699/150460888-63360451-34ab-4557-8ebf-a841971ace4b.png)
![screencapture-hackforla-org-projects-ems-triage-tracker-2022-01-20-19_11_14](https://user-images.githubusercontent.com/83432699/150460895-81112d84-5b47-4ca8-b4f1-d2a05f809736.png)
![screencapture-hackforla-org-projects-heart-2022-01-20-19_12_51](https://user-images.githubusercontent.com/83432699/150460904-c5ff9e5a-2e14-4dae-810f-e11541bc5edd.png)
![screencapture-hackforla-org-projects-undebate-2022-01-20-19_14_17](https://user-images.githubusercontent.com/83432699/150460909-d01ae1c7-3b9e-49ed-968d-09c170c87d6d.png)
![screencapture-hackforla-org-projects-metro-ontime-2022-01-20-19_14_00](https://user-images.githubusercontent.com/83432699/150460911-a1108cbd-884f-4677-bf46-6c9de5fb458c.png)
![screencapture-hackforla-org-projects-work-for-la-2022-01-20-19_14_37](https://user-images.githubusercontent.com/83432699/150460914-900b2200-bb47-46de-b5cd-a9f61ca771a3.png)
![screencapture-hackforla-org-projects-public-tree-map-2022-01-20-19_13_24](https://user-images.githubusercontent.com/83432699/150460917-74d1abbe-8e04-41ce-8ea5-856e3bd9c06a.png)

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
![screencapture-localhost-4000-projects-work-for-la-2022-01-20-19_28_18](https://user-images.githubusercontent.com/83432699/150460949-3a8c5bff-b23e-4bec-9d2a-e5e30150f8eb.png)
![screencapture-localhost-4000-projects-public-tree-map-2022-01-20-19_27_18](https://user-images.githubusercontent.com/83432699/150460956-e75a3e4b-5675-4a3b-bff2-f7941b7301f9.png)
![screencapture-localhost-4000-projects-hellogov-2022-01-20-19_27_00](https://user-images.githubusercontent.com/83432699/150460970-52e78a47-77e9-4d3d-8322-f42a6d212090.png)
![screencapture-localhost-4000-projects-ems-triage-tracker-2022-01-20-19_26_11](https://user-images.githubusercontent.com/83432699/150460971-ec4cd623-1c1e-44a7-9c96-4e7b6f877078.png)
![screencapture-localhost-4000-projects-undebate-2022-01-20-19_28_03](https://user-images.githubusercontent.com/83432699/150460975-89adf6a1-12f4-4268-ba8f-d7726b6328ca.png)
![screencapture-localhost-4000-projects-metro-ontime-2022-01-20-19_27_43](https://user-images.githubusercontent.com/83432699/150460977-3fc4b42f-403b-4bd8-ad41-7c6916c0701a.png)
![screencapture-localhost-4000-projects-heart-2022-01-20-19_26_38](https://user-images.githubusercontent.com/83432699/150460980-f48f31a4-8455-4edc-93fa-15615512be20.png)

</details>

2022-01-23 01:15 UTC, JessicaLucindaCheng commented
Removed `Ready for Milestone` label as the issue was already in the Prioritized Backlog and had a milestone.

2022-01-24 21:02 UTC, JessicaLucindaCheng commented
- Availability: 6 hours
- Review ETA: Tuesday, January 24, 2022

2022-01-25 21:50 UTC, JessicaLucindaCheng requested changes
@Georgema20 Thanks for working on this issue! Please make the changes as suggested in my inline comments. Also, please do the following:

1. Please add your pull request to the project board.
<img width="297" alt="Add-to-project-board" src="https://user-images.githubusercontent.com/31293603/150872571-d6b0a9a4-43fd-4357-a875-082f680e29c1.png">

2. Please edit the title of your pr so it has a descriptive title of what you have done. For more info, see this: https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#i-complete-pull-request-1-update-pull-request-title

2022-01-25 21:50 UTC, JessicaLucindaCheng commented on _layouts/project.html
> +             <h2 class='project-page-card-title title6'> Project Team</h2>
1. Right before `<h2`, please remove 1 space.
2. For`> Project Team`, there is an extra space between `>` and `Project Team`. Please remove that space.

2022-01-25 21:50 UTC, JessicaLucindaCheng commented on _layouts/project.html
> +              <h2 class='project-page-card-title title6'>Current Project Team</h2>
Right before `<h2`, please remove 2 spaces.

2022-01-25 21:55 UTC, JessicaLucindaCheng commented on _layouts/project.html
> +        {%  endif %}
Currently, there is an extra space in `{%  endif %}`. Please remove 1 space between `{%' and `endif %}`

2022-01-26 03:46 UTC, anthonysim commented
ETA: 1/29/22
Availability: 3 hrs, Saturday 12-3 PM

2022-01-26 04:11 UTC, anthonysim commented
@Georgema20, LGTM! Please make the changes that @JessicaLucindaCheng suggested and its good to go!

2022-01-26 19:59 UTC, Georgema20 commented
Availability: 1 hour
ETA: midnight 1/26

2022-01-26 20:49 UTC, Georgema20 commented
@JessicaLucindaCheng hey I think I did it all. Let me know if you want to see anything different.

2022-01-26 22:46 UTC, JessicaLucindaCheng commented
- Availability: 6 hours
- Review ETA: Thu, Jan 27,2022

2022-01-28 01:27 UTC, JessicaLucindaCheng commented
@Georgema20 Sorry, I don't have time to review it today. So, I will be delaying my review by one day.
- Availability: 6 hours
- ETA: Friday, January 28, 2022

2022-01-28 22:22 UTC, JessicaLucindaCheng approved these changes
@Georgema20 Your changes look good to me!

2022-01-29 07:17 UTC, anthonysim approved these changes

2022-01-29 09:01 UTC, merged