Tooltip bug fix
hackforla/website pull request #2713
Opened 2022-01-23 20:22 UTC by R-Tomas-Gonzalez

Fixes #2408 

### What changes did you make and why did you make them ?
  - Instead of making a global change of '!important' on the wins-card, I went ahead and added in the '.project-card' class without the overflow style. This makes the '.wins-card' overflow style take precedence, without creating a global '!important' rule.
  - This also makes it so that this change does not effect any other page stylings using the ".project-card" or ".wins-page" attributes

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>
<img width="637" alt="Screen Shot 2022-01-23 at 2 20 13 PM" src="https://user-images.githubusercontent.com/63771558/150696613-452106b8-4f55-4096-9921-7a434b52349d.png">
</details>

<details>
<summary>Visuals after changes are applied</summary>
<img width="637" alt="Screen Shot 2022-01-23 at 2 20 35 PM" src="https://user-images.githubusercontent.com/63771558/150696633-8b12e746-243d-436b-ab81-26c6dcab8493.png">
</details>

2022-01-26 03:27 UTC, JessicaLucindaCheng commented
- Availability: 6 hours
- Review ETA: Thursday, January 27, 2022

2022-01-26 03:27 UTC, SAUMILDHANKAR commented
ETA: 1/27/22
Availability: 3 hrs, Thursday 3-6 PM

2022-01-26 03:46 UTC, anthonysim commented
ETA: 1/29/22
Availability: 3 hrs, Saturday 12-3 PM

2022-01-26 04:00 UTC, anthonysim submitted a review, later dismissed
@R-Tomas-Gonzalez, LGTM! I see the change allows the tool tip overflow from being hidden. Good job!

2022-01-28 22:53 UTC, SAUMILDHANKAR commented
Revised review ETA: 1/29/22
Availability: 3 hrs, Saturday 4-7 PM

2022-01-29 08:46 UTC, SAUMILDHANKAR commented on _sass/components/_projects-page.scss
> -    overflow: hidden;
@R-Tomas-Gonzalez Great job in making the changes. Tooltip looks good in my environment. Just curious if overflow should be removed from _projects-page.scss?

2022-01-31 21:15 UTC, R-Tomas-Gonzalez commented on _sass/components/_projects-page.scss
> -    overflow: hidden;
Hey Saumil! You're totally right. I will put that back. Whoops!

2022-01-31 21:30 UTC, R-Tomas-Gonzalez commented on _sass/components/_projects-page.scss
> -    overflow: hidden;
Went ahead and added the "!important" attribute to overflow on the .wins-card class in the the wins-page.scss file. I feel fine with this since we will not be using a new wins-card most likely ever except for on this page. And if we do, we wouldn't want that attribute to be hidden anyway.

2022-02-02 06:44 UTC, JessicaLucindaCheng commented
- Availability: 3 hours
- Review ETA: Thu, Feb 3, 2022

2022-02-04 02:21 UTC, JessicaLucindaCheng commented
Sorry, going to delay reviewing this by one day.
- Availability: 3 hours
- Review ETA: Fri, Feb 4, 2022

2022-02-07 00:40 UTC, JessicaLucindaCheng requested changes
@R-Tomas-Gonzalez Sorry for the delay in reviewing your pr. Since there are concerns about using !important and not duplicating .project-card scss class, can `overflow: visible` be added to `.project-card.wins-card` but outside of the media query? It produces the same outcome. Here is a link to `.project-card.wins-card`: https://github.com/hackforla/website/blob/d8400dcaf4af7bfeb3af856f259d71038c617df1/_sass/components/_wins-page.scss#L37-L41.

2022-02-07 00:50 UTC, R-Tomas-Gonzalez commented
> @R-Tomas-Gonzalez Sorry for the delay in reviewing your pr. Since there are concerns about using !important and not duplicating .project-card scss class, can `overflow: visible` be added to `.project-card.wins-card` but outside of the media query? It produces the same outcome. Here is a link to `.project-card.wins-card`:
> 
> https://github.com/hackforla/website/blob/d8400dcaf4af7bfeb3af856f259d71038c617df1/_sass/components/_wins-page.scss#L37-L41
> 
> .

Great catch! Thank you.

2022-02-07 01:02 UTC, JessicaLucindaCheng approved these changes
@R-Tomas-Gonzalez Thanks for making the changes! It looks good to me now.

2022-02-07 01:04 UTC, merged