Applied Title classes to heading elements on donate page
hackforla/website pull request #2723
Opened 2022-01-28 14:39 UTC by pattshreds

Fixes #2084

### What changes did you make and why did you make them ?

  - Applied Title classes to heading elements so that they don't relay on Hx styling rules.
  - Repositioned the first H1 element on the page to align with the P below it according to the donate page Figma.
  - Defined the used Title classes in the _donate.scss file.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

![Screen Shot 2022-01-28 at 7 33 00 AM](https://user-images.githubusercontent.com/74014488/151565511-66b0c4dc-0c3e-48ab-8e68-bea67d5329b0.png)

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
![Screen Shot 2022-01-28 at 7 33 07 AM](https://user-images.githubusercontent.com/74014488/151565597-56439da1-539d-48f5-8599-2e4daceb3d1a.png)

</details>

2022-01-30 19:44 UTC, JessicaLucindaCheng commented
- Availability: 3 hours
- ETA: Tue, Jan 30, 2022

2022-02-02 06:42 UTC, JessicaLucindaCheng commented
Sorry, I'm going to delay my review by one day. My new ETA and availability are as follows:
- Availability: 3 hours
- Review ETA: Wed, Feb 2, 2022

2022-02-02 22:45 UTC, JessicaLucindaCheng requested changes
Good job noticing the header didn't align with the paragraph. I have some inline request for changes. Also, please do the following:

1. Please add your pull request to the project board.
<img width="297" alt="Add-to-project-board" src="https://user-images.githubusercontent.com/31293603/150872571-d6b0a9a4-43fd-4357-a875-082f680e29c1.png">

2. I noticed your changes impact more than just the portion in your screenshot. Please screenshot the whole page by using the GoFullPage Chrome extension: https://chrome.google.com/webstore/detail/gofullpage-full-page-scre/fdpohaocaechififmbbbbbknoalclacl?hl=en

3. You don't need to define the title classes in _sass/components/_donate.scss because they already exist in our codebase. So, please remove the title classes you added in that file.

4. When applying the title classes to the HTML, the class name should be lowercase. For example, `<h1 class="title1">`.

2022-02-02 22:45 UTC, JessicaLucindaCheng commented on pages/donate.html
> +      <h1 class="Title4">Help Us Keep The Lights On</h1>
This should be a `h2` header.

2022-02-02 22:45 UTC, JessicaLucindaCheng commented on pages/donate.html
> +        <h2 class="Title7">Running Hack for LA costs money</h2>
This should be a `h3` header.

2022-02-02 22:45 UTC, JessicaLucindaCheng commented on pages/donate.html
> +        <h2 class="Title7">How to help us continue to do impactful work</h2>
This should be a `h3` header.

2022-02-02 23:06 UTC, JessicaLucindaCheng commented
@pattshreds Also, please do the following:
i. Please update your forked gh-pages so that it is in sync with the hackforla/website gh-pages. Here are instructions for [how to update your forked gh-pages](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#27e-working-on-an-issue-5-incorporating-changes-from-upstream).
ii. Then merge your gh-pages into your topic branch locally.
iii. Then push the merged changes in your topic branch locally to your remote topic branch in your forked repo.

2022-02-10 22:22 UTC, JessicaLucindaCheng commented
@pattshreds When you are ready for me to re-review your pull request, please click the following in the Reviewers section on the right:
<img width="243" alt="image" src="https://user-images.githubusercontent.com/31293603/153506185-1cab4d94-853f-49cd-8275-ab0573465b5e.png">

2022-02-19 00:11 UTC, JessicaLucindaCheng requested changes
@pattshreds I wasn't sure if you were ready for me to review your pr again but I went ahead and did it anyway. (Sorry if it wasn't ready and you were still working on it.) In addition to my in-line comments for changes, please do the following:

- [ ] Since changes to the _guide-pages/2FA.html is not part of your pr, to try to fix that, please update your forked gh-pages so that it is in sync with the hackforla/website gh-pages and then update your topic branch. Here are instructions for [how to update your forked gh-pages](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#27e-working-on-an-issue-5-incorporating-changes-from-upstream) and [the how to update your topic branch](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#i-incorporating-changes-into-your-topic-branch).

2022-02-19 00:11 UTC, JessicaLucindaCheng commented on pages/donate.html
> +      <h1 class="title4">Help Us Keep The Lights On</h1>
This should be an `h2` header so that they reflect the correct hierarchy of the page for screen readers (since the styling no longer relies on the h tags).

2022-02-19 00:11 UTC, JessicaLucindaCheng commented on pages/donate.html
> +        <h2 class="title7">Running Hack for LA costs money</h2>
This should be an `h3` header so that they reflect the correct hierarchy of the page for screen readers (since the styling no longer relies on the h tags).

2022-02-19 00:11 UTC, JessicaLucindaCheng commented on pages/donate.html
> +        <h2 class="title7">How to help us continue to do impactful work</h2>
This should be an `h3` header so that they reflect the correct hierarchy of the page for screen readers (since the styling no longer relies on the h tags).

2022-02-19 00:11 UTC, JessicaLucindaCheng commented on pages/donate.html
> +          <h2 class="title6">Make a donation to Hack for LA</h2>
This should be an `h3` header so that they reflect the correct hierarchy of the page for screen readers (since the styling no longer relies on the h tags).

2022-02-19 00:11 UTC, JessicaLucindaCheng commented on _sass/components/_donate.scss
> +            font-size: 1rem;
Please remove `font-size: 1rem;` because the font size should be determined by the title classes.

2022-02-22 23:54 UTC, JessicaLucindaCheng commented
- Availability: 2 hours
- Review ETA: Wed, Feb 23, 2022

2022-02-23 22:08 UTC, JessicaLucindaCheng requested changes
@pattshreds Good job changing the headers tags to the correct hierarchy and merging updates from gh-pages.

- [ ] When I compared the Donate page with the changes you made to the Donate page on the live website, the headers look different in terms of font size. The Donate page headers should still look the same as the ones on the live website. Since the font-size for the headers now should only depend on the title classes, the font-sizes for any headers should be removed from `_sass/components/_donate.scss`. (Note: In that SCSS file, there are font-sizes for other elements besides headers.)
- [ ] Check your changes locally using Docker and make sure everything still looks the same as [Donate page](https://www.hackforla.org/donate/) on the live website
- [ ] When you are ready for me to re-review your pull request, please click the following in the Reviewers section on the right:
  <img width="243" alt="image" src="https://user-images.githubusercontent.com/31293603/153506185-1cab4d94-853f-49cd-8275-ab0573465b5e.png">

2022-02-28 09:07 UTC, SAUMILDHANKAR commented
@pattshreds Hope you are doing well. Just wanted to share one of the decisions made during our team meeting. We are now requesting all website team members to attend at least one meeting in a week (Tuesday, Thursday or Sunday) as we strive to replicate a professional working environment within our team amongst other things. Therefore, request you to let us know which of the weekly meetings would be suitable for you based on availability. We have decided to make an exception for this requirement only on a case-by-case basis. I will leave a message for you on slack as well. Thank you.

2022-03-09 03:13 UTC, Carlos-A-P commented
@pattshreds Great job adding the classes and changing the header tags to have a proper header structure. As Jessica mentioned, all you need to do is remove any header styling in the _donate.scss file to resolve the issue

2022-03-11 22:24 UTC, SAUMILDHANKAR commented
@pattshreds Just wanted to follow up regarding the progress on this PR. Please let us know if you have any questions, need help or any changes in your availability. I will reach out to you on slack as well. Look forward to hearing back. Thanks.

2022-03-17 21:38 UTC, SAUMILDHANKAR commented
Heard back from Patrick on slack. Would be updating progress this week.

2022-03-24 01:30 UTC, pattshreds commented
Progress: Title classes are assigned in HTML.
Blockers: The title 4 element and the first title7 element don't seem to be the correct sizes. Need to figure out where to define their sizes.
Availability: This week 6pm - 8pm
ETA: Thursday 3/24/22

2022-03-24 04:56 UTC, JessicaLucindaCheng commented
@pattshreds You shouldn't need to define the font sizes because they are already defined by the title classes you applied and the headers should only depend on the font styling defined in the title classes. I think what is happening is the font sizes in the other classes used by the elements are overriding the font sizes in the title classes you applied.

Using developer tools, inspect the headers and see what classes are overriding the font sizes in the title classes you applied; then, remove the font size styling in those classes, which should be in  `_sass/components/_donate.scss`. This should fix the font size issues you are seeing.

2022-03-25 23:32 UTC, JessicaLucindaCheng commented
- Availability: 3 hours
- Review ETA: Saturday, March 26, 2022

2022-03-27 15:22 UTC, JessicaLucindaCheng requested changes
@pattshreds Thanks for working on this issue! Please make the changes as requested in my in-line comments. Also, please do the following as well:
- [ ] Please change all the title classes to be lowercase (title1, title2, title3, etc). For example, `<h1 class="title1">`.
- [ ] In _donate.scss, please remove any font-size styling for h1 and h2 headers because the font-size for all the headers should be determined by the title classes that were applied.
- [ ] Please update your forked gh-pages so that it is in sync with the hackforla/website gh-pages and then update your topic branch. Here are instructions for [how to update your forked gh-pages](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#27e-working-on-an-issue-5-incorporating-changes-from-upstream) and [how to update your topic branch](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#i-incorporating-changes-into-your-topic-branch).
- [ ] When you are ready for me to re-review your pull request, please click the following in the Reviewers section on the top right:
<img width="243" alt="image" src="https://user-images.githubusercontent.com/31293603/153506185-1cab4d94-853f-49cd-8275-ab0573465b5e.png">

2022-03-27 15:22 UTC, JessicaLucindaCheng commented on pages/donate.html
> +      <h1 class="Title4">Help Us Keep The Lights On</h1>
This should be a `h2` header in order to follow WCAG requirements. (Link for more info: https://www.w3.org/WAI/tutorials/page-structure/headings/)

2022-03-27 15:22 UTC, JessicaLucindaCheng commented on pages/donate.html
> +        <h2 class="Title7">Running Hack for LA costs money</h2>
This should be a `h3` header in order to follow WCAG requirements. (Link for more info: https://www.w3.org/WAI/tutorials/page-structure/headings/)

2022-03-27 15:22 UTC, JessicaLucindaCheng commented on _sass/components/_donate.scss
>                      }
From 210-211, remove
```
h2 {
}
```
since there is nothing defined between the curly braces in this section and is unneeded code.

2022-03-27 15:22 UTC, JessicaLucindaCheng commented on _sass/components/_donate.scss
>                  font-size: 48px;
Can the font-size here also be removed since the font-size for all the headers should be determined by the title classes?

2022-03-31 02:48 UTC, kathrynsilvaconway commented
Availability: 5-6pm Sat 4/02
ETA: 6PM Saturday, 4/02/2022

2022-03-31 08:09 UTC, JessicaLucindaCheng commented
Availability: 1 hour
Review ETA: Thu, Mar 31, 2022

2022-03-31 16:14 UTC, Carlos-A-P commented
Availability: 2 hrs EOD
ETA: Thu, Mar 31, 2022

2022-04-01 03:45 UTC, Carlos-A-P reviewed
Hey @pattshreds, I see you've made some more changes and wanted to make a suggestion

2022-04-01 03:45 UTC, Carlos-A-P commented on _sass/components/_donate.scss
>          h1 {
I noticed that some elements relied on their header styling in scss such as margins and padding, you can maybe replace the h1 and h2 selectors with the .title# classes depending on which element was being styled

2022-04-03 02:40 UTC, kathrynsilvaconway requested changes
@pattshreds Nice job making all of the changes to the header tags and updating the title classes on this page. Based on the image in the original issue, I can see that you have made the updates correctly. I also see that youu have  made the changes to the SCSS that @JessicaLucindaCheng requested.

The only change I am not able to see is where you aligned the "Donate To Hack For LA" header with the paragraph below. I can see there have been several revisions to this PR, was this change reverted? Just wanted clarification on that, although it was not part of the original issue. Otherwise, everything looks good.

2022-04-04 01:27 UTC, JessicaLucindaCheng commented on _sass/components/_donate.scss
>              }
Can this media query and its curly braces be removed since there is no code between the curly braces?

2022-04-05 14:26 UTC, pattshreds commented
> @pattshreds Nice job making all of the changes to the header tags and updating the title classes on this page. Based on the image in the original issue, I can see that you have made the updates correctly. I also see that youu have made the changes to the SCSS that @JessicaLucindaCheng requested.
> 
> The only change I am not able to see is where you aligned the "Donate To Hack For LA" header with the paragraph below. I can see there have been several revisions to this PR, was this change reverted? Just wanted clarification on that, although it was not part of the original issue. Otherwise, everything looks good.

2022-04-05 14:28 UTC, pattshreds commented
@kathrynsilvaconway Yes, that change was reverted! I had that styling applied to the "Donate to Hack for LA" h1 in the SCSS file but was told to remove all header styling from that file so now it's back to being indented farther than the paragraph below it.

2022-04-05 17:39 UTC, kathrynsilvaconway approved these changes, later dismissed
@pattshreds Ok, just checking on the alignment thing. Everything looks good. Nice job.

2022-04-06 00:19 UTC, JessicaLucindaCheng requested changes
@pattshreds Thanks for making changes to the code. In addition to the in-line requests for change, please do the following:
- [x] When I use developer tools to look at the Donate page, the alignment of the text is off in mobile view compared to the current site. You can try doing what @Carlos-A-P suggested to see if that fixes the problem.

  <details>
    <summary>Current Donate Page in Mobile View</summary>
    
    ![donate-mobile-current](https://user-images.githubusercontent.com/31293603/161468039-a4b6248b-9439-40b8-bc43-3bc970ce8f26.png)

  </details>
  
  <details>
    <summary>Your Donate Page in Mobile View</summary>
    
    ![donate-mobile-alignment-problem](https://user-images.githubusercontent.com/31293603/161468058-50708515-5fde-4c4b-bbf0-b4331d027314.png)
  
  </details>
  
  - [x] The header "Help Us Keep the Lights On" should be centered like the current site in mobile view.
  - [x] The headers "Running Hack for LA costs money" and "How to help use continue to do impactful work" should be left aligned like the current site in mobile view.
- [x] Please update your forked gh-pages so that it is in sync with the hackforla/website gh-pages and then update your topic branch. Here are instructions for [how to update your forked gh-pages](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#27e-working-on-an-issue-5-incorporating-changes-from-upstream) and [how to update your topic branch](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#i-incorporating-changes-into-your-topic-branch).
  - [x] You will encounter a merge conflict for `donate.html` and will need to resolve that carefully.
    - [x] To help with that I recommend taking a look at the current code for [pages/donate.html](https://github.com/hackforla/website/blob/gh-pages/pages/donate.html) and the [changes you made to the code](https://github.com/hackforla/website/pull/2723/files) to figure out what parts of the code to keep.
    - [x] If you are using VS Code, you will see something like the following:
      <img width="970" alt="merge-conflict" src="https://user-images.githubusercontent.com/31293603/161871395-7a0db8d5-a9d5-426d-b802-aec45f9c72a9.png">

      - [x] 1) You'll see a message in your terminal saying you have a merge conflict.
      - [x] 2) To find the files with merge conflicts, click on directories with a dark pink/red dot and writing.
      - [x] 3) Then, open any files with dark pink/red writing and `!`.
      - [x] 4) You'll see green and blue highlights in the file. Scroll/navigate to those lines of code.
      - [x] 5) You'll see lines of code highlighted in green and blue - something like the following:
            ```
            <<<<<<< HEAD
            green_highlighted_lines_of_code            
            =======
            blue_highlighted_lines_of_code 
            >>>>>>> new_branch_to_merge_later
            ```
            - [ ] You'll need to figure out what code to keep. For your merge conflict, the lines of code to keep will be a combination of the changes you made and what is currently in [pages/donate.html](https://github.com/hackforla/website/blob/gh-pages/pages/donate.html). So you need to do some editing with the code.
            - [ ] Then, remove the lines with 
            `<<<<<<< HEAD`          
            `=======`
            `>>>>>>> new_branch_to_merge_later`
            Note: Do not use VSCode's default choices ("Accept Current Change", "Accept Incoming Change", and "Accept Both Changes") for resolving your merge conflicts for this pr because your merge conflicts don't fit neatly into the choices provided and will need a combination of the code highlighted in green and blue.
            - [ ] Then, save your changes.
    - [x] After saving the changes, do `git add <file>`, where `<file>` should be replaced with the name of the file you fixed merge conflicts in. Do a git add for each page you had a merge conflict in.
    - [ ] Do a `git commit` and a window will pop up asking you to edit the commit message for merging. You can just close the window and use the default message for merging, which is usually something along the lines of "Merging branch `NAME_OF_BRANCH` into NAME_OF_ANOTHER_BRANCH".
    - [ ] Then, do a `git push` to push your changes to the remote branch on your forked repo.
- [ ] When you are ready for me to re-review your pull request, please click the following in the Reviewers section on the top right:
  <img width="260" alt="request re-review" src="https://user-images.githubusercontent.com/31293603/161872094-7a7495cc-d9e0-42dd-989f-44a959ac2af6.png">

2022-04-06 00:19 UTC, JessicaLucindaCheng commented on _sass/components/_donate.scss
>              }
Can this media query and its curly braces be removed since there is no code between the curly braces?

2022-04-06 00:19 UTC, JessicaLucindaCheng commented on pages/donate.html
> +Title: Donate
Title should be lowercase.

2022-04-06 00:19 UTC, JessicaLucindaCheng commented on _sass/components/_donate.scss
> +                // margin-left: -30px;
I think this commented out code was from when you were trying to fix the alignment in the Donate to Hack for LA header. If you are no longer wanting to fix the alignment issue, please just delete this comment. We can create another issue to address alignment problems for the header.

2022-04-17 16:54 UTC, JessicaLucindaCheng commented
@pattshreds Please give a progress report in a comment in this pr. See what you need to include in your progress report and more information in [section 2.5 Reporting progress on your issue in CONTRIBUTING.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#25-reporting-progress-on-your-issue)

Also, did you have any questions?

2022-04-19 23:14 UTC, JessicaLucindaCheng commented
@pattshreds Please provide an update as I specified above: https://github.com/hackforla/website/pull/2723#issuecomment-1100914812. If we don't hear back from you by Wednesday, April 27, we will close this pr and unassign you from your issue.

I will email you and Slack message about this as well.

2022-04-20 14:27 UTC, pattshreds commented
Progress: Working on merge conflict
Availability: 4.20.22 hour or two after 8pm, 4.21.22 - 4.24.22 after 6pm.
ETA: Sunday 4.24.22

2022-04-23 10:41 UTC, JessicaLucindaCheng commented
- Availability: 3 hours
- Review ETA: Wed, April 27, 2022

2022-05-01 06:27 UTC, JessicaLucindaCheng requested changes
@pattshreds Thanks for updating your topic branch with the lastest updates. In addition to my in-line request for changes, please do the following:
- [x] Please update your [first post](https://github.com/hackforla/website/pull/2723#issue-1117480822) as follows:
  - [x] Update what you did by removing the following (since you are no longer doing the following):
    - [ ] "Repositioned the first H1 element on the page to align with the P below it according to the donate page Figma."
    - [ ] "Defined the used Title classes in the _donate.scss file."

  - [ ] Update the screenshots for the visuals for the before and after. Since you are changing the headers for the whole Donate page, you may want to use [GoFullPage - Full Page Screen Capture Chrome Extension](https://chrome.google.com/webstore/detail/gofullpage-full-page-scre/fdpohaocaechififmbbbbbknoalclacl?hl=en) in order to screenshot the whole page in desktop and mobile views.
- [ ] When you are ready for me to re-review your pull request, please click the following in the Reviewers section on the top right:
  <img width="260" alt="request re-review" src="https://user-images.githubusercontent.com/31293603/161872094-7a7495cc-d9e0-42dd-989f-44a959ac2af6.png">

2022-05-01 06:27 UTC, JessicaLucindaCheng commented on pages/donate.html
> +      <h1 class="title4">Help Us Keep The Lights On</h1>
On line 23, the header should be changed to a `h2` header because it is a subsection of the "Donate to Hack for LA" page

2022-05-01 06:27 UTC, JessicaLucindaCheng commented on pages/donate.html
> +      <img id="donate-donation-icon" class='donate-card-img' src="/assets/images/donate/help-us-icon.svg" alt="donate card image" />
Delete lines 25-26 because they are a duplicate of lines 23-24

2022-05-01 06:27 UTC, JessicaLucindaCheng commented on pages/donate.html
> +      <img id="donate-donation-icon" class='donate-card-img' src="/assets/images/donate/help-us-icon.svg" alt="donate card image" />
On line 24, the alt here should match the one on the live website, so change `alt="donate card image"` to `alt=""`

2022-05-01 06:27 UTC, JessicaLucindaCheng commented on pages/donate.html
> +        <h2 class="title7">Running Hack for LA costs money</h2>
On line 28, the header should be changed to an `h3` header because it is a subsection of "Help Us Keep the Lights On" section.

2022-05-01 06:27 UTC, JessicaLucindaCheng commented on pages/donate.html
> +        <h2 class="title7">How to help us continue to do impactful work</h2>
On line 39, the header should be changed to an `h3` header because it is a subsection of "Help Us Keep the Lights On" section.

2022-05-01 06:27 UTC, JessicaLucindaCheng commented on pages/donate.html
> +        <h3 class="title7">How to help us continue to do impactful work</h3>
Remove lines 36-37 because they are a duplicate of lines 38-39

2022-05-01 06:27 UTC, JessicaLucindaCheng commented on _sass/components/_donate.scss
>              font-size: 48px;
Lines 22-23 (the comment and the font-size) can be removed because title1 is defined correctly and is 3rem for desktop size screens, which equals 48px since the base font is 16px. Also, title1 class (and all the title classes) font-size is suppose to change as the screen size gets smaller. See the [Typography section in the Design System in Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3689%3A21144)

<details>
  <summary>Click here to see screenshot of title1 class in Design System in Figma</summary>
  <img width="519" alt="design-system-title-1" src="https://user-images.githubusercontent.com/31293603/165872371-3b695b78-304e-4813-bbc0-ef254537e6c9.png">
</details>

2022-05-18 14:47 UTC, Sparky-code commented
Avail: 1-2hrs
ETA: 5/18-19 EOD

2022-05-19 01:03 UTC, trishajjohnson commented
Availability: 2 hrs
ETA: EOD 5/19/22

2022-05-20 02:48 UTC, trishajjohnson commented
@SAUMILDHANKAR needing clarification, it appears this issue dates back quite a ways.  I'm assuming you just want me to review the most recent changes dating back to the last PR done by Katherine on April 5, or am I mistaken?

2022-05-20 05:20 UTC, Sparky-code requested changes, later dismissed
At first pass it looks like everything has been updated properly according to the comments made. I do see noted that the misalignment of the title1 header will be addressed as another issue. 

I may be mistaken and I know the images are addressed specifically but I don't see any visual changes made in this issue and am wondering if the images are necessary. 

I noticed that there are still some unresolved comments in the issue. I believe that they have all been addressed in your more recent commits but would ask that they be marked as 'resolved' before this issue is merged. You can find the relevant conversations at the bottom of the page:
![image](https://user-images.githubusercontent.com/95888938/169455706-9713344a-2d01-422a-b01a-73e2f4d89c77.png)

2022-05-20 06:04 UTC, trishajjohnson approved these changes
@pattshreds I took a look at your pull request and all the requested changes.  You effectively added the heading classes, the hierarchy of heading tags have been done properly and upon inspection, it appears in the window everything lines up with the figma design, except the already previously mentioned discrepancies: the h1 at the top in desktop view not being in line with the following paragraph. 

I noticed that you also resolved the issue with the h3 from line 26 being improperly indented in mobile view, and it is now in line with the figma design.  I wonder, though, not that this is part of your issue, but the h3 on line 26, as it is now, seems awkwardly jetted out significantly and might look better more in line with the following paragraph like the rest of the headings and paragraphs.  I also noticed in mobile view that the two paragraphs on lines 11 and 27 have different text-align styles and it might benefit from design continuity (one is centered, the other aligned to the left).

You updated the before/after images, per Jessica's request.  I, too, noticed they don't seem different at all and wonder if they are redundant, as Devin did.  I also saw that you updated heading styles in _sass/components/_donate.scss.  

Overall, great job and kudos to you for sticking with it.  Looks like this was a bit of winded issue.  Now, you're in the home stretch.  Like Devin mentioned, some conversations need to be resolved and then you should be able to merge and close this issue.

2022-05-25 02:43 UTC, JessicaLucindaCheng commented
Availability: 2 hours
ETA: Wed, May 25, 2022

2022-05-28 17:49 UTC, JessicaLucindaCheng approved these changes
@pattshreds Sorry for the delay in reviewing your pr as I was on vacation for over a week. You made all the requested changes and everything looks good to me now. Great job!

2022-05-28 18:00 UTC, JessicaLucindaCheng commented
@Sparky-code There actually is visual changes to the font sizes for some of the headers but the changes don't vary much so it may be hard to see by just looking at the webpage.

Also, I am going to go ahead and resolve the conversations since I did not expicitly ask Patrick to "Resolve Conversations" originally in any of my previous reviews and had been resolving them when I reviewed. However, going forward, if you think we should have pr creators Resolve Conversations (if they fixed the problem and there is no more need for conversation) as a standard practice in our team, we can discuss it further.

2022-05-28 18:02 UTC, merged

2022-05-29 22:25 UTC, pattshreds commented
@JessicaLucindaCheng Thanks Jessica, I usually do resolve the conversations, but for some reason 2 of the most recent requests didn't have the resolve button on them and I couldn't figure out why.