Blue Audit
hackforla/website pull request #2767
Opened 2022-02-12 07:18 UTC by lindseyindev

Fixes #2204 

### What changes did you make and why did you make them ?

  - Replaced hard-coded blue hex values in SCSS files with color variables so that changing the color variable value will change that color across the site.
  - Wrote about this in the issue but SVG fills have hardcoded hex values, I attempted several ways to move these fill values to variables and all of the syntax I attempted broke the SVG. I could not find an SVG in the codebase to reference that used variable colors over hex values and my research pointed me in the direction that our SVGs would have to be written using different properties to make the colors variable values but after spending multiple hours researching and attempting different syntax I could not implement this. 
  - Note for tech leads: If variable fills in all of Hack for LA's SVGs is something that would add value, it is an issue in itself to ensure that it is done uniformly across the site. Also if you search the codebase for every SVG fill property -> `fill="` there are over 4000 individual results that would have to be changed from a hex code to a color code OR of course re-doing the SVGs.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>
<img alt="hackforla:about#platform" src="https://user-images.githubusercontent.com/89806097/153700896-74725d51-0f83-49ec-a61c-820143b2b3e7.png" />
https://www.hackforla.org/about/#platform

</details>

<details>
<summary>Visuals after changes are applied</summary>
<img alt="screencapture-localhost-4000-about" src="https://user-images.githubusercontent.com/89806097/153700898-83d39326-fa27-45c2-b0ab-2798ef2ae681.png" />
http://localhost:4000/about/#platform
</details>

2022-02-13 18:21 UTC, SAUMILDHANKAR commented
Review ETA: EOD 1/16/22
Availability: Tuesday 6-8 PM

2022-02-17 10:26 UTC, SAUMILDHANKAR requested changes
@lindseyindev Thank you for your detailed analysis of this issue. I agree changes to svg might be beyond this issue.  All looks fine in my environment. Should be ready to merge once color-blue is confirmed. Thank you.

2022-02-17 10:26 UTC, SAUMILDHANKAR commented on _sass/variables/_colors.scss
>  $color-blue: #046afa;
@lindseyindev Just wanted to confirm if you noticed $color-blue: #046afa being used anywhere on the website. If not, we can remove this as well. Thank you.

2022-02-21 04:23 UTC, lindseyindev commented on _sass/variables/_colors.scss
>  $color-blue: #046afa;
@SAUMILDHANKAR I have color-blue used once on the wins form scss 
https://github.com/hackforla/website/blob/gh-pages/_sass/components/_wins-form.scss 

and my audit didn't result in a change to this
![color-blue](https://user-images.githubusercontent.com/89806097/154888599-411d9fd6-ae81-48c3-86c2-8e10786c14ba.png)

2022-02-21 18:39 UTC, SAUMILDHANKAR commented
Review ETA: 8 PM 2/21/22
Availability: Monday 7-8 PM Pacific Time

2022-02-21 23:40 UTC, SAUMILDHANKAR commented on _sass/variables/_colors.scss
>  $color-blue: #046afa;
@lindseyindev Thank you for confirming this. Sorry, I missed it as I only searched using hexadecimal color value.

2022-02-21 23:44 UTC, SAUMILDHANKAR approved these changes
Looks good to me. Thank you Lindsey.

2022-02-21 23:44 UTC, merged