changed the overview link for the markdown file to show the pdf as em…
hackforla/website pull request #2772
Opened 2022-02-13 02:57 UTC by blulady

…bedded

Fixes #2242

### What changes did you make and why did you make them ?

  -I added the pdf to the assets/pdf
  -I added the link to the TDM_Calculater.md 

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

![image](https://user-images.githubusercontent.com/67162265/154869397-a5fda9da-0639-45e3-861d-5003ed75a49c.png)

</details>

<details>
<summary>Visuals after changes are applied</summary>

![image](https://user-images.githubusercontent.com/67162265/154869544-bdbdacbb-5ef4-4d2c-804e-4b05a0266570.png)

2022-02-13 07:10 UTC, JessicaLucindaCheng commented
@blulady In your original post, where it says "Fixes #update-how-overview-link-opens-for-LA-TDM-Calculator_2242", can you edit it so it links to the issue this pr is supposed to fix? So, it should be "Fixes #2242".

2022-02-13 13:06 UTC, blulady commented
Thanks Jessica!! I knew I had done something.

2022-02-13 17:09 UTC, JessicaLucindaCheng commented
@blulady 
On the right, please add your pull request to the project board.
<img width="297" alt="Add-to-project-board" src="https://user-images.githubusercontent.com/31293603/150872571-d6b0a9a4-43fd-4357-a875-082f680e29c1.png">

2022-02-13 18:15 UTC, JessicaLucindaCheng commented
- Availability: 1 hour
- Review ETA: Sun, Feb 13, 2022

2022-02-14 02:59 UTC, JessicaLucindaCheng requested changes
@blulady Thanks for working on this issue!
- [ ] On the right, please add your pull request to the project board.
<img width="297" alt="Add-to-project-board" src="https://user-images.githubusercontent.com/31293603/150872571-d6b0a9a4-43fd-4357-a875-082f680e29c1.png">

- [ ] I don't see LA TDM Calculator's overview pdf in the /assets/pdfs directory. So, please add the pdf there.
- [ ] The link should not be set in embed tags. The link should be changed and should look something like `'../assets/pdfs/Name-of-One-Sheet.pdf'` with Name-of-One-Sheet,pdf replaced with the actual name of the pdf file you added to the /assets/pdfs folder.

Please take a look at the instructions in your issue #2242 again for more instructions and details.

2022-02-14 21:30 UTC, blulady commented
Ok... So I don't know how I got so far off track. But I believe I made the correct fixes this time. Can I submit an entirely new pr for this issue?

2022-02-14 21:32 UTC, blulady commented
Also can you send a page link to where I add the pr to the project board?

2022-02-15 21:37 UTC, JessicaLucindaCheng commented
@blulady 

> Ok... So I don't know how I got so far off track. But I believe I made the correct fixes this time. Can I submit an entirely new pr for this issue?

If you are using the same topic branch (update-how-overview-link-opens-for-LA-TDM-Calculator_2242) in your forked repo, you can just push commits to your topic branch and you should see the commits in this pr.


> Also can you send a page link to where I add the pr to the project board?

Sorry, I wasn't clearer about how to do that. Hopefully, the following instructions are more helpful:

1) On the right, under the "Projects" section
<img width="300" alt="how-to-add-to-the-project-board1" src="https://user-images.githubusercontent.com/31293603/154151587-60ef593b-82c2-4ad1-9da2-8c1d727969ed.png">

2) Click on the gear icon
<img width="300" alt="Add-to-project-board" src="https://user-images.githubusercontent.com/31293603/150872571-d6b0a9a4-43fd-4357-a875-082f680e29c1.png">

3) Then click on Project Board to add your pull request to the project board.
<img width="300" alt="how-to-add-to-the-project-board3" src="https://user-images.githubusercontent.com/31293603/154151631-ac963253-f7d4-4112-89f5-dfce27bf2449.png">

2022-02-17 01:06 UTC, JessicaLucindaCheng commented
@blulady I have removed the request for review for myself for now. Please make the requested changes in this comment: https://github.com/hackforla/website/pull/2772#pullrequestreview-881115088

After you make those changes and you are ready for me to re-review your pull request, please click the following in the Reviewers section on the right:
<img width="243" alt="image" src="https://user-images.githubusercontent.com/31293603/153506185-1cab4d94-853f-49cd-8275-ab0573465b5e.png">

2022-02-20 23:19 UTC, blulady commented
I think I corrected it ¯\_(ツ)_/¯ 
Let me know

2022-02-22 23:56 UTC, JessicaLucindaCheng commented
- Availability: 1 hour
- Re-review ETA: Tue, Feb 22, 2022

2022-02-23 00:55 UTC, JessicaLucindaCheng commented on _projects/tdm-calculator.md
> +>>>>>>> 5277539778f9c03ef1a6839d8feb01a4179324b5
Lines 56-58 arose from a merge conflict. These lines should be removed.

2022-02-23 00:57 UTC, JessicaLucindaCheng requested changes
@blulady Thanks for adding the pdf to assets/pdfs and making the requested changes!

- [ ] However, since code from different branches were merged together and the same file was changed, there is now a merge conflict in the file `tdm-calculator.md`. You will need to edit the file and push changes to fix this issue. (See my in-line comments for which lines should be removed.)

- [ ] When you are ready for me to re-review your pull request, please click the following in the Reviewers section on the right:
<img width="243" alt="image" src="https://user-images.githubusercontent.com/31293603/153506185-1cab4d94-853f-49cd-8275-ab0573465b5e.png">

2022-02-23 00:57 UTC, JessicaLucindaCheng commented on _projects/tdm-calculator.md
> +>>>>>>> 5277539778f9c03ef1a6839d8feb01a4179324b5
Lines 56-58 arose from a merge conflict. These lines should be removed.

2022-02-23 00:57 UTC, JessicaLucindaCheng commented on _projects/tdm-calculator.md
> +<<<<<<< HEAD
Line 54 arose from a merge conflict. This line should be removed.

2022-03-11 19:35 UTC, JessicaLucindaCheng approved these changes
@blulady Good job with the changes! You did it!

2022-03-11 19:35 UTC, merged