Credits
hackforla/website pull request #2774
Opened 2022-02-13 06:05 UTC by jqg123

Fixes #replace_this_text_with_the_issue_number

### What changes did you make and why did you make them ?

  -
  -
  -

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

![image](Paste_Your_Image_Link_Here_After_Attaching_Files)

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
![image](Paste_Your_Image_Link_Here_After_Attaching_Files)

</details>

2022-02-13 07:05 UTC, JessicaLucindaCheng commented
- Availability: 1.5 hours
- Review ETA: Tue, Feb 15, 2022

2022-02-16 04:14 UTC, SAUMILDHANKAR commented
Review ETA: 2/17
Availability: Thursday 6-8 PM

2022-02-17 00:06 UTC, JessicaLucindaCheng submitted a review, later dismissed
@jqg123 In addition to my inline comments for changes, please make these changes too.

- [ ] There might have been possible changes to the branch since you last worked on this issue. Check the last pr merged on to the feature-homepage-launch branch, which should be a pr by arghmatey. In that pr, click the "Files Changed" to see what files were added.
  - [ ] Specifically, you should see what images were already added by comparing the images in Figma. 
    - [ ] There are some svg images, such as infinite.svg, that do not show up as an image but as code when looking in the "Files Changed" tab, so you will have to use Docker by using 'docker-compose up' to see those images.
    - [ ] Then make a note of what the file names are for those images and edit your credits files' `image-url` fields accordingly with those image file names.
  - [ ] Delete any images that you added that are already on the feature-homepage-launch branch. To see what images you added, check the ["Files Changed" tab for your pr](https://github.com/hackforla/website/pull/2774/files).
    - [ ] I think the only image you need to keep is this one with hands:
        
      <img width="778" alt="Hands-image-to-keep" src="https://user-images.githubusercontent.com/31293603/154377980-b80e97b8-a86a-48ef-bd7b-c7f43cddb82e.png">  

- [ ] The citizen-engagement.yml should not have been edited as it is a credit file for a different image on a different page. Please revert the changes for that file and create a new file called citizen-engagement-2.yml
  - [ ] Change the alt field text description to match the image.

- [ ] The design.yml should not have been edited as it is a credit file for a different image on a different page. Please revert the changes for that file and create a new file called design-2.yml
  - [ ] title-link should be `https://thenounproject.com/icon/design-3160558/`

- [ ] discussion-teamwork.yml is missing an alt field for alt text.

- [ ] In the section under "What changes did you make and why did you make them?" in your original post/comment, you wrote "figma prototype to feature branch". I'm confused what that means. Can you please clarify what you meant by that in your original post/comment?

- [ ] I don't see an image for the section "Visuals before changes are applied" in your original post/comment. Please edit your comment/post with a before image. You can use [GoFullPage Chrome Extension](https://chrome.google.com/webstore/detail/gofullpage-full-page-scre/fdpohaocaechififmbbbbbknoalclacl?hl=en) to get a full page screenshot.

- [ ] Also, I can't see all your images in the "Visuals after changes are applied". Please add a blank line in between each image in your original post/comment.

- [ ] Please add your pr to the Project Board.

  <details>
  
    <summary>Click here for more detailed instructions on how to add your pr to the Project Board</summary>
    
    1) On the right, under the "Projects" section
    <img width="300" alt="how-to-add-to-the-project-board1" src="https://user-images.githubusercontent.com/31293603/154151587-60ef593b-82c2-4ad1-9da2-8c1d727969ed.png">
    
    2) Click on the gear icon
    <img width="300" alt="Add-to-project-board" src="https://user-images.githubusercontent.com/31293603/150872571-d6b0a9a4-43fd-4357-a875-082f680e29c1.png">
    
    3) Then click on Project Board to add your pull request to the project board.
    <img width="300" alt="how-to-add-to-the-project-board3" src="https://user-images.githubusercontent.com/31293603/154151631-ac963253-f7d4-4112-89f5-dfce27bf2449.png">
  
  </details>
  
 
- [ ] When you are ready for me to re-review your pull request, please click the following in the Reviewers section on the right:
<img width="243" alt="image" src="https://user-images.githubusercontent.com/31293603/153506185-1cab4d94-853f-49cd-8275-ab0573465b5e.png">

2022-02-17 00:06 UTC, JessicaLucindaCheng commented on _data/internal/credits/discussion-teamwork.yml
> +provider-link: https://thenounproject.com/kerismaker/collection/product-management-line/?i=3656728
This link should be `https://thenounproject.com/`

2022-02-17 00:06 UTC, JessicaLucindaCheng commented on _data/internal/credits/operations.yml
> +provider-link: 'https://thenounproject.com/'
The link doesn't need single quotes around it.

2022-02-17 00:06 UTC, JessicaLucindaCheng commented on _data/internal/credits/datascience.yml
> +title-link: https://www.thenounproject.com/search/?q=data+science&i=1705416
The link should be `https://thenounproject.com/search/?q=data+science&i=1705416`

2022-02-17 00:06 UTC, JessicaLucindaCheng commented on _data/internal/credits/operations.yml
> +title-link: https://thenounproject.com/icon/operations-1819014/
The link should be `https://thenounproject.com/search/?q=operations&i=1819014`

2022-02-17 00:06 UTC, JessicaLucindaCheng commented on _data/internal/credits/datascience.yml
> +provider-link: https://www.thenounproject.com/
The link should be `https://thenounproject.com/`

2022-02-17 00:06 UTC, JessicaLucindaCheng commented on _data/internal/credits/accounting.yml
> +
Missing an `alt` field for alt-text

2022-02-17 00:06 UTC, JessicaLucindaCheng commented on _data/internal/credits/hand.yml
> +
`alt` field for alt text is missing.

2022-02-17 00:06 UTC, JessicaLucindaCheng commented on _data/internal/credits/infinity.yml
> +
Missing an alt field for alt text.

2022-02-17 00:06 UTC, JessicaLucindaCheng commented on _data/internal/credits/marketing.yml
> +
Missing an alt field for alt text.

2022-02-17 00:06 UTC, JessicaLucindaCheng commented on _data/internal/credits/socialsafetynet.yml
> +
Missing an alt field for alt text.

2022-02-17 00:06 UTC, JessicaLucindaCheng commented on _data/internal/credits/justice.yml
> +
Missing an alt field for alt text.

2022-02-17 00:06 UTC, JessicaLucindaCheng commented on _data/internal/credits/environment.yml
> +
Missing an alt field for alt text.

2022-02-17 00:06 UTC, JessicaLucindaCheng commented on _data/internal/credits/diversityequityinclusion.yml
> +
Missing an alt field for alt text.

2022-02-17 00:06 UTC, JessicaLucindaCheng commented on _data/internal/credits/VotingRepresentation.yml
> +
Missing an alt field for alt-text.

2022-02-17 00:06 UTC, JessicaLucindaCheng commented on _data/internal/credits/civictechinfrastructure.yml
> +alt: 'Image of people together in community'
This alt text description doesn't match the image. Please use a description that describes the image.

2022-02-17 00:06 UTC, JessicaLucindaCheng commented on _data/internal/credits/justice.yml
> +title: Justice
`title: Justice` should go on the line before the line with `used-in` field.

2022-02-17 00:06 UTC, JessicaLucindaCheng commented on _data/internal/credits/justice.yml
> +used in: Homepage
Fields can't have spaces. It should be `used-in`

2022-02-17 00:06 UTC, JessicaLucindaCheng commented on _data/internal/credits/VotingRepresentation.yml
> +Provider: Unsplash
`provider` should be lowercase.

2022-02-17 00:06 UTC, JessicaLucindaCheng commented on _data/internal/credits/environment.yml
> +used in: Homepage
Should be `used-in`

2022-02-17 00:06 UTC, JessicaLucindaCheng commented on _data/internal/credits/diversityequityinclusion.yml
> +Used in: Homepage
Should be `used-in`

2022-02-17 00:06 UTC, JessicaLucindaCheng commented on _data/internal/credits/VotingRepresentation.yml
> +artist: Christina-wocintechchat
The artist should be `Phillip Goldsberry`

2022-02-17 01:31 UTC, JessicaLucindaCheng commented on _data/internal/credits/VotingRepresentation.yml
> +image-url: /assets/images/Voting&Representation/christina-wocintechchat-com-mxOdUd1BQIM-unsplash.jpg
The image-url link should be `/assets/images/program-areas/vote-representation.png`

2022-02-21 18:32 UTC, SAUMILDHANKAR commented
Review ETA: End of day 2/22/22
Availability: Tuesday 8-10 PM Pacific Time

2022-02-23 23:59 UTC, SAUMILDHANKAR commented on assets/images/discussion-teamwork/noun-discussion-teamwork-3656728.svg
> +</svg>
This image is already there in the feature-homepage-launch branch, so please remove it.

2022-02-24 00:02 UTC, SAUMILDHANKAR commented on _data/internal/credits/discussion-teamwork.yml
> +---
Your yml file should basically edit the following yml file already in the feature branch as per new details on the Figma page. [_data/internal/credits/product-management.yml](https://github.com/hackforla/website/pull/2373/files#diff-5d43d5d9daf112bf202b7bee4f1bfe98b81e0f85b7441f5890289d85f544ff07)

2022-02-24 00:23 UTC, SAUMILDHANKAR commented on _data/internal/credits/WorkforceDevelopment.yml
> +
Please remove this yml file as this is not there on the Figma page.

2022-02-24 00:34 UTC, SAUMILDHANKAR commented on _data/internal/credits/design.yml
>  ---
There should be no changes made to this file, i.e., it should look exactly as it currently is on the feature branch and hence should not be in the files changes tab.

2022-02-24 00:53 UTC, SAUMILDHANKAR commented on _data/internal/credits/design-2.yml
> +used-in: Credits
Please change Credits to Homepage

2022-02-24 00:54 UTC, SAUMILDHANKAR commented on _data/internal/credits/design-2.yml
> +artist: stories
Please change stories to Eucalyp

2022-02-24 00:55 UTC, SAUMILDHANKAR commented on _data/internal/credits/design-2.yml
> +provider: Freepik
Please change Freepik to Noun Project

2022-02-24 00:56 UTC, SAUMILDHANKAR commented on _data/internal/credits/design-2.yml
> +provider-link: 'https://www.freepik.com/'
Please use the following link: 'https://www.thenounproject.com/'

2022-02-24 00:57 UTC, SAUMILDHANKAR commented on _data/internal/credits/design-2.yml
> +alt: 'Design Community Concept Illustration'
Please remove this line.

2022-02-24 01:01 UTC, SAUMILDHANKAR commented on assets/images/design/noun-design-3160558.svg
> +</svg>
Please use the credits folder [website/assets/images/credits/] for this image.

2022-02-24 01:04 UTC, SAUMILDHANKAR commented on _data/internal/credits/design-2.yml
> +image-url: /assets/images/credits/credits-hero.svg
image-url should be changed based on where the image is stored. Please see my comment below next to this file: assets/images/design/noun-design-3160558.svg

2022-02-24 01:28 UTC, SAUMILDHANKAR commented on _data/internal/credits/design-2.yml
> +title-link: https://www.freepik.com/free-vector/design-community-concept-illustration_6610841.htm
Please use the following correct link: https://thenounproject.com/icon/design-3160558/

2022-02-24 01:50 UTC, SAUMILDHANKAR commented on assets/images/infinity/noun-infinity-686117.svg
> +</svg>
We don't need to add this file as it is a duplicate of the following: [assets/images/hero/infinite.svg](https://github.com/hackforla/website/pull/2373/files#diff-f445b1436dff9828d448e19bb8fca38894f203cfda3b92a580341d59be18c3d1) and is already there in the feature branch.

2022-02-24 01:53 UTC, SAUMILDHANKAR commented on _data/internal/credits/justice.yml
> +image-url: /assets/images/justice/sean-lee-bvHcG6334dE-unsplash.jpg
As the image already exists in the feature branch, so use that image-url here instead.

2022-02-24 02:06 UTC, SAUMILDHANKAR commented on _data/internal/credits/civictechinfrastructure.yml
> +image-url: /assets/images/civictechinfrastructure/adeolu-eletu-unRkg2jH1j0-unsplash.jpg
Please change the url with the following url: [assets/images/program-areas/civic-tech-infrastructure.png](https://github.com/hackforla/website/pull/2373/files#diff-d7eb5be6267d0ba2f752538b0ea04a331aa1436b6a3d0aee372b5dc4b3952844) as the image already exists in the feature branch.

2022-02-24 02:17 UTC, SAUMILDHANKAR requested changes
@jqg123 Thanks for making the changes in your latest commit. We are getting there. Request you to make the following changes:
- The following jpg file used as image for workforce development should not be there as part of this PR, so please remove it. [assets/mages/WorkforceDevelopment/christina-wocintechchat-com-mxOdUd1BQIM-unsplash.jpg]
- The following two files should not be in the files changes tab as it is already there in the feature branch. [_data/internal/credits/operations.yml], [assets/images/operations/noun-operations-1819014.svg](https://github.com/hackforla/website/pull/2774/files#diff-b0c05d9fcef87ca26f5cf0884ef8f879e6c882bcc3cf743e9c64e5519582a0db)(https://github.com/hackforla/website/pull/2774/files#diff-db5a867ab8ddb97cf786803bf4adfc17bb74de24680fb3c2c549bd1a9dc31399), also please do the same for data-science and marketing as well.
- Your accounting yml file should make changes to the revenue yml file which already exists in the feature branch and accounting image is also there with the name of fundraising.
- Your coding yml file should make changes to the engineering yml file which already exists in the feature branch, please make changes to the respective images as well.
- Your design-2 yml file should make changes to the ui-ux yml file which already exists in the feature branch, please make changes to the respective images as well.
- Citizen Engagement yml file should not be in the files changes tab. Changes that you have made to the citizen engagement file should actually be made to citizen-engagement-2 yml file. Also, the image url in citizen-engagement02 file should be [assets/images/program-areas/citizen-engagement.png](https://github.com/hackforla/website/pull/2373/files#diff-c039d78059b82346b5b6f0f0a09781a8c4866bf492c913cdf558affde81d0fbe) as the file already exists in the feature branch.

There are some more changes that need to be made which are similar to those I have already requested, i.e., images for Diversity equity inclusion, social safety net, vote representation, justice, environment are already there in the feature branch so no need to add them here. I will wait for you to make these changes and then take a look again. Please request a re-review once you are done. Thank you.

2022-02-26 20:44 UTC, jqg123 commented
I may need someone to take over this issue. 
ETA:n/a
Availability: 1hr

2022-03-05 01:08 UTC, JessicaLucindaCheng commented
@jqg123
> I may need someone to take over this issue. ETA:n/a Availability: 1hr

Do you want us to un-assign you from the issue related to this pr?

2022-03-07 22:14 UTC, SAUMILDHANKAR commented
@jqg123 Just wanted to follow up and know more about the reasons you wanted someone to take over this issue. Do you have any questions, need help or not have enough time or if you would like to work on some other issue instead of this? Please let us know. We will wait for a few days for your response before taking next steps. I will leave a slack message about the same as well. Thank you.

2022-03-12 01:31 UTC, SAUMILDHANKAR commented
Received an update from John, not able to continue on this due to an upcoming job. 
Planning to close this PR since it would take more time to make changes than doing it from scratch. Also, the issue needs a rewrite as well. Including Jessica and John for reference (@jqg123, @JessicaLucindaCheng)

2022-03-12 01:34 UTC, closed without merging