Added program area 2384
hackforla/website pull request #2790
Opened 2022-02-18 19:04 UTC by KazushiR

Fixes #2384

### What changes did you make and why did you make them ?

added the program-area as instructed
There are no changes to the website

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

![image](Paste_Your_Image_Link_Here_After_Attaching_Files)

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
![image](Paste_Your_Image_Link_Here_After_Attaching_Files)

</details>

2022-02-19 05:45 UTC, SAUMILDHANKAR commented
Review ETA: End of day 2/18/22
Availability: Now for an hour

2022-02-19 06:07 UTC, SAUMILDHANKAR requested changes
@KazushiR Thanks for working on this issue. Changes made to the spare.md file should not be part of this PR. Following stpes might fix it: update your forked gh-pages and merge your forked gh-pages into your topic branch. Also, request you to add your ETA and availability while picking up a new issue. Thanks.

2022-02-19 06:07 UTC, SAUMILDHANKAR commented on _projects/spare.md
> -    url: 'http://whatcanyouspare.org'
@KazushiR Changes made to this file should not be part of this PR.

2022-02-19 06:14 UTC, KazushiR commented
> @KazushiR Thanks for working on this issue. Changes made to the spare.md file should not be part of this PR. Following stpes might fix it: update your forked gh-pages and merge your forked gh-pages into your topic branch. Also, request you to add your ETA and availability while picking up a new issue. Thanks.

@SAUMILDHANKAR 
Ah my mistake. I will fix this issue and make another pull request.

2022-02-19 07:57 UTC, SAUMILDHANKAR commented
@KazushiR No worries. There is no need to make another pull request. You can make the changes in this branch itself and add another commit.

2022-02-19 23:42 UTC, KazushiR commented
> @KazushiR No worries. There is no need to make another pull request. You can make the changes in this branch itself and add another commit.

@SAUMILDHANKAR Hello, I believe I have made the requested changes. Are you able to confirm on your side?

2022-02-20 09:36 UTC, SAUMILDHANKAR commented
@KazushiR Sorry if I was not clear about making the changes to the spare.md file. In your last commit, spare.md file seems to be deleted. This should not be the case and the file should be part of you branch. 
We need to resolve the conflicts in your branch. Please go through the following link, [resolving merge conflict](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github) for the possible next steps. Thank you.

2022-02-20 18:23 UTC, Carlos-A-P commented
Availability: 2hrs
ETA: Wed, 2/23/2022

2022-02-20 22:17 UTC, Carlos-A-P commented
@KazushiR While you're resolving the merging conflicts, also make sure to add "No visual changes" under "Screenshots of Proposed Changes Of The Website"

2022-02-22 17:52 UTC, KazushiR commented
> @KazushiR Sorry if I was not clear about making the changes to the spare.md file. In your last commit, spare.md file seems to be deleted. This should not be the case and the file should be part of you branch. We need to resolve the conflicts in your branch. Please go through the following link, [resolving merge conflict](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github) for the possible next steps. Thank you.

@SAUMILDHANKAR Hello, I followed the steps and it seems as though I'm not authorized to merge a pull request.

2022-02-22 17:52 UTC, KazushiR commented
> @KazushiR While you're resolving the merging conflicts, also make sure to add "No visual changes" under "Screenshots of Proposed Changes Of The Website"

2022-02-22 18:03 UTC, Carlos-A-P commented
@KazushiR Once you think your PR is ready to be reviewed again, request @SAUMILDHANKAR to review it again. You have to be part of the merging team to merge PRs

2022-02-25 02:06 UTC, SAUMILDHANKAR commented
Review ETA: End of day 2/24/22
Availability: Thursday 9-10 PM Pacific Time

2022-02-25 20:38 UTC, SAUMILDHANKAR requested changes
@KazushiR Thank you for making another commit to fix the issue, however, as you can see in the files changed tab spare.md is showing up as deleted. Please make sure only the changes made to jobs-for-hope.md file are visible in the files changed tab. Thanks.

2022-02-28 09:34 UTC, SAUMILDHANKAR commented
@KazushiR Hope you are doing well. Just wanted to share one of the decisions made during our team meeting. We are now requesting all website team members to attend at least one meeting in a week (Tuesday, Thursday or Sunday) as we strive to replicate a professional working environment within our team amongst other things. Therefore, request you to let us know which of the weekly meetings would be suitable for you based on availability. We have decided to make an exception for this requirement only on a case-by-case basis. I will leave a message for you on slack as well. Thank you.

2022-03-05 07:57 UTC, SAUMILDHANKAR commented
Progress update: Kazushi will be back next week.

2022-03-05 07:59 UTC, KazushiR commented
> Progress update: Kazushi will be back next week.

Hello, I am feeling better and will start working on this issue this weekend. I apologize on the delay.

2022-03-18 16:16 UTC, KazushiR reviewed
I believe I have corrected the changes on this PR

2022-03-18 23:39 UTC, SAUMILDHANKAR commented
> I believe I have corrected the changes on this PR

@KazushiR I still see spare.md file as deleted in the files changed tab. Did you try adding it back to your branch?

2022-03-18 23:42 UTC, KazushiR commented
> > I believe I have corrected the changes on this PR
> 
> 
> 
> @KazushiR I still see spare.md file as deleted in the files changed tab. Did you try adding it back to your branch?

Hello Saumil. I tried to make the changes in my original branch but when I tried to push the changes, it will make a new PR. I went in and deleted the spare.md file in this pr manually.

2022-03-21 06:44 UTC, SAUMILDHANKAR commented
@KazushiR We will need to resolve the merge conflicts which are part of this PR (this might be because changes were made to spare.md file twice). Since, you are being prompted to make a new PR while doing a commit, I am not sure if git revert would work either. But we can explore `git reset --hard`. Please let me know if you would like to go over it during meeting time or some other time that works for you. Thank you.

2022-03-21 06:46 UTC, KazushiR commented
> @KazushiR We will need to resolve the merge conflicts which are part of this PR (this might be because changes were made to spare.md file twice). Since, you are being prompted to make a new PR while doing a commit, I am not sure if git revert would work either. But we can explore `git reset --hard`. Please let me know if you would like to go over it during meeting time or some other time that works for you. Thank you.

Hello Saumil. I will look into this further and if I cannot get it resolved, I will go over it with you during the meeting.

2022-03-26 07:13 UTC, SAUMILDHANKAR requested changes
@KazushiR Thanks a lot for working on this issue and resolving merge conflicts. Thanks @JessicaLucindaCheng for helping us in resolving merge conflicts. I just noticed that there would be visual changes to the website (as program area: social safety net should be visible in jobs for hope project card) and I should have mentioned it yesterday as well (my bad). So, requesting to add the images in your initial comment. Rest all looks good. Please request a re-review once you have done that. Really appreciate your great work. Thank you.

2022-03-27 06:41 UTC, KazushiR commented
> @KazushiR Thanks a lot for working on this issue and resolving merge conflicts. Thanks @JessicaLucindaCheng for helping us in resolving merge conflicts. I just noticed that there would be visual changes to the website (as program area: social safety net should be visible in jobs for hope project card) and I should have mentioned it yesterday as well (my bad). So, requesting to add the images in your initial comment. Rest all looks good. Please request a re-review once you have done that. Really appreciate your great work. Thank you.

@SAUMILDHANKAR I will go ahead and get this done to close out this pr. @JessicaLucindaCheng thank you again for the help.

2022-04-01 23:54 UTC, SAUMILDHANKAR approved these changes
@KazushiR Thanks a lot for making the changes and adding the images. I will just remove the line where it says no change to the website. Rest all looks good. Really appreciate all the work that you have done on this issue. Thank you.

2022-04-01 23:56 UTC, merged