Issue 2423 - Modernized HTML <b> to <strong> tags
hackforla/website pull request #2862
Opened 2022-02-23 05:12 UTC by greylaw89

Fixes #replace_this_text_with_the_issue_number

### What changes did you make and why did you make them ?

  -
  -
  -

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

![image](Paste_Your_Image_Link_Here_After_Attaching_Files)

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
![image](Paste_Your_Image_Link_Here_After_Attaching_Files)

</details>

2022-02-23 18:06 UTC, answebdev commented
ETA: End of day 2/23/2022
Availability: 3 hours, 2/23/2022

2022-02-23 20:28 UTC, greylaw89 commented
Hello Adolf,

Thank you for reviewing my first pull request, please let me know if there
is anything I can improve upon.

Thanks!!!

Kristoffer Law


On Wed, Feb 23, 2022 at 10:06 AM Adolf Schmuck ***@***.***>
wrote:

> ETA: End of day 2/23/2022
> Availability: 3 hours, 2/23/2022
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/hackforla/website/pull/2862#issuecomment-1049063410>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACZYJ67ROAUJIAHYEQKFUHLU4UO3TANCNFSM5PDKEWXA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you modified the open/close state.Message
> ID: ***@***.***>
>

2022-02-23 20:28 UTC, answebdev approved these changes
@greylaw89 Thank you for submitting your PR. For this issue, the tags in lines 24 and 25 needed to be changed from b to strong, which I can see that you did. Great job with that!

- Also, please add this PR to the project board. Thank you.

2022-02-24 07:01 UTC, JasonY188 approved these changes
Hi Kristoffer,

Your changes look good.  Great job!

2022-02-24 20:17 UTC, JessicaLucindaCheng commented on _guide-pages/2FA.html
> +            <h5 class="title-left"><strong>Visit and follow </strong><strong><a href="https://docs.github.com/en/github/authenticating-to-github/configuring-two-factor-authentication" target="blank">
Instead of having 2 strong tags for line 25, there should be one strong tag. This is specified in the instructions in the issue for Line 25 being changed to
```
<h5 class="title-left"><strong>Visit and follow <a href="https://docs.github.com/en/github/authenticating-to-github/configuring-two-factor-authentication" target="blank">Github's Guide to Setting Up 2FA</a></strong></h5>
```

2022-02-24 20:22 UTC, JessicaLucindaCheng requested changes
@greylaw89 Thanks for working on this issue.

- [ ] Please make the in-line request for change and push your changes to your branch.

- [ ] Also, please add your pr to the Project Board.

  <details>
  
    <summary>Click here for more detailed instructions on how to add your pr to the Project Board</summary>
    
    1) On the right, under the "Projects" section
      <img width="300" alt="how-to-add-to-the-project-board1" src="https://user-images.githubusercontent.com/31293603/154151587-60ef593b-82c2-4ad1-9da2-8c1d727969ed.png">
    
    2) Click on the gear icon
      <img width="300" alt="Add-to-project-board" src="https://user-images.githubusercontent.com/31293603/150872571-d6b0a9a4-43fd-4357-a875-082f680e29c1.png">
    
    3) Then click on Project Board to add your pull request to the project board.
      <img width="300" alt="how-to-add-to-the-project-board3" src="https://user-images.githubusercontent.com/31293603/154151631-ac963253-f7d4-4112-89f5-dfce27bf2449.png">
  
  </details>

- [ ] When you are ready for me to re-review your pull request, please click the following in the Reviewers section on the right:
  <img width="243" alt="image" src="https://user-images.githubusercontent.com/31293603/153506185-1cab4d94-853f-49cd-8275-ab0573465b5e.png">

2022-02-24 20:22 UTC, JessicaLucindaCheng commented on _guide-pages/2FA.html
> +            <h5 class="title-left"><strong>Visit and follow </strong><strong><a href="https://docs.github.com/en/github/authenticating-to-github/configuring-two-factor-authentication" target="blank">
Instead of having 2 strong tags for line 25, there should be one strong tag. This is specified in the instructions in the issue for Line 25 being changed to
```
<h5 class="title-left"><strong>Visit and follow <a href="https://docs.github.com/en/github/authenticating-to-github/configuring-two-factor-authentication" target="blank">Github's Guide to Setting Up 2FA</a></strong></h5>
```

So, after `Visit and follow `, remove the `</strong><strong>`

2022-02-24 20:30 UTC, greylaw89 commented
Thank you Jessica, I'll review and resubmit with the correct changes.

Thanks!!

Kristoffer Law


On Thu, Feb 24, 2022 at 12:22 PM Jessica Cheng ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> @greylaw89 <https://github.com/greylaw89> Thanks for working on this
> issue. Please make the in-line request for change and push your changes to
> your branch.
>
> When you are ready for me to re-review your pull request, please click the
> following in the Reviewers section on the right:
> [image: image]
> <https://user-images.githubusercontent.com/31293603/153506185-1cab4d94-853f-49cd-8275-ab0573465b5e.png>
> ------------------------------
>
> In _guide-pages/2FA.html
> <https://github.com/hackforla/website/pull/2862#discussion_r814235763>:
>
> > @@ -21,8 +21,8 @@
>      <a class='anchor' id='To-Enable-2FA'></a>
>      <div class='section-container'>
>          <div>
> -            <h3 class="title-left"><b>To Enable 2FA:</b></h3>
> -            <h5 class="title-left"><b>Visit and follow </b><b><a href="https://docs.github.com/en/github/authenticating-to-github/configuring-two-factor-authentication" target="blank">Github's Guide to Setting Up 2FA</a></b></h5>
> +            <h3 class="title-left"><strong>To Enable 2FA:</strong></h3>
> +            <h5 class="title-left"><strong>Visit and follow </strong><strong><a href="https://docs.github.com/en/github/authenticating-to-github/configuring-two-factor-authentication" target="blank">Github's Guide to Setting Up 2FA</a></strong></h5>
>
> Instead of having 2 strong tags for line 25, there should be one strong
> tag. This is specified in the instructions in the issue for Line 25 being
> changed to
>
> <h5 class="title-left"><strong>Visit and follow <a href="https://docs.github.com/en/github/authenticating-to-github/configuring-two-factor-authentication" target="blank">Github's Guide to Setting Up 2FA</a></strong></h5>
>
> So, after Visit and follow , remove the </strong><strong>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/hackforla/website/pull/2862#pullrequestreview-892951862>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACZYJ66LHHGRMLRH3M7X54DU42HSDANCNFSM5PDKEWXA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-03-12 06:58 UTC, SAUMILDHANKAR commented
@greylaw89 Hi Kristoffer, Just wanted to follow up regarding your progress on this issue. Please let us know if you have any questions, need help or need more time to work on the changes requested. I will leave a slack message as well about the same. Thanks.

2022-03-19 17:07 UTC, SAUMILDHANKAR commented
@greylaw89 I am planning to close this PR due to inactivity. Feel free to work on this or any other issue when your availability changes. Thank you.

2022-03-26 21:28 UTC, closed without merging