Applied design system heading classes to Getting Started page
hackforla/website pull request #2889
Opened 2022-02-25 21:45 UTC by 1anya1

Fixes #2083

### What changes did you make and why did you make them ?

Applied design system heading classes to Getting Started page 
  -  added title1 class to "Getting Started" header
  - added title4 class to "Frequently Asked Questions" header
  -  checked for mobile responsiveness  and accessibility for Heading hierarchy and the tests passes. 

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

![Getting Started Desktop - original](https://user-images.githubusercontent.com/52765927/155806872-a9b337a2-e099-42f0-8481-30dd3c9d5277.png)

</details>

<details>
<summary>Visuals after changes are applied</summary>

![Getting Started Desktop View - Updated](https://user-images.githubusercontent.com/52765927/155805985-ee7e6739-cc6e-438f-9be4-839e4afff1ef.png)
  
![ Getting Started Mobile View - updated version](https://user-images.githubusercontent.com/52765927/155805385-6a872f5d-493b-4de7-9045-0dc43eff633b.png)

</details>

2022-02-26 21:38 UTC, Carlos-A-P commented
Availability: 2 hrs
ETA: 2/26/2022

2022-02-26 22:27 UTC, Carlos-A-P approved these changes, later dismissed
@1anya1 I can see the added classes in my local environment. Great Job!

2022-02-27 18:27 UTC, Sparky-code commented
ETA: EOD Monday
Avail: 1hr today + time tomorrow

2022-02-28 17:17 UTC, Sparky-code reviewed
Changes look good on git and in local environment. double checked responsiveness, looks good!

2022-02-28 17:18 UTC, Sparky-code submitted a review, later dismissed

2022-02-28 20:46 UTC, JessicaLucindaCheng requested changes
@1anya1 Thanks for working on this issue! Please make the requested changes in my in-line comment.

- [x] When you are ready for me to re-review your pull request, please click the following in the Reviewers section on the right:
<img width="243" alt="image" src="https://user-images.githubusercontent.com/31293603/153506185-1cab4d94-853f-49cd-8275-ab0573465b5e.png">

2022-02-28 20:46 UTC, JessicaLucindaCheng commented on pages/getting-started.html
> +            <p class="getting-started-step-title-faq title4">Frequently Asked Questions</p>
I'm not sure why this uses a p HTML tag but it should have been a header tag.
- [ ] Please change the `p` HTML tag to a `h2` HTML tag so that heading follows WCAG. (For additional information about header tags and WCAG: https://www.w3.org/WAI/tutorials/page-structure/headings/)
- [ ] Make sure this heading still looks good both in mobile and desktop, and that nothing gets messed up due to the change

2022-02-28 21:23 UTC, 1anya1 commented on pages/getting-started.html
> +            <p class="getting-started-step-title-faq title4">Frequently Asked Questions</p>
@JessicaLucindaCheng changes have been made.

2022-02-28 21:59 UTC, JessicaLucindaCheng approved these changes
@1anya1  Thanks for making the changes! It looks good to me now.

2022-02-28 22:00 UTC, merged