Update COP engineering section
hackforla/website pull request #2905
Opened 2022-03-01 05:59 UTC by luke-karis

Fixes #2744

### What changes did you make and why did you make them ?

  - Removed Greg Pawin from engineering COP section
  - Added Ava Li to engineering COP section

### Screenshots of Proposed Changes Of The Website  

<details>
<summary>Visuals before changes are applied</summary>

![2744_Before](https://user-images.githubusercontent.com/69996875/156113401-9b20cef5-f5e1-44a9-8fd1-c755d01faa40.png)

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
![2744_After](https://user-images.githubusercontent.com/69996875/156113455-13dce6ec-d52c-4299-a297-016b916d904f.png)

</details>

2022-03-01 17:25 UTC, tamara-snyder commented
Availability: 1 hour
Review ETA: Tuesday, March 1, 2022

2022-03-01 17:37 UTC, tamara-snyder approved these changes, later dismissed
Hi Luke, this looks great! The engineering lead has been updated, the new links work, and the picture displays as expected. Well done on this issue!

2022-03-01 23:54 UTC, blulady commented
Picture looks great (I like how you linked it to the slack) and the code looks clean. However it looks like the github link goes to https://github.com/hackforla/engineering rather than Ava's personal github but I believe it is intentional. The rest of the github links go to various HackforLa departments. I only mention it because in the code, it links to her personal github.

2022-03-01 23:55 UTC, blulady commented
Availability: 90 minutes
Review ETA: Tuesday, March 1, 2022

2022-03-01 23:56 UTC, blulady submitted a review, later dismissed

2022-03-02 01:56 UTC, JessicaLucindaCheng requested changes
@luke-karis Thanks for working on this issue! Please make the change I requested in the in-line comment.

When you are ready for me to re-review your pull request, please click the following in the Reviewers section on the right:
<img width="243" alt="image" src="https://user-images.githubusercontent.com/31293603/153506185-1cab4d94-853f-49cd-8275-ab0573465b5e.png">

2022-03-02 01:56 UTC, JessicaLucindaCheng commented on _data/internal/communities/engineering.yml
> +    picture: https://ca.slack-edge.com/T04502KQX-U01B73XGCKV-5d88eaa82b7f-512
Please change the picture link to `https://avatars.githubusercontent.com/Aveline-art`, which will show her GitHub profile picture.

The reason for this change is
- When you click on the profile picture, it links to Ava's GitHub profile (which is the expected behavior). Thus, it may be confusing that the picture on the COP doesn't match the GitHub profile picture.
- Also, this keeps it consistent with the rest of the profile pictures on the COP page, which uses GitHub profile pictures.

2022-03-02 03:55 UTC, luke-karis commented on _data/internal/communities/engineering.yml
> +    picture: https://ca.slack-edge.com/T04502KQX-U01B73XGCKV-5d88eaa82b7f-512
Ok I will make this change. The reason I used the slack photo was because Ava's GitHub profile picture is just a default GitHub one

2022-03-02 21:30 UTC, JessicaLucindaCheng approved these changes
@luke-karis Thanks for making the change! Looks good to me now.

2022-03-02 21:31 UTC, merged