Resolve issue 2155 to add a comment reminding assignee to add ETA and Availability
hackforla/website pull request #2962
Opened 2022-03-11 04:33 UTC by usaboo

Fixes #2155

### What changes did you make and why did you make them ?
So basically the motive of this issue is to remind the person who has picked up an issue to let others know of their availability and their ETA to solve the issue. This is done by adding a github action script which posts a comment as soon as the issue is assigned to a person reminding them to add their availability and ETA in the form of a comment.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
No visual changes to the website but changes when you the issues are assigned on github.

2022-03-12 09:01 UTC, SAUMILDHANKAR commented
Review ETA: End of day 3/13/22
Availability: Sunday 4-6 PM Pacific Time

2022-03-14 06:50 UTC, SAUMILDHANKAR reviewed
@usaboo: Good job working on this issue. Unfortunately, I won't be able to finish my review before the end of this week due to limited availability. Please bring it up during the Tuesday dev meeting if you can, so we can have another review in the meantime if possible. 
I would also like to you to take a look at the following file: [GitHub Actions Refactor Proposal](https://docs.google.com/spreadsheets/d/12NcZQoyGYlHlMQtJE2IM8xLYpHN75agb/edit#gid=1048521288) as well as the architecture notes in this [comment](https://github.com/hackforla/website/issues/2668#issue-1096279426). Further, please consider if we can implement this functionality using the existing check-labels.js and post-labels-comment.js files. Again, thank you for working on this issue and apologies for the delay in the review.

2022-03-14 06:50 UTC, SAUMILDHANKAR commented on github-actions/trigger-issue/add-missing-labels-to-issues/check-label-preliminary-update.js
> +//With the existing labels we see if we are to post the comment or not(based on whether there exists a role:Backend/devOps tag or not) and return it as a boolean
Should this comment be updated to include other labels as mentioned in the issue.

2022-03-14 06:50 UTC, SAUMILDHANKAR commented on github-actions/trigger-issue/add-missing-labels-to-issues/check-label-preliminary-update.js
> +    //issue states that only if the roles contain back end/devOps ...(continued on next comment)
Comment needs a cleanup.

2022-03-14 06:50 UTC, SAUMILDHANKAR commented on github-actions/trigger-issue/add-missing-labels-to-issues/check-label-preliminary-update.js
> +    // or if the roles contain both front end and design are we supposed to post the comment
Comment needs a cleanup.

2022-03-16 02:32 UTC, tamara-snyder commented
Availability: 3 hours
Review ETA: Thursday, March 17, 2022

2022-03-16 02:36 UTC, luke-karis commented
Review ETA: End of Day 3/18
Availability: 2/16 1 hour, 2/18 2 hours

2022-03-20 21:38 UTC, tamara-snyder reviewed
I'm sorry Utkarsh, I will need a bit more time to make sure I understand how this code works. My review isn't finished, but I've left a few comments. ETA for my final review is Tuesday, March 22, 2022.

2022-03-20 21:38 UTC, tamara-snyder commented on github-actions/trigger-issue/add-missing-labels-to-issues/preliminary-update.md
> +i. **Availability:**(When would you be available to work on the issue/answer questions other programmers might have about your issue)
I think line 6 would be more clearly worded if you changed the text from:
`When would you be available to work on the issue/answer questions other programmers might have about your issue`
 to:
`When are you available to work on the issue/answer questions other programmers might have about your issue?`

2022-03-20 21:38 UTC, tamara-snyder commented on github-actions/trigger-issue/add-missing-labels-to-issues/preliminary-update.md
> +ii. **ETA:**(When do you think you would be able to resolve this issue by)
Change line 7 to `When do you expect this issue to be completed?` so it matches the ETA section in update-instructions-template.md

2022-03-20 21:38 UTC, tamara-snyder commented on github-actions/trigger-issue/add-missing-labels-to-issues/check-label-preliminary-update.js
> +return({shouldpost,issueNum})
Can you please indent lines 13-23 since they're inside of a function?

2022-03-20 21:38 UTC, tamara-snyder commented on github-actions/trigger-issue/add-missing-labels-to-issues/preliminary-update-comment.js
> +  }
Please unindent the closing braces (`}`) in lines 69 and 90.

2022-03-21 02:47 UTC, SAUMILDHANKAR requested changes
@usaboo I have tested your code in my repo and it works as required. Good job! However, we should consider if this functionality can be achieved using the existing check-labels.js and post-labels-comment.js files since we can reuse some of the code. So, just want to know your thoughts on that if you have tried it or would like to give it a try or if there might be some impediments. Please let me know. I will wait to hear back from you and other reviewers. Thank you.

2022-03-21 05:14 UTC, luke-karis requested changes
Hey @usaboo great job working on this! I tested creating each of the types of issues on my forked repo and it works well. In addition to the comments other people had, I think that there are some more changes that you should consider. I will leave overall comments here and then put individual comments in the code.
- Your variable naming convention is not consistent across the files. Especially in check-label-preliminary-update you are not using camel case for variable names with more than one word. I think this would make your variables a lot easier to read and it would make your code consistent as you use camel case in prelimiary-update-comment.
- I agree with Saumil that it is worth looking into consolidating your changes into the files that previously exist. However, if you don't do this I think you should make a new folder for the files you added in this PR because they are currently all in the add-missing-labels-to-issues folder.
- I think its great you've spent the time to add comments to your code :) That being said I think it would be helpful if you could make sure that for larger comments before your methods, you include a little bit about what the method does along with any params and what it returns

2022-03-21 05:15 UTC, luke-karis commented on github-actions/trigger-issue/add-missing-labels-to-issues/check-label-preliminary-update.js
> +function postcomment(namesarray)
could you use existingLabels instead of namesarray? I think its more descriptive and its what you use above when you call this method so it could help people who are reading through the code

2022-03-21 05:25 UTC, luke-karis commented on github-actions/trigger-issue/add-missing-labels-to-issues/check-label-preliminary-update.js
> +    }
These if, else if statements functionally work great and I agree with you from our previous conversation that they are pretty readable. However, if you wanted to you could consolidate these statements onto one line by making a constant array of roles and then doing something like `if(roleLabels.some(label => namesarray.include(label)){return true}` where roleLabels is an array containing the role labels.

This might actually be worse because it could make this harder to understand but I thought it was interesting and maybe in the future you'll need to compare elements of two arrays. I'm including a stack overflow post and more info about the some method.
https://stackoverflow.com/questions/16312528/check-if-an-array-contains-any-element-of-another-array-in-javascript
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/some

2022-03-21 05:30 UTC, luke-karis commented on github-actions/trigger-issue/add-missing-labels-to-issues/preliminary-update-comment.js
> +    const instructions = makeComment()
Could you indent the line inside the else statement? Also, I think it could be a good idea to remove the line separating the if and else since they are logically connected

2022-03-21 05:32 UTC, luke-karis commented on github-actions/trigger-issue/add-missing-labels-to-issues/preliminary-update-comment.js
> +  }
Does this need to be its own separate method? Its only called once and its only a couple lines so I feel like the body of this method could just be moved into the makeComment function.

2022-03-21 16:42 UTC, usaboo commented on github-actions/trigger-issue/add-missing-labels-to-issues/check-label-preliminary-update.js
> +//With the existing labels we see if we are to post the comment or not(based on whether there exists a role:Backend/devOps tag or not) and return it as a boolean
Sounds good Saumil, I have updated it to say:-

//With the existing labels we see if we are to post the comment or not(based on whether there exists a relevant role tag or not) and return it as a boolean

You should be able to see it soon.

2022-03-21 19:31 UTC, usaboo commented on github-actions/trigger-issue/add-missing-labels-to-issues/check-label-preliminary-update.js
> +    //issue states that only if the roles contain back end/devOps ...(continued on next comment)
I have cleaned it up, hope it solves the issue :)

2022-03-21 19:31 UTC, usaboo commented on github-actions/trigger-issue/add-missing-labels-to-issues/check-label-preliminary-update.js
> +    // or if the roles contain both front end and design are we supposed to post the comment
I have cleaned it up, hope it solves the issue :)

2022-03-21 19:32 UTC, usaboo commented on github-actions/trigger-issue/add-missing-labels-to-issues/preliminary-update.md
> +i. **Availability:**(When would you be available to work on the issue/answer questions other programmers might have about your issue)
I have made the change Tamara, hope it is better worded now :)

2022-03-21 19:32 UTC, usaboo commented on github-actions/trigger-issue/add-missing-labels-to-issues/preliminary-update.md
> +ii. **ETA:**(When do you think you would be able to resolve this issue by)
I have made the change Tamara, hope it is better worded now :)

2022-03-21 19:34 UTC, usaboo commented on github-actions/trigger-issue/add-missing-labels-to-issues/check-label-preliminary-update.js
> +return({shouldpost,issueNum})
I have indented the code in lines 13 - 23, plus formatted it a little to look neater. Hope it's good now.

2022-03-21 19:36 UTC, usaboo commented on github-actions/trigger-issue/add-missing-labels-to-issues/preliminary-update-comment.js
> +  }
I have formatted the formatComment() and postComment() functions to look neater and well indented as well.

2022-03-21 19:42 UTC, usaboo commented on github-actions/trigger-issue/add-missing-labels-to-issues/check-label-preliminary-update.js
> +function postcomment(namesarray)
That's a good idea luke, it does make it more clear. I have made that change.

2022-03-21 19:42 UTC, usaboo commented on github-actions/trigger-issue/add-missing-labels-to-issues/preliminary-update-comment.js
> +    const instructions = makeComment()
Yes, make sense. Made the change :)

2022-03-21 19:50 UTC, usaboo commented on github-actions/trigger-issue/add-missing-labels-to-issues/preliminary-update-comment.js
> +  }
So this is from the current gh-pages itself. I did not write this function by myself. But I honestly feel that it's easier to understand this code because it is more modular but maybe we could discuss this on Tuesday :)

2022-03-21 19:59 UTC, usaboo commented on github-actions/trigger-issue/add-missing-labels-to-issues/check-label-preliminary-update.js
> +    }
Yes I remember the discussion Luke, we could discuss this once more on Tuesday, I think both have their pros and cons but it's always nice to have as few lines of code to do anything. 
Thanks for the link also, I will look at it :)

2022-03-23 14:23 UTC, tamara-snyder requested changes
Hi Utkarsh, overall, this looks really good! I think it was a good call to move everything into its own folder.

I noticed you missed a couple of the name changes to camelcase that Luke suggested in `check-label-preliminary-update.js`. `obtainlabels()` on line 31 should be refactored to `obtainLabels()` and `postcomment()` on line 43 should become `postComment()`. And then just make sure to refactor those names elsewhere in the file.

Otherwise, really great work on this issue.

2022-03-23 21:43 UTC, SAUMILDHANKAR commented
Re-review ETA: End of day 3/24/22
Availability: Thursday 3-4 PM Pacific Time

2022-03-24 00:39 UTC, luke-karis requested changes
Hey @usaboo thanks for making changes here! I have a couple more minor comments
- It seems like your use of curly brackets are not consistent. for some functions (and if statements) you have them start on the line after the declaration and for others you have them start on the same line. I think you should be consistent with them. Looking briefly at the other GitHub action code it seems like the convention is to have the bracket start on the same line as the declaration (which I also prefer)
- For comments that are in the block comments I don't think you need the // inside them. A better options in my opinion is what you do for the formatComment method where you use a dash to split the param/return info and the description.
- Finally, I know this is nit picky and I think I mentioned it before but I think it would be good to have a little description of what the method does in each block comment. There are times that you do include a  description but it is below the comment but I think it would make more sense and look better if the description was included inside the block.

2022-03-24 00:43 UTC, luke-karis commented on github-actions/trigger-issue/add-preliminary-comment/preliminary-update-comment.js
> +      await postComment(issueNum, instructions)
Instead of checking if `instructions === null` you could do the check `instructions !== null` and in that if block call postComment. This a minor change but I think will make the code a little nicer to read.

2022-03-24 02:15 UTC, usaboo commented on github-actions/trigger-issue/add-preliminary-comment/preliminary-update-comment.js
> +      await postComment(issueNum, instructions)
Yes, it does make things more readable I agree. I have made that change :)

2022-03-25 15:13 UTC, tamara-snyder requested changes
Hi Utkarsh, thank you for fixing the comments and curly braces as Luke requested, as well as changing the rest of the names to camelcase. Everything looks a lot clearer now. There's only that one section that still needs fixed on lines 27-28 of preliminary-update-comment.js. Great work and hopefully we can get this merged soon!

2022-03-25 15:13 UTC, tamara-snyder commented on github-actions/trigger-issue/add-preliminary-comment/preliminary-update-comment.js
> +      await postComment(issueNum, instructions)}
Can you indent lines 27-28 and move the closing curly brace to the next line?

2022-03-25 21:36 UTC, SAUMILDHANKAR commented
Revised Re-review ETA: End of day 3/25/22
Availability: Friday 7-8 PM Pacific Time
@usaboo Hi Utkarsh, I was not able to finish my review yesterday but I plan to do it today. Sorry for the delay. Thak you.

2022-03-26 09:33 UTC, SAUMILDHANKAR requested changes
@usaboo Thanks for making the requested changes and keeping up with the review process. We are almost there. In addition to the pending indentation change request, please consider using consistent spacing before and after keywords, for example: line 47 in `github-actions/trigger-issue/add-preliminary-comment/check-label-preliminary-update.js` vs line 19 in `github-actions/trigger-issue/add-preliminary-comment/preliminary-update-comment.js`. Thank you.

2022-03-26 09:33 UTC, SAUMILDHANKAR commented on .github/workflows/issue-trigger.yml
> +          script: |
script block indentation should be consistent within this file, i.e.,  18-21, 28-31, 46-49, 57-60.

2022-03-26 09:33 UTC, SAUMILDHANKAR commented on github-actions/trigger-issue/add-preliminary-comment/preliminary-update-comment.js
> +function makeComment(){
Please compare line 37 with line 77 and consider consistent spacing before the start of curly brackets.

2022-03-27 19:39 UTC, usaboo commented on github-actions/trigger-issue/add-preliminary-comment/preliminary-update-comment.js
> +      await postComment(issueNum, instructions)}
Good catch Tamara. Sorry I keep making these silly mistakes. I have fixed it now though.

2022-03-27 19:53 UTC, usaboo commented on .github/workflows/issue-trigger.yml
> +          script: |
Good catch Saumil. Thanks for catching it, I have made the changes!

2022-03-27 19:56 UTC, usaboo commented on github-actions/trigger-issue/add-preliminary-comment/preliminary-update-comment.js
> +function makeComment(){
Made this change too Saumil, thanks for catching it. I will try to bring it into practice as I write more code.

2022-03-29 22:57 UTC, SAUMILDHANKAR commented
Re-review ETA: End of day 4/1/22
Availability: Friday 3-4 PM Pacific Time

2022-03-29 23:42 UTC, luke-karis commented
Re-review ETA: End of day 3/30/22
Availability: Wednesday 7-8 pm PST

2022-03-30 16:20 UTC, tamara-snyder commented
Re-review ETA: Friday, April 1
Availability: 2 hours

2022-04-02 17:20 UTC, SAUMILDHANKAR requested changes
@usaboo Thank you for making a new folder as well as all the requested changes. I have tested this in my repo and the comment is getting posted as it should, however, it is being addressed to the issue creator instead of the assignee. So we should make changes in the makeComment() function as well as preliminay-update.md file accordingly, sorry I missed it earlier. Also, suggesting a few spacing and indentation changes which I will add inline. Really appreciate your detailed work on this issue. Thanks.

2022-04-02 17:20 UTC, SAUMILDHANKAR commented on github-actions/trigger-issue/add-preliminary-comment/preliminary-update-comment.js
> +    }
Lines 27-29 should be indented, as they are inside the if block.

2022-04-02 17:20 UTC, SAUMILDHANKAR commented on github-actions/trigger-issue/add-preliminary-comment/preliminary-update-comment.js
> +  return commentToPost
Requesting to make the indentation of formatComment and postComment function blocks consistent with main and makeComment function blocks. Thank you.

2022-04-02 17:20 UTC, SAUMILDHANKAR commented on github-actions/trigger-issue/add-preliminary-comment/preliminary-update-comment.js
> +  }
Requesting to make the indentation of formatComment and postComment function blocks consistent with main and makeComment function blocks. Thank you.

2022-04-02 17:20 UTC, SAUMILDHANKAR commented on github-actions/trigger-issue/add-preliminary-comment/preliminary-update.md
> +Hi @${issueCreator}, thank you for taking up this issue! Hfla appreciates you :)
This comment should not be addressed to the issue creator but to the assignee.

2022-04-02 17:20 UTC, SAUMILDHANKAR commented on github-actions/trigger-issue/add-preliminary-comment/check-label-preliminary-update.js
> +
Suggesting to remove this extra line. Thank you.

2022-04-02 17:20 UTC, SAUMILDHANKAR commented on github-actions/trigger-issue/add-preliminary-comment/preliminary-update-comment.js
> +
Suggesting to remove this extra line. Thank you.

2022-04-02 17:20 UTC, SAUMILDHANKAR commented on github-actions/trigger-issue/add-preliminary-comment/preliminary-update-comment.js
> +    const issueCreator = context.payload.issue.user.login
Requesting to make changes in the makeComment() function, so we can address the assignee instead of the issue creator. Thanks.

2022-04-03 03:28 UTC, luke-karis requested changes
Hey @usaboo thank you for making these changes and for your great and consistent work on this ticket! I agree with Saumil that we should definitely address the assignee instead of issue creator. 

The only other thing that I would suggest that you change is the block comments for your methods. In other parts of the code the description part is put on top of the block comment without the @description tag.  I think its a good idea to make your code and comments consistent and personally I like when the description is at the top of a block comment.

2022-04-05 21:08 UTC, tamara-snyder requested changes
Hi @usaboo, in addition to what Saumil and Luke suggested, I just found a few minor things that might need to be changed. We are almost there! Keep up the great work!

2022-04-05 21:08 UTC, tamara-snyder commented on github-actions/trigger-issue/add-preliminary-comment/preliminary-update.md
> +ii. **ETA:**(When do you expect this issue to be completed?)
I think it would look clearer if you added spaces between the `**` and `(` in lines 6-7. So `i. **Availability:**(` would become `i. **Availability:** (`, etc. That way there's a space between the colon and the first word of the instruction.

2022-04-05 21:08 UTC, tamara-snyder commented on github-actions/trigger-issue/add-preliminary-comment/preliminary-update-comment.js
> +      console.log('No need to post comment.')
Is it necessary to have the console.log in line 20? I feel like people won't be looking for it, but maybe that's just me.

2022-04-05 21:08 UTC, tamara-snyder commented on github-actions/trigger-issue/add-preliminary-comment/check-label-preliminary-update.js
> +    else if(existingLabels.includes("role: design" )){
In postComment(), can you please make the spacing after the strings in the parentheses consistent?

2022-04-05 21:08 UTC, tamara-snyder commented on github-actions/trigger-issue/add-preliminary-comment/preliminary-update.md
> +P.S. - You may not take up another issue until this issue gets merged with the main gh-pages (Or closed). Thanks again :)
Can you un-capitalize the `(Or closed)` so that it becomes `(or closed)`?

2022-04-06 14:41 UTC, usaboo commented on github-actions/trigger-issue/add-preliminary-comment/check-label-preliminary-update.js
> +    else if(existingLabels.includes("role: design" )){
Done this Tamara, thanks for catching it.

2022-04-06 14:43 UTC, usaboo commented on github-actions/trigger-issue/add-preliminary-comment/preliminary-update-comment.js
> +      console.log('No need to post comment.')
I think it's more of a debugging thing, it was already there in the sister github action (add-missing-label-to-issues) and I just carried it forward. We could discuss this further :)

2022-04-06 14:44 UTC, usaboo commented on github-actions/trigger-issue/add-preliminary-comment/preliminary-update.md
> +ii. **ETA:**(When do you expect this issue to be completed?)
Made the change Tamara!

2022-04-06 14:44 UTC, usaboo commented on github-actions/trigger-issue/add-preliminary-comment/preliminary-update.md
> +P.S. - You may not take up another issue until this issue gets merged with the main gh-pages (Or closed). Thanks again :)
Made the change :)

2022-04-06 14:46 UTC, usaboo commented on github-actions/trigger-issue/add-preliminary-comment/preliminary-update-comment.js
> +    }
Made this change Saumil :)

2022-04-06 14:53 UTC, usaboo commented on github-actions/trigger-issue/add-preliminary-comment/preliminary-update-comment.js
> +  return commentToPost
I have done this too Saumil :)

2022-04-06 14:56 UTC, usaboo commented on github-actions/trigger-issue/add-preliminary-comment/preliminary-update-comment.js
> +  }
I have a consistent reasoning behind the indentation at this point, maybe I can explain my thought process in the next doubts session? I feel it would make sense after that.

2022-04-06 14:59 UTC, usaboo commented on github-actions/trigger-issue/add-preliminary-comment/check-label-preliminary-update.js
> +
Hi @SAUMILDHANKAR, do you mean line 18 or line 21? I feel line 18 is making things a little clearer to read otherwise one might get confused as to which comment is for which variable(shouldPost or existingLabels). Hope my reasoning makes sense, let me know if I understood.

2022-04-06 15:29 UTC, usaboo commented on github-actions/trigger-issue/add-preliminary-comment/preliminary-update-comment.js
> +    const issueCreator = context.payload.issue.user.login
Hi Saumil, that is indeed the most important catch in my opinion. I am looking into how to modify the code so that the issue assignee's handle comes instead. Will keep you posted.

2022-04-06 15:31 UTC, usaboo commented
Hi @SAUMILDHANKAR, @tamara-snyder and @luke-karis ~ thank you guys so much for consistently reviewing my work. I really appreciate it, I am working on Saumil's catch that the comment is being addressed to the issue creator instead of the issue assignee, will request a re-review once I figure out how to do that!

2022-04-07 02:06 UTC, tamara-snyder commented on github-actions/trigger-issue/add-preliminary-comment/preliminary-update-comment.js
> +      console.log('No need to post comment.')
Oh, fair. I was just wondering. If it's already in another one of the GitHub actions, then I think it makes sense to leave it in here as well.

2022-04-20 14:37 UTC, usaboo commented
Blockers: Hi @tamara-snyder @luke-karis , so the issue is almost done now, except for one thing, as @SAUMILDHANKAR caught this issue -> the comment is being addressed to the issue creator instead of the issue assignee. In  order to try to remedy that on **line 40 in preliminary-update-comment.js** I have changed it to:-
-> const issueAssignee = context.payload.issue.assignee.login
this however does not solve the issue completely, especially when there is more than one assignee already, it addresses the comment to the first assignee on the issue as opposed to the most recent one which is not what we want. Hope you guys can help me address this issue, I am a little out of ideas.

ETA - EOD, Thursday(April 22nd)

2022-04-20 14:54 UTC, tamara-snyder requested changes, later dismissed
Hey @usaboo, I made a comment because I realized there might be a couple more places to address the issue assignee and not the issue creator. I'm going to look into how you can address multiple assignees.

Off the top of my head, it might work to keep a list of assignees and send a comment only to the last one in the list when assignment is triggered.

Edit: I think with the above idea we would also have to handle removing assignees from that list when they un-assign themselves. And then with re-assignment we could just append them to the end.

2022-04-20 14:54 UTC, tamara-snyder commented on github-actions/trigger-issue/add-preliminary-comment/preliminary-update-comment.js
> +  return commentWithIssueCreator
Just noticed this, but I think it would make more sense if lines 49-50 and 52 here also addressed the assignee and not the issue creator. Correct me if I'm wrong.

2022-04-20 14:59 UTC, usaboo commented on github-actions/trigger-issue/add-preliminary-comment/preliminary-update-comment.js
> +  return commentWithIssueCreator
This is only an issue in terms of variable names! The comment is still being addressed to the assignee now as the comment object uses issue assignee now(lines 42 - 47). 

I will change the name of the variable to make it more relevant. Thanks for catching it :)

2022-04-23 06:16 UTC, SAUMILDHANKAR submitted a review, later dismissed
@usaboo Hi Utkarsh, as per our discussion yesterday, I just noticed using GitHub API that assignee and assignees are different fields. Please see: https://api.github.com/repos/usaboo/website/issues/7. So, even though we had usaboo as the last assignee on the issue, the assignee field still had saumildhankar and hence, the error in the comment.
- I like Tamara's idea about keeping a list of assignees and using it to know the latest assignee.
- Additionally, based on my discussion with Jessica, you can also try [Issue Events API](https://docs.github.com/en/rest/issues/events): https://api.github.com/repos/usaboo/website/issues/7/events?per_page=100 or [Timeline Events API](https://docs.github.com/en/rest/issues/timeline): https://api.github.com/repos/usaboo/website/issues/7/timeline?per_page=100 to fetch the latest assignee based on event "assigned" and use that in your comment. 
- Also, Jessica shared a very helpful observation in your preliminary-update.md file, where part of your last line "until this issue gets merged with the main gh-pages" shouldn't be restricted to main gh-pages as this is not valid in case of feature branches. So, either add a generic reference to feature branches or remove branches altogether. I will let you decide on that. 

Thank you for your great work on this issue.

2022-05-05 04:48 UTC, JessicaLucindaCheng commented
@usaboo I saw a "Status: Help Wanted" label. Did you still need help with this pr?

Also, left a Slack message for you about this too.

2022-05-22 23:16 UTC, usaboo commented
Hi @SAUMILDHANKAR @tamara-snyder @luke-karis, I think I have finally fixed the issues with the code. Thank you so much for your patience guys and I am sorry it took so long.

2022-05-24 23:48 UTC, SAUMILDHANKAR commented
Re-review ETA: 5/29
Availability: 1 hr

2022-05-27 12:54 UTC, tamara-snyder commented
Availability: 1 hour
Review ETA: Monday, May 30

2022-05-30 19:15 UTC, SAUMILDHANKAR commented on github-actions/trigger-issue/add-preliminary-comment/check-label-preliminary-update.js
> +
I meant line 21, but I am going to resolve this for now since it is a minor change.

2022-05-30 22:14 UTC, SAUMILDHANKAR reviewed
@usaboo Hi Utkarsh, sorry for the delay in my review and thank you for making great progress on this issue. I understand you have been working on this for quite sometime and your contribution is really commendable. Just ran the tests in my repo and I couldn't find any gaps in the functionality to be implemented, so your PR has my approval. 

Additionally, I noticed that some of the functions such as getTimeline(), obtainLabels() and postComment() are being declared at multiple places in our codebase. It would be more efficient if we could reuse them, for instance by placing them in utils folder and then calling the function where required. We can make changes here (if you want) or have a new refactoring issue to implement this. Will let you and the merge team decide that since I won't be available going forward. Thanks for making it work.

2022-06-01 00:57 UTC, luke-karis commented on github-actions/trigger-issue/add-preliminary-comment/preliminary-update-comment.js
> +  //console.log(arra)
This should be removed (or un commented I guess if you want to keep it)

2022-06-01 01:02 UTC, luke-karis commented on github-actions/trigger-issue/add-preliminary-comment/preliminary-update-comment.js
> +	let arra = []
It seems like you copied this function from add-label.js but I just wanted to note that I really dislike this variable name. For one it is not descriptive and it also is confusing, I'm not sure why the y in array didn't make the cut when everything else did. For now thought I think its fine to leave it as is especially if someone in the future will put this function in a utility class

2022-06-01 01:35 UTC, luke-karis requested changes
Great job sticking with this and making all these changes! The only change I noticed was a log that is commented out but besides that this looks. I also tested creating issues locally in my forked repo and it works really well. This will be an awesome addition once it gets merged in.

2022-06-15 14:11 UTC, usaboo commented
ETA : 06/15/22 EOD
Availability : 1 hour

2022-06-16 05:10 UTC, usaboo commented on github-actions/trigger-issue/add-preliminary-comment/preliminary-update-comment.js
> +	let arra = []
Hi Luke, 
I have made the changes ~ I removed the commented console log and renamed arra to history since it better represents what that variable accomplishes.
Feel free to come up with a better name for the variable though, I'm open to suggestions :)

2022-06-21 02:42 UTC, luke-karis approved these changes
This looks good to me! Thanks so much for working on this!!

2022-06-23 23:53 UTC, tamara-snyder approved these changes
Hi @usaboo, thanks so much for all your hard work on this! All looks good to me. This will be a great addition to our GitHub Actions :)

2022-06-24 00:01 UTC, merged

2022-11-28 02:33 UTC, jdingeman commented
> @usaboo Hi Utkarsh, sorry for the delay in my review and thank you for making great progress on this issue. I understand you have been working on this for quite sometime and your contribution is really commendable. Just ran the tests in my repo and I couldn't find any gaps in the functionality to be implemented, so your PR has my approval.
> 
> Additionally, I noticed that some of the functions such as getTimeline(), obtainLabels() and postComment() are being declared at multiple places in our codebase. It would be more efficient if we could reuse them, for instance by placing them in utils folder and then calling the function where required. We can make changes here (if you want) or have a new refactoring issue to implement this. Will let you and the merge team decide that since I won't be available going forward. Thanks for making it work.

@ExperimentsInHonesty, I just checked the repo and it looks like these functions are still being declared in multiple places, so I think it'd be best that we write a new issue to consolidate these functions in a utils folder like Saumil said. It'll require some investigation across the .js files as there are some functions like obtainLabels() in check-label-preliminary-update.js that does not take a parameter, whereas the obtainLabels(context) in obtain-labels.js does take a parameter despite being essentially the same function. This is plenty of content for a new medium - large issue.