removed card-body and card-width class
hackforla/website pull request #2973
Opened 2022-03-13 03:53 UTC by scarter31191

Fixes #2720

### What changes did you make and why did you make them?

  - Removed unused classes card-body and card-width 
  -
  -

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

Moving files to another directory. No visual changes to the website.

2022-03-13 17:30 UTC, riddle015 commented
- Availability: 2 hours
- Review ETA: Wed, Mar 16 2022

2022-03-13 17:30 UTC, Gorck1416 commented
- Availability: 4 hours
- Review ETA: March 14, 2022 or March 15, 2022

2022-03-15 00:04 UTC, JessicaLucindaCheng requested changes
@scarter31191 Thanks for working on this issue!

- [ ] Please make the changes as requested in my in-line comment.

- [ ] You wrote, "Moving files to another directory. No visual changes to the website." No files were moved for this issue, so I'm confused as to to the line "Moving files to another directory" as the reason for no visual changes. I think the reason for no visual changes would be since the scss classes card-body and card-width never existed, removing those classes from the html would not impact the styling of the page. So, please clarify/change "Moving files to another directory. No visual changes to the website."

- [ ] When you are ready for me to re-review your pull request, please click the following in the Reviewers section on the right:
<img width="243" alt="image" src="https://user-images.githubusercontent.com/31293603/153506185-1cab4d94-853f-49cd-8275-ab0573465b5e.png">

2022-03-15 00:04 UTC, JessicaLucindaCheng commented on _includes/citizen-engagement-cards.html
> +                   <div class="page-card card-primary page-card-lg  program-area" data-dropdown>
I think there are 2 spaces between page-card-lg and program-area. Please remove one of the spaces.

2022-03-15 21:16 UTC, JessicaLucindaCheng approved these changes
@scarter31191 Thanks for making the changes! Looks good to me now.

2022-03-15 21:17 UTC, merged