Update card format 2339
hackforla/website pull request #2977
Opened 2022-03-13 19:55 UTC by Carlos-A-P

Fixes #2339

### What changes did you make and why did you make them?

  - Cards within desktop view of the Wins page match Option A within the [The Wins Page Figma design (within the dark blue border)](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=16207%3A101187)
  - Cards within mobile view of the Wins page match Option B within the [The Wins Page Figma design (within the dark blue border)](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=16207%3A101187)
  - Positioned the "See More" button relative to the card itself rather than the card text

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>
 Desktop View

![desktop-card](https://user-images.githubusercontent.com/85038929/158076574-98baf84b-9fe9-451d-a19b-e8e447a3ed9c.jpg)

Mobile View
![desktop-mobile](https://user-images.githubusercontent.com/85038929/158076577-65624780-2f03-43ec-9e53-54336740d0e0.jpg)

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
Desktop View
![updated-desktop-1](https://user-images.githubusercontent.com/85038929/158076611-54148daa-8ff5-48bf-90ca-1d58bb2beb0b.PNG)

Mobile View
![updated-desktop-mobile-1](https://user-images.githubusercontent.com/85038929/158076617-2e117fd9-6e81-4800-9323-1fa76191c1aa.PNG)
![updated-desktop-mobile-2](https://user-images.githubusercontent.com/85038929/158076619-f12d61a1-f2f6-45c0-b141-f98c4acc0e67.PNG)
</details>

2022-03-15 00:13 UTC, JessicaLucindaCheng commented
@Carlos-A-P I converted your pr to a draft. Once it is complete and your blocker is addressed, you can click "Ready for review":
<img width="686" alt="Screenshot 2022-03-14 171220" src="https://user-images.githubusercontent.com/31293603/158281225-d8511686-0406-4120-96e8-30ad38be83b6.png">

2022-03-15 00:14 UTC, JessicaLucindaCheng commented
Availability: 3 hours
Figuring out blocker ETA: Thu, March 17, 2022

2022-03-23 02:41 UTC, blulady commented
Review ETA: 11 AM 3.22.22
Availability: 4-6 PM Thursday 3.22.22

2022-03-23 02:41 UTC, tamara-snyder commented
Availability: 3 hours
Review ETA: Friday, March 25, 2022

2022-03-24 21:49 UTC, blulady commented
In the linked issue they talk about an arrow that points up or down, depending on if the card is expanded. Is that something that applies in this case? If so, I didn't see it when I pulled the changes and looked at it in the local.
The branch is correct. The linked issue is applicable. The "See More" link has been moved to the correct location. I need more help checking to see if the cards on the desktop matches Option A and the cards on the mobile match Option B. But it looks pretty good.

2022-03-26 14:19 UTC, tamara-snyder requested changes
Hi Carlos, really great work on this issue. I can tell you've put a lot of time and thought into this.
 
The changes match the Figma design for desktop and mobile devices really well, with one exception: Galaxy Fold. Since it has a much smaller width than most devices (280px), text is spilling off the cards and the LinkedIn and GitHub icons in the top right of the cards have inconsistent sizing. Additionally, when there is too much text in a card, the arrow button used to expand the card doesn't work (see Bonnie's win card, for example).

#### Spilling off the card on Galaxy Fold:
![Screen Shot 2022-03-25 at 2 15 05 PM](https://user-images.githubusercontent.com/57715733/160243387-e2769648-5ba1-4a63-ae37-2f147f4d2390.png)
#### Various Sizes of LinkedIn/GitHub icons on Galaxy Fold:
![Screen Shot 2022-03-25 at 2 16 02 PM](https://user-images.githubusercontent.com/57715733/160243458-c009029f-fd2c-48c6-8074-da9cb79a8a96.png)
![Screen Shot 2022-03-25 at 2 16 41 PM](https://user-images.githubusercontent.com/57715733/160243459-60c929d3-1291-42ae-a587-28aec29b2170.png)
![Screen Shot 2022-03-25 at 2 15 53 PM](https://user-images.githubusercontent.com/57715733/160243461-9b9d4a8e-6038-4a48-a35d-0bf9ee5117f7.png)
![Screen Shot 2022-03-25 at 2 18 18 PM](https://user-images.githubusercontent.com/57715733/160243465-d73fd6ca-e953-4755-a061-9a63b335f999.png)


I'm not too sure what could fix this at the moment, but it may just be that we need a new media query for extremely small screens like the Galaxy Fold. I'm going to look into it more.

Other than that, I've left some small comments, mostly regarding formatting. Again, well done on a challenging issue! Hopefully this fix won't be too complex.

2022-03-26 14:19 UTC, tamara-snyder commented on _sass/components/_wins-page.scss
> +	// &.relative {
Please remove all commented code.

2022-03-26 14:19 UTC, tamara-snyder commented on _sass/components/_wins-page.scss
> +    margin: 1em 0 0;
In [CSS shorthand](https://developer.mozilla.org/en-US/docs/Web/CSS/Shorthand_properties#:~:text=When%20three%20values%20are%20specified,in%20that%20order%20(clockwise).), three values in a statement means that the first value applies to the top, the second to the left and right, and the third to the bottom. Please remove the redundant `margin-top` in line 70.

2022-03-26 14:19 UTC, tamara-snyder commented on _sass/components/_wins-page.scss
> +            transform: rotate(0deg);
Please remove the empty line before the media query and add a space between the selector and curly brace in line 91.

2022-03-26 14:19 UTC, tamara-snyder commented on _sass/components/_wins-page.scss
> +            display: block;
Add a space between `.wins-card-overview` selector and curly brace

2022-03-26 14:19 UTC, tamara-snyder commented on assets/js/wins.js
> +	}
This looks fine on GitHub, but on my local branch, this whole block of code within `toggleSeeMoreLess(id)` is unindented. If that's the case on your branch as well, could you please select it all and indent it once?

2022-03-26 14:19 UTC, tamara-snyder commented on assets/js/wins.js
> +		for(let i = 0; i < span.length; i++ ){
Please check through your code and fix any inconsistencies in spacing between statements and curly braces or parentheses, e.g. `function foo(){` or `}else {` or `if(` and add a space where necessary.

2022-03-26 14:19 UTC, tamara-snyder commented on assets/js/wins.js
> +	  if (parent.classList.contains('expanded') && screenWidth > 960) {
Unindent the if statement in line 391

2022-03-27 21:11 UTC, Carlos-A-P commented
@tamara-snyder, thanks for reviewing my PR! I'll finish making those changes. I also noticed the problem with the text spilling at 280px, and it was like that in the original code. I wondered if we should create another issue to fix that since it wasn't part of the original issue, or should I try and fix that up as well?

2022-03-27 23:58 UTC, Carlos-A-P commented on assets/js/wins.js
> +	}
This block was originally indented in my local branch before I created the PR, and it shows up as indented? Not sure why it wouldn't show up as indented.

2022-03-28 15:32 UTC, tamara-snyder commented
@Carlos-A-P I think creating a new issue to resolve that would be a good idea since it was already a problem before. Could you please still investigate why the cards with more text (like Bonnie's) can't expand? Thank you!

2022-03-30 01:35 UTC, Carlos-A-P commented
@tamara-snyder The content to the right of the profile pic is grouped under the ".wins-card-top" div element. We can probably add a breakpoint and make the ".wins-card-top" elements wrap, then space some of the elements out a bit

2022-03-30 02:55 UTC, tamara-snyder commented
@Carlos-A-P I really like the look of that and it seems like a sensible solution! We may want to clear that with the design team before implementing it, though. Perhaps drop a message in the Slack site channel so that they can see it before our next all-team meeting.

2022-03-30 03:01 UTC, Carlos-A-P commented
> @Carlos-A-P I really like the look of that and it seems like a sensible solution! We may want to clear that with the design team before implementing it, though. Perhaps drop a message in the Slack site channel so that they can see it before our next all-team meeting.

@tamara-snyder Awesome! I will send over a message and bring it up next meeting.

2022-04-05 18:01 UTC, tamara-snyder commented
@Carlos-A-P @phuonguvan Have we come to a decision about the Galaxy Fold fix yet? If not, we can make sure it's on the agenda for the next Sunday meeting.

Also, I'm curious if it will resolve the not being able to easily expand certain cards due to there being overlapping elements, as shown in this gif:
![Recording 2022-04-05 at 13 53 25](https://user-images.githubusercontent.com/57715733/161819915-645d0eb2-2ada-40b5-bd09-7d609a33b26e.gif)

I'm a bit hesitant to approve this until we know there's another issue out there that will fix this. Thanks!

2022-04-05 18:21 UTC, Carlos-A-P commented
> @Carlos-A-P @phuonguvan Have we come to a decision about the Galaxy Fold fix yet? If not, we can make sure it's on the agenda for the next Sunday meeting.

@tamara-snyder I haven't heard back yet, but I'll reach out on slack later today to see if there's an update. If the icons overlap the button, I can also add a media query and add space as a part of this ticket.

2022-04-05 18:41 UTC, tamara-snyder commented
@Carlos-A-P Yes, adding some extra space would be fantastic. Thanks so much!

2022-04-06 02:14 UTC, kathrynsilvaconway commented
Availabilty: 1 hour
ETA: End of the day on 4/10

2022-04-07 20:42 UTC, ExperimentsInHonesty commented
@Carlos-A-P @JessicaLucindaCheng @tamara-snyder Re the design problem with the Galaxy fold: It sounds like we have a few outstanding issues.  We don't want to hold up fixes for one thing, while trying to solve something else that could be moved to another issue.  It's unclear from the notes that we read if we need to make a decision about the Galaxy display on this issue, or it can wait for another.  Please advise.

2022-04-08 12:17 UTC, tamara-snyder commented
@ExperimentsInHonesty I wanted to get an idea of what the design fix could be since the site is broken on Galaxy Fold, but I think it makes sense to create a new issue for this given that it was already somewhat broken before and it will be at least the size of a small issue. My biggest concern before merging here was that certain elements were overlapping and couldn't be interacted with easily, but I think that can be resolved in the new issue as well.

Otherwise, everything @Carlos-A-P has done looks great! We probably just need a special media query in order for the wins cards to work on Galaxy Fold.

I can approve the changes for this and leave the rest for another issue.

2022-04-08 17:05 UTC, kathrynsilvaconway approved these changes
@Carlos-A-P REally nice work updating the wins cards. I can see that you have implemented the design changes from Figma, and everything is displaying correctly. 

I notice there is still some spill over when viewing on Galaxy Fold (I see it on Boonie's card), but  I understand that to be a larger problem that is outside the scope of this issue, So I am approving these changes as they are. 

 I can see you putl some real effort into this, and it is much appreaciated.

2022-04-08 19:09 UTC, tamara-snyder approved these changes
@Carlos-A-P great work on this and thank you again for making the requested changes! All looks good to me. Galaxy Fold to be continued...

2022-04-08 19:12 UTC, merged

2022-04-08 22:52 UTC, JessicaLucindaCheng commented
@tamara-snyder @Carlos-A-P Can you please follow up with Design with this problem at Sunday All Team meeting? If Design gives the okay to proceed, please make an issue for the Galaxy Fold problem.

2022-04-10 17:40 UTC, ExperimentsInHonesty commented
@tamara-snyder or @Carlos-A-P Product has decided that we need to investigate if the Galaxy fold problem needs to be handled by design. We will make that decision by looking into how many people have used that device when visiting our site.  Can you make an issue for product to review necessity?

2022-04-10 18:20 UTC, JessicaLucindaCheng commented
@tamara-snyder @Carlos-A-P
Some notes: 
The issue is we need to figure out if it makes sense to accommodate the Galaxy Fold device. This is a feasibility review. Action Items to include, but not limited to:
- Check in with product how many people are using this device.
- Design check how many pages they would need to design for the Galaxy Fold.