Change text size for getting started page 2656
hackforla/website pull request #2988
Opened 2022-03-18 13:11 UTC by A-BMT02

Changed text size for Getting Started Page

  - Added "paragraph2" class to Getting Started page as requested
  - Removed 3 lines of code form "header-p" class as it overlaps with the new "paragraph2" class added

2022-03-20 16:48 UTC, SAUMILDHANKAR commented
@A-BMT02 Just want to share the following points with you regarding the review process and some other processes that we are currently following in our team:
- I have removed the reviewers from this PR as currently we assign reviewers during the team meetings. Requesting to not assign reviewers yourself since they may not be available or part of our team and doing so may also prevent other team members from picking up this PR for review.
- Also, requesting you to review some of the PRs as well while you are waiting for yours to be reviewed.
- Please add Fixes #issuenumber in your top comment as well as a note about if before and after images are required or not. Adding following two links for more information: [Contributing guideline for adding issue number to your PR](https://github.com/hackforla/website/blob/2e3c45fede99e61f479548ccca3f0dda83e351db/CONTRIBUTING.md#ii-complete-pull-request-2-add-issue-number-to-the-pull-request) and [note about adding images](https://github.com/hackforla/website/blob/2e3c45fede99e61f479548ccca3f0dda83e351db/CONTRIBUTING.md#iv-complete-pull-request-4-include-images-if-available)
- We are now requesting all website team members to attend at least one meeting in a week (Tuesday, Thursday or Sunday) as we strive to replicate a professional working environment within our team amongst other things. Therefore, request you to let us know which of the weekly meetings would be suitable for you based on availability. We have decided to make an exception for this requirement only on a case-by-case basis.

Please feel free to reach out to me through slack or leave a comment and @ mention my GitHub username for more information. Thank you.

2022-03-20 17:17 UTC, SAUMILDHANKAR commented
Review ETA: End of day 3/21/22
Availability: Monday 5-6 PM Pacific Time

2022-03-20 17:20 UTC, frankstepanski commented
Review ETA: End of day 3/21/22
Availability: Monday evening EST

2022-03-20 19:34 UTC, A-BMT02 commented
@SAUMILDHANKAR Thank you for the update 
Noted and appreciated

As for the meetings , i will be attending the ones on Sundays

2022-03-20 19:37 UTC, A-BMT02 commented
@SAUMILDHANKAR Also,  what is the process for reviewing a pull request ? 

Do i have to be assigned a pull request to review IN A MEETING?

2022-03-22 02:12 UTC, frankstepanski submitted a review, later dismissed
Great job @A-BMT02 adding the paragraph2 class and removing the header-p CSS class.
Tested the layout and displays as expected.

2022-03-22 18:06 UTC, tamara-snyder commented
@A-BMT02 You may self-assign a pull request at any time, not just at the meetings. Here's a link to Hack for LA's guide on [How to Review Pull Requests](https://github.com/hackforla/website/wiki/How-to-Review-Pull-Requests), which should tell you all you need to know.

If you have any questions, feel free to drop a message in the [hfla-site-pr channel](https://hackforla.slack.com/archives/C025ERFDM4Y).

2022-03-22 21:53 UTC, A-BMT02 commented
Thank you @tamara-snyder

2022-03-23 00:26 UTC, SAUMILDHANKAR commented on _sass/components/_getting-started-page.scss
>      font-size: 18px;
Please consider if this font-size would interfere with paragraph2 class in mobile view.

2022-03-23 00:28 UTC, SAUMILDHANKAR requested changes
@A-BMT02 Great work in adding the paragraph2 class and making changes to .header-p class. Requesting to please add Fixes #issuenumber in your top comment as well as a note about if before and after images are required or not. Refer to the following two links for more information: [Contributing guideline for adding issue number to your PR](https://github.com/hackforla/website/blob/2e3c45fede99e61f479548ccca3f0dda83e351db/CONTRIBUTING.md#ii-complete-pull-request-2-add-issue-number-to-the-pull-request) and [note about adding images](https://github.com/hackforla/website/blob/2e3c45fede99e61f479548ccca3f0dda83e351db/CONTRIBUTING.md#iv-complete-pull-request-4-include-images-if-available)

2022-03-23 00:28 UTC, SAUMILDHANKAR commented on _sass/components/_getting-started-page.scss
>      font-size: 18px;
Please consider if this font size would interfere with paragraph2 class in mobile view.

2022-03-23 16:04 UTC, A-BMT02 commented on _sass/components/_getting-started-page.scss
>      font-size: 18px;
@SAUMILDHANKAR You are right , the font-size in the media is redundant 
I removed it

2022-03-23 16:07 UTC, A-BMT02 commented
@SAUMILDHANKAR Thank you for the review
Made the necessary changes

2022-03-23 21:47 UTC, SAUMILDHANKAR commented
Re-review ETA: End of day 3/24/22
Availability: Thursday 4-5 PM Pacific Time

2022-03-25 21:41 UTC, SAUMILDHANKAR commented
Revised Re-review ETA: End of day 3/25/22
Availability: Friday 7-8 PM Pacific Time
@A-BMT02 I was not able to finish my review yesterday, but I plan to do it today. Sorry for the delay. Thak you.

2022-03-25 21:56 UTC, A-BMT02 commented
@SAUMILDHANKAR No problem

2022-03-26 07:31 UTC, SAUMILDHANKAR requested changes
@A-BMT02 Thanks a lot for removing the font-size for mobile view. Request you to also change your initial comment about "removed 3 lines of code from header-p" to "removed 4 lines of code from header-p" and include the before and after images as well. I understand that changes are hardly noticeable, but it would be easier for QA and would be consistent with the process that we follow. Really appreciate your good work on this issue. Thank you.

2022-03-26 20:26 UTC, A-BMT02 commented
@SAUMILDHANKAR 
Updated my initial comment
Thanks for the review , i'm loving it!

2022-03-29 01:33 UTC, kathrynsilvaconway commented
Review ETA: 10AM EST on 3/29/2022
Availability: Tuesday Morning EST

2022-03-29 13:56 UTC, kathrynsilvaconway commented
Update on availability:

Review ETA: 10PM EST on 3/29/2022
Availability: Tuesday Afternoon/Evening EST

I am still working out my PR review skills. It took me a little longer than I expected to view all the changes. I will write my review and have it up before the meeting tonight.

2022-03-29 19:35 UTC, A-BMT02 commented
@kathrynsilvaconway Thats totally ok , i'm also working on my first pull request review too
Take your time

2022-03-29 21:45 UTC, SAUMILDHANKAR approved these changes
@A-BMT02 Thanks for making the changes. Looks good in my environment. I will wait for Kathryn's review. Good job!

2022-03-29 23:17 UTC, kathrynsilvaconway approved these changes
Nice work adjusting the paragraph on the Getting Started page, @A-BMT02. I see that the 'paragraph2' tag has been added and that you have removed the lines from the .header-p class that were redundant. The page looks good in all the mobile checks as well.

2022-03-29 23:22 UTC, merged

2022-03-30 20:20 UTC, A-BMT02 commented
Thank you @kathrynsilvaconway