Applied "title3" classes to headings, bug fix changed img src path.
hackforla/website pull request #3008
Opened 2022-03-24 19:37 UTC by RyanCahela

Fixes #2089

### What changes did you make and why did you make them?

  - changed the 'day-heading' class to 'title3' utility class to decouple the font size from h3 html tag.
  - changed 'h3' tags to 'h2' because there were no h2 elements on the page and these headings mark the second most important pieces of information in the document.
  - changed hero image src path to begin with "../" instead of "./" because it wasn't loading with "./" prefix. 

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

![Before-Full-iPad](https://user-images.githubusercontent.com/6194542/159995625-e3c7eb86-e1af-4c19-8dc3-c349323e6010.png)
![Before-Full-iPhone-X](https://user-images.githubusercontent.com/6194542/159995626-14a2c15b-802a-41b6-9108-aaa4f712c3f9.png)
![Before-Full-Generic-Laptop](https://user-images.githubusercontent.com/6194542/159995618-b2267e92-7a27-4703-8d78-6d2dded374d1.png)
</details>

<details>
<summary>Visuals after changes are applied</summary>
  
![image](Paste_Your_Image_Link_Here_After_Attaching_Files)
![After-Full-Generic-Laptop](https://user-images.githubusercontent.com/6194542/159995811-ea677faa-ee77-4ee2-9a95-095b4825d289.png)
![After-Full-iPad](https://user-images.githubusercontent.com/6194542/159995821-00fb0fde-7c8d-4879-aec6-f1fb3f5e6ca4.png)
![After-Full-iPhone-X](https://user-images.githubusercontent.com/6194542/159995822-b978ee51-8140-45a0-a451-35bea518245a.png)

</details>

2022-03-25 03:53 UTC, tamara-snyder commented
Availability: 1 hour
Review ETA: Within the next hour

2022-03-25 04:15 UTC, tamara-snyder commented
Hi Ryan, great work on this! I can see you've changed the class of all the weekdays to ".title3" and the headings to h2 tags, which I think makes more sense in this context. The changes are visible on the page and everything still looks good in both mobile and desktop. Well done!

2022-03-25 04:21 UTC, tamara-snyder submitted a review, later dismissed
Hi Ryan, great work on this! I can see that you've changed the weekdays to exist within h2 tags with a class of ".title3", which I think makes more sense in this context. The changes are visible on the page and everything still looks good in both mobile and desktop. Well done!

Also, thank you for fixing the image source. Even though it's not part of the issue, I think it's worth leaving that in. I'll wait for someone else to review it to get a second opinion before merging.

2022-03-26 06:49 UTC, SAUMILDHANKAR requested changes
@RyanCahela Hi Ryan, great job in adding the title3 class and changing h3 tags to h2, however, not sure if we should remove day-header class, since it changes the margin and makes the page look slightly different. I would recommend keeping it for now. 
Also, not sure if we should change the path in this issue, it might be confusing for QA and there might already be a pending issue for it. I would encourage to look if there is already an issue to fix this and if not create one. Thanks again for your detailed analysis. Please request a re-review once you have made changes or let me know if you have questions.

2022-03-27 16:19 UTC, kathrynsilvaconway commented
ETA: Within one hour.
Availability:
One Hour

2022-03-27 19:22 UTC, RyanCahela commented
@SAUMILDHANKAR I've added the 'day-header' class back to give the headings some margin. I left the image path bug fix in as per our discussion this morning. 

Let me know if I need to change anything else.

2022-03-27 20:41 UTC, kathrynsilvaconway approved these changes
Nice work updating @RyanCahela the heading tags to h2 from h3. I think this improves the hierarchy and makes the flow of the content a little clearer. Adding the '.title3' class to these tags improves clarity as well.

2022-03-29 07:01 UTC, SAUMILDHANKAR requested changes, later dismissed
@RyanCahela Thanks for making the changes as per team discussion. Code looks all good only requesting minor changes in your initial comment. I understand the "visuals after changes are applied" in your initial comment, would change because of this so requesting to update them as well. Also, it would be really helpful if we could update the initial post where it says changed day header class to title3. Really appreciate your insights on this issue as well as quick turnaround.

2022-03-30 22:29 UTC, RyanCahela commented
@SAUMILDHANKAR I updated the "after changes" screenshots and changed the first bullet point to reflect adding the "title3" class instead of replacing the "day-header" class. 

Let me know if I need to fix anything else.

2022-03-31 02:04 UTC, JessicaLucindaCheng approved these changes
@RyanCahela Thanks for making the requested changes. It looks good to me.

2022-03-31 02:05 UTC, merged