Add so go survey credit page 3022
hackforla/website pull request #3043
Opened 2022-04-11 21:28 UTC by Jaretzbalba

Fixes #3022

### What changes did you make and why did you make them ?

  - Update header text with new paragraph for Credit page
  - Create Tools section and style based off Figma design for desktop and mobile versions
  - Add headers to "iconography & Imagery" and "Tools" section

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

![credit page desktop BEFORE](https://user-images.githubusercontent.com/93153059/162836336-1d96e143-8b92-48fa-92ca-1ddc4fbb7326.png)
![credit page mobile BEFORE](https://user-images.githubusercontent.com/93153059/162836347-54142dff-4fe6-445c-940e-55dcf15b47bb.png)

</details>

<details>
<summary>Visuals after changes are applied</summary>
 
![credit page desktop](https://user-images.githubusercontent.com/93153059/162836052-443369c7-664c-4697-9d00-34a2766eeaa1.png)
![credit page desktop bottom](https://user-images.githubusercontent.com/93153059/162836075-5ebe2d15-de1c-4028-92d7-9b64eef1a4d7.png)
![credit page mobile](https://user-images.githubusercontent.com/93153059/162836089-7204c644-ced6-4937-8a64-efd
![credit page mobile bottom](https://user-images.githubusercontent.com/93153059/162836096-a6cc5c11-0bd2-4831-b315-4f4bff38aa04.png)
87f95d3a7.png) 

</details>

2022-04-11 22:06 UTC, kathrynsilvaconway commented
Availability: 1 hour.
ETA: By the end of the day on 4/12.

2022-04-12 03:59 UTC, kathrynsilvaconway requested changes
Nice woark updating the credits page, @Jaretzbalba. I see that you have made every update listed to the paragraph and also added the tools section. Two things I see:
1. The alt text in line 82 should be changed to an empty alt tag(i.e. alt = "").
![image](https://user-images.githubusercontent.com/81049661/162876889-07e56d56-d2f6-4bf1-95eb-ae45adae8160.png)
2. The icons in the Iconography & Imagery section appear in a different order than they do on the live page. They seem to be alphabetized? Did you mean to make this change? I don't see any reference to a change like this in the original issue.

Otherwise, everything looks really good.

2022-04-12 16:11 UTC, Jaretzbalba commented
@kathrynsilvaconway I left the alt tag as is because that code is just pulling information from the .yml file which states that the alt tag is empty. I figured it would be best to leave the code just in case future icons may need an alt tag. I can bring up this topic at tonights meeting to see what people think. As for the icon order, I looked through my code and even tried reverting it back but the order was still changed. This would also be a good question to bring up during the meeting. Thank you for all the input!

2022-04-13 03:08 UTC, Jaretzbalba commented
On Tuesday Dev Meeting 4/12/22 @JessicaLucindaCheng informed us about the ongoing issue of the credit icons being ordered in a different pattern compared to when it becomes live. This will be addressed in a later issue. Also talked about the HTML file and changing the code for the icons to empty alt tags since it would be redundant. All previous icon alt tags will be changed in a later issue as well.

2022-04-13 03:28 UTC, kathrynsilvaconway approved these changes, later dismissed
Thanks for clearing up those two issues, @Jaretzbalba. Nice work overall.

2022-04-13 19:12 UTC, answebdev commented
Review ETA: 4/13/2022 (end of day)
Availability: 2 hours

2022-04-13 19:23 UTC, blulady approved these changes, later dismissed
Branches look good. It is linked to the correct issue. The image has been renamed to so-go-survey and placed in the Add the image to the /assets/images/credits directory. A new folder was created in _data/internal/credits named tools and it contains the so-go-survey.yml file. The .yml file looks a little grumpy about there not being a newline at the end and the` alt: '' `on line 9 isn't in the original text from the linked issue but it looks like it was requested later on.
The HTML has the requested changes in the paragraph. There is the correct if statement,  appropriately indented following `{%- for item in site.data.internal.credits -%} `. At the bottom of the page there is a new section for tools with an h2 header. The alt text for the SoGoSurvey logo image is alt="". The SCSS has been altered. I am uncertain if the .credits-tool and .credits-heading are existing classes/styling in our codebase but the page looks great in mobile, tablet, and desktop views.

2022-04-13 22:24 UTC, JessicaLucindaCheng commented on pages/credits.html
> +      <h2 class="title2 credits-heading ">Iconography & Imagery</h2>
Remove the extra space after `credits-heading

2022-04-13 22:26 UTC, JessicaLucindaCheng commented on pages/credits.html
> +    <div class='page-card card-primary page-card-lg page-card--credits'>
To be consistent with the rest of the code, please use double quotation marks instead of single quotation marks, so the result is `<div class="page-card card-primary page-card-lg page-card--credits">`

2022-04-13 22:27 UTC, JessicaLucindaCheng commented on _data/internal/credits/tools/so-go-survey.yml
> +alt: ''
These lines are not necessary because you added `alt=""` in the HTML and will show as that when the page is generated. So, please remove these lines.

2022-04-13 22:34 UTC, JessicaLucindaCheng requested changes
@Jaretzbalba Thanks for adding the `alt=""` for the `img` tag for the Tools section. I made some in-line comments, so please make those changes.

2022-04-14 02:14 UTC, Jaretzbalba commented
@JessicaLucindaCheng I accidentally pushed the wrong code. What would be the best method to undo this commit and push the correct code? Sorry about this mistake!

2022-04-14 17:32 UTC, blulady commented
> @JessicaLucindaCheng I accidentally pushed the wrong code. What would be the best method to undo this commit and push the correct code? Sorry about this mistake!

can you push the correct code?

2022-04-14 23:08 UTC, JessicaLucindaCheng commented
@Jaretzbalba 
> @JessicaLucindaCheng I accidentally pushed the wrong code. What would be the best method to undo this commit and push the correct code? Sorry about this mistake!

It looks like you already did a git revert, which was what I was going to suggest. Did that fix your problem?

2022-04-14 23:10 UTC, Jaretzbalba commented
@JessicaLucindaCheng Yes, the git revert fixed my problem and I was able to submit the correct code afterward.

2022-04-17 16:58 UTC, JessicaLucindaCheng commented
- Availability: 3 hours
- Review ETA: Tue, Apr 19, 2022

2022-04-18 01:19 UTC, answebdev submitted a review, later dismissed
@Jaretzbalba Thank you for submitting this PR and working on this issue. I can see that you have updated the header text with new paragraph for the Credit page, created a Tools section and style based off the Figma design for desktop and mobile versions, and added the headers to the "Iconography & Imagery" and "Tools" section. I can see these in the browser, and the changes also look good in mobile, tablet, and desktop views. I looked at the files and the code and saw that you have addressed the items in the Action Items. I can also see that you have addressed Jessica's in-line comments, such as removing an extra space in the `h2` class name in `pages/credits.html`, and by updating to the double quotation marks for consistency in the `div` class name in `pages/credits.html`. Great job with this!

2022-04-19 19:00 UTC, blulady submitted a review, later dismissed
In addition to the previous requests that you already met, it looks like you made Jessica's requested changes as well. That means you eliminated the alt="" on line 9 in the .yml file, removed the extra space after credits-heading on line 23 in the credits.html and changed the quotation marks to double quotation on line 72 in credits.html. It still looks great in mobile, tablet and desktop

2022-04-19 21:45 UTC, JessicaLucindaCheng requested changes
@Jaretzbalba Good work on the issue and for making my requested changes! In addition to my new in-line change requests,
-  [ ] I see the credits for the "Iconography & Imagery" section is cutoff on the right side in tablet view when I view your changes using Docker. How the credits look in the "Iconography & Imagery" section should be the same as on the current website.
    <details>
      <summary>Click here to see tablet view with Credits cutoff on the right</summary>
      
      ![credits-table-cutoff](https://user-images.githubusercontent.com/31293603/164102849-95785b05-6208-4cad-83a0-5b12a585ed71.png)
    
    </details>
    
    <details>
      <summary>Click here to see current Credits page in tablet view</summary>
      
      ![credit-current-tablet](https://user-images.githubusercontent.com/31293603/164103338-61bd9bb1-7af5-4c98-953e-ae5e76f3d4e2.png)
      
    </details>

- [ ] For mobile, please add a little more spacing on the left side of the SoGoSurvey credit.

  <details>
    <summary>Click here to see screenshot of SoGoSurvey credit in mobile with spacing indicators</summary>
    
    <img width="335" alt="more-margin-for-so-go-survey-credit" src="https://user-images.githubusercontent.com/31293603/164106383-9197eb0f-77fb-47dc-84e7-4d40445d9f45.png">
    
  </details>
  
Also, in the future, you may want to use [GoFullPage]( https://chrome.google.com/webstore/detail/gofullpage-full-page-scre/fdpohaocaechififmbbbbbknoalclacl?hl=en) if you want to take a screenshot of the full webpage.

2022-04-19 21:45 UTC, JessicaLucindaCheng commented on _data/internal/credits/tools/so-go-survey.yml
> +    project-name: Design System's Team
There is suppose to be dash here, so that it is
```
used-by:
    # Name of a project team
  - project-name: Design System's Team
    # Link to the project team's page
    project-link: https://www.hackforla.org/projects/design-systems
```
because we want to be able to add other project teams later. After making the change, you have to change the code in `pages/credits.html` too so it will display the team and link to its page.

For an example of something similar, see the "leadership" section used in [gh-pages/_projects/website.md](https://github.com/hackforla/website/blob/gh-pages/_projects/website.md?plain=1).

2022-04-19 21:45 UTC, JessicaLucindaCheng commented on pages/credits.html
> +                    <!-- originally class="project-card-inner" -->
To make it easier for developers to read
- [x] Please remove 2 spaces before  `<li>`
- [x] Please also remove 2 spaces before `<!--`

2022-04-19 21:45 UTC, JessicaLucindaCheng commented on _sass/components/_credit-items.scss
> +   font-size: 20px;
To make the indentation consistent,
- [ ] Please add another space before `padding-left: 5px`
- [ ] Please add another space before `font-size: 20px`

2022-04-20 23:17 UTC, JessicaLucindaCheng commented
Availability: 3 hours
Review ETA: Thu, Apr 21, 2022

2022-04-23 02:04 UTC, JessicaLucindaCheng requested changes
@Jaretzbalba Good job fixing the credits being cut off in tablet view and adding more spacing on the right for the Tools credits. In addition to my in-line comment for change, please do the following:
- [ ] For the field "By:", the link for the Design System's Team is no longer showing because of adding "-" to the yml. You will need to change some of the Liquid template language code in pages/credits.html for it to show.
  <details>
    <summary>Click here to see screenshot of Design System's Team link missing</summary>
    <img width="200" alt="no-link-to-Design-System-team" src="https://user-images.githubusercontent.com/31293603/164862782-f4c3965b-b41d-4cf4-81d4-2ad4306a5b02.png">
  </details>

2022-04-23 02:04 UTC, JessicaLucindaCheng commented on pages/credits.html
> +                <!-- originally class="project-card-inner" -->
Sorry, I wasn't clear before when I said to remove two spaces and now it's not indented enough.
- [ ] On line 78, please indent `<li>` once so it is aligned with its closing tag `</li>` on line 113
- [ ] On line 79, please indent `<!--` once so it is aligned with the beginning of the `<div` tag on line 80

2022-04-23 02:04 UTC, JessicaLucindaCheng commented on pages/credits.html
> +                          <a href="{{item[1].provider-link}}">{{ item[1].tool-provider}}</a>
Add an indent before `<a` in line 105

2022-04-23 02:04 UTC, JessicaLucindaCheng commented on pages/credits.html
> +                          {{ item[1].provider }}
Add an indent before `{{item[1]` in line 107

2022-04-23 02:04 UTC, JessicaLucindaCheng commented on pages/credits.html
> +                        <strong>Used in: </strong>
Add an indent before `<strong>` on line 87

2022-04-23 02:04 UTC, JessicaLucindaCheng commented on pages/credits.html
> +                        <a href="{{item[1].used-by.project-link}}">{{ item[1].used-by.project-name}}</a>
Add an indent before `<a` on line 95

2022-04-23 02:04 UTC, JessicaLucindaCheng commented on pages/credits.html
> +                        {{ item[1].used-by }}
Add an indent before `{{ item[1]` on line 97

2022-04-23 02:04 UTC, JessicaLucindaCheng commented on pages/credits.html
> +                      </p>
Add another indent for lines 92-99. The reason is it is inside the if block.

2022-04-23 02:04 UTC, JessicaLucindaCheng commented on pages/credits.html
> +                          {{ item[1].provider }}
Also, for line 107, I think it should be `{{ item[1].tool-provider }}` in order for the tool-provider to show without a link

2022-04-25 16:01 UTC, Jaretzbalba commented on pages/credits.html
> +                          {{ item[1].provider }}
@JessicaLucindaCheng I was basing it off the Figma design for this page which shows the tool-provider as a link. Should I change it to show it without a link?

2022-04-25 16:33 UTC, Jaretzbalba commented on pages/credits.html
> +                          {{ item[1].provider }}
@JessicaLucindaCheng Nvm I see. This is so that it'll still show the tool-provider even if there isn't a link provided.

2022-04-26 17:51 UTC, blulady approved these changes
Looks like the changes requested have been made. Great Job!!
The indent on line 78 now matches the indent on line 113. The <strong> div on line 87 is now inside the <p> div. The <a> div is now indented past the if statement. The {{ item[1] }} is tucked with in the else statement. Lines 92 -101 are now indented inside the if statement. The <a> link is now tucked inside the if statement.  The {{ item[1] }} is now indented inside the else statement.

2022-04-28 02:11 UTC, JessicaLucindaCheng commented
- Availability: 3 hours
- Review ETA: Thu, Apr 28

2022-05-01 07:03 UTC, JessicaLucindaCheng approved these changes
@Jaretzbalba Thank you for all your hard work on this issue and making all the requested changes. The changes you made to the Credits page looks good to me now.

2022-05-01 07:03 UTC, merged

2022-05-01 07:04 UTC, JessicaLucindaCheng commented
@Jaretzbalba Since this is now merged, please complete the last action item in your issue https://github.com/hackforla/website/issues/3022