Changed the About
hackforla/website pull request #3057
Opened 2022-04-15 19:25 UTC by KazushiR

Fixes #3023

### What changes did you make and why did you make them ?

  - Changed the about section so when you go to "Get in touch", it will go to the "get in touch" section in the home page
  -
  -

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

![image](https://user-images.githubusercontent.com/38971729/163623534-b24e2aaf-4e05-41af-8c42-da0c0c9bd96d.png)

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
![image](https://user-images.githubusercontent.com/38971729/163623572-412fa5ea-9c96-4888-aaf2-17f24ccf1f5d.png)

</details>

2022-04-15 22:33 UTC, answebdev commented
Review ETA: 4/15/2022 (end of day)
Availability: 2 hours

2022-04-15 22:57 UTC, answebdev approved these changes
@KazushiR Thank you for submitting your PR. For this issue, line 1 in `_includes/forms/contact-us.html` needed to be updated so that it becomes

```
<a class="anchor" id="get-in-touch"></a>
<section class="home--contact home--section">
```
so that one is able to go directly to the Get In Touch section without scrolling by adding this anchor. I can see that you did this, and when I checked in the browser, going to `localhost:4000/#get-in-touch` does indeed jump to the Get In Touch section on the homepage, as in your screenshot. Great job with that!

I was wondering though, @SAUMILDHANKAR or @JessicaLucindaCheng : Everything was done correctly here according to the original issue, but isn't it the case with anchors that when you jump to the section, the section that you go to should be up at the top of the page? In other words, when you go to `localhost:4000/#get-in-touch`, although it jumps to the Get In Touch section, the "Volunteer with us" card is at the top. Shouldn't it look something like this, where the Get In Touch section is up top (in my screenshot here, I had to manually scroll up so that the "Get in touch..." card sits up top):

<details>
  <summary>"Get in touch with us" section (Note: I scrolled up manually here)</summary>

![git](https://user-images.githubusercontent.com/36783010/163650329-0fbc6520-e483-4c59-9169-e0c9abf6ded5.jpg)

</details>

Anyway, everything was done according to the issue, but I just wanted to check and ask about this. Maybe that's just how anchors work, or maybe it's because of manually typing it in the URL for now.

2022-04-15 23:39 UTC, KazushiR commented
> @KazushiR Thank you for submitting your PR. For this issue, line 1 in `_includes/forms/contact-us.html` needed to be updated so that it becomes
> 
> 
> 
> ```
> 
> <a class="anchor" id="get-in-touch"></a>
> 
> <section class="home--contact home--section">
> 
> ```
> 
> so that one is able to go directly to the Get In Touch section without scrolling by adding this anchor. I can see that you did this, and when I checked in the browser, going to `localhost:4000/#get-in-touch` does indeed jump to the Get In Touch section on the homepage, as in your screenshot. Great job with that!
> 
> 
> 
> I was wondering though, @SAUMILDHANKAR or @JessicaLucindaCheng : Everything was done correctly here according to the original issue, but isn't it the case with anchors that when you jump to the section, the section that you go to should be up at the top of the page? In other words, when you go to `localhost:4000/#get-in-touch`, although it jumps to the Get In Touch section, the "Volunteer with us" card is at the top. Shouldn't it look something like this, where the Get In Touch section is up top (in my screenshot here, I had to manually scroll up so that the "Get in touch..." card sits up top):
> 
> 
> 
> <details>
> 
>   <summary>"Get in touch with us" section (Note: I scrolled up manually here)</summary>
> 
> 
> 
> ![git](https://user-images.githubusercontent.com/36783010/163650329-0fbc6520-e483-4c59-9169-e0c9abf6ded5.jpg)
> 
> 
> 
> </details>
> 
> 
> 
> Anyway, everything was done according to the issue, but I just wanted to check and ask about this. Maybe that's just how anchors work, or maybe it's because of manually typing it in the URL for now.

Thank you for taking a look at my pr. If any changes needs to happen, is this something I could look into or will the leads look into this further?

2022-04-16 01:17 UTC, answebdev commented
@KazushiR I've tagged @SAUMILDHANKAR or @JessicaLucindaCheng to ask about this, and to see if this is something that needs to be addressed here, or if it's okay. So for right now, I think it's best to wait to hear back. It was just something that I noticed, so I wanted to ask them about it and see what they say.

2022-04-16 23:25 UTC, Carlos-A-P commented
Availability: 1 hr
ETA: 4/16/2022 EOD

2022-04-17 06:47 UTC, Carlos-A-P approved these changes
@KazushiR great job on this issue! I can see the code changes and can jump to the "Get in touch" section on the homepage by going to http://localhost:4000/#get-in-touch.

2022-04-17 16:53 UTC, JessicaLucindaCheng commented
Availability: 1 hour
Review ETA: Monday, April 18, 2022

2022-04-19 23:10 UTC, JessicaLucindaCheng requested changes
@KazushiR Thanks for working on the issue. However, the issue specified making changes to code in the "feature-homepage-launch" branch.
- [ ] Close this pr.
- [ ] Follow the instructions below and in the wiki article on how to work off the "feature-homepage-launch" branch. 
#### Feature Branch
The pull request created from this issue should be pushed into a feature branch called "feature-homepage-launch." Please note this [wiki article](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch) on how to work off of a feature branch

Also, here is what the Get in Touch section looks like in the redesigned homepage.
<details>
  <summary><h4>Click Here to See Screenshot of Get in Touch Section on the Redesigned Homepage</h4></summary>
  <img width="949" alt="get-in-touch" src="https://user-images.githubusercontent.com/31293603/161402137-288d4358-4ba6-4df3-99ca-9008c12ce4f2.png">
</details>

2022-05-08 16:02 UTC, SAUMILDHANKAR commented
@KazushiR As per Jessica's review and our last discussion, closing this PR. Also, would be unassigning you from the corresponding issue so you could pick up a medium issue next which would be more in line with your issue progression. But if you feel like you have already done substantial amount of work for this issue, you can pick up this issue again instead and work on it. I will leave it up to you, but please work on only one issue at a time. Thank you.

2022-05-08 16:02 UTC, closed without merging