added anchors to guides and external resources
hackforla/website pull request #3075
Opened 2022-04-21 04:10 UTC by Carlos-A-P

Fixes #2802

### What changes did you make and why did you make them ?

  - Added an anchor to the Guides section so that https://www.hackforla.org/toolkit#guides will jump to that section
  - Added an anchor to the External Resources section so that https://www.hackforla.org/toolkit#external-resources will jump to that section

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
 - No visual changes

2022-04-21 16:13 UTC, Sparky-code commented
Avail: 1hr
ETA: 4/21-22 EOD

2022-04-22 02:19 UTC, tamara-snyder commented
Availability: 1 hour
Review ETA: 04/21/2022

2022-04-22 03:12 UTC, tamara-snyder requested changes
Hi @Carlos-A-P, great work on this! All looks good with the anchor tags and thank you for taking the time to fix some of the formatting in this file. I'm just requesting a few changes, which you'll see in my comments. Thanks!

2022-04-22 03:12 UTC, tamara-snyder commented on pages/toolkit.html
> +            community.</p>
Changing this isn't part of the issue, but it seems clearer, so that's fine. Can you please move the closing </p> tag in line 14 to the next line for clarity?

2022-04-22 03:12 UTC, tamara-snyder commented on pages/toolkit.html
>      {% endfor %}
For the sake of clarity, this section in lines 21-27 should be reverted to its original indentation. It's basically saying
```
for {
  if {
    <a></a>
  }
  else {
    <a></a>
  }
}
```

If it's not indented like it would be for normal blocks of code, it could get confusing to read.

2022-04-22 03:12 UTC, tamara-snyder commented on pages/toolkit.html
>              {%- endfor -%}
Revert indentation, same as above

2022-04-22 03:12 UTC, tamara-snyder commented on pages/toolkit.html
> +                        }
Thanks for fixing this.

2022-04-22 03:12 UTC, tamara-snyder commented on pages/toolkit.html
> +    }
Thanks for fixing this as well.

2022-04-22 03:12 UTC, tamara-snyder commented on pages/toolkit.html
> +    <a class="anchor" id='external-resources' data-name="external-resources"></a>
Change the id to use double quotes instead of single

2022-04-22 03:12 UTC, tamara-snyder commented on pages/toolkit.html
> +    <a class="anchor" id='guides' data-name="guides"></a>
Change the id to use double quotes instead of single

2022-04-23 05:59 UTC, Sparky-code commented
Updated ETA:  4/23/EOD
Blocker: School work + Docker Trouble

2022-04-24 02:29 UTC, Carlos-A-P commented
Hey @tamara-snyder. I have the prettier extension installed, and since I reinstalled my code editor the extension was reenabled for all of my projects and I didn't notice before I pushed. If the formatting looks good, I'll fix up those changes!

2022-04-25 03:32 UTC, Sparky-code requested changes
Hey @Carlos-A-P Everything looks good across devices. it looks like you've addressed Tamara's formatting requests in your second commit. I'd only ask that you check off the additional steps in the referenced issue (and note if no additional SCSS was added) in your initial comment. 

Not part of this issue but something I thought was worth noting here. The 'suggest' buttons don't do anything, it might be worth creating a 'coming soon' onclick class until they have a direction. This could be a useful reusable class for live pages that are under development.

2022-04-27 03:23 UTC, Carlos-A-P commented
Hey @Sparky-code, I checked off the additional steps in the referenced issue and noted if additional SCSS was added to my comment. Just wanted to note here that we discussed the potential of creating a new issue regarding the  'coming soon' onclick class for the 'suggest' buttons during our meetings and to follow up on slack. Let me know if find anything else for my pr or have any other questions!

2022-04-27 03:41 UTC, Sparky-code commented
Hey @Carlos-A-P, Thanks for doing that and noting our discussion. So discussing that issue creation with @JessicaLucindaCheng ended up leading to an issue that she was seeing with this issue where at certain screensize/resolution the when landing on the anchors the title text gets obscured by the H4LA logo:

<details> 
 <summary> Anchor Issue </summary>
 
![image](https://user-images.githubusercontent.com/95888938/165433859-26267f3d-56c3-48f5-94e3-bc4c53973f49.png)
</details>

I wasn't seeing this issue when I was using dev tools in chrome so I suggest looking at it through firefox where you have more control over the screen size and resolution. 

**Note:** Its ok that the title block goes behind the logo on scrolling but the anchor should resolve at all screen sizes /resolutions so that the title is not obscured when you land there. 

The other point would be that I'm guessing you added the 'data-name' to the anchor tag as a result of the about page reference. That seems to be unnecessary so next steps for this issue would be:

- [ ] Remove 'date-name' from the anchor tags generated for the toolkits page
- [ ]  Test page for the visual issue noted above 
- [ ]  Implement adjustments to resolve this issue

2022-05-02 02:49 UTC, Carlos-A-P commented
Hey @Sparky-code, I kept the data attribute since I wasn't sure of its purpose.  I looked more into the about page anchors and wondered if you had any idea what the data attributes are for? I looked around in the about.js file, but I don't see them being used?

2022-05-02 06:05 UTC, JessicaLucindaCheng commented
@Carlos-A-P I don't see a purpose or use of the data-name attribute for the Guides and External Guides anchors, so it is preferred if we don't include code we aren't using. You can test out what happens if that attribute is removed just to make sure but I'm pretty sure the anchors will function without the data-name attribute and we can always add them later if needed.

2022-05-04 04:23 UTC, Carlos-A-P commented
Hey, @tamara-snyder @Sparky-code I made some changes. I would request for reviewers to review again but the request button doesn't show up on my side? 

Either way, I made some changes in _toolkit.scss and it picked up some errors for duplicate selectors. I addressed it in another dev's pr who's also working on the same page if they can take a look at it but I can do it too if needed.

2022-05-04 17:42 UTC, Sparky-code commented
Hey @Carlos-A-P Will take a look today/tomorrow. Sorry I didn't get back to your questions before you worked on it. I think that makes sense. If there's another element slightly above you can set it to to give it more 'padding' or more directly do that (Note that anchor elements don't directly take padding). Something I just googled that might be useful: https://stackoverflow.com/questions/10732690/offsetting-an-html-anchor-to-adjust-for-fixed-header

2022-05-04 19:08 UTC, Carlos-A-P commented
@Sparky-code sounds good! I'll find a better way to add spacing to it instead of using padding on the anchor tag, thanks!

2022-05-06 14:37 UTC, tamara-snyder commented
Hey @Carlos-A-P, thank you for removing the data-name attributes as Jessica requested. All looks good. I'm going to wait until the SCSS Linter check is resolved to do a proper review.

2022-05-07 02:07 UTC, SAUMILDHANKAR commented
@Carlos-A-P Hi Carlos, we just noticed that the Lint SCSS workflow is failing for your PR. We are considering making a new issue to resolve this. Just wanted to let you know that unless there was any SCSS (that you modified as part of your PR) which might have resulted in this error, there is no need for you to fix this and you can ignore it for this PR. Thank you.

2022-05-07 05:36 UTC, Carlos-A-P commented
Hey @tamara-snyder @Sparky-code, just made a few updates again and this pr is ready for review. Not too sure as to why I'm still not able to request reviewers even though there are changes requested?
![image](https://user-images.githubusercontent.com/85038929/167240076-b2db9ebd-7dcd-4e42-8f04-dd0f81f989af.png)

2022-05-08 18:05 UTC, Sparky-code requested changes
Hey @Carlos-A-P Thanks for working on this and being patient on this review. Looks like the issue is mostly solved though I am noticing a couple of things at smaller pages. I think a slightly larger padding should solve the second issue, at first glance I'm not sure what the cause of the first issue is.

<details>
<summary> Issue with guides bar organization with smaller screens </summary>
![image](https://user-images.githubusercontent.com/95888938/167309177-fefaa499-5e08-451a-ade9-b4c910179570.png)
![image](https://user-images.githubusercontent.com/95888938/167460102-ebc0646f-3b0e-4631-9eec-8693e97e7f73.png)

</details>

<details>
<summary> Issue with resource headers at smaller screens </summary>
![image](https://user-images.githubusercontent.com/95888938/167309215-0d97ec69-85bf-430f-bb58-6e4dc07a0a77.png)
</details>

2022-05-09 00:24 UTC, Carlos-A-P commented
Hey @Sparky-code not sure if it's just my side but I'm not able to view the images in your last comment

2022-05-09 17:01 UTC, Sparky-code commented
@Carlos-A-P Thats strange, im not sure why thats happening. Moved them outside of the details, should be visible now.

2022-05-11 03:09 UTC, Carlos-A-P commented
@Sparky-code for the first image, I could only assume that the images disappear since the guides list filters by changing the URL. For example, to filter for design it would be "hackforla.org/toolkit/#Design" so the anchor tags would interfere which I now see is an issue as well. I'm also not too sure why at 1238px width it didn't work on your side. I tested the anchor in two different browsers and the headers don't seem to be blocked?

![image](https://user-images.githubusercontent.com/85038929/167761168-e90de828-e6b2-4d46-bcaf-2aa19e737114.png)

2022-05-18 02:47 UTC, Sparky-code commented
Hi @Carlos-A-P adding this update as a follow up from our discussion on Sunday 5/15 - This issue is still ongoing due to an edge case that occurs when accessing the guides and the usage of anchor tags and hrefs appear to conflict and cause issues with what is being displayed and what is supposed to display. Please let me know If I forgot anything here.

2022-05-18 03:18 UTC, Carlos-A-P commented
> Hi @Carlos-A-P adding this update as a follow up from our discussion on Sunday 5/15 - This issue is still ongoing due to an edge case that occurs when accessing the guides and the usage of anchor tags and hrefs appear to conflict and cause issues with what is being displayed and what is supposed to display. Please let me know If I forgot anything here.

Hey @Sparky-code, that's correct, and was also wondering if you still get the problem with the logo covering the header?

2022-05-18 15:22 UTC, Sparky-code commented
Avail: 1-2hrs
ETA: 5/17-18 EOD

2022-05-18 20:51 UTC, Sparky-code approved these changes
This appears to solve the issue of the logo overlaying on the section title when screen size was close to the media breakpoint. Nice!

2022-05-18 20:52 UTC, Sparky-code approved these changes

2022-05-18 20:52 UTC, Sparky-code commented on _sass/components/_toolkit.scss
> +        padding-top: 1.7rem;
Looks like these fix the issue of Logo overlay at or near the screen size break points at the medium screen size, nice!

2022-05-18 21:00 UTC, Sparky-code approved these changes, later dismissed

2022-05-18 21:00 UTC, Sparky-code commented on pages/toolkit.html
> +            let guidesCategories = ["all", "development", "design", "projectmanagement", "professionaldevelopment"]
This looks great! What I did to try to reproduce the problem we were seeing with the selected guides vanishing when switching between guide groups in the toolkit nav bar (using hrefs) vs the resource/toolkit sections (using anchors)

Land @ /toolkit/ > select 'design' from nav > edit http address appendix to '#guides' > guides remain! > append to '#external-resources' instead > scroll up > guides remain!

Land @ /toolkit/#external-resources > scroll up > guides exist > select 'development' from nav > edit http address appendix to '#guides' > Guides remain!

I think thats the flow that was showing us the issue before. I'm not able to replicate it with these fixes.  NIce work

2022-05-20 02:40 UTC, kathrynsilvaconway submitted a review, later dismissed
@Carlos-A-P I can see that the two anchors are added and everything else looks good in the code. Nice job cleaning up the padding as well. It looks like everything unresolved in this discussion is out side of the scope of the original issue, so I am just going to approve it. Very good work.

2022-05-20 03:05 UTC, tamara-snyder approved these changes, later dismissed
Hi @Carlos-A-P, the anchors work great! Thanks for working on this issue.

2022-05-25 02:13 UTC, JessicaLucindaCheng commented
@tamara-snyder @Sparky-code Is this pr ready to be merged?

I know the Lint SCSS check is failing. However, if the linting is catching code issues that Carlos did not edit nor add (meaning the linting is catching something that already exists in the code and Carlos did not touch that portion of the code), it should be okay to merge as long as the linting problem doesn't break anything on the website.

2022-05-25 06:04 UTC, Sparky-code commented
@JessicaLucindaCheng I believe so.

Confirming It does not appear to have a negative impact on the page Carlos worked on. Its not code he edited. I re-ran his branch locally to be sure, am adding the error output here for reference for creating an issue to fix this as I believe it has come up in a few issues though I haven't investigated where the duplicate class came from / was made for.

> 2022-05-18 04:42:30 [ERROR]   Found errors in [stylelint] linter!
2022-05-18 04:42:30 [ERROR]   Error code: 2. Command output:

>_sass/components/_toolkit.scss
 235:1  ✖  Unexpected duplicate selector ".resource-svg-icons", first used at line 120          no-duplicate-selectors
 240:1  ✖  Unexpected duplicate selector ".toolkit-info-container", first used at line 126      no-duplicate-selectors
 241:5  ✖  Unexpected duplicate selector ".toolkit-info-container h3", first used at line 130   no-duplicate-selectors

2022-05-27 03:18 UTC, Carlos-A-P commented
@Sparky-code, just fixed the merged conflict so it's ready to be reviewed again.

2022-05-27 17:32 UTC, Sparky-code approved these changes
Everything looks good, I see you've resolved the merge conflict by including the changes for the toolkits page that were merged from a separate issue since your previous commit.

2022-05-27 17:37 UTC, merged