fixed spelling of non-profit to nonprofit, line 77, join-us.html
hackforla/website pull request #3076
Opened 2022-04-21 20:58 UTC by JayBarbanel

Fixes #2914

### What changes did you make and why did you make them ?

  - Changed text on line 77 in the join-us.html page from non-profit to nonprofit. 
  -
  -

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

![image](Paste_Your_Image_Link_Here_After_Attaching_Files)

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
![image](Paste_Your_Image_Link_Here_After_Attaching_Files)

</details>

2022-04-21 23:34 UTC, Sparky-code commented
Avail: 1hr
ETA: 4/22 EOD

2022-04-22 01:36 UTC, tamara-snyder commented
Availability: 1 hour
Review ETA: 04/21/2022

2022-04-22 02:01 UTC, tamara-snyder requested changes, later dismissed
Hi @JayBarbanel, great work! I'm just requesting you to change line 77 from "NonProfit" to "Nonprofit" to match what is written in the issue description, and also to post screenshots of your visual changes in your PR. Thank you!

2022-04-22 02:01 UTC, tamara-snyder commented on pages/join-us.html
> +        <a href="./survey3" target="_blank" class="btn btn-primary btn-md btn-partner-with-us btn--default" title="Non-profit Contact Form">NonProfit</a>
Based on the issue description, I think the spelling here should be "Nonprofit" instead of "NonProfit".

2022-04-22 05:41 UTC, JayBarbanel commented on pages/join-us.html
> +        <a href="./survey3" target="_blank" class="btn btn-primary btn-md btn-partner-with-us btn--default" title="Non-profit Contact Form">NonProfit</a>
thanks for catching that Tamara!  I went ahead and fixed that issue, also added screenshots above.  Let me know if there's anything I'm missing here - I appreciate your help as this is my first issue.

2022-04-22 06:04 UTC, Sparky-code requested changes
Hey @JayBarbanel, welcome to H4LA!
Your changes to join-us.html look good 👍
Since the issue is looking specifically at spelling and capitalization:
- The changes made doesn't read as accurate 
- Your before image doesn't seem to show the correct 'prior' state from looking at your file change. 

- I'm curious why there are changes to the docker-compose.yml file as well (I know there were some issue with docker for new volunteers, wondering if its related to that)

2022-04-22 06:18 UTC, JayBarbanel commented
> 

@Sparky-code weird - on my end it looks like it's updated and correct.  
As for the image - I had pushed my first commit and then added the images after, so it only shows the version I had updated, not how the file was originally.  I had to go back and just fix the cap on the 'P' in Nonprofit.  
Next time I know to screenshot before doing any updating.  

As for the .yml file - I was having issues but was advised to update that file, worked once I did.  

Let me know how to move forward here, thank you!

2022-04-23 05:55 UTC, Sparky-code commented
@JayBarbanel Sorry, bad phrasing. In your initial comment. Referencing the changes made.

> What changes did you make and why did you make them ?
> Changed text on line 77 in the join-us.html page from **N**on-**P**rofit to **N**onprofit.

No worries on the images, just wanted to note it. Same with the capitalization. just wanted to note it. If you can fix that text in the initial comment though. If you've addressed Tamara's request you should be able to 'resolve conversation' for her request and that should kick all the automated tests to complete and be ready for merge.

Gotcha on the .yml file 👍 glad that's working for you with an easy fix.

2022-04-23 17:56 UTC, JayBarbanel commented
@Sparky-code Should be all good now!  Thanks for walking me through that, I appreciate the help.

2022-04-23 19:39 UTC, Sparky-code commented
@JayBarbanel Of course, we're all learning new stuff. Don't forget to re-request those reviews!
I'm going to check with the merge team about committing those changes to the .yml file, since that feels like it should be a separate issue.

2022-04-25 00:32 UTC, JessicaLucindaCheng requested changes
@JayBarbanel Thanks for working on this issue! In addition to my in-line change requests, do the following:
- [ ] Please check off the items you have completed in your issue https://github.com/hackforla/website/issues/2914
- [ ] Please add your pr to the Project Board.

  <details>
  
    <summary>Click here for more detailed instructions on how to add your pr to the Project Board</summary>
    
    1) On the right, under the "Projects" section
      <img width="158" alt="" src="https://user-images.githubusercontent.com/31293603/165002124-e0e5ff5c-42e1-42b9-8217-64c6dd2f5fd3.png">
    
    2) Click on the gear icon
      <img width="155" alt="" src="https://user-images.githubusercontent.com/31293603/165002132-d1d0f652-5882-4abb-a1d2-e39c468b7554.png">
    
    3) Then click on Project Board to add your pull request to the project board.
      <img width="155" alt="" src="https://user-images.githubusercontent.com/31293603/165002148-12c25b18-e18f-4232-92ca-d3e62e906014.png">
  
  </details>

Also, in the future, you can take screenshots from the current, live website (https://www.hackforla.org/) for your before pictures instead of having to undo your changes to take the before screenshots.

2022-04-25 00:32 UTC, JessicaLucindaCheng commented on docker-compose.yml
> +    image: jekyll/jekyll:4.2.0
Change `4.2.0` back to `pages` for now. (Sorry for the inconvenience but we want to make sure to test any changes to this file to make sure it doesn't break using Docker for other developers, which is currently being worked on in another issue.)

2022-04-25 00:32 UTC, JessicaLucindaCheng commented on pages/join-us.html
> +        <a href="./survey3" target="_blank" class="btn btn-primary btn-md btn-partner-with-us btn--default" title="Non-profit Contact Form">Nonprofit</a>
As requested in the issue, please also change `title="Non-profit Contact Form"` to `title="Nonprofit Contact Form"`

2022-04-26 22:41 UTC, kathrynsilvaconway commented
Availability: 1 hour
Review ETA: 04/27/2022

2022-04-26 22:55 UTC, kathrynsilvaconway approved these changes
@JayBarbanel  Nice work fixing this error. I see you have made the requested change on line 77. Everything looks good in the html and I can see the changes locally. Good first issue!

2022-04-27 18:00 UTC, JayBarbanel commented
@JessicaLucindaCheng Added this to the project board.  As far as checking off what I've done in the issue..Where do I do that?  I made a comment in the initial issue showing that I changed line 77, is there somewhere else I need to do that?  

I think i should be all set, but I'm still seeing 3 change requests.  Could you let me know if/what else I need to do to wrap this one up?  Thank you!

2022-04-28 02:12 UTC, JessicaLucindaCheng commented
- Availability: 2 hours
- Review ETA: Thu, Apr 28

2022-04-28 14:51 UTC, Sparky-code commented
@JayBarbanel if you click through to the original issue you assigned yourself to (https://github.com/hackforla/website/issues/2914), you'll find the 'Action Items' that you completed to create this. Check those off there. 

<details> 
<summary> Action Item Not completed</summary>
![image](https://user-images.githubusercontent.com/95888938/165780362-3dfe6e96-ddfc-40ce-8bd2-e3fa02638189.png)
</details>

<details> 
<summary> Action Item completed</summary>
![image](https://user-images.githubusercontent.com/95888938/165780580-96f5c514-0803-4fb9-9b0e-b97957c0df73.png)
</details>

2022-04-28 21:53 UTC, Sparky-code approved these changes
Hey Jay,

- [x] Looks good!
- [x] Thanks for addressing the detailed changes!

2022-04-28 23:18 UTC, JessicaLucindaCheng approved these changes
@JayBarbanel Thanks for making the changes. The code looks good to me now.

> As far as checking off what I've done in the issue..Where do I do that?

See @Sparky-code's comment above about how to do that: https://github.com/hackforla/website/pull/3076#issuecomment-1112304850
Please make sure to do that for any issues you work on.

2022-04-28 23:20 UTC, merged