Update project page header 2355
hackforla/website pull request #3087
Opened 2022-05-02 22:43 UTC by Jaretzbalba

Fixes #2355

### What changes did you make and why did you make them ?

  - Update HTML text to match new header text in Figma
  - Update SCSS to match styling in Figma

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

![2355-project-page-desktop-before](https://user-images.githubusercontent.com/93153059/166338255-b16e00f3-04d0-42cd-94f9-a49366e54625.png)

![2355-project-page-mobile-before](https://user-images.githubusercontent.com/93153059/166338263-928e79aa-9dd6-42a2-ae3a-1bf8434013f7.png)

</details>

<details>
<summary>Visuals after changes are applied</summary>

![2355-project-page-desktop-after](https://user-images.githubusercontent.com/93153059/166338288-1c574413-a544-4af3-98ed-d84c626d861f.png)

![2355-project-page-mobile-after](https://user-images.githubusercontent.com/93153059/166338294-14fafc63-bf62-4036-9b8c-2d5843b515a3.png)

</details>

2022-05-02 23:04 UTC, Jaretzbalba commented
Blocker: Previous commits from a different issue somehow got grouped into this pull request. I'm not sure what is the best way to go about fixing this conflict.

2022-05-03 03:33 UTC, kathrynsilvaconway commented
ETA: End of the day on 5/06
Availability: 2 hours

2022-05-03 03:46 UTC, kathrynsilvaconway commented
@Jaretzbalba It looks like these conflicts are all being caused by comments that aren't commented out properly. Are those on your current branch? If they are, try going through the code and changing all the ">>>>>>>" and "<<<<<<<" to "//" If you click on the Resolve conflicts button here, it will show you where they all are. You use Ctrl + / to comment out the lines properly. See if that fixes it. 
![Screenshot 2022-05-02 233647](https://user-images.githubusercontent.com/81049661/166401882-7eaaecec-d3c4-4028-bd8f-897d1f0989c0.png)

2022-05-04 15:49 UTC, Sparky-code commented
hey @Jaretzbalba I'll take a look sometime today/tomorrow but can you reference the other issue that changes somehow got lumped in from?
Avail: 1-2hrs
ETA: 5/05 EOD

2022-05-04 17:00 UTC, Jaretzbalba commented
@Sparky-code The issue that got lumped into this PR was issue #3022/ PR #3043. 

Yes, the files that shouldn't be included in this PR are:

_data/internal/credits/tools/so-go-survey.yml
_sass/components/_credit-items.scss
assets/images/credits/so-go-survey.png
pages/credits.html

2022-05-04 19:59 UTC, JessicaLucindaCheng commented
@Jaretzbalba Try a git revert on the commit that shouldn't be in this pr and push to the branch `update-project-page-header-2355`. Then, check the Files Changed tab to make sure only the files/code you want changed is there.

2022-05-04 21:20 UTC, JessicaLucindaCheng commented
@SAUMILDHANKAR @tamara-snyder @answebdev There is something weird going on with all the automations/checks not running, which there are usually 3 that run. (See "Checks" tab for this pr.) I'm not sure if it has something to do with the merge conflicts. However, I manually added the labels to help developers looking to review prs to know about the pr/issue by the labels.

2022-05-09 04:10 UTC, Jaretzbalba commented
@JessicaLucindaCheng The git revert seems to have fixed the file issue. However, I can't seem to get this current branch to update with the latest changes from gh-pages. When I'm on the branch I'll check upstream and it claims it is already up to date; however, I can clearly see that files are missing from recent merges and my branch on GitHub even says that it's behind.

<details>
<summary>Terminal</summary>

![terminal](https://user-images.githubusercontent.com/93153059/167339091-a24db16b-2d56-4f1b-9b99-90f3670802b5.png)

</details>

<details>
<summary>GitHub</summary>

![GitHub](https://user-images.githubusercontent.com/93153059/167338882-8dcf78db-38f3-44cd-b591-0e0be9de1f71.png)

</details>

2022-05-11 03:16 UTC, Jaretzbalba commented
The blocker was resolved during the team meeting on 5/10/22. @JessicaLucindaCheng recommended merging the upstream-gh-pages to my topic branch to have the most up-to-date files. However, since my gh-pages are a few commits ahead, I will need to refork this repo.

2022-05-16 15:45 UTC, Sparky-code submitted a review, later dismissed
Content changes look good on both mobile and and desktop. Links in the callouts work as expected and CSS is clean and works well. Happy to see the files issue was resolved as well. 

Great job!

2022-05-18 03:02 UTC, tamara-snyder commented
Availability: 1 hour
Review ETA: Wednesday, May 18

2022-05-20 02:29 UTC, tamara-snyder requested changes, later dismissed
Hi @Jaretzbalba, well done on this! The desktop and mobile versions look great. I left a couple of comments, but the main one is just that a tablet query may need to be added in order to accommodate about 40px of width where the paragraph spills off the page. You'll find a screenshot of the problem in my comment. Thanks for working on this! Feel free to request another review when you're ready.

2022-05-20 02:29 UTC, tamara-snyder commented on _sass/elements/_containers.scss
> +  max-width: 508px;
This width looks good for the most part, but when it's between around 520px and 480px, the paragraph gets squished and pushed off the screen as shown in this screenshot:
<img width="484" alt="Screen Shot 2022-05-19 at 9 57 45 PM" src="https://user-images.githubusercontent.com/57715733/169434348-fc9eeb4b-a3fb-45a6-9767-1874a337df59.png">
Could you please look into adding a tablet query that could accommodate this range of widths?

2022-05-20 02:29 UTC, tamara-snyder commented on pages/projects-page.html
> +        <a class="callout-link"  href="/about/">About Us</a>
This line links to an unfinished page with lorem ipsum text and this PR is going to be merged into gh-pages. @SAUMILDHANKAR @JessicaLucindaCheng @Sparky-code @answebdev I can't find finished copy for this page since it's still in development. We could go ahead and merge it as is or I could write an issue to hide that section of the new About page until the text is written. Let me know what you all think.

2022-05-25 03:02 UTC, Jaretzbalba commented on pages/projects-page.html
> +        <a class="callout-link"  href="/about/">About Us</a>
@tamara-snyder At Tuesday's Developer meeting @JessicaLucindaCheng talked about testing out what commenting-out the "About Us" section and taking screenshots of what that would look like instead of pushing the changes. We could then propose this at Sunday's meeting and see if this is an acceptable fix for now or we can discuss further steps if not.

2022-05-25 06:32 UTC, Sparky-code commented
Avail: 2hrs
ETA: 5/27 EOD

2022-05-27 12:57 UTC, tamara-snyder commented on pages/projects-page.html
> +        <a class="callout-link"  href="/about/">About Us</a>
Alright, so do you mean like merging commented out code and then creating an issue later to uncomment it?

2022-05-29 03:24 UTC, JessicaLucindaCheng commented on pages/projects-page.html
> +        <a class="callout-link"  href="/about/">About Us</a>
@tamara-snyder Yes.

@Jaretzbalba Will you be able to comment out the section and provide screenshots in a new comment below, so we can show to Bonnie at Sunday's meeting and get her approval?

2022-05-29 16:13 UTC, Jaretzbalba commented on pages/projects-page.html
> +        <a class="callout-link"  href="/about/">About Us</a>
@JessicaLucindaCheng I actually won't be able to make it to today's meeting but I was able to get screenshots if someone is able to show Bonnie today. 

<details>
<summary>Visuals before changes are applied</summary>

![2355-project-page-desktop-version-1](https://user-images.githubusercontent.com/93153059/170879777-734f3926-297c-47f5-879a-38d602dbf294.png)

![2355-project-page-mobile-version-1](https://user-images.githubusercontent.com/93153059/170879789-70096155-ac3d-4c03-b4f8-b1b00c6a170a.png)

</details>

<details>
<summary>Visuals after changes are applied</summary>

![2355-project-page-desktop-version-2](https://user-images.githubusercontent.com/93153059/170879807-414cb053-d13e-4758-803e-5d75e9c1c3a5.png)

![2355-project-page-mobile-version-2](https://user-images.githubusercontent.com/93153059/170879811-8d24d5e3-71d5-4fd3-acb9-4c11c3abdd26.png)


</details>

2022-05-29 17:22 UTC, Sparky-code commented
Sorry for the delay - Reviewing today

2022-05-29 20:17 UTC, Sparky-code commented
@Jaretzbalba So I see that you made the correct changes and the resulting complication with the page to the unfinished about us page. When I pull your branch I am still seeing the about us section. From reading your comments it is unclear whether or not you are commenting out that section as a part of this issue or if that was something that was done as a visual test to bring up in meeting. If it is the former, I am not seeing it reflected in the code. If the latter, and it was decided that we will keep the link to the unfinished page than it looks like everything is good to go

2022-05-29 21:27 UTC, JessicaLucindaCheng commented
@Sparky-code We actually did discuss it in the meeting. Bonnie said to merge it onto the feature-homepage-launch branch. So, don't hide anything within a comment.

@Jaretzbalba So, now you will need to do the following:
- [ ] Merge the `feature-homepage-launch` branch into your topic branch `update-project-page-header-2355` by doing the following:
  - [ ] Do the first two bullet points in [Step #1](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch#step-1-create-your-branch). (Do **not** do the third bullet point.)
  - [ ] Then, git checkout your topic branch
  - [ ] Then, do a `git merge feature-homepage-launch`
- [ ] Update the "into" branch in your pr by:
  - [ ] 1. By clicking the "Edit" button next to the pr
    <img width="926" alt="Screenshot 2022-05-29 141943" src="https://user-images.githubusercontent.com/31293603/170891911-378dd293-41ec-4ca6-be31-c7859554fb17.png">
  - [ ] 2. Updating the "into" branch to `feature-homepage-launch`
  - [ ] 3. Click the "Save" button.
    <img width="939" alt="Screenshot 2022-05-29 142408-step2" src="https://user-images.githubusercontent.com/31293603/170892024-72dc5840-01e6-43a5-9e0f-9f0d23ba980f.png">

2022-05-29 21:38 UTC, JessicaLucindaCheng commented on pages/projects-page.html
> +        <a class="callout-link"  href="/about/">About Us</a>
See my comment here: https://github.com/hackforla/website/pull/3087#issuecomment-1140527638

2022-05-30 17:32 UTC, Jaretzbalba commented
> 

@JessicaLucindaCheng Just to make sure I do this correctly should the {FEATURE BRANCH NAME} in the steps provided be `feature-homepage-launch` or  `update-project-page-header-2355`?

2022-05-31 22:47 UTC, JessicaLucindaCheng commented
@Jaretzbalba 
> @JessicaLucindaCheng Just to make sure I do this correctly should the {FEATURE BRANCH NAME} in the steps provided be `feature-homepage-launch` or `update-project-page-header-2355`?

`feature-homepage-launch`

2022-06-15 02:33 UTC, Sparky-code approved these changes
I see that the branch was updated to reflect the discussion had in the comments regarding that.

2022-06-19 17:29 UTC, kathrynsilvaconway commented
ETA: End of day 6/20
Availability: 1 hour

2022-06-28 21:59 UTC, Sparky-code commented
git checkout -b feature-homepage-launch upstream/feature-homepage-launch
git checkout -b Jaratzbalba-update-project-page-header-2355 feature-homepage-launch
git pull https://github.com/Jaretzbalba/website.git update-project-page-header-2355

2022-07-01 00:37 UTC, kathrynsilvaconway approved these changes
@Jaretzbalba Changes all  look good locally and the links work. I see that you have pushed your changes to the correct feature branch as well. Overall, very nice work, Jaret.  Thank you.

2022-07-01 00:38 UTC, merged