Update profile greenearth 3059
hackforla/website pull request #3179
Opened 2022-05-29 17:21 UTC by frankstepanski

Fixes #3059 

### What changes did you make and why did you make them?

  -  Updated project details for GreenEarth
  
  https://github.com/hackforla/website/blob/gh-pages/_projects/green-earth-os.md

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

![before](https://user-images.githubusercontent.com/7707247/170883038-5d3246bc-6267-4b8f-8e5b-eea4ca177317.png)

</details>

<details>
<summary>Visuals after changes are applied</summary>

![after](https://user-images.githubusercontent.com/7707247/170883083-12c3c66d-980b-49ed-9ee5-aa5c79ec17f4.png)

</details>

2022-05-30 17:46 UTC, Jaretzbalba commented
ETA: End of the day on 6/01
Availability: 2 hours

2022-05-30 17:56 UTC, Jaretzbalba requested changes
@frankstepanski Thank you for working on this issue! Based on what's requested in the issue for this PR, please add a technologies section to the md file as well. I also left a comment regarding a link you need to update as well as a link to a profile picture for Sanya. Thanks again!

2022-05-30 17:56 UTC, Jaretzbalba commented on _projects/green-earth-os.md
> +    picture: https://avatars.githubusercontent.com/samaynathani
The GitHub handle for Raji needs to be updated as it is currently linked to Samay Nathani's profile.

2022-05-30 18:00 UTC, Jaretzbalba commented on _projects/green-earth-os.md
> +      github: 'https://github.com/sanya301'
Sanya needs a link for her profile picture here

2022-06-01 04:27 UTC, luke-karis commented
ETA: End of day of 6/3
Availability 2 hours

2022-06-07 04:45 UTC, luke-karis requested changes
Hey @frankstepanski great job working on this issue! I agree with basically all of Jaret's comments we should try to get a picture for Sanya and change the picture for Raji. While the ticket says we should also add a technologies section for MkDocs I feel that we could maybe just throw this in the Tools section. What do you think @Jaretzbalba? Maybe we should check in with the creator of the ticket.

2022-06-26 17:28 UTC, blulady commented
Availability: 1 hour
ETA: 7/1/22

2022-08-08 21:25 UTC, blulady commented
@frankstepanski Hey, are you going to finish this issue? If not please let us know so we can close this issue and give it to someone else.

2022-08-13 03:27 UTC, frankstepanski commented
Sorry, my mother passed 2 months ago. 
ETA: By Wednesday (8/17)

2022-08-19 21:17 UTC, closed without merging