Issue form GitHub actions
hackforla/website pull request #3451
Opened 2022-08-05 06:09 UTC by arpitapandya

Fixes #2299

### What changes did you make and why did you make them ?

  - created a gha-issue-template.yml file in [this folder](https://github.com/hackforla/website/tree/gh-pages/.github/ISSUE_TEMPLATE)
  - Form is visible

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
There aren't any changes to site.
- NOTE: I am not sure about the checkbox information I have used is correct.
- Time saver helpful tools: [extension to vs code](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml), [yamllint](http://www.yamllint.com/)

2022-08-05 08:17 UTC, Zak234 commented
ETA: Aug 7th
Availability: Aug 6th 9:00 AM - 3 PM

2022-08-05 20:11 UTC, Zak234 requested changes
There seems to be several issues with the template. First, there is no way for the user to add pseudo code when creating the issue as its just a label with no text field (also pseudo is spelled wrong). Second, I don't think there should be a description for textarea as the one included seems to be issue specific. Third, the label ``` New and existing unit tests pass locally with my changes``` should not be marked as required as this leads to the issue creator having to check the box to create the issue rather than the issue assignee. Fourth, the description ```Checklist on how to use the GitHub actions``` needs to be a label as it doesn't show up in the created issue currently.  Fifth, Action Items needs to be changed so the issue creator can actually add action items to the issue. Sixth, you cannot have ```"https://github.com/hackforla/website/wiki/Hack-for-LA's-GitHub-Actions"``` be a description as it doesn't appear in the created issue. Seventh, the ```Never done GitHub actions? [Start here!](https://docs.github.com/en/actions)
        Note that you might want to do something outside the scope of the above psudo-code. If so, be sure to leave comments in your PR or this issue that justifies your reasoning. If you feel you need guidance, be sure to reach out! We cannot foresee whether this issue is solvable, or what hard decisions have to be made, but we would love to hear and help you!``` description is supposed to be under resources.

2022-08-07 16:47 UTC, blulady commented
> Fixes #2299
> 
> ### What changes did you make and why did you make them ?
> * created a gha-issue-template.yml file in [this folder](https://github.com/hackforla/website/tree/gh-pages/.github/ISSUE_TEMPLATE)
> * Form is visible
> 
> ### Screenshots of Proposed Changes Of The Website (if any, please do not screen shot code changes)
> There aren't any changes to site.
> 
> * NOTE: I am not sure about the checkbox information I have used is correct.
> * Time saver helpful tools: [extension to vs code](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml), [yamllint](http://www.yamllint.com/)

Thank you for sharing tools with us!! It really is delightful!!!

2022-08-07 17:27 UTC, Zak234 requested changes
There still seems to be an issue with the Resources-instructions not appearing upon creating the issue because it is a description. Additionally, the description for the Overview section seems to be specific to a single issue and doesn't seem like it applies to all Github Action issues. I also believe based on the posted example issue that pseudo code and action items are supposed to be separate sections.

2022-08-10 02:26 UTC, jdingeman commented
ETA: EOD Aug 8
Availability: 4 hrs

2022-08-10 22:49 UTC, jdingeman commented on .github/ISSUE_TEMPLATE/gha-issue-template.yml
> +        Note that you might want to do something outside the scope of the above psudo-code. If so, be sure to leave comments in your PR or this issue that justifies your reasoning. If you feel you ne
"Pseudo-code" is spelled wrong

2022-08-10 23:11 UTC, jdingeman requested changes
- Line 37: "Resources-instructions" should be "Resources/Instructions"
- Lines 18-24: Overview should be required.
- I agree with @Zak234 that Action Items and Pseudo-code should be separate sections
- The [original issue](https://github.com/hackforla/website/issues/2299) says that if the checkbox is checked, then it will display the staple text. I don't think there is a way in YAML to express conditional logic for our purposes. I think the staple text (the text containing the link to generic GitHub Actions) should appear with the last portion of the body. The Hack-for-LA's GitHub Actions should be in the description of Resources and Instructions.

2022-08-11 04:09 UTC, arpitapandya commented
This PR is not ready to re-review as I am working on some changes, I have moved to Actively working for now. I will re-request once It's ready. Thank you

2022-08-13 23:22 UTC, arpitapandya commented
Need help to delete the last commit.
How this happened: My intention was to make changes to the pull request. So, as I deleted the branch 2 days ago. I was trying to pull the branch locally so that I can work on it.
- command used `git checkout -b arpitapandya-issue-form-github-actions-2299 gh-pages`
- forked changes to my repo website for hackforla. I read few commits behind `update` so I forked changes
- which led me to this commit below I wanna get rid of
![helpwanted](https://user-images.githubusercontent.com/66761308/184516356-85ef17bb-4211-4039-933b-c98a8b2439cd.PNG)

2022-08-15 02:28 UTC, jdingeman commented
> Need help to delete the last commit. How this happened: My intention was to make changes to the pull request. So, as I deleted the branch 2 days ago. I was trying to pull the branch locally so that I can work on it.
> 
> * command used `git checkout -b arpitapandya-issue-form-github-actions-2299 gh-pages`
> * forked changes to my repo website for hackforla. I read few commits behind `update` so I forked changes
> * which led me to this commit below I wanna get rid of
>   ![helpwanted](https://user-images.githubusercontent.com/66761308/184516356-85ef17bb-4211-4039-933b-c98a8b2439cd.PNG)

Are you able to go into the previous commits and copy and paste the one you want it to revert back to? And then just commit it again?

2022-08-28 22:15 UTC, arpitapandya commented
@Zak234 @jdingeman I have made changes, I am not sure if that even makes any sense. Do let me know, also if we still need to make changes to the last check box for staple text.

2022-08-29 14:20 UTC, arpitapandya commented
Have to close this.

2022-08-29 14:20 UTC, closed without merging