Change sdg-image-alt text in the lucky-parking.md
hackforla/website pull request #3519
Opened 2022-09-05 01:45 UTC by plang-psm

Fixes #3097

### What changes did you make and why did you make them ?

  - change the sdg-image-alt text in the lucky-parking.md file to '11: sustainable cities and communities' from sdg-image-alt: sustainable cities bottom sustainable dev goal

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

No visual changes were made.

2022-09-05 21:10 UTC, neevliberman commented
Review ETA: 3 PM PST, 9-5-22
Availability: 3 Hours

2022-09-05 21:17 UTC, neevliberman requested changes, later dismissed
I see that you changed all double quotes to single quotes. Was this for consistency or is there also a functional purpose? Also on line 60 you deleted a whitespace character, I'm also curious about this. Doesn't seem website-breaking but just in case it's good to know why certain changes were made, so it might be helpful to explain in your comment! The change you needed to make was good, otherwise!

2022-09-05 21:17 UTC, neevliberman commented on _projects/lucky-parking.md
> +card-image-alt:
Why was this change made? Does the extra white space cause issues?

2022-09-06 02:12 UTC, arpitapandya approved these changes
The changes are correct! Because it doesn't break anything I would approve this. But, I would suggest not to make extra changes for the issues which are about to make line specific change only. Sometimes, that may break other things. Here the issue suggest to make changes to only line 60. Great job @plang-psm

2022-09-06 02:22 UTC, merged

2022-09-06 23:02 UTC, plang-psm commented
Thank you for catching this! @neevliberman! I only edited line 60 but I believe my editor may have auto formatted once I saved the line with single quotes. I usually use single quotes when coding so thats most likely it. I'll take a look into it to make sure it doesn't happen in the future.

2022-09-06 23:05 UTC, plang-psm commented
Thank you @arpitapandya! I believe the extra changes came from my editor as it may have auto formatted when I saved the file. I'll make sure to change this to prevent any future unwanted changes.

2022-09-06 23:15 UTC, arpitapandya commented
> Thank you @arpitapandya! I believe the extra changes came from my editor as it may have auto formatted when I saved the file. I'll make sure to change this to prevent any future unwanted changes.

@plang-psm Since, the changes has already been merge and updated now, you do not do anything. No problem