add-feature-branch-to-contributing-1750
hackforla/website pull request #3558
Opened 2022-09-16 04:48 UTC by plang-psm

Fixes #1750

### What changes did you make and why did you make them ?

4 changes were made to the Contributing page:
  - The feature branch headings were added to the table of contents. (eg. 2.8 Working off a feature branch).
  - The feature branch information/guide was placed below section 2.7.
  - The "Resolving a merge conflict on GitHub" link was placed under 4.2a Hack for LA resources.
  - This was not part of the action items but the table of contents link for 31.b.v was broken due to spelling of How. I changed the 'H' to an 'h' which then fixed the link.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

![image](https://user-images.githubusercontent.com/101952500/190558473-2d99b661-ca9d-43de-a75a-1ab51ab3938e.png)

![image](https://user-images.githubusercontent.com/101952500/190558539-367aa790-da5b-4505-b536-95bbfe38b25a.png)

![image](https://user-images.githubusercontent.com/101952500/190558570-635fafc0-a809-4857-96f7-8e4c40c27d90.png)

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
![image](https://user-images.githubusercontent.com/101952500/190558662-ad016405-c89f-41d5-941f-ac71bc33bf56.png)

![image](https://user-images.githubusercontent.com/101952500/190558401-d657d4a6-d1c8-42f8-ba2c-977f910a90a7.png)

![image](https://user-images.githubusercontent.com/101952500/190558413-da6f66b4-7e1f-4c0d-bd5c-9a74cd666169.png)

</details>

2022-09-16 20:13 UTC, arpitapandya commented
ETA: 2022-09-16
Availability: 6hrs

2022-09-18 00:08 UTC, neevliberman commented
ETA: 2022-09-17
Availability: 4hrs

2022-09-18 00:15 UTC, neevliberman reviewed
This all looks great! I'm sure it's nothing but just to make sure nothing breaks before approving this PR I'm curious to know why the format is different for the "merge 1 commit into gh-pages from add-feature-branch-to-contributing-1750" at the top of the page? I'm unsure why the parts explicitly saying "hackforla:" and "plang-psm:" t(heir username) seem to be missing from this PR.

2022-09-18 00:27 UTC, plang-psm commented
Hey @neevliberman , I wasn't 100% sure of the process to making a change to the contribution page which may have been my mistake. I believe I edited the Hack for LA repo instead of my own repo. Should I go back and resubmit?

2022-09-18 00:54 UTC, neevliberman commented
> Hey @neevliberman , I wasn't 100% sure of the process to making a change to the contribution page which may have been my mistake. I believe I edited the Hack for LA repo instead of my own repo. Should I go back and resubmit?

Hmm interesting... I may not be the best person to ask since I'm not really an expert at Git but i can try. When you created this branch that you made the changes on, did you create it off of the gh-pages branch? Also, can you type in `git remote -v` to your console while in the git repo and let me know what it says? Again, it's possible that the steps you took were fine, but we just want to be sure!

2022-09-18 01:43 UTC, arpitapandya requested changes
@plang-psm I am seeing the branch you created doesn't come from your website repo. Please go to your website repo and create the branch, not directly on hackforla-website. It should be in your GitHub website repo, similar way as you worked on previous issues.

If you need help, feel free to dm me on slack. Happy to help.
![comingfromwrongplace](https://user-images.githubusercontent.com/66761308/190881931-3c17c7cf-fa9a-4d8c-a839-10406c25d3bf.PNG)

2022-09-18 01:47 UTC, arpitapandya commented
> Hey @neevliberman , I wasn't 100% sure of the process to making a change to the contribution page which may have been my mistake. I believe I edited the Hack for LA repo instead of my own repo. Should I go back and resubmit?

Once you create new PR, we can close this PR

2022-09-19 20:19 UTC, closed without merging

2022-09-19 20:20 UTC, plang-psm commented
PR #3564 V2 add feature branch to contributing 1750 will replace this PR.