V2 add feature branch to contributing 1750
hackforla/website pull request #3564
Opened 2022-09-19 20:15 UTC by plang-psm

Fixes #1750

*** Please note this version will replace PR #3558.

### What changes did you make and why did you make them ?

4 changes were made to the Contributing page:
  - The feature branch headings were added to the table of contents. (eg. 2.8 Working off a feature branch).
  - The feature branch information/guide was placed below section 2.7.
  - The "Resolving a merge conflict on GitHub" link was placed under 4.2a Hack for LA resources.
  - This was not part of the action items but the table of contents link for 31.b.v was broken due to the spelling of How. I changed the 'H' to an 'h' which then fixed the link.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

![image](https://user-images.githubusercontent.com/101952500/190558473-2d99b661-ca9d-43de-a75a-1ab51ab3938e.png)

![image](https://user-images.githubusercontent.com/101952500/190558539-367aa790-da5b-4505-b536-95bbfe38b25a.png)

![image](https://user-images.githubusercontent.com/101952500/190558570-635fafc0-a809-4857-96f7-8e4c40c27d90.png)

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
![image](https://user-images.githubusercontent.com/101952500/190558662-ad016405-c89f-41d5-941f-ac71bc33bf56.png)

![image](https://user-images.githubusercontent.com/101952500/190558401-d657d4a6-d1c8-42f8-ba2c-977f910a90a7.png)

![image](https://user-images.githubusercontent.com/101952500/190558413-da6f66b4-7e1f-4c0d-bd5c-9a74cd666169.png)

</details>

2022-09-19 23:52 UTC, arpitapandya commented
Availability: 6 hrs
ETA: EOD 2022-09-20

2022-09-21 02:29 UTC, AzaniaBG commented
ETA: 09/22/2022 by 5 PM
Availability: 09/21/2022: 3 PM - 5 PM; 09/22/2022: 3 PM - 5 PM

2022-09-21 15:15 UTC, arpitapandya commented
@plang-psm There is a link missing to 2.8. When I click, gives error 404. I have other pointers which I would like to bring in next meeting.

2022-09-21 23:45 UTC, AzaniaBG commented on CONTRIBUTING.md
> +    - [**2.8 Working off a feature branch**]()
Please add a link here.

2022-09-21 23:47 UTC, AzaniaBG commented on CONTRIBUTING.md
> +```
Please add instructions to push changes to the remote branch after line 734 (to match the other guide).

2022-09-21 23:49 UTC, AzaniaBG commented on CONTRIBUTING.md
> +Create a pull request that is comparing across forks, from your branch to the feature branch with the following settings:
It might be helpful to specify that this is done on GitHub, rather than on the command line, but it's up to you :)

2022-09-22 00:04 UTC, AzaniaBG requested changes, later dismissed
@plang-psm ~ nice work on this issue. It was easy to understand all the changes you made. I left specific inline-comments for requested changes, summarized as follows:
* To match the instructions from [How to work off of a feature branch](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch), add the instruction to push changes after the instruction to stage and commit changes.
* The 2.8 link in the ToC needs a link
* You may want to add a link to the GitHub "resolving a merge conflict" in Section 2.8 so that people know where they can go if they run into that problem
* I tried the  3.1.b.v link on the [CONTRIBUTING.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#how-to-contribute-to-hack-for-la) and it is working. If it is working, it should not be changed, but maybe I'm not checking the correct link?

Let me know if you have any questions!

2022-09-23 17:17 UTC, arpitapandya commented
Here are the notes that have been discussed in earlier meetings and last Thursday's office hours.
- The linked issue is written in 2021.
- At this time, Adding the same instructions to the `contributing.md` from the wiki page only will not help us.
- We have to update it based on the ongoing feedback received by the devs and the problems devs face while working on `feature-homepage-launch` (which includes working on issue, creating PR, running docker, and reviewing PR) and not having awareness of having `feature-homepage-launch` branch on their machine first while reviewing if they never picked up the small issue relating to `feature-homepage-launch` and worked on `gh-pages` only
- Also, we have to be more concerned about the order as it also reflects on other pages such as the pre-work checklist template.
- I and Kathryn were in process of opening an issue related to updating the `contributing guide` and making the instructions clear, especially for new devs who have no prior experience.
- Since we found out that we already have the issue and as Phillip already started working on it, I can't update the issue. I respect Phillip's time and contribution to this.
- To close this and approve it to be merged, We have found it more intuitive to just add a link to the wiki page under the resources section for now and not to create more confusion without clarity.
- I will create a new issue and help update the guide based on the feedback and dm's I have been receiving and past reviews.
- The New issue will focus on the instructions of the order of both branches and how to work on issues, create PR and review it, possible mistakes, and how to resolve them; and make devs aware of the feature branch and running docker.
- I welcome all the suggestions.

2022-09-23 17:23 UTC, arpitapandya approved these changes
@plang-psm Thank you for making all the changes and making yourself available to address the changes. Thank you @AzaniaBG for catching up on the errors and leaving valuable reviews which were really helpful. Both of your's contribution and time is much appreciated on this PR.
Great job!! @plang-psm @AzaniaBG

2022-09-23 17:52 UTC, merged