Update contributing.md 3493
hackforla/website pull request #3633
Opened 2022-10-17 23:02 UTC by MattPereira

Fixes #3493 

### What changes did you make and why did you make them ?
- added `git pull upstream` instructions to the end of section **2.7.a**
- changed title of section **2.7.d**
- replaced `git fetch upstream` instructions with `git pull upstream` instructions in section **2.7.d**

These changes update `CONTRIBUTING.md` to incorporate the new best practices related to syncing a fork to the main Hack For LA website repository.

### Screenshots of Proposed Changes Of CONTRIBUTING.md

<details>
<summary>Visuals before changes are applied</summary>

![Old Section 2.7.a](https://user-images.githubusercontent.com/73561520/196296807-0ba26368-ee55-4f68-a3b3-e2eb440c559b.png)
![Old Section 2.7.d](https://user-images.githubusercontent.com/73561520/196296914-56e102f2-e800-416b-be09-e1a04946d855.png)

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
![New Section 2.7.a](https://user-images.githubusercontent.com/73561520/196298055-362ffe2a-0818-4eac-825c-7f8cfb6e9a17.png)

![New Section 2.7.d](https://user-images.githubusercontent.com/73561520/196298467-8c55ac25-eedf-4c21-a08a-b37ec805fba7.png)

</details>

2022-10-17 23:44 UTC, d-perez-8 commented
ETA: EOD 10/17/2022
Availability: 5 pm to 6 pm 10/17/2022

2022-10-18 00:07 UTC, jyaymie commented
Review ETA: 6pm PST 10/17/22
Availability: 1 hour

2022-10-18 00:30 UTC, jyaymie requested changes
Fantastic work! You were thoughtful in bolding appropriate words as consistently seen in the rest of the file. I'm not sure if a "brief screen capture" specifically means a video capture, but I feel like the photos you provided were sufficiently helpful.

2022-10-18 00:30 UTC, jyaymie commented on CONTRIBUTING.md
> +**IMPORTANT:** Before you push your local commits to your repository, sync your fork to the main Hack For LA website repository. git pull upstream will ensure that your local repository is up-to-date
I think "git pull upstream" needs to be formatted as inline code like so: "`git pull upstream` will ensure..."

2022-10-18 00:30 UTC, jyaymie commented on CONTRIBUTING.md
>  #### **2.7.d Working on an issue (4): Check upstream before you push**
It looks like the section title needs to be replaced with "Working on an issue (4): Pulling from upstream before you push"

2022-10-18 17:56 UTC, MattPereira commented on CONTRIBUTING.md
> +**IMPORTANT:** Before you push your local commits to your repository, sync your fork to the main Hack For LA website repository. git pull upstream will ensure that your local repository is up-to-date
I definitely overlooked the inline code formatting. Thank you for catching my error.

2022-10-18 17:58 UTC, MattPereira commented on CONTRIBUTING.md
>  #### **2.7.d Working on an issue (4): Check upstream before you push**
Nice job catching this omission as well. I am fortunate to have a keen eye like yours reviewing my pull requests!

2022-10-18 18:11 UTC, MattPereira commented
> Fantastic work! You were thoughtful in bolding appropriate words as consistently seen in the rest of the file. I'm not sure if a "brief screen capture" specifically means a video capture, but I feel like the photos you provided were sufficiently helpful.

I was also unsure about the ambiguity of "brief screen capture" as "screen capture" implies screenshot or image, but the adjective "brief" seems more likely to be describing a video. I did record a video, but ultimately decided using the screenshot from the official GitHub Docs was more helpful and easier to see.

2022-10-18 18:57 UTC, jyaymie approved these changes
All the requested changes have been incorporated. Solid work!

2022-10-19 00:55 UTC, gstemmann commented
Review ETA: 6 PM 3/24/2022
Availability: 6 hours

2022-10-19 01:08 UTC, gstemmann approved these changes
Awesome adding the important instructions to keep our team of developers can always be aware of best practices. And the screenshots look good.

2022-10-19 01:44 UTC, d-perez-8 approved these changes
This looks great 👍 You have made changes accordingly, and maintain the consistency of the document style. Thank you for your work!

2022-10-19 18:05 UTC, t-will-gillis commented
Review ETA: 2 PM 10/19/2022
Availability: 3 hours

2022-10-19 20:20 UTC, t-will-gillis approved these changes
Everything looks great and passes the ABCs. I like that you made **IMPORTANT** bold- I don't think that was explicit in the 'Action Items'. The screen shots look great. 

These changes and additions, especially to the first section, are really helpful. Thanks!

2022-10-20 00:51 UTC, merged