Project Page Wiki & Overview should not have alt text "/" issue # 2626
hackforla/website pull request #3649
Opened 2022-10-22 18:54 UTC by Unity7

Project Page Wiki & Overview should not have alt text "/" issue # 2626

Fixes #2626

### What changes did you make and why did you make them ?

  - Updated the logic that rendered the image's alt text from item.alt to page.alt and added quotations in order to render the full string from the md file
  -Updated the alt text for 100 Automation from 216 characters to 98 characters (issue suggest 100 character max)
  -Updated the alt text for 311 Data to provide a more clear description of the image (96 characters)

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

![image](https://user-images.githubusercontent.com/44449168/197357740-579c2c90-57ca-42bc-9070-5af85b0bff04.png)

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
![image](https://user-images.githubusercontent.com/44449168/197357842-6107552e-9b36-4cf9-84bd-ff838a8af02d.png)

</details>

2022-10-23 18:37 UTC, gstemmann commented
Availability: 6 hours
ETA: 10/31/2022

2022-10-23 18:39 UTC, AzaniaBG commented
Review availability: 3 PM - 4 PM 10/23/2022; 7 - 8 AM 10/24/2022; 7 - 8 AM 10/24/2022; 2 - 3 PM 10/24/2022
ETA: 10/25/2022 by 7 PM

2022-10-23 21:12 UTC, gstemmann approved these changes, later dismissed
The alt text you decided to go with seems much more descriptive and removes a lot of text that was not needed to accurately describe the images through text. Great Job.

2022-10-23 23:58 UTC, gstemmann reviewed
The alt text you decided to go with seems much more descriptive and removes a lot of text that was not needed to accurately describe the images through text. Great Job.
I also saw you didn't change any alt text for the [Civic Tech Index](https://www.hackforla.org/projects/civic-tech-index) and decided to change the 311 Data card when the two cards have similar content. Were you able to find a reason to skip changing the alt text in Civic Tech Index?

2022-10-23 23:59 UTC, MattPereira commented
**Availability**: 12 - 3 PM
**ETA**: End of Day10/23/22

2022-10-24 01:02 UTC, Unity7 commented
> I also saw you didn't change any alt text for the [Civic Tech Index](https://www.hackforla.org/projects/civic-tech-index) and decided to change the 311 Data card when the two cards have similar content. Were you able to find a reason to skip changing the alt text in Civic Tech Index?

Great question, I changed 100 Automation because the alt text description was over 200 characters. 311 Data was only 14 characters and provided no meaningful description. Lastly, I decided not to make any changes to Civic because it had a good description and reasonable character count. However, upon reviewing based on your comment I see that Civic Tech Index alt description is 120 words and can be condense by removing the first 4 words: "Civic Tech Index logo. A magnifying glass over the outline of the world map on the left "Civic Tech Index" on the right." which would make it 97 characters. If this needs to be done please request change.

2022-10-24 02:56 UTC, gstemmann requested changes
Please re-check word count on civic tech index.md file

2022-10-24 03:11 UTC, MattPereira commented
> Please re-check word count on civic tech index.md file

Good catch on noticing the [Alt text no more than 100 characters](https://fae.disability.illinois.edu/rulesets/IMAGE_4_EN/) resource provided by issue #2626 and great attention to detail checking the alt character count in the `_projects/civic-tech-index.md` file.

Nice work George! 👍

2022-10-24 16:21 UTC, Unity7 commented
> Please re-check word count on civic tech index.md file

I have updated the civic tech index.md file alt description to be under 100 characters by removing the first four words.

2022-10-24 17:02 UTC, MattPereira approved these changes, later dismissed
Great work on this one @Unity7 ! 👍 

The alt text now appears on the project pages resources cards img elements, and you modified all three project markdown files alt text properly by shortening the alt text to under 100 characters and accurately communicating the function of the image containing text by using the alt attribute. Excellent interpretation of the alt decision tree resource!

2022-10-24 21:40 UTC, gstemmann approved these changes, later dismissed
The civic tech index.md file alt description looks great and you did a great job!

2022-10-24 22:35 UTC, AzaniaBG commented on _projects/100-automations.md
> +alt: 'Logo shown as a 1 and two gears between open and closing brackets followed by the word Automations'
This type of image seems to fall between an [image used alone as a linked logo](https://www.w3.org/WAI/tutorials/images/functional/#example-1-image-used-alone-as-a-linked-logo) and a [logo image within link text](https://www.w3.org/WAI/tutorials/images/functional/#example-2-logo-image-within-link-text). It seems that it may be appropriate to either leave the alt text empty (`alt=""`) or use the alt text to indicate where the link will take the user, e.g., `alt="100 Automations home"`, as opposed to describing the actual image. The first box in [this decision tree](https://www.w3.org/WAI/tutorials/images/decision-tree/) suggests leaving leaving alt text empty if the image contains text that is also present as real text nearby, however the second box in the decision tree may also be applicable.

2022-10-24 22:35 UTC, AzaniaBG commented on _includes/resource-card.html
> +                <img src={{ page.image | absolute_url }} class='project-tmb-img project-start-guide-img' alt='{{ page.alt }}'/>
This may be considered a because the image is supplementary to link text to improve appearance and increase the clickable area. See [Decorative Image](https://www.w3.org/WAI/tutorials/images/decorative/) and [Decorative image as part of a text link](https://www.w3.org/WAI/tutorials/images/decorative/#example-2-decorative-image-as-part-of-a-text-link) for details. If you decide the image falls within either category, the alt text can be empty.

2022-10-24 22:37 UTC, AzaniaBG reviewed
Hey @Unity7 ~ amazing work on this issue. You put a lot of thought into writing the alt text for these images, and I like that you limited the text to 100 characters. A few things to consider:
1. I noticed you linked this PR to issue #3649 such that approval of this PR would close that issue. Your comment says this PR "Fixes #3649", but I'm wondering if instead it should read "Closes #3649". Can you decide which would be most appropriate?
2. I think the alt text can be more concise, and may need to describe its function, i.e., that it links to a specific resource. I found [this resource](https://www.w3.org/WAI/tutorials/images/functional/), which has been added to issue 3649. It discusses how to handle alt text for a logo image with a link. I believe this will be helpful in making the alt text more concise. I've added inline comments with more detail on this concept.

2022-10-25 20:40 UTC, MattPereira commented on _projects/100-automations.md
> +alt: 'Logo shown as a 1 and two gears between open and closing brackets followed by the word Automations'
After seeing Azania's astute evaluation of the W3C documentation and reviewing the links she posted, I am inclined to agree with her assessment that the alt text should be either empty or used to indicate where the link will take the user. Personally, I think it would be nice to have the alt text describe the destination of the link, but as Azania explained, both options seem applicable for this case.

2022-10-25 20:56 UTC, AzaniaBG commented on _projects/100-automations.md
> +alt: 'Logo shown as a 1 and two gears between open and closing brackets followed by the word Automations'
Thanks for the input, @MattPereira. The whole topic was pretty complex so I wasn't really sure what to make of it 😅

2022-10-26 01:09 UTC, Unity7 commented on _projects/100-automations.md
> +alt: 'Logo shown as a 1 and two gears between open and closing brackets followed by the word Automations'
> After seeing Azania's astute evaluation of the W3C documentation and reviewing the links she posted, I am inclined to agree with her assessment that the alt text should be either empty or used to indicate where the link will take the user. Personally, I think it would be nice to have the alt text describe the destination of the link, but as Azania explained, both options seem applicable for this case.

Is the alt attribute being used anywhere else on the website? If this is to be a unique alt text just for the resources portion then we can hard code the alt text to be blank alt="". If you want to still have the alt text and a secondary that might say "Logo home"  only for resources then we would have to add a secondary alt text attribute in the md file, otherwise it has to be blank so that the more descriptive alt text can still be used on other pages. @AzaniaBG

2022-10-26 01:20 UTC, Unity7 commented
> Member

1) I am not sure what you are talking about the PR # is 3649 and linked to issue #2626, might be due to my lack of understanding in the process.

2) Is the alt attribute being used anywhere else on the website? If this is to be a unique alt text just for the resources portion then we can hard code the alt text to be blank alt="". If you want to still have the alt text and a secondary that might say "Logo home" only for resources then we would have to add a secondary alt text attribute in the md file, otherwise it has to be blank so that the more descriptive alt text can still be used on other pages

2022-10-26 02:41 UTC, AzaniaBG commented
> > Member
> 
> 1. I am not sure what you are talking about the PR # is 3649 and linked to issue [Individual project pages' Wiki and Overview should not have alt="/" #2626](https://github.com/hackforla/website/issues/2626), might be due to my lack of understanding in the process.
> 2. Is the alt attribute being used anywhere else on the website? If this is to be a unique alt text just for the resources portion then we can hard code the alt text to be blank alt="". If you want to still have the alt text and a secondary that might say "Logo home" only for resources then we would have to add a secondary alt text attribute in the md file, otherwise it has to be blank so that the more descriptive alt text can still be used on other pages

@Unity7 ~ I think we resolved this question at tonight's team meeting. Sorry for any confusion!

2022-10-26 02:55 UTC, AzaniaBG commented on _projects/100-automations.md
> +alt: 'Logo shown as a 1 and two gears between open and closing brackets followed by the word Automations'
@Unity7 ~ I believe the alt attribute is used in two different files: 1. for projects and 2. for _includes/resource-card.html. The blank alt text or alt text that indicates the target page would relate to the projects. Let me know if you're free to discuss on Slack in more detail.

2022-10-27 00:01 UTC, Unity7 commented on _projects/100-automations.md
> +alt: 'Logo shown as a 1 and two gears between open and closing brackets followed by the word Automations'
> @Unity7 ~ I believe the alt attribute is used in two different files: 1. for projects and 2. for _includes/resource-card.html. The blank alt text or alt text that indicates the target page would relate to the projects. Let me know if you're free to discuss on Slack in more detail.

@AzaniaBG Thanks for clarifying with me. To summarize, for the resources pages it looks like the full alt text description should be used. This is consistent with the changes we have already made. Please let me know there is anything else needed on this. Thank you

2022-10-27 14:54 UTC, AzaniaBG commented on _projects/100-automations.md
> +alt: 'Logo shown as a 1 and two gears between open and closing brackets followed by the word Automations'
@Unity7 ~ thanks for discussing and clarifying this issue with me. If you do not believe the images on the resource cards constitute [Decorative Images](https://www.w3.org/WAI/tutorials/images/decorative/#example-2-decorative-image-as-part-of-a-text-link), you can use the alt text you've already written. Otherwise, use an empty alt attribute (`alt=""`). The decision is up to you! :)

2022-10-27 22:31 UTC, Unity7 commented on _projects/100-automations.md
> +alt: 'Logo shown as a 1 and two gears between open and closing brackets followed by the word Automations'
> @Unity7 ~ thanks for discussing and clarifying this issue with me. If you do not believe the images on the resource cards constitute [Decorative Images](https://www.w3.org/WAI/tutorials/images/decorative/#example-2-decorative-image-as-part-of-a-text-link), you can use the alt text you've already written. Otherwise, use an empty alt attribute (`alt=""`). The decision is up to you! :)

Yes I believe we should keep the changes already made.

2022-10-29 23:59 UTC, esantiano commented
ETA: End of Day10/31/22
Availability: 3- 5 PM

2022-10-31 16:46 UTC, esantiano submitted a review, later dismissed
Hey @Unity7, 

Great job cutting down on the 100-automations alt description. From what I understand from the issue it looks like there are a couple more projects files that need the same changes. 

Here's a list of project files that might need to be changed: 
- access-the-data.md
- website.md 
- youthjusticenav.md

hope this helps!

2022-10-31 19:10 UTC, MattPereira requested changes, later dismissed
After reviewing the [alt Decision Tree](https://www.w3.org/WAI/tutorials/images/decision-tree/), I think the images that contain text (displayed on the individual project page's resource cards) are "only shown for visual effects". In this case, the [decorative images](https://www.w3.org/WAI/tutorials/images/decorative/) appear to supplement the link text to improve appearance and increase the clickable area, which means the alt text should be an empty string according to the docs. 

From the perspective of the users, I wonder if it makes sense for them to listen to the screen reader recite "311 Data Logo depicted with squiggly lines and the numbers 311" when the image in question is just being used to decorate the link to a project's "Wiki", "Overview", or "Readme" page

2022-10-31 20:36 UTC, gstemmann reviewed
Yes, it looks like the proper way to set the alt text here is to leave an empty string. Thanks for all your hard work on this! @Unity7

2022-10-31 21:51 UTC, AzaniaBG commented
Review availability: 11/1/2022 3 - 5 PM
ETA: 11/1/2022 by 7 PM

2022-11-01 23:34 UTC, AzaniaBG submitted a review, later dismissed
@Unity7 ~ you've done an excellent job on this issue, which has required a lot of work. I requested changes (see inline comments) based on [Bonnie's comment on this issue](https://github.com/hackforla/website/issues/2626#issuecomment-1297790151). 
PS: In reviewing this issue, I realized the alt text on the [projects page](http://localhost:4000/projects/) does not need to be modified; only the alt text on the individual project pages need to be fixed.

2022-11-01 23:34 UTC, AzaniaBG commented on _includes/resource-card.html
> +                <img src={{ page.image | absolute_url }} class='project-tmb-img project-start-guide-img' alt='{{ page.alt }}'/>
Please change the alt text based on [this comment](https://github.com/hackforla/website/issues/2626#issuecomment-1297790151) from Bonnie

2022-11-01 23:34 UTC, AzaniaBG commented on _projects/100-automations.md
> +alt: 'Logo shown as a 1 and two gears between open and closing brackets followed by the word Automations'
As discussed in [this thread](https://github.com/hackforla/website/pull/3649/files#r1003830445), the alt text should either be empty (`alt=""`) or it should indicate where the link will take the user, e.g., for the 100 Automations link, the alt text would be something like `alt="100 Automations" home`; for the 311 Data link, alt text would be `alt="311 Data home`, etc.

2022-11-04 15:06 UTC, Unity7 commented
Availability: Going on vacation
Blockers: 2 week vacation
ETA: 11/26/22

2022-11-12 19:49 UTC, DmitriiTsy commented
Availability: 3 hours
ETA: 11/12/2022

2022-11-23 01:22 UTC, Unity7 commented
> @Unity7 ~ you've done an excellent job on this issue, which has required a lot of work. I requested changes (see inline comments) based on [Bonnie's comment on this issue](https://github.com/hackforla/website/issues/2626#issuecomment-1297790151). PS: In reviewing this issue, I realized the alt text on the [projects page](http://localhost:4000/projects/) does not need to be modified; only the alt text on the individual project pages need to be fixed.

Please let me know if this is an accurate interpretation of the desired changes. 
1) Revert all changes to the alt text descriptions
2) GitHub, Slack, and Getting Started are using SVGs which cannot have an alt attribute. There is nothing to be done for those. On images that are rendered img, hard code the alt text to "Projects" based on Bonnie's comment.

2022-11-30 03:53 UTC, Unity7 commented on _includes/resource-card.html
> +                <img src={{ page.image | absolute_url }} class='project-tmb-img project-start-guide-img' alt='{{ page.alt }}'/>
changed alt text to project per Bonnie's comment

2022-11-30 03:54 UTC, Unity7 commented
> Hey @Unity7,
> 
> Great job cutting down on the 100-automations alt description. From what I understand from the issue it looks like there are a couple more projects files that need the same changes.
> 
> Here's a list of project files that might need to be changed:
> 
> * access-the-data.md
> * website.md
> * youthjusticenav.md
> 
> hope this helps!

According to Bonnie's comment we do not need to change the md files.

2023-01-24 17:31 UTC, MattPereira approved these changes
@Unity7 sincere apologies from the merge team that this took so long to get figured out. 

You did a great job here and we let you down.

2023-01-24 17:32 UTC, MattPereira commented
Merging this PR after discussion about how to address resource card images that are SVGs at the [Dev/PM Meeting on 2023-01-23](https://github.com/hackforla/website/issues/2607#issuecomment-1399599452)

2023-01-24 17:34 UTC, merged