Improved errorlog  in add-label.js #2438
hackforla/website pull request #3652
Opened 2022-10-24 07:53 UTC by Suman2795

Fixes #2438 

### What changes did you make and why did you make them ?
   Made improvements to the error logs in add-label.js file

  - In line no 214, for function removeLabels updated the catch statement to retrieve the error
  -In line no 235, for function addLabels updated the catch statement to retrieve the error
  -In line no 249, for function postComment updated the catch statement to retrieve the error
  -In line no 283, for function getAssignees updated the catch statement to retrieve the error

2022-10-24 16:36 UTC, t-will-gillis commented
Review ETA: 5 PM 10/25
Availability: 10-5 Tuesday

2022-10-24 18:49 UTC, jyaymie commented
Review ETA: 1pm 10/24/22
Availability: Now through 1pm

2022-10-24 19:18 UTC, jyaymie requested changes
Fantastic work, @Suman2795! You linked the correct issue and found the appropriate functions to modify despite the difference in line numbers. There are just a few things I noticed, which I marked as inline comments. Let me know if you think otherwise!

2022-10-24 19:18 UTC, jyaymie commented on github-actions/add-update-label-weekly/add-label.js
>    } catch {
I believe the catch needs to take in `err` as a parameter.

2022-10-24 19:18 UTC, jyaymie commented on github-actions/add-update-label-weekly/add-label.js
> +      console.error(`Function failed to remove labels.Please refer to the error below: \n`,err);
It's a good idea to add a space between the two sentences to make it more readable. I would also add a space between the comma and `err`.

2022-10-24 19:18 UTC, jyaymie commented on github-actions/add-update-label-weekly/add-label.js
> +    console.error(`Function failed to add labels.Please refer to the error below:\n`,err);
This is probably me just being nit-picky, so this one's up to you! I notice an inconsistency with the error messages, particularly with the spacing around `\n`. I recommend sticking with one format and using it for all your error messages.

2022-10-24 22:16 UTC, t-will-gillis commented on github-actions/add-update-label-weekly/add-label.js
> +      console.error(`Function failed to remove labels.Please refer to the error below: \n`,err);
I would also opt for the space between the period at the end of the first sentence and the start of the second. (As far as the spaces at  "    below: \n', err  " , my only observation is that I would opt for consistency- whichever way you choose to use spaces in all four of the changes) 

My other open question/observation is regarding the formatting of the console.error message itself. I may be wrong here- and if I am I apologize and feel free to ignore me- but I am unable to duplicate the console message when formatted as shown, however these two will work with backticks: 

console.error(`Function...below: \n` + err)    OR
console.error(`Function...below: \n ${err}`)

2022-10-24 22:25 UTC, t-will-gillis commented on github-actions/add-update-label-weekly/add-label.js
>    } catch {
I also believe the `err` parameter is needed

2022-10-24 22:29 UTC, t-will-gillis requested changes
Hi @Suman2795 - Suman great work with the error log edits and tracking down the correct line numbers! I am adding a couple of comments to Jamie's, which I hope are useful. Thanks!

2022-10-27 17:09 UTC, t-will-gillis commented on github-actions/add-update-label-weekly/add-label.js
>    } catch {
I see the (err) parameter at Line 234 in the updated code- looks good thanks!

2022-10-27 17:10 UTC, t-will-gillis commented on github-actions/add-update-label-weekly/add-label.js
> +      console.error(`Function failed to remove labels.Please refer to the error below: \n`,err);
Hi @Suman2795 - Thank you for the adding the space between sentences and making the four console.error() changes consistent in construction- very 'Clean'. This looks great.

2022-10-27 17:10 UTC, t-will-gillis approved these changes

2022-10-27 23:17 UTC, MattPereira commented
Review ETA: End of Day 10/27/22
Availability: 2 hours

2022-10-27 23:34 UTC, MattPereira approved these changes
Excellent work @Suman2795 ! :+1: 

You updated the catch blocks to log the exact error when the parent function fails, which will be much more helpful for debugging. Additionally, I see you made all of the changes requested by @jyaymie and @t-will-gillis and now all of the `console.error`'s have matching spacing. 

Good teamwork everyone!

2022-10-28 20:48 UTC, jyaymie approved these changes

2022-10-29 23:10 UTC, esantiano commented
Review ETA: 10/29/22
Availability: 3 - 5PM

2022-10-29 23:13 UTC, esantiano approved these changes
Hey @Suman2795,

The changes you made look nice and consistent, its a lot easier to understand what specific functions are failing and why. Nice job!

2022-10-30 18:54 UTC, merged