Convert project profile card update template into github issue form
hackforla/website pull request #3672
Opened 2022-10-28 19:26 UTC by MattPereira

Fixes #2292

### What changes did you make and why did you make them ?

  - Created a GitHub issue form to replace the current markdown issue template in order to streamline and simplify the process of issue creation. The user creating the issue will no longer have to replace text in markdown format.
  - Converted "Project Name" and "Project Card URL" into drop-downs with one option for every HFLA project
  - Converted action item checklist from [current issue template](https://github.com/hackforla/website/blob/gh-pages/.github/ISSUE_TEMPLATE/project-profile-card-review-and-update.md) into yes/no drop-downs followed by an input area as requested by Bonnie at the Sunday meeting. Users of the form will be required to indicate if they wish to change each item or not.
  - Converted "status" item to a dropdown with the options: "active", "completed", or "on hold".
  - Deleted the old markdown template

#### [Current Issue Template](https://github.com/hackforla/website/blob/gh-pages/.github/ISSUE_TEMPLATE/project-profile-card-review-and-update.md)

#### [New Github Issue Form](https://github.com/MattPereira/website/blob/convert-project-profile-card-2292/.github/ISSUE_TEMPLATE/project-profile-card-review-and-update.yml)

2022-10-28 20:37 UTC, DmitriiTsy commented
ETA: Morning 10/29/22
Availability: 4 hours

2022-10-29 17:29 UTC, DmitriiTsy approved these changes, later dismissed
@MattPereira 
- All the changes look correct 
- Linters are okay as well as all checks 
You did a really great job. 👍

2022-10-29 23:55 UTC, esantiano commented
ETA: 10/29/22
Availability: 3-5PM

2022-10-31 15:16 UTC, esantiano commented on .github/ISSUE_TEMPLATE/project-profile-card-review-and-update.yml
> +        - "HelloGov"
HelloGov to HelloGOV

2022-10-31 15:19 UTC, esantiano commented on .github/ISSUE_TEMPLATE/project-profile-card-review-and-update.yml
> +        - "brigade-organizers-playbook.md"
switch lines with ballot-nav.md for alphabetical order

2022-10-31 15:38 UTC, esantiano commented on .github/ISSUE_TEMPLATE/project-profile-card-review-and-update.yml
> +        - "Spare"
Include an "other" option for unlisted projects that have an existing project url

2022-10-31 15:42 UTC, esantiano requested changes
Hey @MattPereira, 

The new issue template looks way better compared to the previous, I just had a few suggestions in regards to the spelling, ordering, and options available in the Project Name field.

2022-10-31 16:51 UTC, gstemmann commented on .github/ISSUE_TEMPLATE/project-profile-card-review-and-update.yml
> +        - "Spare"
Your notes for @MattPereira for changes, I think, are great. 
For adding "other" to the projects list, I wonder if that may lead to multiple issue creators mistakenly using "other" when the projects are already listed.

2022-10-31 16:52 UTC, gstemmann commented
ETA: Morning 11/4/22
Availability: Tuesday 6-9pm

2022-10-31 17:53 UTC, MattPereira commented on .github/ISSUE_TEMPLATE/project-profile-card-review-and-update.yml
> +        - "Spare"
I wonder if the "project profile card update" issue template is only used for updating the "Current Projects" listed on the [hfla projects page](https://www.hackforla.org/projects/) or if this issue form is also used for other internal record keeping not displayed on the website.

2022-10-31 17:58 UTC, MattPereira commented
> Hey @MattPereira,
> 
> The new issue template looks way better compared to the previous, I just had a few suggestions in regards to the spelling, ordering, and options available in the Project Name field.

Hi @esantiano ,

I appreciate the kind words and astute review. Great catch on the casing of HelloGOV and the alphabetical listing error. I am also open to discussion on how to better handle the potential edge case of unlisted projects.

2022-11-04 22:31 UTC, esantiano approved these changes, later dismissed
Hey @MattPereira, 

Thanks for addressing my comments, this looks good to me. Keep up the good work!

2022-11-05 15:53 UTC, luiderek commented
From a UX perspective, having a drop down to reveal a yes/no split seems frustrating. Is the checkbox possibly something than can be used? I know it's something that exists in issue forms, but not sure how nicely interaction cooperates with them.

2022-11-05 17:40 UTC, MattPereira commented
> From a UX perspective, having a drop-down to reveal a yes/no split seems frustrating. Is the checkbox possibly something than can be used? I know it's something that exists in issue forms, but not sure how nicely interaction cooperates with them. It's something that'd only save a click, but with 14 mandatory drop-downs I think they add up.

I agree with you 100% about having so many yes/no drop-downs being an unpleasant user experience. However, as noted in the pull request creation comment: 
>Converted action item checklist from [current issue template](https://github.com/hackforla/website/blob/gh-pages/.github/ISSUE_TEMPLATE/project-profile-card-review-and-update.md) into yes/no drop-downs followed by an input area as requested by Bonnie at the Sunday meeting.

I used Bonnie's [communities-of-practice-information-updates.yml](https://github.com/hackforla/website/blob/gh-pages/.github/ISSUE_TEMPLATE/communities-of-practice-information-updates.yml) as a guide to build this new form, and I assume she has a good reason for choosing the yes/no drop downs.

2022-11-06 23:24 UTC, gstemmann submitted a review, later dismissed
The new form looks great!  And much cleaner than the look with the checkboxes. Great Job!

2022-11-07 15:17 UTC, jyaymie commented
Review ETA: 11/7/22 9am
Availability: 11/7/22 Now - 9am

2022-11-07 16:20 UTC, jyaymie requested changes
Such thorough work, @MattPereira! You followed all the items in the linked issue, including making a comment with your defined form elements and behavior, and I witnessed how highly communicative you were with the team throughout this entire process. I requested some very minor edits, but wow! Impressive job.

Edit: I'm curious! How did you manage to default the "Update Test Site Link?" dropdown to `Selection: None`. I noticed it in the link to your GH form, but I couldn't find the code for it.

2022-11-07 16:20 UTC, jyaymie commented on .github/ISSUE_TEMPLATE/project-profile-card-review-and-update.yml
> +labels: ["P-Feature: Project Info and Page", "role: back end/devOps, role: front end, Size: Small, size: 0.5pt, time sensative"]
I'd remove the end quotation in `"P-Feature: Project Info and Page",` to improve readability and correct the typo from `sensative` to `sensitive`.

2022-11-07 16:20 UTC, jyaymie commented on .github/ISSUE_TEMPLATE/project-profile-card-review-and-update.yml
> +      label: Techonologies
Looks like an extra "o" snuck in the Technologies label.

2022-11-07 16:20 UTC, jyaymie commented on .github/ISSUE_TEMPLATE/project-profile-card-review-and-update.yml
> +      label: "If YES on remove person(s) edit the below to provide the information required. If NO, delete the template in the field below:"
Grammar-wise, I think there should be a comma after `person(s)`.

2022-11-07 16:20 UTC, jyaymie commented on .github/ISSUE_TEMPLATE/project-profile-card-review-and-update.yml
> +      options:
Pickiest comment of all! For consistency's sake, I'd put these dropdown options in all caps.

2022-11-07 16:20 UTC, jyaymie commented on .github/ISSUE_TEMPLATE/project-profile-card-review-and-update.yml
> +      value: "As a product manager, I want my project's details to be up to date on the HackforLA website."
I'm not sure if `HackforLA` needs to have spaces between the words? I know no spaces were included in the original card, but I don't see the organization's name written like that anywhere on the website.

2022-11-07 19:14 UTC, MattPereira commented on .github/ISSUE_TEMPLATE/project-profile-card-review-and-update.yml
> +labels: ["P-Feature: Project Info and Page", "role: back end/devOps, role: front end, Size: Small, size: 0.5pt, time sensative"]
Nice catch on the readability issue here

2022-11-07 19:16 UTC, MattPereira commented on .github/ISSUE_TEMPLATE/project-profile-card-review-and-update.yml
> +      label: Techonologies
I definitely should have thought to turn on a spell checking extension for this issue :facepalm:

2022-11-07 19:18 UTC, MattPereira commented on .github/ISSUE_TEMPLATE/project-profile-card-review-and-update.yml
> +      label: "If YES on remove person(s) edit the below to provide the information required. If NO, delete the template in the field below:"
Superb attention to detail!

2022-11-07 19:18 UTC, MattPereira commented on .github/ISSUE_TEMPLATE/project-profile-card-review-and-update.yml
> +      options:
I couldn't agree more!

2022-11-07 19:19 UTC, MattPereira commented on .github/ISSUE_TEMPLATE/project-profile-card-review-and-update.yml
> +      value: "As a product manager, I want my project's details to be up to date on the HackforLA website."
I'm on team spaces with you!

2022-11-07 19:36 UTC, MattPereira commented
> Edit: I'm curious! How did you manage to default the "Update Test Site Link?" dropdown to `Selection: None`. I noticed it in the link to your GH form, but I couldn't find the code for it.

Oops, this was actually an error. It looks like GitHub issue forms defaults dropdowns to `Selection:None` if you do not include `required: true` for the input validations. 

As always, I appreciate your generous compliments and superbly meticulous reviews @jyaymie!

2022-11-07 20:17 UTC, jyaymie commented
> > Edit: I'm curious! How did you manage to default the "Update Test Site Link?" dropdown to `Selection: None`. I noticed it in the link to your GH form, but I couldn't find the code for it.
> 
> Oops, this was actually an error. It looks like GitHub issue forms defaults dropdowns to `Selection:None` if you do not include `required: true` for the input's validations.
> 
> As always, I appreciate your generous compliments and superbly meticulous reviews @jyaymie!

Learned something new. Way to figure that out!

2022-11-07 20:18 UTC, jyaymie submitted a review, later dismissed

2022-11-08 03:54 UTC, jdingeman reviewed
Hi @MattPereira, this looks very good. Nice job. Did you bring this up with Product yet to confirm the design?

2022-11-08 16:35 UTC, MattPereira commented
> Hi @MattPereira, this looks very good. Nice job. Did you bring this up with Product yet to confirm the design?

Hey @jdingeman,  I appreciate your review! 

I reached out in slack about two weeks ago for direction about how to complete the final "Signoff by Product" action item:
https://hackforla.slack.com/archives/C4UM52W93/p1666652792228699?thread_ts=1666644066.968969&cid=C4UM52W93

If there are any additional steps I need to take to move forward please let me know.

2022-11-12 18:36 UTC, DmitriiTsy submitted a review, later dismissed

2022-11-14 01:48 UTC, jdingeman approved these changes
Nice job @MattPereira! Thanks for your patience. After commenting on #2292, putting the appropriate labels, and moving to New Issue Approval, you can move on to your next issue.

2022-11-14 01:48 UTC, merged