Linked and stored visual demo pdf for pull request review in contributing wiki
hackforla/website pull request #3696
Opened 2022-11-05 07:04 UTC by patrickohh

Fixes #3651 

### What changes did you make and why did you make them ?

  - Stored demo pdf in assets/pdf folder within repository
  - Linked demo to phrase "visual demo on pull request reviews" under section 3.1.c in contributing wiki 
  -

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

![image](<img width="300" alt="before pull 115" src="https://user-images.githubusercontent.com/50275188/200107244-42e74991-95fa-4e8e-b0cc-45aa9ac9d840.PNG">)

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
![image](<img width="300" alt="after 115" src="https://user-images.githubusercontent.com/50275188/200107281-783daa96-c49d-4dc8-9c2a-19981399cc73.PNG">)

</details>

2022-11-05 15:16 UTC, esantiano commented
ETA: 11/5/2022
Availability: 8-10AM

2022-11-05 15:54 UTC, esantiano approved these changes, later dismissed
Hey @patrickohh

Nice addition to the contributing page and I also liked your attention to detail on grammar. Overall great job!

2022-11-05 18:46 UTC, patrickohh commented
Hi @esantiano 
Thank you! I actually had some trouble figuring out if a download link would be better rather than just taking them to where the file is in the repository to view. Would a download link be more preferable?

2022-11-05 21:03 UTC, MattPereira commented
Review ETA: End of Day 11/5/22
Availability: 4 - 6 PM

2022-11-06 22:14 UTC, t-will-gillis commented
Review ETA: Sun 11/6 5 pm-ish
Availability: 3-5 pm

2022-11-06 23:33 UTC, t-will-gillis submitted a review, later dismissed
Hi @patrickohh- Your additions look great! Although I am not the person to answer your question above, I would have linked to the repository the same as you did. Good job

2022-11-07 03:48 UTC, MattPereira reviewed
Hi @patrickohh,

First of all, good work on this issue so far! I like the spot in `CONTRIBUTING.md` that you found to place the hyperlink to the pdf. It definitely makes the most sense since there is no section specifically dedicated to PR reviews. 

Also, I think the place you chose to store the pdf file makes sense. However, after browsing through all of the other media content that is used in the `CONTRIBUTING.md` file, I noticed that none of the media files are actually stored directly inside the website repository. Many of the images and gifs are stored at `src="https://user-images.githubusercontent.com/21162229/..."`. 

I wonder if it is possible to upload the pdf document to the same location as much of the other media since the file is relatively large at 12.9 MB, which appears to be much larger than any other file stored inside the website repository.

2022-11-07 20:41 UTC, patrickohh commented
@MattPereira I'll look into this and see if I can store it in the same place as all the other images!

2022-11-07 20:46 UTC, patrickohh commented
@MattPereira Seems like the images with the url: `src="https://user-images.githubusercontent.com/21162229/..."` are stored via a created issue or pull request. I don't know if this method is preferable over just storing it in a folder in the repository.

2022-11-07 21:13 UTC, jyaymie commented
Review ETA: 11/7/22 5pm
Availability: 11/7/22 Time-flexible

2022-11-07 21:40 UTC, jyaymie reviewed
Great job, @patrickohh! Perfect phrasing for the link.

@MattPereira does bring up a good point about the origin of the PDF. It may be worth reaching out to @blulady for confirmation on this. If storing the file in `assets/pdfs` is a-ok, I'd replace the file name's periods with dashes to follow the naming convention and remove "2" so there's no indication of another version of this file in the codebase. Basically: `How-to-Review-a-PR.pdf`.

2022-11-07 23:10 UTC, patrickohh commented
Hi @jyaymie, definitely will incorporate those changes and reach out to confirm on where to store the files. Thanks for the suggestion.

2022-11-08 00:06 UTC, jdingeman requested changes
Hi Patrick. Thanks for taking on this issue! Since this file is not necessarily going to be used publicly/outside of the organization, I think the best place to have the file would be in the [Google Drive](https://drive.google.com/drive/u/0/folders/1MPY9CKcfKKN7hpDCG46ARrRzRSM8d8OA). Developers accessing CONTRIBUTING.md are assumed to have access to the drive so it should be a safe place to store it and directly link it.

2022-11-08 00:09 UTC, patrickohh commented
@jdingeman Okay sounds good I will be sure to make the requested changes by tomorrow.

2022-11-08 18:54 UTC, patrickohh commented
Made the move of the document to the google drive and properly linked it in the contributing.md file,

2022-11-08 20:30 UTC, jyaymie approved these changes
I see you removed the file from `assets/pdfs` and instead uploaded it to the Drive in `HackforLA.org website > Developers`, which I think was an appropriate move. The link in the wiki worked beautifully. Awesome job, @patrickohh!

2022-11-11 01:30 UTC, jdingeman approved these changes
Nice job, Patrick! I will merge this after Arpita is done testing something with the linter. :smile:

2022-11-11 15:57 UTC, merged