Updated partners.yml file with program-areas field
hackforla/website pull request #3719
Opened 2022-11-15 06:44 UTC by patrickohh

Fixes #2459

### What changes did you make and why did you make them ?

  - Updated partners.yml file with appropriate program-areas field so liquid references are easier to implement
  - 
  -

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
No apparent visual changes. 

<details>
<summary>Visuals before changes are applied</summary>

![image](Paste_Your_Image_Link_Here_After_Attaching_Files)

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
![image](Paste_Your_Image_Link_Here_After_Attaching_Files)

</details>

2022-11-15 19:43 UTC, MattPereira commented
Review ETA: End of day 11/15/22
Availability: 7 - 10 PM

2022-11-15 23:26 UTC, jyaymie commented
Review ETA: 11/15/22 5pm
Availability: 11/15/22 Flexible

2022-11-16 00:06 UTC, jyaymie requested changes
This looks great, @patrickohh! You didn't miss a single partner. One more (small) thing - I might remove the dropdowns in the PR if they're not being used.

2022-11-16 00:06 UTC, jyaymie commented on _data/internal/partners.yml
> +  program-areas:
Based on the issue, I think the property should be `program-area` (singular).

2022-11-16 00:06 UTC, jyaymie commented on _data/internal/partners.yml
>    image: /assets/images/partners/la-county-homeless-initiative.png
I'm wondering if the info in the issue's [comment](https://github.com/hackforla/website/issues/2459#issuecomment-974919932), last edited 22 days ago, is the most updated version. For example, The LA County Homeless Initiative's image, described in the comment as `real-help-lasting-change.svg` is different from what is found here, `la-county-homeless-initiative.png`. Additionally, the image in the comment is not actually found in the current codebase, whereas the image here does exist.

2022-11-16 00:21 UTC, plang-psm commented
Review ETA: 11/20/22
Availability: 6 hrs

2022-11-16 01:07 UTC, patrickohh commented on _data/internal/partners.yml
> +  program-areas:
I'll be sure to update the field to this thanks!

2022-11-16 01:10 UTC, patrickohh commented on _data/internal/partners.yml
>    image: /assets/images/partners/la-county-homeless-initiative.png
I will ask in the upcoming meeting about this. Thanks for the heads up.

2022-11-16 01:13 UTC, patrickohh commented on _data/internal/partners.yml
> +  program-areas:
Alright just updated 'program-areas' to be 'program-area'

2022-11-16 01:49 UTC, plang-psm approved these changes
Looks good! Noticed you fixed the 'program-areas' to 'program-area', and the site ran normally after the changes. Good work!!

2022-11-16 03:58 UTC, patrickohh commented
Some differences in partners.yml compared to the information in this [comment](https://github.com/hackforla/website/issues/2459#issuecomment-974919932):
1. 'name: Los Angeles Department of Neighborhood Empowerment' (current) ; 'name: Empower LA' (comment)
2. 'name: Los Angeles Metro' (current); 'name: Metro' (comment)
3. 'name: Los Angeles Department of Transportation' (current); 'name: LADOT' (comment)   
4. 'image: /assets/images/partners/la-county-homeless-initiative.png' (current); 'image: /assets/images/partners/real-help-lasting-change.svg' (comment)

2022-11-16 04:45 UTC, Suman2795 commented
ETA:16/11/2022
Availability: 3 hours

2022-11-16 17:02 UTC, Suman2795 reviewed
There are differences in the image description of comment and the file but the program areas field added is done correct.

2022-11-16 19:03 UTC, MattPereira approved these changes
I agree with @Suman2795 . The `program-area` property has been correctly implemented as instructed by the issue. Concerns about discrepancies between the [comment](https://github.com/hackforla/website/issues/2459#issuecomment-974919932) and the current codebase(for two of the partners' `name` and `image` properties) may be warranted, but that seems to fall outside the scope of #2459. Given that the `link` property still matches between both sources, I think its safe to assume @patrickohh has properly correlated the `program-area` field value(s) for each partner.

2022-11-17 18:07 UTC, blulady commented on _data/internal/partners.yml
>    image: /assets/images/partners/la-county-homeless-initiative.png
We discussed this at a meeting, we're going to confirm the name changes with Bonnie on Sunday before merging.

2022-11-20 18:56 UTC, blulady commented
All changes were intentional continue as instructed.

2022-11-27 06:52 UTC, ExperimentsInHonesty commented on _data/internal/partners.yml
>    image: /assets/images/partners/la-county-homeless-initiative.png
Actually @patrickohh and @blulady I agree the changes are outside the scope.  I think we should accept the changes as is.  And fix anything else that we want changed after the pr has been accepted.  i will add a note to the issue to indicate the steps that come after.

2022-11-27 06:55 UTC, ExperimentsInHonesty commented
@merge team, please accept this pr if you are satisfied that the program-area changes have happened.  I'll leave a note on the issue about the remaining items that need to be audited before they can be addressed (in a new issue).

2022-11-27 08:43 UTC, jdingeman commented
Merging PR without "waiting for requirements to be met" since I can't seem to find the unresolved conversation. Any changes requested look like they were resolved in the thread.

2022-11-27 08:43 UTC, merged