On the events page, removed project information from the event location cards
hackforla/website pull request #3725
Opened 2022-11-16 08:49 UTC by roslynwythe

Fixes #3027

### What changes did you make and why did you make them ?

  - changes made to _events.scss creating new CSS classes including flexbox to hold the new event location card items as per the Figma design, using media queries for mobile and tablet breakpoints
  - changes to our-locations-content.html were only to replace old CSS class names with the new ones.  
  - updated Figma Event card section with Class, CSS, Uses, and Context Examples.  

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

![screencapture-hackforla-org-events-2022-11-16-00_43_52](https://user-images.githubusercontent.com/5314153/202131832-b92eb88e-8ed9-41b8-a34c-00a1bb4bdca3.png)

![desktop-hackforla-org-events-2022-11-16-00_47_08](https://user-images.githubusercontent.com/5314153/202132552-6a329904-a4dc-4b47-8956-1bd7b15df405.png)

</details>
<details>
<summary>Visuals after changes are applied</summary>
![375px-capture-localhost-4000-events-2022-11-14-19_35_54](https://user-images.githubusercontent.com/5314153/202130556-5100a6c7-68de-40c2-a7ab-3d62c375626e.png)

  
![1440px-capture-events-2022-11-14-19_08_53](https://user-images.githubusercontent.com/5314153/202133005-9b5c7dd5-ad0f-4743-89c5-a1a1d6599143.png)

</details>

2022-11-17 06:38 UTC, tunglinn commented
ETA: tomorrow night
Availability: 11/17 2-4pm

2022-11-17 07:00 UTC, tunglinn commented
So far, the only little issue I've found is in Figma.
<details><summary>.events-card should be .event-card</summary>

![image](https://user-images.githubusercontent.com/86996158/202378013-b740de0c-7b1e-42e9-b304-377c8b25b559.png)

![image](https://user-images.githubusercontent.com/86996158/202378104-92de49e2-2ce6-45f3-b03b-9f0acba788c4.png)

</details>

2022-11-17 19:29 UTC, roslynwythe commented
> So far, the only little issue I've found is in Figma.
> 
> .events-card should be .event-card

Thank you for noticing that.  I corrected the Figma file.

2022-11-19 05:42 UTC, tunglinn requested changes
<details><summary>On desktop view, the event cards are square and not rounded.</summary>

![image](https://user-images.githubusercontent.com/86996158/202836280-a2eb6b32-1ac0-4fec-8e76-3f1510078233.png)
<details>

I believe there's no default border radius for the card. There's only one for bp-below-tablet.

2022-11-20 20:23 UTC, roslynwythe commented
> On desktop view, the event cards are square and not rounded.
> I believe there's no default border radius for the card. There's only one for bp-below-tablet.

Thank you for reviewing this issue.  In the new design, the image files were modified to incorporate rounded corners into the PNG.  Unfortunately I had failed to add the images files before committing, so the updated images were not part of the reviewed branch.  I just pushed up those changes.

2022-11-21 23:37 UTC, roslynwythe commented
@tunglinn Requested changes have been made, waiting for review.  Thank you

2022-11-23 03:15 UTC, blulady commented
@tunglinn @MatthewBozin do you think you guys can review this before the holidays? <3

2022-11-25 21:13 UTC, MattPereira requested changes
Hey @roslynwythe , great work on this issue so far! :+1: 

A few things I hope to discuss:
- For the mobile view: The figma seems to indicate there should be `24px` of space in between each `.event-card` and that the size should all be `343px` by `343px`<details><summary><strong>See relevant screenshots</strong></summary>
![Screenshot from 2022-11-25 13-10-55](https://user-images.githubusercontent.com/73561520/204055654-9698ea82-8eec-4ba8-9155-a9e392eb82d6.png)
![figma](https://user-images.githubusercontent.com/73561520/204055411-2272fd57-88bf-4f32-a6bb-124976b06265.png)






</details>

- Also, I am curious if you were instructed to replace the DLTA.png, southla.png, and westside1.png image files ? (#3027 does not appear to indicate this is necessary)

2022-11-25 22:23 UTC, MattPereira requested changes

2022-11-25 22:23 UTC, MattPereira commented on _sass/components/_events.scss
> +  margin-top: 45px;
For the desktop view, it looks like the figma is instructing `48px` of space between the yellow covid alert and the row of event cards

![Screenshot from 2022-11-25 13-20-31](https://user-images.githubusercontent.com/73561520/204056673-56766393-c4c3-412a-a954-8268ec86c3fc.png)

2022-11-27 04:46 UTC, roslynwythe commented
> Hey @roslynwythe , great work on this issue so far! 👍
> 
> A few things I hope to discuss:
> 
> * I am curious if you were instructed to replace the DLTA.png, southla.png, and westside1.png image files since #3027 does not appear to indicate this is necessary
> * For the mobile view: The figma seems to indicate there should be `24px` of space in between each `.event-card` and that the size of each card should be `343px` by `343px`**See relevant screenshots**
>   ![Screenshot from 2022-11-25 13-10-55](https://user-images.githubusercontent.com/73561520/204055654-9698ea82-8eec-4ba8-9155-a9e392eb82d6.png)
>   ![figma](https://user-images.githubusercontent.com/73561520/204055411-2272fd57-88bf-4f32-a6bb-124976b06265.png)

@MattPereira thank you for your comments.  Since the Figma mobile design had a screen width of 375px, that is the screen width I used for testing the mobile view.  The images are 343px square at 375px screen width, and as the screen width increases, they will enlarge up to the maximum width of 414px at a screen width of 1440px.  This is my first front-end issue for Hfla so please advise if I have misunderstood the instructions.  Regarding the gap between the images, you are correct.  I'm puzzled because I had checked that at one point, but now I'm having a lot of trouble getting it right.   I'll work on this all day tomorrow if needed to get it right.  

Regarding the images, perhaps I should have inquired about the images, but my reasoning was that the images in Figma were updated with rounded corners, and so I assumed that I was supposed to use the new images in the design.  Please advise if that was incorrect.  

>

2022-11-28 01:10 UTC, roslynwythe commented
@MattPereira the branch has been updated with changes addressing the spacing between images in mobile view and the spacing between the header and images in fullscreen view.  I retained the new images with rounded corners.  I am available to discuss that issue now or at the Tues meeting.  I believe this is considered an "unresolved conversation" above.  

There is an additional commit to merge recent upstream changes.  I wasn't sure if it was safe to do a rebase (because the branch had already been pushed to Github) so I did a merge.  

Thank you for your time reviewing this issue.

2022-11-28 01:58 UTC, MattPereira approved these changes, later dismissed
I really appreciate all of your hard work, timely responses, and thoughtful changes on this pull request @roslynwythe !

You did a great job correcting the margins to match the figma design, and your explanation/approach to setting the mobile card sizes was superb. My apologies for not considering the figma starting screen width for mobile devices. I am still a little nervous about replacing the images, but I totally understand where you are coming from and its totally bizarre in the first place that some of the images have manually cropped corners rather than just using a CSS `border-radius` property to control the shape. 

Looking forward to discussing this with you and the team on Tuesday night to iron out the final details and hopefully get this merged! :+1:

2022-11-30 02:03 UTC, roslynwythe commented
Hi @MattPereira I just wanted to mention that the original images had an aspect ratio that didn't match the new design, and were also larger than necessary, so if we decide we want images without rounded corners, I suggest that we request suitable images from the design team.

2022-11-30 02:15 UTC, roslynwythe commented
Hi @MattPereira I just noticed a problem with the img alt text and just pushed the fix.

2022-11-30 18:48 UTC, roslynwythe commented
The objectives of this issue have been met, but the dev concluded that best practice would be to use images without manually cropped (rounded) corners, and to apply the rounded corners in CSS (border-radius style).   This was suggested by @MattPereira and confirmed by @plang-psm.  This will be addressed in a future issue.

2022-11-30 18:49 UTC, roslynwythe commented
@tunglinn please advise if you will be able to review.  Thank you

2022-12-01 17:57 UTC, MattPereira commented on _includes/events-page/our-locations-content.html
> +            <img class="location-image" src="../assets/images/hack-nights/southla.png" alt="South L.A"  />
Hey @roslynwythe , nice catch noticing all of the alt attributes were set to "westside".

I noticed you also removed the id attribute from each image, was this intentional?

Also, you might consider either removing the "." from "L.A" or adding the second "." so it looks like "L.A.". (I have no idea what the best practices is here for accessibility)

2022-12-01 19:34 UTC, tunglinn commented
@roslynwythe I won't be able to review this until Monday.

2022-12-01 20:03 UTC, roslynwythe commented on _includes/events-page/our-locations-content.html
> +            <img class="location-image" src="../assets/images/hack-nights/southla.png" alt="South L.A"  />
@MattPereira Thank you for your insightful comments.  

At one point I added id attributes to the images because I thought I needed to apply a distinct style to the last image, but that turned out to be unnecessary so I deleted them.  

You raise a valid and interesting point about the abbreviation "L.A.", that is, "Los Angeles" should either be abbreviated as "L.A." (more grammatically correct and used by the L.A. Times) or "LA" (which is widely used on the Hfla website).   It seems to me that "L.A." would be more accessible because a screen reader would recognize it as an abbreviation whereas the screen reader would try to pronounce "LA" as a word.   Another option, which may be the most accessible, is to skip the abbreviation and spell out "Los Angeles".   [@hackforla/product-managment](https://github.com/orgs/hackforla/teams/product-managment) Do we have any accessibility experts at Hfla whom we could consult?  It would be nice to have an accessible and consistent approach to abbreviating "Los Angeles" throughout the site.  But for now I changed it to "L.A." and pushed the change to github.com.

2022-12-08 00:35 UTC, roslynwythe commented
> 

Thank you.  I know its a busy time.

2022-12-08 03:21 UTC, tunglinn commented
@roslynwythe Looks like there's a merge conflict. Once that's resolved, this PR looks good!

2022-12-08 20:55 UTC, tunglinn submitted a review, later dismissed
Merge branches are correct. The changes fulfill the changes of the linked issue, with certain concerns being addressed in a future issue. For example, the rounded borders will be implemented through CSS in the future. I'm also assuming this will allow us to replace the current images with better quality images since it's just a tad blurry on my desktop right now.

2022-12-10 02:50 UTC, MattPereira requested changes
Hi @roslynwythe , 

This is a very minor detail, but I noticed the images you added seem to have a blue rectangle near the edges that does not appear to be a part of the original images.

![locations-cards](https://user-images.githubusercontent.com/73561520/206824940-427e7b37-e48c-41d0-94a7-20c037e75e96.png)

2022-12-14 01:24 UTC, roslynwythe commented
> Hi @roslynwythe ,
> 
> This is a very minor detail, but I noticed the images you added seem to show a thin blue rectangle near the edges that does not appear to be a part of the original images.
> 
> ![locations-cards](https://user-images.githubusercontent.com/73561520/206824940-427e7b37-e48c-41d0-94a7-20c037e75e96.png)

@MattPereira you have a great eye, thanks for catching that.  Those blue rectangles appear within the images I exported from Figma and appear to be related to shapes that the designer used to specify the space between the images. 

![figma-screenshot](https://user-images.githubusercontent.com/5314153/207481736-2dfb6a61-e5c1-48f0-aa57-15c0d8d1c220.JPG)
ed.  

I'm not sure how to proceed, any advice would be appreciated.

2022-12-14 21:59 UTC, roslynwythe commented
@MattPereira @tunglinn I re-imported the 3 location images from Figma.  There was a measuring layer in Figma containing spacing squares that were exported as part of the image, but after hiding that layer I was able to export the images without those blue rectangles.  Thank you again for reviewing this issue.

2022-12-15 20:36 UTC, MattPereira requested changes
Hey @roslynwythe ,

The desktop view is now showing the location images as squares with sharp edges. 

I think the simplest fix would be to add `border-radius: 24px` to the `.location-image` class in _events.scss

I noticed you added `border-radius: 5.8%` to the `$bp-below-tablet` media query for the `.location-image` class. I'm curious about your process for deciding to use a percentage value instead of pixels for the border radius. 

Also, if you do decide to add the `border-radius` property to `.location-image` outside of the media query, it will no longer be necessary inside of the media query.

![Screenshot from 2022-12-15 12-15-35](https://user-images.githubusercontent.com/73561520/207959742-9e7ca80d-44a6-439f-9778-80534971ebb6.png)

2022-12-16 00:23 UTC, roslynwythe commented
> Hey @roslynwythe ,
> 
> The desktop view is now showing the location images as squares with sharp edges.
> 
> I think the simplest fix would be to add `border-radius: 24px` to the `.location-image` class in **_events.scss**
> 
> Also, I noticed you added `border-radius: 5.8%` to the `$bp-below-tablet` media query for the `.location-image` class. I'm curious about your process for deciding to use a percentage value instead of pixels for the border radius.
> 
> If you do decide to add the `border-radius` property to `.location-image` outside of the media query, it will no longer be necessary inside of the media query.
> 
> ![Screenshot from 2022-12-15 12-15-35](https://user-images.githubusercontent.com/73561520/207959742-9e7ca80d-44a6-439f-9778-80534971ebb6.png)

Hi Matt, I had the same problem recently and it turned out that I was viewing old images (from the live site), either because docker didn't rebuild the image folder or because the browser was caching the images.  I suggest first clearing cached images from the browser history, and if that doesn't work, go ahead and rebuild _site using rm -r _site and rm .jekyll-metadata.

Thank you for taking the time to re-review this issue.

2022-12-16 00:38 UTC, MattPereira approved these changes
@roslynwythe my sincere apologies. I thought stopping docker and running `docker compose up` again was sufficient to handle the old images problem. 

I appreciate you understanding and taking the time to explain how to mitigate the issue!

Great work on this pull request :+1:

2022-12-16 22:44 UTC, merged