Make toolkit guide cards WCAG compliant
hackforla/website pull request #3726
Opened 2022-11-16 19:38 UTC by michaelmagen

Fixes #2929

### What changes did you make and why did you make them ?

  - Updated _includes/guide-card.html as specified in issue.
  - Moved 2FA.svg to assets\images\guides\2FA directory
  - Moved survey-reporting-image.svg to assets\images\guides\2FA directory assets\images\guides\survey-reporting directory
- Updated svg field for all html files in _guide-pages\ directory
- After making these changes, had trouble fixing the spacing between image and text in guid cards (see screenshots below). Created this pull request to allow others to help fix the spacing.   

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

<img width="1102" alt="Screen Shot 2022-11-16 at 11 31 40 AM" src="https://user-images.githubusercontent.com/107211477/202276375-c7dff43d-7442-4b46-9aa0-a4df16383661.png">

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
<img width="1099" alt="Screen Shot 2022-11-16 at 11 32 51 AM" src="https://user-images.githubusercontent.com/107211477/202276619-3a5b544b-915b-4dde-b211-359a89e7a7d5.png">

</details>

<details>
<summary>Figma design for the Toolkit page</summary>

<img width="755" alt="Screen Shot 2022-11-16 at 11 37 03 AM" src="https://user-images.githubusercontent.com/107211477/202277464-1a94ddde-3223-47b2-8728-0b934e9111b6.png">

</details>

2022-11-17 17:56 UTC, blulady commented
@plang-psm Did you get a chance to slack [michaelmagen](https://github.com/michaelmagen) about your findings? If not, feel free to post them here, if you already spoke with him, don't worry about it.

2022-11-17 22:43 UTC, plang-psm commented
Hi @blulady , just wrapped up our meeting regarding the issue! @michaelmagen will be finishing up and submitting for PR review soon.

2022-11-17 22:54 UTC, angelenelm commented
I can't wait to see how you figured out the spacing!

2022-11-17 23:34 UTC, michaelmagen commented
I added the changed I had discussed with @plang-psm. However, there is an extra commit called "Merge brach 'hackforla:gh-pages' into guide-card-wcag-update-2929" from when I tried to incorporate the update my topic branch with the changes made in the hackforla repository. Is this an issue?

2022-11-19 05:03 UTC, blulady commented
> I added the changed I had discussed with @plang-psm. However, there is an extra commit called "Merge brach 'hackforla:gh-pages' into guide-card-wcag-update-2929" from when I tried to incorporate the update my topic branch with the changes made in the hackforla repository. Is this an issue?

Shouldn't be.

2022-11-19 23:05 UTC, MattPereira requested changes

2022-11-19 23:05 UTC, MattPereira commented on _sass/components/_toolkit.scss
> +.toolkit-flex-item-img-container svg,
Nice job adding the `.toolkit-flex-item-img-container img` combinator  to target the `<img>` elements that are now direct children of `.toolkit-flex-item-img-container` ! :+1: 

I think it may be best practice to remove the `.toolkit-flex-item-img-container svg` combinator here since there are no more instances of an `<svg>` element inside of the `.toolkit-flex-item-img-container` class in the code base after making the changes instructed by your issue.

2022-11-19 23:14 UTC, MattPereira requested changes

2022-11-19 23:14 UTC, MattPereira commented on _sass/components/_toolkit.scss
> +    height: 16em;
I completely understand where you are coming from changing the `max-height` property to `height` in order to force the `.toolkit-flex-item-img-container` boxes to all be the same size. However, I fear this solution may have some unintended consequences for small to medium view port widths. It seems to work well for desktop and mobile sizes, but the in between sizes appear to be suffering from a change to the overall height of the cards:
![Screenshot from 2022-11-19 14-40-19](https://user-images.githubusercontent.com/73561520/202875158-8f56ccab-b2e7-40a2-b631-78fafdfc780f.png)

2022-11-23 01:14 UTC, michaelmagen commented on _sass/components/_toolkit.scss
> +.toolkit-flex-item-img-container svg,
The `.toolkit-flex-item-img-container svg` combinator is used in the bottom 'external resources' section of the page. Removing it messes up the images of the external resources. See below for screenshot of site when `.toolkit-flex-item-img-container svg` is removed:

<details>
<summary>Site screenshot with combinator removed </summary>
<img width="1303" alt="Screen Shot 2022-11-22 at 4 27 43 PM" src="https://user-images.githubusercontent.com/107211477/203451735-1a54c650-5043-4fd8-b952-6ce0b255a41f.png">
</details>

2022-11-23 01:23 UTC, MattPereira commented on _sass/components/_toolkit.scss
> +.toolkit-flex-item-img-container svg,
Well this is certainly embarrassing for me especially since its on the same page and I missed it.
 
My sincere apologies!

2022-11-23 01:29 UTC, michaelmagen commented on _sass/components/_toolkit.scss
> +    height: 16em;
I think you are correct. I changed `.toolkit-flex-item-img-container` so that at smaller viewports the height is now `height: auto`. I think this makes the guide cards look better at these viewports. Although, the `.toolkit-flex-item-img-container` is also used for the images in the external resources sections. The change I just mentions breaks those images, so I added `height: 15.5rem` to the `.resource-svg-icons` class. This keeps the resource svg's at `height: 15.5rem` instead of changing them to `height: auto`.

2022-11-23 23:00 UTC, blulady reviewed
The issue linked says to make it look like the site. I would argue that you have made it look better than the site, especially for the Responsive view. All of the mobile views seem to have the problem of the default card not being the same size as the website and while, personally, I think it's fine, I am uncertain if it is functioning as designed. 


<details>
<summary>see screen shots</summary>

![Screenshot (304)](https://user-images.githubusercontent.com/67162265/203658991-6964acc7-e6c9-4571-b467-e17cf8ee5757.png)

![Screenshot (305)](https://user-images.githubusercontent.com/67162265/203659071-1409de00-e1a1-4ef8-bae5-efbb4a5def57.png)

![Screenshot (306)](https://user-images.githubusercontent.com/67162265/203659124-893563f9-ba11-407f-9122-a58b9430ae85.png)

![Screenshot (307)](https://user-images.githubusercontent.com/67162265/203659195-a09d0af2-d24d-460b-997f-368146e1c695.png)

</details>

<details>
<summary>The ipads look good. Until you come to the view of the Surface Duo which seems to have the same issue but the Galaxy Fold has the same problem</summary>


![Screenshot (308)](https://user-images.githubusercontent.com/67162265/203659791-36e95b70-2bd7-43d3-914a-d0d6ca7d43ef.png)

</details>

The rest look amazing. All of which Matt said way more succinctly.

2022-11-25 03:09 UTC, MattPereira commented on _sass/components/_toolkit.scss
> +    height: 16em;
I completely agree that your `height: auto` solution makes the guide card look better for the small-medium viewports. Also, nice attention to detail accounting for the breaking change to the external resources svg!

2022-11-25 03:10 UTC, MattPereira approved these changes

2022-11-25 03:18 UTC, MattPereira approved these changes
I completely agree with @blulady 's argument that your changes look better than the live site for the small to medium responsive views. Furthermore, you did an amazing job communicating with the team, asking for help, and fine tuning your solution.

Amazing work on this issue @michaelmagen ! :+1:

2022-11-26 18:43 UTC, merged