Design System Audit Color Swap Red
hackforla/website pull request #3730
Opened 2022-11-18 00:47 UTC by esantiano

Fixes #2112 

### What changes did you make and why did you make them ?

  - changed all changeable instances of '#fa114f' to '$color-red'

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

No visual changes to the website, color variable swap should allow the website to remain the same.

</details>

<details>
<summary>Visuals after changes are applied</summary>

  No visual changes to the website, color variable swap should allow the website to remain the same.

</details>

2022-11-18 03:42 UTC, t-will-gillis commented
Available: Fri 11/18
ETA: Fri 11/18

2022-11-18 04:55 UTC, Adastros commented
Availability: 9 - 11 PM 17NOV22, 18NOV22
Review ETA: 11PM 17NOV22

2022-11-18 07:33 UTC, Adastros submitted a review, later dismissed
Good job @esantiano! You successfully changed all of the instances that had a hard coded red color with its equivalent scss variable. The changes also didn't affect the website. 

One thing I want to note is that I noticed some files had other hard-coded colors that don't seem to exist in the _colors.scss file. A couple of examples are linked below. It's not within the scope of this issue but it's something I thought I should bring up to see if they should be replaced with a variable too. 

https://github.com/hackforla/website/blob/87c6ab8020941865c8460674dcb20535e0956a84/_layouts/project.html#L147

https://github.com/hackforla/website/blob/87c6ab8020941865c8460674dcb20535e0956a84/_sass/components/_getting-started-page.scss#L323

2022-11-18 12:58 UTC, Suman2795 commented
ETA:18/11/2022
Availability: 2 hours

2022-11-18 17:26 UTC, Suman2795 reviewed
Good work @esantiano ! You made suitable changes in the files as per the comment.

2022-11-18 17:27 UTC, Suman2795 submitted a review, later dismissed

2022-11-18 20:10 UTC, t-will-gillis approved these changes, later dismissed
Hi @esantiano - Looks great! 

Appears that all references to hard-coded `#fa114f ` (outside of the excluded files) have been changed to `$color-red` per the issue. As it says in the linked issue #2112, it also looks like references to the other reds (i.e. `$color-firebrick`, etc.) are to the color variable name and not the hard-coded color and that all are being used.

2022-11-18 20:46 UTC, MattPereira commented on _guide-pages/how-to-set-reminders-in-slack.md
>    h1 {
I noticed that this `<style>` element is actually being rendered as text: [how-to-set-reminders-in-slack.md](https://github.com/hackforla/website/blob/gh-pages/_guide-pages/how-to-set-reminders-in-slack.md)

Thus, none of these styles are being applied to the markdown file.

2022-11-18 22:02 UTC, MattPereira requested changes
Hi @esantiano ,

Great job replacing the instances of `#fa114f` with `$color-red` ! :+1: 

However, it seems that the `$color-salmon` variable from [/_sass/variables/_colors.scss](https://github.com/hackforla/website/blob/gh-pages/_sass/variables/_colors.scss) and `.color-salmon` class from [/_sass/elements/_color-styles.scss](https://github.com/hackforla/website/blob/gh-pages/_sass/elements/_color-styles.scss) are both unused throughout the code base and the issue instructs they both be removed from their respective files if inactive. 

**UPDATE**
-  `rgb(255, 173, 173)` matches  the `$color-salmon` `#ffadad`  and is used for the `.status-Completed` class's `background-color` property found in [/_sass/components/_home.scss](https://github.com/hackforla/website/blob/gh-pages/_sass/components/_home.scss) , [/_sass/components/_projects-pages.scss](https://github.com/hackforla/website/blob/gh-pages/_sass/components/_projects-page.scss), and [/_sass/components/_projects.scss](https://github.com/hackforla/website/blob/gh-pages/_sass/components/_projects.scss). Perhaps these 3 instances of `rgb(255, 173, 173)` should be changed to use the `$color-salmon` variable?
- `rgb(250, 17, 79)` matches `$color-red:` `#fa114f` and is used 4 times in the [/components/_about.scss](https://github.com/hackforla/website/blob/gh-pages/_sass/components/_about.scss) file. This could also potentially be swapped to use the `$color-red` variable

2022-11-18 22:06 UTC, t-will-gillis commented on _guide-pages/how-to-set-reminders-in-slack.md
>    h1 {
Hi @MattPereira -

Looking at the webpage for how-to-set-reminders-in-slack.html, it appears that the change renders correctly in Docker on @esantiano 's branch. Please see attached.
![issue 3730 comparison](https://user-images.githubusercontent.com/40799239/202810881-6dfd810d-030c-44a7-bd90-2fc030ee2f9a.png)

I.e. I think this is rendering correctly, but I could be misunderstanding how the .md is displayed in the .html

2022-11-18 22:13 UTC, t-will-gillis commented on _guide-pages/how-to-set-reminders-in-slack.md
>    h1 {
Or is it that the <style> element does not affect anything regardless of the `$color-red` or `fa114f`? I see what you are saying about the <style> element, but I am seeing it in the original .md file also.

2022-11-19 04:23 UTC, MattPereira commented on _guide-pages/how-to-set-reminders-in-slack.md
>    h1 {
So it turns out the `<style>` element being rendered as text in the .md file doesn't matter, but what does matter is that using `code { color: $color-red; }` in this file does not work for styling the code element text to red in the `how-to-set-reminders-in-slack.md` file. I believe issue #2112 instructs to use the `.color-red` class since `$color-red` does not work here

2022-11-19 04:31 UTC, MattPereira requested changes

2022-11-19 04:31 UTC, MattPereira commented on _guide-pages/how-to-set-reminders-in-slack.md
> +    color: $color-red;
This change results in the `<code>` element from the file losing its red color
https://www.hackforla.org/guide-pages/how-to-set-reminders-in-slack.html

<details><summary>Before</summary>
<img src="https://user-images.githubusercontent.com/73561520/202833995-f3f154bf-fad1-47b5-8ee8-55155747ec64.png">
</details>

<details><summary>After</summary>
<img src="https://user-images.githubusercontent.com/73561520/202834076-40d80e8f-ad4d-48fd-96fb-3e27511bfcb6.png">
</details>

2022-11-19 05:39 UTC, Adastros commented on _guide-pages/how-to-set-reminders-in-slack.md
>    h1 {
I tested this out on my side and agree that the `code` tag isn't styled red when `$color-red` is used in `how-to-set-reminders-in-slack.md`. One of the things I missed when reviewing it last night. 

In regards to the `style` element rendering as text, I don't see it converting to text on my side. If I understand how Markdown gets parsed/ rendered correctly, the `style` element should be treated as a HTML element. The other content in the file should be converted into HTML.

2022-11-19 05:47 UTC, MattPereira commented on _guide-pages/how-to-set-reminders-in-slack.md
>    h1 {
@Adastros you are correct. I mistakenly thought it _might_ matter that it shows as text if you visit this link: https://github.com/hackforla/website/blob/gh-pages/_guide-pages/how-to-set-reminders-in-slack.md

2022-11-19 05:56 UTC, Adastros commented on _guide-pages/how-to-set-reminders-in-slack.md
>    h1 {
Ahhk okay. I understand now. I thought you were referring to the website. Thanks for showing me!

2022-11-20 00:55 UTC, esantiano commented on _guide-pages/how-to-set-reminders-in-slack.md
> +    color: $color-red;
Hi @MattPereira, 

Good catch on the page as this was something I did not notice when looking at the changes. It looks like applying the change you suggested however does not correct the problem however and I'm not entirely sure why thats the case. the color scss files under elements and variables seem to be correct however the code element does not seem to be affected by either.

2022-11-20 01:03 UTC, esantiano commented
> One thing I want to note is that I noticed some files had other hard-coded colors that don't seem to exist in the _colors.scss file. A couple of examples are linked below. It's not within the scope of this issue but it's something I thought I should bring up to see if they should be replaced with a variable too.
> 
> https://github.com/hackforla/website/blob/87c6ab8020941865c8460674dcb20535e0956a84/_layouts/project.html#L147
> 
> https://github.com/hackforla/website/blob/87c6ab8020941865c8460674dcb20535e0956a84/_sass/components/_getting-started-page.scss#L323


Hi @Adastros 

good job catching those instances, its my understanding that these issues will be addressed in the future related to issue #2114.

2022-11-20 02:03 UTC, MattPereira commented on _guide-pages/how-to-set-reminders-in-slack.md
> +    color: $color-red;
Hey @esantiano,

I think it works if you wrap the `<code>` element in a `<span>` and apply the class to the span. However, there may be a better practice that I am unaware of.

<details><summary>Click here for example</summary>
<img src="https://user-images.githubusercontent.com/73561520/202879156-6bd88702-22ce-4213-ae55-1c2ae723034b.png" />

<img src="https://user-images.githubusercontent.com/73561520/202879183-cdf52d32-9cdb-4938-b0bc-6e58738f043e.png" />

</details>

2022-11-27 00:56 UTC, esantiano commented
`Progress:` changed all changeable instances of #fa114f to "$color-red".
`Blockers:` lines 46-48 in how-to-set-reminders-in-slack.md seem to not be applied to <code> tags using the change, however this was resolved on Sunday Nov 20th meeting. 
`Availability:` 2 Hours
`ETA:` 11/26/2022

2022-11-27 01:28 UTC, esantiano commented
Hi @MattPereira 

>     * `rgb(255, 173, 173)` matches  the `$color-salmon` `#ffadad`  and is used for the `.status-Completed` class's `background-color` property found in [_home.scss](https://github.com/hackforla/website/blob/gh-pages/_sass/components/_home.scss) , [_projects-pages.scss](https://github.com/hackforla/website/blob/gh-pages/_sass/components/_projects-page.scss), and [_projects.scss](https://github.com/hackforla/website/blob/gh-pages/_sass/components/_projects.scss). Perhaps these 3 instances of `rgb(255, 173, 173)` should be changed to use the `$color-salmon` variable?
> 
I think this might be addressed with a new issue as well. 

>     * `rgb(250, 17, 79)` matches `$color-red:` `#fa114f` and is used 4 times in the [_about.scss](https://github.com/hackforla/website/blob/gh-pages/_sass/components/_about.scss) file. This could also probably be swapped.

After looking at the about.scss I found that the change from `#fa114f` to `$color-red` had been incorporated.

2022-11-27 03:21 UTC, MattPereira commented
Hey @esantiano , 

- I'm pretty sure #2112 encapsulates replacing all of the shades of red that are currently hardcoded throughout the codebase <details><summary><strong>See screenshot</strong></summary>![reds](https://user-images.githubusercontent.com/73561520/204117551-4aee8933-cd51-43e7-91e2-ea9a49e9de74.png)</details>
- Instances of `rgb(250, 17, 79)` ( which is equivalent to `#fa114f` ) in _about.scss <details><summary><strong>See screenshot</strong></summary>![Screenshot from 2022-11-26 19-16-15](https://user-images.githubusercontent.com/73561520/204117603-fe8864d1-a0cb-47c6-9056-5c86461692c7.png)</summary>

2022-12-04 03:14 UTC, esantiano commented
> Hey @esantiano ,
> 
>     * I believe [Design System Audit: Swap colors with color variables: Reds #2112](https://github.com/hackforla/website/issues/2112) encapsulates replacing all of the shades of red that are currently hardcoded throughout the codebase including `$color-salmon:` `#ffadad`**See screenshot**![reds](https://user-images.githubusercontent.com/73561520/204117551-4aee8933-cd51-43e7-91e2-ea9a49e9de74.png)
> 
>     * Instances of `rgb(250, 17, 79)` ( which is equivalent to `#fa114f` ) in _about.scss **See screenshot**![Screenshot from 2022-11-26 19-16-15](https://user-images.githubusercontent.com/73561520/204117603-fe8864d1-a0cb-47c6-9056-5c86461692c7.png)

Hey @MattPereira 

Just changed these instances - the changes were applied to the mobile site and haven't affected any of the colors used.

2022-12-10 03:18 UTC, MattPereira approved these changes
@esantiano good work replacing all remaining hard-coded instances of "reds" with the corresponding color variables  ! :+1:

2022-12-10 03:23 UTC, merged