Add Problem, Solution, and Impact Sections to Project Pages
hackforla/website pull request #3767
Opened 2022-12-06 01:13 UTC by patrickohh

Fixes #3547

### What changes did you make and why did you make them ?

  - Added value card to project pages.
  - Value card only renders if specific project page has problem, solution and impact fields.
  - Added CSS components to _project-page.scss file to render value card with proper dimensions.
### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

![image]<img width="824" alt="before value card" src="https://user-images.githubusercontent.com/50275188/205781563-bf48e100-44cf-4db8-b68a-e4eb124a68dc.PNG">

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
![image]<img width="768" alt="after value" src="https://user-images.githubusercontent.com/50275188/205782294-e1b9cd33-be3a-409e-8028-02331bd5b117.PNG">

</details>

2022-12-07 19:35 UTC, t-will-gillis commented
Review availability: Weds 12/7 3-5 pm
ETA: Weds 12/7 5pm

2022-12-09 02:51 UTC, t-will-gillis submitted a review, later dismissed
Hi @patrickohh - 

Great job- It appears that the Project Value Card is rendering correctly- matching the proposed Figma screenshot-  for the five projects where `project.problem` exists and not the others with the Liquid if statememt. The new 'Value' card seems to be rendering and resizing correctly, and I don't see any unintended effects.  Good catch with the edits to the `_project-page.scss`-

2022-12-10 04:21 UTC, MattPereira requested changes
Hey @patrickohh solid work this looks really good! :+1: 

Just a couple of edits if possible:

- For small to medium screen sizes, I noticed the sustainable development goal card bumps up against the edge of its container card. Perhaps the CSS could be better adjusted for this screen size range ?<details><summary>See Screenshot</summary><img src="https://user-images.githubusercontent.com/73561520/206828343-7c154078-10cf-44d1-9e7c-89c0406b9d46.png"/>
</details>

- For mobile screen sizes, the figma from the issue shows a modified design for the sustainable development goal card <details><summary>See Screenshot Comparison</summary><h3>Figma Design For Mobile</h3><img src="https://user-images.githubusercontent.com/73561520/206828428-04ea1dd8-da45-4775-a51a-128c71290494.png"/><h3>Current Pull Request on Mobile</h3><img src="https://user-images.githubusercontent.com/73561520/206828471-71a51530-ab76-4de6-8f9c-d58141d65d6d.png"/>



</details>

2022-12-10 04:25 UTC, patrickohh commented
Hi @MattPereira , I will look into making the necessary edits as soon as possible!

2022-12-19 17:24 UTC, patrickohh commented
1. Progress: Haven't gotten a chance to look at the changes needed for this issue due to a busy week last week.
2. Blockers: Last week was just a filled schedule for me, but will take time this week to fix the needed issues.
3. Availability: 12/21 - 12/23
4. ETA: 12/23 Evening

2023-01-09 22:27 UTC, patrickohh commented
> Hey @patrickohh solid work this looks really good! 👍
> 
> Just a couple of edits if possible:
> 
> * For small to medium screen sizes, I noticed the sustainable development goal card bumps up against the edge of its container card. Perhaps the CSS could be better adjusted for this screen size range ?See Screenshot![](https://user-images.githubusercontent.com/73561520/206828343-7c154078-10cf-44d1-9e7c-89c0406b9d46.png)
> 
> * For mobile screen sizes, the figma from the issue shows a modified design for the sustainable development goal card See Screenshot Comparison### Figma Design For Mobile![](https://user-images.githubusercontent.com/73561520/206828428-04ea1dd8-da45-4775-a51a-128c71290494.png)### Current Pull Request on Mobile![](https://user-images.githubusercontent.com/73561520/206828471-71a51530-ab76-4de6-8f9c-d58141d65d6d.png)

Made the changes for the description card to avoid touching the outer div with small to medium screen sizes, however still finding trouble in implementing the mobile design for the description card. None of my media queries seem to work in the redesign. Is there a way to replace one div with another without having the change the whole structure of the html code?

2023-01-11 02:45 UTC, MattPereira requested changes

2023-01-11 02:45 UTC, MattPereira commented on _sass/components/_project-page.scss
> +}
I'm pretty sure you want the media query here to be `$bp-below-tablet` for the `.sdg-description-card` to implement the the mobile design. I put `flex-direction:row` and `flex-wrap: nowrap` inside of a below tablet query to start moving it in the right direction.

![Screenshot from 2023-01-10 18-44-34](https://user-images.githubusercontent.com/73561520/211705929-78c7d593-cb33-4e79-b0f4-cb0a9bffd042.png)

2023-01-13 00:58 UTC, patrickohh commented on _sass/components/_project-page.scss
> +}
Ok will try to implement this later tonight. Thanks for the tip!

2023-01-14 02:42 UTC, patrickohh commented on _sass/components/_project-page.scss
> +}
Made the necessary changes to implement the mobile design. Had to make a totally new div to create it more mobile-friendly.

2023-01-18 05:51 UTC, jyaymie approved these changes, later dismissed
This is awesome work, @patrickohh! You developed a section that very closely matches the prototype and with logical class names and a good use of Liquid. I totally understand why you created a new div specifically for mobile as the shift in the elements' placement is tricky to implement here! That said, I think it is possible to work off just the one div you created. I played around with some of the code and got something working using this HTML structure:

```
<div class='sdg-description-card'>
     <h2 class='sdg-card-title title7'>Sustainable Development Goal</h2>
     <div class="sdg-description-wrapper">
          <img class='sdg-img' src='{{ page.sdg-image-src }}'/>
          <div class='sdg-description-grid-item'>{{ page.sdg }}</div>
     </div>
</div>
```

The main change is the wrapper around the SDG image and text. (If you have a better class name, by all means!) The SDG title, now on its own, should be more easier to manage when working on responsive design.

I'm gonna approve this PR because you did come up with a 100% valid solution, but I also know it's good practice to avoid repeated code. If you do attempt to refactor your code and get stuck, feel free to reach out on Slack!

2023-01-19 00:44 UTC, MattPereira submitted a review, later dismissed
I concur with @jyaymie. The responsiveness from desktop down through mobile view is excellent. This is great work on a rather difficult Figma implementation 

Seems like all that remains is the trade off between shipping changes faster vs completely DRY code.

@patrickohh leaving the decision up to you. Let us know if you are done and we'll merge it as is or if you'd like to take on the challenge of implementing Jamie's clever optimization we are here for that too! :+1:

2023-01-19 23:27 UTC, patrickohh commented
> This is awesome work, @patrickohh! You developed a section that very closely matches the prototype and with logical class names and a good use of Liquid. I totally understand why you created a new div specifically for mobile as the shift in the elements' placement is tricky to implement here! That said, I think it is possible to work off just the one div you created. I played around with some of the code and got something working using this HTML structure:
> 
> ```
> <div class='sdg-description-card'>
>      <h2 class='sdg-card-title title7'>Sustainable Development Goal</h2>
>      <div class="sdg-description-wrapper">
>           <img class='sdg-img' src='{{ page.sdg-image-src }}'/>
>           <div class='sdg-description-grid-item'>{{ page.sdg }}</div>
>      </div>
> </div>
> ```
> 
> The main change is the wrapper around the SDG image and text. (If you have a better class name, by all means!) The SDG title, now on its own, should be more easier to manage when working on responsive design.
> 
> I'm gonna approve this PR because you did come up with a 100% valid solution, but I also know it's good practice to avoid repeated code. If you do attempt to refactor your code and get stuck, feel free to reach out on Slack!

Made some changes to use only one div, but running into an issue where the description section of the card wraps down too much from the screen size shrinking.

2023-01-19 23:28 UTC, patrickohh commented
> I concur with @jyaymie. The responsiveness from desktop down through mobile view is excellent. This is great work on a rather difficult Figma implementation
> 
> Seems like all that remains is the trade off between shipping changes faster vs completely DRY code.
> 
> @patrickohh leaving the decision up to you. Let us know if you are done and we'll merge it as is or if you'd like to take on the challenge of implementing Jamie's clever optimization we are here for that too! 👍

Made an attempt on taking @jyaymie recommendation. But running into a format issue with the description section of the card.

2023-01-25 04:50 UTC, MattPereira requested changes

2023-01-25 04:50 UTC, MattPereira commented on _sass/components/_project-page.scss
> +  height: fit-content;
I think the `text-align:center` applied here is causing the description section to have centered text, but the figma shows the description of the SDG card having a `text-align: start`. Also, it looks like there is probably too much space on the bottom of the card compared to the figma.

Also, I'm not sure what you mean exactly when you say
> the description section of the card wraps down too much from the screen size shrinking

<details><summary>Figma Design</summary>
<img src="https://user-images.githubusercontent.com/73561520/214482525-13c25392-9293-48ec-8911-e40db2179ba6.png">
</details>

<details><summary>Current Pull Request</summary>
<img src="https://user-images.githubusercontent.com/73561520/214482102-06036c4a-0c50-4864-8c51-992b5ec30b2e.png">
</details>

2023-01-30 17:13 UTC, patrickohh commented on _sass/components/_project-page.scss
> +  height: fit-content;
Sorry for the late reply. I have been pretty busy with other tasks and was gone all weekend. I will be sure to make these changes by the end of today!

2023-01-30 22:53 UTC, patrickohh commented on _sass/components/_project-page.scss
> +  height: fit-content;
@MattPereira Just implemented the change!

2023-02-01 02:05 UTC, MattPereira approved these changes
Superb work on this one @patrickohh :+1: 

We really appreciate your willingness to take on the challenge of refactoring the html and css to be more concise than the original implementation.

2023-02-01 02:05 UTC, merged

2023-02-02 17:08 UTC, patrickohh commented
> Superb work on this one @patrickohh 👍
> 
> We really appreciate your willingness to take on the challenge of refactoring the html and css to be more concise than the original implementation.

Thank you for reviewing my code and offering suggestions along the way @jyaymie @MattPereira!