Implement desktop footer design
hackforla/website pull request #3801
Opened 2023-01-09 22:19 UTC by jyaymie

Fixes #2393

### What changes did you make and why did you make them ?
  - I corrected the Contact Us link from `#contact-us` to `#get-in-touch`. See related [comment](https://github.com/hackforla/website/issues/2393#issuecomment-1334962487).
  - In `_includes/footer.html` and `_sass/components/_footer.scss` , I added new lines and spaces and reformatted code to increase readability.
  - I used desktop media queries to modify the existing footer section based on the Figma design and its exact dimensions.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>
<img width="1351" alt="Screen Shot 2023-01-09 at 2 17 37 PM" src="https://user-images.githubusercontent.com/104411072/211419606-4dac0eb8-be97-4ff0-93b5-9bfb03afc843.png">

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
<img width="1357" alt="Screen Shot 2023-01-09 at 2 16 29 PM" src="https://user-images.githubusercontent.com/104411072/211419623-0491c7b0-a553-4f75-a4b4-22e4a4c7a23b.png">

</details>

2023-01-11 02:31 UTC, MattPereira commented
Review ETA: End of Day 1/11/23
Availability: 20 hours

2023-01-11 04:50 UTC, roslynwythe commented
Review Availability: 1/10 10 pm - midnight, 1/11 8 pm - midnight
ETA: EOD 1/11

2023-01-11 04:52 UTC, roslynwythe commented
@jyaymie it looks like there is a possible merge conflict with _footer.scss

2023-01-11 06:53 UTC, jyaymie commented
Ah, the issue must've been merged after I created the PR. Great catch, @roslynwythe! I decided to override the code with my changes as I feel like the footer columns should have a fixed width that doesn't change with link length.

2023-01-11 07:07 UTC, jyaymie commented
I caught a couple more errors. I was missing the `</footer>` tag in `_includes/footer.html` and I should've used a media query so my changes to each `<li>` in `_footer.scss` applied only in desktop view.

2023-01-11 20:53 UTC, roslynwythe commented
@jyaymie - so in https://github.com/hackforla/website/pull/3774#issue-1512111547, the media query breakpoint was changed from $bp-mobile-up to $bp-desktop-up and you switched it back to $bp-mobile-up.  Your result looks great;  was that because of your changes to the padding?

2023-01-11 21:09 UTC, jyaymie commented
> @jyaymie - so in [#3774 (comment)](https://github.com/hackforla/website/pull/3774#issue-1512111547), the media query breakpoint was changed from $bp-mobile-up to $bp-desktop-up and you switched it back to $bp-mobile-up. Your result looks great; was that because of your changes to the padding?

@roslynwythe, I must've missed it! Could you point me to where I switched it back to `$bp-mobile-up`? It wasn't my intent if that switch was made. I did remove padding as I didn't see any in the Figma prototype, but perhaps giving content some breathing room is better CSS practice?

2023-01-11 22:13 UTC, MattPereira requested changes

2023-01-11 22:13 UTC, MattPereira commented on _sass/components/_footer.scss
> +  }
I could be wrong, but my understanding of the `mobile-up` media query is that it will apply to all screen sizes larger than `480px` which would make adding `margin-top: -165px` to the `desktop-up` media query unnecessary here.

Just a tiny nit pick and please let me know if I am misunderstanding

(everything else is superb as usual)

- https://github.com/hackforla/website/blob/gh-pages/_sass/variables/_layout.scss

2023-01-11 22:42 UTC, jyaymie commented on _sass/components/_footer.scss
> +  }
I went back and forth on this, and it looks like I got too in my head about inheritance only to now realize we're not dealing with inheritance at all here. Thank you for calling this back to my attention, @MattPereira! Change made!

2023-01-11 22:45 UTC, jyaymie commented
With more eyes on my code, I keep catching things I missed! I changed the alignment of the links at the bottom of the footer to be centered with the adjacent social media icons as laid out in the prototype.

2023-01-12 01:44 UTC, roslynwythe commented
> > @jyaymie - so in [#3774 (comment)](https://github.com/hackforla/website/pull/3774#issue-1512111547), the media query breakpoint was changed from $bp-mobile-up to $bp-desktop-up and you switched it back to $bp-mobile-up. Your result looks great; was that because of your changes to the padding?
> 
> @roslynwythe, I must've missed it! Could you point me to where I switched it back to `$bp-mobile-up`? It wasn't my intent if that switch was made. I did remove padding as I didn't see any in the Figma prototype, but perhaps giving content some breathing room is better CSS practice?

@jyaymie, I apologize, I misinterpreted the file diff snippet.  It looks great both on the website and in the code, the branches are correct and all the links work perfectly.  Great work, thank you!

2023-01-12 01:45 UTC, roslynwythe approved these changes
It looks great both on the website and in the code, the branches are correct and all the links work perfectly.  Great work, thank you!

2023-01-12 02:37 UTC, MattPereira approved these changes
I appreciate you going the extra mile adding spaces in between the `.column` divs to make it more readable for future developers. 

Also want to commend the teamwork and communication on display here as you cleared up the link confusion.

Reviewing your PRs is a pleasure and we are lucky to have you @jyaymie

2023-01-12 02:39 UTC, merged