Display VRMS data on Events and Project Meetings pages
hackforla/website pull request #3833
Opened 2023-01-17 06:56 UTC by jyaymie

Fixes #3701

### What changes did you make and why did you make them?

  - I added 'if' statements in the `insertEventSchedule` and `display_object` functions in `assets/js/utility/api-events.js`, which fixed TypeErrors caused by incompatible or missing values in the data. Rather than combing through the VRMS data to find what caused these errors, I thought this was a more efficient solution that safeguards against similar issues in the future.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

<img width="1032" alt="Screen Shot 2023-01-16 at 10 20 21 PM" src="https://user-images.githubusercontent.com/104411072/212829490-ee663d2d-f357-4d7d-b8ce-7d067c085ecd.png">

<img width="936" alt="Screen Shot 2023-01-16 at 10 21 56 PM" src="https://user-images.githubusercontent.com/104411072/212829705-4c06356c-c89d-44cb-a231-817db7a7f838.png">

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
<img width="1039" alt="Screen Shot 2023-01-16 at 10 21 00 PM" src="https://user-images.githubusercontent.com/104411072/212829737-d632c00f-5d54-45aa-851e-bab13692b46e.png">

<img width="943" alt="Screen Shot 2023-01-16 at 10 21 30 PM" src="https://user-images.githubusercontent.com/104411072/212829516-c6898a4f-4a3d-4354-9d42-964e40eb3493.png">

</details>

2023-01-17 21:01 UTC, MattPereira commented
Review ETA: End of Day 1/17/23
Availability: 6-10 PM Tuesday

2023-01-17 22:18 UTC, MattPereira requested changes

2023-01-17 22:18 UTC, MattPereira commented on assets/js/utility/api-events.js
> +  }
I think this code is the only absolutely necessary part to fix the meeting time display issue, but I don't mind the additional  `if(event)` conditional block on line 35 as its always good to try and handle weak spots in the code before they break the site.

I am curious if maybe it would be better to use a `try...catch` statement to give us information what exactly is breaking? (or maybe thats just an expressJS pattern that I'm trying to apply in the wrong situation here)

Also, I think I figured out exactly why it was breaking by console.logging the `responseData` from `getEventData()` and using a `try...catch` block. It seems the very last meeting time is a test that someone left in there that was breaking everything because the `project` was set to `null`. 

![Error](https://user-images.githubusercontent.com/73561520/213023900-1de2b1b6-3a52-498b-b39f-5e6a2901f307.png)

2023-01-17 23:22 UTC, t-will-gillis approved these changes
Hi  jyaymie – Looks good- the `/events` and `/project-meetings` pages both seem to be displaying the meeting times correctly, and the individual project pages do not seem to break. I started a tedious exercise comparing the before and after `vrms_data.json` files. As Matt already pointed out, there are a couple dozen lines of code that were deleted in ‘testy test Team Meeting’ that were previously included in `project: ` and now are null, which may have been the breakpoint. 
I am marking my review as ‘approved’  - I have nothing to add to Matt’s or your insights, but I will be following along to see how the two of you resolve this.
Great job moving this forward.  
![Screenshot 2023-01-17 150550](https://user-images.githubusercontent.com/40799239/213033900-6e2080a4-abb8-4cf0-9476-6315b9aab654.png)

2023-01-17 23:55 UTC, jyaymie commented on assets/js/utility/api-events.js
> +  }
Hm, I'm not sure if a `try...catch` is needed in this case since we don't (yet) have a meaningful way of handling the errors outside of console.logging them. Perhaps it's something we can add as a separate issue?

And kudos to you + @t-will-gillis for finding that pesky testy test! 😄

2023-01-18 00:44 UTC, MattPereira commented on assets/js/utility/api-events.js
> +  }
Ya I may have gotten a little too excited about `try...catch` being useful in discovering the root of the bug lol

Totally agree with your sentiment that `console.log()`is probably not a great plan for handling code errors in a production environment

2023-01-18 00:48 UTC, MattPereira commented
Moving this bug discovery out of "resolved conversation" for future reference

After console.logging the `responseData` from `getEventData()` and using a `try...catch` block around the `rv_object` instantiation. It seems the very last meeting time is a test that was breaking everything because the `project` property was set to `null`. 

![Error](https://user-images.githubusercontent.com/73561520/213023900-1de2b1b6-3a52-498b-b39f-5e6a2901f307.png)

2023-01-18 00:58 UTC, MattPereira approved these changes
@jyaymie nice work knocking down a large issue so quickly! :muscle: 

Appreciate your explanation of the proposed changes and the quality screenshots.

My only tiny suggestion is to use the check boxes provided under the issue action items, but I have seen lots of other developers here not using them so maybe I just have a weird thing for check marks 🤔

2023-01-18 01:00 UTC, merged

2023-01-18 03:37 UTC, jyaymie commented
> My only tiny suggestion is to use the check boxes provided under the issue action items, but I have seen lots of other developers here not using them so maybe I just have a weird thing for check marks 🤔

Good call, @MattPereira. Those boxes are there for a reason!