Update sdg img size and .sustainable-dev-goal padding
hackforla/website pull request #3844
Opened 2023-01-19 22:17 UTC by SZwerling

Fixes #3738

### What changes did you make and why did you make them ?

  -All changes within $bp-media-up media query.
  -  .sdg-image height: 145 px
  -  .sustainable-dev-goal padding: 20px
  - p element within .sustainable-dev-goal margin-bottom: 0

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

![image](Paste_Your_Image_Link_Here_After_Attaching_Files)

</details>

<details>
<summary>Visuals after changes are applied</summary>

![image](
[screencapture-localhost-4000-citizen-engagement-2023-01-19-13_59_39 (1).pdf](https://github.com/hackforla/website/files/10461529/screencapture-localhost-4000-citizen-engagement-2023-01-19-13_59_39.1.pdf)
 )

</details>

2023-01-25 01:35 UTC, jdingeman commented
ETA: EOD 1/24
Availability: 2hrs

2023-01-25 02:04 UTC, jdingeman requested changes
Hello. Nice job on this. The SDG images are sized correctly and padding looks good.

However in reading the issue, I believe the padding between cards should also be increased. It looks like in the published website and your current layout have a margin of 14px between cards:
<details>

<summary>Current layout margin</summary>

![image](https://user-images.githubusercontent.com/88953806/214464009-d81d55a8-3c09-4145-8721-9be84cc6660b.png)

![image](https://user-images.githubusercontent.com/88953806/214464042-df0058ec-be51-419e-9ba1-d45ce4e53fc5.png)

</details>

It looks like the figma design is proposing a margin of 30px between each card:

<details>

<summary>Figma design margin</summary>

![image](https://user-images.githubusercontent.com/88953806/214464269-5d255d95-aa21-4521-93df-24f0ab3d95c8.png)

</details>

2023-01-28 00:09 UTC, SZwerling commented
Thank you. I'll fix that card padding.

2023-02-09 02:41 UTC, jdingeman commented
Hi @SZwerling, just wanted to check in to see if you are still working on this issue and could provide a progress update?

2023-02-11 20:28 UTC, SZwerling commented
Hello, @jdingeman. Apologies for delayed response.
I have updated the .program-area in tablet-up to have a margin top and bottom of 30px.
I pushed that to my remote repo. I am unsure what to do next. Another pull request on the same issue?
I am a little confused.
Thank you.

2023-02-11 22:16 UTC, jdingeman commented
Hey @SZwerling , sorry about that, I see that you had pushed the commits prior to my comment. I will rereview.

2023-02-13 17:39 UTC, Jaretzbalba commented
ETA: EOD 2/13
Availability: 2hrs

2023-02-13 17:42 UTC, Jaretzbalba approved these changes
@SZwerling I see the changes to the padding and margin on the $bp-tablet-up media query reflect the new figma design. Everything looks to be uniform now and spaced as requested. Thank you for working on this issue!

2023-02-14 00:26 UTC, jdingeman approved these changes
Looks great @SZwerling !

2023-02-14 00:26 UTC, merged