Update project profile 3818
hackforla/website pull request #3907
Opened 2023-01-31 23:52 UTC by kotynskm

Fixes #3818

### What changes did you make and why did you make them ?

  - Removed Renee Moore-Adams from leadership
  - Added Anousha Shadrach and Moji Momoh to leadership
  - Updated links for each new leadership member

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals after changes are applied</summary>
  
![Screenshot 2023-01-31 at 3 39 10 PM](https://user-images.githubusercontent.com/29113012/215909395-bcccaf98-8346-4633-b840-4c3e6453a3c3.png)

</details>

2023-01-31 23:55 UTC, kotynskm commented
I forgot to take a screenshot of before changes, I tried to revert to the original, but then the site did not update for me. I put back the correct changes and now I don't see any content for the tdm project page. Please let me know if there are any issues.

2023-02-01 16:58 UTC, vmaineng commented
ETA: End of the day on 2/1
Availability: 2 hours

2023-02-01 20:32 UTC, vmaineng commented
After reviewing this PR, it looks good to be merged in and met all the requirements.

2023-02-01 20:37 UTC, vmaineng submitted a review, later dismissed
After reviewing this PR, it looks good to be merged in and met all the requirements.

2023-02-02 18:49 UTC, MattPereira commented
**ETA:** 20 minutes
**Availability:** 8 - 10 PM Sunday - Thursday

2023-02-02 19:00 UTC, MattPereira requested changes

2023-02-02 19:00 UTC, MattPereira commented on _projects/tdm-calculator.md
> +   - name: Anousha Shadrach
Hey @kotynskm it looks like you accidentally used an extra space on this line before the `-` which is causing the docker container to throw a YAML Error. YAML is extremely picky about indentation lol

Everything else looks great ! :+1: 

![YAML_error](https://user-images.githubusercontent.com/73561520/216423190-b2670ca9-a86f-4315-bb5b-b70cdddb97de.png)

2023-02-02 19:19 UTC, kotynskm commented on _projects/tdm-calculator.md
> +   - name: Anousha Shadrach
Thanks for pointing this out! I believe I found it and fixed the issue. 👍🏻

2023-02-04 00:40 UTC, MattPereira approved these changes
Solid work on this one @kotynskm ! :+1: 

Appreciate your timely response to my requested changes. The LA TDM Calculator details are now up to date well done!

2023-02-04 00:40 UTC, merged