Edit content field 2806
hackforla/website pull request #3961
Opened 2023-02-10 20:09 UTC by Thinking-Panda

Fixes #2806

### What changes did you make and why did you make them ?

  -Edited content field.
  -Changed it to "content-type: image"
  -Removed the Type field

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
No visible change to website

2023-02-10 22:13 UTC, MarkWiltberger commented
Review ETA: 6 PM ET 02/11/2023 Sat
Availability: 10AM-6 PM ET Monday - Friday

2023-02-11 02:55 UTC, angelenelm commented
Review ETA 7:15PM PT Fri, 2/10/2023
Availability: 10AM - 3PM Mon-Fri

2023-02-11 02:59 UTC, angelenelm approved these changes, later dismissed
Addresses the tasks needed to be done in issue #2806, well done! :)

2023-02-11 22:01 UTC, MarkWiltberger requested changes
Great job! **I love what you have done, @Thinking-Panda!**

The pull request is done with the correct branch and links the correct issue. 

Do the changes pass the ABC's:
A - _Applicable_: **Pass**, the changes apply to the linked issue.
B - Does not _Break_ the main website: **Pass**, the change branch was incorporated in the local site using Docker and the main website did not break. As expected, the fix of this issue does not result in visible changes to the website. Code was inspected and the changes are present.
C - _Clean_: **Changes requested**. I noticed that there is an empty line where the type field was. It appears from the other credit files, the convention is not to have any empty lines between the dashed lines in the markdown file, and the original issue also requests that this line be deleted. Please delete this line, as marked in the inline comment, to make the code more _Clean_ and condensed.

Other than that, it looks great! **Well Done, @Thinking-Panda !**

2023-02-11 22:01 UTC, MarkWiltberger commented on _data/internal/credits/check.yml
> +
Please delete this line to make the code  _Clean_ and condensed. After that, @Thinking-Panda , you should be all set!

2023-02-11 23:09 UTC, MarkWiltberger commented on _data/internal/credits/check.yml
> +
After reviewing this PR and requesting a small change to make the code more _Clean_, I noticed that there were four _commits_ requested to be merged for this pull request. Upon closer inspection, the first two commits appear to be for a different issue, for PR #3954 fixing issue #3872 . That PR has been approved and the commits have been merged already.

If that is the case, then the first two commits are not applicable to the issue at hand for this PR, and the PR does not pass the _Applicable_, portion of the ABC test.

These two commits are:
[b322180](https://github.com/hackforla/website/pull/3961/commits/b322180c4cf219f18b22dcb75b1ffdb21a9f26a3)
[994d57f](https://github.com/hackforla/website/pull/3961/commits/994d57f5aaac77bee6d081ce7410935d23fb6651)


As I am not sure if this is a problem, and I am not sure of the resolution of the problem (e.g., can the 2 commits be removed from the pull request?), I am flagging this PR "Status: Help Wanted" and mentioning @Thinking-Panda and @jdingeman .

I am available to discuss synchronously daily from 10am - 6pm ET (7am - 3pm PT).

2023-02-12 18:22 UTC, MattPereira commented
Looks good just need to remove the extra line at the end of the .yml file! :+1:

2023-02-12 19:30 UTC, MarkWiltberger commented on _data/internal/credits/check.yml
> +
After discussion at Sunday's DEV meeting with @MattPereira , it is believed that the first two commits will not affect the merge, because the only differences in the code are associated with the last two commits. So as @MattPereira comments, the only thing to do is remove the extra line at the end of the .yml file.   👍

2023-02-14 19:59 UTC, Thinking-Panda commented
I have made the correction mentioned. Please review the request.

2023-02-14 20:38 UTC, chrismenke45 commented
Review ETA: 5pm today.
Availability: 12:30-5 today

2023-02-14 20:50 UTC, chrismenke45 approved these changes
Looks good! You have completed what was requested and removed the extra line @MarkWiltberger noticed. Good work!

2023-02-14 22:07 UTC, MarkWiltberger commented
2nd review after changes:
**Availability:** Daily 10am-6pm ET (7am - 3pm PT)
**ETA:** 02/15/2023 Wed 6pm ET (3pm PT)

2023-02-15 04:40 UTC, MarkWiltberger approved these changes
Looks good! Code was inspected on local machine. You completed what was requested and removed the empty line of code from check.yml. 👍

2023-02-15 04:41 UTC, angelenelm approved these changes
Approved, thanks everyone for pointing out the empty line :)

2023-02-15 04:41 UTC, MarkWiltberger commented on _data/internal/credits/check.yml
> +
Empty line has been removed and PR is approved.

2023-02-15 08:11 UTC, merged