Update project profile 3773
hackforla/website pull request #3979
Opened 2023-02-15 01:59 UTC by Satenik-Ba

Fixes #3773

### What changes did you make and why did you make them ?

  - In the Current Project Team section, updated the role of team members currently listed as "Project Manager" to "Product Manager"

<details>
<summary>Visuals before changes are applied</summary>

<img width="849" alt="Screen Shot 2023-02-14 at 5 56 50 PM" src="https://user-images.githubusercontent.com/79809138/218907846-3e6b5107-6fe7-4ea4-9b49-09983423809d.png">

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
<img width="848" alt="Screen Shot 2023-02-14 at 5 59 16 PM" src="https://user-images.githubusercontent.com/79809138/218908001-38cf3acb-1080-45a8-980a-d2dfc17835fb.png">

</details>

2023-02-15 20:25 UTC, vanessavun commented
Availability: 12PM-2PM Wed 2/15, evening Sat 2/18
ETA: Wed 2/15 by 2PM

2023-02-15 20:32 UTC, vanessavun requested changes
Thanks for working on this issue as requested. Visually it checks out and your commits are into gh-pages from your username and branch. Please review my comment about the extra line in line 41 and resubmit.

2023-02-15 20:32 UTC, vanessavun commented on _projects/home-unite-us.md
> +
Great job changing all associated "Project" to "Product" as requested in the fix and visually it reflects the changes. However, it looks like you created an extra line here. Please remove the extra line for consistency.

2023-02-16 17:30 UTC, blulady commented
@christinaor Please add your eta & availability for this PR review when you get a chance.

2023-02-16 18:03 UTC, christinaor commented
Availability: Thurs 4-5pm
ETA: Thurs 5pm

2023-02-16 20:54 UTC, christinaor commented
The changes look good on Docker! I agree with Vanessa on removing line 41 to be consistent with the rest of the formatting.

I also noticed multiple commits here. If your fork of the website was synced, and then it was merged into your local gh-pages and subsequently the update-project-profile-3773 branch, I think it is fine this time as there are multiple ways to sync your branch to the upstream gh-pages.

I will review after the resubmit - great job so far!

2023-02-16 21:36 UTC, christinaor approved these changes
Confirmed the change from "Project Manager" to "Product Manager" are still present when checking the website via Docker, and the empty line after line 40 has been removed. Great job, Satenik!

2023-02-24 01:46 UTC, Satenik-Ba commented on _projects/home-unite-us.md
> +
Hi @vanessavun changes made, but wasnt able to request a review again. if you can take a look over the changes will be great. thank you!

2023-02-24 02:21 UTC, vanessavun approved these changes
Thanks for making the changes! All in the clear.

2023-02-24 06:44 UTC, blulady commented
@vanessavun & @christinaor were you able to pull the branch into your local repo? 
`git checkout -b satenik-ba-update-project-profile-3773`
`git pull https://github.com/Satenik-Ba/website update-project-profile-3773`
I am getting a merge conflict when I pull the branch into my local. Looks like line 39, 40 and 47 need to be deleted...
Getting a merge conflict warning when I try to merge this branch into the code base. Am not seeing it in the github files changed.... Please pull into your local repos and let me know if this is a me thing...

2023-02-24 18:00 UTC, christinaor commented
@blulady The pull is now asking me to merge lines 39 to 44, which are from the addition of Kristelle Gumaru. I synced my gh-pages branch before pulling Satenik's branch again, so I think the merge conflict might be from the recently merged solutions. I can still see the changes from "Project Manager" to "Product Manager" for lines 40, 46, 52, and 58, but line 40 needs to be accepted through the addition of lines 39 to 44 in the merge conflict, at least from what I can see. Hope this helps!

2023-02-24 18:45 UTC, vanessavun commented
@blulady I'll be available tonight to check! ETA 5-6PM.

2023-02-25 07:08 UTC, vanessavun approved these changes
> @vanessavun & @christinaor were you able to pull the branch into your local repo? `git checkout -b satenik-ba-update-project-profile-3773` `git pull https://github.com/Satenik-Ba/website update-project-profile-3773` I am getting a merge conflict when I pull the branch into my local. Looks like line 39, 40 and 47 need to be deleted... Getting a merge conflict warning when I try to merge this branch into the code base. Am not seeing it in the github files changed.... Please pull into your local repos and let me know if this is a me thing...

I'm not getting any merge conflicts but I did confirm that "Project Manager" are all "Product Manager" for lines 40, 45, 52, and 58.

2023-02-25 07:09 UTC, vanessavun commented
@christinaor We need your review too.

2023-02-25 16:29 UTC, christinaor approved these changes
Based on what I saw, I think this can be approved with the thought the merge team will take care of the syncing issues between the branches.

2023-02-25 22:41 UTC, merged