Update project profile in Home Unite Us page - #3929
hackforla/website pull request #4002
Opened 2023-02-17 19:54 UTC by perlaroyerc

Fixes #r3939

### What changes did you make and why did you make them?

  - Removed "auth0" and added "Amazon Cognito" to the "technologies" vairable
  - Added three new team members to the "leadership" variable, including their name, role, slack, GitHub, and picture.
  - Removed one team member. 

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

<img width="863" alt="Screenshot 2023-02-17 at 1 44 17 PM" src="https://user-images.githubusercontent.com/72838172/219778248-2a879c6c-904c-460f-87e1-34931cc9f178.png">

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
<img width="832" alt="Screenshot 2023-02-17 at 1 50 47 PM" src="https://user-images.githubusercontent.com/72838172/219778368-a4369787-199f-4c29-897c-e83ad14daae6.png">

</details>

2023-02-17 20:08 UTC, Thinking-Panda commented
Availability: Weekdays 10 AM - 3 PM
ETA: 10 PM 2/17/23

2023-02-17 20:39 UTC, Thinking-Panda reviewed
Hi @perlaroyerc 
The production website has technologies listed as React, NoSQL, Flask, Auth0 / OIDC / OAuth2, MongoDB. 
The issue mentions to remove auth0 and add Amazon Cognito. Should the change look like 
Option 1: React, NoSQL, Flask, Amazon Cognito / OIDC / OAuth2, MongoDB
Or
Option 2: React, NoSQL, Flask, OIDC / OAuth2, MongoDB, Amazon Cognito
Please confirm with @brycelednar

2023-02-17 21:15 UTC, brycelednar commented
Hi @Thinking-Panda and @perlaroyerc , 

Option 1 looks good - thanks!

Bryce

2023-02-17 22:21 UTC, christinaor reviewed
I can see all the updates on the Home Unite Us project page in the Technologies section under Project Overview and in Current Project Team via Docker. Confirming that the front matter is formatted correctly in the markdown file as well. Awesome work there, Perla!

I'm not sure which issue the update in the website markdown is referring to or if I'm missing it in the referenced issue, but will act on this as soon as this part is clarified.

2023-02-18 06:08 UTC, Thinking-Panda commented
Changes to home_unite_us.md are approved.

There are also changes applied to website.md that is not mentioned in the related issue.

2023-02-19 07:47 UTC, jdingeman commented
Hi @perlaroyerc, I'm not sure if you may have accidentally worked on an old branch, but you will need to remove the changes made to website.md before we can merge this issue, as it has conflicts.

2023-02-19 07:48 UTC, jdingeman requested changes

2023-02-19 07:48 UTC, jdingeman commented on _projects/website.md
>      picture: https://avatars.githubusercontent.com/bishrfaisal
Hi @perlaroyerc, I'm not sure if you may have accidentally worked on an old branch, but you will need to remove the changes made to website.md before we can merge this issue, as it has conflicts.

2023-02-19 07:49 UTC, jdingeman requested changes

2023-02-19 07:49 UTC, jdingeman commented on _projects/website.md
> -  - name: Stephanie Samuels
Hi @perlaroyerc, I'm not sure if you may have accidentally worked on an old branch, but you will need to remove the changes made to website.md before we can merge this issue, as it has conflicts.

2023-02-20 19:55 UTC, perlaroyerc commented on _projects/website.md
> -  - name: Stephanie Samuels
Hi @jdingeman! My apologies, I will make sure to switch to the correct branch and remove any changes that are causing conflicts as soon as possible.

2023-02-20 22:21 UTC, closed without merging