Enhance wins alt text 3960
hackforla/website pull request #4076
Opened 2023-03-01 05:55 UTC by RyanGehris

Fixes #3960

### What changes did you make and why did you make them ?

  - Added a ternary operator on line 266 and 273 to change the alt text for each badge icon to the toolkit text when the view is 'win' or to change the alt text to '' when the view is 'overlay'
  - In phone/tablet view, when the icon container is expanded, I added a for loop on lines 407-409 to remove the alt text from the badge icons
  - In phone/tablet view, when the icon container is expanded, I added a for loop on lines 399-401 to add the correct alt text for each badge icon based on its siblings textContent

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Before and After of wins page view</summary>

## Before

![Screenshot 2023-02-28 at 9 37 59 PM](https://user-images.githubusercontent.com/105510284/222055985-3e622fc8-7bbe-4ceb-82c5-00ce8fe173c4.png)

## After

![Screenshot 2023-02-28 at 9 38 16 PM](https://user-images.githubusercontent.com/105510284/222056020-a3a911da-6156-44e4-9709-0064224019f5.png)

</details>

<details>
<summary>Before and after of overlay view</summary>
  
## Before

![Screenshot 2023-02-28 at 9 38 46 PM](https://user-images.githubusercontent.com/105510284/222056146-187a6778-80b2-4cb6-9a4e-3e15c23250c4.png)

## After

![Screenshot 2023-02-28 at 9 39 00 PM](https://user-images.githubusercontent.com/105510284/222056176-16925e67-6b12-44bf-856e-8fd741ac9a8f.png)

</details>

<details>
<summary>Before and after of wins page view NOT expanded (Phone/tablet)</summary>
  
## Before

![Screenshot 2023-02-28 at 9 39 30 PM](https://user-images.githubusercontent.com/105510284/222056445-26575a9f-9da0-4d09-9221-31b0ebbc9734.png)

## After

![Screenshot 2023-02-28 at 9 40 17 PM](https://user-images.githubusercontent.com/105510284/222056500-b092bd76-6ea1-43a8-8129-de64931dc400.png)

</details>

<details>
<summary>Before and after of wins page view  expanded (Phone/tablet)</summary>
  
## Before

![Screenshot 2023-02-28 at 9 39 55 PM](https://user-images.githubusercontent.com/105510284/222056540-5f2b591d-2dab-49b0-a082-5bad61649723.png)

## After

![Screenshot 2023-02-28 at 9 40 36 PM](https://user-images.githubusercontent.com/105510284/222056584-697016f8-a136-4fc1-8e7c-6973f21a9a6f.png)

</details>

2023-03-01 19:20 UTC, mademarc commented
Review ETA:  11:20M 3/1/22
Availability:  11:30AM weds

2023-03-01 19:42 UTC, mademarc reviewed
@RyanGehris  The format of this code looks very readable, keep it up  and great job! :)

2023-03-01 21:12 UTC, roslynwythe commented
Availability: 6-10 pm on 3/1
ETA: EOD 3/1

2023-03-02 04:05 UTC, roslynwythe requested changes
@RyanGehris Your code works perfectly at all screen widths and you made a great choice to use the text node of the bubble div to restore the alt text when the tooltips are hidden in mobile and tablet view.  I also appreciate that you fixed whitespace errors throughout the code.  I just have one nitpicky change request, to align the indenting on line 405.

2023-03-02 22:12 UTC, RyanGehris commented
@roslynwythe I just manually fixed the indenting on line 405. I use prettier so it usually formats the code automatically. Thanks for noticing that. I am always happy to make a quick easy fix!

2023-03-03 08:23 UTC, roslynwythe approved these changes
Thank you @RyanGehris for outstanding work on this PR.  You identified code changes to implement the issue for all screen sizes and developed code to provide a clean and effective solution.

2023-03-04 01:08 UTC, roslynwythe commented
Hi @mademarc, you and I are the only reviewers on this PR, so please complete your review of this issue so that it can be merged,  Be sure to test the page at mobile, tablet and wide screen sizes.   When your review is complete, please submit the "Review Changes" form which can be found on the "Files Changed" page.  If you have any questions please let me know.

2023-03-04 03:59 UTC, mademarc commented
Availability: 7:58pm on 3/2/23
ETA: 1Hr

2023-03-04 04:02 UTC, mademarc approved these changes

2023-03-05 06:07 UTC, merged