Update the value of title and description in not-today.md
hackforla/website pull request #4121
Opened 2023-03-07 00:10 UTC by mattmalane

Fixes #4082

### What changes did you make and why did you make them ?

  - Changed the value of title to `Not Today`
  - Changed the value of description to `Not Today - the self-defense against suicidal thoughts app is intended to help people wait out periods of suicidal thinking without acting on their thoughts.`
  - Confirmed in local environment that the title does not run off the mini-card.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

<img width="95" alt="mini-card-before" src="https://user-images.githubusercontent.com/73557586/223284860-02fe5e54-bb77-431b-92ef-b80a45268634.png">

<img width="919" alt="description-before" src="https://user-images.githubusercontent.com/73557586/223284886-0fce7c92-4d6a-41b2-8675-c519e8cc8223.png">

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
<img width="95" alt="mini-card-after" src="https://user-images.githubusercontent.com/73557586/223284899-a2169ca7-31fe-4e04-9622-5c1a9309aff8.png">

<img width="919" alt="description-after" src="https://user-images.githubusercontent.com/73557586/223284919-428b06bb-9845-4deb-905c-4bcaf763c983.png">

</details>

2023-03-07 22:58 UTC, jefflueck approved these changes
Looks great. I love that you included screenshots for me to look at.

2023-03-08 06:23 UTC, Adastros commented
Availability (PST): 10:30 - 11PM 07MAR23, 9 - 11 PM 07MAR23
Review ETA (PST): 11 PM 07MAR23

2023-03-08 07:07 UTC, Adastros requested changes
@mattmalane good job on completing the issue! The changes to the title and description were implemented as stated in the issue. The images provided in the pull request are excellent too. On the website, the title doesn't spill out of the card and the project page reflects the changes you implemented.

Could you add a brief statement explaining why the changes were made in your pull request comment (why change the title and description)? It's clear in this issue why, but this is mainly to get into the habit of good documentation practices.

2023-03-08 23:35 UTC, mattmalane commented
> Looks great. I love that you included screenshots for me to look at.

Thanks for the review Jeff!

2023-03-08 23:37 UTC, mattmalane commented
> @mattmalane good job on completing the issue! The changes to the title and description were implemented as stated in the issue. The images provided in the pull request are excellent too. On the website, the title doesn't spill out of the card and the project page reflects the changes you implemented.
> 
> Could you add a brief statement explaining why the changes were made in your pull request comment (why change the title and description)? It's clear in this issue why, but this is mainly to get into the habit of good documentation practices.

Hi Danny, thanks for reviewing this PR. I updated my PR comment to include brief explanations on why changed were made.

2023-03-09 06:36 UTC, Adastros approved these changes
@mattmalane thanks for implementing the update. Looks good!

2023-03-09 06:37 UTC, merged