Create and Swap Sass Color Variable in project.html - #4138
hackforla/website pull request #4148
Opened 2023-03-11 06:26 UTC by perlaroyerc

Fixes #4138 

### What changes did you make and why did you make them?

  - Created "color-cyanblue" variable in variables/_colors.scss file.
  - Replaced the hardcoded color in _layouts/project.html with the created color variable.
  - Why? The Sass variable can be reused throughout the project resulting in a more maintainable and clean code.

No visual changes to the website.

2023-03-12 17:29 UTC, Skydodle commented
Availability: Monday 3/13/23 6 to 8pm
ETA: EOD Monday 3/13/23

2023-03-12 17:31 UTC, roslynwythe commented
Availability: 3/12 7-9 pm
ETA EOD 3/12

2023-03-13 17:01 UTC, roslynwythe requested changes

2023-03-13 17:01 UTC, roslynwythe commented on _layouts/project.html
> +      style="margin: 0; border: 2px; color: color-cyanblue; box-sizing: border-box">
Hi @perlaroyerc great job on defining the new color and modifying the existing styles.  Currently the element you modified is not being rendered on the page, due to the liquid test, and so it is difficult to test in the browser.  This is an extremely minor point but I believe your statement would be cleaner and more consistent with the original syntax if you continued to use the 'border shorthand' format, like this:
`style="margin: 0; border: 2px solid color-cyanblue; box-sizing: border-box">`

2023-03-13 17:14 UTC, roslynwythe requested changes

2023-03-13 17:14 UTC, roslynwythe commented on _layouts/project.html
> +      style="margin: 0; border: 2px; color: color-cyanblue; box-sizing: border-box">
Hi @perlaroyerc great job defining the new sass variable for the color, and modifying the html to use the variable.  It appears that the modified html is not rendered due to the liquid condition so it cannot be viewed in the browser.  This is a very minor point but I believe it would be a cleaner solution to stick with the border shorthand syntax used in the original code, as follows:
style="margin: 0; border:  2px  color-cyanblue; box-sizing: border-box">

2023-03-13 17:28 UTC, roslynwythe commented
Hi @jdingeman this issue modified styling of iframes on the projects page, but it appears that due to the liquid condition `{% if page.iframe.available == true %}`, there are no instances of iframes appearing on the projects page.  If the iframe will no longer be used, we might want to create another issue to clean up the code by removing the liquid condition and html inside it.

2023-03-14 16:25 UTC, Skydodle commented
Hi @perlaroyerc, great job on creating a new color variable and replacing the hardcoded values.

Aside from what @roslynwythe mentioned about using the border shorthand syntax as well as retaining the solid styling for the border from the original code, I also recommend that you add the pull request to the project board. You can find instructions [here](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#v-complete-pull-request-5-how-to-add-a-pull-request-to-the-project-board) in the contirbuting.md if you need any guidance.

Thank you so much for your help!

2023-03-14 22:22 UTC, perlaroyerc commented
Hi! Thank you @roslynwythe and @Skydodle for your input. I have renamed the variable name to "mediumdarcyanblue" as it looked more cohesive with the rest of the color variables and updated the border syntax. I also added the PR to the Project Board, as Jhonny pointed out.

2023-03-16 04:09 UTC, Skydodle approved these changes
I see that the color variable mediumdarkcyanblue was created for a more distinguishable variant of cyan blue,  border was changed to shorthand syntax correctly that includes the solid style, and PR was added to project board.

Great job! @perlaroyerc

2023-03-16 19:19 UTC, roslynwythe approved these changes
Thank you @perlaroyerc for a great job on this issue.  The branches are correct, the code is clean, and it looks great in the browser.

2023-03-16 19:20 UTC, merged