Implement redsigned donate page 3983
hackforla/website pull request #4197
Opened 2023-03-16 20:31 UTC by Thinking-Panda

Fixes #3983

### What changes did you make and why did you make them ?

  - changed images based on Figma design
  - altered text content based on Figma design
  - edited stylesheet to incorporate changes based on Figma design by adding a couple of new classes and removing a few classes
  - I have added screenshots of different viewports below

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

![donate_mobile](https://user-images.githubusercontent.com/122488603/225744486-c55da9f5-d794-421c-aaf2-d981f54ac941.png)
![donate_tablet](https://user-images.githubusercontent.com/122488603/225744536-fc1954cc-4cf4-4521-ba38-a0fa2685e881.png)
![donate_desktop](https://user-images.githubusercontent.com/122488603/225744550-ebb9edfd-1bf7-44ec-80d4-901ddcf4cf0d.png)

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
![redesigned_mobile](https://user-images.githubusercontent.com/122488603/225744619-a9ca63e6-1ab7-4352-8e06-ca289952bbbe.png)
![redesigned_tablet](https://user-images.githubusercontent.com/122488603/225744659-985a1e76-da9f-47db-889b-ab5351734eef.png)
![redesigned_desktop](https://user-images.githubusercontent.com/122488603/225744695-4bb981a1-b601-4933-a526-0998f054c5a0.png)

</details>

2023-03-19 09:19 UTC, roslynwythe commented
Availability: 3/19 2 - 4 pm
ETA EOD 3/19

2023-03-19 14:32 UTC, Suman2795 commented
Review ETA : 19/03/23
Availability :3 hours

2023-03-19 20:05 UTC, roslynwythe commented
Thank you @Thinking-Panda for your excellent work on this issue.  The branches are setup correctly, the PR is descriptive, and the branch looks great in the browser at all screen sizes.  I was a bit surprised at how extensive the changes were in the .html and .scss files.  It would be useful for reviewers if you could explain a bit about those changes.

2023-03-20 06:57 UTC, roslynwythe submitted a review, later dismissed
Thank you @Thinking-Panda for your excellent work on this issue. The branches are setup correctly, the PR is descriptive, the html and scss are clean and well organized, and the branch looks great in the browser at all screen sizes.

2023-03-20 18:08 UTC, Thinking-Panda commented
Hello @roslynwythe and @Suman2795 , I have edited the PR with details of code changes in each file. Hope this helps.

2023-03-20 22:53 UTC, jdingeman commented
Hello @Suman2795 - wanted to check in for your review?

@Thinking-Panda - it looks like there are merge conflicts. You may want to identify and resolve these before the merge can be made.

2023-03-21 07:29 UTC, roslynwythe commented
Hi @Thinking-Panda it looks like in a recent PR #4210, line 14 in _includes/donate-card.html was modified to update the alt text.  So when resolving the merge conflict, you will want to retain that line.  Let me know if you need assistance with that.

2023-03-21 15:32 UTC, Suman2795 submitted a review, later dismissed
Nice work @Thinking-Panda . The branches are merged correctly, website works good on the local machine in different modes and code changes are as per the action items in the issue.

2023-03-21 17:23 UTC, Thinking-Panda commented
> Hi @Thinking-Panda it looks like in a recent PR #4210, line 14 in _includes/donate-card.html was modified to update the alt text. So when resolving the merge conflict, you will want to retain that line. Let me know if you need assistance with that.

Thank you @roslynwythe. I really need your assistance on resolving the conflict. I noticed the conflict but wasn't sure how to resolve it. Please let me know how to identify and retain that line.

2023-03-23 06:40 UTC, roslynwythe approved these changes
@Thinking-Panda thank you for resolving the merge conflict and then following up with the update to alt text in donate.html.  I've re-reviewed the issue and everything still checks out fine in the browser including the alt text.

2023-03-23 06:47 UTC, roslynwythe commented
Hi @Suman2795 this is a reminder that we have to re-review the PR because of the merge conflict.  After resolving the merge conflict, a new commit was required to restore the alt text on the donation graphic.

2023-03-23 07:09 UTC, Suman2795 approved these changes, later dismissed

2023-03-23 18:29 UTC, roslynwythe requested changes
@Thinking-Panda There is a possible problem with moving the images to donate.html: that is, this page: https://www.hackforla.org/join that also includes donate-card.html.   If you look at the Join Us page in your branch, you will see that it is missing the elements that were moved from donate-card.html to donate.html, so I need to ask that you restore those elements into donate-card.html.

2023-03-23 19:08 UTC, Thinking-Panda commented
@roslynwythe , I see the missing image. I will make changes needed and update here.

2023-03-24 02:02 UTC, mademarc commented
Review ETA:  3/23/2023
Availability: 7:05PM Monday

2023-03-24 02:07 UTC, mademarc approved these changes, later dismissed
Hey  @Thinking-Panda the ul  elements looks very well updated and the media queries code was coded done correctly.

2023-04-07 23:39 UTC, roslynwythe approved these changes
Great work @chrismenke45 on quite a challenging large issue.  You've implemented a powerful live filtering feature, complete with dynamic filter lists that are very usable.  The PR was well formed and you responded to all requests thoughtfully and patiently.   Thank you!

2023-04-07 23:44 UTC, roslynwythe requested changes
Hi @Thinking-Panda please advise, do you require assistance understanding the changes requested in https://github.com/hackforla/website/issues/3983#issuecomment-1496503522

2023-04-13 17:26 UTC, Thinking-Panda commented
Changes requested are being worked on. New commits will me made by 4/17/23

2023-04-17 19:19 UTC, Thinking-Panda commented
@roslynwythe , @Suman2795 , @mademarc - Changes requested has been made after the issue was re-written. Please re-review this PR and let me know your thoughts.

2023-04-17 23:21 UTC, roslynwythe requested changes
Hi @Thinking-Panda there is a problem with overlapping text next to the animated donation gif from screen widths 480 px to 700 px.  This is at 600px width.  
![image](https://user-images.githubusercontent.com/5314153/232631373-300cfab4-de56-423a-b34f-d6a1bde722f2.png)

2023-04-18 06:58 UTC, roslynwythe commented on _includes/donate-card.html
> +  <h3 class="title6 donate-title ">Provide In-Kind Software & Services</h3>
Hi @Thinking-Panda This card (under the donation circles graphic) does not match the Figma design.  The card should start with the header ""How" to help us continue to do impactful work" which was present in your initial commit, in donate-card.html, but is now missing. 
![image](https://user-images.githubusercontent.com/5314153/232696573-d0245432-76ca-43d6-835e-0001864d8fba.png)

2023-04-18 18:27 UTC, Thinking-Panda commented on _includes/donate-card.html
> +  <h3 class="title6 donate-title ">Provide In-Kind Software & Services</h3>
> Hi @Thinking-Panda there is a problem with overlapping text next to the animated donation gif from screen widths 480 px to 700 px. This is at 600px width. ![image](https://user-images.githubusercontent.com/5314153/232631373-300cfab4-de56-423a-b34f-d6a1bde722f2.png)

Working on it @roslynwythe. I will update soon.

2023-04-18 18:29 UTC, Thinking-Panda commented on _includes/donate-card.html
> +  <h3 class="title6 donate-title ">Provide In-Kind Software & Services</h3>
Regarding the card that starts with "How to ....", Bonnie mentioned the change that I have implemented ,in the comments section of the issue #3983

2023-04-18 23:19 UTC, Thinking-Panda commented
@roslynwythe , I have fixed the overlapping text and pushed the changes. Let me know about the In Kind donation card information. Which one should I keep "How to..." or "Provide In-KInd..." ?

2023-04-18 23:25 UTC, roslynwythe commented on _includes/donate-card.html
> +  <h3 class="title6 donate-title ">Provide In-Kind Software & Services</h3>
I see.  I apologize for the confusion.  

Please post your progress, availability and ETA for the other requested change.  As I mentioned, this issue is now time-sensitive, so we need to know when we can expect an update.  Thank you!

2023-04-19 01:52 UTC, roslynwythe approved these changes
Awesome work @Thinking-Panda.  The branches have been setup correctly, you described your work and provided screenshots after each update.  Both the Donate and Join Us pages look good in the browser at mobile, desktop and tablet screen sizes.  Thank you for your patience and persistence in this PR.

2023-04-19 02:18 UTC, mademarc commented
Review ETA: 4/18/2023
Availability: 7:20 PM

2023-04-19 02:30 UTC, mademarc approved these changes
Hey  @Thinking-Panda the code looks better structured and very readable also  thanks to @roslynwythe in making the marking these changes... well done

2023-04-19 18:26 UTC, roslynwythe reviewed
Hi @Thinking-Panda while we're waiting for the final review, I have a minor request.  The second bullet point in your PR is a bit confusing, because the donation-graphic.svg did not actually replace solidarity-pana.svg.  Please correct me if I'm wrong but it appears that solidarity-pana.svg was removed, and donation-graphic.svg was replaced with a more recent design.  Thanks.

2023-04-20 06:28 UTC, Thinking-Panda commented
> Hi @Thinking-Panda while we're waiting for the final review, I have a minor request. The second bullet point in your PR is a bit confusing, because the donation-graphic.svg did not actually replace solidarity-pana.svg. Please correct me if I'm wrong but it appears that solidarity-pana.svg was removed, and donation-graphic.svg was replaced with a more recent design. Thanks.

Hi @roslynwythe 
solidarity-pana.svg is the image on the donate page of the published website.
![Screenshot 2023-04-19 225008](https://user-images.githubusercontent.com/122488603/233270596-51425a34-f08d-48e9-85e3-f7af8772107c.jpg)
I have replaced it with the vertical three circle image as per Figma design.
Hope this answers your question.

2023-04-20 07:00 UTC, merged