Renamed citizen engagement file
hackforla/website pull request #4205
Opened 2023-03-18 02:07 UTC by arcan9

Fixes #3756 

### What changes did you make and why did you make them ?

  - Renamed the `citizen-engagement-cards.html` to `program-area-pages-cards.html` so that the name of the file reflects the purpose of the card better.
  -  In `pages/citizen-engagement.html`, this line
```
{% include citizen-engagement-cards.html %}
```
is changed to
```
{% include program-area-pages-cards.html %}
```

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
Only the file name and the markup were changed. No visual changes to the website. Looks good on desktop, tablet and mobile, and functions like before.

2023-03-19 17:31 UTC, bootcamp-brian commented
Review ETA: End of day today
Availability: All day today

2023-03-19 19:58 UTC, bootcamp-brian requested changes
Good job getting the branches set up right and the issue linked as well as making all the requested changes from the issue. The only thing I would change is that I would add the changes you made inside the _includes/program-area-pages-cards.html file to your list of you made in your pull request comment.

2023-03-19 20:20 UTC, arcan9 commented
@bootcamp-brian Thanks! I've updated my PR.

2023-03-19 20:26 UTC, bootcamp-brian approved these changes
Everything looks good now. Great job!

2023-03-20 02:51 UTC, oliviazhai approved these changes
this looks good to me!

2023-03-20 04:18 UTC, t-will-gillis approved these changes
Hey @arcan9 - Great job on this issue! Your from and to branches are correct, and you addressed the requirements of the issue. And you made the changes to the description working with @bootcamp-brian - good teamwork! I also checked on Docker and the `/citizen-engagement` page seems to be working as before. 

Great job again-

2023-03-20 04:25 UTC, t-will-gillis commented
As a reminder, there is one additional item to change the wiki, shown on #3756 , to be done after this is merged. Thanks for your work!

2023-03-20 04:25 UTC, merged