GitHub Img Alt Text Changed 4088
hackforla/website pull request #4259
Opened 2023-03-23 07:43 UTC by richardmundyiii

Fixes #4088

### What changes did you make and why did you make them ?

  - added empty alt tag to GitHub icon in wins-card-template.html
  - assigned alt text dynamically on page load and on overlay ("See More" in for wide-screens)
  - the change was made to conform to WCAG guidelines for providing meaningful alt text

### Screenshots of Proposed Changes Of The Website  (if any, please do not screenshot code changes)

No visual changes to the website

2023-03-23 15:59 UTC, arcan9 commented
Review ETA: EOD 03/23/23
Availability: 5-8pm, M-F

2023-03-23 23:07 UTC, arcan9 requested changes
Great start @richardmundyiii! I added a few inline comments.

2023-03-23 23:07 UTC, arcan9 commented on _includes/wins-page/wins-overlay.html
> +              <span id="overlay-icons" class="wins-card-icons" alt=""></span>
Regarding this additional `alt` tag in `_includes/wins-page/wins-overlay.html`, I didn't see a bullet point about this in the original issue. This `alt` is targeting the group of icons rather than the individual Github icon. Checking it on my local host, this alt doesn't have a value when inspecting. I'm wondering if it's needed?

Feel free to point out if I overlooked something, @richardmundyiii. Just wanted to clarify, is all!

2023-03-23 23:07 UTC, arcan9 commented on assets/js/wins.js
> +			cloneCardTemplate.querySelector('.github-icon').alt = `github of ${card[name]}`;
Nit: `Github profile for ${card[name]}`

2023-03-23 23:07 UTC, arcan9 commented on assets/js/wins.js
> +  			makeIcon(data[i][github_url], overlayIcons, 'github-icon', '/assets/images/wins-page/icon-github-small.svg', 'Github profile for' + data[i][name]);
I think you duplicated this code then added your modification. This current change reflects two Github icons in the upper right when "See More" is clicked in wide-screen view:

![Screenshot 2023-03-23 150706](https://user-images.githubusercontent.com/102492480/227381115-940700ee-f24f-47cb-8bd1-bb43b6f4ad40.png)

To solve this, remove the duplicated code then just go back to the first `makeIcon()` and add `'Github profile for ' + data[i][name]` as its last argument. Make sure to add an empty space after the word "for" and before the closing quotation mark. Otherwise, "for" and the person's name will be one word (e.g. "Github profile forJohnSmith").

2023-03-24 02:08 UTC, mademarc commented
Review ETA:  3/23/2023
Availability:  7:10PM Monday

2023-03-24 02:10 UTC, mademarc submitted a review, later dismissed
Hey @richardmundyiii  the alt along with the empty variable was done correctly onthe a tag and span elements.

2023-03-25 02:29 UTC, richardmundyiii commented on _includes/wins-page/wins-overlay.html
> +              <span id="overlay-icons" class="wins-card-icons" alt=""></span>
@arcan9 There was no bullet point in the original issue but rather a request from @roslynwythe who also completed a task similar to this one. (https://github.com/hackforla/website/pull/4223).

2023-03-25 02:30 UTC, richardmundyiii commented on assets/js/wins.js
> +			cloneCardTemplate.querySelector('.github-icon').alt = `github of ${card[name]}`;
Thank you for catching this.

2023-03-25 02:30 UTC, richardmundyiii commented on assets/js/wins.js
> +  			makeIcon(data[i][github_url], overlayIcons, 'github-icon', '/assets/images/wins-page/icon-github-small.svg', 'Github profile for' + data[i][name]);
Removed the unnecessary line.

2023-03-25 03:04 UTC, arcan9 commented on _includes/wins-page/wins-overlay.html
> +              <span id="overlay-icons" class="wins-card-icons" alt=""></span>
@richardmundyiii Thanks for clarifying!

2023-03-25 09:15 UTC, arcan9 submitted a review, later dismissed
Thank you for making the changes. Refactoring looks good. Great on web browser, tablet, and mobile views. Great work @richardmundyiii!

2023-03-25 19:43 UTC, richardmundyiii commented
> Hey @richardmundyiii the alt along with the empty variable was done correctly onthe a tag and span elements.

Thanks @mademarc. I see you left a comment but didn't approve or request changes.

2023-03-25 23:06 UTC, mademarc submitted a review, later dismissed

2023-03-26 20:22 UTC, t-will-gillis commented on _includes/wins-page/wins-overlay.html
> +              <span id="overlay-icons" class="wins-card-icons" alt=""></span>
Hi @arcan9 and @richardmundyiii - I think there are some good arguments about which person should mark a conversation as resolved/select the 'Resolve conversation' button below. Should it be the person who created the comment, the person who responded to the comment, or whoever is merging? In a case like this, my vote would be for the person who asked the question/made the comment (i.e. arcan9) to 'Resolve conversation' during a re-review if they believe the other person (richardmundyiii) has answered or addressed the comment/ question. 

But you will see [arguments](https://github.com/distributed-system-analysis/pbench/discussions/2113?sort=top) other ways. Sounds like a good discussion to have in the org- stay tuned. In the meantime I will 'Resolve' it

2023-03-26 21:09 UTC, t-will-gillis submitted a review, later dismissed
Hey @richardmundyiii ! The basics are good- Correct branches, correctly linked issue and good explanation in the PR description. You addressed all points in the issue. Great job!

Also wanted to say that your back and forth with @arcan9 was great to see- this is how it is supposed to work! Thanks for taking care of this

2023-03-26 21:13 UTC, t-will-gillis approved these changes
Resolved merge conflict

2023-03-26 21:14 UTC, merged