Projects filters 3744
hackforla/website pull request #4280
Opened 2023-03-24 19:56 UTC by chrismenke45

Fixes #3744

### What changes did you make and why did you make them ?

  - current-projects.html was changed to include proper elements for the js file to add filter elements to after DOM loaded
  - _base.scss was changed to have clip overflow instead of hidden to allow sticky filter sidebar to work **THIS COULD POTENTIALLY AFFECT OTHER PAGES OF THE SITE (it changes a css value on the html&body elements), BUT I DON'T THINK IT HAS**
  - _filter_dropdown.scss was updated to reflect new styling of filters
  - current-projects.js was updated to allow filters to be used as shown in Figma

### Screenshots of Proposed Changes Of The Website 

<details>
<summary>Visuals before changes are applied</summary>

Desktop Layout Before Changed
<img src="https://user-images.githubusercontent.com/86500980/227623124-dad66abe-a74b-49f9-a78e-f2b25a3ceab6.png" width="" length="" />

Mobile Layout Before Changed
<img src="https://user-images.githubusercontent.com/86500980/227623158-45d34f99-e19c-4eb9-a302-fe372170a879.png" width="" length="" />

</details>

<details>
<summary>Visuals after changes are applied</summary>
  

Desktop Layout After Changed
<img src="https://user-images.githubusercontent.com/86500980/227623832-c6624c74-7f37-4e29-a333-d0cc9e0517ad.png" width="" length="" />

Mobile Layout After Changed
<img src="https://user-images.githubusercontent.com/86500980/227624107-a2495355-6a17-48b1-bdfa-cc46a788ed13.png" width="" length="" />

Mobile Layout After Changed (Filter Pop up)
<img src="https://user-images.githubusercontent.com/86500980/227625142-039a1d77-9bf2-493b-a8b4-937905336619.png" width="" length="" />

</details>

2023-03-24 22:19 UTC, ExperimentsInHonesty commented
I left a note on the issue this is from https://github.com/hackforla/website/issues/3744#issuecomment-1483496383

2023-03-24 23:39 UTC, chrismenke45 commented
Filter-Toolbar padding was reduced(by ~35%). I left a decent chunk there because I'm trying to make it at the level it should be with the search bar when it is implemented. If I should move it up further, please let me know :)

2023-03-27 08:32 UTC, roslynwythe commented
Availability: 3/27: 10 am - noon, 3/28 10 am - 1 pm
ETA EOD 3/29

2023-03-28 01:43 UTC, roslynwythe commented on _includes/current-projects.html
> +          {% include svg/icon-hamburger-nav.svg %}
Hi @chrismenke45 I really like the use of the <button> element with the aria label for accessibility, but one result of using the include (which is also included in the page header) is that the resulting page has two elements with the identical id="hamburger-nav".  I'm not certain this is a problem, just asking if it might be.

2023-03-28 02:07 UTC, chrismenke45 commented on _includes/current-projects.html
> +          {% include svg/icon-hamburger-nav.svg %}
@roslynwythe Thank you for catching that! I think that will be a problem. I'll discuss it with the team tomorrow (idk if i should be adding an svg to our codebase or take another course of action). Let me know if you see anything else that requires a change.

2023-03-28 07:05 UTC, roslynwythe commented on _includes/current-projects.html
> +          {% include svg/icon-hamburger-nav.svg %}
Hi @chrismenke45 The sidebar looks great but it looks like it is placed a bit low relative to the project cards.  From the screenshot in Bonnie's comment https://github.com/hackforla/website/issues/3744#issuecomment-1483496383, the Figma design calls for the top edge of the project cards to be aligned with the horizontal bar separating the Filters heading and the Program Areas link.

2023-03-28 20:43 UTC, chrismenke45 commented on _includes/current-projects.html
> +          {% include svg/icon-hamburger-nav.svg %}
Hi @roslynwythe 
I just moved the filters up so their top is inline with the project cars top. Thank you for all the feedback! :) Let me know if theres anything else I can change.

2023-03-29 02:55 UTC, chrismenke45 commented on _includes/current-projects.html
> +          {% include svg/icon-hamburger-nav.svg %}
Hi @roslynwythe 
Justin and I spoke about the svg's at tonights meeting and landed on me putting the svg's directly into my html instead of {%- include -%}'ing them. He also let me know you were looking further into this, so if you have a different preferred fix please let me know and I'll make the change!

2023-03-30 09:20 UTC, roslynwythe commented on assets/js/current-projects.js
> +        <span class='labelArrow' tabindex="0" aria-label="Toggle Show ${filterTitle} Filters"> ∟ </span>
Hi @chrismenke45 the `aria-label` on this line is great, but since this `<span>` is behaving as a button, toggling the opening/closing of the filter dropdown, I suggest adding `role="button"`.   The same is true for the `a.clear-filter-tags` and `li.view-all` elements.  

If you prefer I can make an ER for these items.

2023-03-30 09:20 UTC, roslynwythe commented on _includes/current-projects.html
> +          {% include svg/icon-hamburger-nav.svg %}
Hi @chrismenke45 that solution works for me!

2023-03-30 17:09 UTC, chrismenke45 commented on assets/js/current-projects.js
> +        <span class='labelArrow' tabindex="0" aria-label="Toggle Show ${filterTitle} Filters"> ∟ </span>
Hi @roslynwythe 
I just added the role="button" to those 3 elements. 
Sidenote: What does ER stand for? I'm assuming its something about creating a new issue after this one but I'm not sure.

2023-04-02 07:41 UTC, roslynwythe commented on assets/js/current-projects.js
> +        <span class='labelArrow' tabindex="0" aria-label="Toggle Show ${filterTitle} Filters"> ∟ </span>
Hi @chrismenke45 you are correct, ER stands for "Emergent Request" and is used to document requirements that arise while an issue in progress, that would fall outside the scope of the issue.  

I apologize for the delay in re-reviewing.  I will work on it tomorrow, and I will encourage others at the meeting, to review the item.

2023-04-03 05:29 UTC, bzzz-coding commented
Availability: Tuesday and Thursday evenings
ETA: EOD 4/5/23

2023-04-04 00:29 UTC, ExperimentsInHonesty commented
Looks good.

2023-04-05 19:54 UTC, bzzz-coding commented
@chrismenke45 Great job on adding the filter! The styles look good to me, and the tab focus worked on different screen sizes—thanks for ensuring good accessibility for the UX! 
One thing I've noticed is that on medium-sized screens, the filter takes up half of the width (see screenshot for a screen width of 780px), and I wonder if that's the intended design. In my opinion, the filter shouldn't take more than 1/3 of the width, but that's subjective. I can't find a layout design in Figma that was made for medium-sized screens, nor have I found documentation that specify the column ratio for the filter and cards. What are your thoughts on this?

2023-04-06 03:17 UTC, chrismenke45 commented
Hi @bzzz-coding,
I reached out to @sijiapitts (the designer) on slack to see if she could shed some light on this.

2023-04-06 04:19 UTC, chrismenke45 commented
Hi @bzzz-coding,
I got a response from sijia:
"But the issue is we only designed for desktop and mobile, not in between sizes. I’m thinking maybe we should use the mobile filter style for tablet size as well"
Do you think that'll work? I can make the changes.

2023-04-06 04:39 UTC, bzzz-coding commented
@chrismenke45 and @sijiapitts thank you for your input! Since we don't have a design made for medium-sized screens, I think whichever design the team thinks works best for this screen size would work. 
@chrismenke45 Great job adding the filter! :)

2023-04-06 14:48 UTC, chrismenke45 commented
Hi @bzzz-coding 
I changed the breakpoint from $screen-tablet(768px) to $screen-desktop(960px). See below for the layout right before the new breakpoint at 960px. I will also be following up with @sijiapitts on slack to confirm this is an appropriate breakpoint. If not, I will add a custom breakpoint (as apposed to using our breakpoint values in scss variables).
![Screen Shot 2023-04-06 at 7 41 41 AM](https://user-images.githubusercontent.com/86500980/230415404-2b3e4128-d175-4305-a9f1-51a9bab48ac2.png)

2023-04-06 17:36 UTC, roslynwythe commented
Hi @chrismenke45 the initial page load on desktop now has too much space between the filters and cards:
![image](https://user-images.githubusercontent.com/5314153/230454164-c0a94800-d6f8-4c13-ab6a-0ea21b9dfe3c.png)

2023-04-06 17:38 UTC, roslynwythe requested changes
Hi @chrismenke45 now in desktop view there is too much space between the filter and cards:

![image](https://user-images.githubusercontent.com/5314153/230454438-8122cf49-563f-4b26-a01c-16d6d3256ebc.png)

2023-04-06 17:46 UTC, bzzz-coding commented
@chrismenke45 I was wondering if using aspect ratios or adjusting the column span would be a more responsive approach than setting a px width. 

That said, you've also been working super hard on this issue and because there was no design for medium-sized screens, I'm not sure if adjusting layouts for medium-sized screens is out of the scope of this current issue. @roslynwythe What are your thoughts on this?

2023-04-06 18:18 UTC, chrismenke45 commented
@bzzz-coding & @roslynwythe,
Thank you for all the help on this issue.
In regards to the extra space between the filter and the cards on a large screen I have three possible solutions:
1. Bitian's solution of setting the filters+project cards container to be 1fr for the filters and 2fr for the cards
2. Add another column of project cards so they take up more space on the screen
3. Add a max-width to the filters+project cards container so they are always next to each other and a wide screen will just have margins on the sides

Let me know what you think

2023-04-06 21:13 UTC, bzzz-coding commented
@chrismenke45 Thank you for proposing different solutions! I'm not an expert on frontend, but I do remember using something like `autofit` and setting a max value for `grid-template-columns` to control the maximum width of a column, as you suggested in solution 3. Or, maybe setting something like `grid-template-columns: 1fr 2fr;` alone would solve the problem?
Ultimately, I believe it's up to you to decide which CSS trick to use in order to change the layouts. Perhaps you can start with the one you're most familiar with and see if it works as intended?

2023-04-06 21:28 UTC, roslynwythe commented
@chrismenke45 @bzzz-coding I am not inclined to request further development on this PR for the sake of the medium sizes screens.  I would prefer that we restore the desktop view to match the Figma design and leave the mid-size screen view as it  was.  You could create an ER to deal with the mid-sized screen.  But I'm not the dev lead, so if either of you feel otherwise, please ask Justin to take a look.

2023-04-06 21:42 UTC, bzzz-coding commented
@chrismenke45 @roslynwythe I'm fine with the previous layout too and would approve the PR if you decide to change it back. Just let me know. Excellent job!

2023-04-06 23:34 UTC, bzzz-coding approved these changes
@chrismenke45 Excellent job on adding the filter section to the page🌟! 
Thank you for problem-solving and being flexible about different approaches to resolve an issue. 🙌

2023-04-06 23:38 UTC, chrismenke45 commented
@bzzz-coding @roslynwythe 
Thank you for all the help with my issue.
@roslynwythe If this last change was not what you had in mind, please let me know and I'd be happy to change it

2023-04-07 23:43 UTC, roslynwythe approved these changes
Great work @chrismenke45 on quite a challenging large issue.  You've implemented a powerful live filtering feature, complete with dynamic filter lists that are very usable and look great.  The PR is well formed and you responded to all requests thoughtfully and patiently.   Thank you!

2023-04-08 00:20 UTC, merged