Update Project Profile Card Review & Update template
hackforla/website pull request #4290
Opened 2023-03-26 04:55 UTC by drakenguyen4000

Fixes #4268

### What changes did you make and why did you make them ?
  - Replaced the content in the value field on line 332 with "If you need to update your meeting times, names, dates, or frequency, please see the [VRMS User Guide](https://github.com/hackforla/VRMS/wiki/User-Guide).  The HackforLA.org website gets the meeting times from the updates the Project PM makes to the projet's meeting data in vrms.io"
  - Remove lines 311 - 324

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
- Modified codes of HackForLA github Issue Template.  No visual changes to the website.

2023-03-26 17:20 UTC, bootcamp-brian commented
Review ETA: By end of day tomorrow
Availability: Weekdays this week before 5pm

2023-03-27 05:18 UTC, mjshelton12 commented
Review ETA: Done by noon tomorrow if not tonight
Availability: Tonight until 11pm, tomorrow 9am-12pm

2023-03-27 16:47 UTC, LOSjr4 commented
Review ETA: by noon today 3/27/2023
Availability: Mon., Tues., Thurs 9am-1pm

2023-03-27 20:21 UTC, bootcamp-brian requested changes
Thanks for working on this issue, @drakenguyen4000. The issue is linked and the branches are setup right. And good job following the instructions on the issue. I did notice a typo in the change to the value field. It says "projet's" instead of "project's". Looks like that was a typo on the issue instructions though and it was just copied over from there. So it turns out you just followed the instructions a little too well is all.

2023-03-27 23:18 UTC, LOSjr4 requested changes
Aside from the "projet's" typo Brian first pointed out, everything else checks out and you followed all of the submission protocols correctly. Add that "c" and thanks for submitting nice clean work Drake!

2023-03-28 03:57 UTC, drakenguyen4000 commented
Good catch, guys!  I'll be more thorough next time.  I made the spelling change as recommended and the commit is ready for review.

2023-03-28 18:59 UTC, LOSjr4 approved these changes
Yep, you fixed it. Thank you for updating it so quickly Drake!.

2023-03-28 19:54 UTC, bootcamp-brian approved these changes
Everything looks good to me now. Thanks for making the changes and good job!

2023-03-28 21:55 UTC, mjshelton12 approved these changes
Excellent work - branches are great, code is clean, changes are effective! Nice work adjusting the spelling error in a timely manner as well!

2023-03-28 22:51 UTC, plang-psm approved these changes
Great job. I will be merging your PR into production.

2023-03-28 22:51 UTC, merged