Update project profile for civic tech jobs 4127
hackforla/website pull request #4406
Opened 2023-04-04 16:48 UTC by janice87

Fixes #4127 

### What changes did you make and why did you make them ?

  - The Civic Tech Jobs project page needs to be updated with the current team's information
  - Removed the following members: Syed Danish Imran, Kevin Park, Grace Lin, Maria Elizabeth Rodriguez Beltran, Stephanie G Stahlberg, Helene Dendor and Summer Kim
  - Edited: Ava Li from Full Stack Developer to Development Lead, updated Jen Chung's slack ID and changed role from UX/UI Designer to UX/UI Design Lead
  - Added the following new members: Noor Grewal, Tin Wei Chung, Lu Feng, Gabriel Vicencio, Melinda Sukosd, Beth Williford, Genggeng Zhang and Karen Coronel

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

![ct1](https://user-images.githubusercontent.com/97845061/229860469-0ed28a74-82df-4be3-81e9-5f662b30764d.JPG)

</details>

<details>
<summary>Visuals after changes are applied</summary>

![ct2](https://user-images.githubusercontent.com/97845061/229860548-cc503f8a-468d-4d2a-81f2-b0e4418a07ec.JPG)
</details>

2023-04-04 20:13 UTC, LOSjr4 commented
Availability: tues, fri, mon
ETA: today (4/4 -3pm)

2023-04-04 22:15 UTC, LOSjr4 reviewed
@janice87, There were a lot of changes and you handled them perfectly. 
However, @kcoronel I want to bring to your attention what I believe is a typo on the original instructions. Melinda Sukosd and Beth Williford have the same Slack Member IDs.
![image](https://user-images.githubusercontent.com/100797135/229933568-63900d11-9003-4341-a417-4547a57fb6c8.png)

ETA: I will be out the next few days, but hopefully be able to give final approval on Friday.

2023-04-04 22:19 UTC, kcoronel commented
Hi there, updates below: 

Melinda Sukosd -
Slack ID: U03T1G9F46P 

Beth Williford 
Slack ID: U0312CTAZS4

2023-04-04 22:36 UTC, janice87 commented
@LOSjr4 Good catch on the slack IDs. I updated it with the new slack IDs provided. Thank you!

2023-04-04 22:59 UTC, LOSjr4 approved these changes, later dismissed
I see the correction and I'm impressed by the fast return of both @janice87 and @kcoronel. Teamwork makes the dreamwork!

2023-04-04 23:07 UTC, LOSjr4 commented
BTW @kcoronel I added you as a reviewer to bring up the typo, but I'm not certain if that was the correct protocol. Just letting you know so you can complete the review or remove yourself as a reviewer.

2023-04-04 23:08 UTC, jdingeman requested changes
Holding merge until org rep provides us with information needed.

2023-04-05 22:05 UTC, jdingeman requested changes
Hello @janice87, please add the following to the team

Name: Matt Pereira
GitHub Handle: @MattPereira
Role: Developer
Slack Member ID: U045XKKB5DH

Name: Bitian Zhang
GitHub Handle: @bzzz-coding
Role: Developer
Slack Member ID: U04H6PYK14N

2023-04-09 18:15 UTC, jdingeman requested changes
Awesome job, Janice. Thank you for making those last minute changes.

2023-04-09 18:15 UTC, jdingeman commented on _projects/civic-tech-jobs.md
> +      slack: https://hackforla.slack.com/team/U045Q8PD1B5
Hi @janice87 - so sorry, Jen's Slack ID is actually U02A6H5PVAA. Could you please change it? Thanks!

2023-04-09 21:52 UTC, janice87 commented on _projects/civic-tech-jobs.md
> +      slack: https://hackforla.slack.com/team/U045Q8PD1B5
Hi @jdingeman, it is updated. Thank you!

2023-04-11 22:53 UTC, jdingeman approved these changes
Perfect, thank you @janice87!

2023-04-11 22:53 UTC, merged

2023-04-15 18:43 UTC, Aveline-art commented
Wanna jump in and say thank you all so much for getting this done! I really appreciate it.