Add new section on setting up SSH Keys in contributing.md
hackforla/website pull request #4435
Opened 2023-04-06 23:06 UTC by Jaretzbalba

Fixes #4350

### What changes did you make and why did you make them ?

  - Add new section 2.7f on how to setup SSH Keys on contributing.md
  - Update table of contents to link to the new section

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

Updating markdown file in website repository. No visual changes to the website.

2023-04-07 01:17 UTC, mjshelton12 commented
Review ETA: By end of day 4/8
Availability: Friday 9am-noon, Saturday all day

2023-04-07 01:18 UTC, arcan9 commented
Review ETA: EOD 04/07
Availability: after 5pm, M-F

2023-04-09 00:11 UTC, arcan9 requested changes
Hi @Jaretzbalba! I just have a few comments addressing some lines of the code. For context, I'm using [this comment](https://github.com/hackforla/website/issues/947#issuecomment-806257539) as reference for the setup instructions, and it looks like there are some discrepancies between what's written in the original comment and in your code. I'm not too familiar with SSH Keys as I've only done this once a long time ago, so feel free clarify some things by replying to my code review, so that I can properly approve your PR!

2023-04-09 00:11 UTC, arcan9 commented on CONTRIBUTING.md
> +eval "$(ssh-agent -s)"
I've looked at the setup instructions (here: https://github.com/hackforla/website/issues/947#issuecomment-806257539). And it looks like there are actually some steps in the Windows setup that differ slightly from the Mac setup. So, referencing the linked instructions, this line is supposed to be `` eval `ssh-agent -s` ``

2023-04-09 00:11 UTC, arcan9 commented on CONTRIBUTING.md
> +ssh-add ~/.ssh/id_ed25519
change to `ssh-add ~/.ssh/id_rsa`

2023-04-09 00:11 UTC, arcan9 commented on CONTRIBUTING.md
> +clip < ~/.ssh/id_ed25519.pub
change to `clip < ~/.ssh/id_rsa.pub`

2023-04-10 17:54 UTC, Jaretzbalba commented on CONTRIBUTING.md
> +clip < ~/.ssh/id_ed25519.pub
@arcan9 Yes, I researched into adding SSH Keys using the GitHub documentation and the instructions seemed to differ from what was referenced in the comment for this issue. I figured maybe the info was now outdated or wasn't written correctly so I followed what was currently in the documentation and tested it on my own machine as well. Hope this helps!

2023-04-10 20:52 UTC, arcan9 approved these changes

2023-04-10 20:53 UTC, arcan9 commented on CONTRIBUTING.md
> +clip < ~/.ssh/id_ed25519.pub
@Jaretzbalba Got it, thanks for clarifying! Approved.

2023-04-12 03:04 UTC, mademarc commented
Review ETA: 04/13
Availability: after 7:30pm

2023-04-13 03:14 UTC, merged