Added a new tech work experience project to the hack for la website
hackforla/website pull request #4474
Opened 2023-04-12 02:24 UTC by ftblmagician

Fixes #2288 

### What changes did you make and why did you make them ?
A new Tech Work Experience project.md card was added in the _projects folder The image and hero image files were also added to the /assets/images/projects folder. The new project makes the hack for la website project list current.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

[Tech-Work-Experience.pdf](https://github.com/hackforla/website/files/11206473/Tech-Work-Experience.pdf)

2023-04-12 02:31 UTC, chrismenke45 commented
Review ETA: 4/12 EOD
Availability: 4/12 8am-12pm

2023-04-12 03:04 UTC, mademarc commented
Review ETA: 04/13
Availability: after 7:45pm

2023-04-12 14:27 UTC, karengcecena commented
Review ETA: 04/12
Availability: 8:30 am

2023-04-12 14:51 UTC, karengcecena requested changes
Hi, [ftblmagician](https://github.com/ftblmagician). Thank you for taking the time to complete this issue. Your pull request is to and from the correct branches, you linked the issue correctly, and the website looks good on my local machine. I also see you uploaded the two images to the correct location. 

Furthermore, I see you added the project.md file, however in the links section, the links are for 100automation instead of the ones it asked for (i.e. GitHub: https://github.com/hackforla/internship, the wiki: https://github.com/hackforla/internship/wiki, and overview: https://github.com/hackforla/product-management/blob/master/project-one-sheets/Tech-Work-Experience-One-Sheet.pdf). Could you go back and make sure those are linked correctly? It may be a good idea to check the Slack link as well. 

Thanks again for working on this issue!

2023-04-14 01:02 UTC, mademarc reviewed
Hey @ftblmagician  the code looks in order with that said best to follow up with @karengcecena on her recommended suggestion to make this code work effectively also Good job as well.

2023-04-21 17:44 UTC, ftblmagician commented
Hello,

Thank you for the feedback! I made the changes... Please let me know if I need to change anything else

2023-04-22 00:16 UTC, chrismenke45 commented
Updated review ETA: 4/23 EOD

2023-04-24 02:18 UTC, chrismenke45 commented
My apologies, I will need to update my review ETA to tomorrow: 4/24 EOD

2023-04-24 16:54 UTC, karengcecena requested changes
Please check the inline comment I made after the links section of your tech-work-experience.md page for further clarification about the links I previously mentioned in the comment above. Thanks again for going back to edit/ check these.

2023-04-24 16:54 UTC, karengcecena commented on _projects/tech-work-experience.md
> +    url: 'https://100automations.org/'
Hi @ftblmagician. I'm still seeing 100automations website links in the links section of this project.md. Maybe your changes were not pushed to your pull request?

2023-04-26 02:29 UTC, ftblmagician commented
Hi Karen,

I believe the changes are made now... Please let me know if there's another issue!... Thank you

2023-04-26 02:33 UTC, chrismenke45 commented
Updated review ETA: 4/27 EOD

2023-04-26 20:41 UTC, chrismenke45 requested changes

2023-04-26 20:41 UTC, chrismenke45 commented on _projects/tech-work-experience.md
> +    url: 'https://github.com/hackforla/intership'
Great work @ftblmagician . Everything looks great but this link needs to be changed to 'https://github.com/hackforla/internship'. Missing the 'n' in internship.

2023-05-02 01:49 UTC, ftblmagician commented
Okay I corrected the error!... Is there anything else I need to correct?

2023-05-04 01:59 UTC, roslynwythe commented
@mademarc @karengcecena @chrismenke45 Thank you for your thoughtful comments on this PR.  If the PR meets with your approval, please use the Request Changes form (found on the "Files Changed" page) and Select "Approved".  Thanks!

2023-05-04 16:33 UTC, chrismenke45 commented
updated review ETA: 5/5 12pm

2023-05-04 22:19 UTC, karengcecena requested changes
Hi. Good job fixing up those links. However, I noticed you used this link for the overview: "assets/pdfs/Tech-Work-Experience-One-Sheet.pdf" instead of the one that said 
"(to copy from): https://github.com/hackforla/product-management/blob/master/project-one-sheets/Tech-Work-Experience-One-Sheet.pdf". 

Secondly, I'm not sure if there should be a site link? Do you know if this project already has a site, or if should be removed altogether. Currently, you are linking to the overview link, so I though these may be good questions to ask. 

Thank you!

2023-05-21 16:51 UTC, t-will-gillis commented
Hello @ftblmagician Would you please give us an update on this issue? Thanks!

2023-05-22 14:39 UTC, ftblmagician commented
Sorry I was a bit overwhelmed at work

Progress: The link for Overview needs to be changed and discussed whether its needed or not
Blockers: Discussing whether the Overview link is needed
Availability: 2 hours
ETA: 5/28
Pictures (optional): "Add any pictures of the visual changes made to the site so far.

2023-05-29 19:48 UTC, ftblmagician commented
Okay I update the overview link... thank you

2023-05-31 02:24 UTC, chrismenke45 commented
Updated ETA: 6/1 EOD
Availability: 8am-12pm weekdays

2023-05-31 15:22 UTC, chrismenke45 approved these changes
@ftblmagician Looks good! Thank you for making all the changes. All the links seem to work properly.

2023-06-01 21:03 UTC, blulady commented
@karengcecena @mademarc I'd like to merge this sooner rather than later, if you'd like to review it please put an eta on it.

2023-06-03 02:11 UTC, mademarc commented
Review ETA: 6/2/2023
Availability: 7:11PM

2023-06-03 02:14 UTC, mademarc approved these changes
Hey @ftblmagician good job on the change and yes @blulady  feel free to merge this anytime now

2023-06-07 13:27 UTC, chrismenke45 commented
@karengcecena Please comment your updated ETA and availability. Thank you.

2023-06-11 17:06 UTC, ExperimentsInHonesty requested changes

2023-06-11 17:06 UTC, ExperimentsInHonesty commented on _projects/tech-work-experience.md
> +  - name: Site
Please remove the site link and site link category.  In this case its just repeating the overview.  projects don't have to have a site link.

2023-06-13 01:20 UTC, ExperimentsInHonesty commented on _projects/tech-work-experience.md
> +  - name: Site
I just realized that this isn't the proper location for the pdf, but you would not have known that because it wasn't in the instructions that you should copy the pdf from its current location to the repository, like it is in other project.md files.

2023-06-27 00:13 UTC, closed without merging

2023-06-27 00:15 UTC, ExperimentsInHonesty commented
We are closing this pr for lack of responsiveness.  It was a time sensitive ticket, so it has to be done quickly.  The delay has lasted so long that the team info has actually changed.  The issue will be cleaned up and put back into the prioritized backlog