Add Styles and initiate images folder
hackforla/website pull request #45
Opened 2019-03-26 06:37 UTC by abregorivas

The pull request covers the following:
- Adds all base styles
- updates the config.yml file to use sass partials & imports
- Updates the head.html (_includes) to use the generated styles

2019-03-26 17:16 UTC, thekaveman requested changes
Remember we had to get rid of the `site/` folder in order for GitHub pages to build (it has to build directly from the root). So I think all your additions just need to shift up by one directory, into the root of the repository.

And then we don't need that modification in `_config.yml` or the `site/` folder.

2019-03-26 19:00 UTC, abregorivas commented
I made the following changes.
- Removed sass configuration in config.yml
- moved all files up to root

2019-03-27 02:29 UTC, thekaveman approved these changes

2019-03-27 02:30 UTC, thekaveman commented
This looks @abregorivas! I'm going to squash merge to get rid of those sync commits, but we'll still have the full history in this PR.

2019-03-27 02:33 UTC, merged