Created Donation Circle Component and Integrated with Donate Page
hackforla/website pull request #4573
Opened 2023-04-27 08:43 UTC by agosmou

Fixes #4263 

### What changes did you make and why did you make them ?

  - Created a new HTML file without the use of "images-of-text" to render donation circles components to meet WCAG.
  - Created a SCSS file for the donation component items without the use of images. The new circles are made using styling.
  - Created references to the new material at the instructed locations and ensured changes were responsive on mobile.
  - Note: The new iteration of this component required more words on the circles per instructions. 

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

![image-1](https://user-images.githubusercontent.com/73868258/234806834-60bf7ae9-d5da-4827-8398-e28df4d1e9a1.png)

</details>

<details>
<summary>Visuals after changes are applied</summary

![image-2](https://user-images.githubusercontent.com/73868258/234807247-3aba7112-01d2-4fa9-965e-ae4dfda0daa0.png)
![image-3](https://user-images.githubusercontent.com/73868258/234807251-4329a9db-9ee2-4c2a-99ef-315289f17897.png)

 

</details>

2023-04-27 15:47 UTC, LOSjr4 commented
Availability: M,T,TH 9AM-1PM
ETA: 4/27/23

2023-04-27 16:44 UTC, LOSjr4 approved these changes, later dismissed
I visibly saw the changes in Docker.
I inspected the new html file _includes/donation/donation-circles.html.
I saw in pages/donate.html, the <img> tag and it's contents were replaced with liquid tag {% include donation/donation-circles.html %}.
I saw _sass/components/_donate-components.scss was created and an import statement was added in _sass/main.scss.
I inspected the appearance of the new circles across several screen dimensions with Chrome.
Great work @agosmou, I enjoyed reviewing your issue.

2023-04-27 17:17 UTC, Thinking-Panda commented
Availability: 10 AM- 3-PM
ETA: 4/28/23

2023-04-28 17:44 UTC, Thinking-Panda requested changes
Hello @agosmou , The circles and text are very well created with css. 

The circles look aligned to the left in mobile viewport width 320 px

![leftAligned#4573](https://user-images.githubusercontent.com/122488603/235216984-af97cb24-2499-43c3-a677-94a8b34bbd7c.jpg)

Also, the code needs a little cleanup:
donate.html- indent line 19
_donate-components.scss- delete line 20

2023-04-28 18:21 UTC, agosmou commented
@Thinking-Panda 

Thanks for taking the time to review. 

We should be good now - the requested items are complete. Check my latest commit.

- [ ] donate.html- indent line 19
- [ ] _donate-components.scss- delete line 20
- [ ] "The circles look aligned to the left in mobile viewport width 320 px" 
Note: I made media queries for better mobile UX/UI - I think the left alignment is an optic - take a look at the containers. It does look a little better now, but if you feel there's more to be done, are you able to suggest how to make an adjustment? Thanks!

2023-04-28 18:27 UTC, agosmou commented
@merge-team

I had one successful review.
The second reviewer requested minor tweaks so I pushed a new commit. 

Then I saw this message:
> [agosmou](https://github.com/agosmou) dismissed [LOSjr4](https://github.com/LOSjr4)’s [stale review](https://github.com/hackforla/website/pull/4573#pullrequestreview-1404485724) via [799d84e](https://github.com/hackforla/website/commit/799d84ef1e6724434517556e5d898d38e9a1e4df) [13 minutes ago](https://github.com/hackforla/website/pull/4573#event-9127322838)

Must I request another review from him?

2023-04-28 19:19 UTC, Thinking-Panda commented
> @Merge-Team
> 
> I had one successful review. The second reviewer requested minor tweaks so I pushed a new commit.
> 
> Then I saw this message:
> 
> > [agosmou](https://github.com/agosmou) dismissed [LOSjr4](https://github.com/LOSjr4)’s [stale review](https://github.com/hackforla/website/pull/4573#pullrequestreview-1404485724) via [799d84e](https://github.com/hackforla/website/commit/799d84ef1e6724434517556e5d898d38e9a1e4df) [13 minutes ago](https://github.com/hackforla/website/pull/4573#event-9127322838)
> 
> Must I request another review from him?

@agosmou , after pushing commits with requested changes, you should request a second review by clicking on the two arrow circle next to the reviewer name. I did it for you this time.
![rereview](https://user-images.githubusercontent.com/122488603/235233917-ef48d65a-3633-41a6-8120-dbc728c6ab48.jpg)

2023-04-28 19:53 UTC, agosmou commented
@Thinking-Panda  Thanks!
@LOSjr4 , take a quick peak at the minor changes requested by @Thinking-Panda and re-confirm your review please - Thank you Luis :)

2023-04-28 20:22 UTC, Thinking-Panda reviewed
Hi @agosmou , Thankyou for adjusting the circle sizes for mobile viewport. 

Minor request: The lower circles look a little squished together. Can we have a gap (maybe 1em) in between the circles like you have a gap of 4em for larger viewports. 
This may be just my perspective. Please let me know your thoughts.

2023-04-28 21:45 UTC, agosmou commented
@Thinking-Panda  If you look at the code from the first and latest commit, there was a 1.8em gap but to make it look better on mobile for the first request, ie the alignment, it was better to remove it. (esp. for smaller screens like the 320px or galaxy fold screen)

I've re-added the gap, but as 1em. Checkout the differences below!

-1em-gap
![1em-gap](https://user-images.githubusercontent.com/73868258/235258970-36e97957-c1e0-47b8-87e4-83f94bf5b703.png)

-no-Gap
![no-gap](https://user-images.githubusercontent.com/73868258/235258979-a5c82e35-c95f-466e-8ddd-18ac45cb0f8a.png)

2023-04-29 05:32 UTC, Thinking-Panda commented
ETA: 4/29/23

2023-04-30 04:24 UTC, Thinking-Panda approved these changes
@agosmou , thank you for incorporating the changes. LGTM

2023-05-01 18:02 UTC, LOSjr4 approved these changes
Good eye @Thinking-Panda! I'll remember to pay more attention to the spacing on mobile in the future. Although most screen sizes looked ok, the spacing was most notable at the 320pixel width.
Good work implementing the fixes @agosmou. I reexamined your code and watched docker update the spacing.
I learned a few more things doing this review and I appreciate the experience.

2023-05-02 04:19 UTC, merged