Create donation gif component 4439
hackforla/website pull request #4650
Opened 2023-05-11 04:46 UTC by bphan002

Fixes #4439

### What changes did you make and why did you make them ?

  - I made the donate gif/text into a reusable component
  -  I did a small refactor of the html so that the header was outside of the original component and made it a sibling of the component
  - I transferred all the related scss from the _donate.scss into the _donate-component.scss

#### Implantation Before
<details>

Desktop
![Previous Desktop](https://github.com/hackforla/website/assets/83096266/976d14ef-8c4a-4fcf-adda-c2d75dc6d633)
Mobile
![Previous Mobile](https://github.com/hackforla/website/assets/83096266/e39b5d70-22c7-45f1-9523-5312efce7da5)
</details>

#### Implementation After
<details>

Desktop
![After Desktop](https://github.com/hackforla/website/assets/83096266/198a827f-0654-45ed-8a08-1f67b9307eb2)
Mobile
![After Mobile](https://github.com/hackforla/website/assets/83096266/87261c80-4c2f-4909-b3ff-005c0f44678d)
</details>

2023-05-11 18:04 UTC, roslynwythe commented
Availability: 5/11 2 - 4pm
ETA: EOD 5/12

2023-05-12 16:49 UTC, Thinking-Panda commented
Availability: 10AM-3PM
ETA: 5/12/23

2023-05-15 17:53 UTC, roslynwythe commented
Hi @bphan002  I apologize for the delay in reviewing.  I need to update my ETA:

Availability: 5/15 11 -2pm, 5/16 2 -5 pm
ETA: EOD 5/16

2023-05-15 19:19 UTC, roslynwythe requested changes
Hi @bphan002 I apologize that this was not mentioned explicitly but the intention is that the component include the sentence "Hack for LA takes donations through Code for America".  This was depicted in both the "component elements" screenshot and the "Final appearance" screenshots.  You could grab the html from this page: https://www.hackforla.org/about/ (3rd card from the bottom).

2023-05-15 19:19 UTC, roslynwythe commented on _includes/donate-card.html
> +  <h3 class="title6 donate-title">Make a donation to Hack for LA</h3>
Hi @bphan002 I apologize that this was not mentioned more explicitly but the intention is to change the h3 header text to "Make a Donation" as it is depicted in the "Final appearance" screenshot (under Resources).

2023-05-15 20:11 UTC, Thinking-Panda requested changes
Hi @bphan002 , 
As `<h3>` and `.donate-title` is moved outside the component, styling in line 78 and line 110 in `_donate-components.scss` could be moved to `_donate.scss`
![issue4439](https://github.com/hackforla/website/assets/122488603/4338d85c-0752-49c5-9a71-9153885bb2ec)

Also, the text inside the red circle is not included in the new version.

2023-05-15 23:51 UTC, bphan002 commented on _includes/donate-card.html
> +  <h3 class="title6 donate-title">Make a donation to Hack for LA</h3>
Hi @roslynwythe 
The html from https://www.hackforla.org/about/ (3rd card from the bottom) was done using flex, while the current one I was working on uses grid.  

Is it okay if I just make the whole component flex then?

2023-05-17 02:50 UTC, bphan002 commented
@Thinking-Panda Thank you for catching that. I'm not sure if you are able to chime in on this question I left for Roslyn.
The html from https://www.hackforla.org/about/ (3rd card from the bottom) was done using flex, while the current one I was working on uses grid.

Is it okay if I just make the whole component flex then?

2023-05-17 03:05 UTC, Thinking-Panda commented
> @Thinking-Panda Thank you for catching that. I'm not sure if you are able to chime in on this question I left for Roslyn. The html from https://www.hackforla.org/about/ (3rd card from the bottom) was done using flex, while the current one I was working on uses grid.
> 
> Is it okay if I just make the whole component flex then?



Changing it to flex will move the text "100% of donation..." on top of the donation gif in the mobile viewport
![PR4650](https://github.com/hackforla/website/assets/122488603/fade2029-dd6c-499f-9f6c-27545153ace9)
 And as per last action item in the issue, that text has to be underneath the donation gif.

2023-05-18 06:04 UTC, roslynwythe commented on _includes/donate-card.html
> +  <h3 class="title6 donate-title">Make a donation to Hack for LA</h3>
Hi @bphan002 If you feel it is necessary or desirable to change the layout to flex then that is fine but please explain your reasoning.  Honestly I didn't think that the requested changes would cause significant impact but perhaps I am missing something.  Thanks again for your work on this issue.

2023-05-19 00:22 UTC, Thinking-Panda commented
ETA- 5/19/23

2023-05-19 17:38 UTC, Thinking-Panda requested changes
@bphan002 , a couple of things that I noticed.
1. The `<h3>` in `donate-card.html` should be "Make a Donation"
2. `_donate.scss` could have a clean up of lines 11-14

2023-05-19 17:46 UTC, bphan002 commented
@Thinking-Panda  & @roslynwythe  thank you so much for your feedback.  I have just made the changes requested.

2023-05-19 21:49 UTC, Thinking-Panda submitted a review, later dismissed
@bphan002 , Thank you for incorporating the changes requested. Code changes are applicable and clean. Website works well on my local machine.

2023-05-19 21:50 UTC, Thinking-Panda commented
@bphan002 - Looks like there is a merge conflict. To learn about resolving merge conflict please use this link
https://github.com/hackforla/website/wiki/How-to-Resolve-Merge-Conflicts

2023-05-20 05:39 UTC, bphan002 commented
Sorry for all the issues.  I believe the merge conflict has been resolved and the requested changes have been made.

2023-05-22 16:33 UTC, Thinking-Panda commented
Thank you @bphan002 for resolving the merge conflict. 

Review ETA: EOD 5/22/23

2023-05-23 04:33 UTC, Thinking-Panda commented
Extending my ETA to 5/23

2023-05-24 03:34 UTC, Thinking-Panda requested changes
@bphan002 , changes to  `_projects/access-the-data.md` are not mentioned in this issue. Rest look good.

2023-05-24 03:41 UTC, bphan002 commented
> @bphan002 , changes to `_projects/access-the-data.md` are not mentioned in this issue. Rest look good.

Thank you so much for your patience. I have corrected this.

2023-05-24 03:43 UTC, Thinking-Panda approved these changes, later dismissed
Well done @bphan002 . Thank you for your work!

2023-05-24 04:08 UTC, bphan002 commented on _includes/donate-card.html
> +  <h3 class="title6 donate-title">Make a donation to Hack for LA</h3>
I believe it is good now

2023-05-24 23:23 UTC, roslynwythe requested changes
Hi @bphan002 great work so far on this issue.  Please adjust the styles to match the "final appearance" screenshots a bit more closely.   

For desktop screen sizes, please align the sentence "Hack for LA takes donations.." with the top of the form box, and allow more whitespace between each line of text, and italicise the sentence "100% proceeds go to ..".  Also the size of that italicized text should be reduced. Make sure there is enough spacing so the text doesn't get too close around 780 px.  

In mobile, again please add some spacing between the lines of text, and the text "*100% of proceeds" should be left-aligned.

2023-05-25 03:57 UTC, bphan002 commented
> Hi @bphan002 great work so far on this issue. Please adjust the styles to match the "final appearance" screenshots a bit more closely.
> 
> For desktop screen sizes, please align the sentence "Hack for LA takes donations.." with the top of the form box, and allow more whitespace between each line of text, and italicise the sentence "100% proceeds go to ..". Also the size of that italicized text should be reduced. Make sure there is enough spacing so the text doesn't get too close around 780 px.
> 
> In mobile, again please add some spacing between the lines of text, and the text "*100% of proceeds" should be left-aligned.

Hi @roslynwythe I tried the text-align:left , but it had no effect so I put a - margin. Hope that is okay.

2023-05-28 20:09 UTC, roslynwythe commented
Hi @bphan002 thank you for making the requested changes.  They look really good.  Please update the "Implementation After" screenshot to reflect the latest appearance of the PR.

2023-05-30 18:48 UTC, bphan002 commented
> Hi @bphan002 thank you for making the requested changes. They look really good. Please update the "Implementation After" screenshot to reflect the latest appearance of the PR.

Hi Roslyn,  

I just updated the "Implementation After" desktop and mobile screenshots. Thanks

2023-05-30 22:35 UTC, Thinking-Panda requested changes
@bphan002 , Thank you for your patience! The italics for "100% of ..." is applied only when viewport is min-width: 768px and smaller viewports have a regular font. Applying the italics style to all viewports would achieve our goal.

2023-05-31 00:15 UTC, bphan002 commented
> @bphan002 , Thank you for your patience! The italics for "100% of ..." is applied only when viewport is min-width: 768px and smaller viewports have a regular font. Applying the italics style to all viewports would achieve our goal.

All set

2023-05-31 03:35 UTC, Thinking-Panda commented
ETA: 5/31/23

2023-05-31 17:47 UTC, Thinking-Panda approved these changes
Excellent work. Thak you @bphan002 ! Approved.

2023-06-01 06:46 UTC, roslynwythe commented
Thank you so much @bphan002 for making those changes.  Please update the "Implementation After" desktop view.

2023-06-01 06:47 UTC, roslynwythe requested changes
Thank you so much @bphan002 for making those changes. Please update the "Implementation After" desktop view.

2023-06-02 06:36 UTC, bphan002 commented
> Thank you so much @bphan002 for making those changes. Please update the "Implementation After" desktop view.

Apologies for missing this and thank you again for your patience.  I just updated the desktop view.

2023-06-08 09:06 UTC, roslynwythe approved these changes
Thank you @bphan002 for great work on this issue.  The code changes are correct and clean, and work perfectly in the browser, the PR is well-formed and you decribed your work, and you were responsive to requests for changes.

2023-06-08 09:06 UTC, merged