Updated Label in External Resource Markdown File
hackforla/website pull request #4674
Opened 2023-05-15 18:12 UTC by ldietz08

Fixes #4476

### What changes did you make and why did you make them ?

  - I updated the label in suggest-an-external-resource.md by adding 'Complexity:Missing' to indicate that a label of a certain series is missing from an issue. 
  - This prevents the GitHub bot from taking off the labels when devs add them to issues.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

Updating suggest external resource markdown file. No visual changes to the website.

2023-05-15 18:21 UTC, ldietz08 commented
Availability for this week: M-F 4pm-8pm PST

2023-05-16 13:27 UTC, 93Belen commented
Availability: Tuesday, Thursday and Sunday from 7am to 5pm

2023-05-16 13:34 UTC, 93Belen submitted a review, later dismissed
The PR is done from the correct branch.
You linked the issue.
As you explain, there is no visual changes in the website
You explain your changes and why you did them
Good job!

2023-05-16 19:16 UTC, t-will-gillis requested changes
Hi @ldietz08  - super job on your issue! You are using the correct branches, you linked the issue, you gave a great, concise description by saying what you did and why (and commenting out the visuals), and you followed the issue and made the code changes as requested.

You did what you were instructed to do- thanks!- but inadvertently the code we said to use has some typos. Instead would you please replace the code on Line 5 with the following-

`labels: ['P-Feature: Toolkit', 'role: front end', 'size: 0.5pt', 'Complexity: Missing']`

As @roslynwythe indicated, this will need to be tested before merging and we will give you instructions and show you how to do so. 

Again, super job, apologies for our typo, and thank you for your work!

2023-05-17 01:32 UTC, t-will-gillis approved these changes
@ldietz08 looks great thanks for picking this up! I am able to test the change on my end. 

Next step is for you to test this also: @roslynwythe linked the instructions [here](https://github.com/hackforla/website/issues/4307#issuecomment-1549888931) You can send us a message on Slack if you run into any problems.

2023-05-17 02:22 UTC, 93Belen commented
Availability: Thursday and Sunday from 7am to 5pm
ETA: Thursday by 5pm

2023-05-17 17:57 UTC, roslynwythe approved these changes
Hi @ldietz08 your PR looks good.  You setup the branches correctly and described your work,  and the issue template you created worked successfully in a test GitHub repository.  Thank you and congratulations completing your first good issue.

2023-05-17 17:58 UTC, merged