Remove blank roles from Wins filter options
hackforla/website pull request #4701
Opened 2023-05-19 18:48 UTC by pdimaano

Fixes #4592

### What changes did you make and why did you make them ?

  - Added conditional statement to remove blank checkbox option from dropdown menu
  - Fixed spelling error with name of dropdown variable
  - Removed unnecessary spaces for formatting

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

<img width="313" alt="Screen Shot 2023-05-19 at 11 42 18 AM" src="https://github.com/hackforla/website/assets/80801555/fde5f18d-c3a0-4506-8f6c-0d93f6424094">

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
<img width="309" alt="Screen Shot 2023-05-19 at 11 44 24 AM" src="https://github.com/hackforla/website/assets/80801555/1dc4921e-1e77-4d72-8054-d5eb206bf6ed">

</details>

2023-05-20 01:34 UTC, Sebster3 commented
Availability: 5/19-5/20
ETA: 5/19

2023-05-20 01:42 UTC, Sebster3 reviewed
Hey @pdimaano, great job working on this PR!

The basics all look good: The branches are correct, the site renders successfully in my local environment, and the changes you've made correctly prevent blank roles from appearing in the filter dropdown.

I've left some thoughts below that I'd like to get your opinion on. let me know what you think, cheers!

2023-05-20 01:47 UTC, Sebster3 commented on assets/js/wins.js
> +			}
This loop appears to be building a filter entry bit by bit, then appending the new entry to the filter dropdown at the end of the loop.

The current placement of the conditional statement implies that the preceding lines in the loop should run regardless of `key`s state, however the work done in the preceding lines is discarded if `key` is empty.

As a suggestion, the conditional statement could be moved to the top of the for loop and simplified to:

```js
if ( /* key is an empty string*/ ) {
    continue
}
```

Doing so would make it clear that the body of the loop should **not** run if the key is empty and makes the code easier to read (less nesting).

2023-05-20 18:04 UTC, pdimaano commented on assets/js/wins.js
> +			}
@Sebster3 Thank you for the recommendation. I changed the location of the conditional statement for clarity and it looks like the dropdown menu is still being generated correctly.

2023-05-20 19:50 UTC, Sebster3 commented on assets/js/wins.js
> +			}
Thanks for considering it @pdimaano, and I'm glad it seemed like a worthwhile change!

One last suggestion, the `else` block surrounding the lines handling `cloneFilterTemplate` could be dropped since those lines would only run when `key` is not an empty string, thus making the `else` redundant.

```js
for(const [key,value] of Object.entries(roleHash) ){
	if (key === '') {
		continue
	}
	
	let cloneFilterTemplate = filterTemplate.content.firstElementChild.cloneNode(true);
	cloneFilterTemplate.querySelector("input").value = `role_${key}`;
	cloneFilterTemplate.querySelector("input").id = `role_${key.replace(/\s+/g, '')}`;
	cloneFilterTemplate.querySelector("input").name = `role_${key.replace(/\s+/g, '')}`;
	cloneFilterTemplate.querySelector("input").addEventListener("click",checkboxClickHandler);
	cloneFilterTemplate.querySelector("label").textContent = `${key}`;
	cloneFilterTemplate.querySelector("label").htmlFor =`role_${key.replace(/\s+/g, '')}`;
	roleDropDown.append(cloneFilterTemplate);
}
```

2023-05-21 16:28 UTC, mjshelton12 commented
Availability: Sunday 1pm-5pm, Mon-Fri 9am-1pm
ETA: 5/21 end of day

2023-05-21 16:47 UTC, roslynwythe commented
Availability 5/21 9 - 11 pm 
ETA 5/22 EOD

2023-05-21 17:05 UTC, Sebster3 approved these changes, later dismissed
Everything still looks good following the recent changes. The site builds & renders correctly and the action item in the issue was addressed. Approved!

2023-05-24 19:48 UTC, mjshelton12 approved these changes, later dismissed
First off, great work on the basics. Your branches are correct, you linked to an issue, you provided a thorough explanation of what you did/why you did it, and included appropriate visuals. Your code is clean and effective, plus it shows perfectly in chrome desktop, tablet, and phone as well as safari desktop. Excellent work!

You did a great job finding the cleanest and most effective way to write this code block - I can see by your adjustments in pushes. I liked seeing how you came to the code you ultimately want merged, it helped me see your process. Very nice work and thank you for fixing that blank checkmark!

2023-05-24 22:42 UTC, roslynwythe requested changes
Excellent work @pdimaano - your branches are setup correctly and your PR is well-formed and descriptive and it checks out fine in the browser.  My only request is to change the indenting of the code so that it is consistent with the other indenting on the page.  Inconsistent indenting can cause confusion, if for example the next developer to work on this has an automated prettifier which modifies the lines of code that you changed.

2023-05-29 22:54 UTC, roslynwythe commented on assets/js/wins.js
> +			if (key === '') {
Hi @pdimaano your code does work perfectly but for the sake of other developers we do want to indent code consistently.  Line 108 should be indented one tab to the right of line 107.  Lines 111-118 and lines 121-128 should be at that same indent level as line 108.  Thank you.

2023-05-30 20:10 UTC, pdimaano commented on assets/js/wins.js
> +			if (key === '') {
@roslynwythe I made the code formatting changes according to your prior comment and it looks fine in my code editor. However, when I view the code in GitHub there seem to be some slight differences with the appearance and indentation. I also ran the updated code on my local system which still works to fix the issue. Are these changes still alright?

2023-06-21 03:42 UTC, ronaldpaek commented
@pdimaano I think I found the issue, my vscode also was causing issues with every file I was modifying inserting a /n

2023-06-21 03:44 UTC, ronaldpaek commented
@pdimaano I actually never used eslint as a formatter, but the way hack4la has it set up the only workspace rules defined is with .stylelintrc.json which I think a linter and so if you apply that it will follow the rules, but I also have it not apply any prettier formatting if there is no configuration files

<img width="309" alt="Screenshot 2023-06-20 at 8 39 32 PM" src="https://github.com/hackforla/website/assets/95109313/4276e84c-85db-44f0-8fe0-31ae82fe9ee2">
pdimaano

2023-06-21 07:53 UTC, ronaldpaek commented
@pdimaano 
https://marketplace.visualstudio.com/items?itemName=tombonnike.vscode-status-bar-format-toggle
https://www.robinwieruch.de/how-to-use-prettier-vscode/

2023-06-23 17:27 UTC, pdimaano commented
@roslynwythe I disabled the ESLint and Prettier extensions in my VS Code editor but apparently I cannot push another commit since no actual code in the JavaScript file was changed. I checked that the code still works in Docker. Is there a way around this and would it fix the issues with indentation and formatting?

2023-06-28 02:15 UTC, blulady commented
> @roslynwythe I disabled the ESLint and Prettier extensions in my VS Code editor but apparently I cannot push another commit since no actual code in the JavaScript file was changed. I checked that the code still works in Docker. Is there a way around this and would it fix the issues with indentation and formatting?

So the easiest thing to do would be to create slight change commit it & push it & then change it back & push it. There is probably a better way.

2023-06-29 02:31 UTC, pdimaano commented
@blulady @roslynwythe I disabled the ESLint and Prettier extensions and made the commits as suggested previously. I made sure to check that line 108 is one tab to the right of line 107 and lines 111-118 and 121-128 are at the same indent level as line 108. I ran the application in Docker to make sure the code still works as intended. Does this fix the issues with indentation and formatting?

2023-07-06 06:33 UTC, roslynwythe commented
Hi @pdimaano please browse to the "Files Changed" page then click on "View File"
![image](https://github.com/hackforla/website/assets/5314153/074d0be0-be70-4d6d-b199-664aa7f6e913)
then see lines 107-128.  
![image](https://github.com/hackforla/website/assets/5314153/037bc4a6-ad53-4ffd-befc-3c525aebcd0c)

Is this what you see in your IDE?

2023-07-06 18:59 UTC, pdimaano commented
@roslynwythe This is how the code appears in my VSCode editor (I made sure to check ESLint and Prettier extensions were disabled):
<img width="1051" alt="Screen Shot 2023-07-06 at 11 54 01 AM" src="https://github.com/hackforla/website/assets/80801555/13d10861-a080-47d8-8820-007af1f28568">

2023-07-09 23:32 UTC, pdimaano commented
@roslynwythe I made some commits after comparing the formatting differences with the code in VSCode, TextEdit and GitHub. It looks like the JavaScript file as it appears in GitHub now follows the formatting specifications that we discussed previously. I believe the appropriate lines are now indented and formatted correctly. I also ran it Docker as well to make sure it still works as intended. Please let me know if this is correct.

2023-07-12 02:32 UTC, roslynwythe approved these changes
Thank you @pdimaano for your hard work on this issue.  The code change is correct, clean and well-formatted, the PR is well-formed and descriptive, and the code checks out in the browser.  I appreciate the extra effort to get the clean indenting; that helps make the code easier for new developers to understand.

2023-07-12 02:32 UTC, roslynwythe commented on assets/js/wins.js
> +			if (key === '') {
Hi @pdimaano are you using a linter or prettifier like pretty print that might be messing up the indenting?

2023-07-12 02:34 UTC, blulady commented
@Sebster3 & @mjshelton12 hey, when you guys get a chance please put down etas to re-review this pr?

2023-07-13 22:29 UTC, Sebster3 commented
ETA: 07/15

2023-07-16 05:24 UTC, Sebster3 approved these changes
Good work on the revisions for this PR @pdimaano. The formatting appears correct both locally and on GitHub, the site builds successfully, and the issue is addressed correctly. The extra time spent on formatting is noticed and appreciated, thank you!

2023-07-16 05:26 UTC, Sebster3 commented on assets/js/wins.js
> +			if (key === '') {
Marking as implicitly resolved following @roslynwythe's approval of overall changes.

2023-07-18 06:20 UTC, merged