Edit System Audit Text #4482
hackforla/website pull request #4750
Opened 2023-05-29 02:02 UTC by DakuwoN

Fixes #4482 

### What changes did you make and why did you make them ?

  - Added labels with [] (brackets) in the markdown file 
  - These brackets add the labels from the Missing series
  - Prevents the GitHub bot from taking the labels off when developers add new issues.

2023-05-29 02:18 UTC, Mayank2808sharma approved these changes
LGTM

2023-05-29 02:20 UTC, DakuwoN commented
Thank you @Mayank2808sharma I am not sure how to test it, but I did run those commands in git... lol

2023-05-31 18:44 UTC, EdASalazar approved these changes
LGTM

2023-06-01 02:49 UTC, roslynwythe requested changes
Hi @DakuwoN Thank you for taking on this issue.  This Pull Request looks good.  The branches are setup correctly and the code change appears to be correct and clean.  However to confirm the updated template is correct, I need the URL of the template in your test repository.    Please edit Issue #4482, under "Link for Reviewer", replacing the text [REPLACE THIS TEXT AND BRACKETS WITH THE URL] with that URL.  Then complete the test procedure outlined in this comment, by copying the listed sections from the Issue, into this PR, under the "What changes did you make..." section.  Please send me a Slack message if you have any questions.

2023-06-13 22:03 UTC, DakuwoN commented
> Hi @DakuwoN Thank you for taking on this issue. This Pull Request looks good. The branches are setup correctly and the code change appears to be correct and clean. However to confirm the updated template is correct, I need the URL of the template in your test repository. Please edit Issue #4482, under "Link for Reviewer", replacing the text [REPLACE THIS TEXT AND BRACKETS WITH THE URL] with that URL. Then complete the test procedure outlined in this comment, by copying the listed sections from the Issue, into this PR, under the "What changes did you make..." section. Please send me a Slack message if you have any questions.
> 
> One other minor request: please provide a more descriptive name for the PR. The key point is that you have modified the labels on the "Design System Audit" template. Thanks

I explained the changes I made and why in the first comment above? Is this supposed to go elsewhere?

2023-06-13 23:33 UTC, roslynwythe requested changes
Hi @DakuwoN thank you for providing the URL.  I looked and it looks fine.  I just have two tiny requests:
Please update the name of the PR just to indicate that you updated labels on the "Edit System Audit: Text" template.  
Please see the last Action Item in this comment.  It is asking you to copy a few sections of text from the issue into the PR.  After doing that please check off those last check boxes.

2023-06-18 02:30 UTC, DakuwoN commented
For PR Reviewers and Merge Team
To review this issue, click the link below under "Link for reviewers" and verify that the labels match the updated labels string in the issue.

Link for Reviewers
This URL will be inserted by the dev during the test process and will be used by reviewers to preview the updated template.
URL of the issue branch on the test Repository: https://github.com/hackforla/website/issues/4482
For PM, Merge Team, or Tech Lead

 Once the pull request associated with this issue is approved and merged, please update and edit epic https://github.com/hackforla/website/issues/4307 by
 Checking off the dependency for this issue
 If all dependencies are checked off, please move issue to the New Issue Approval column and remove the Dependency label

2023-06-18 04:55 UTC, roslynwythe approved these changes
Hi @DakuwoN Thank you for making all of the requested changes.  Due to the need to test the updated template, this was more involved than most of our good first issues and we really appreciate your attention and effort to complete all the details.

2023-06-18 04:55 UTC, merged