Add bottom margin to arrow element to fix alignment of paragraph
hackforla/website pull request #4759
Opened 2023-05-31 04:21 UTC by thedvo

Fixes #4552 

### What changes did you make and why did you make them ?

  - added a bottom margin to the arrow w/ id `#head-content::before` which solved the issue where the paragraph text appeared under the arrow when the dimensions of the window changed

### Screenshots of Proposed Changes Of The Website  

<details>
<summary>Visuals before changes are applied - GIF </summary>

![before_changes](https://github.com/hackforla/website/assets/92699502/a6632520-becd-46b7-9e16-502961c1d54e)

</details>

<details>
<summary>Visuals after changes are applied - GIF </summary>

![after_changes](https://github.com/hackforla/website/assets/92699502/5ba0e4fe-4226-4b25-9cbf-7715132960d5)

</details>

2023-05-31 22:11 UTC, 93Belen commented
Availability: Thursday, Sunday and Monday all day
ETA: Thursday by 6pm

2023-06-01 02:34 UTC, roslynwythe commented
Availability: 6/1 2 hrs. 6/2 1 hr
ETA: 6/3

2023-06-01 13:57 UTC, 93Belen submitted a review, later dismissed
Nicely done!
You did the PR from the correct branch. Linked the Issues and provided a descriptive description of your changes.
I tested the code in my browser and it works exactly as you show in the description's visuals.
Good job!

2023-06-04 20:13 UTC, roslynwythe requested changes
Hi @thedvo the original problem does appear for a very small range of screen sizes, so perhaps we should change the bottom margin to 65 px.  
![image](https://github.com/hackforla/website/assets/5314153/210a83fe-7acc-4535-9cd8-b99c0e59194b)

2023-06-05 19:32 UTC, thedvo commented
> [Project Board](/hackforla/website/projects/7) automation moved this from **test-approved-by-reviewer (Automated Column, do not place items here manually)** to **test-pending-approval (Automated Column, do not place items here manually)** [Jun 4, 2023](#event-9425733626)
> [ ](/thedvo)

Hi @roslynwythe I made the update to 65px for the bottom margin. Currently after testing different breakpoints on Chrome and Safari I haven't noticed any issues. Let me know if you're still encountering the same issues, thanks!

2023-06-08 08:34 UTC, roslynwythe approved these changes
Hi @thedvo thank you for making the requested change and for overall great work on this issue.  Your code change is clean and correct and works well in the browser at all screen sizes, the PR branches are setup correctly and you are described your work, complete with screenshots depicting the visual changes.

2023-06-08 08:35 UTC, merged