Toolkit dropdown menu 3985
hackforla/website pull request #4764
Opened 2023-06-01 02:25 UTC by kwangric

Fixes #3985

### What changes did you make and why did you make them ?

  - **Main Change:** Added a dropdown menu to toolkit page to allow users to filter guide cards based on different parameters. This includes adding the dropdown menu into the toolkit HTML `current-guides.html` and adding the filter functionality to the JS page `toolkit.js`. The filters should function correctly on desktop and mobile.
  - Refactored how the toolkit HTML was set up in order to be consistent with the Projects page (see `toolkit.html` & `current-guides.html`.
  - Changed `guide-card.html` to include all the properties from the guide-pages (status, practice areas, etc.) to allow the filter to function.
  - Changed the CSS in `_sass/components/_toolkit.scss` to match the Figma design and to be consistent with the current Projects page.
  - Even though the current guide cards in the repo do not contain Resource Type and Technologies properties as shown in the Figma filters, they will work with the new filters when added in the future (see [comments](https://github.com/hackforla/website/issues/3985#issuecomment-1555359253) in issue).

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

![image](https://github.com/hackforla/website/assets/43795498/675034e8-0559-48e1-a737-1f30f7944056)

![image](https://github.com/hackforla/website/assets/43795498/1b01a296-1530-47ed-a83d-083820929a9e)

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
![image](https://github.com/hackforla/website/assets/43795498/c8d9bb43-7025-434d-a76d-ed77e624b116)

![image](https://github.com/hackforla/website/assets/43795498/2337f136-e3d3-435d-84dd-aaf8e77f70dc)

</details>

2023-06-01 04:17 UTC, kwangric commented
While browsing the project board I noticed issue [#4753](https://github.com/hackforla/website/issues/4753), which noted that the placement of the red filter tags on the Projects page was unintentionally changed with a recent pull request and is currently being reverted. I had thought that the change was intentional when I was working on the issue, but I've moved the tags back to the original location with my latest commit.

2023-06-04 18:32 UTC, chrismenke45 commented
Review ETA: 6/6 EOD
Availability: 8am-1pm Monday

2023-06-05 23:32 UTC, chrismenke45 commented
@kwangric It looks really good. I think everything works as intended, but would it be possible for you to pull the most recent gh-pages into this branch. The issue in #4753 has been fixed and I just want to make sure that the fix won't affect your filters and your code won't affect those filters since they all use the same classes.

2023-06-05 23:56 UTC, kwangric commented
@chrismenke45, branch has been merged with the latest version of gh-pages.

2023-06-06 04:22 UTC, Adastros commented
Availability (PST): 10 - 11 PM 05JUN2023 - 07JUN2023
Review ETA (PST): End of day 07JUN2023

2023-06-06 15:03 UTC, chrismenke45 submitted a review, later dismissed
@kwangric All the changes look good! The functionality is great and I don't see any effects on other pages.

2023-06-08 06:25 UTC, Adastros requested changes
Hi @kwangric, good job on completing the issue! 

- The filters work as expected, including the "Resource Type"  and " Technologies" filters
- The correct guide pages appear when selecting the filters
- The filter component behaves as expected when transitioning between mobile and desktop views
- The other components on the toolkit page are unaffected
- The other filters on the project, wins, and home pages do not seem to be affected by the change
- Works on both Firefox and Chrome

The only things I would request to be changed right now are as follows:

- [x] very minor but could you remove the issue # from the title of the pull request? This is to avoid any confusion on what # is associated with the pull request
- [x] I noticed that text in the filter tags can overflow the parent container. Can you update the styling for this to match how the filter on the projects page handles overflow for the filter tags? 

    <details>

    ![image](https://github.com/hackforla/website/assets/48114590/64e37730-0250-4c51-b724-628fb4b68fdb)

    </details>

2023-06-08 07:03 UTC, Adastros commented
I also had thoughts regarding the code in `toolkit.js`. Looking through it, the code deviates from `current-projects.js` a bit (differently named functions, different methods of sorting arrays, etc.). There's nothing wrong with that and I don't want to undo all the work @kwangric did; I'm not sure how strictly we want `toolkit.js` to align with the code in `current-projects.js` or (possibly) the other filters on the site. This could complicate things down the line if we have to change something on the filters since we'll need to take a look at differently coded filters with similar functionality. 

Any thoughts @chrismenke45 and @kwangric?

2023-06-08 07:06 UTC, Adastros commented
I noticed a few other things with the filters in general while reviewing this pull request but it doesn't affect the approval status of this pull request. I'll update this comment tomorrow for documentation purposes.

2023-06-08 21:45 UTC, kwangric commented
@Adastros I should have the changes you requested done by tomorrow. 

As for the difference between `current-project.js`, since the projects and guide pages are set up differently in the repository, I had to pull the information from the files in a different way. From there, I tried to reuse some of the same code from `current-projects.js` but set it up in a way that was intuitive to me.

2023-06-10 05:36 UTC, kwangric commented
@Adastros I made the changes that you requested. 

One thing I noticed about the project page is that the project filter tags also have the same overflow issue, but it's just hard to see since the background is also white.

2023-06-14 06:28 UTC, Adastros commented
> @Adastros I made the changes that you requested.
> 
> One thing I noticed about the project page is that the project filter tags also have the same overflow issue, but it's just hard to see since the background is also white.

Thanks for making the changes! Good job on catching that! I'm okay with the changes since it only affects the "Professional Development" and contributor Ahdithan Uthayakumar Tarang Gupta tags. I think they can be shortened if we want to make them fit. The overflow issue on the projects page will be addressed in issue #4784. 

Before I approve this pull request, could you comment in ER issue #4769 on how the "no results" feature works? You can write about the relevant functions you added, how they work together, and what changes should/can be made to make the code reusable for the toolkit and projects page filters. It would be good to reference this [guide](https://github.com/hackforla/website/issues/3744) from the projects page filter to explain how a dev would try to refactor your code to make it work on the projects filter page too.

<details>
<summary>Toolkit Page Filter - No Results</summary>

![image](https://github.com/hackforla/website/assets/48114590/0600e866-6839-434e-999a-b877db7fd4be)

</details>

2023-06-14 22:54 UTC, kwangric commented
@Adastros I just left a comment on the ER issue with how the feature works and some steps on how it could be implemented on another page. Please let me know if anything else is needed.

2023-06-16 05:47 UTC, Adastros approved these changes
Thanks for being patient and accommodating @kwangric. The note on ER issue #4769 describes covers the "no result" feature well.

2023-06-16 05:47 UTC, Adastros commented on assets/js/toolkit.js
> +}
I noticed that this feature of the filter component was added. Looking at `current-projects.js` and the [guide ](https://github.com/hackforla/website/issues/3744)@chrismenke45 drafted, it doesn't seem like it wasn't originally part of the filter component code. I think it's a great and much needed addition but it does make me me wonder if we can include it within the scope of the issue. 

Looking at the filter on the projects page, the messages don't appear when none of the projects fit the selected filters.

Thoughts @chrismenke45?

<details>
<summary>Toolkit Page</summary>

![image](https://github.com/hackforla/website/assets/48114590/e9dc2cfa-7568-4c31-a7a4-4e017c3e7c52)

</details>

<details>
<summary>Projects Page</summary>

![image](https://github.com/hackforla/website/assets/48114590/0de8f7c8-c5d6-40d3-88a7-58a4128f114c)

</details>

2023-06-16 05:47 UTC, Adastros commented on assets/js/toolkit.js
> +}
Looks like an ER was created to address this for the projects filter. See #4769. This feature might need to be removed for this pull request and addressed in the issue that will be created for ER #4769. 

Please hold on doing anything for this portion of the code.

2023-06-16 05:47 UTC, Adastros commented on assets/js/toolkit.js
> +}
See [comment](https://github.com/hackforla/website/issues/4769#issuecomment-1588758037) and [this comment](https://github.com/hackforla/website/pull/4764#issuecomment-1590553134) for resolution.

2023-06-18 03:27 UTC, chrismenke45 commented
My apologies. I hadn't realized I'd be rerequested to review this while I was out of town.
ETA: 6/18 EOD

2023-06-18 21:58 UTC, chrismenke45 approved these changes
Looks good @kwangric ! @Adastros you brought up a lot of good points in your review. Its good to see any lingering problems with the filters will be addressed with those ERs. Sorry for my lack of responses during the review process. I was out of town and when I got back and didn't notice.

2023-06-20 05:02 UTC, merged