Create Footer & hook to Default.html
hackforla/website pull request #48
Opened 2019-03-27 20:43 UTC by abregorivas

2019-03-28 16:52 UTC, thekaveman commented
@abregorivas it looks like this PR contains both the header and footer... which is totally fine. I'll just close your other one #40 and we'll use this one, sound good?

2019-03-28 19:52 UTC, abregorivas commented
Yes Sounds good.

2019-03-30 18:39 UTC, thekaveman requested changes

2019-03-30 18:39 UTC, thekaveman commented on _data/navigation/main.yml
> +  icon_class:
it looks like each `icon_class` is part of the `.svg` files - any reason to duplicate here? Or any way to pull out of the `.svg` files and generate dynamically from this data?

There's a lot of duplication - `icon nav-icon icon-hack-nights icon-projecets` is on almost every one, some multiple times.

2019-03-30 18:39 UTC, thekaveman commented on _data/navigation/social.yml
> +  icon_url: /svg/icon-twitter
I think we should use the full `icon_url` for these - the template shouldn't have to know it needs to add the `.svg` extension to render these.

2019-03-30 18:39 UTC, thekaveman commented on _includes/footer.html
> +              }}{{ item.icon_url }}.svg -%} {% endif %}
```html
{%- include {{ site.baseurl
}}{{ item.icon_url }}.svg -%}
```

I've seen this pattern a few times - any particular reason for the usage of `{%-` ... `-%}` instead of the usual `{%` ... `%}` ? Any reason for that line break?

2019-03-30 18:44 UTC, thekaveman requested changes

2019-03-30 18:44 UTC, thekaveman commented on _data/navigation/main.yml
> +  link: contact
Each of these `link` should include the `#` symbol at the beginning for now: since we're still in single-page-website mode for now, they are jump links vs. page links.

2019-03-30 18:48 UTC, abregorivas commented on _includes/footer.html
> +              }}{{ item.icon_url }}.svg -%} {% endif %}
my understanding is that the "-" cleans up empty spaces

2019-04-02 05:44 UTC, thekaveman commented on _includes/footer.html
> +          {% for item in site.data.navigation.social %} {% if item.footer %}
You could also do something like:

```
{% assign nav = site.data.navigation.social | where: "footer" %}
{% for item in nav %}
```

So using an `assign` and the `where` filter instead of an `if` block... just an option

2019-04-02 06:12 UTC, thekaveman commented
@abregorivas would you mind rebasing on the latest `gh-pages` again?

2019-04-12 20:51 UTC, abregorivas commented
changes made and rebase

2019-04-23 02:36 UTC, thekaveman approved these changes

2019-04-23 02:42 UTC, thekaveman commented
Rebased one last time to deal with conflicts.

2019-04-23 02:42 UTC, merged