Add frameworks #460
hackforla/website pull request #480
Opened 2020-05-01 19:27 UTC by ruben1s

Fixes #460

2020-05-01 20:13 UTC, cnk requested changes

2020-05-01 20:13 UTC, cnk commented on _layouts/project.html
> +<!--Script for adding frameworks to "Frameworks" Section-->
@ruben1s I don't think we need javascript to fill in the frameworks. The data for this is in the project.md file itself - not in the JSON data we scrape from GitHub's api.

Can you please take this out and see if frameworks display? If so, please edit your pull request. If not, please get back to me so I can look more carefully to see why we need JS to do this.

2020-05-03 20:18 UTC, ruben1s commented
I made the change @cnk requested.

2020-05-03 22:21 UTC, cnk commented
Had to manually resolve conflicts so had to create an alternate pull request #491 that contained these updates

2020-05-03 22:21 UTC, closed without merging