dev template label update
hackforla/website pull request #4879
Opened 2023-06-24 05:04 UTC by whitneywind

Fixes #4478 

### What changes did you make?
  - updated labels in ".github/ISSUE_TEMPLATE/pre-work-template--dev.md"
 

For PR Reviewers and Merge Team
To review this issue, click the link below under "Link for reviewers" and verify that the labels match the updated labels string in the issue.

Link for Reviewers
This URL will be inserted by the dev during the test process and will be used by reviewers to preview the updated template.
URL of the issue branch on the test Repository: https://github.com/whitneywind/website/issues/new?assignees=&labels=Feature%3A+Onboarding%2FContributing.md%2Cprework%2Csize%3A+1pt%2Crole+missing%2CComplexity%3A+Missing%2CDraft&projects=&template=pre-work-template--dev.md&title=Pre-work+Checklist%3A+Developer%3A+%5Breplace+brackets+with+your+name%5D

For PM, Merge Team, or Tech Lead

 Once the pull request associated with this issue is approved and merged, please update and edit epic https://github.com/hackforla/website/issues/4307 by
 Checking off the dependency for this issue
 If all dependencies are checked off, please move issue to the New Issue Approval column and remove the Dependency label

2023-06-25 03:12 UTC, one2code commented
**ETA:** 6/25/23

2023-06-25 14:02 UTC, one2code submitted a review, later dismissed
Good naming convention for the issue branch, and the requested branch to merge into is correct. I've also verified that after clicking the link provided by @whitneywind, all of the updated labels correctly display by default.

Good job on your pull request and excellent attention to detail!

2023-06-25 18:34 UTC, roslynwythe commented
Hi @whitneywind since this issue was written, there have been some changes to the labelling of prework issues, and so we may need to change the required `labels` string.  I will confirm with PM and report back on 6/27.  I apologize for the delay.

2023-06-26 19:43 UTC, t-will-gillis commented on .github/ISSUE_TEMPLATE/pre-work-template--dev.md
> +labels: ['Feature: Onboarding/Contributing.md', 'prework', 'size: 1pt', 'role missing', 'Complexity: Missing', 'Draft']
Hello @whitneywind - My apologies, I gave you incorrect information previously. We **do** want to retain both the 'Complexity: Prework' and the 'prework' labels. Therefore, the edit should be: 

labels: ['Feature: Onboarding/Contributing.md',  'Complexity: Prework',  'prework', 'size: 1pt', 'role missing', 'Draft']

2023-06-26 19:46 UTC, t-will-gillis requested changes
Hi @whitneywind - My apologies- I gave you the wrong information. This line should be changed to:
```
labels: ['Feature: Onboarding/Contributing.md', 'Complexity: Prework', 'prework', 'size: 1pt', 'role missing',  'Draft']
```
and not what I told you previously. Sorry for giving you incorrect info!

2023-06-26 20:38 UTC, one2code commented
I'll be sure to update my review to account for the changes.

On Mon., Jun. 26, 2023, 3:46 p.m. Will Gillis, ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Hi @whitneywind <https://github.com/whitneywind> - My apologies- I gave
> you the wrong information. This line should be changed to:
>
> labels: ['Feature: Onboarding/Contributing.md', 'Complexity: Prework', 'prework', 'size: 1pt', 'role missing',  'Draft']
>
> and not what I told you previously. Sorry for giving you incorrect info!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/hackforla/website/pull/4879#pullrequestreview-1499292355>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AKVNQU2DZI5X2QR6X6SVAALXNHRJ3ANCNFSM6AAAAAAZSJINME>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>

2023-06-27 04:29 UTC, one2code approved these changes, later dismissed
@whitneywind I've reviewed the latest changes, and have verified that you have updated the labels to @t-will-gillis latest comment. Excellent job on quickly updating the labels to the needs of the project.

2023-06-28 20:26 UTC, roslynwythe requested changes
Hi @whitneywind I just realized that I need to request another change in the labels.  I have updated the Action Items on the issue to omit the `Draft` label.  You will have to push a new commit to your fork, re-check the Action Item checkbox and click the "re-review" icon in the PR.  I apologize for missing this problem in my first review, and I thank you for your patience.

2023-06-29 18:07 UTC, t-will-gillis approved these changes
Hi @whitneywind Great job! I am seeing the correct labels applied on the link you provided. Otherwise, your branches are correct, your description is good. Thank you for your patience!

2023-07-02 17:50 UTC, one2code approved these changes

2023-07-06 06:00 UTC, roslynwythe approved these changes
Thank you @whitneywind for your excellent work on this issue and for making the requested changes.  I do apologize that we did not recognize the problem with the issue until you had submitted the PR.

2023-07-06 06:00 UTC, merged