Added labels to gha-issues-template
hackforla/website pull request #4896
Opened 2023-06-28 07:21 UTC by one2code

Fixes #4475 

### What changes did you make?
Added `labels: ['role missing', 'Complexity: Missing', 'Feature Missing', 'size: missing','Draft']` under `description:` in the `gha-issues-template` file found at `.github/gha-issues-template.yml`

### Why did you make the changes (we will use this info to test)?
  To prevent Github Action bots from removing labels when moved to a different column in the project board

### Testing

[Click here](https://github.com/one2code/website/issues/new?assignees=&labels=role+missing%2CComplexity%3A+Missing%2CFeature+Missing%2Csize%3A+missing%2CDraft&projects=&template=gha-issue-template.yml&title=Sample+form+for+GitHub+actions+) to test the labels on the gha-issues-template in my repo. And refer to [this comment](https://github.com/hackforla/website/issues/4475#issuecomment-1610674971) if you would like to push this branch up to your repo and test it there as well.

- [ ] Copy these sections from the Issue into the PR 
  - [ ] "For PR Reviewers and Merge Team"
  - [ ] "Link for Reviewers"
  - [ ] "For PM, Merge Team, or Tech Lead"

2023-06-28 19:06 UTC, roslynwythe requested changes
Hi @one2code thank you for providing the link to the issue template on onetocode/website.  However when I followthat link, no labels appear on the issue template, probably because those labels don't exist in your repository.  Please add the labels in your repository.  Thanks.

2023-06-29 14:30 UTC, one2code commented
@roslynwythe The labels are available for selection under the labels menu, but for some reason, the labels do not stay selected in the template when I link, even when the conditions for them exist in the url such as
https://github.com/one2code/website/issues/new?assignees=&labels=role+missing%2CComplexity%3A+Missing%2CFeature+Missing%2Csize%3A+missing%2CDraft&projects=&template=gha-issue-template.yml&title=Sample+form+for+GitHub+actions+

2023-07-05 01:44 UTC, adrianang requested changes
Hi @one2code! I took a look at the GHA issues template in your repo that you linked and noticed that it was missing the `role missing` label. I checked your source code and it matches with what the linked issue was asking for, so it doesn't seem like anything in the code needs to change, but I noticed that the labels in your repo (https://github.com/one2code/website/labels) has `'role missing'` (single-quotes at the start and end of the tag) instead of `role missing`. If you remove the single quotes at the start and end of the `'role missing'` tag/label in your repo, does that fix your template so that it has `role missing` pre-selected?

Otherwise, the branching looks good and the other four labels requested show up!

2023-07-05 03:16 UTC, one2code commented
> Hi @one2code! I took a look at the GHA issues template in your repo that you linked and noticed that it was missing the `role missing` label. I checked your source code and it matches with what the linked issue was asking for, so it doesn't seem like anything in the code needs to change, but I noticed that the labels in your repo (https://github.com/one2code/website/labels) has `'role missing'` (single-quotes at the start and end of the tag) instead of `role missing`. If you remove the single quotes at the start and end of the `'role missing'` tag/label in your repo, does that fix your template so that it has `role missing` pre-selected?
> 
> Otherwise, the branching looks good and the other four labels requested show up!

I've updated the label on my repo so now that role missing shows up. It was the ' ' around it. I forgot to remove it while troubleshooting and testing various changes on the labels in both the GHA and on my repo.

2023-07-05 05:33 UTC, adrianang submitted a review, later dismissed
The `role missing` label is now showing up for me on the linked template, in addition to the four previous labels that were already showing up. The code matches what was requested of in the issue. Thank you @one2code for fixing this issue!

2023-07-06 02:58 UTC, roslynwythe requested changes
Hi @one2code.  You've made the change as specified in the Action Items, followed the test procedure, and created a well-formed PR.  Unfortunately I need to request a change, because this issue was created a while ago and in the opinion of the current team, the GHA issue template should have the label 'Feature: Board/GitHub Maintenance'.  I have modified the Action Item and I need to ask you to make that change and push the updated branch to your fork to update the PR.   You'll also have to create the new label in your repo.  I apologize for the extra work and thank you very much for your effort and contributions.

2023-07-06 04:17 UTC, one2code commented
@roslynwythe The requested update has been made and tested, and the `Feature: Board/GitHub Maintenance` label displays by default in the new GHA issue template.

2023-07-07 07:50 UTC, adrianang requested changes
Hi @one2code! It seems that the labels aren't showing up for me anymore when I open your template (screenshot below) -- have the labels been added back to the repo again?

Also, I noticed that your pushed code doesn't match the updated labels in #4475 that @roslynwythe had edited them to; I think the `Feature Missing` is still there.

<details>
<summary>My current view of one2code/website GHA issues template</summary>
<img width="1145" alt="Screen Shot 2023-07-07 at 12 39 59 AM" src="https://github.com/hackforla/website/assets/24426473/17be3800-a6e5-4141-8f86-8d1026ed4cdd">
</details>

2023-07-07 08:04 UTC, roslynwythe commented on .github/ISSUE_TEMPLATE/gha-issue-template.yml
> +labels: ['role missing', 'Complexity: Missing', 'Feature: Board/GitHub Maintenance', 'Feature Missing', 'size: missing', 'Draft']
Hi @one2code you'll have to remove `Feature Missing`.

2023-07-07 22:43 UTC, one2code commented on .github/ISSUE_TEMPLATE/gha-issue-template.yml
> +labels: ['role missing', 'Complexity: Missing', 'Feature: Board/GitHub Maintenance', 'Feature Missing', 'size: missing', 'Draft']
Ok, pushing that change up right now.

2023-07-07 23:22 UTC, one2code commented
@adrianang You'll have to click the link below for all of them to show up correctly, the old link will not work as intended.
[Click this link to test the template](https://github.com/one2code/website/issues/new?assignees=&labels=role+missing%2CComplexity%3A+Missing%2CFeature%3A+Board%2FGitHub+Maintenance%2Csize%3A+missing%2CDraft&projects=&template=gha-issue-template.yml&title=Sample+form+for+GitHub+actions+)
@roslynwythe I have made the requested changes.

2023-07-08 02:34 UTC, roslynwythe commented
Hi @one2code thank you for making the update.  In the PR, please update the text under "What changes did you make?" and the link under Testing.

2023-07-08 23:15 UTC, adrianang commented
@one2code The labels are still not showing up for me on the new GHA template link that you had sent... but the code has been updated to match what was requested in the linked issue.

<details>
<summary>
My view of the GHA template on one2code/website
</summary>

<img width="1467" alt="Screen Shot 2023-07-08 at 4 09 10 PM" src="https://github.com/hackforla/website/assets/24426473/d3dc466d-1a7c-4321-b0e6-819928398256">

</details>

2023-07-09 02:22 UTC, one2code commented
> @one2code The labels are still not showing up for me on the new GHA template link that you had sent... but the code has been updated to match what was requested in the linked issue.
> 
> My view of the GHA template on one2code/website
> <img alt="Screen Shot 2023-07-08 at 4 09 10 PM" width="1467" src="https://user-images.githubusercontent.com/24426473/252089441-d3dc466d-1a7c-4321-b0e6-819928398256.png">

I'm unable to replicate this issue. When I open the link in a new tab or refresh, all of the labels are loaded onto the template by default. I need to see the parameters in the url to verify if they are being applied to the issue template.

To be honest, this isn't really a deal breaker as long as the labels are available for selection in the drop down menu. If they were to be added by a bot, this would be managed by a separate GHA script with the following value in it
`Labels to add:  ['role missing', 'Complexity: Missing', 'Feature: Github Board/ Maintenance', 'size: missing','Draft' ]`

2023-07-10 07:24 UTC, adrianang commented
@one2code Here's a screenshot of my view of the template including the URL at the top; this is right after clicking on the updated URL that you had sent on the 7th, which I notice does include the parameters for the label.

<details>
<summary>
My view of the GHA issues template on one2code/website, after clicking your updated URL (URL in view)
</summary>
<img width="1680" alt="Screen Shot 2023-07-10 at 12 02 16 AM" src="https://github.com/hackforla/website/assets/24426473/aa349c08-292c-4b74-ac96-436320c48724">
</details>

However, I also tried testing this template change onto a branch on my fork of the website and am able to see the required labels pre-selected, so the code doesn't seem to be the issue (as previously established, since it matches what was in the linked issue). 

<details>
<summary>
My view of the GHA issues template on adrianang/website, in my one2code-gha-issue-template-4475 branch
</summary>
<img width="1680" alt="Screen Shot 2023-07-09 at 11 52 38 PM" src="https://github.com/hackforla/website/assets/24426473/dfcf9eb9-3a7e-4ab2-96ae-2cc6fcccc2ce">
</details>

I looked through some of the other similar PRs associated with this epic and noticed that their templates were working for me as well (tested using links in issues #4767, #4844, and #4879), so I'm not quite sure why this template is not pre-populating with the labels.

If this is good enough for Roslyn or the rest of merge team, then feel free to disregard my review/I'll approve my review, but from my understanding of the instructions for PR reviewers on the linked issue, as well as a comparison between template links in PRs for the other templates, the template should be showing the labels pre-selected already.

2023-07-11 00:00 UTC, one2code commented
@adrianang were you able to see it at first? I didn't really change any permissions on the repo. All labels were added without ' ' on the repo, and the values array is YAML compliant.  Can you see the labels @roslynwythe ?

2023-07-11 04:48 UTC, adrianang commented
@one2code Yeah, the template was working as expected for me using the reviewer link you had provided until commit [d9c7ed4](https://github.com/hackforla/website/pull/4896/commits/d9c7ed42b58b2654ad06eedf9efad9bb5ff11492); somewhere between my previous approval and previous change request, the labels stopped showing up.

I'll bring this up as one of my blockers during stand-up on Tuesday's/tomorrow's meeting, in case this might just be an issue on my end, and so hopefully it can get merged much sooner than later.

2023-07-12 06:52 UTC, adrianang approved these changes
Per tonight's meeting (7/11), @blulady had suggested rolling back to commit [500d3d6](https://github.com/hackforla/website/pull/4896/commits/500d3d64afcf48ed58638013cbae2c2ce06bde97) as that pushed commit was the last time that the labels had shown up on the linked template URL pre-selected, and/or merging this PR to see if the labels will show up pre-selected on the template, since the labels are showing up on the template on my end when I pushed this branch onto my fork of the repo (labels also in the URL).

Branching is still set up correctly and the code requested has been changed accordingly to requests while this PR was open; thanks @one2code!

2023-07-12 08:02 UTC, roslynwythe approved these changes
Thank you @one2code for completing this issue in spite of the change in the specified labels.  It appears that @adrianang and I no longer have rights to create issues in your repository and I don't understand that, but since both Adrian and I successfully tested your branch in our own repositories, I am approving the PR.

2023-07-12 08:03 UTC, merged