Update Labels: Issue Template: wiki--research-plan-review
hackforla/website pull request #4928
Opened 2023-07-10 22:52 UTC by kiwookim

Fixes #4488

### What changes did you make?
  - replaced labels with: ['Feature: Wiki', 'role: user research', 'size: 0.5pt', 'Complexity: Missing'] in this file path .github/ISSUE_TEMPLATE/wiki--research-plan-review----replace-with-name-of-page-.md
  

### Why did you make the changes (we will use this info to test)?
  - To avoid GitHub bot taking off the labels when dev adds them to issues
  

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
 - No Visual Changes to the website

2023-07-11 04:38 UTC, adrianang commented
- Availability: MTThFSS, 6 PM - 10 PM (PST) (Week of 7/10)
- ETA: I plan on finishing this PR review by Tuesday, 7/11 at 10 PM.

2023-07-11 07:56 UTC, adrianang requested changes
Hi @kiwookim! The branching is set up correctly for this PR, and the corresponding issue is also linked, but in reviewing the files changed, I noticed that you also edited `.github/ISSUE_TEMPLATE/blank-issue-form-with-dependency.yml`. This change seems to correspond with issue #4485 instead, so changes on that file should be discarded for this issue; only `.github/ISSUE_TEMPLATE/wiki--research-plan-review----replace-with-name-of-page-.md` should be changed.

Other than that, the requested code has been changed correctly and the template linked to in the reviewer URL is coming up with the correct labels pre-selected. There are some other changes in the file, but they seem to be cosmetic as they are just removing trailing spaces and will ultimately help clean up the file! Once the changes to the blank issue form are discarded, this should be good to go for merging.

2023-07-12 02:14 UTC, blulady commented
eta: Thursday
avaiability: Thursday

2023-07-13 21:51 UTC, kiwookim commented
> Hi @kiwookim! The branching is set up correctly for this PR, and the corresponding issue is also linked, but in reviewing the files changed, I noticed that you also edited `.github/ISSUE_TEMPLATE/blank-issue-form-with-dependency.yml`. This change seems to correspond with issue #4485 instead, so changes on that file should be discarded for this issue; only `.github/ISSUE_TEMPLATE/wiki--research-plan-review----replace-with-name-of-page-.md` should be changed.
> 
> Other than that, the requested code has been changed correctly and the template linked to in the reviewer URL is coming up with the correct labels pre-selected. There are some other changes in the file, but they seem to be cosmetic as they are just removing trailing spaces and will ultimately help clean up the file! Once the changes to the blank issue form are discarded, this should be good to go for merging.

Hi @adrianang, thank you for the review! Thank you for pointing that out. I actually was wondering about that. Before making a new branch, I git pulled from gh-pages, then made a new branch and only locally changed the file associated with this issue.  But, as you mentioned, I saw all these other changes when I made PR. Cosmetic changes might be from the extension Prettier formatter I am using, but the other labels were the result of 'git pull.' To revert back the file(.github/ISSUE_TEMPLATE/blank-issue-form-with-dependency.yml), should I just delete the labels it added when I git pulled and push again?  Also, what would be a good workflow to prevent this for future PR? Thanks a lot!

2023-07-14 02:20 UTC, mademarc commented
Review ETA: 7/13/2023
Availability: 7:20PM

2023-07-14 02:27 UTC, mademarc approved these changes, later dismissed
Hey @kiwookim the changes for line 3 on the yml was done correctly, the same goes for the line 5 changes for the .md file plus the format was properly done well.

2023-07-15 09:11 UTC, adrianang commented
@kiwookim I took a look at the commit history for your branch and noticed that all of the changes in the blank template GHA file came from commit `fab9469`, so I think the easiest fix to do would be to run `git revert fab9469` in your branch and push that commit into this branch again!

`git revert [commit ID]` makes a new commit that undoes the changes made in the [commit ID] commit  only, which works well in this case since we can discard all the changes in `fab9469` (blank issue template) and want to keep the changes in `55298d2` (research plan template).

I think a good workflow to prevent this for future PRs would be to check what files are being changed when you're making a new PR on Github and double-checking that you've only made changes to files expected in the linked issue. Individually adding files with `git add` would be good for prevention, and knowing how to `git revert` certain commits would be good to 'fix' commits that have already been made 😃

2023-07-15 22:41 UTC, kiwookim commented
@adrianang Thanks a lot for the detailed explanation. It makes a lot of sense now! I will be careful only to add the files I changed in future issues. @mademarc @adrianang I reverted the changes and pushed again! Thank you, adrian and marco!

2023-07-16 09:09 UTC, adrianang approved these changes
This looks good! The branching is still setup correctly, the correct issue is linked, and the changes to the blank template were discarded, so only the Wiki Research Plan template is being changed now. The labels requested to be added are showing up when I check the template through the link. Thank you @kiwookim for taking up this issue and quickly making the requested change! 🙌🏽

2023-07-18 19:48 UTC, t-will-gillis approved these changes
Hi @kiwookim - Great job! The branches are good as is your description, and you have changed only what is being asked for in the issue (besides the removal of whitespaces which you said is probably Prettier). Great communication between yourself and @adrianang to get your commits correct! 
Thanks!

2023-07-18 19:48 UTC, merged