Add a search function to projects page- Draft
hackforla/website pull request #4942
Opened 2023-07-12 16:53 UTC by Thinking-Panda

Fixes #4136

### What changes did you make?
  - Edited html and css files to insert a search bar. Imported the `_search-bar.scss` in `main.scss`
  - Edited `current-projects.js` so the search function displays the desired result.
  

### Why did you make the changes (we will use this info to test)?
  - Html changes- added the search bar as a form
  - CSS changes- added a new file with style properties for the search bar and imported it in `main.scss`
  - JS changes- added functions for click events in the search bar. Edited the function `updateProjectCardDisplayState(filterParams)` to incorporate results from the search function

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

![beforeChangeMobile](https://github.com/hackforla/website/assets/122488603/3160bdfb-dadc-4eb4-90bb-e59597522f26)

![beforeChangeTablet](https://github.com/hackforla/website/assets/122488603/04262563-19d7-41de-a748-08ae94f25155)

![beforeChange](https://github.com/hackforla/website/assets/122488603/7f2b5fc1-a665-4149-a31b-48458541d0f2)

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
![AfterChangeMobile](https://github.com/hackforla/website/assets/122488603/7ca93ed1-dd59-4118-a65d-0b316bd4004f)
![AfterChangeTablet](https://github.com/hackforla/website/assets/122488603/50af4352-c3e1-4b68-804a-fd80d419f0ef)
![AfterChangeLaptop](https://github.com/hackforla/website/assets/122488603/719d1aaf-f886-4071-9afd-07f01fd9c86b)
![search+filterResults](https://github.com/hackforla/website/assets/122488603/f627f4b6-9d8f-4b9f-afe9-7fe091832354)

</details>

2023-07-12 19:22 UTC, Thinking-Panda commented
@kwangric - Let me know if you have any suggestion of code change to combine the filter and search results.

2023-07-13 16:42 UTC, kwangric reviewed
Issue resolved over Slack.

2023-07-18 20:35 UTC, roslynwythe commented
Hi @Thinking-Panda if you were able to get the help you needed, please remove the `Help Wanted` and `Status Updated` labels.  Thank you @kwangric for assisting with the code.

2023-08-01 02:53 UTC, Thinking-Panda commented
@Merge Team- I have made the necessary code changes and this PR is ready to be reviewed and merged. Thanks!

2023-08-01 05:00 UTC, kwangric commented
ETA: EOD 8/5
Availability: Most days after 3pm PT

2023-08-07 23:21 UTC, kwangric requested changes
@Thinking-Panda, great job with this issue!
- The search bar and function works as expected. Projects are correctly filtered based on whether the search term is included in the description or not.
- The search works in conjunction with the filters.
- Boolean operators can be used to refine the search.
- Search bar is also displayed and works correctly in mobile view.

I just have two requests for changes to be made:
- You used `NOT` instead of the `-` symbol for the exclude operator. Given that the issue and the link to boolean operators included uses `-`, it might be best to use that instead.
- For the booleans operators, I noticed that the operators work even when not in uppercase. This might cause confusion fs the user is searching for terms that include the word 'and' & 'or', but aren't trying to use the operators. Can they be changed so they only work if they are in uppercase?

2023-08-08 10:31 UTC, Thinking-Panda commented
@kwangric , the requested changes have been done. Please review. Thanks.

2023-08-09 16:24 UTC, LRenDO commented
Hi @mademarc! Please add your ETA and Availablity when you have a minute.  Thanks!

2023-08-11 00:13 UTC, kwangric requested changes
Thanks for the a quick turnaround on the changes Niki!

- Boolean operators are now working only when in uppercase
- The operators use `-` instead of `NOT`

One last small request: at the moment in order to exclude a term, you will need a space between the `-` symbol and the search term (e.g. `HTML - react`). I believe there shouldn't be a space for the operator to work (`HTML -react`). Can you make this change? The other operators work as expected.

2023-08-11 14:11 UTC, Thinking-Panda commented
@kwangric , @mademarc - Change requested has been implemented. Thank you for your patience. The PR is now ready to be re-reviewed.

2023-08-11 21:29 UTC, StephenTheDev1001 reviewed
The search bar looks great, pixel perfect implementation from the designs. The search bar works as intended. I'm not sure how to handle the event property here. Would it be better to do it the old deprecated way to be consistent or use the newer way to avoid errors in newer browsers? Also a small suggestion for searchEnterKeyHandler.

It's obvious you put a lot of time and effort into this. Thank you.

2023-08-11 21:29 UTC, StephenTheDev1001 commented on assets/js/current-projects.js
> +    if (event.key === "Enter") {
Same here. The [event property](https://developer.mozilla.org/en-US/docs/Web/API/Window/event) is deprecated.
```suggestion
    if (e.key === "Enter") {
```

2023-08-11 21:29 UTC, StephenTheDev1001 commented on assets/js/current-projects.js
> +        document.querySelector(".search-glass").click();
Instead of using a querySelector that calls searchEventHandler, I think it'd be more efficient just to call search event handler.
```suggestion
       searchEventHandler(e);
```

2023-08-11 21:29 UTC, StephenTheDev1001 commented on assets/js/current-projects.js
> +function searchCloseEventHandler(){
Same here. The [event property](https://developer.mozilla.org/en-US/docs/Web/API/Window/event) is deprecated.
```suggestion
function searchCloseEventHandler(e){
e.preventDefault();
```

2023-08-11 21:29 UTC, StephenTheDev1001 commented on assets/js/current-projects.js
> +function searchEventHandler(){
The [event property](https://developer.mozilla.org/en-US/docs/Web/API/Window/event) is deprecated. You can pass the event as a parameter.
```suggestion
function searchEventHandler(e){
e.preventDefault();
```

2023-08-12 00:24 UTC, mademarc commented
Review ETA: 8/11/2023
Availability: 5:24PM

2023-08-12 00:29 UTC, mademarc submitted a review, later dismissed
Hey @Thinking-Panda  the html elements were added very well, same with the scss file and the js file with proper formatting as well and @LRenDO the ETA and Availability is done.

2023-08-15 00:46 UTC, kwangric approved these changes, later dismissed
Thanks for making the requested changes, the search bar is working as intended and everything looks good visually. Great work!

2023-08-18 02:38 UTC, StephenTheDev1001 commented on assets/js/current-projects.js
> +        document.querySelector(".search-glass").click();
@Thinking-Panda do you think this would cause problems doing it this way

2023-08-20 13:24 UTC, Thinking-Panda commented
@StephenTheDev1001, @kwangric @mademarc  , suggested changes have been made and the function still works good. Please re-review

2023-08-20 19:08 UTC, StephenTheDev1001 approved these changes
The search bar works as intended. Good job with the requested changes.

2023-08-20 21:42 UTC, kwangric approved these changes
The search function still functions as expected. 

One thing I noticed in previous commits was that the text in the search bar wouldn't clear when you click the magnifying glass to search, while pressing enter would clear the text. The latest change seems to keep the text from clearing when hitting enter, which is good for consistency sake.

I'm not familiar with the Lint SCSS test, so I'm not sure what is causing it to fail the check. I will see if anyone else on the merge team can help resolve it.

2023-08-21 03:21 UTC, kwangric commented
It looks like the failed check is an issue with the linter itself. Since everything else looks good, I will go ahead and merge the PR. Great job with the issue @Thinking-Panda!

2023-08-21 03:21 UTC, merged