Updated scss to only target h2 on privacy policy page
hackforla/website pull request #4945
Opened 2023-07-13 03:32 UTC by angelenelm

Fixes #4864

### What changes did you make?
 - Update ```h2``` selector on lines 52-54 (within ```@media #{$bp-desktop-up}```) to target ```h2```s in ```.content-section--privacy-policy``` class, which corresponds to ```h2```s in the Privacy Policy card

### Why did you make the changes (we will use this info to test)?
- Per #4864 and #4794

### Screenshots

<details>
<summary>Visuals before changes are applied</summary>

Join Us page:
<img width="1440" alt="Screen Shot 2023-07-12 at 8 17 32 PM" src="https://github.com/hackforla/website/assets/9537526/f830dcf3-3b47-428b-9c9e-64a21120069e">

Privacy Policy page:
<img width="1440" alt="Screen Shot 2023-07-12 at 8 17 54 PM" src="https://github.com/hackforla/website/assets/9537526/2f946a56-dbba-4883-b617-2c50fb113d5f">

</details>

<details>
<summary>Visuals after changes are applied</summary>

Join Us page (headers here are no longer being affected):
<img width="1440" alt="Screen Shot 2023-07-12 at 8 17 36 PM" src="https://github.com/hackforla/website/assets/9537526/23a9f59d-3aea-4970-81b2-4bbf4043b3f0">

Privacy Policy page (headers here are still affected):
<img width="1440" alt="Screen Shot 2023-07-12 at 8 17 56 PM" src="https://github.com/hackforla/website/assets/9537526/6773c4d5-d4d5-40ed-b955-5e3e57ee7fcf">

</details>

2023-07-16 17:45 UTC, kiwookim commented
ETA: July 17 EOD
Availability: 9-5pm PST

2023-07-17 18:21 UTC, steven-positive-tran commented
ETA: July 17 EOD
Availability: 12-6pm PST

2023-07-17 20:42 UTC, steven-positive-tran approved these changes, later dismissed
Branches look good, code changes seem in line with the issue that needed to be addressed. 
I see that 311 page and the join us page the margin at the top for each card is reduced which is the expected outcome.

Good job and thank you for taking up this issue for hackforla.

2023-07-18 00:21 UTC, kiwookim commented
Thanks for taking this issue @angelenelm.
Branch name looks good, and I checked using docker to confirm that there aren't any breaking changes.
Correct class is applied to h2.

2023-07-18 00:26 UTC, kiwookim approved these changes, later dismissed
Thanks for taking this issue @angelenelm.
Branch name looks good, and I checked using docker to confirm that there aren't any breaking changes as a result of applying a class to affect only the h2 elements in privacy policy page.


@roslynwythe @t-will-gillis  -- tagging you guys as Roslyn suggested during Sunday meeting regarding one of the linter not passing.

2023-07-19 14:52 UTC, ronaldpaek submitted a review, later dismissed
Thank you for taking up this issue, everything works perfectly on my end no issue with the linter.

2023-07-19 15:22 UTC, ronaldpaek commented
When I run it on my own repo the test case passes, but the current test keeps failing, how weird

2023-07-19 15:27 UTC, ronaldpaek commented
I wonder if you can refactor to 

```
.content-section--privacy-policy {
	padding-top: 34px;
    padding-bottom: 34px;
    h2 {
      margin-top: 48px;
    }
}
```

I'm also not the best in SCSS, haven't really used it much.

2023-07-19 15:38 UTC, ronaldpaek commented
@t-will-gillis It pass locally on my side, but still seems like it is failing here, you can figure it out and then merge.

2023-07-19 15:39 UTC, ronaldpaek commented
@t-will-gillis if there is still an issue I was thinking of trying to add this rule set in the .stylelintrc.json file 

    "at-rule-no-unknown": true
    
    but not sure if that'll work

2023-07-19 16:02 UTC, angelenelm commented
After some research I saw that the error could be thrown due to the comment syntax starting on line 60. Stylelint doesn't support SCSS but can with [this config](https://www.npmjs.com/package/stylelint-config-standard-scss). Let me know what the best course of action should be :)

2023-07-19 16:09 UTC, angelenelm commented
I saw the check is failing at line 30, which isn't a section I touched so I'm not sure what's going on

2023-07-19 16:09 UTC, ronaldpaek commented
> this config

try it, try to modify the .stylelintrc.json file to extend the package you are referring to see if it works without npm install, I'm still kind of confused about npm install and package.json for this whole project cause there isn't one in the root.

2023-07-19 21:27 UTC, t-will-gillis requested changes
hi @angelenelm Thanks for your patience! Your issue looks great as the previous reviewers have indicated.

The 'fail' that is happening with the Lint SCSS is likely caused by some conflicts that occurred when the we updated `github/super-linter` to v5.0.0 per the Dependabot. Some other PRs/ issues are being flagged with the same 'fail' message, so this is not unique to yours.

Would you please revert the changes to `.stylelintrc.json`? After that we can merge your PR. We will open a new issue to address the Lint SCSS.

Thank you!

2023-07-19 22:10 UTC, angelenelm commented
@t-will-gillis Thanks so much for the explanation! The changes to that file have been removed.

2023-07-19 22:10 UTC, t-will-gillis approved these changes

2023-07-20 18:57 UTC, ronaldpaek approved these changes

2023-07-21 22:07 UTC, merged