Project languages pull 3805
hackforla/website pull request #5037
Opened 2023-07-20 04:35 UTC by StephenTheDev1001

Fixes #replace_this_text_with_the_issue_number

### What changes did you make?
  -allow for more than one repo id to be scraped
  -merge lanaguages array from all repos without duplicates
  -added CTI backend repo id to md file

### Why did you make the changes (we will use this info to test)?
  -the languages section now shows languages used in both CTI Frontend and CTI Backend 
  -
  -

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

![image](Paste_Your_Image_Link_Here_After_Attaching_Files)

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
![image](Paste_Your_Image_Link_Here_After_Attaching_Files)

</details>

2023-07-20 04:51 UTC, StephenTheDev1001 commented
I don't like what I did on line 30 of project.js, but I can't think of a way to do it better without going beyond the scope of the issue.

2023-07-20 17:05 UTC, MattPereira requested changes
@StephenTheDev1001 admire your persistence and hard work on this issue


you might consider adding an extra key/value pair to the `civic-tech-index.md` that contains the additional repo id and then just adding conditional logic to `projects.js` and `current-projects.js` that checks for if that property exists on the project object in order to display the extra languages on both the project details page and the project cards

2023-07-20 17:05 UTC, MattPereira commented on _projects/civic-tech-index.md
> +identification: '241519642, 275296439'
adding the extra project id like this breaks the logic in `current-projects.js` which generates the project cards that show on the homepage and projects page

![Screenshot from 2023-07-20 09-51-01](https://github.com/hackforla/website/assets/73561520/869ad3be-9a37-4010-bc48-9150f5426354)

2023-07-25 11:08 UTC, StephenTheDev1001 commented
@MattPereira Should I make it to where we can add more than one additional repo to scrape from or is one additional repo enough?

If more than one additional repo to scrape from is required, I might need another week to complete this.

2023-07-25 15:42 UTC, MattPereira commented
@StephenTheDev1001 I think one additional is fine since only this one project has multiple repos but I'm not up to date with website team affairs anymore 

@t-will-gillis @roslynwythe what do you think?

2023-07-25 22:36 UTC, t-will-gillis commented
>@StephenTheDev1001 I think one additional is fine since only this one project has multiple repos but I'm not up to date with website team affairs anymore

@MattPereira I am not aware of any other project that would need more than one additional repo to scrape for language data.

2023-07-26 09:42 UTC, StephenTheDev1001 commented on _projects/civic-tech-index.md
> +identification: '241519642, 275296439'
This helped a lot. Thanks

2023-07-26 16:12 UTC, MattPereira approved these changes
Looks good @StephenTheDev1001 !!! 

Nice execution, solid communication with the team, and quick turnaround on the requested changes :+1:

2023-07-26 16:12 UTC, MattPereira commented on assets/js/project.js
> +}
I like the refactor here it's more readable with the function

Also using `const` and `return` feels much stronger than setting project to null and using `break` to end the loop :muscle:

2023-07-26 16:12 UTC, MattPereira commented on assets/js/project.js
> +    let set = new Set(languagesArr);
i think these could be `const` but its nbd. Nice use of `Set` !!! :tada:

2023-07-27 00:24 UTC, LRenDO commented
Hi @adrianang! If you plan to review this PR, please add your ETA and availability when you have a minute. If not, please remove yourself as reviewer. Thanks!

2023-07-27 11:00 UTC, adrianang commented
- Availability: FSS, 6 PM - 10 PM (PST) (Week of 7/24)
- ETA: I plan on finishing this issue by Saturday, 7/29 at 10 PM.

2023-07-31 02:49 UTC, adrianang approved these changes
Hi @StephenTheDev1001 — the branching is set up correctly, the corresponding issue is linked, and the requested change has been made (ensure that Civic Tech Index shows all languages between its two repositories). In testing your branch on my local environment through Docker, I see the same thing that you had screenshotted for both the card view on the main Website page and the CTI project page view itself, and no other project seems to be affected as a result of these code changes.

I like the guard clauses that you set up, as a result of adding the second repo ID instead of appending it onto `identification`, as it minimizes the number of nested loop calls that the function makes (if I recall correctly, one of your previous commits called nested loops on each project). Nice job optimizing!

Thank you for sticking with the issue and seeing it through to completion; apologies that I couldn't be of more help, but it's great that you were able to find a pretty clever solution. Your efforts are deeply appreciated! 🙌🏼

2023-07-31 02:49 UTC, merged