removed ending slash for IMG tag-issue #5027
hackforla/website pull request #5043
Opened 2023-07-20 22:31 UTC by jnomad21

Fixes #5027

### What changes did you make?
Removed a closing slash from an IMG tag for `<img` src="/assets/images/about/wins-card-mobile.svg" alt="Wins card: contributors' names, teams and roles, and testimonials of their `accomplishments.">`

### Why did you make the changes (we will use this info to test)?
Action was requested for a good first issue to make code consistent

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

![hfla-issue-5027-before](https://github.com/hackforla/website/assets/127683817/772bbcc5-9f5a-4725-bcc5-508ef50d881c)

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
![hfla-issue-5027-after](https://github.com/hackforla/website/assets/127683817/733c00c2-da64-451f-84d4-ab5ff4cdec6e)

</details>

2023-07-21 04:40 UTC, thedvo commented
Review ETA: 8pm PST - 07/21/23
Availability: 5-8 PM Tues-Fri

2023-07-21 18:45 UTC, thedvo approved these changes
Hey @jnomad21, great job working on this issue. You committed to and from the correct branches and made the correct changes to the img tag. Everything looks good to me and I've approved the PR. Thank you for your contribution!

2023-07-22 11:11 UTC, adrianang commented
> Review ETA: 8pm PST - 07/21/23 Availability: 5-8 PM Tues-Fri

@thedvo I noticed that you made yourself an _assignee_ on this pull request, when I think you meant to assign yourself as a _reviewer_. I went ahead and removed you as an assignee, but in the future, you just need to assign yourself as a reviewer (right above the assignees) if you're committing to make a PR. Thank you for reviewing this issue! 🙌🏼

2023-07-22 11:30 UTC, adrianang requested changes
Hey @jnomad21! The branching is set up correctly, the corresponding issue is linked, and you've made the exact changed asked — no more, no less — but since this issue doesn't really involve any visual changes, your PR doesn't need any screenshots. Can you delete the screenshots from your PR and instead write a quick blurb explaining why there isn't visual changes (per Section 3.1biv of [our contribution guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)). This will help keep our PR documentations a bit cleaner and more organized.

Also, I noticed that you had submitted this PR before your earlier good first issue (#5006) was merged — please assign yourself to only one issue at a time. If you want to contribute while waiting for your issue to be merged or closed, reviewing PRs are a good way to do so! 😄

2023-07-25 15:18 UTC, jnomad21 commented
@adrianang Thank you for the additional info.  I have removed the screenshots and written the summary.  Also, apologies on taking up the second issue, I misunderstood and thought we were able to once everything was approved but I reviewed the documentation and it states that we cannot take up another issue until the first one is merged.  I will follow that procedure moving forward.

2023-07-27 03:19 UTC, adrianang approved these changes
Hi @jnomad21 — thank you for editing your PR! As before, the branching is still set up correctly, the corresponding issue is still linked, and the requested ending slash on the `img` tag on line 29 for the mobile Wins card was removed.

One thing I did notice in the linked issue though, was that this issue was taken from the `New Issue Approval` column, rather than `Prioritized Backlog`. Just a light reminder for your next issues that you should only take issues that are in the `Prioritized Backlog` column, as issues in the `New Issue Approval` column still have to be reviewed by project leads before a dev can start working them. However, it seems that Bonnie has gotten a chance to look at it and sort it appropriately, so this issue can/should be approved now.

Thank you again for taking up this issue and good job with finishing your first two `good first issue`s! 🥳

2023-07-27 03:21 UTC, merged