Integrate donation gif component 4504
hackforla/website pull request #5055
Opened 2023-07-24 00:39 UTC by bphan002

Fixes #4504 

### What changes did you make?
  - Replaced the html from the about-card-donations file to utilize the donate component
  - Modified the SCSS  so that the component styles matches the current appearance
  - No changes were made to the mobile view

### Why did you make the changes (we will use this info to test)?
  - I made the changes so the donation section are more uniform through the various pages

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>

<summary>Visuals before changes are applied</summary>

![Screenshot 2023-07-23 at 5 38 02 PM](https://github.com/hackforla/website/assets/83096266/ba84fae4-cefe-430f-ac0e-4efc74de8ccd)
</details>

<details>
<summary>Visuals after changes are applied</summary>
  
![Screenshot 2023-07-23 at 5 01 55 PM](https://github.com/hackforla/website/assets/83096266/82605be7-3dd2-4180-a1d8-c88a5e14a571)

![
</details>

2023-07-26 02:23 UTC, kwangric commented
ETA: EOD 7/26
Availability: After 5pm PDT

2023-07-26 19:02 UTC, JpadillaCoding commented
eta: 7/29
availability: 7/29 5pm-5am

2023-07-27 06:37 UTC, LRenDO commented
Hi @mademarc! If you still would like to review this request, please add your ETA and Availability when you get a minute. If not, please remove yourself as a reviewer. Thanks!

2023-07-28 02:25 UTC, mademarc commented
Review ETA: 7/27/2023
Availability: 7:25PM

2023-07-28 02:29 UTC, mademarc submitted a review, later dismissed
Hey @bphan002 Good call on the html and SCSS code changes and @LRenDO   the ETA and Review is done.

2023-07-28 03:27 UTC, kwangric submitted a review, later dismissed
Branches are set up correctly and it looks like the `about-card-donations.html` page now uses the liquid `include` tag as stated in the issue.

The donate component still looks good on desktop and mobile. I did notice there was some slight margin/padding differences compared to the current design on the About page, but the new design matches the donate component on the Join Now page that was merged recently through a similar issue, so I'm good with that.

Great work with the issue!

2023-07-29 12:40 UTC, JpadillaCoding submitted a review, later dismissed
Hey, @bphan002! 
The branches are set up correctly, you eliminated the correct code, included the proper liquid tag, and set up styling to keep the component consistent with the Join Us page. The component also looks good on mobile. Good job!

2023-07-30 04:32 UTC, adrianang commented
There is a bug I noticed that causes the Donation component on the About page to essentially stay in Mobile view if the window is resized from the tablet view as an inline class that overrides the `display: grid;` rule gets added upon window resize.

I took a look into the cause and notice that it probably has something to do with some of the JS code in `assets/js/about.js` that assigns classes to the containers on the page upon resize, but am not completely sure off the top of my head of an immediate fix for this, without going into the code a bit deeper.

With that, I consulted the rest of Merge Team on how to move forward with merging this PR, as merging this would technically complete the refactor request and make the components on all the pages look quite nice, but would also introduce a bug onto a pretty important part (donation section) of the website.

2023-07-30 05:10 UTC, adrianang requested changes
Hi @bphan002 — although the changes look great so far (the integration of the component is functionally working, and the style changes are looking consistent between the three locations the component is situated in and also improve the appearance), the bug that the refactor would introduce onto the page due to how the event listeners for this page are set up (so nothing that you had coded!) is quite substantial and will have to be looked into for possible solutions before this gets merged.

2023-08-01 22:21 UTC, bphan002 commented
Hi @adrianang

Do you know if I can work on other issues, while this one gets solved?  Or do I work on that bug?

2023-08-02 10:20 UTC, adrianang commented
Hi @bphan002 — we ask that developers stay on one issue until the issue gets merged; if you would like to look into a possible fix for the bug in the meantime, that would be great!

As a related update, Bonnie had advised to merge this issue with the bug, as it technically completes the refactor with working functionality, although the presentation is off, but also advised to first look for possible fixes that would avoid having to do an Emergent Request to fix the bug before merging. I'll only be able to do so later today or tomorrow, but if you can find a fix for it before then, that would also be great! If neither of us can find a fix, I'll probably merge this around Friday afternoon/evening (and after then you'd be able to pick up a new issue). Thanks for your patience!

2023-08-06 03:38 UTC, adrianang commented
Hey @bphan002 — I finally got the chance to take a closer look at this bug; if you put the donation GIF component includes into `<div class="about-us-section-content">`, then that `div` gets the `display: block;` rule added onto it, and then the donation component will shift between the `grid` view on tablet-size up and the `flex` view on mobile (since the parent container no longer has the overriding `display: block` rule).

Essentially, adding this `div` back on line 3:
```
<div class="about-us-section-content">
  {% include donation/donate-gif-text.html %}
</div>
```

Let me know if that worked for you! If it does, I'll merge your PR.

2023-08-09 04:13 UTC, bphan002 commented
Hi @adrianang I went ahead and added the div.  Thanks for the suggestion.

2023-08-09 08:03 UTC, adrianang requested changes

2023-08-09 08:03 UTC, adrianang commented on _includes/about-page/about-card-donations.html
> +        <div class="about-us-section-content"></div>
@bphan002 The ending `</div>` tag on this line (line 3) needs to be deleted. Currently, the footer is taken out of the document flow of the About page because of this ending tag.

I would also remove the extra tab on lines 3–5 to keep the file clean and show that the header `<div>` and content `<div>` are sibling elements.

2023-08-10 09:41 UTC, adrianang approved these changes
@bphan002 The About page is now rendering correctly for me and integrating the Donation GIF component seems to work nicely now between the mobile and desktop views! 🙌🏼

Thank you for completing this issue and working through the bug throughout this whole time!

2023-08-10 09:43 UTC, merged