Add Hero Section
hackforla/website pull request #51
Opened 2019-03-28 20:30 UTC by abregorivas

Following changes were made
- Hero _include created
- Hero signup form created
- Set up hero as a collection
- Linked to index.html

2019-03-31 22:24 UTC, thekaveman requested changes

2019-03-31 22:24 UTC, thekaveman commented on _hero/hero.md
> +      Hack for LA. Everyone is welcome!
Can you please clean up the spacing and line breaks?

2019-03-31 22:24 UTC, thekaveman commented on _includes/hero.html
> +    <p class="form-confirmation">
Would this `form-confirmation` make more sense as part of the `forms/hero-signup` include? Presumably the two should always be used together, and some javascript is going to be acting on both.

2019-03-31 22:24 UTC, thekaveman commented on _includes/hero.html
> +    {% endfor %}
What's the use-case for supporting multiple hero items? If we're going to support multiple, we may want a wrapper around each for spacing etc.

2019-04-10 01:33 UTC, abregorivas commented
Re-based and pushed all changes.

2019-04-23 02:47 UTC, thekaveman approved these changes

2019-04-23 03:53 UTC, merged