Removed ending slash from header-hero img tag in Program Areas page
hackforla/website pull request #5161
Opened 2023-08-08 01:05 UTC by agutiernc

Fixes #5137

### What changes did you make?
  - Updated header-her img tag with no ending slash in Program Areas page.

### Why did you make the changes (we will use this info to test)?
  - So that the code base is consistent with how we use img HTML tags.
  

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

![image](Paste_Your_Image_Link_Here_After_Attaching_Files)

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
![image](Paste_Your_Image_Link_Here_After_Attaching_Files)

</details>

2023-08-08 07:29 UTC, Abrosss requested changes
Hello @agutiernc! Everything looks good! The branch was set up correctly. The ending slash was removed in one img tag (toolkit-hero.svg) as requested. The image is displayed correctly after changes, and nothing is affected on the page in my environment.
The only thing I would remind you to do is to check all the boxes in the issue #5137  (Action Items) and it's done!

2023-08-08 21:36 UTC, agutiernc commented
> Hello @agutiernc! Everything looks good! The branch was set up correctly. The ending slash was removed in one img tag (toolkit-hero.svg) as requested. The image is displayed correctly after changes, and nothing is affected on the page in my environment. The only thing I would remind you to do is to check all the boxes in the issue #5137 (Action Items) and it's done!

Thanks @Abrosss! Boxes are checked.

2023-08-08 21:40 UTC, christinaor approved these changes
Good job on this good first issue! Confirming the slash has been removed and the checklist items have been checked off.

2023-08-09 03:04 UTC, Abrosss approved these changes
Thank you @agutiernc !

2023-08-09 03:33 UTC, merged