Fix issue 5178 : Refactor img tag
hackforla/website pull request #5190
Opened 2023-08-13 06:54 UTC by nitin-pandita

Fixes #replace_this_text_with_the_issue_number
Fix issue #5178
### What changes did you make?
  - Deleted the backslash at the end of the image tag

### Why did you make the changes (we will use this info to test)?
  -
  -
  -

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

![image](Paste_Your_Image_Link_Here_After_Attaching_Files)

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
![image](Paste_Your_Image_Link_Here_After_Attaching_Files)

</details>

2023-08-13 07:35 UTC, wongstephen requested changes
Hi @nitin-pandita 

Great job with the 'good first issue'. The code that you pushed looks correct. 

Your labels are not being pulled into the pull request. You likely need to add the issue # to the first line of the template "Fixes #replace_this_text_with_the_issue_number" so that the bot parses it correctly. 

Next, you may want to add a brief description on why the changes were needed. A good way to do it for this issue is to paraphrase it directly from the issue:  so that the codebase is consistent with how we use img HTML tags.

Your screenshots are not working for me. Screenshots are not necessary for this fix since there's not visual change, but if you choose to toss some in, that great too!

Great job! I also look forward to the changes.

2023-08-13 10:49 UTC, nitin-pandita commented
> Hi @nitin-pandita
> 
> Great job with the 'good first issue'. The code that you pushed looks correct.
> 
> Your labels are not being pulled into the pull request. You likely need to add the issue # to the first line of the template "Fixes #replace_this_text_with_the_issue_number" so that the bot parses it correctly.
> 
> Next, you may want to add a brief description on why the changes were needed. A good way to do it for this issue is to paraphrase it directly from the issue: so that the codebase is consistent with how we use img HTML tags.
> 
> Your screenshots are not working for me. Screenshots are not necessary for this fix since there's not visual change, but if you choose to toss some in, that great too!
> 
> Great job! I also look forward to the changes.

I have done all the changes please have a look

2023-08-13 17:18 UTC, roslynwythe commented
@nitin-pandita I need to close this PR because the linked issue was not yet in the Prioritized Backlog column.  Please message me on Slack if you need help finding another issue.

2023-08-13 17:18 UTC, closed without merging

2023-08-14 00:11 UTC, nitin-pandita commented
> @nitin-pandita I need to close this PR because the linked issue was not yet in the Prioritized Backlog column. Please message me on Slack if you need help finding another issue.

@roslynwythe thank you for your message, I would love to contribute, can you please tell me your slack username