Refactor img tag –– About Us Sponsors Card
hackforla/website pull request #5240
Opened 2023-08-16 23:26 UTC by homeroochoa47

Fixes #5201 

### What changes did you make?
  - Removed the ending slash in the img HTML tag for the about-card-sponsors header icon

### Why did you make the changes (we will use this info to test)?
  - The tag was updated to create consistency among HTML tags in the rest of the codebase 

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>
-Desktop
<img width="810" alt="before-edit-desktop" src="https://github.com/hackforla/website/assets/104741653/4cc346e0-0bbc-47e3-be9b-63eb60175e29">

-Mobile
<img width="358" alt="before-edit-mobile" src="https://github.com/hackforla/website/assets/104741653/6caa440b-d4b2-474d-950e-a056f107e355">

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
-Desktop
<img width="885" alt="after-edit-desktop" src="https://github.com/hackforla/website/assets/104741653/30ff4e5d-c81f-4b01-982a-2638ed0252eb">

-Mobile
<img width="358" alt="after-edit-mobile" src="https://github.com/hackforla/website/assets/104741653/37e138b1-8ebe-4866-9bac-289e327d4139">

</details>

2023-08-16 23:35 UTC, Vinny02 commented
Availability: Mon-Fri 4pm-7pm
ETA: 08/16 EOD

2023-08-16 23:49 UTC, Vinny02 requested changes
Hi @homeroochoa47 ! Great job with your first PR. The branches are set up correctly and your code is correct. You have linked the correct issue, and the website works in my local environment. 

 One minor change, is that there was no visual changes to the website, so instead of your screenshots, you can clean up the PR by writing:
 
Screenshots of Proposed Changes Of The Website (if any, please do not screen shot code changes)
No visual changes to the website.

2023-08-17 17:35 UTC, Vinny02 approved these changes

2023-08-17 17:39 UTC, Vinny02 commented
Hi @homeroochoa47 , I can see you have updated it to get rid of the screenshots and I have approved the pull request. In the future, you can remove the drop-down text saying "Visuals before changes are applied" and "Visuals after changes are applied", so that it looks like this:

Screenshots of Proposed Changes Of The Website (if any, please do not screen shot code changes)
No visual changes to the website.

2023-08-19 23:48 UTC, adrianang approved these changes
Hi @homeroochoa47 – the branching looks good, the corresponding issue is linked, and the requested change of removing the ending slash on the Sponsors icon has been removed on line 4. This change also doesn't appear to change anything on the About Us page visually or functionally when I test it on my local environment, which is expected (and what we want!).

The What/Why in the PR is also well-written. @Vinny02 had a great suggestion on how to handle a PR where there are no visual changes, and I would try to implement it like that for the next PR as it'll help keep our documentation a bit more organized, but overall, this detail is just something to keep in mind for next time and the rest of the PR was done well.

Thank you for taking up this issue! 🙌🏼

2023-08-19 23:48 UTC, merged