Removed ending slash in img tag
hackforla/website pull request #5247
Opened 2023-08-17 22:56 UTC by mshirk2

Fixes #5150 
### What changes did you make?
  - Changed the img HTML tag ending with a slash (<img.../>) to an img tag without an ending slash (<img...>) in the Partner With Us section of the Join Us page

### Why did you make the changes (we will use this info to test)?
  - So that the codebase is consistent with how we use img HTML tags

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

![Before](https://github.com/hackforla/website/assets/104318817/bfb6c774-3b90-4e7c-9abc-7a558767036d)

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
![After](https://github.com/hackforla/website/assets/104318817/680b72eb-d1b8-41af-8512-b3a7c6bd1502)

</details>

2023-08-18 12:19 UTC, Vinny02 commented
ETA: EOD
Availability: 9-5 friday aug 19

2023-08-18 12:24 UTC, Vinny02 requested changes
Hi @mshirk2 , great work with your first PR! I can confirm the necessary changes have been made. One small change is that a screenshot isn't needed for this PR since there was no visual changes, so you can remove the screenshots and the "Visuals before/after changes are applied" details section. It should look like this:


Screenshots of Proposed Changes Of The Website (if any, please do not screen shot code changes)
No visual changes to site

2023-08-19 20:55 UTC, mshirk2 commented
Thanks @Vinny02! I have updated the PR description as you suggested.

2023-08-19 21:19 UTC, Vinny02 approved these changes
I can confirm you made the changes @mshirk2 and I've approved the PR. Great work and thank you for your contribution at HFLA!

2023-08-20 02:58 UTC, adrianang approved these changes
Hi @mshirk2 — the branching is set up correctly, the corresponding issue is linked, the PR is descriptive, and the change of removing the ending slash on the image tag in line 73 has been removed.

In testing this branch on my local environment, I noticed that this refactoring had already been completed by #5235, but it seems to be that two separate issues were made for this image tag and you wouldn't have noticed as I had just merged the previous issue earlier today, so nothing that you had done wrong! The good news is that your branch didn't throw me a merge conflict, so good job! 👍🏼 

Sorry about the issue already being completed, but I think the important takeaway from `good first issue`s are getting comfortable with making PRs and updating/editing as needed in response to code review, and I think you did that well based on your PR and correspondence with @Vinny02 above. Thank you for taking up this issue! 🙌🏼

2023-08-20 02:58 UTC, merged