Hid non-functional links on Engage project site
hackforla/website pull request #5346
Opened 2023-08-30 00:55 UTC by erinzz

Fixes #5330 

### What changes did you make?
  - Hid non-functional links in Engage project card 

### Why did you make the changes (we will use this info to test)?
  - Currently the links lead to non-existent pages. We want to hide the links until we have functional pages built for each link. 

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>
![Screenshot 2023-08-29 at 5 39 56 PM](https://github.com/hackforla/website/assets/95315514/a5e02573-8d63-4c37-abde-8354c60899cd)
</details>

<details>
<summary>Visuals after changes are applied</summary>
![Screenshot 2023-08-29 at 5 40 06 PM](https://github.com/hackforla/website/assets/95315514/4cb0862d-74c0-44a0-9824-3c5a54329954)
</details>

2023-08-31 20:07 UTC, brianf4 commented
Review ETA: 6 PM 8/31/2023
Availability: 1-8 PM Thursday

2023-08-31 21:39 UTC, brianf4 commented on _projects/engage.md
> -  - name: Site
Just this line to be commented out.

2023-08-31 21:40 UTC, brianf4 commented on _projects/engage.md
> -    url: 'https://sm.engage.town'
Just line 41 to be commented out.

2023-08-31 21:46 UTC, brianf4 requested changes
Hey @erinzz I left comments on the lines that should just be commented out rather than all the links!

2023-08-31 21:51 UTC, brianf4 commented
Hey @erinzz , I believe the issue wanted to just comment out the name for "Site" and the url for "Site". As those links are the dead ones. All the other links are functional. I left comments on the 'file changed' tab showing what lines should be commented out.

2023-09-01 02:02 UTC, mademarc commented
Review ETA: 8/31/2023
Availability: 7:01PM

2023-09-01 02:06 UTC, mademarc submitted a review, later dismissed
Hey @erinzz The changes are done well and the interface on the screenshots looks good as well.

2023-09-01 02:28 UTC, StephenTheDev1001 commented
@brianf4 From the issue "Comment out both the line beginning with  - name: ... as well as the line with    url: ...". I think he wants lines 38 - 41 commented out.

2023-09-01 02:40 UTC, erinzz commented
Hey @brianf4, thanks for catching that! And, @StephenTheDev1001, thanks for clarifying which lines to comment out!

I've corrected the changes and only hid the non-functional links while keeping the functional ones. See below for the new after visuals. 

![Screenshot 2023-08-31 at 7 36 09 PM](https://github.com/hackforla/website/assets/95315514/47995447-3d63-46f3-a8bb-89cf8cb50dcb)

2023-09-01 02:59 UTC, StephenTheDev1001 requested changes
Replace the image in the `Visuals after changes are applied` section with the new screenshot you captured and you're all set. Good job on your first pull request.

2023-09-01 03:22 UTC, brianf4 commented
> @brianf4 @erinzz From the issue "Comment out both the line beginning with - name: ... as well as the line with url: ...". I think he wants lines 38 - 41 commented out.

@StephenTheDev1001 

You are correct that lines 38 through 41 should be commented out but for this issue in particular it's just asking for lines 40 and 41 to be commented out. 

I only say this because I actually just worked and an [issue](https://github.com/hackforla/website/pull/5339) where they **only** wanted the "Test Site" `name` & `url` commented out.

2023-09-01 03:24 UTC, brianf4 requested changes
Please comment out **only** lines 40 & 41.

2023-09-01 18:40 UTC, StephenTheDev1001 requested changes
@brianf4 is right. Comment out lines 40 - 41 and update the screenshot on the PR.

2023-09-01 22:21 UTC, closed without merging