Add About/contact section
hackforla/website pull request #54
Opened 2019-03-28 22:23 UTC by abregorivas

The following changes were made:
- Create about & contact includes
- Create collection files for contact & about
- Configured collection and connect to index.html

2019-04-02 05:33 UTC, thekaveman requested changes

2019-04-02 05:33 UTC, thekaveman commented on _contact_us/contact-us.md
> +w---
this was probably from a vim `:wq` right?

2019-04-02 05:40 UTC, abregorivas commented on _contact_us/contact-us.md
> +w---
lol! yes it was trying to exit

2019-04-02 06:20 UTC, thekaveman requested changes
This is almost there. I think to get the site up:

1. convert to simple includes like you did for the hero
2. rebase on the latest `gh-pages` (and careful with those whitespace changes on e.g. index)

2019-04-10 01:34 UTC, abregorivas commented
Rebased and made all the changes

2019-04-23 03:56 UTC, thekaveman approved these changes

2019-04-23 03:56 UTC, merged