Refactor HTML to resolve linter error in about-card-executive-letter
hackforla/website pull request #5405
Opened 2023-09-01 07:24 UTC by euthanizedtortoise

Fixes #replace_this_text_with_the_issue_number

### What changes did you make?
  - ' -> "
  -
  -

### Why did you make the changes (we will use this info to test)?
  - bc it told me to
  -
  -

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

![image](Paste_Your_Image_Link_Here_After_Attaching_Files)

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
![image](Paste_Your_Image_Link_Here_After_Attaching_Files)

</details>

2023-09-01 21:54 UTC, ortegaa32 commented
Review ETA: 3 PM 9/1/23
Availability: 1-3 PM everyday

2023-09-01 22:22 UTC, ortegaa32 requested changes
Hey @euthanizedtortoise! It appears as though there is no issue linked to this pull request. In the first line: Fixes #replace_this_text_with_the_issue_number, could you please add the issue number that this pull request is addressing. Also, could you please be more descriptive in your pull request and if there are no visual changes to the website you could just delete everything after the "Screenshots of Proposed Changes Of The Website" and note that there are no visual changes. After making those changes, please request another review and I'd be glad to approve your changes. Thanks!

2023-09-01 23:40 UTC, euthanizedtortoise commented
ok thanks for letting me know i’ll get to it
Sent from Gmail Mobile


On Fri, Sep 1, 2023 at 3:22 PM Arturo Ortega ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Hey @euthanizedtortoise <https://github.com/euthanizedtortoise>! It
> appears as though there is no issue linked to this pull request. In the
> first line: Fixes #replace_this_text_with_the_issue_number, could you
> please add the issue number that this pull request is addressing. Also,
> could you please be more descriptive in your pull request and if there are
> no visual changes to the website you could just delete everything after the
> "Screenshots of Proposed Changes Of The Website" and note that there are no
> visual changes. After making those changes, please request another review
> and I'd be glad to approve your changes. Thanks!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/hackforla/website/pull/5405#pullrequestreview-1607719738>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A3ZA4JH5YTI2YMAUE663YF3XYJN2XANCNFSM6AAAAAA4HEWJTI>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-09-02 00:46 UTC, euthanizedtortoise commented
Just fixed it feel free to check when you have time. :)

2023-09-03 22:30 UTC, ortegaa32 commented
- Pull request contains correct branch
- Pull request links to correct issue. 
- Changes don't appear to break the website 
- Changes made to the right file and source code looks good.

Good job on your first pull request @euthanizedtortoise!

2023-09-03 22:30 UTC, ortegaa32 approved these changes

2023-09-04 03:01 UTC, t-will-gillis approved these changes
Hey @euthanizedtortoise - Great job on your first issue and working with @ortegaa32. The branches are correct, the original issue is linked, the description explains what was done and why, and the code changes are clean. Looks good- thanks!

2023-09-04 03:02 UTC, merged