Added Meeting Times to Project Pages Fixes #541
hackforla/website pull request #543
Opened 2020-05-26 20:10 UTC by ruben1s

Fixes #541

2020-05-26 20:14 UTC, ruben1s commented
Removed console.log on second merge.

2020-05-27 17:10 UTC, cnk requested changes
@ruben1s The meeting info looks good on the page but the code contains a lot of stuff that isn't needed (or even used?). Since the output is just a list of the upcoming meetings for this project - not broken out into days of the week, I don't think there is any reason to be creating the day of week lists. Can you simplify this code so it just goes through the JSON data and grabs all the events for the project we are looking for? The data we receive is ordered so I think you can just display it as is - once you have grabbed the relevant entries.

2020-05-27 17:10 UTC, cnk commented on _layouts/project.html
> +// Assigns variable to each header by ID
The html doesn't have any of these elements so this code is not needed

2020-05-27 18:45 UTC, cnk commented on _layouts/project.html
> +function removeDuplicates(array) {
Not used

2020-05-27 18:45 UTC, cnk commented on _layouts/project.html
> +            if (scheduleData == localData) {
Question: Why are you assigning different css classes to the 2 data types? Is this so you can see if the updates succeeded? or is there some other reason?

2020-05-27 18:45 UTC, cnk commented on _layouts/project.html
> +let calendarFetch = fetch(API_URL, {method: 'GET'});
Is there a reason to assign this to a variable? It's only used once - and very far away from this assignment which makes the code harder to read.

2020-05-27 18:45 UTC, cnk commented on _layouts/project.html
> +let meetingsToday = false;
NitPick: this variable name is misleading. The meetings are not necessarily today. How about meetingsFound?

2020-05-27 18:45 UTC, cnk commented on _layouts/project.html
> +            if (projectTitle.toLowerCase().substring(0,4) === projectName.toLowerCase().substring(0, 4)
I would prefer not to work around the differences in project titles between our project cards and the VRMS titles. I would prefer to leave the mismatched projects without meeting times to encourage VRMS to fix the titles - or insist we change our titles. 
But if you want to include this code, it needs a comment to explain the purpose and the implimentation.

2020-05-27 19:08 UTC, ruben1s commented on _layouts/project.html
> +            if (scheduleData == localData) {
I gave it two diff classes so that the js knows what to replace using the class as an identifier.

2020-05-27 19:09 UTC, ruben1s commented on _layouts/project.html
> +let meetingsToday = false;
I removed meetingsToday

2020-05-27 19:11 UTC, ruben1s commented on _layouts/project.html
> +let calendarFetch = fetch(API_URL, {method: 'GET'});
Just a good habit. I'll change it.

2020-05-27 19:14 UTC, ruben1s commented on _layouts/project.html
> +function removeDuplicates(array) {
Removed

2020-05-27 19:16 UTC, ruben1s commented on _layouts/project.html
> +            if (projectTitle.toLowerCase().substring(0,4) === projectName.toLowerCase().substring(0, 4)
I reverted to an === and will wait for VRMS to change their data

2020-05-29 17:59 UTC, ruben1s commented on _layouts/project.html
> +// Assigns variable to each header by ID
Removed

2020-05-29 19:22 UTC, cnk commented on _layouts/project.html
> +            if (scheduleData == localData) {
Ok cool

2020-05-30 20:03 UTC, merged