Update Partner Text Under BallotNav Project
hackforla/website pull request #5572
Opened 2023-09-23 02:27 UTC by danielmshawn

Fixes #5410

### What changes did you make?
  - Within _projects/ballot-nav.md, removed line "partner: Code for America, Other Brigades"
  - Replaced line with "partner: Code for San Jose, Code for Atlanta, Open Oakland"

### Why did you make the changes (we will use this info to test)?
  - Simple and specific instructions from the issue

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>
<img width="395" alt="Screenshot 2023-09-14 at 5 53 27 PM" src="https://github.com/hackforla/website/assets/75091266/a9dd4036-5954-4cb8-8c76-8a2faa4b93a5">

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
<img width="398" alt="Screenshot 2023-09-14 at 6 14 33 PM" src="https://github.com/hackforla/website/assets/75091266/eb324421-3304-4968-86ad-1d54e1cc9698">

</details>

2023-09-23 03:47 UTC, A-Wu5 commented
Review ETA: 10 PM 9/22/23
Availability: 5-8 PM Monday

2023-09-23 03:54 UTC, A-Wu5 approved these changes
Everything looks good to me! The changes meet the criteria stated in the issue. Nice job!

2023-09-24 16:28 UTC, t-will-gillis requested changes
Hey @danielmshawn - Everything looks great- you have the correct branches, you are linking to the original issue, you are including relevant before and after screenshots, and your edits change only what needs to be changed. 

One minor request: On the description for what you did and why: the "what" section is good because it briefly describes the changes. On the "why" section, what we are looking for here is the reason that the changes needed to be made. This can be copied and/or summarized from the original issue, for example: "We need to remove mention of CfA from the list of partners on the Ballot Nav project" 

Otherwise, this is good to go- thanks!

2023-10-01 15:19 UTC, t-will-gillis commented
Hello @danielmshawn Checking in from last week- in case it was not clear, your PR is blocked from being merged until you make the requested changes or explain why the changes should not be made. Please let one of us know if you would like to discuss. Thank you!

2023-10-03 18:26 UTC, danielmshawn commented
Apologies, @t-will-gillis! I misread. Requested changes to the "Why" have been made, and I'll make sure to put the correct info there from now on. Thank you!!

2023-10-03 18:34 UTC, t-will-gillis approved these changes
Hey @danielmshawn No problem! Thanks for making the change

2023-10-03 18:34 UTC, merged