Removed mention of CfA from the Join Us page
hackforla/website pull request #5645
Opened 2023-10-02 06:27 UTC by YolandaHaynes

Fixes #5447 

### What changes did you make?
  - Removed and replaced the mention of Code for America to Civic Tech Structure. 
  - Updated href link to stripe donation page. 
  - Added clickable link on the donation image to the donation page.

### Why did you make the changes (we will use this info to test)?
  - To update the donation section of the join us page with current information by removing mention of CfA to Civic Tech Structure.
  - Updating the donation link to a Stripe donation page and making sure the image when clicked will go to the donation page.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

<img width="550" alt="Screenshot-before-change" src="https://github.com/hackforla/website/assets/12980710/ac1349b9-39ed-40f1-9499-bcdea9be4e75">

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
<img width="550" alt="Screenshot-after-changes" src="https://github.com/hackforla/website/assets/12980710/eca60aa2-e3f8-4257-83dd-b9565f5cbaf6">

</details>

2023-10-02 18:29 UTC, pdimaano commented
ETA: 10/4/23
Availability: Weekday evenings

2023-10-02 22:17 UTC, pdimaano approved these changes
@YolandaHaynes Good job: The branches are correct and the issue is linked. The changes are visible on my system on desktop, mobile and tablet. The correct files were changed and the links lead to the correct stripe donation page. I also see that the you changed the name for styling from "gif" to "png" since the image is now in a different format from the original. Well done!

2023-10-02 23:21 UTC, agutiernc commented
ETA: 10/03/23
Availability: EOD

2023-10-03 09:44 UTC, jaasonw requested changes
Looks good on my end, but I have some small accessibility nitpicks

Availability: 12pm - 6pm

2023-10-03 09:44 UTC, jaasonw commented on _includes/donation/donate-gif-text.html
> +  <a href="https://donate.stripe.com/bIY9Cpcg8dihfIc5kl" target="_blank" rel="noopener noreferrer"><img class="donation-png" src="/assets/images/about/donate-form.png" alt=""/></a>
Whenever possible, add some alt text because it helps visitors with screen readers access the site

2023-10-03 09:44 UTC, jaasonw commented on assets/images/about/donate-form.png
Would suggest using a jpg instead, pngs tend to be larger in filesize and can affect page load times

2023-10-03 09:44 UTC, jaasonw commented on _includes/donation/donate-gif-text.html
>      <ol>
Seeing as there is now only one step, does this still need to be an ordered list?

2023-10-04 00:05 UTC, YolandaHaynes commented on _includes/donation/donate-gif-text.html
> +  <a href="https://donate.stripe.com/bIY9Cpcg8dihfIc5kl" target="_blank" rel="noopener noreferrer"><img class="donation-png" src="/assets/images/about/donate-form.png" alt=""/></a>
Make sense! I just notice the previous code didn't have it, so I wasn't sure if I can just add in. But will be updating to add in the alt text.

2023-10-04 00:16 UTC, YolandaHaynes commented on assets/images/about/donate-form.png
Good to know about the load page time. In the overview section, the resource that was provided was in png format and I notice in the assests/images/about folder, the images in there was also in png format, so I just kept it same as. Is it best that I change this to jpg? Also for future reference, does HackForLA have a certain format they prefer?

2023-10-04 00:21 UTC, YolandaHaynes commented on _includes/donation/donate-gif-text.html
>      <ol>
I wondered about that as well. I just copied and paste the code that was in the instructions. Is there someone I can reach out to clarify? Or does this need to be a new ticket for a new change format? I'm not familiar what's the best way to move forward.

2023-10-04 01:29 UTC, jaasonw commented on assets/images/about/donate-form.png
I don't think there is; it's just good to keep image sizes small in general

2023-10-04 02:31 UTC, agutiernc approved these changes
The following are confirmed:

- Correct branch and linked issue
- Replaced code with the updated version
- Replaced the donation form graphic and is linked correctly
- Changes are shown in different view modes
- Confirmed before/after screenshots

You did an outstanding job @YolandaHaynes! Thanks for contributing.

As for making further changes than those listed, I'd recommend to follow the instructions and images as given.

If there are any questions or concerns, it's best to consult with the #hfla-site slack channel or a team lead. There are also more instructions on your _Pre-work Checklist_

2023-10-04 14:20 UTC, kwangric commented
Hi @jaasonw & @YolandaHaynes. The accessibility findings are good points to bring up, but they are not within the scope of the issue and can be addressed in future issues. We encourage devs to follow the action items in the original issue as closely as possible. As @agutiernc brought up, any findings can be brought up on the slack channel or directly with the merge team.

2023-10-04 19:41 UTC, jaasonw approved these changes
LGTM then 🚀

2023-10-05 00:15 UTC, merged