Updated Pre-work Instructions for Google Calendar Invites
hackforla/website pull request #5668
Opened 2023-10-06 22:58 UTC by agutiernc

Fixes #5629

### What changes did you make?
  -  Removed the instructions provided in the pre-work checklist regarding Google calendar invites

### Why did you make the changes (we will use this info to test)?
  -   In order to avoid confusion

### For Reviewers
- Use this URL to check the updated issue template: [URL to updated issue template](https://github.com/agutiernc/website/issues/new?assignees=&labels=Feature%3A+Onboarding%2FContributing.md%2Cprework%2Csize%3A+1pt%2Crole+missing%2CComplexity%3A+Prework&projects=&template=pre-work-template--dev.md&title=Pre-work+Checklist%3A+Developer%3A+%5Breplace+brackets+with+your+name%5D) 

### Screenshots of Proposed Changes Of The Website
<details>
<summary>Visuals before changes are applied</summary>

![before_screenshot](https://github.com/hackforla/website/assets/42459347/d420f987-20b6-4998-9ab8-e99c494391aa)

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
![after-screenshot](https://github.com/hackforla/website/assets/42459347/eefeadb9-ae23-4459-95ea-67746cf990a9)

</details>

2023-10-08 17:33 UTC, kezzaam commented
Availability: Sunday-Thursday around an hour each day - I have flexible working hours.
ETA: Thursday 12th Oct PST

2023-10-09 19:43 UTC, kwangric commented
Hey @brianf4! When you get the chance, please leave a comment with your availability and ETA for your review. Thanks!

2023-10-10 12:55 UTC, brianf4 commented
Availability: Tuesday - Friday 2pm - 8pm
ETA: Tuesday (today) EOD or Friday EOD

2023-10-10 23:00 UTC, kezzaam requested changes
Hi @agutiernc,

I can see you've handled everything as expected and the changes look good, well done!

Unfortunately there are conflicts, suggesting that the file has been updated in another issue since you made these changes.  
    Conflicting files:
    .github/ISSUE_TEMPLATE/pre-work-template--dev.md

You could try syncing your repo and pushing your branch again?
After that, click the button beside requested changes (under reviewers top right of this page) to re-request a review from me, so I know you've made changes.

Thankyou!

2023-10-11 03:09 UTC, brianf4 submitted a review, later dismissed
Hey @agutiernc I took a look at the changes and they look good to me. But unfortunately I got the same conflict message `Merge conflict in .github/ISSUE_TEMPLATE/pre-work-template--dev.md`

But as @kezzaam mentioned it seems like the file had been updated at the time of your pull request. Make sure to pull the latest changes into your local branch. After, manually edit the file to resolve the merge conflict.

2023-10-12 01:30 UTC, agutiernc commented
I resolved the conflicts and re-requested a review.
Thanks for letting me know @kezzaam and @brianf4!

2023-10-13 21:08 UTC, kezzaam commented
Hi @agutiernc, sorry but now I'm seeing the line that was meant to be removed in both the url to check, and the files changed. And there's some lines `<<<<<<< HEAD ` &  `>>>>>>> c78e6e3d (removed line regarding prework instructions for calendar invites) ` that I don't think should be there? 

<img width="621" alt="Screenshot 2023-10-14 at 9 59 57 AM" src="https://github.com/hackforla/website/assets/124431740/7b0e7bf7-466a-488d-9bfb-de35aa0063c4">

2023-10-14 01:33 UTC, agutiernc commented
> Hi @agutiernc, sorry but now I'm seeing the line that was meant to be removed in both the url to check, and the files changed. And there's some lines `<<<<<<< HEAD ` & `>>>>>>> c78e6e3d (removed line regarding prework instructions for calendar invites) ` that I don't think should be there?

Hi @kezzaam. I believe it's finally fixed as I removed those lines. It's been a learning experience and I appreciate your time in reviewing.

2023-10-14 02:30 UTC, kezzaam approved these changes
Hi @agutiernc!

Thanks for all your work on this issue! The changes look good to me, although there has been a few more changes since you began this issue, the line in question has been removed and the pre-work instructions make sense. Good job :)

2023-10-17 19:15 UTC, jaasonw approved these changes
looks good no more merge conflict 🚀

2023-10-18 03:43 UTC, t-will-gillis approved these changes
Hey @agutiernc - Great job all the way around: branches are correct, issue linked, good description, and relevant before and after screenshots. Thanks for working with @kezzaam and @brianf4 to resolve the merge conflict!

2023-10-18 03:45 UTC, merged