Added Rhoda Michael profile on guides team
hackforla/website pull request #5692
Opened 2023-10-10 06:11 UTC by sakibian

Fixes #5623 

### What changes did you make?
  - Added Rhoda Michael's profile on the guides team board

### Why did you make the changes (we will use this info to test)?
  - Information was not there, added a new name to the board

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

![image](https://github.com/hackforla/website/assets/40847839/c9a01b55-b8b6-44e1-9d61-76bbb9b9eea0)

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
![image](https://github.com/hackforla/website/assets/40847839/23e6475d-46ca-4856-a4cb-56d7df866b50)

</details>

2023-10-10 08:39 UTC, KyleA99 commented
Review ETA: 6 PM 10/10/23
Availability: 5-8 PM Tuesday

2023-10-10 18:13 UTC, KyleA99 approved these changes, later dismissed
Reviewed and approved.  Looks great @sakibian 

I am curious, is your "visuals before changes applied" image from the actual deployed website?  I'm assuming it is because it shows Sarah Levinen's profile, but the codebase does not have her profile info.  Might be a good practice to have your "visuals before changes applied" image taken from an initial docker build prior to any file changes, rather than taking screenshot from deployed site.  Not sure if this matters, just a thought.

2023-10-11 02:04 UTC, Thinking-Panda commented
Availability: Weekdays
ETA: 10/11

2023-10-12 03:17 UTC, sakibian commented
> Reviewed and approved. Looks great @sakibian
> 
> I am curious, is your "visuals before changes applied" image from the actual deployed website? I'm assuming it is because it shows Sarah Levinen's profile, but the codebase does not have her profile info. Might be a good practice to have your "visuals before changes applied" image taken from an initial docker build prior to any file changes, rather than taking screenshot from deployed site. Not sure if this matters, just a thought.

Yes @KyleA99, it is from the deployed site and when I try to `pull upstream` I don't see Sarah Levinen's profile in the code base. I thought I would get an updated code after using `pull upstream`.

2023-10-12 03:32 UTC, KyleA99 commented
@sakibian neither do I, I observed the same thing

2023-10-12 16:03 UTC, sakibian commented
That's interesting 🤨🤔

2023-10-12 19:08 UTC, Thinking-Panda requested changes
@sakibian , I had the same situation. Please check if your remote codebase has "Sarah Levine" listed. Then, try `git pull --rebase` on your `gh-pages` branch to make it up-to-date

2023-10-14 14:50 UTC, sakibian commented
@Thinking-Panda is it good this time?
![image](https://github.com/hackforla/website/assets/40847839/182d5c0a-c432-4f98-b915-acc6f20dde13)

2023-10-15 01:59 UTC, KyleA99 commented
@sakibian looks good to me.  I guess we were both pulling in git incorrectly

2023-10-15 02:45 UTC, sakibian commented
@KyleA99 That's not correct, we were using correct commands but for some reason our gh-pages hasn’t been updated, but after two days it fixed, May be levin's code contributer had merge conflict or something we unaware of.

2023-10-16 18:51 UTC, Thinking-Panda reviewed
@sakibian , Just checking, did you type in "Sara Levine" details or you pulled it from the published website codebase?

2023-10-16 19:04 UTC, Thinking-Panda commented
> @KyleA99 I think we weren’t wrong, we were using correct commands but for some reason our gh-pages wasn’t updating, may be updated code was missing, but after two days it gets fixed, May be Levin's code contributer had merge conflict or something we unaware of.

Levine's details were merged recently and that why this pull request has merge conflicts to be resolved. Resolving that will clear the PR to be approved. Helpful resource- https://github.com/hackforla/website/wiki/How-to-Resolve-Merge-Conflicts

2023-10-18 03:04 UTC, sakibian commented
> @sakibian , Just checking, did you type in "Sara Levine" details or you pulled it from the published website codebase?

After review changes request I did `git pull upstream gh-pages` saw the updated `guides-team.md` file added to my local. From here I did checkout to `sakibian:update-guides-team-profile-5623` branch here is my previous code was `pushed` and `pull requested` created here, and I just manually copy paste Sara Levin's
profile to my current branch and updated the code. [Updated here](https://github.com/hackforla/website/pull/5692/commits/6639b962cca2a8e3740ff30bbeb05e3c6d4e7b99 )

2023-10-18 03:41 UTC, sakibian commented
[5733](https://github.com/hackforla/website/pull/5733)

2023-10-18 05:34 UTC, closed without merging