resolve linter error in about-card-platform.html
hackforla/website pull request #5731
Opened 2023-10-17 18:26 UTC by jaasonw

fixes #5371

Fixes #replace_this_text_with_the_issue_number

### What changes did you make?
  - added closing span tag to `_includes/about-page/about-card-platform.html`
  
### Why did you make the changes (we will use this info to test)?
  - to resolve the linter issue in https://github.com/hackforla/website/issues/5371

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
no visual changes across all platforms (chrome, firefox, webkit, edge)

2023-10-18 02:24 UTC, DorianDeptuch commented
Availability: Weekday evenings
ETA: 10/18 EoD

2023-10-18 03:08 UTC, MattChau01 commented
Availability: Evenings
ETA: By EOD Friday

2023-10-19 05:09 UTC, DorianDeptuch requested changes
Hi @jaasonw,

You correctly stated why you made the changes, what changes were made, and linked the correct issue. You added the ending span tag in the correct position and I can confirm that no visual changes were made and that everything runs fine in my local environment.

However, It does appear that your code formatter changed the double quotes on line 1 to single quotes. Everything else looks great! If you can change the double quotes back then everything will be good to go. You can re-request my review and I will approve the PR.

2023-10-19 06:15 UTC, jaasonw commented
woah what the heck i did not see that, will fix

2023-10-20 02:45 UTC, mademarc commented
Review ETA: 10/19/2023
Availability: 7:45PM

2023-10-20 02:48 UTC, mademarc approved these changes
Hey @jaasonw good job changing the impact text to span on this issue

2023-10-20 17:09 UTC, MattChau01 approved these changes
- The branch is going into the correct branch `gh-pages`. ✅ 
- The original issue #5371 was properly referenced. ✅ 
- A closing span tag was properly added per original issue request. ✅ 

Great job @jaasonw !

2023-10-23 20:23 UTC, kwangric commented
Hey @DorianDeptuch, when you get the chance, can you leave a comment with the ETA for your review? Thanks!

2023-10-23 20:27 UTC, DorianDeptuch commented
Availability: Weekday afternoons
ETA: EoD 10/23

2023-10-23 20:29 UTC, DorianDeptuch approved these changes
Hey @jaasonw,

Great job on the changes! Everything looks good to me!

2023-10-23 20:38 UTC, merged