Fixed #5618
hackforla/website pull request #5744
Opened 2023-10-20 18:52 UTC by kevin31yu

Fixes #5618 

### What changes did you make?
  - Installed Code Spell Checker via VSCode
  - Created new branch and edited cspell.json, added "Westside" to the config file
  - Checked '_includes/events-page/our-locations-content.html' and no error message

### Why did you make the changes (we will use this info to test)?
  - There was an error message "Unknown word" for the word "Westside"
  -
  -

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

![image](Paste_Your_Image_Link_Here_After_Attaching_Files)

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
![image](Paste_Your_Image_Link_Here_After_Attaching_Files)

</details>

2023-10-21 04:23 UTC, freaky4wrld requested changes
Hey there @kevin31yu , here are some changes that you can do 
- In the reason for changes made section you have to empty bullets, remove those( dashes )
- In the visual changes remove the changes after and before section and instead mention `No visual changes`

Rest is cool, make these mentioned changes so that I can approve the PR.

2023-10-21 16:39 UTC, kevin31yu commented
> Hey there @kevin31yu , here are some changes that you can do
> 
> * In the reason for changes made section you have to empty bullets, remove those( dashes )
> * In the visual changes remove the changes after and before section and instead mention `No visual changes`
> 
> Rest is cool, make these mentioned changes so that I can approve the PR.

Hi, I have made the corrections. Thanks for your time.

2023-10-22 13:38 UTC, freaky4wrld approved these changes
hey @kevin31yu great work there, 

- the merging branch is correct
- the reason for changes is correctly mentioned
- the issue is correctly linked
- the specified changes are done correctly

Keep up the good work

2023-10-22 15:58 UTC, t-will-gillis approved these changes
Hey @kevin31yu Great job! You have the correct branches from and to, you are linked to the original issue, you have explained what you did and why, you mention that there are no visual changes to the website, and your code edits changes only what needs to be changed. 

Great job working with @freaky4wrld and congrats on your first PR!

2023-10-22 15:59 UTC, merged