replaced existing img tag with new one
hackforla/website pull request #5745
Opened 2023-10-20 21:50 UTC by Chrisklangley

Fixes #5620 

### What changes did you make?
  - on line 990 of the contributing.md file I replaced existing image tag with new one Via issue details 
  
  

### Why did you make the changes (we will use this info to test)?
For Reviewers: Do not review changes locally, rather, review changes at https://github.com/hackforla/website/blob/2e3c45fede99e61f479548ccca3f0dda83e351db/CONTRIBUTING.md#31-how-to-make-a-pull-request

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

<img src="https://user-images.githubusercontent.com/21162229/137784250-96281332-9231-4c5d-aba2-0d4c36521b82.jpg" alt="Making a comment visual example" />

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
<img src="https://user-images.githubusercontent.com/21162229/137784250-96281332-9231-4c5d-aba2-0d4c36521b82.jpg" alt="Making a comment visual example">

</details>

2023-10-20 21:57 UTC, jaasonw commented
eta: 10/20 eod
availability: 10/20 all day

2023-10-20 22:01 UTC, jaasonw requested changes
visually, it looks good to me but I added some suggestions and I also suggest
a. making the title more descriptive 
b. small nitpick but you didn't have to screenshot the code change
![image](https://github.com/hackforla/website/assets/8981287/80d6b614-2739-42d5-9ad9-6b636a64ed74)

2023-10-20 22:01 UTC, jaasonw commented on CONTRIBUTING.md
> -  <img src="https://user-images.githubusercontent.com/21162229/137784250-96281332-9231-4c5d-aba2-0d4c36521b82.jpg" alt="Making a comment visual example" />
you should re add the space here to keep the indentation consistent

2023-10-20 22:01 UTC, jaasonw commented on package-lock.json
> -  "lockfileVersion": 1
you might have accidentally committed this but this package-lock.json file isnt relevant to the pr

2023-10-20 22:43 UTC, Chrisklangley commented on CONTRIBUTING.md
> -  <img src="https://user-images.githubusercontent.com/21162229/137784250-96281332-9231-4c5d-aba2-0d4c36521b82.jpg" alt="Making a comment visual example" />
DO you mean a space between the details tag? Can you please explain what you mean? Thanks

2023-10-20 23:12 UTC, jaasonw commented on CONTRIBUTING.md
> -  <img src="https://user-images.githubusercontent.com/21162229/137784250-96281332-9231-4c5d-aba2-0d4c36521b82.jpg" alt="Making a comment visual example" />
referring to the space that was deleted here
![image](https://github.com/hackforla/website/assets/8981287/88bb60e3-3c5f-40c2-a7af-1f21821a1b24)

2023-10-21 05:11 UTC, jaasonw requested changes
your package-lock.json changes are still committed and it appears you undid your original changes
(see: https://github.com/hackforla/website/pull/5745/files)

2023-10-22 19:12 UTC, closed without merging