Added Sydney Walcoff to the expunge-assist.md File
hackforla/website pull request #5835
Opened 2023-11-04 05:31 UTC by jleung7158

Fixes #5760 

### What changes did you make?
  - Found the leadership variable and added the Sydney Walcoff text as a new entry for Expunge Assist project (_projects/expunge-assist.md)

### Why did you make the changes (we will use this info to test)?
  - We need to keep project information up to date so that visitors to the website can find accurate information.
  - Not sure how else to answer this personally besides *cue Patrick Star voice* "Because you told me to!" 

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
<details>
<summary>Visuals before changes are applied</summary>
<img width="956" alt="issue 5760 before changes" src="https://github.com/hackforla/website/assets/119633800/d789fb6b-06ad-46c0-bbfe-d722ac0cdf1e">
</details>

<details>
<summary>Visuals after changes are applied</summary>
<img width="954" alt="issue 5760 after changes" src="https://github.com/hackforla/website/assets/119633800/c238614a-fc46-4b31-935c-88219856517b">
</details>

2023-11-04 05:37 UTC, jleung7158 commented
i. Availability: Monday-Tuesday after 2PM, Wednesday-Friday after 7PM
ii. ETA: 1 week
created a new PR to solve this issue 5760 (prior PR was PR #5811)

2023-11-06 22:11 UTC, jackyuan1 submitted a review, later dismissed
- Correct branches
- Original issue is referenced
- Succinct and relevant description
- Screenshot showcases changes, but is not up to date with current website (not sure if this is an issue since the code itself is up to date when I run the container)
- Good job! Looks good besides the outdated screenshots

2023-11-07 20:10 UTC, LRenDO requested changes
Hi @jleung7158! Changes look great overall! Nice work!

I do still have one request. It looks like there were single quotes `''` added on line 57. Please remove those as they are not part of the issue and now appear on the website (see image below). Though it's non-functional, as @jackyuan1 said updating the images is also good practice to make sure only what is meant to be changed is affected.

Thanks!
![Screenshot (13)](https://github.com/hackforla/website/assets/59513509/80c5fcbb-3f57-45bf-bee8-0d2e7fd05562)

2023-11-08 02:54 UTC, Tomomi-K1 requested changes
@jleung7158  Thank you for fixing the branch name and creating this new pull request. 
correct branches are used, issue is attached. Great job!! 
As @LRenDO  mentioned, please remove '' on line 57.

2023-11-08 06:45 UTC, jleung7158 commented
### What changes did you make?
  - As requested, I have removed the two ' marks from line 57!

### Why did you make the changes (we will use this info to test)?
  - "Because you told me tooo!" 

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals after changes are applied</summary>
<img width="1307" alt="issue 5760 after marks removal" src="https://github.com/hackforla/website/assets/119633800/8d0fa7a9-688f-4f62-b78c-ddf3ae8fb18f">
</details>

2023-11-08 14:56 UTC, kwangric commented
Hey @jleung7158! Once you made the requested changes, don't forget to click on the arrows next to the reviewers names to re-request a review and let them know the PR is ready to be looked at. Thanks!
![image](https://github.com/hackforla/website/assets/43795498/a8cabf05-c44f-4e00-8413-8a9acb714c56)

2023-11-08 16:43 UTC, LRenDO approved these changes
Hi @jleung7158! Thanks for making the requested change and for contributing the site!

2023-11-11 06:30 UTC, jleung7158 commented
Progress: Just awaiting final review!
Blockers: None!
Availability: Monday-Tuesday after 2PM, Wednesday-Friday after 7PM
ETA: Most likely a few days!

2023-11-13 03:58 UTC, Tomomi-K1 approved these changes
@jleung7158  Thank you for working on this issue several times!! Sorry it took for a while for me to get to this review!! Great job!

2023-11-13 21:08 UTC, merged