Create Issue Template for adding github-handle to leadership member data in project file. #5541
hackforla/website pull request #5883
Opened 2023-11-08 02:54 UTC by JanineSooThow

Fixes #5541

### What changes did you make?
  -  Created an issue template for adding github-handle to leadership member data in project file with YAML frontmatter

### Why did you make the changes (we will use this info to test)?
  -  The aim of this issue was to demonstrate the new issue template by creating a new issue in my forked repo by making the issue branch the default branch on my fork. 

### For Reviewers
- Use this URL to check the updated issue template: [https://github.com/JanineSooThow/website/issues/1]

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

2023-11-08 03:00 UTC, JanineSooThow commented
Hello everyone, apologies this issue took me a long time to complete. I am not sure if I have done this right so please correct me with anything! It has been a long time since I have created a PR. In order to create this issue template I made this branch 'JanineSooThow:5541-create-issue-template-for-adding-github-handle-to-leadership-member-data-in-project-file' my default branch. I hope the URL to the issue template I have given works! Please correct all my issues :D (I am sure there are many!) Thank you kindly!

2023-11-08 19:37 UTC, allison-truhlar commented
ETA - Weds, Nov 8 EOD
Availability - most weekdays 9-5pm ET

2023-11-08 20:11 UTC, allison-truhlar requested changes, later dismissed
@JanineSooThow Good job with this PR! You have the merge request set up to and from the correct branches, and your link back to the original issue is working. Further, I can see the new md file in your branch and this is the only change you have made, as requested. Also, the link to your test issue is working - nice job! My only comments are some minor formatting changes to make the issue template appear more closely styled to the template Roslyn wrote out. I left these as inline comments in the "files changed" tab, rather than writing them all out in a comment - I thought they might be easier to follow that way.

2023-11-08 20:11 UTC, allison-truhlar commented on .github/ISSUE_TEMPLATE/add-github-handle.md
> +# Add new variable github-handle to member [INSERT MEMBER NAME] in [INSERT PROJECT FILE]
Looking at how other issues appear, I think this title is meant to be left out of the template, since it appears in the front matter above and will therefore appear in the "title" position of the issue (above the body of the issue).

2023-11-08 20:11 UTC, allison-truhlar commented on .github/ISSUE_TEMPLATE/add-github-handle.md
> +2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide.](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f871
Very minor - the period at the very end of this line, after the close parentheses, is an extra period and can be deleted.

2023-11-08 20:11 UTC, allison-truhlar commented on .github/ISSUE_TEMPLATE/add-github-handle.md
> +We need to create a single variable github-handle to hold the github handle for each member of the leadership team. Eventually github-handle will replace the github and picture variables, reducing re
Change to match template - specifically, add back-ticks around all instances of github-handle, and github and picture in the second sentence: We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team.  Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.

2023-11-08 20:11 UTC, allison-truhlar commented on .github/ISSUE_TEMPLATE/add-github-handle.md
> +- [ ] Open the file [INSERT PATH TO PROJECT FILE] in the IDE
Change to match template: - [ ] Open the file `_projects/[PROJECT FILE]` in the IDE

2023-11-08 20:11 UTC, allison-truhlar commented on .github/ISSUE_TEMPLATE/add-github-handle.md
> +- [ ] Replace
Add : at the end of Replace to match template

2023-11-08 20:11 UTC, allison-truhlar commented on .github/ISSUE_TEMPLATE/add-github-handle.md
> +- [ ] Do not use a tab to indent github-handle. YAML doesn't allow tabs; it requires spaces.
Add back-ticks around github-handle to match template.

2023-11-08 20:11 UTC, allison-truhlar commented on .github/ISSUE_TEMPLATE/add-github-handle.md
> +```
Delete the triple back-ticks on lines 31 and 32 to remove the empty code-styled line.

2023-11-08 20:11 UTC, allison-truhlar commented on .github/ISSUE_TEMPLATE/add-github-handle.md
> +```
Delete the triple back-ticks on lines 35 and 36 to remove the empty code-styled line.

2023-11-08 20:11 UTC, allison-truhlar commented on .github/ISSUE_TEMPLATE/add-github-handle.md
> +- [ ] Release the dependency for this issue in [Epic: Create issues to add github-handle to leadership teams #5441](https://github.com/hackforla/website/issues/5441). If all the dependencies have bee
The styling of the Epic link doesn't look quite the same as in the template. It looks like the template just has #5441 instead of the full link written out? I'm not sure if that will change the styling. But the link works correctly, so I'm not sure if this is a big deal.

2023-11-08 20:11 UTC, allison-truhlar commented on .github/ISSUE_TEMPLATE/add-github-handle.md
> +- This issue is part of Epic: [Create issues to add github-handle to leadership teams #5441](https://github.com/hackforla/website/issues/5441)
The styling of the Epic link doesn't look quite the same as in the template. It looks like the template just has #5441 instead of the full link written out? I'm not sure if that will change the styling. But the link works correctly, so I'm not sure if this is a big deal.

I would make this match the link above though, by putting Epic: inside the brackets.

2023-11-11 02:42 UTC, JanineSooThow commented on .github/ISSUE_TEMPLATE/add-github-handle.md
> +# Add new variable github-handle to member [INSERT MEMBER NAME] in [INSERT PROJECT FILE]
Hi @allison-truhlar I have removed the title as requested

2023-11-11 02:42 UTC, JanineSooThow commented on .github/ISSUE_TEMPLATE/add-github-handle.md
> +2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide.](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f871
@allison-truhlar I have removed the extra period :)

2023-11-11 02:43 UTC, JanineSooThow commented on .github/ISSUE_TEMPLATE/add-github-handle.md
> +We need to create a single variable github-handle to hold the github handle for each member of the leadership team. Eventually github-handle will replace the github and picture variables, reducing re
@allison-truhlar Thank you so much for this advice! I actually didn't know how to make it appear like the template. Good learning for me!

2023-11-11 02:43 UTC, JanineSooThow commented on .github/ISSUE_TEMPLATE/add-github-handle.md
> +- [ ] Open the file [INSERT PATH TO PROJECT FILE] in the IDE
@allison-truhlar completed

2023-11-11 02:44 UTC, JanineSooThow commented on .github/ISSUE_TEMPLATE/add-github-handle.md
> +- [ ] Replace
@allison-truhlar completed

2023-11-11 02:44 UTC, JanineSooThow commented on .github/ISSUE_TEMPLATE/add-github-handle.md
> +- [ ] Do not use a tab to indent github-handle. YAML doesn't allow tabs; it requires spaces.
@allison-truhlar done :)

2023-11-11 02:45 UTC, JanineSooThow commented on .github/ISSUE_TEMPLATE/add-github-handle.md
> +```
@allison-truhlar Thank you for pointing this out :D Have removed the triple back-ticks as requested

2023-11-11 02:45 UTC, JanineSooThow commented on .github/ISSUE_TEMPLATE/add-github-handle.md
> +```
@allison-truhlar done

2023-11-11 02:45 UTC, JanineSooThow commented on .github/ISSUE_TEMPLATE/add-github-handle.md
> +- [ ] Release the dependency for this issue in [Epic: Create issues to add github-handle to leadership teams #5441](https://github.com/hackforla/website/issues/5441). If all the dependencies have bee
@allison-truhlar yea I actually ahd trouble styling this part. I wasn't sure how to do it to closely match the template..

2023-11-11 02:46 UTC, JanineSooThow commented on .github/ISSUE_TEMPLATE/add-github-handle.md
> +- This issue is part of Epic: [Create issues to add github-handle to leadership teams #5441](https://github.com/hackforla/website/issues/5441)
@allison-truhlar have put Epic inside the brackets as requested

2023-11-11 02:52 UTC, JanineSooThow commented
@allison-truhlar Hello Allison! Thank you so much for reviewing this PR I hope the changes I have made have come through mainly because when I committed the changes on the [5541-create-issue-template-for-adding-github-handle-to-leadership-member-data-in-project-file](https://github.com/JanineSooThow/website)  branch and refreshed the page that contains the issue template, the changes did not come through...which was very strange, so I had to go and modify the changes again on the page containing my issue template https://github.com/JanineSooThow/website/issues/1 

 My code is not in an IDE. I mainly created this issue template on GitHub...I hope I did the right thing...please let me know if I missed a step. Thank you!

2023-11-13 04:46 UTC, freaky4wrld commented
Availability: Evenings
ETA: EOD Wednesday 11/15

2023-11-14 20:49 UTC, roslynwythe commented on .github/ISSUE_TEMPLATE/add-github-handle.md
> +We need to create a single variable github-handle to hold the github handle for each member of the leadership team. Eventually github-handle will replace the github and picture variables, reducing re
@JanineSooThow thank you for fixing that detail.  My guess is that the back-ticks were lost because you copied the rendered markdown instead of the source markdown.  In the future, to avoid this, you can go into Edit mode and then copy the source.  

Thank you @allison-truhlar for an excellent review.

2023-11-15 01:12 UTC, roslynwythe submitted a review, later dismissed
@JanineSooThow thank you for creating a well-formed and descriptive PR and for resolving issues as they have arisen.

I would like to understand your comments better so that if necessary, I can improve the instructions we provide in future issues.   I have always created templates in my IDE, but I understand that the instructions in the doc you referenced use a different method, in which the template is created in the GitHub IDE.  I apologize if there is something in the issue instructions or the testing instructions that was incorrect or confusing.   If that is the case please let me know.  

I agree with the changes suggesed by @allison-truhlar .  Regarding those changes, are you saying that after updating the template markdown file with those changes, they were not reflected in the issue template in your repository?  Note that the link you provided is to an issue that has already been created and we could not expect template updates to be reflected in existing issues, so it would be expected that you would have to create a new issue for testing.  It looks like you've done that and it looks good, so I'm approving the PR.

2023-11-15 01:35 UTC, JanineSooThow commented
> @JanineSooThow thank you for creating a well-formed and descriptive PR and for resolving issues as they have arisen.
> 
> I would like to understand your comments better so that if necessary, I can improve the instructions we provide in future issues. I have always created templates in my IDE, but I understand that the instructions in the doc you referenced use a different method, in which the template is created in the GitHub IDE. I apologize if there is something in the issue instructions or the testing instructions that was incorrect or confusing. If that is the case please let me know.
>  Hi @roslynwythe thank you so much for your reply and feedback! I don't think your instructions are confusing at all. I think what happens is that I tend to get my words and sentences in English mixed up and jumbled which can make it difficult for me to understand/process instructions so I have to ask for more clarification :D Also, because the technical terminology is sometimes difficult, I am trying to get used to it. I appreciate you taking the time to help me with this issue. I definitely learnt alot and feel better that I managed to create an issue for the first time! Thank you! 

> I agree with the changes suggesed by @allison-truhlar . Regarding those changes, are you saying that after updating the template markdown file with those changes, they were not reflected in the issue template in your repository? Note that the link you provided is to an issue that has already been created and we could not expect template updates to be reflected in existing issues, so it would be expected that you would have to create a new issue for testing. It looks like you've done that and it looks good, so I'm approving the PR.

@roslynwythe Yes that is correct. I could not see the changes reflected in my issue template after modifying the template markdown file and thought it would update automatically :)

2023-11-15 10:35 UTC, freaky4wrld commented
Hey there @JanineSooThow great work with completing the specified changes by @allison-truhlar, the PR looks fine to me the from/to branch is correct, the desired additions are done as mentioned in the linked issue, the corrections are made correctly and can be viewed by making a new issue by you. 
Just a query in the Resource and Instruction column you have used 'For QA to validate change' instead of `Project Markdown File` mentioned in Roslyn's template , can I know why ?

2023-11-15 23:44 UTC, JanineSooThow commented
> Hey there @JanineSooThow great work with completing the specified changes by @allison-truhlar, the PR looks fine to me the from/to branch is correct, the desired additions are done as mentioned in the linked issue, the corrections are made correctly and can be viewed by making a new issue by you. Just a query in the Resource and Instruction column you have used `For QA to validate change` instead of `Project Markdown File` mentioned in Roslyn's template , can I know why ?

Hello @freaky4wrld , thank you for the feedback! I believe the reason I had 'For QA to validate change:' is because I took up the issue on the 9th October and this was in the original template and then Roslyn updated it on the 16th October. I can change it if you want?

2023-11-16 06:24 UTC, freaky4wrld submitted a review, later dismissed
@JanineSooThow since Roslyn had approved it, then works with me too...... great work with implementing the changes addressed by Allison, I approve this. 
You can re-request a review by @allison-truhlar, by pressing the `round-arrow-cycle icon` next to her `profile-image` in the `Reviewer` column

2023-11-29 23:43 UTC, LRenDO requested changes
Hi @JanineSooThow!
Great job with this pull request and working through the changes that @allison-truhlar requested!

- The branching was done correctly
- Issue number was listed
- The PR title is descriptive of the changes
- Changes were made correctly in the code
- Changes appear correctly on the issue template in your repo.
- The PR request clearly states what was updated

I have a couple non-functional requests related to the Epic links.  When you're done updating them as described below, you can click the circle with the arrows next to my name in the reviewers section to request a re-review.
- [ ] I left two inline comments to help resolve the formatting issue for the link to the Epic that is still showing up on the template in your repo.

Though not essential, these are a couple minor changes that would clean up the PR comment a bit. Adding `No visual changes` at the end would add a little clarity and replacing the URL with `[Updated Template](https://github.com/JanineSooThow/website/issues/new?assignees=&labels=P-Feature%3A+Project+Info+and+Page%2C+good+first+issue%2C+ready+for+dev+lead%2C+role%3A+back+end%2FdevOps%2C+role%3A+front+end%2C+size%3A+0.25pt&projects=&template=add-github-handle.md&title=Add+github-handle+for+%5BINSERT+NAME%5D+in+%5BINSERT+PROJECT+FILE%5D)`

Again, great work and thanks for taking the time to contribute to the website and make these updates!

2023-11-29 23:43 UTC, LRenDO commented on .github/ISSUE_TEMPLATE/add-github-handle.md
> +- [ ] Release the dependency for this issue in [Epic: Create issues to add github-handle to leadership teams](https://github.com/hackforla/website/issues/5441)#5441. If all the dependencies have been
The formatting issue for the Epic can be fixed by replacing `[Epic: Create issues to add github-handle to leadership teams #5441](https://github.com/hackforla/website/issues/5441)` with `#5441`.

2023-11-29 23:43 UTC, LRenDO commented on .github/ISSUE_TEMPLATE/add-github-handle.md
> +- This issue is part of [Epic: Create issues to add github-handle to leadership teams #5441](https://github.com/hackforla/website/issues/5441)
For this one, the formatting issue can be fixed by replacing `[Epic: Create issues to add github-handle to leadership teams #5441](https://github.com/hackforla/website/issues/5441)` with `#5441`.

2023-12-01 18:29 UTC, JanineSooThow commented on .github/ISSUE_TEMPLATE/add-github-handle.md
> +- [ ] Release the dependency for this issue in [Epic: Create issues to add github-handle to leadership teams](https://github.com/hackforla/website/issues/5441)#5441. If all the dependencies have been
awesome thank you! have done this as requested.

2023-12-01 18:29 UTC, JanineSooThow commented on .github/ISSUE_TEMPLATE/add-github-handle.md
> +- This issue is part of [Epic: Create issues to add github-handle to leadership teams #5441](https://github.com/hackforla/website/issues/5441)
done :)

2023-12-02 01:08 UTC, LRenDO approved these changes
Hi @JanineSooThow! Looks great! Thanks for taking the time to make the updates!

2023-12-02 01:16 UTC, merged