Refactor Slack image icon with svg icon in communities of practice page
hackforla/website pull request #5896
Opened 2023-11-13 08:46 UTC by aadilahmed

Fixes #5829

### What changes did you make?
  - Replaced img tag for the "Join Slack Channel" button icon with a liquid image element referencing _includes/svg/icon-slack.svg
  - Modified CSS to maintain current appearance of page

### Why did you make the changes (we will use this info to test)?
  - To make sure that only a single slack icon svg is used in the codebase
  - Make it easier to render the svg in various colors throughout the website

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

<img width="947" alt="communities-of-practice-before" src="https://github.com/hackforla/website/assets/15069166/8e0f61f1-b867-4c7a-806f-145a0bcb61d2">

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
<img width="947" alt="communities-of-practice-after" src="https://github.com/hackforla/website/assets/15069166/bc94e1f3-69f9-45c9-85ca-3384ea28501e">

</details>

2023-11-14 20:16 UTC, roslynwythe requested changes

2023-11-14 20:16 UTC, roslynwythe commented on pages/communities-of-practice.html
> +                        <svg class="button-icon" id="slack-icon" alt="slack icon" viewBox="0 0 100 100">
Great work @aadilahmed - the appearance of the svg is idenitcal to the previous image, as desired.  And the PR is setup correctly and is descriptive.  

 I appreciate the effort to provide alternative text for the svg image, but I don't believe that "alt" is a recognized attribute of svg and in my testing your branch, the alt attribute was not effective on svg.  No alt text is displayed and there is no "accessible name" for the image.  Therefore I suggest removing that attribute, and in a separate issue we will apply a technique for making inline svg elements accessible.  

And just a question: please explain the reason for the outer svg element.  Was it done for the purpose of overriding the id in the svg file, for the purpose of applying styles, or for other reasons as well ?

2023-11-15 06:14 UTC, aadilahmed commented on pages/communities-of-practice.html
> +                        <svg class="button-icon" id="slack-icon" alt="slack icon" viewBox="0 0 100 100">
Thank you for reviewing my pull request. I included the outer svg element tag for the purpose of applying styles to the image, but I've removed it so now only the liquid includes tag is used. In the .scss file I applied the style attributes to the original svg id, "Layer_1". I've pushed the new code to the pull request.

2023-11-15 07:38 UTC, roslynwythe approved these changes
Excellent job @aadilahmed.  The PR has well-formed branches, descriptive text and screenshots.  The code is correct and clean and it looks great in the browser.  Thank you!

2023-11-16 00:13 UTC, agutiernc commented
Review ETA: EOD of 11/16/23
Availability: After 6pm

2023-11-18 03:40 UTC, agutiernc approved these changes
I confirm the following:
- Correct branch and linked issue
- Correct code to display the slack icon
- Changes render in different view modes
- Screenshots display the changes correctly

Outstanding job @aadilahmed! Thanks for contributing!

2023-11-19 19:19 UTC, merged