Update Project Profile: Lucky Parking (Remove Sijia Pitts)
hackforla/website pull request #5904
Opened 2023-11-14 22:00 UTC by djbradleyii

Fixes #5800

### What changes did you make?
  - Removed Sijia Pitts from the lucky-parking.md

### Why did you make the changes (we will use this info to test)?
  - We need to keep project information up to date so that visitors to the website can find accurate information.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

![before](https://github.com/hackforla/website/assets/52722401/508b6ba4-efa0-45b0-889a-ca6c0c962466)

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
![after](https://github.com/hackforla/website/assets/52722401/52be59fc-aba4-47a7-afe7-b5420a21d470)

</details>

2023-11-15 09:30 UTC, KyleA99 requested changes
See inline comment regarding single/double quotes.

I'll review again once these issues are fixed

2023-11-15 09:30 UTC, KyleA99 commented on _projects/lucky-parking.md
> -identification: '216854923'
I dont believe we are supposed to change these to double quotes (not sure if this was done by a linter?).  The only changes for this PR should be what is detailed in the action items of issue #5800 

Please correct for each change

2023-11-15 18:17 UTC, djbradleyii commented on _projects/lucky-parking.md
> -identification: '216854923'
Oh no! Lint strikes again. I will make the update and re-request a review. Good catch.

2023-11-16 00:10 UTC, LRenDO commented
Hi @mademarc! Thanks for volunteering to review this issue! When you have a minute, please add your ETA and Availability. If for some reason you find that you're unable to review the request, please remove yourself as a reviewer. Thanks!

2023-11-17 03:10 UTC, mademarc commented
Review ETA: 11/16/2023
Availability: 7:10PM

2023-11-17 03:18 UTC, mademarc approved these changes, later dismissed
Hey @djbradleyii good call on the changes for lines 58-63 and also on the adding of the double quotes either with or without linter.

2023-11-19 18:45 UTC, djbradleyii commented
@KyleA99 good catch. I fixed the issue. Let me know if you notice anything else.

2023-11-23 19:50 UTC, KyleA99 approved these changes, later dismissed
@djbradleyii changes look great.  Thank you for the great work!

2023-11-26 22:39 UTC, t-will-gillis requested changes
Hey @djbradleyii Great job on your first PR.
- Branches from/ to are good
- Linked back to original issue
- There is a concise description of what was done and why
- Relevant 'before' and 'after' screenshots are shown
- The code edits only change what needs to be changed

Everything looks good on your end- thanks!

You'll notice below that there is a merge conflict on this PR. If you have not seen this before, it just means that other people were working on the same file as you so the branch you started with is out of date. It is relatively easy to fix: First select "Resolve conflicts". The conflicts are shown on the next screen:
<details>
<summary>Merge conflicts</summary>

<img width="893" alt="Screenshot 2023-11-26 143153" src="https://github.com/hackforla/website/assets/40799239/70515107-5da5-4993-b123-88cedfb03ecf">

</details>

Your branch is showing 'Jodie Chen' and 'Yujin Chang' in Lucky Parking still, but if you look at #4909 these two have been removed by other issues. To resolve the conflict, you will want to delete these two profiles, so everything from lines 46-66. When done, select "Mark as resolved" and this should take care of the conflicts flag. 

When you are done, select the chasing arrows next to my name to "re-request review".

Thanks for working on this issue!

2023-11-28 01:47 UTC, djbradleyii commented
@KyleA99 Now that the edits have been made, can you please approve the PR? Thanks.

2023-11-28 01:48 UTC, t-will-gillis approved these changes
Hey @djbradleyii - Awesome, thanks for fixing the merge conflict!

2023-11-28 01:50 UTC, merged