Change Clickable Area from Arrow to Filter Section Heading
hackforla/website pull request #5908
Opened 2023-11-15 19:24 UTC by raviteja4117

Fixes #5770 

### What changes did you make?
  -  Changed the clickable area for a filter section from the arrow to the filter section heading

### Why did you make the changes (we will use this info to test)?
  - To keep the clickable area consistent without the use of images/svgs.
  

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

![image]( 
![Screen Recording 2023-11-15 at 2-2](https://github.com/hackforla/website/assets/129820906/d39e031b-b6ee-4a0b-b89f-019f6bbc57e6)
)

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
![image](
![Screen Recording 2023-11-15 at 2](https://github.com/hackforla/website/assets/129820906/740c500e-6252-487b-8463-c21e3a853530)
)

</details>

2023-11-16 01:41 UTC, KyleA99 commented
Availability: M-F, 5-8 PM
ETA: 11/18/23 EOD

2023-11-16 04:11 UTC, Chrisklangley commented
Availability: weekday 5-8 PM
ETA: 11/18/23 EOD

2023-11-17 01:43 UTC, KyleA99 requested changes
@raviteja4117 
- Your PR is done with the correct branch.
- The logic you implemented appears to work as intended.  The only issue I saw is that on the "Toolkit" page, in the contributors section, when the user clicks on the red "view all" link, it incorrectly collapses the filter section (user must re-open the filter section to see the new total-list of contributors.  If this is unclear, feel free to message me on slack.

Please see the image of the "View all" link below:
<img width="708" alt="Screenshot 2023-11-16 at 5 42 48 PM" src="https://github.com/hackforla/website/assets/106561238/5f5b9391-966f-475d-8eeb-dd69423585d0">

2023-11-18 22:28 UTC, raviteja4117 commented
Hi, @KyleA99 

Thank you for bringing this to my attention. I appreciate your feedback. I've now fixed the issue, and clicking on the "view all" link in the contributors section on the "Toolkit" page should no longer incorrectly collapse the filter section.

2023-11-19 00:59 UTC, Chrisklangley approved these changes
Hey @raviteja4117 
•visually everything looks good
• the changes you made your great and your code looks line

Great job

2023-11-19 01:53 UTC, KyleA99 approved these changes
@raviteja4117 everything looks great to me now, thank you for the revision and great work

2023-11-20 18:40 UTC, merged