updated the slack img.
hackforla/website pull request #5920
Opened 2023-11-17 22:14 UTC by GRK1998

Fixes #replace_this_text_with_the_issue_number

### What changes did you make?
 modify the Communities of Practice page, replacing the current image with the inline SVG

### Why did you make the changes (we will use this info to test)?
 storing only a single Slack icon SVG file in the codebase and matching the appearance of the current image.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>
<img width="1511" alt="Screenshot 2023-11-17 at 4 42 10 PM" src="https://github.com/hackforla/website/assets/97300861/603e1365-dfc5-4357-a93e-2d70f5eb8ac2">

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
<img width="1510" alt="Screenshot 2023-11-17 at 4 55 12 PM" src="https://github.com/hackforla/website/assets/97300861/88b415dc-4834-441e-839c-9850834270f4">

</details>

2023-11-19 07:49 UTC, ajb176 commented
Please make sure to add the issue number, if that isn't done the issue isn't linked and the PR can't be reviewed

2023-11-19 08:14 UTC, ajb176 requested changes
PR can't be reviewed until the issue number is added

2023-11-21 17:17 UTC, GRK1998 commented
Hi @ajb176 I have updated the issue number. If there are any additional changes to be made, please let me know.

2023-11-22 03:42 UTC, sornekian commented
Review ETA: 2PM 11/22/23
Availability: Wednesday 10-5 PM

2023-11-22 07:41 UTC, ajb176 commented
Yes, I'm aware of the issue number of the pull request, I was hoping for the linked issue number

2023-11-22 20:47 UTC, sornekian reviewed
Changes look simple and clean, just need that lint error fixed.

2023-11-23 08:13 UTC, ajb176 requested changes
Correct linked issue number still needs to be added

What was added was the issue number of the PR itself

2023-11-25 19:23 UTC, GRK1998 commented
Hi @ajb176 I have updated the issue number, and i quite did not get the lint error code so Could you please let me know what needs to be done.

2023-11-26 00:00 UTC, t-will-gillis commented
Hi @GRK1998 - when you make changes to your PR, please remember that you'll need to re-request the reviewers by selecting the chasing arrows next to their names:
<img width="446" alt="Screenshot 2023-11-25 155731" src="https://github.com/hackforla/website/assets/40799239/c27faced-e72f-4103-af9d-9862e80af2c5">

Also @sornekian and @ajb176 Please disregard the "Lint SCSS / Lint SCSS (pull_request)" test- there is an issue with the linter that we need to correct.

2023-11-26 12:46 UTC, ajb176 commented
Tagging the original issue creator @roslynwythe 

I'm seeing very different visuals in different browsers. The PR creator increased the width and height of the SVG icon from 24px to 80px. In Firefox (and whatever browser the creator is using) this seems to essentially match the current version of the website, while the 24px version looks tiny. In Safari, the 80px version looks massive, whereas the 24px looks accurate. I'd like some other people to review this, but it seems like replacing the SVG is introducing some irregularities. 

Here's what I'm seeing: 

<details>
<summary>Changes on Firefox: </summary>
<img width="569" alt="FireFoxIcon" src="https://github.com/hackforla/website/assets/19783179/edaf7a7e-7aad-4579-b178-d50c55b73aa1">
</details>

<details>
<summary>Changes on Safari: </summary>
<img width="560" alt="SafariIcon" src="https://github.com/hackforla/website/assets/19783179/890433c2-75dd-4251-8067-7ac698e3546a">
</details>

2023-11-26 12:51 UTC, ajb176 commented
Hey @sornekian 

I noticed you reviewed the PR before the PR creator added the linked issue number. If you dug up the initial linked issue manually and cross-checked the PR with it, that's great. Otherwise, you can't properly review a PR without cross-checking with the linked issue and making sure the changes by the PR creator line up with the instructions of the linked issue. 

If you haven't already, you'll need to pull the changes to a local branch and run them in docker. Please do so, view the changes in a few different browsers and let me know if what you find lines up with my comment above, or if maybe I'm mistaken.

2023-11-28 08:30 UTC, roslynwythe commented
@ajb176 I'm really glad you tested in Safari so you could discover the cross-browser issue.  I suggest that you do more research regarding browser support for svg styling and sizing methods and also see this PR which addresses a issue similar to yours:  https://github.com/hackforla/website/pull/5900   One of the files changed in that PR is pages/getting-started.html and the developer created an `svg` element that wraps the included svg, and makes use of the 'viewBox' attribute of the outer svg element for scaling.   Perhaps using that technique would provide cross-browser results.  If you would be willing to do a review that issue and so some cross-browser testing and comment on your results, that would be great.

2023-12-02 18:04 UTC, ajb176 commented
@roslynwythe Yeah, using a viewbox seems like it should do the trick. I'm a little busy right now but I'll definitely look into that PR within a week.

2024-01-17 20:23 UTC, sornekian reviewed
Hey @GRK1998, I don't see any revisions after @ajb176 comments with the sizing issue on different browsers. Please update.

2024-01-18 09:15 UTC, roslynwythe commented
@GRK1998 if you are able to update this PR as discussed above, please leave a comment describing your progress, availability and ETA.  Otherwise, please let me know so I can make the issue available to another developer.

2024-01-18 16:04 UTC, GRK1998 commented
@roslynwythe Apologies for the delay. I have unassigned myself from the issue. Feel free to reassign it to another developer, as I am currently working on other issues.

2024-01-19 06:25 UTC, jphamtv commented
The developer unassigned themself from the PR and issue. I moved the issue back to the top of the Prioritized backlog.

2024-01-19 06:25 UTC, closed without merging