Adjusting padding in drop down menu for filters
hackforla/website pull request #5942
Opened 2023-11-29 02:16 UTC by Jfong1218

Fixes #replace_this_text_with_the_issue_number

### What changes did you make?
  - Adjusted padding values in _dropdown_filters.scss  to make sure filter items are not covered by buttons on the bottom when in smartphone/tablet views

### Why did you make the changes (we will use this info to test)?
  - Per requested in the issue #5333
  - When filter drop down menus is fully expanded certain selections are covered by buttons on the bottom.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

<img width="392" alt="截圖 2023-11-28 下午6 14 29" src="https://github.com/hackforla/website/assets/109251936/416b6015-9a4e-4dc1-90c7-57128a614b8f">

</details>

<details>
<summary>Visuals after changes are applied</summary>

<img width="392" alt="截圖 2023-11-28 下午6 14 48" src="https://github.com/hackforla/website/assets/109251936/834017f7-6899-44f5-846e-4b54184405a1">

</details>

2023-11-30 00:14 UTC, LRenDO commented
Hi @colin-macrae and @soleilherring! Thanks for volunteering to review this issue! When you have a minute, please add your ETA and Availability. Thanks!

2023-11-30 05:29 UTC, colin-macrae commented
ETA:  Thursday, 11/29
Availability:  2+ hours on 11/29 and 6+ hours this week

2023-11-30 21:10 UTC, soleilherring commented
ETA: Thursday, 11/30
Availability: 2+ hours on 11/30 and 3+ hours during rest of week

2023-11-30 21:13 UTC, soleilherring commented
Hi @Jfong1218 can you please put the issue number here "Fixes #replace_this_text_with_the_issue_number" so for example,  "Fixes #5333"  for this pull request. After that, it will be easier to check!

2023-12-01 00:53 UTC, colin-macrae commented
Hi @Jfong1218 .  It looks like you did a great job with the changes, but I cannot tell for sure since I cannot check based on the original issue assinged to you.  As mentiond by @soleilherring, please go to the issue assigned to you and find the issue number, and link it by copy/pasting it into your above comment.  

Your comment, here:  
![image](https://github.com/hackforla/website/assets/122063836/a6d23c60-c799-4692-89f1-a3bb671dde02)

Should look like this:  
![image](https://github.com/hackforla/website/assets/122063836/ca4fb340-e16b-4b99-82dc-7bbfa929879c)

If you need further help on this, read here: 
https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

Thank you!

2023-12-05 00:04 UTC, Jfong1218 commented
I've updated the issue number with the description above

2023-12-07 21:07 UTC, colin-macrae reviewed
Hi @Jfong1218 , this looks like the right area for the fix, but perhaps 65px would work better for padding-bottom.  Please see my conversation comments.

2023-12-08 01:53 UTC, Jfong1218 commented
upon further testing I also agree that 65 px for the padding may look better on the drop down menu options. I have updated the PR to reflect this.

Thank you

2023-12-12 20:51 UTC, colin-macrae requested changes
Hi @Jfong1218 - Thanks for the changes : ) I think we are getting closer.  But, one issue.  What we want is `padding: 0 12px 65px;`.  If we do it this way, since padding-left has no value assigned, it defaults to the same as the right side (12px).  That is what we want.  

But, if you give a value of 0 for padding-left, as you did, like this: `padding: 0 12px 65px 0;` it will take away the padding-left. 

So we actually have two options, either: 
`padding: 0 12px 65px;`  or 
`padding: 0 12px 65px 12px;`

The two will give us the same thing: padding-left and padding-right of 12px, which we need. 

In addition, it looks like the Lint SCSS didn't pass the Github checks.  You might also want to see if that needs sorting out as well. 

Thanks @Jfong1218 , and I'll take another look after the changs are made.  Please let me know if you think I have overlooked anything.

2023-12-20 02:47 UTC, Jfong1218 commented
> Hi @Jfong1218 - Thanks for the changes : ) I think we are getting closer. But, one issue. What we want is `padding: 0 12px 65px;`. If we do it this way, since padding-left has no value assigned, it defaults to the same as the right side (12px). That is what we want.
> 
> But, if you give a value of 0 for padding-left, as you did, like this: `padding: 0 12px 65px 0;` it will take away the padding-left.
> 
> So we actually have two options, either: `padding: 0 12px 65px;` or `padding: 0 12px 65px 12px;`
> 
> The two will give us the same thing: padding-left and padding-right of 12px, which we need.
> 
> In addition, it looks like the Lint SCSS didn't pass the Github checks. You might also want to see if that needs sorting out as well.
> 
> Thanks @Jfong1218 , and I'll take another look after the changs are made. Please let me know if you think I have overlooked anything.

Upon reviewing i think adding in the left padding will most likely be the better practice.

2023-12-20 21:54 UTC, colin-macrae approved these changes
Hi @Jfong1218, great job, and thank you!  Changes approved.

- The branch is going into the correct branch gh-pages. ✅
- The original issue [issue with #number] was properly referenced. ✅
- Per the instructions on the original issue, the issue of list visibility was addressed with adding padding to the bottom of the element ✅

2024-01-02 01:53 UTC, Jfong1218 commented
@soleilherring Could you please take a look at this PR and provide your feedback?

2024-01-02 20:52 UTC, soleilherring approved these changes
So sorry! These messages were being sent to spam. Looks great. So sorry for the delay!

2024-01-03 14:58 UTC, merged