Resolve codeql alert4 5674
hackforla/website pull request #5950
Opened 2023-11-30 20:55 UTC by junadkat32

Fixes #5674 

### What changes did you make?

![image](https://github.com/hackforla/website/assets/84764716/660a2d1f-75a5-46ea-8dbe-7fa6d744f110)

### Why did you make the changes (we will use this info to test)?
To address the CodeQL Alert 4 #5674 

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

![image](https://github.com/hackforla/website/assets/84764716/490bd10d-e675-4d18-aa01-44df0157508c)

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
![image](https://github.com/hackforla/website/assets/84764716/9358d885-fdf6-4685-a78c-84e477a0ed29)

</details>

2023-12-06 11:17 UTC, KyleA99 requested changes
Please see my inline comment I left on the PR.  Once changes are made, please re-request changes on the PR.

2023-12-06 11:17 UTC, KyleA99 commented on _includes/resource-card.html
> +<a href="{{ url }}" class='resource-link' target="_blank" rel="noopener noreferrer">
@junadkat32 there are some slight differences between your code and the replacement code from issue https://github.com/hackforla/website/issues/5674. It may be easier to copy and paste the replacement code rather than typing it out.

When you have a chance, can you also "check off" the checkboxes in the issue itself?

Great work so far :)

2023-12-07 19:48 UTC, junadkat32 commented on _includes/resource-card.html
> +<a href="{{ url }}" class='resource-link' target="_blank" rel="noopener noreferrer">
Hi @KyleA99, in the original code there was no <a href="{{item.resource-url}}" class="toolkit-flex-item-status" target="_blank">     instead it was     <a href='{{ url }}' target="_blank" class='resource-link'>

and I replaced it with <a href="{{ url }}" class='resource-link' target="_blank" rel="noopener noreferrer">

That is why I removed the "item.resource" because when I added "item.resource" the resource links to Github and others were deleted when I tested it on docker.

Please advice the further steps.

2023-12-07 19:50 UTC, junadkat32 commented on _includes/resource-card.html
> +<a href="{{ url }}" class='resource-link' target="_blank" rel="noopener noreferrer">
Hi @KyleA99, in the original code there was no 
![image](https://github.com/hackforla/website/assets/84764716/ad126e3e-cc30-4d1f-a5b8-444768999062)

instead it was 

![image](https://github.com/hackforla/website/assets/84764716/5811c974-6df7-4061-99bd-dedbeea93568)


and I replaced it with

![image](https://github.com/hackforla/website/assets/84764716/800efcf4-d184-4162-b4b8-188e43c31e54)


That is why I removed the "item.resource" because when I added "item.resource" the resource links to Github and others were deleted when I tested it on docker.

Please advice the further steps.

2023-12-08 08:57 UTC, roslynwythe commented on _includes/resource-card.html
> +<a href="{{ url }}" class='resource-link' target="_blank" rel="noopener noreferrer">
@junadkat32 As you stated, the "original" code quoted in the issue was incorrect.  I edited the issue and I apologize for the error!  

@KyleA99 Thank you for the attention to detail in your review!  It is appreciated!

2023-12-08 16:21 UTC, junadkat32 reviewed
So I think, the code that I have replaced is fine. 

@KyleA99 do have a look at it and let me know if any further changes are required.

2023-12-08 22:17 UTC, roslynwythe approved these changes
Great job @junadkat32.  You setup the branches correctly, made a clean, correct code change, and described your work.  You tested the behavior and appearance of the links locally and they all work perfectly.

2023-12-09 07:19 UTC, KyleA99 approved these changes
Reviewed and approved.  Thank you for submitting this PR and for your diligent work @junadkat32

2023-12-09 19:38 UTC, merged