Refactored CSS so icon-slack.svg can use various colors
hackforla/website pull request #6003
Opened 2023-12-12 08:59 UTC by piecanoe

Fixes #5819

### What changes did you make?
  - added ":not(div.resource-img *" to .icon {}

### Why did you make the changes (we will use this info to test)?
  - This will allow the icon-slack.svg icons to be displayed in resource cards with their original colors

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

![image](Paste_Your_Image_Link_Here_After_Attaching_Files)

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
![image](Paste_Your_Image_Link_Here_After_Attaching_Files)

</details>

2023-12-13 03:25 UTC, colin-macrae commented
Review ETA: 12/13/23
Availability: 2+ hrs on 12/13, plus 4+ other hrs this week

2023-12-13 06:23 UTC, MattChau01 commented
ETA: 12/14
Availability: Weekday evenings

2023-12-13 22:37 UTC, colin-macrae requested changes
Hi @piecanoe - This looks good, except I don't believe any extra code was supposed to be deleted.  That is, the original lines 1-4 should still be there, and only lines 5-10 should be replaced, according to the issue's instructions.

2023-12-14 17:20 UTC, piecanoe commented
Hi Colin, thanks for catching this. I will correct this and resubmit.

2023-12-14 17:29 UTC, piecanoe commented
Fixes #5819 

### What changes did you make?
  - Added back the original 1-4 lines:

.svg-sprites {
  display: none;
}


### Why did you make the changes (we will use this info to test)?
 - This was incorrectly removed on the first push

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
<!-- Note, if your images are too big, use the <img src="" width="" length="" />  syntax instead of ![image](link) to format the images -->
<!-- If images are not loading properly, you might need to double check the syntax or add a newline after the closing </summary> tag -->

<details>
  <summary>Visuals before changes are applied</summary>

  ![image](Paste_Your_Image_Link_Here_After_Attaching_Files)

</details>

<details>
  <summary>Visuals after changes are applied</summary>

  ![image](Paste_Your_Image_Link_Here_After_Attaching_Files)

</details>

2023-12-15 01:39 UTC, MattChau01 approved these changes
- The branch is going into the correct branch `gh-pages`. ✅ 
- The original issue #5819 was properly referenced. ✅ 
- Per the instructions on the original issue, the specified lines of code were properly updated. ✅ 

Hi @piecanoe, great work on the PR and responding to @colin-macrae's change request! For future references, you can remove the section for screenshots if the issue doesn't have any frontend/visual changes.

2023-12-15 03:12 UTC, colin-macrae approved these changes
@piecanoe great job, and thanks @MattChau01.  The mistaken deletions were re-added and the changes approved.  

- The branch is going into the correct branch gh-pages. ✅
- The original issue https://github.com/hackforla/website/issues/5819 was properly referenced. ✅
- Per the instructions on the original issue, the specified lines of code were properly updated. ✅

2023-12-15 14:42 UTC, merged