updated wiki link for bop - #5972
hackforla/website pull request #6061
Opened 2024-01-04 20:07 UTC by siddhanthiyer-99

Fixes #5972 

### What changes did you make?
 Changed the link of the wiki URL for Brigade Organizers Playbook.

### Why did you make the changes (we will use this info to test)?
Old code had codeforamerica in the link, the new one doesn't.  

No screenshots.

2024-01-05 05:37 UTC, heejung-hong approved these changes
Good work!
The branches are correct and the issue is linked.
The correct file was changed with the correct information.
I have inspected and confirmed the changes in developer mode on Chrome (desktop, iPad, and iPhone view), Firefox, and Safari browser.

<img width="1170" alt="Screenshot 2024-01-04 at 9 31 24 PM" src="https://github.com/hackforla/website/assets/133067265/9e6d137f-18d9-4720-8e88-d3b20a1bc37a">

2024-01-07 20:55 UTC, robertnjenga commented
Review ETA:  01/07/2024
Availability: 10am - 2pm

2024-01-07 21:05 UTC, robertnjenga requested changes
Hi @siddhanthiyer-99! Thank you for taking up this issue.
The branching was done correctly, you used correct branch to commit from and into, you linked the issue, code changes were made correctly, description of changes i.e updated wiki link in brigade-organizers-playbook project file, and reason for the changes. I'm able to confirm on Docker that that the wiki link in the Brigade Playbook project page points to the relevant page.
Just one edit if possible in the PR comments - replace "No screenshots" with "No Visual Changes"
After the edit you can re-request the review. Thanks!

2024-01-07 21:37 UTC, siddhanthiyer-99 commented
@robertnjenga Thanks for the feedback! I have made the necessary changes in the PR comments.

2024-01-07 21:40 UTC, robertnjenga approved these changes
@siddhanthiyer-99 Thanks for making the changes, Nice Work!

2024-01-08 01:24 UTC, merged