Add size missing label gha 6022
hackforla/website pull request #6085
Opened 2024-01-10 00:23 UTC by djbradleyii

Fixes 6022

### What changes did you make?
  - Added "size" check to GHA's 

### Why did you make the changes (we will use this info to test)?
  - GHA does not check whether a newly created issue has a size label. We need to update this GHA so that the size: missing label is added to issues created without a size label.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

![label_added](https://github.com/hackforla/website/assets/52722401/bee72d2e-8662-4893-b995-733006c347de)

</details>

2024-01-10 03:42 UTC, coding-yost commented
I added a # in front of your issue number so it properly links to the issue being fixed:
Fixes 6022 < -- to --> Fixes #6022
I hope it's okay I made the quick edit, I just saw it during the meeting and thought it'd be a quick fix.

2024-01-11 05:48 UTC, t-will-gillis commented
eta: 1/12/24 eod

2024-01-12 05:59 UTC, t-will-gillis requested changes
Hey @djbradleyii Thanks for working on this issue. The from/to branches are good, the original issue is linked, and short descriptions are provided for what changes were made and why. For the screenshots, the visual provided is not the “Visual(s) before changes are applied”- please revise. To demonstrate that the automation works properly, links to both the issue created during testing as well as to the successful action log could be provided.

Regarding the code edits, both files have extensive edits beyond the scope of the issue: e.g. the addition of explicit semicolons, changing single quotes to double quotes, and other reformatting and restyling. Please limit the code changes to only the scope of the issue itself.

2024-01-23 03:31 UTC, djbradleyii commented
My linter strikes again. I will take care of it and have it completed by EOD 1/23.

2024-01-23 09:21 UTC, djbradleyii commented
All updates have been made. Let me know if there is anything else that needs to be addressed. Thank you.

2024-01-23 19:40 UTC, t-will-gillis approved these changes
Hey @djbradleyii Great, thanks for making the edits! I was able to test this on my repo and confirm that the gha is checking new issues for "size" labels and adds the `size: missing` when appropriate. 

Fyi- the action log from your repo shows an error because some steps in the automation need a personal access token and the bot either can't find the token, or the token does not have permissions/ is expired. But the step for the label check does not need the token. For the next gha, you can check out [Hack for LA's Github Actions](https://github.com/hackforla/website/wiki/Hack-for-LA's-GitHub-Actions)) esp. tips 6 & 7 for setting up a mock Project Board and tokens. 

Thanks again for working on this

2024-01-23 19:41 UTC, merged