added team member to file for issue#6104
hackforla/website pull request #6148
Opened 2024-01-24 01:04 UTC by kevin-421

Fixes #6104

### What changes did you make?
  - Added team member leo peng to the "_data/internal/communities/ui-ux.yml" file.
  -
  -

### Why did you make the changes (we will use this info to test)?
  - To keep project information up to date so that visitors can be informed on all recent changes.
  -
  -

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
- Added a team member to a data file. no visual changes made to the website.
<details>
<summary>Visuals before changes are applied</summary>

</details>

<details>
<summary>Visuals after changes are applied</summary>
  

</details>

2024-01-24 02:44 UTC, njackman-2344 commented
Availability: Tuesday 1/23 7pm-10pm, Wednesday 5pm-10pm 1/24, Friday 5pm-10pm 1/25

ETA: Friday 1/25 EOD

2024-01-24 03:12 UTC, KyleA99 commented
ETA: 1/23/24 EOD
Availability: 1/23/24 all day

2024-01-24 08:29 UTC, KyleA99 commented on _data/internal/communities/ui-ux.yml
> +  - name: Leo Peng
Move from links section to leadership section (move to below Peter Gwon's section).

2024-01-24 08:30 UTC, KyleA99 requested changes
@kevin-421 

- Your PR is done with the correct branch.
- Your code needs to be modified slightly - see inline comment.
- These changes do actually affect the website visuals, please add a screenshot to your pull request once the code has been modified.

Feel free to reach out to me if you need any assistance.  

Great work

2024-01-24 17:33 UTC, LRenDO commented
Hi @kevin-421! 

Great job with the "what" and the "why" as well as the branching! In addition to any changes requested by your reviewers, please also remove the unused bullet points in the original pull request comment. Though it's non-functional, we like to keep them clean. I would also change `team member` in the PR title to `Leo Peng` for clarity as we often have issues very similar to this one.

@KyleA99 mentioned that the visuals do change. These changes will occur on the [Communities of Practice page](https://www.hackforla.org/communities-of-practice). The affected pages are often included in the resource section of the issue.

If you have any questions, feel free to reach out. Thanks for taking the time to contribute and make updates!

2024-01-26 01:14 UTC, KyleA99 approved these changes, later dismissed
PR approved.  Great work @kevin-421 

- Code is properly changed and looks great visually.  

Thank you for your contributions!

2024-01-26 06:28 UTC, njackman-2344 submitted a review, later dismissed
Great work @kevin-421 

Like @KyleA99 said, Code and visuals look good.

2024-01-26 08:01 UTC, jphamtv commented on _data/internal/communities/ui-ux.yml
> -
Please undo the removal of this blank line to maintain formatting consistency with the other yml files in the communities folder.

2024-01-26 08:05 UTC, jphamtv commented
Hey @kevin-421, thanks for making the changes requested by @KyleA99 and @LRenDO.

I noticed the action items on the issue aren't checked off. Please make sure to mark them as completed. It helps track progress and keeps the team updated on what's done and what still needs attention.

Also, an edit was made that's out of scope. It's minor, but to maintain consistency with other yml files, revert the removal of the blank line above `recruiting-messages:`. Thanks!

2024-01-28 19:15 UTC, kevin-421 commented
Hello @jphamtv I see that you want me to check off actions items, but I cannot see where they are located can you point me in the right direction. And I also went ahead and deleted the blank line and pushed the code up thank you.

2024-01-29 23:00 UTC, jphamtv commented
Hey @kevin-421 , I'm sorry if my previous feedback wasn't clear. Let me try explaining again: 

- The Action Items to be checked off are located in the issue here: #6104. 

- What I originally meant to say is to restore the blank line that used to be between the `links:` and `recruiting-message:` sections. Keeping the blank line there would make the formatting consistent with the other .yml files within the communities folder. Here's what lines 46–53 should look like:

```
links:
  - name: Slack
    url: https://app.slack.com/client/T04502KQX/C017ESHSMNG/
  - name: Github
    url: https://github.com/hackforla/UI-UX
    
recruiting-message:
---
```

Let me know if this makes sense. I'm happy to clarify further if needed. Please re-request reviews once you've made the changes. To re-request reviews, click the icon with the arrows next to the reviewer names. Thanks!

<img width="330" alt="Screenshot 2024-01-29 at 14 55 23" src="https://github.com/hackforla/website/assets/4952258/23ba22bf-2bb6-4439-971b-9cbac30f86d6">

2024-01-29 23:52 UTC, kevin-421 commented
yes it makes sense @jphamtv thank you for clarifying. I went ahead and make the changes let me know If anything else needs correcting. Thank you!

2024-01-30 03:23 UTC, njackman-2344 approved these changes, later dismissed
I see the consistent code markup as suggested from @jphamtv . I apologize I didn't account for that earlier. 

The visuals support the change before and after. The branch commit matches. 

Great Job @kevin-421

2024-01-30 06:34 UTC, jphamtv commented on _data/internal/communities/ui-ux.yml
> +    links:
Remove indentation

2024-01-30 06:41 UTC, jphamtv commented
> yes it makes sense @jphamtv thank you for clarifying. I went ahead and make the changes let me know If anything else needs correcting. Thank you!

Hey @kevin-421, you're almost there. Just remove the indentation on line 46 and you should be all set.

2024-01-30 19:44 UTC, kevin-421 commented
Hello @jphamtv correct me if I am wrong but I went ahead and looked at the rest of the code on the file. It looks like all of the indentation is the same for the "links:".

2024-01-30 21:08 UTC, KyleA99 commented
@kevin-421 I'll review again now and take a look at line 46

2024-01-30 21:17 UTC, KyleA99 requested changes
@kevin-421 I just looked over the current code for this PR and I believe that there is an indentation/nesting issue with "links:" on line 46.  Please note that it appears we are using an internal "links:" for each leadership profile, and also a separate "links:" under/after the leadership profiles.

If you refer back to the original code (https://github.com/hackforla/website/blob/gh-pages/_data/internal/communities/ui-ux.yml), the "links:" is not indented/nested inside of the last leadership profile.  I believe this issue is also throwing off the visuals, currently.
![Screenshot 2024-01-30 at 1 13 02 PM](https://github.com/hackforla/website/assets/106561238/d0705a65-10a0-45f0-afd3-2db8b011dbbd)

2024-01-30 21:22 UTC, Thinking-Panda commented
Availability: Weekdays
Review ETA: 1/30/24

2024-01-30 21:47 UTC, kevin-421 commented
hello @jphamtv I went ahead and removed the indentation, the visuals are now looking good. 
![image](https://github.com/hackforla/website/assets/88993079/dca0a15e-5cc4-43ba-ad7f-627381af3ae5)

2024-01-30 22:12 UTC, KyleA99 approved these changes
Code and visuals appear properly changed now.  Approved! Great job @kevin-421

2024-01-31 03:55 UTC, Thinking-Panda approved these changes
@kevin-421 , Thank you for working on this issue. Merge branches are correct. Code changes give desired results. Website works well in local machine. Well done. Approved!

2024-01-31 07:26 UTC, jphamtv approved these changes
@KyleA99, thanks for providing detailed feedback on the indentation issue.

@kevin-421, appreciate your efforts on this pull request. All looks good now.

2024-01-31 07:34 UTC, njackman-2344 approved these changes
branches are mergeable. 

Code format is specified to standards. 

Thank you!

2024-01-31 07:39 UTC, merged