Update code events page
hackforla/website pull request #6158
Opened 2024-01-25 03:50 UTC by Anahisv23

Fixes #6082 

### What changes did you make?
  - Updated the display_object function's if condition to exclude Hack4LA and test objects.

### Why did you make the changes (we will use this info to test)?
  - To prevent any events with the "Hack4LA" and "test" title from showing up on the events page.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

![before 1](https://github.com/hackforla/website/assets/74325966/5fc85169-a7f1-4643-b7cd-c016a3f34d0d)

![before 2](https://github.com/hackforla/website/assets/74325966/06eba029-58e9-439d-b645-140fec2c82be)

![before 3](https://github.com/hackforla/website/assets/74325966/c231fd42-7dce-4fc1-b8a5-ef23b45ffd89)

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
![image](Paste_Your_Image_Link_Here_After_Attaching_Files)

![after 1](https://github.com/hackforla/website/assets/74325966/d2620e55-fcce-4c82-b7d6-7fbb4b6a8752)
![after 2](https://github.com/hackforla/website/assets/74325966/61d7de2f-9861-47f4-8565-fb294e55a667)

![after 3](https://github.com/hackforla/website/assets/74325966/85cd2cbb-c4e1-42b9-b0c3-f477569f226a)

</details>

2024-01-26 07:04 UTC, njackman-2344 commented
Availability: Friday 1/26 5pm - 10pm, Saturday 1/27 3pm-7pm, Monday 1/29 5pm-8pm

ETA: Monday EOD

2024-01-29 08:35 UTC, freaky4wrld commented
ETA: EoD 1/29/12
Availability: Evenings

2024-01-29 09:54 UTC, freaky4wrld requested changes
Hey @Anahisv23 thanks for taking up the issue, your solution works as required, the content you provided is correct, your branches are correct as well.....

A slight change can be made to simplify the conditional statement..... you can replace

```
  if (item  && item.project.name (item.project.name !== "Hack4LA" && item.project.name !== "test"))
 
```
with 

```
if (item?.project?.name !== "Hack4LA" && item?.project?.name !== "test")

```

Your piece of code is correct too... the above one looks more simpler with optional chaining I've suggested the above line of code from @nelsonuprety1 solution for the same issue.......

I would like to hear from the other reviewers about the above suggestion!!

2024-01-29 18:07 UTC, nelsonuprety1 commented
Yes @freaky4wrld, I also think implementing the optional chaining will make the code look more readable and clean.

2024-01-29 20:39 UTC, njackman-2344 commented
@freaky4wrld @nelsonuprety1 What about deleting the "test mctestyface" and "HackforLA" in the vrms api endpoint itself? 
https://www.vrms.io/api/recurringevents

If that's the source of it, delete it there? It's a mess but I thought there's a vs code readable extension for it?

2024-01-29 22:05 UTC, Anahisv23 commented
Hey @freaky4wrld @nelsonuprety1 thanks for the feedback and reviewing the PR. I can go ahead and change the conditional statement to incorporate the chaining suggestions. ETA: Monday Jan 29,  3 - 7pm

2024-01-30 00:32 UTC, Anahisv23 commented
Hey y'all, I just changed the if condition to include the chaining suggestions. Let me know if everything looks good.

2024-01-30 04:33 UTC, freaky4wrld commented
> @freaky4wrld @nelsonuprety1 What about deleting the "test mctestyface" and "HackforLA" in the vrms api endpoint itself? https://www.vrms.io/api/recurringevents
> 
> If that's the source of it, delete it there? It's a mess but I thought there's a vs code readable extension for it?

Hey @njackman-2344 we use the API to fetch information regarding the events, deleting those events might need some authorization which is given to `admins` only...... it's better to handle it from our end rather than trying to alter the dependency we are using to get info on those events!!!

2024-01-30 05:41 UTC, freaky4wrld commented
Hey @Anahisv23 I can see that the instance of `Mtesty face` maybe it's been updated from `Test` to `Test-Updated Name Prod`
<details>
<summary>Screenshot</summary>
<img width="1394" alt="image" src="https://github.com/hackforla/website/assets/134206855/c445c7b0-7a8d-4951-8b29-dbfa4380f605">
</details>

- Maybe the screenshot looks a bit different because of timezone differences, you can check for the instances of `Test-Updated-Name-Prod`
- Also I think we can make use of regex here, and update the current conditional statement to 
      
       ```
             if (item?.project?.name !== "Hack4LA" && !/^Test\b/i.test(item?.project?.name))
        ```
        
I would like to know others opinion on the above suggestions...... maybe @Anahisv23 @roslynwythe @njackman-2344 and @nelsonuprety1 can comment down there feedback below

2024-01-30 21:21 UTC, Anahisv23 commented
> Hey @Anahisv23 I can see the instance of `Mtesty face` maybe it's been updated from `Test` to `Test-Updated Name Prod`
> 
> Screenshot
> * Maybe the screenshot looks a bit different because of timezone differences, you can check for the instances of `Test-Updated-Name-Prod`
> * Also I think we can make use of regex here, and update the current conditional statement to
> 
> ```
>           if (item?.project?.name !== "Hack4LA" && !/^Test\b/i.test(item?.project?.name))
> ```
> 
> I would like to know others opinion on the above suggestions...... or @Anahisv23 @roslynwythe @njackman-2344 and @nelsonuprety1 have any other solution to resolve this issue.

Hey @freaky4wrld. Good catch! I like this approach. I can update it so it will also handle that new "Test-Updated Name Prod" case.

2024-01-31 04:28 UTC, freaky4wrld approved these changes
Hey there @Anahisv23 thanks for taking up the issue and bearing with me for making those changes I appreciate your commitment towards the issue....
Also thanks @njackman-2344 @roslynwythe  and @nelsonuprety1 for sharing their insights on the issue

These are my observation :
- to/from branch looks good
- issue is linked correctly
- reason for making the changes and the places where changes are made are discussed
- Visual changes are apt as well
- Testing on local environment shows no sign of dangling events from the past or the events for testing purposes

PR approved.......

2024-01-31 06:34 UTC, njackman-2344 approved these changes
I agree with @freaky4wrld for PR approval.

The branch looks correct and issue is linked. Correction made.

Visuals look good and testing as well.

Great!!

2024-02-01 07:58 UTC, roslynwythe approved these changes
Great job on this issue @Anahisv23 - as the other reviewers noted, your initial PR was perfectly fine, but we appreciate your willingness to incorporate their suggestions.  

@nelsonuprety1 that was some pretty elegant javascript, thanks for that

@freaky4wrld great review as always, so glad you spotted the `test` event and proposed a fix.

2024-02-01 07:59 UTC, merged

2024-02-02 23:44 UTC, Anahisv23 commented
> Hey there @Anahisv23 thanks for taking up the issue and bearing with me for making those changes I appreciate your commitment towards the issue.... Also thanks @njackman-2344 @roslynwythe and @nelsonuprety1 for sharing their insights on the issue
> 
> These are my observation :
> 
> * to/from branch looks good
> * issue is linked correctly
> * reason for making the changes and the places where changes are made are discussed
> * Visual changes are apt as well
> * Testing on local environment shows no sign of dangling events from the past or the events for testing purposes
> 
> PR approved.......

No problem! Thanks for reviewing the issue :)