Updated wins app script to add spacing and line breaks to wins json feed
hackforla/website pull request #6205
Opened 2024-02-01 20:37 UTC by Jung-GunSong

…etween items and line breaks inbetwen arrays

Fixes #4035 

### What changes did you make?
  - Added a spacer parameter to JSON.stringify() on line 92

### Why did you make the changes (we will use this info to test)?
  - Adds line breaks in between arrays and indentation for array elements in the wins json feed

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

![image](
<img width="1046" alt="Screen Shot 2024-02-01 at 3 05 49 PM" src="https://github.com/hackforla/website/assets/121644228/c87b61a1-c885-4a08-92af-14a5b22cb57f">
)

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
![image](
<img width="1038" alt="Screen Shot 2024-02-01 at 3 36 22 PM" src="https://github.com/hackforla/website/assets/121644228/8b9ddda5-3927-4825-b650-548f2e717fac">
)

</details>

2024-02-05 06:06 UTC, freaky4wrld commented
ETA: EoD 2/6/24
Availability: Evenings

2024-02-06 04:51 UTC, freaky4wrld commented
@Jung-GunSong please refer the action items and make changes in the PR.....

```
In the pull request, provide links to the "Update wins-data.json via Google Apps Script" Pull Request and also the Wins page (both in your repository), for the convenience of reviewers.
```

2024-02-06 05:31 UTC, roslynwythe requested changes
Great work so far @Jung-GunSong.  You created a well-formed PR that describes your work.  The code in `main()` actually creates two json feeds:  wins-data.json (starting at line 91) and _wins-data.json (starting at line 68).  You have the correct strategy for formatting the json, but it should be applied to section of code that generates _wins-data.json.

2024-02-06 16:36 UTC, Jung-GunSong commented
@roslynwythe I understand and apologize for the confusion. I've updated the JSON.stringify() to include the spacer for the _wins-data.json. I hope this fixes the issue.

@freaky4wrld I was able to add the link for the PR, but I'm not sure what the "wins page" is, so I'd like some clarification on that.

2024-02-07 09:08 UTC, roslynwythe commented
@Jung-GunSong @freaky4wrld I realized that my instruction to post a link to the wins page (in your repository) was not complete, because it would require configuration of GitHub pages on your repository, to enable reviewers to view the /wins page.

2024-02-07 10:49 UTC, roslynwythe approved these changes
@Jung-GunSong @freaky4wrld I confirmed that this branch is working by merging the formatted feed into my repository.  The resulting page can be viewed at https://roslynwythe.github.io/wins/  
 In case you are interested, we will be providing instructions shortly on how to publish GitHub pages site from a developer's repository.

2024-02-07 10:49 UTC, merged