Enhance hyperlink security in project layout
hackforla/website pull request #6214
Opened 2024-02-02 18:58 UTC by JackCasica

Fixes #6048

### What changes did you make?
  - Updated the first hyperlink in the project's layout to include `rel="noopener noreferrer"` attributes,

### Why did you make the changes (we will use this info to test)?
  - Adding this attribute improves security and performance by preventing the newly opened page from controlling the page that linked to it. This change guards against potential exploits such as `window.opener` API misuse and reduces the chance of performance issues on the originating page.

2024-02-02 20:17 UTC, mshirk2 commented
Review ETA: 2/5/24 6pm (PT) 
Availability: Weekdays 10-6pm (PT)

2024-02-02 21:11 UTC, mshirk2 commented on _layouts/project.html
> +                    <a target="_blank" href='{{ item.url }}' rel="noopener noreferrer"> {{ item.name }}</a>                    {% assign counter = counter | minus:1 %}
@JackCasica it appears an additional line was changed in your edits. For cleanliness, please return `{% assign counter = counter | minus:1 %}` to its own line.

2024-02-02 21:12 UTC, mshirk2 requested changes
@JackCasica please see inline comment for a small change needed. Once resolved, feel free to re-request PR review.

2024-02-02 23:35 UTC, njackman-2344 commented
Availability: 2/2 Friday 4pm-7pm, 2/3 Saturday 10am-1pm

ETA: 2/3 Saturday EOD

2024-02-03 01:35 UTC, JackCasica commented on _layouts/project.html
> +                    <a target="_blank" href='{{ item.url }}' rel="noopener noreferrer"> {{ item.name }}</a>                    {% assign counter = counter | minus:1 %}
Thanks @mshirk2  ~  It's resolved and ready for a re-review.

2024-02-03 02:41 UTC, njackman-2344 commented
@JackCasica 
For Comment consistency, please keep screenshot: Screenshots of Proposed Changes Of The Website (if any, please do not screen shot code changes) and update us underneath :)

I pulled code and saw it on same line consistency in Docker. Thanks!

2024-02-03 02:52 UTC, JackCasica commented
> @JackCasica For Comment consistency, please keep screenshot: Screenshots of Proposed Changes Of The Website (if any, please do not screen shot code changes) and update us underneath :)

Hello @njackman-2344 ~ I updated the comment to include the requested header and added `n/a` underneath. Is this the correct way to comment for no visual changes? Thanks.

2024-02-03 19:01 UTC, njackman-2344 approved these changes
Branches look good

issue linked

code looks good and seen  screen in different sizes in docker
 
Thanks!

2024-02-05 17:54 UTC, mshirk2 approved these changes
@JackCasica Thanks for making that change, and well done with this pull request!

- The new branch is merging into the correct branch 'gh-pages'
- Original issue is linked
- PR description is clear and correct
- The specified change has been correctly implemented

2024-02-05 19:39 UTC, merged