Added in Closing Span Tag on the About Us Page - Workforce Development Section
hackforla/website pull request #6292
Opened 2024-02-14 02:28 UTC by evan-ishibashi

Fixes #5365

### What changes did you make?
  - Added in a Closing span tag on the About Us Page in the Workforce Development Section
  - Compared Docker local host to the existing website, and visually the section has not changed.
  -

### Why did you make the changes (we will use this info to test)?
  - This was added in to resolve a linter error
  -
  -

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<!-- If images are not loading properly, you might need to double check the syntax or add a newline after the closing ### 
Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

Moving files to another directory. No visual changes to the website.

2024-02-14 03:18 UTC, danvgar commented
I can take a look at this, should be able to review before the end of this week (Fri Feb 16). Thank you!

2024-02-14 03:26 UTC, gaylem commented
Availability: Weekdays
Review ETA: Wednesday, Feb 14th, 8pm CST

2024-02-14 14:59 UTC, gaylem requested changes
Great job @evan-ishibashi! 

- Your branch looks great
- You correctly linked the issue
- The span tag has been added correctly

The only advice I have is that the docs indicate to note that no changes to the website have been made under "Screenshots of Proposed Changes Of The Website (if any, please do not screen shot code changes)" in lieu of images.

Could you add a a comment like "No visible changes made to website" under the screenshots section? 

Thanks for your work on this! :)

2024-02-16 06:24 UTC, jphamtv requested changes
Hey @evan-ishibashi, the pull request is complete with the correct branch, and the issue is properly linked. Your summary of changes is clear, and I've verified that the code change didn't visually alter the page. Nice work executing the code edit cleanly.

In addition to adding the comment requested by @gaylem, could you please remove the extra bullet points that aren't used in your summary of changes section? 

After making these adjustments, re-request a review by clicking on the re-request review circular arrow icon next to the reviewer's name. The PR is ready for approval and merging once those minor edits are completed. Thanks!

2024-02-17 01:13 UTC, jphamtv approved these changes
@evan-ishibashi thanks for making the updates. PR is approved.

2024-02-17 06:08 UTC, freaky4wrld approved these changes
@evan-ishibashi thanks for taking up the issue, @gaylem and @jphamtv thanks for suggesting the changes.
 The branches look good, linked issue is correct, changes done correctly in order to resolve linter error, docker-testing was successful too.

PR approved....

2024-02-17 06:13 UTC, freaky4wrld commented
@gaylem re-review the issue again, and then it can proceed to further merging stage!!

2024-02-17 07:15 UTC, gaylem approved these changes
Excellent work, @evan-ishibashi! Thanks for making the changes. Approved! :)

2024-02-17 08:44 UTC, merged