Adds tools filter to projects and projects-check pages
hackforla/website pull request #6392
Opened 2024-02-29 03:36 UTC by sornekian

Fixes #6196 

### What changes did you make?
  - Added Tools to filter list of Languages and Technologies on the Projects page
  - Refactored createFilter function so that Tools would be combined on projects page rather than be it's own filter

### Why did you make the changes (we will use this info to test)?
  - To include Tools filter for projects and projects-check pages

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>
<img width="1470" alt="before" src="https://github.com/hackforla/website/assets/119828225/0dcae5d9-37b3-4452-b3eb-988453d816f6">
<img width="1457" alt="before1" src="https://github.com/hackforla/website/assets/119828225/814f9ec6-0ba2-436e-97ca-a182f0be75d0">

</details>

<details>
<summary>Visuals after changes are applied</summary>
<img width="1465" alt="after" src="https://github.com/hackforla/website/assets/119828225/9836a575-d87c-4978-9924-51c4173286fd">
  
<img width="1470" alt="after1" src="https://github.com/hackforla/website/assets/119828225/c718e429-46d1-4e67-9a59-77feb73dc7c2">

</details>

2024-03-01 23:05 UTC, luisitocanlas commented
Review ETA: EOD 3/3/24
Availability: 3/1/24 ~ 3/3/24

2024-03-01 23:49 UTC, luisitocanlas reviewed
Hi @sornekian ,

- I just have one question: for lines 230 and 231 before the changes, there was a commented out code for `'looking'` as well as a comment below it saying to see issue #1997 for more info on why that is commented out. Is it alright to have those lines removed or should they be kept?

Thank you!

2024-03-02 19:30 UTC, sornekian commented
@luisitocanlas Yes you're absolutely right, I accidently removed that out. I just returned that bit and pushed again. Please review.

2024-03-02 19:36 UTC, luisitocanlas approved these changes
Hi @sornekian ,

- Pull request is done with the correct branch.
- The issue is linked properly.
- Pull request changes, reasoning, and screenshots were provided.
- Operation of the filters on the `/project` page works
- Appearance and behavior of the `/projects-check` page is unchanged.
- Everything looks good!

Thank you!

2024-03-04 10:14 UTC, elliot-d-kim approved these changes
Hey Sarven,

- Branches and naming was done properly
- Issue is linked
- Summary is concise and descriptive with appropriate visualizations
- Code looks accurate and I appreciate the improved readability thanks to your code!

Approved ✅

2024-03-04 20:00 UTC, Thinking-Panda requested changes
@sornekian , Thank you for making the requested changes. The tools items are added to the Filter list, but the frequency shows 0 for all tool items. Ex: Figma(0), GitHUb(0). Could you please make code changes to reflect the correct frequency number. Thank you for you patience.

2024-03-05 20:45 UTC, elliot-d-kim commented
Good catch @Thinking-Panda.

@sornekian Looking forward to your updates, I'll be happy to review again then.

2024-03-12 00:01 UTC, sornekian commented
I'm having issues with this. The tools when bundled with languages and technologies shows up as (0) but if I put tools separately it works fine. Please see below image. I've tried looking up my issue but I can't seem to figure it out. Can I ask for some help? or if that's not how this works, I can drop the issue for someone else to work on. 

<img width="1460" alt="weird_tools" src="https://github.com/hackforla/website/assets/119828225/121a61ca-e92e-4b79-b59f-0e0223f3fcea">

2024-03-12 19:39 UTC, Thinking-Panda commented
@sornekian , You can sure ask for help. HackForLA community is to learn and grow together. 

The filter frequency is added in the function `updateFilterFrequency()` on `line 390`.
While debugging try comparing `onPageFilters` array and `filterFrequencyObject` to figure out why the tools frequency is not updated.

2024-03-18 20:27 UTC, closed without merging