Resolved codeql alert 98
hackforla/website pull request #6566
Opened 2024-04-04 20:48 UTC by nelsonuprety1

Fixes #6309

### What changes did you make?
  - Moved the attribute rel="noopener noreferrer" from the <img> tag to the <a> tag.

### Why did you make the changes (we will use this info to test)?
  - This change was made to establish tracking between this issue and the alert.
 
### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

<img width="1440" alt="Screenshot 2024-04-04 at 14 44 11" src="https://github.com/hackforla/website/assets/25173636/2a89c964-793f-4701-9f1e-0ed3cdd8d2d3">

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
<img width="1440" alt="Screenshot 2024-04-04 at 14 44 11" src="https://github.com/hackforla/website/assets/25173636/2a89c964-793f-4701-9f1e-0ed3cdd8d2d3">

</details>

2024-04-04 21:28 UTC, aidanwsimmons requested changes
Hey Nelson- changes made to the code look good, issue linked correctly and branches look correct.
Just requesting a couple edits to your pr description to clean it up a bit:
- in changes made: 
include tag names ( a, img )  instead of "from the  tag to the tag"

- in why did you make the changes:
 change to the following: to resolve the alert "Potentially unsafe external link"
i think you may have misinterpreted the issues first action item as the need for these changes. The checkbox is what is used to establish tracking between the issue and the alert.

for the visual changes- since nothing is changing visually, you can just put something similar to the following example from contributing.md 3.1.b:

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

Moving files to another directory. No visual changes to the website.

2024-04-04 21:29 UTC, aidanwsimmons commented
Availability: weekday afternoons
ETA: EOD today

2024-04-09 00:36 UTC, nelsonuprety1 commented
@aidanwsimmons I have changed as per your request. Please kindly do check , thank you.

2024-04-10 02:25 UTC, aidanwsimmons approved these changes
Changes look good- nice work. issue linked correctly and branches look good. Good descriptions of changes.

2024-04-10 05:04 UTC, freaky4wrld approved these changes
@nelsonuprety1 thanks for taking up the issue, branch looks good, changes made are correct and you mentioned things as required.

PR approved!!

2024-04-10 05:14 UTC, merged