Updates the profiles on the civic tech jobs page
hackforla/website pull request #6748
Opened 2024-04-25 00:08 UTC by jono4727

Fixes #6638 

### What changes did you make?
  - Removed the profiles of Jen Chung, Melinda Sukosd, and Jenn Wu
  - Moved and updated the profile for Lu Feng

### Why did you make the changes (we will use this info to test)?
  - Keeps Civic Tech Job project information up to date so that visitors to the website can find accurate information.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

![image]<img width="960" alt="Screenshot 2024-04-23 at 10 20 51 PM" src="https://github.com/hackforla/website/assets/67129178/68ea2ad5-d0d1-4c6a-a6f3-f57c45594328">

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
![image]<img width="960" alt="Screenshot 2024-04-23 at 10 21 09 PM" src="https://github.com/hackforla/website/assets/67129178/6233aac2-a39e-4151-9333-d08a14db64c3">

</details>

2024-04-25 04:30 UTC, freaky4wrld commented on _projects/civic-tech-jobs.md
> +    github-handle: fenglugithub
@jono4727 we don't want it to be 

```
- name: Lu Feng
    github-handle: fenglugithub

```

however it should follow the template provided in the main issue

```
- name: Lu Feng
    github-handle: 

```

2024-04-25 05:39 UTC, jono4727 commented on _projects/civic-tech-jobs.md
> +    github-handle: fenglugithub
It says in the issue to "Update the profile by adding the GitHub handle fenglugithub to the github-handle variable and change the role to UI/UX Lead". It's a little further down maybe you didn't see?

2024-04-25 18:18 UTC, Jperparas commented
**availability:** 4/25
**ETA:** EoD 4/25

2024-04-25 18:26 UTC, Jperparas approved these changes
Great work on the issue!
 branch is labeled correctly and going into the correct branch, issue linked, correct code changes, made.  Visual changes are documented and consistent with  issue.

Keep it up!

2024-04-25 20:59 UTC, jphamtv commented on _projects/civic-tech-jobs.md
> +    github-handle: fenglugithub
Hi @jono4727, you're correct. I'll mark this as resolved.

2024-04-25 21:07 UTC, jphamtv requested changes
Hi @jono4727, 

Please move Lu Feng's profile up so it's directly after any managers or leads of the project per the issue's instructions. Also, your branch has conflicts that need to be resolved. 

Make sure to update your screenshots after making the changes. Once the updates are complete, re-request reviews by clicking on the circular arrows icon next to the reviewers. 

Thanks for your work on this!

2024-04-26 01:09 UTC, jonnyoe commented
Hey @jphamtv,

Okay yeah I see that now. I'll create a new pull request later tonight. Thank you for catching this.

2024-04-26 01:09 UTC, closed without merging