Updates profiles in the civic tech jobs page
hackforla/website pull request #6764
Opened 2024-04-26 03:00 UTC by jono4727

Fixes #6638 

### What changes did you make?
  - Removed Jen Chung, Melinda Sukosd, and Jenn Wu's profiles
  - Moved and updated Lu Feng's profile

### Why did you make the changes (we will use this info to test)?
  - Keeps civic tech jobs project profiles and information up to date

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

![image]<img width="1512" alt="Screenshot 2024-04-25 at 7 48 27 PM" src="https://github.com/hackforla/website/assets/67129178/caeafd26-4b93-4d66-9053-e4bda0141b50">
</details>

<details>
<summary>Visuals after changes are applied</summary>
  
![image]<img width="1512" alt="Screenshot 2024-04-25 at 7 45 20 PM" src="https://github.com/hackforla/website/assets/67129178/3920ce98-4a2d-47b0-b29e-3e122c60ab60">
</details>

2024-04-26 08:56 UTC, A-Wu5 commented
Availability: 4/26, 4/27 1-3PM
ETA: 4/26

2024-04-27 01:01 UTC, A-Wu5 approved these changes
Hi @jono4727, great job on this issue!. The pull request comes from the correct branch and you linked the issue correctly. I've verified the changes locally and it looks good to me!

2024-04-27 01:06 UTC, A-Wu5 commented
A question for the merge team: there was recently another pull request that updated the data for Melinda Sukosd in PR #6678, and I wanted to confirm that removing her profile here is intended.

2024-04-27 21:48 UTC, jphamtv requested changes
Hi @jono4727, 
The code change looks clean and accurate, and the changes to the website look good when tested locally. 

However, I noticed that a submodule directory called 'website' was added in this pull request. Could you please remove the submodule and push the updated changes? Once that's done, the pull request will be ready for merging. Thanks!

2024-04-27 21:51 UTC, jphamtv commented on website
@jono4727 - please remove this submodule directory and push the changes.

2024-04-27 22:08 UTC, jphamtv commented
> A question for the merge team: there was recently another pull request that updated the data for Melinda Sukosd in PR #6678, and I wanted to confirm that removing her profile here is intended.

Thanks for checking @A-Wu5, removing Melinda's profile is the intended action. The issue to remove her profile was created after the issue to update her data.

2024-04-30 22:55 UTC, closed without merging