Update Media Query to Prevent Dropdown Wrapping in Wins Page
hackforla/website pull request #6766
Opened 2024-04-26 05:21 UTC by gdkoo

Fixes #6272 

### What changes did you make?
  - Increased max-width of existing media query to 1024px to cover tablet, desktop and between desktop and xl-desktop sizes
  - This changes the dropdown size to two columns when screen is in tablet, desktop, or between desktop and xl-desktop sizes

### Why did you make the changes (we will use this info to test)?
  - To improve user experience when viewing our website with different devices. 

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>
**Tablet Size**
<img width="837" alt="tablet-wrap" src="https://github.com/hackforla/website/assets/110444314/493be43d-a23c-494b-bd6c-03932ebc5ebb">
**Desktop Size**
<img width="834" alt="desktop-wrap" src="https://github.com/hackforla/website/assets/110444314/6298ead1-8f33-4b84-b1f5-b6e984107259">

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
**Tablet Size**
<img width="850" alt="tablet-nowrap" src="https://github.com/hackforla/website/assets/110444314/fd49d73b-0eb2-41e4-8dd7-b53aa763d1c6">

**Desktop Size**
<img width="1108" alt="desktop-nowrap" src="https://github.com/hackforla/website/assets/110444314/4bec3241-ea77-4eea-b7bb-ce2f2b61fc48">

</details>

2024-04-28 17:25 UTC, ExperimentsInHonesty commented
@gdkoo Please add to a comment, screenshots of the page at the various break points with the team drop-down opened.  The current screenshots before and are of two different things (before: team drop down; after:  role drop down).  So it's not actually showing the before and after.

2024-04-29 05:20 UTC, gdkoo commented
### Additional Screenshots of Proposed Changes Of The Website (if any, please do not screen shot code changes)

Breakpoints and dropdown were selected based on which dropdown resulted in wrapping at specified breakpoints

**Tablet Size 768px (Teams Dropdown):**
Visuals before changes are applied:
<img width="879" alt="tablet-nowrap2" src="https://github.com/hackforla/website/assets/110444314/9d31e125-a368-4f5f-bf88-80b8ee80faad">

Visuals after changes are applied:
<img width="837" alt="tablet-wrap" src="https://github.com/hackforla/website/assets/110444314/ad2bdde4-7d9c-4c67-8767-0d3720ea6592">

**Between Tablet Size and Desktop Size 999px (Role Dropdown):** 
Visuals before changes are applied:
<img width="834" alt="desktop-wrap" src="https://github.com/hackforla/website/assets/110444314/1a30efca-7cd0-45a0-9aa7-9559971ce984">


Visuals after changes are applied:
<img width="834" alt="desktop-wrap" src="https://github.com/hackforla/website/assets/110444314/9fe6037b-2434-4008-abef-159fdd1af1c1">

2024-04-29 05:31 UTC, gdkoo commented
> @gdkoo Please add to a comment, screenshots of the page at the various break points with the team drop-down opened. The current screenshots before and are of two different things (before: team drop down; after: role drop down). So it's not actually showing the before and after.

Will do. For the desktop size, only the roles dropdown has wrapping, the teams dropdown has no issue. Which means that for each breakpoint, alternating dropdowns are affected. Would you like me to include both dropdowns for each breakpoint, or would my update of before and after images focusing on affected dropdowns for each breakpoint be sufficient?

2024-04-29 08:08 UTC, roslynwythe reviewed
@gdkoo this looks great.  
- Pull Request is well-formed and descriptive
- Code change is clean
- Branch checks out in the browser across all screen widths

Can I ask, how did you select the breakpoint max-width: 1024px ?  Would it be possible to use one of the existing breakpoints, for example $screen-desktop: 960px?

2024-04-30 13:34 UTC, gdkoo commented
@roslynwythe: wrapping was an issue up until 999px, so I chose the closest defined screen size (1024px is the desktop size on the browser document inspector).

This was what I was wondering during office hours: since 999px is in between ‘screen-desktop’ and ‘desktop-large’ in ‘_sass/variables/_layout.scss’, to set the breakpoint to everything up to screen-desktop-large would mean all screen sizes would have the two column drop-down.

2024-05-01 06:48 UTC, Jperparas commented
**Availability** Early  Afternoons
**ETA** 5/7 EoD

2024-05-07 21:40 UTC, Jperparas commented on _sass/elements/_old_dropdown_filters.scss
> +@media (max-width: 1024px) {
After the comment by @roslynwythe I tested multiple existing breakpoints and found that  `$bp-below-desktop-large` seems to work 
```
@media #{$bp-below-desktop-large} {
```

2024-05-09 03:34 UTC, roslynwythe requested changes
@Jperparas thanks for testing that.  Honestly I am unsure; @gdkoo does have a good point about changing the design of the desktop layout, so I would like to ask the product team for input.  

@gdkoo I would like to ask product for input on this review but first it would be helpful if you could update the screenshots in the main body of the PR.  I see that you responded to Bonnie's request by posting screenshots in a comment, but I'm a bit confused by those because it seems like under the heading "Tablet Size 768px (Teams Dropdown):", the "before" and "after" screenshots might be switched.  Also it would be best to avoid confusion if the screenshots were placed in the body of the PR instead of a comment.  Thanks

2024-05-09 04:05 UTC, gdkoo commented
@roslynwythe: Thanks for taking a look. I'll make the changes to the screenshots.

2024-05-09 07:11 UTC, roslynwythe commented
@ExperimentsInHonesty Please advise - by modifying the value of `max-width` in a media query (referring to the viewport width at which the drop down lists narrow), this PR does resolve the wrapping in the wins drop downs, with a minimal change to the design.  The only problem is that the value of `max-width` does not match any of our predefined breakpoints, which is undesirable.  The only predefined breakpoint that would eliminate wrapping is 'desktop-large', and that would change the design for desktop-size screens; the dropdown lists would each be half of the width of the screen, up to a viewport of 1632 px, like this:
<details><summary>Details</summary>

![image](https://github.com/hackforla/website/assets/5314153/414a9036-1fda-46cc-aa9e-e60cfec6cc64)


</details>

2024-05-11 21:55 UTC, Jperparas commented on _sass/elements/_old_dropdown_filters.scss
> +@media (max-width: 1024px) {
After reviewing this again I realize that this isn't a solution.  @gdkoo is right.  I suggest that we update `_layout.scss` with another breakpoint `$screen-desktop-medium: 1024px;` 
This is probably outside the scope of this issue.

2024-05-15 04:02 UTC, roslynwythe requested changes
@gdkoo thank you for adding the `screen-desktop-medium` as per the suggestion by @Jperparas, and making use of that breakpoint to resolve the wrapping in the drop downs.

Please correct me if I'm wrong, but I think the screenshots in the "Visual Changes" section, under "Between Tablet Size and Desktop Size 999px (Role Dropdown)" are no longer accurate.  Would you be willing to post screenshots for "Between Tablet Size and Desktop Size" using a screen size equal or greater than 1024px so that Bonnie can view it in QA?

2024-05-16 03:33 UTC, gdkoo commented
@roslynwythe If I were to screenshot before and after for `$screen-desktop-medium: 1024px`, both images would be the same, as wrapping does not take place after 1000px. We chose `1024px` as the breakpoint because it is the width of the standard 'Laptop' on the document inspector.

2024-05-16 06:33 UTC, Jperparas approved these changes
Good job @gdkoo ! This one was a doozy but you stuck in there.
Everything looks good
- Issue linked, 
- branch is correct, 
- I checked the visuals on my local machine with your most recent commit and it was correct. 

Good luck on your next issue!

2024-05-29 02:44 UTC, Thinking-Panda commented
@roslynwythe Please add an availability and ETA for this PR.

2024-06-19 07:37 UTC, roslynwythe approved these changes
Great job @gdkoo - we really want to thank you for your patience and perseverence on this issue. 
- the code change is correct and clean
- the PR is well-formed and descriptive
- the changes look good at all screen sizes in the browser

2024-06-19 07:37 UTC, merged