Update project profile in 6640 `projects/civic-tech-jobs.md`
hackforla/website pull request #6774
Opened 2024-04-28 02:25 UTC by moaz-dev1

Fixes #replace_this_text_with_the_issue_number

### What changes did you make?
  -
  -
  -

### Why did you make the changes (we will use this info to test)?
  -
  -
  -

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

![image](Paste_Your_Image_Link_Here_After_Attaching_Files)

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
![image](Paste_Your_Image_Link_Here_After_Attaching_Files)

</details>

2024-04-28 18:29 UTC, Anahisv23 commented
ETA: Monday April 29 11am - 5pm

2024-04-29 17:49 UTC, ajb176 requested changes
Hey @moaz-dev1, nice work on the issue. You haven't done much wrong but I'm going to request a slight change. 

This is a little bit confusing because the previous version of the page didn't seem to be formatted correctly, but I believe the profiles are meant to be grouped together based on their roles. All members with the same role are meant to be adjacent with each other (i.e. all UX Designers, then all UX researchers, then all Developers). 

Specifically: 
- Brenda's block should be right after Lu Feng's block where Gabriel used to be
- Manju's block should be right after Leah Ellis'

In the previous version Nga Do's block was at the end which seems to have been a mistake.

2024-04-29 20:28 UTC, Anahisv23 requested changes
Hey @moaz-dev1 nice work on this issue! Below I added what you did well on this issue. I agree with @ajb176, in order to ensure consistency with role titles you should reposition Brenda and Manju’s information to be where Gabriel and Ngo’s information was previously.   

Here’s what you did well: 
- There is a linked issue 
- Modified correct files 
- Removed Gabriel’s information
- Removed Ngo ’s information
- UI displays Brenda and Manju’s information on civic tech jobs project page

2024-04-30 03:45 UTC, moaz-dev1 commented
Hey @ajb176 @Anahisv23, thanks for correcting me.
I just updated them, here is how it looks now

<details>
<summary> Before </summary>

![image](https://github.com/hackforla/website/assets/32923319/fe9d3b10-1774-4244-bfb2-c91b4d0903e6)

</details>

<details> 
<summary> After </summary>

![image](https://github.com/hackforla/website/assets/32923319/b5bb835b-7577-49ec-8b48-2a75a7ac36ef)

</details>

2024-04-30 09:36 UTC, ajb176 approved these changes
Looks great, nice work @moaz-dev1

2024-04-30 22:15 UTC, Anahisv23 approved these changes
Looks good! @moaz-dev1

2024-05-01 19:29 UTC, LRenDO commented
Hi @moaz-dev1! Nice work on this PR and the updates. I am going to go ahead and merge, but when you have a moment can you please copy the most recent visual changes you posted in [this comment](https://github.com/hackforla/website/pull/6774#issuecomment-2084323086) into the original PR comment "Visuals after changes are applied" section. Just makes things a little easier to track if for some reason we needed to go back to this PR. 

Again, nice work and thanks for taking on this issue!

2024-05-01 19:29 UTC, merged