New dropdown menu top nav bar
hackforla/website pull request #6854
Opened 2024-05-14 19:40 UTC by ramitaarora

Fixes #2455

### What changes did you make?
  - Created a hoverable dropdown menu in the top navigation
  - Fixed the links in _data > navigation > main.yml according to new design
  - In _data > navigation > main.yml, added link-name variable
  - Fixed the hover states for the desktop navigation and new dropdown menu

### Why did you make the changes (we will use this info to test)?
  - I made these style changes in accordance to the new design in figma
  - I added the link-name variable in order to have the dropdown menu render dynamically, rather than hard-coding each filename.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

![image](https://github.com/hackforla/website/assets/104021517/d0b63e83-45cb-44bf-860b-8550941791ec)

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
<img width="1089" alt="Screenshot 2024-05-14 at 12 24 44 PM" src="https://github.com/hackforla/website/assets/104021517/f8145820-77e4-4ed2-a1e8-61cddbb5a59b">

</details>

2024-05-15 17:56 UTC, LRenDO commented
Hi @marioantonini and @roslynwythe! When you have a minute, please add your ETA and Availability. Thanks!

2024-05-15 17:59 UTC, marioantonini commented
1. Availability: W, Th, Fr: 2-4
2. ETA: EoD 5/16/2024

2024-05-18 01:38 UTC, marioantonini requested changes
The links under `Toolkit` are not resolving properly, but I guess that is an issue with the actual toolkit page not having the proper anchor tags. Some of the navigation links seem wonky (meaning they go inconsistently to either same page or different pages), but that is beyond the scope of this particular issue.

Apart from the requested changes involving classes and ids, the navigation looks good!
All the dropdowns work properly. Links are behaving as expected. And everything looks as nice as the figma files!!

2024-05-18 01:38 UTC, marioantonini commented on _includes/main-nav.html
> +    <li class="{{ item.list_class_name }}" id="dropdown">
`item.list_class_name` seems to be empty, the elements are being rendered without a class. Also, `id="dropdown"` is giving all the dropdown `li` the same `id`, which should not happen. You should not have duplicate ids in a page.

2024-05-18 01:38 UTC, marioantonini commented on _includes/main-nav.html
> +      <a href="{{ item.link }}" role="menuitem" id="menuitem">
Same issue with `id="menuitem"`, this should be a `class`, not an `id` and might be better as `menu-item`, but that is debatable.

2024-05-18 01:38 UTC, marioantonini commented on _includes/main-nav.html
> +          <li class="{{ link.name }}">
In this case, this is a candidate for `id` instead of `class`, since our navigation links should be unique.

2024-05-18 01:38 UTC, marioantonini commented on _sass/components/_header-nav.scss
> +    #menuitem {
This should be a class `.menuitem` or better `.menu-item`

2024-05-18 01:38 UTC, marioantonini commented on _includes/main-nav.html
> +        <ul id="dropdown-content">
Same `id` vs `class` incident

2024-05-18 01:38 UTC, marioantonini commented on _sass/components/_header-nav.scss
> +    #dropdown {
This should be a class.

2024-05-18 01:38 UTC, marioantonini commented on _sass/components/_header-nav.scss
> +    #dropdown-content {
This should be a class

2024-05-19 19:46 UTC, marioantonini commented
After discussing with @ExperimentsInHonesty, the conclussion is that adding the anchor tags to the `Toolkit` page is part of the scope of this issue.
- This is mentioned in the `Action Items` of #2455 
`Check all the links in the top navigation work and go to the correct webpage or section on a webpage`

@ramitaarora please add the proper anchor tags to the file [toolkit.html](https://github.com/hackforla/website/blob/gh-pages/pages/toolkit.html)

2024-05-23 19:29 UTC, roslynwythe requested changes

2024-05-23 19:29 UTC, roslynwythe commented on _includes/main-nav.html
> +    <li id="{{ item.name }}" class="dropdown">
I don't understand why `item.name` should be used to set the id of the `li` element.  The `item.name` field contains whitespace characters which are not permitted in the `id` attribute of HTML elements.  Perhaps it should be `item.link-name` ? I'm not sure this is actually causing a problem or even why the `li` element requires an `id` attribute.  

In any case, I noticed that from the homgepage, the "Our Work" link (/#our-work) does not appear to link to a named anchor target.  Do we need to create an anchor id="our-work" ?

2024-05-24 14:44 UTC, ramitaarora commented
Hey @roslynwythe and @marioantonini , I made the requested changes! For the #our-work anchor tag, I added it to the homepage under projects, but let me know if I should put it in a different place.

As discussed in office hours, I left the toolkit links as is, since that seems to be a bigger issue. :)

2024-05-25 02:25 UTC, roslynwythe commented
@ExperimentsInHonesty 
1. There was no named anchor target for the link "Our Story".  Just to prove that navigation is working,  an anchor was added on the homepage just above the heading "Explore our projects by Program Area".  
2. On the Toolkit page, the named anchors for  `Guides` and `External Resources` do exist, however the links are not working, and we believe that is a result of the manipulation of the url (via window.history.replaceState) that is performed within Toolkit.js, as part of the filter implementation.  For example, if you enter  the url `/toolkit#guides` in the browser, the address is reset to `/toolkit/?` and the portion of the url after the "#" is lost.  I believe this will require modification to the javascript and that may not fall within the scope of this issue.  Please advise.

2024-05-26 16:28 UTC, ExperimentsInHonesty commented
@roslynwythe 

> 1. There was no named anchor target for the link "Our Story".  Just to prove that navigation is working,  an anchor was added on the homepage just above the heading "Explore our projects by Program Area".  

I don't see a menu item "Our Story" on the menu example of the [figma layout](https://www.figma.com/design/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=14120-92883&t=6XowUKXgenZAeNAE-0)
![image](https://github.com/hackforla/website/assets/37763229/e9c7bd3f-8164-41e7-a8ae-b669998062eb)


> 2. On the Toolkit page, the named anchors for  `Guides` and `External Resources` do exist, however the links are not working, and we believe that is a result of the manipulation of the url (via window.history.replaceState) that is performed within Toolkit.js, as part of the filter implementation.  For example, if you enter  the url `/toolkit#guides` in the browser, the address is reset to `/toolkit/?` and the portion of the url after the "#" is lost.  I believe this will require modification to the javascript and that may not fall within the scope of this issue.  Please advise.  

@ramitaarora Please make an ER for this

> 3. There is an accessibility issue: the new navigation bar is not fully navigable via keyboard.  A keyboard user can navigate between the top level menu items but is not able to expand the drop down menu.  Please advise, is this within the scope of this issue?

@roslynwythe @ramitaarora the accessibility is within the scope of this issue.

2024-05-27 07:45 UTC, roslynwythe commented
@ExperimentsInHonesty I apologize, I meant to write that there was no named anchor target for the link "Our Work" on the homepage.  Just to prove that navigation is working, an anchor was added on the homepage just above the heading "Explore our projects by Program Area".  

@ramitaarora please contact me on Slack if you need help writing the ER or with implementing keyboard navigation for the drop down.

2024-05-31 20:33 UTC, ramitaarora commented
@roslynwythe I am working on the keyboard accessibility - which js file could I write this code in? Or should I make a new one?

2024-06-05 23:01 UTC, marioantonini commented
1. Availability: Th, Fr: 2-5
2. ETA: EoD 6/7/2024

2024-06-07 23:25 UTC, marioantonini approved these changes

2024-06-07 23:31 UTC, marioantonini commented
Changes look good. I tested the navigation, and apart from the discussed issue with the links in Toolkit, everything is pinting to the right place.
@roslynwythe @ramitaarora the only thing that for some reason I was not able to test properly was keyboard navigation. But that might have been a problem on my end.

2024-06-17 18:10 UTC, roslynwythe requested changes
@ramitaarora great job adding `assets/js/nav-accessibility.js` for keyboard navigation.  However in mobile and tablet views, while the "hamburger" menu icon does expand via keyboard, the menu options themselves are not reachable via keyboard navigation.

2024-06-19 07:50 UTC, roslynwythe approved these changes
Great job @ramitaarora 
- code changes are correct and clean
- PR is well-formed and descriptive
- changes check out in the browser

There are some changes we would like to see in the menu before the homepage launch, but we have decided to accept this PR as-is and to create new ERs/issues to address these changes.  These changes are:
- remove hyperlinks from the top-level menu items
- improvement to keyboard navigation to use down arrow and/or Enter for submenu
- remove Toolkit menu item from header menu
- remove Toolkit item from footer menu

2024-06-19 07:52 UTC, merged