added github handle for Nicole Doan-6721
hackforla/website pull request #6860
Opened 2024-05-18 18:13 UTC by blaycoder

Fixes #replace_this_text_with_the_issue_number

### What changes did you make?
 I replaced:  

`-name: Nicole Doan`

with

```
-name: Nicole Doan
  github-handle:
```

### Why did you make the changes (we will use this info to test)?
  -To create a single variable  to hold the github handle for each member of the leadership team.

<details>
<summary>Visuals before changes are applied</summary>
<img width="353" alt="before-nicole-doan" src="https://github.com/hackforla/website/assets/79864764/3c7439c5-6be4-487b-943f-25f101154a51">

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
<img width="349" alt="after-nicole-doan" src="https://github.com/hackforla/website/assets/79864764/d32dfc37-4b5d-4ed0-b97a-90b04aba9ea1">

</details>

2024-05-19 17:03 UTC, t-will-gillis commented
Hey @blaycoder - FYI I cleared all of the reviewers that you selected because none of them are currently active on the website team so you would have been waiting a very long time to get this PR reviewed. Unless you know for certain that a specific person is available, it is best not to assign reviewers.

2024-05-19 17:06 UTC, blaycoder commented
Alright, thank you

2024-05-19 20:41 UTC, A-Wu5 commented
Availability: M-F 8-10pm
ETA: Sunday 5/19 EOD

2024-05-19 21:17 UTC, A-Wu5 commented
Hi @blaycoder, thank you for working on this issue. Great work! The changes look good and clean to me.
There are a few things I saw that I wanted to address:

1. Please link the issue you are resolving at the top of the pull request description as stated.

> Fixes #replace_this_text_with_the_issue_number

I believe that the the correct issue is #6721 not #6271.

2. For the visuals section of the pull request, please provide screenshots of the **visual changes on the website**, if any. Review section [how to make a pull request](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#31-how-to-make-a-pull-request) in [contributing](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#how-to-contribute-to-hack-for-la) for more details.

5. I see that you are working on multiple issues and have already completed a `good first issue`. Please move on to issues that are of `Complexity: Medium` and then continue to `Complexity: Large` and claim only one issue at a time.

2024-05-19 21:19 UTC, A-Wu5 requested changes
Please link the issue to the pull request as stated above.

2024-05-22 06:59 UTC, blaycoder commented
@A-Wu5 Thank you so much for the review, I have made the changes based on your request.
Kindly  review once again

2024-05-22 07:00 UTC, blaycoder commented
I have edited my first comment

2024-05-23 20:11 UTC, jphamtv commented
Hey @blaycoder, just a tip for future reference: to re-request a review, click the circular arrow icon next to the reviewer's name. I've already taken care of it for you this time, but keep this in mind for your next reviews. 

<img width="322" alt="Screenshot 2024-05-23 at 13 07 42" src="https://github.com/hackforla/website/assets/4952258/7fa4c196-a8e2-41f7-80ab-bc167e89a4d7">

2024-05-23 22:35 UTC, del9ra commented
Availability: Friday 1-5pm
ETA: May 23, 10PM

2024-05-23 23:03 UTC, del9ra requested changes
Hey @blaycoder, Good job!
- Please avoid duplicating the issue number “Fixes [#6721](https://github.com/hackforla/website/issues/6721) [#6721”](https://github.com/hackforla/website/issues/6721)
- Replace “6271” with “6721” in the name of your branch
- Instead of screenshotting code changes, provide screenshots of proposed website changes if any. If there are no changes, please add “No visual changes to the website.” Refer to the contributing guide for more details.
- The other changes were made correctly 
- The look of the project webpage hasn't changed
Please address these points, and I’ll be happy to approve your PR. Thank you!

2024-05-24 21:28 UTC, A-Wu5 requested changes
Everything else looks good, please remove the duplicated issue # and the screenshots.

Thank you!

2024-05-24 21:37 UTC, Maarimar commented
Agree with @A-Wu5. After you make the requested changes is good to go :)

2024-05-24 21:38 UTC, Maarimar reviewed
Agree with @A-Wu5. After you make the requested changes is good to go :)

2024-05-25 17:36 UTC, closed without merging

2024-05-25 17:48 UTC, blaycoder commented
@Maarimar I have renamed the branch . Click on the link below to access it
https://github.com/blaycoder/website/tree/update-github-handle-nicole-dean-6721