GHA add comments to prework issue 4820
hackforla/website pull request #6873
Opened 2024-05-21 18:24 UTC by partapparam

Fixes #4820

### What changes did you make?
- [x] The following event/activity types are set up to trigger the workflow
   - [x] issues: `opened`, `assigned`, `unassigned`, `closed as completed`, or `closed as not planned`
     - Updated `issue-trigger.yml` file with new job `Add-Comment-To-Prework-Issue`
   - [x] issue_comment: `created`
     - Created `issue-comment-trigger.yaml` file and created new job ` Add-Comment-To-Prework-Issue`
   - [x] pull_request: `opened`, `closed`
     - Updated `pull-reqquest-trigger.yaml` file with new job `Add-Comment-To-Prework-Issue`
   - [x] pull_request_review: `submitted`
     - Created `pull-request-review-trigger.yaml` file and created new job `Add-Comment-To-Prework-Issue`
   - [x] pull_request_review_comment: `created`
     - Created `pull-request-review-comment-trigger.yaml` file and created new job ` Add-Comment-To-Prework-Issue`

- Created and/or actions to:
   - [x]  Determine the contributor generating the event/activity:
      - [x] for `opened` issue events - the issue author
      - [x] for `assigned`, `unassigned`, and `closed` issue events- the issue assignee
      - [x] for issue_comment 'created` events - the comment author
      - [x] for pull_request - the PR author
      - [x] for pull_request_review and pull_request_review_comment - the reviewer or comment author
   - [x] Search for an issue with a "prework" label that is assigned to the contributor 
   - [x] If the prework issue is closed, reopen it and put it in the "In Progress" column
   - [x] Add a comment to the prework issue describing the event/activity

### Why did you make the changes (we will use this info to test)?
  -
  -
  -

2024-05-30 18:48 UTC, jphamtv commented
Hey @marioantonini, when you have a moment please add your ETA and availability. Thanks!

2024-06-10 19:09 UTC, partapparam commented
Hey @marioantonini @jphamtv any update on this PR? I'm hoping to get some feedback and close it so I can work on more issues. Thank you!

2024-06-10 19:12 UTC, marioantonini commented
@partapparam @jphamtv Totally missed this, will get to it today.

2024-06-17 04:28 UTC, t-will-gillis requested changes
Hey @partapparam Thanks for working on this issue! Great job so far- I started testing in my own repo. These are my comments so far:
For a test Pull Request:
- In `pull-request-trigger.yml` , line 70, the section of the if statement `github.event_name == 'pull_request'` is able to be removed since the yml is triggered by the pull request, e.g.  line 70 can be `if: ${{ github.event.action == 'opened' || github.event.action == 'closed' }}`
- In `prework-issue-comment-reusable-workflow.yaml`, the workflow failed right away because of the "if" statements in the "script"  - I think you can get around this by placing your "if" statements at the head of each step, in front of "name" - I made some edits and got through this snag  
  <details>  
  <img width="1058" alt="Screenshot 2024-06-16 210059" src="https://github.com/hackforla/website/assets/40799239/bb73c706-8f38-4745-aa40-dca999cb28b8">

  </details>

- When `prework-issue-comment-reusable-workflow.yaml` calls `get-activity-detail.js`,  the workflow get snagged because on line 23, the event is "pull_request_target" rather than on "pull_request".
- I tweaked this and the following run was snagged on the next step "Get prework issue" - though I am not sure why yet.
- Also, in the "Move issue" step, the workflow got snagged by "const" as shown:  
  <details>
  
  ![Screenshot 2024-06-16 211730](https://github.com/hackforla/website/assets/40799239/f0035678-6f01-4fb2-b1d1-a745e4193c4d)

  </details>
- I know that the original issue requested all of the conditions you are checking for. When this is running we can check for certain however I think that some of the conditions are overlapping each other. We can look at this later....
- FYI, CodeQL has flagged an "Unused variable" in `get-activity-details.js` see above and in "file changed"

2024-07-02 04:51 UTC, t-will-gillis commented
From our previous conversation on Slack:
You might have seen the [Sunset Notice](https://github.blog/changelog/2024-05-23-sunset-notice-projects-classic/) on the Project Board. GitHub is discontinuing Projects (classic) and before August Hack for LA needs to migrate to the Projects Beta. After talking with Bonnie and the team, doing some testing, and checking the calendar, we have decided that the Website is going to migrate to the new Projects Beta on Monday, June 24th.  

Sorry for the short notice- this is happening very quickly. Each of you have currently submitted a PR that involves GitHub Actions and wanted to let you know that we will need to hold off merging any new GHAs until after the migration. To make this interesting, also need to let you know that after migration, any of the existing API calls using a ‘column’ reference will no longer work because Projects Beta is not structured the same- the new term is ‘status’ and it is not interchangeable. Some other REST API endpoints that will be deprecated soon are [here.](https://docs.github.com/en/rest/projects?apiVersion=2022-11-28)  

So for all of you, after migration your workflows will need to be tested using Projects Beta. If you already installed Projects (classic) on your repo you can migrate to Projects Beta for early testing. (FYI after migrating you can reopen Projects (classic)- but do that immediately if you want to keep it because that option disappeared for me after a day.)  

For any workflows that currently involve moving an issue to or from a ‘column’, this should be doable using GraphQL, ProjectV2, and Status. (I have not done this yet- still learning!) And/or we can discuss other options.  

Finally, one last thing I notice is that for all of you there are parts of your issue that overlap with the other two’s issues. As one example, all three of your issues include posting messages to a member’s “Pre-work Checklist”. Unfortunately, this should have been caught earlier so that each issue was worked on after the other was completed, so that you would not each have a different solution to the same problem. (I could also be wrong and maybe there will not be any conflicts.)

2024-07-02 05:00 UTC, t-will-gillis commented
From 6/24 Slack
Hey everyone- we have migrated to Projects Beta. As I mentioned before we made revisions to all workflows that previously involved 'columns' including removing all workflow jobs that used the alex-page automation since these no longer work. "Issue Trigger", "Pull Request Trigger", and "Schedule-Friday" plus related js files had the biggest changes.

2024-08-18 03:21 UTC, t-will-gillis commented
Hey @partapparam I know you have put a lot of work into this, and after we went through the projects migration much has changed. Were you planning to work on this again? Is there anything we should talk about/ discuss? Please let me know - thanks!

2024-08-19 01:09 UTC, partapparam commented
Hey @t-will-gillis, this slipped my radar. I'll review and push the updates this week. Thanks!

2024-09-11 02:30 UTC, Thinking-Panda commented
@partapparam - Please add your availability and ETA to make the requested changes. Thanks!

2024-09-12 00:49 UTC, partapparam commented
**Availability and ETA**: Sunday, 9/15, 3-9 pm. ETA 9/22

2024-10-03 23:42 UTC, jphamtv commented
Hey @partapparam, could you provide an updated ETA and your availability for this PR? If you need assistance, please add a comment with the 'Status: Help Wanted' label or reach out to the team on Slack. Thanks!

2024-10-07 22:18 UTC, JessicaLucindaCheng commented
Param has unassigned themselves from the issue related to this PR. See https://github.com/hackforla/website/issues/4820#issuecomment-2381887331

2024-10-10 02:34 UTC, t-will-gillis commented
@partapparam Thank you for the work that you put into this!

2024-10-10 02:34 UTC, closed without merging