7085 review of bump octokit-rest from `20.1.1` to `21.0.0`
hackforla/website pull request #7126
Opened 2024-07-17 00:46 UTC by mrodz

Fixes #7085 

### What changes did you make?
  - Switched `github-actions/trigger-schedule/github-data` from CommonJS to ESM modules
  - Updated dependency in `package.json`
  - Ran `npm i` to update `package-lock.json`
  - Bumped to semver `3.0.0` because switching to ESM modules is a breaking change
  - Updated imports to reflect changes

### Why did you make the changes (we will use this info to test)?
  -  [@dependabot](https://github.com/apps/dependabot) attempted to bump [@octokit/rest](https://github.com/octokit/rest.js) from `20.1.1` to `21.0.0` (in #7041), but it could not do this without conflicts because octokit-rest `^21.0.0` dropped support for CJS.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
No Visual Changes

### Additional information for Merge Team
- Tested the behavior of the cron job [here](https://github.com/hackforla/website/commit/7b18a1096812010bae9de75b5233659d1b110a6f), which successfully pulled data into `_data/external/github-data.json`.
- **This PR will show signs of a merge conflict once the cron job executes on the main repo, which would put this branch's data on a track with separate history**

2024-07-18 04:27 UTC, t-will-gillis commented
Hey @mrodz Everything looks great so far, thanks for working on this. I am still reviewing. Here are some comments:
- Would you please remove `github-data.json` from the commit? Including the file won't be a problem since it is updated each time "Schedule Daily" runs, however, it does not need to be included (for the same reason) and this will keep us from merge conflicts.
- Yes, I saw the new Dependabot update to v21.0.1 also. Let's stay with the current update to 21.0.0. We recently changed the Dependabot configs to ignore the patch updates, so after this update we won't update again until 21.1.0. 
- I can see how `npm i` updated `package-lock.json`. This might be the correct thing to do- but I would like to look at this some more.
Thanks again! tbc

2024-07-18 20:21 UTC, t-will-gillis requested changes
Hey @mrodz Good call with  `npm -i`. The manual update to `package-lock.json` threw me off because I was thinking that this should be done automatically. But the update revises `"lockfileVersion" : 1` to `3`, which we want (I believe- considering that the current "Schedule Daily" workflow warns about the `old lockfile`).   
<details>
<img width="545" alt="Screenshot 2024-07-18 131652" src="https://github.com/user-attachments/assets/5463a589-0315-4cf3-8c71-18aa1d89f3ba">


</details>  

- [X] I believe you will want to re-run `npm -i` after updating `package.json` - the changes were not fully made to the lock file: "Version 3.0.0" etc.
- [X] Then removing `github-data.json` and I believe this is good to go.

Thanks again!

2024-07-19 06:52 UTC, mrodz commented
Hi @t-will-gillis, I am on it. To revert the testing to `github-data.json` I will reset my head and force push to my branch, then run `npm i` again. 

However, both times that I've worked on issues regarding this cron job, I've followed the testing procedure laid out [here](https://github.com/hackforla/website/issues/6643#issuecomment-2132043028), which pollutes my branch with the testing data and guarantees a merge conflict. Would the testing info benefit from a review/revision?

Thanks for your help throughout this.

2024-07-19 16:09 UTC, t-will-gillis commented
Hi @mrodz 

> However, both times that I've worked on issues regarding this cron job, I've followed the testing procedure laid out https://github.com/hackforla/website/issues/6643#issuecomment-2132043028, which pollutes my branch with the testing data and guarantees a merge conflict. Would the testing info benefit from a review/revision?

What I have done in similar situations is create two branches in my repo, one for testing and a clean one for the PR. You also could try copying the data / replacing the data in your branch's `github-data.json` with the current HfLA `github-data.json`. Also as I was saying updating `github-data.json` with your version should not have a permanent effect, and we can also manually run `schedule-daily-1100.yml` after merging.

About revising the file [here](https://github.com/hackforla/website/issues/6643#issuecomment-2132043028), yes definitely if you would like to suggest revisions to that file and/or any others that would be great, especially if you have not written any issues yet. You could write an ER for it and then propose edits.

2024-07-19 19:44 UTC, mrodz commented
- Merge conflicts were resolved
- Testing performed on child branch in e410aab17c7ed476939fa2e6901cc75a88aa3e2e
- The warning about the old lockfile no longer persists, and the cache was updated with the new dependencies
  <details>
  <summary>Details</summary>

  ![image](https://github.com/user-attachments/assets/7982e139-1363-455d-9eb7-b5eeb4ecca33)
  </details>

2024-07-19 20:49 UTC, t-will-gillis approved these changes
Hey @mrodz Awesome work on this! 

I did a final test and it appears that the workflow is functioning as expected. Thank you especially for updating the `package-lock.json` to the new `"lockfileVersion": 3`.

2024-07-19 20:50 UTC, merged