Feature
hackforla/website pull request #7130
Opened 2024-07-19 20:15 UTC by elsong86

Fixes #7103 

This PR adds the github-handle variable for each member of the leadership team in the _projects/guides-team.md file, addressing issue https://github.com/hackforla/website/issues/7103.

### What changes did you make?
  - Added github-handle variable for leadership team member
  
  

### Why did you make the changes (we will use this info to test)?
  - To reduce redundancy in project file
  -
  -

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

![image](Paste_Your_Image_Link_Here_After_Attaching_Files)

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
![image](Paste_Your_Image_Link_Here_After_Attaching_Files)

</details>

2024-07-22 21:33 UTC, cchrizzle commented
Hi @elsong86, thanks for taking this up!

Changes look good:
1. Linked to the original issue correctly
2. Added the correct section name of "github-handle"
3. Used spaces for the indentation instead of a tab like the instructions directed



 Just a couple of suggestions:
1. Check off the checkboxes in the [issue link](https://github.com/hackforla/website/issues/7103) to show your progress and completion.
2. Specify who you added the section to (Sarah Edwards in this case).
3. Remove the empty bullet points after "To reduce redundancy in project file".
4. Remove what is currently under the screenshots section since there are no visual changes to the website from the changes and specify that there were no visual changes to the website from your update.

After that everything should be good!

2024-07-23 20:40 UTC, elsong86 commented
I have now updated my comment with the requested changes. Thank you.

2024-07-24 16:23 UTC, LRenDO commented
Hi @cchrizzle! Thank you for reviewing and your feedback on this PR. Please review the updates @elsong86 made and use the `Review Changes` button on the `Files Changed` tab. You can select `Approve` or `Request Changes` in that comment box based on what you would like to do. Thanks!

2024-07-24 22:18 UTC, cchrizzle requested changes
Thanks for making the requested changes!

Please also specify "Sarah Edwards" in the "What changes did you make?" section of your pull request and it will be good to go.

2024-07-24 22:18 UTC, cchrizzle commented
@LRenDO Got it, thank you!

2024-07-24 22:22 UTC, elsong86 commented
Added Sarah Edwards to changes made section.

2024-07-24 22:25 UTC, cchrizzle approved these changes
Perfect, approved!

2024-07-26 04:42 UTC, t-will-gillis approved these changes
Hey @elsong86 - great job on this issue. The PR is linked to the original issue, there are concise descriptions of what was done and why, there is a note for no visual changes, and the code edits are clean. Thanks for coordinating with @cchrizzle on the edits. For the next issue, please remember to use a short, descriptive name and include the issue number when you [create the branch](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#27b-working-on-an-issue-2-create-a-new-branch-where-you-will-work-on-your-issue) you will be working on.

Thanks for working on this!

2024-07-26 04:42 UTC, merged