Mobile hamburger nav
hackforla/website pull request #716
Opened 2020-09-04 18:33 UTC by drubgrubby

Fixes #526 

I believe that this is now working according to spec.  

The main features are:
1) When you click the Hamburger icon the nav menu opens.  When you click the X the nav menu closes. 
2) When the menu is open, you should be able to touch anywhere outside of the navigation menu to close the menu and reset the hamburger icon.
3) Icons and buttons have been resized and adjusted to match the figma file. 
4) All of this only happens for screens smaller than tablet size. 

Notes: This is my first big project, so I very much would like to know, in addition to things that don't work, about better ways to do any of this, and if any of these files or styles should be in different places.  

I'm also putting in a vote here to have a scripts directory.

2020-09-09 22:04 UTC, KianBadie requested changes
This is basically there. Only requests are nit picks. Greate job @drubgrubby for writing clear code. As I was figuring out how your code worked it became clear the purpose of a lot of elements/components of your solution. 

I would say to get this merged, I would like to ask for some responses/possible changes to the review comments I made, and an answer to this question: I noticed the nav bar is now smaller for mobile devices than before. I think I heard you talk about this before. Was there a reason for the change in size of the nav bar for mobile?

2020-09-09 22:04 UTC, KianBadie commented on _includes/svg/logo-hfla-mobile.svg
> +<svg class="logo" viewBox="0 0 64 83" fill="none" xmlns="http://www.w3.org/2000/svg">
File not in use, will be deleted as we discussed @drubgrubby. I will go ahead and push that deletion myself

2020-09-09 22:04 UTC, KianBadie commented on _includes/donate-button.html
> +<div class="social-links mobile-flex-grow-2">
What is the intended goal of this class? It seems to get overwritten by other classes with it's final flex grow computing to 1. Was this fixing a big of sorts? If it's purpose got overwritten by other stuff, then I think we could remove it

2020-09-09 22:04 UTC, KianBadie commented on _includes/hamburger-nav.html
> +<div class="align-right" id="swapButton">
It seems `align-right` class is not in use. Was it intentional to leave in there?

2020-09-09 22:04 UTC, KianBadie commented on _includes/hamburger-nav.html
> +      <button onclick="burgerSwap()" id="burgerImage" class="nav-icon">{% include svg/icon-hamburger-nav.svg %}</button>
Is there a need for the `nav-icon` class to be included here? It seems that what it does is sets a default display to none on mobile devices. But it seems that is also being handled already by the #burgerImage and #burgerImageX id's. I see why you added the css rules to have display none for the other nav-icons though, which is good

2020-09-09 22:04 UTC, KianBadie commented on _sass/components/_header-nav.scss
> +  button:hover {
not critical, but it doesn't seem buttons are hoverable on mobile. see https://stackoverflow.com/a/2427465/9174232

It's not creating any bugs, it's just not adding any functionality. if you need to make changes because of this review could we go ahead and delete this while we are at it? But if no changes are necessary, it's fine

2020-09-10 00:42 UTC, drubgrubby commented on _includes/donate-button.html
> +<div class="social-links mobile-flex-grow-2">
You are correct.  When I added this tag is was needed to push the donate button into place as it was sitting in the middle of the header.   Later changes seem to have made it redundant.  This tag can be removed.

2020-09-10 00:51 UTC, drubgrubby commented on _includes/hamburger-nav.html
> +<div class="align-right" id="swapButton">
This tag was already there from wherever I took the original div code from.  This was the beginning of the process and I was disinclined to remove anything if I didn't have to.  But it does not seem to do anything and there's no reason to leave it there.  It can be removed.

2020-09-10 00:55 UTC, drubgrubby commented on _includes/hamburger-nav.html
> +      <button onclick="burgerSwap()" id="burgerImage" class="nav-icon">{% include svg/icon-hamburger-nav.svg %}</button>
Same as the previous reply.  That tag was there from wherever I copied the button code from.  Since it didn't seem to do any harm I just left it.  But you are correct, it doesn't seem to be doing anything useful and can be removed.

2020-09-10 00:58 UTC, drubgrubby commented on _sass/components/_header-nav.scss
> +  button:hover {
You are, once again, correct.  When testing it in my browser the hover effect was visible, and since it wasn't in the figma file, I added this hover tag to turn off the hover effect that's on the full screen navigation.  As you said, we can leave it or remove it.

2020-09-10 20:46 UTC, KianBadie commented on _includes/donate-button.html
> +<div class="social-links mobile-flex-grow-2">
Sweet, yeah let's go ahead and remove it

2020-09-10 20:47 UTC, KianBadie commented on _includes/hamburger-nav.html
> +<div class="align-right" id="swapButton">
I see, yeah I think it would be a good idea to delete it. So whoever reads the code has less things to keep track of in the future

2020-09-10 20:47 UTC, KianBadie commented on _includes/hamburger-nav.html
> +      <button onclick="burgerSwap()" id="burgerImage" class="nav-icon">{% include svg/icon-hamburger-nav.svg %}</button>
Sounds good, my comment will be the same as above too then!

2020-09-10 20:48 UTC, KianBadie commented on _sass/components/_header-nav.scss
> +  button:hover {
sweet, since we are deleting the other things let's go ahead and delete this too!

2020-09-11 02:59 UTC, drubgrubby commented
In answer to your above question about the nav bar being smaller: The HFLA logo is intentionally smaller now for mobile.  The primary reason is that this matches the figma file that our designers made in their great design wisdom. The practical reason is that when the content is squished together on the small mobile screen the larger logo covers some of the text on the page.

2020-09-11 03:22 UTC, drubgrubby commented
I have made all of the changes you requested and pushed them to the mobile-hamburger-nav branch.

2020-09-11 19:39 UTC, KianBadie commented on _includes/svg/logo-hfla-mobile.svg
> +<svg class="logo" viewBox="0 0 64 83" fill="none" xmlns="http://www.w3.org/2000/svg">
File was deleted by @drubgrubby

2020-09-11 19:41 UTC, KianBadie commented on _includes/donate-button.html
> +<div class="social-links mobile-flex-grow-2">
Class was removed

2020-09-11 20:21 UTC, KianBadie requested changes
Hi @drubgrubby, thank you so much for applying those changes. It was looking good and I was going to add a couple really small nitpick changes, but then I realized something bigger in the css class declarations (see my review comments for more). I felt like it was important enough to request a couple more changes

Sorry, I should have realized this earlier so it can get out of the way with 1 go. Let me know if you have any questions

2020-09-11 20:21 UTC, KianBadie commented on _sass/components/_header-nav.scss
> +  .main-header {
Since this styling class is defined in the _header.scss class, it gave me the impression that _header.scss and _header-nav.scss have different responsibilities (overall header vs. navigational stuff in header), do you agree? If so, could we actually move integrate these rules over to _header.scss in order to try to decouple responsibilities? 

If you agree and implement this, let me know how it goes.

2020-09-11 20:21 UTC, KianBadie commented on _sass/components/_header-nav.scss
> +  .btn-donate {
Same story as above class .main-header

In addition, can the `margin-top` be upped to something like 6px so that it can be more vertically centered?

2020-09-11 20:21 UTC, KianBadie commented on _sass/components/_header-nav.scss
> +  .main-header .branding {
Same story as above class .main-header

2020-09-11 20:21 UTC, KianBadie commented on _sass/components/_header-nav.scss
> +  .main-header .branding {
Same story as above class .main-header

2020-09-11 20:21 UTC, KianBadie commented on _includes/hamburger-nav.html
> +      <button onclick="burgerSwap()" id="burgerImage" class="">{% include svg/icon-hamburger-nav.svg %}</button>
Small nitpick, (I was actually going to do this myself, but I requested other changes so I hope it is ok to throw these in here as well) could we please remove the `class=""` statements? Just so that the code is intentional

2020-09-11 23:28 UTC, drubgrubby commented on _includes/hamburger-nav.html
> +      <button onclick="burgerSwap()" id="burgerImage" class="">{% include svg/icon-hamburger-nav.svg %}</button>
Empty classes have been removed.

2020-09-12 00:14 UTC, drubgrubby commented on _sass/components/_header-nav.scss
> +  .main-header {
This has been moved to _header.scss

2020-09-12 00:15 UTC, drubgrubby commented on _sass/components/_header-nav.scss
> +  .btn-donate {
This has been moved to _header.scss.  I also increased the margin-top which makes it look much better.

2020-09-12 00:15 UTC, drubgrubby commented on _sass/components/_header-nav.scss
> +  .main-header .branding {
Moved to _header.scss

2020-09-12 00:18 UTC, drubgrubby commented on _sass/components/_header-nav.scss
> +  .main-header .branding {
In spite of my inherent laziness, I actually did the right thing with this and - instead of just overriding the .main-header .branding tag that was already there - I replaced the css for the large display branding image.  Technically, this css has been removed and the .branding css has been edited.

2020-09-13 01:00 UTC, KianBadie commented on _sass/components/_header-nav.scss
> +  .main-header .branding {
I don't think I understood everything completely. When you say the `.main-header .branding` tag that was already there, do you mean existing on the gh-pages branch? Because I wasn't able to find that class declaration. Would you be able to please explain this in other words to me? Sorry for the misunderstanding!

2020-09-13 01:05 UTC, KianBadie requested changes

2020-09-13 01:05 UTC, KianBadie commented on _sass/components/_header.scss
> +    @include position(absolute, -24px null null -20px);
Was this mixin intentionally added? When I try to run this code it says that the position() mixin is not declared. Another weird behavior that's going on is that in line 2 of this file, it has the same position() mixin in use, but it isn't registering as a change that will be added with this pr. Which is also why I think we can ignore it, because it won't be added to gh-pages

This is where the merge conflict is coming from. I'll mess around with this statement on my branch and see if I can replicate the intended behavior from last commit (since everything was working at that time)

2020-09-13 02:38 UTC, drubgrubby commented on _sass/components/_header.scss
> +    @include position(absolute, -24px null null -20px);
So that's weird. That was already there.  I changed the values to make the image align correctly, but the mixin was already there and is running just fine on my end.  I vaguely remember Cynthia talking about removing bourbon in preparation for adding bootstrap. I'm not sure if anything's happened with that yet.   Since position was defined in bourbon, could that have something to do with it?

2020-09-13 14:56 UTC, KianBadie commented on _sass/components/_header.scss
> +    @include position(absolute, -24px null null -20px);
Resolved by removing mixin and implementing highlighted code with regular css

2020-09-13 15:20 UTC, KianBadie approved these changes

2020-09-13 15:35 UTC, KianBadie reviewed
Thank you @drubgrubby, it looks great. I approved the changes you made, and I think it is an acceptable place to be merged. The only thing stopping me from merging it myself are some edge cases that I wanted to get approved first:
- For very tall phones, because the width is so big, if you switch from vertical to landscape view the width is changes to be too big for the mobile rules of the hamburger nav. But the old nav menu does not show up (I'm assuming this is because the hamburger styling was applied in vertical but still "kept" in horizontal). I don't know how to replicate consistently, but it still happens. I'll post screenshots bellow as "Picture 1"
- While testing on my phone, everything worked fine for the most part. There are some abnormal behaviors on chrome and safari. On chrome the nav bar will detach slightly from top of the page when switching to landscape, but will reattach when scrolled up. On safari, when a nav link is clicked in landscape, the safari search bar will cover the nav bar, but will uncover it in when scrolled up. I'll post screenshots bellow (Picture 2 for chrome and Picture 3 for safari).
Like I said, these are edge cases. And I am a bit reluctant to request changes for this, and wanted to hear the thoughts of @ExperimentsInHonesty, @cnk, and others during today's meeting.
### Picture 1: When a phone is too tall
![Screenshot from 2020-09-13 08-25-35](https://user-images.githubusercontent.com/18221058/93022063-af6b4400-f59b-11ea-9e21-8c2b25d8bd02.png)
### Picture 2: Detached nav bar chrome
![IMG_2737](https://user-images.githubusercontent.com/18221058/93022095-e2add300-f59b-11ea-9abf-3a7b377a3544.PNG)
### Picture 3: Covered Nav bar safari
![IMG_2738](https://user-images.githubusercontent.com/18221058/93022104-f0635880-f59b-11ea-880a-45567c513a44.PNG)

2020-09-16 01:58 UTC, drubgrubby commented
Using Kian's cool hack, I was able to check them all out on my phone - an iPhone SE (2020).  It seems to work on my phone in all of the browsers I tried.  I didn't see any of the strange things that Kian posted above. There were two things: 
1) In Safari, the nav links, donate button and hamburger image were blocked by my ad blocker (1Blocker).  Once I added the site to 1Blocker it worked fine. 
2) The feature where you can click anywhere to close the menu worked in Chrome and Opera but not in Safari and Firefox.  I can live with that. 

Chrome
![UNADJUSTEDNONRAW_thumb_2527](https://user-images.githubusercontent.com/68244054/93283311-24e63880-f785-11ea-947b-e60f66aa75d5.jpg)
![UNADJUSTEDNONRAW_thumb_2528](https://user-images.githubusercontent.com/68244054/93283315-27e12900-f785-11ea-899d-72f61a6c65a9.jpg)

Firefox
![UNADJUSTEDNONRAW_thumb_252b](https://user-images.githubusercontent.com/68244054/93283344-38919f00-f785-11ea-92db-66904d5a9bab.jpg)

![UNADJUSTEDNONRAW_thumb_252a](https://user-images.githubusercontent.com/68244054/93283364-42b39d80-f785-11ea-8d13-fd6d8b44c38c.jpg)

Opera
![UNADJUSTEDNONRAW_thumb_252c](https://user-images.githubusercontent.com/68244054/93283376-4810e800-f785-11ea-8b73-9b9f35eb5f04.jpg)
![UNADJUSTEDNONRAW_mini_252e](https://user-images.githubusercontent.com/68244054/93283384-4b0bd880-f785-11ea-9c82-14e077e9a742.jpg)

Safari
![UNADJUSTEDNONRAW_thumb_252f](https://user-images.githubusercontent.com/68244054/93283434-60810280-f785-11ea-9f9c-f66e4fa595fe.jpg)
![UNADJUSTEDNONRAW_thumb_2530](https://user-images.githubusercontent.com/68244054/93283442-637bf300-f785-11ea-8add-6a28e9613728.jpg)

2020-09-17 21:33 UTC, alexandrastubbs commented
@drubgrubby can you turn your ad blocker back on and see if it works with the existing experience?

2020-09-18 01:00 UTC, KianBadie commented
@alexandrastubbs @ExperimentsInHonesty @drubgrubby I added some code that fixed the bug where tall phones wouldn't have a nav bar show up on orientation change. I have also been fiddling/searching around for the cause/fix to the nav bar having problems with the search bar (images [here](https://github.com/hackforla/website/pull/716#pullrequestreview-487317352)). Unfortunately, I haven't had much luck in fixing it or finding the exact reason why this is happening. My hunch so far is that it is from how mobile browsers resize there search bars (minimize vs showing). The same chrome bug I mentioned [here](https://github.com/hackforla/website/pull/716#pullrequestreview-487317352) also happens with the nav bar on the current site. In addition, the nav bar on chrome (for me) has some issues when scrolling up and down even without orientation change. I want to look more into that, because I did see some stack overflow questions relating to this I can look into.

What I think is interesting too is @drubgrubby said he did not experience these bugs. which brings me to this point: In terms of deciding if this is good for merging, I can send @alexandrastubbs and @ExperimentsInHonesty a few quick steps on how to test things on their mobile device, so that the code does not have to go live before merging. I'm having a bit of difficulty trying to ride the line between "let's get things done" vs "let's do things great".

2020-09-18 02:30 UTC, drubgrubby commented
Just tested out Kian's fix for the tall phone problem and it works exactly as it should.  A much more elegant solution than mine was. 

As Kian mentioned, I don't see the nav bar styling issues that Kian mentioned above, so not sure what to do about that.

2020-09-18 02:39 UTC, drubgrubby commented
@alexandrastubbs It looks like 1Blocker blocks the "Donate" button on the current site as well: 

**Before adding hackforla to 1Blocker:**
![UNADJUSTEDNONRAW_thumb_253a](https://user-images.githubusercontent.com/68244054/93548975-3febb080-f91d-11ea-81bb-5165e29cbc8a.jpg)

**After adding hackforla to 1Blocker:** 
![UNADJUSTEDNONRAW_thumb_253b](https://user-images.githubusercontent.com/68244054/93548995-4bd77280-f91d-11ea-9d62-87f2d2464ffe.jpg)

2020-09-19 23:01 UTC, KianBadie commented
@ExperimentsInHonesty @alexandrastubbs @drubgrubby 
@cnk Reminded me of the conversation we had during the dev meeting regarding this pull request where we decided it would be a good idea to merge this and test live. I personally think it is a good idea as well as we can see if the bugs (which are not breaking bugs) are consistent for other people, as they would be able to test on their own phones.

2020-09-19 23:03 UTC, merged