Iss 555 final
hackforla/website pull request #718
Opened 2020-09-06 04:55 UTC by ruben1s

I have made the final changes to my toolkit page.
![screencapture-0-0-0-0-4000-toolkit-2020-09-05-21_54_02](https://user-images.githubusercontent.com/33906590/92318535-77c03300-efc2-11ea-9f6d-b4c792cdce64.png)
![screencapture-0-0-0-0-4000-toolkit-2020-09-05-21_54_30](https://user-images.githubusercontent.com/33906590/92318536-7989f680-efc2-11ea-8c2b-4f98bffe96b5.png)
![screencapture-0-0-0-0-4000-toolkit-2020-09-05-21_54_50](https://user-images.githubusercontent.com/33906590/92318538-7d1d7d80-efc2-11ea-8c73-27ffbda5993c.png)

2020-09-06 18:04 UTC, ExperimentsInHonesty commented
need to have the text in one column.  Please change the name of the pr

2020-09-06 18:36 UTC, ruben1s commented
Final Changes 

![screencapture-0-0-0-0-4000-toolkit-2020-09-06-11_20_22](https://user-images.githubusercontent.com/33906590/92332783-269d5700-f035-11ea-8e40-45232bed9377.png)
![screencapture-0-0-0-0-4000-toolkit-2020-09-06-11_19_59](https://user-images.githubusercontent.com/33906590/92332785-2735ed80-f035-11ea-97ca-51eb972310d3.png)
![screencapture-0-0-0-0-4000-toolkit-2020-09-06-11_19_32](https://user-images.githubusercontent.com/33906590/92332786-27ce8400-f035-11ea-8531-1fb19671d6df.png)

2020-09-09 00:02 UTC, KianBadie requested changes
Hi Ruben, first I want to saw I really liked the nesting you did with the classes. Smart way to get rid of specific classes, and I learned something new. 

I added review, and some of the comments are just questions that don't require any code change at the moment. If you can, I would appreciate a response to all the comments. I won't wait as long for the next review, and I will try to comment on necessary changes so we can get your page out asap because it is good so far :+1:

2020-09-09 00:02 UTC, KianBadie commented on _sass/components/toolkit.scss
> +    padding-bottom: 50rem;
@ExperimentsInHonesty I know this is replicating the figma exactly, but in terms of practicality is it desired to have the padding be this size? [figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=1548%3A1967) vs what it looks like on screen.
![Screenshot from 2020-09-08 16-41-50](https://user-images.githubusercontent.com/18221058/92537947-4332be00-f1f2-11ea-890a-29557f6a4cc2.png)

2020-09-09 00:02 UTC, KianBadie commented on _data/navigation/main.yml
> -- name: Hack Nights
Saw that hack nights were removed. Was this decided through discussion? I could not find this change noted in the issue

2020-09-09 00:02 UTC, KianBadie commented on toolkit.html
> +<div class="toolkit-header__text-group">
Would we be able to center this horizontally and to a thinner so that it can be closer to the figma? Also, is this a banner or supposed to be a nav bar of sorts?

2020-09-09 00:02 UTC, KianBadie commented on toolkit.html
> +    <div class="toolkit__guides-section">
The figma is in 3 columns. Is this a requirement or just an example of how the page could be laid out? My experience had a 2 column list
![Screenshot from 2020-09-08 16-48-12](https://user-images.githubusercontent.com/18221058/92538267-1c28bc00-f1f3-11ea-8452-1fc1bb26e1b6.png)

2020-09-09 00:02 UTC, KianBadie commented on toolkit.html
> +            <h3 class="toolkit-flex-item-header"><a href="">Create a Kanban Project Board from 0ur Template</a></h3>
The blank href redirects back to the same page. Should these not be links right now and be re-implemented as links once the guides are created? I feel like this could reduce confusion for a user, how about you?

2020-09-09 00:02 UTC, KianBadie commented on toolkit.html
> +            <h3 class="toolkit-flex-item-header"><a href="https://www.hackforla.org/guide-pages/2FA.html">Enabling 2-Factor Authentication</a></h3>
Were the links to the guides mentioned through discussion? If so, how can I verify the links are going to the right place?

2020-09-09 00:02 UTC, KianBadie commented on toolkit.html
> +        <div class="suggest-guide-group"><h3>External Resources</h3><button class="toolkit-button btn btn-primary">Suggest a resource</button></div>
Currently, this button is not functional. Is this intentional? Like are we waiting for a page to be made?

2020-09-09 00:02 UTC, KianBadie commented on toolkit.html
> +        <div class="resource-container">
The resource cards were right leaning for mobile (the strongest case was for Moto G4). Would we be able to center these using some padding for the container?
![Screenshot from 2020-09-08 16-52-58](https://user-images.githubusercontent.com/18221058/92538566-dddfcc80-f1f3-11ea-8cf6-c9a28ea80fcb.png)

2020-09-09 00:02 UTC, KianBadie commented on toolkit.html
> +            <div class="toolkit-flex-item-resource section-container">
Would we be able to format the resource cards so that they match the figma in terms of being horizontally aligned?
![Screenshot from 2020-09-08 16-56-37](https://user-images.githubusercontent.com/18221058/92538742-53e43380-f1f4-11ea-9b91-5e1fa5f150d3.png)

2020-09-09 00:02 UTC, KianBadie commented on toolkit.html
>  <div class="toolkit-header header-container">
Would we be able to overwrite the rule from header-container without modifying the original class (it looks like it was borrowed from another page). It is currently adding a grey bar on top for mobile 
![Screenshot from 2020-09-08 16-57-34](https://user-images.githubusercontent.com/18221058/92538900-c1905f80-f1f4-11ea-91b8-96d99f799a66.png)

2020-09-09 01:02 UTC, ruben1s commented on _data/navigation/main.yml
> -- name: Hack Nights
alexandra commented about it on the issue here https://github.com/hackforla/website/issues/555#issuecomment-674558319

2020-09-09 01:19 UTC, ruben1s commented on toolkit.html
> +    <div class="toolkit__guides-section">
I will work on that

2020-09-09 01:20 UTC, ruben1s commented on toolkit.html
> +            <h3 class="toolkit-flex-item-header"><a href="">Create a Kanban Project Board from 0ur Template</a></h3>
i agree

2020-09-09 01:21 UTC, ruben1s commented on toolkit.html
> +        <div class="suggest-guide-group"><h3>External Resources</h3><button class="toolkit-button btn btn-primary">Suggest a resource</button></div>
Im not sure

2020-09-09 01:21 UTC, ruben1s commented on toolkit.html
> +        <div class="resource-container">
i will work on this

2020-09-12 00:36 UTC, KianBadie commented on _data/navigation/main.yml
> -- name: Hack Nights
@ruben1s I read it, but I didn't see it mention the "Hack Nights" nav option.

2020-09-14 00:57 UTC, closed without merging