added github-handle to Emily Eldar
hackforla/website pull request #7227
Opened 2024-08-06 19:14 UTC by pluto-bell

Fixes #7191

### What changes did you make?
  - Added 'github-handle' under Emily Eldar's name, found in the home-unite-us project

### Why did you make the changes (we will use this info to test)?
  - First good issue.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
No visual changes were made to the website.

<details>
<summary>Visuals before changes are applied</summary>

![image]<img width="442" alt="Screenshot 2024-08-06 at 12 13 46 PM" src="https://github.com/user-attachments/assets/0bc961b1-21a4-4561-b5b0-d29d94795fa3">

</details>

<details>
<summary>Visuals after changes are applied</summary>
  

![image]
<img width="504" alt="Screenshot 2024-08-06 at 12 12 09 PM" src="https://github.com/user-attachments/assets/fe40b2f8-5449-437f-baaf-c3c367baa578">

</details>

2024-08-08 22:03 UTC, TheManTheMythTheGameDev commented
Review ETA: 4 PM 8/8/24
Availability: Every day

2024-08-08 22:46 UTC, TheManTheMythTheGameDev commented on _projects/home-unite-us.md
> +alt: "Home Unite Us"
I don't believe this change was requested in the issue.

2024-08-08 23:03 UTC, TheManTheMythTheGameDev requested changes
Good job with this pull request! The "to" and "from" branches are set up correctly, the relevant issue is linked correctly, and the necessary change has been successfully made.
A few changes I would like to request:
 - I see that you made additional edits to _projects/home-unite-us.md. What was the motivation behind these edits? Even if they are necessary, they should most likely be part of a different pull request.
 - If there are no visual changes made to the website, please do not screen shot code changes. Instead, delete the image section altogether and add a small explanation as to why there are no visual changes. You can say "- No visual changes to the website"
 - You don't need to specify "good first issue" as a reason for why you made the changes.

Thank you for your time and contributions!

2024-08-08 23:31 UTC, t-will-gillis reviewed
Hey @pluto-bell Great job on your first HfLA PR.
- Branches will be ok. For the next time, please include the issue number with the name of your branch, similarly to what is shown in `CONTRIBUTING.md` [Sect. 2.7.b](https://github.com/pluto-bell/website/blob/addHandle/CONTRIBUTING.md#27b-working-on-an-issue-2-create-a-new-branch-where-you-will-work-on-your-issue). In other words, your branch should be named something like: `add-github-handle-7191`. 
- The sections for what was changed and why are fine. You have provided brief, relevant answers here. You can remove the bullet for "- First good issue."
- For the "Screenshots" section, please remove the dropdown images after your comment "No visual changes were made to the website." 
- The code changes are good except as @TheManTheMythTheGameDev mentions, you don't want to go outside the scope of the issue. In the future, the best thing to do when you see things like this will be to bring it up with the issue writer and/or the merge team. Sometimes there is another issue for addressing what you see and sometimes there will be a good reason that the code is written in some way. (Confession- I have been guilty of making little edits like this also...)  

Thank you for working on this!

2024-08-09 02:00 UTC, pluto-bell commented
@t-will-gillis  @TheManTheMythTheGameDev, just want to be clear on what happened with those extra changes. I didn't recall touching anything else so I did some digging and came to realize both line 6 and 114  got modified by some type of code formatter (akin to VS Code's "Prettier" extension).  I disabled my extensions so that shouldn't occur moving forward.

2024-08-10 03:19 UTC, t-will-gillis commented
Hi @pluto-bell Thank you for making the edits. Understand about the auto-formatting. Yes, please change the url line 114 back to single quotes also.

2024-08-13 16:31 UTC, pluto-bell commented
@t-will-gillis great, I've finalized the edits (: 

Should be good to go now!

2024-08-13 17:00 UTC, t-will-gillis approved these changes
Great, thanks for making the change @pluto-bell!

2024-08-14 01:31 UTC, pluto-bell commented
> Good job with this pull request! The "to" and "from" branches are set up correctly, the relevant issue is linked correctly, and the necessary change has been successfully made. A few changes I would like to request:
> 
> * I see that you made additional edits to _projects/home-unite-us.md. What was the motivation behind these edits? Even if they are necessary, they should most likely be part of a different pull request.
> * If there are no visual changes made to the website, please do not screen shot code changes. Instead, delete the image section altogether and add a small explanation as to why there are no visual changes. You can say "- No visual changes to the website"
> * You don't need to specify "good first issue" as a reason for why you made the changes.
> 
> Thank you for your time and contributions!

Hi @TheManTheMythTheGameDev, I think this merge is currently waiting on your review? As it still says "Changes Requested" from you still. I believe everything should be good to go but let me know if not.

2024-08-14 02:37 UTC, roslynwythe commented
@perlaroyerc Please add a comment with your availability and ETA for this PR review

2024-08-14 04:35 UTC, TheManTheMythTheGameDev approved these changes
Hi @pluto-bell! Yes, everything looks good to me now. Sorry if I wasn't clear about which double quotes should be returned to single quotes, but it seems as if that has all been resolved. The description looks good too. Good work on this issue, approved!

2024-08-14 16:27 UTC, merged