Ballot nav card
hackforla/website pull request #724
Opened 2020-09-09 00:12 UTC by Excursionpreneur

Created a project card for BallotNav

2020-09-14 18:10 UTC, KianBadie commented
I see that the id for this project card is "11635254". However, the GitHub data in the [github-data.json](https://github.com/hackforla/website/blob/2785705bc5a9b289fd1d872fbbb6afc518605462/_data/github-data.json#L11959) file has the project id as "288594239". And I think this is the repo that @ExperimentsInHonesty just tagged with "hack-for-la" yesterday 9/14. If we wanted to show the contirbutors from the data I linked, we would have to change the project id to 288594239. I can do that myself too and merge (if there is already a visual confirmation form stakeholders). 

@ExperimentsInHonesty @Excursionpreneur. Was the given repo id from the stakeholder? Is there a specific repo they want us to pull data from besides the one that is linked by their project?

2020-09-15 00:29 UTC, drubgrubby requested changes

2020-09-15 00:29 UTC, drubgrubby commented on .gitignore
> +.idea
Can you explain this change to .gitignore? I'm not sure I understand how it relates to the card.

2020-09-15 00:29 UTC, drubgrubby commented on _projects/ballot-nav.md
> +description: BallotNav is a project of Hack for LA. Hack for LA is a brigade of a Code for America that exists to connect citizens with civic rights and responsibilities. BallotNav helps those who ar
I see a version of a description/blurb in the issue, but it's different from what's written here.  This text clearly came from somewhere, but since I don't see it in the issue, I'm not sure how to review if it is correct.  What's the source of the description text? 
Here's what's in the issue: 
https://github.com/hackforla/website/issues/703#issuecomment-678710811

2020-09-15 00:29 UTC, drubgrubby commented on _projects/ballot-nav.md
> +image-hero: /assets/images/projects/ballot-nav.png
This is not completely clear in the issue, but it seems like the last comment is that the picture of the boy dropping the ballot into the box is going to be on the card, and the map on the hero: https://github.com/hackforla/website/issues/703#issuecomment-679454433

2020-09-15 00:32 UTC, drubgrubby commented
Overall this card looks great.  I have a couple of questions in my review above that may just relate to my not understanding something (which is not uncommon). 

One other note: if you start your PR with "Fixes #703" then it will close the issue when the PR is merged.

2020-09-15 00:37 UTC, drubgrubby commented
One other thing, which doesn't relate to the card as the meeting times aren't on the card, but may relate to the project id issue that Kian mentioned above, under the meetings times it says "undefined", at least when I look at it locally on my machine.  Just mentioning it here so we can figure it out before merging.
<img width="247" alt="Screen Shot 2020-09-14 at 5 33 12 PM" src="https://user-images.githubusercontent.com/68244054/93151482-ec752a80-f6b0-11ea-90cf-ef6f87eb8a12.png">

2020-09-15 05:16 UTC, ExperimentsInHonesty commented on .gitignore
> +.idea
Please remove this file

2020-09-15 05:19 UTC, ExperimentsInHonesty commented on _projects/ballot-nav.md
> +identification: '11635254'
This should be 288594239

2020-09-15 21:57 UTC, KianBadie commented on .gitignore
> +.idea
@drubgrubby @ExperimentsInHonesty Ah, I should have documented this somewhere, my apologies. I was also curious about this file. I asked @cnk and she said it was because @Excursionpreneur was using the IDE [IntelliJ](https://www.jetbrains.com/idea/). We already had `.vscode` in the gitignore for the VSCode IDE. `.idea` is the equivalent for IntelliJ. Should we put that in a different pull request? I think they added it because some unnecessary files were initially being added tho this commit.

2020-09-15 22:09 UTC, KianBadie commented
@drubgrubby Good catch with the meeting times. @ruben1s and @cnk have done some work with the VRMS api, which I think is what the meeting time data depends on. Maybe we can talk about it more at tonight's meeting.

2020-09-16 00:47 UTC, Excursionpreneur commented on .gitignore
> +.idea
I added .idea to the .gitignore file because they were being added when I was trying to push just the ballot-nav.md. And yes, I am using IntelliJ (PHPStorm).

2020-09-16 03:22 UTC, merged