Edits in CONTRIBUTING.md Section 3.1.b #7134
hackforla/website pull request #7279
Opened 2024-08-13 17:17 UTC by patelbansi3009

Fixes #7134 

### What changes did you make?
  - Updated code which starts on Line 825 and ends on Line 855.
  - From
 ```
 
Fixes #replace_this_text_with_the_issue_number

### What changes did you make?
  
  - 
  - 
  - 

### Why did you make the changes (we will use this info to test)?
  
  - 
  - 
  - 

### Screenshots of Proposed Changes To The Website (if any, please do not include screenshots of code changes)
 

<details>
  <summary>Visuals before changes are applied</summary>

  ![image](Paste_Your_Image_Link_Here_After_Attaching_Files)

</details>

<details>
  <summary>Visuals after changes are applied</summary>

  ![image](Paste_Your_Image_Link_Here_After_Attaching_Files)

</details>
``` 
  
- To

 ```
 
Fixes #replace_this_text_with_the_issue_number

### What changes did you make?
  
  - 
  - 
  - 

### Why did you make the changes (we will use this info to test)?
  
  - 
  - 
  - 

### Screenshots of Proposed Changes To The Website (if any, please do not include screenshots of code changes)
 

<details>
  <summary>Visuals before changes are applied</summary>

  ![image](Paste_Your_Image_Link_Here_After_Attaching_Files)

</details>

<details>
  <summary>Visuals after changes are applied</summary>

  ![image](Paste_Your_Image_Link_Here_After_Attaching_Files)

</details>
```

### Why did you make the changes (we will use this info to test)?
  - The instructions in the CONTRIBUTING.md file need to match so that there is no unnecessary ambiguity.
  - For Reviewers: Do not test changes locally, rather test changes at https://github.com/patelbansi3009/website/blob/edits-in-CONTRIBUTING.md-section-3.1.b-7134/CONTRIBUTING.md

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

![image](https://github.com/user-attachments/assets/a549917a-f3c4-4e3c-acaa-2e7f2341da36)

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
![image](https://github.com/user-attachments/assets/123d6d05-df7a-47e2-84ba-07efc942ab4f)

</details>

2024-08-14 05:20 UTC, dcotelessa commented
One of the PR checks is failing. Can we describe why this is faling and then fix?
Thanks.
"Set PR Labels / generate-labels-artifact (pull_request) Failing after 8s"

2024-08-14 17:24 UTC, t-will-gillis requested changes
Hey @patelbansi3009 

As @dcotelessa pointed out, there is a failing PR check. This is not because of anything you did, rather it is due to an unintended conflict with the text in the original issue (which I wrote-ugh).*** Please substitute the new text as shown. Otherwise, your branches look good and you are linking the original issue. For "What changes did you make?", I would recommend simplifying this by removing the actual code changes, and instead stating something to the effect of: "Edited the example of the `pull-request-template.md` in the `CONTRIBUTING.md` file". Otherwise, looks good!

***FYI the reason that "Set PR Labels" workflow is failing is because the text for the example PR template includes the line `... for example 'Fixes # 9876'`. When your PR was created, the bot did a regex search for an issue number appearing after the pattern "Fixes #' and likely found both the correct issue number reference (7134) and the template example (9876). The workflow then crashed when it could not find the example issue nor retrieve its labels. My bad.

2024-08-14 17:24 UTC, t-will-gillis commented on CONTRIBUTING.md
> +  <!--  Important! Add the number of the issue you worked on, for example: 'Fixes #9876'   -->
Hey @patelbansi3009 This is not your error, however please replace line 826 above with:
  ```  
  <!--  Important! Add the number of the issue you worked on  --> 
  ```

2024-08-14 22:49 UTC, dcotelessa commented on CONTRIBUTING.md
> +  <!--  Important! Add the number of the issue you worked on, for example: 'Fixes #9876'   -->
Good to know, thanks, @t-will-gillis

2024-08-21 01:50 UTC, patelbansi3009 commented on CONTRIBUTING.md
> +  <!--  Important! Add the number of the issue you worked on, for example: 'Fixes #9876'   -->
Hey @t-will-gillis , I have updated the code and edited the PR itself, can you help me rerun the PR test?

2024-08-21 01:53 UTC, patelbansi3009 commented
HEy @dcotelessa and @t-will-gillis , Sorry for the delayed update, Please check the PR and let me know if any updates need to be done. Thank You!

2024-08-21 02:01 UTC, t-will-gillis approved these changes
Hey @patelbansi3009 Thank you for making the change. The automations re-ran when you resubmitted and they all went through. 
- Branches look good
- There is a link back to the original issue
- There are concise descriptions of what was done and why
- The screenshots are good- even though they aren't website changes, I feel like it is appropriate to show the `CONTRIBUTING.md`
- The code changes are clean  

Thank you for working on this!

2024-08-22 19:26 UTC, jphamtv commented
Hi @dcotelessa and @pluto-bell, Could you please provide your estimated time for review and your availability? Thanks!

2024-08-22 22:23 UTC, dcotelessa commented
ETA:  Thu-Fri: 3:30-5:30pm
Availability: 1 hr.

2024-08-22 22:27 UTC, dcotelessa approved these changes
Thanks for your fixes!

- The precheck is working now.
- Branch is named well
- Link to issue
- Well written explanations
- I like the screenshots of the changes just to confirm the differences

Great job!

2024-08-23 21:58 UTC, merged