Toolkit final page
hackforla/website pull request #728
Opened 2020-09-13 04:45 UTC by ruben1s

Here is the pull request for the toolkit page

2020-09-13 16:06 UTC, KianBadie commented
Thank you @ruben1s I will look at this Monday 9/14, as I will be taking some time to rest today after the meeting.

2020-09-14 22:21 UTC, KianBadie requested changes
*Summary:*** Thank you for your work, Ruben. Visual changes are needed in order to make a closer match to the figma, as well as some structural/code changes.

Thank you very much for the work, Ruben. The page is coming together more and more. And structurally, the page has improved with the collections and the liquid/jekyll use. Nice work.

In addition to the review comments, there was one question I had that I couldn't make into the form of a comment. The question is: Are `logo-zoom.png`,  `logo-figma.png`, and  `logo-github.png` used anywhere? If not, can we delete it please?

I add some review comments in terms of code/structure/logic. But a good amount of the request in changes stem from the visual aspect of the page. I used the [figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=1548%3A1967) as the standard to meet, and found little differences in the toolkit page. I think implementing them shouldn't be too difficult, since they are styling modifications for small aspects of the page.

I just wanted to emphasize too that the figma is the thing I use to compare to the page, and the standard I have to use in order to review the page. To me, any moderately noticeable changes from the figma are something I have to request a change for. Even if the page is working properly and looks fine (which it does, nice work), I still use the figma as the standard. So I want to recommend before making a pr to just double check the figma and see if there are any noticeable differences. That way, the pr can become more and more focused on the code. What are you thoughts on this?

2020-09-14 22:21 UTC, KianBadie commented on _toolkitResources/template.md
> +---
Is this template being used in the code? If not, do you think we can delete it?

2020-09-14 22:21 UTC, KianBadie commented on _data/navigation/main.yml
> -- name: Hack Nights
So Toolkit is replacing Hack Nights? I know we talked about it last pull request, but I didn't see a definitive answer.

2020-09-14 22:21 UTC, KianBadie commented on _config.yml
> +  toolkitPages:
Is this collection still in use? If not, are we able to delete it?

2020-09-14 22:21 UTC, KianBadie commented on _guide-pages/2FA.html
> +short-description: <p>Hack for LA requires two-factor authentication (2FA) in GitHub for all project contributors.</p>
It seems like this was implemented this way before you edited the file. I think the "<p>" tags should be left out of the front matter. With this guide card specifically, it looks like this is resulting in an extra/empty <p></p> tag. I will try to see what @cnk thinks about this and how we should go about it, since changing the structure of this might affect the guide page itself.

2020-09-14 22:21 UTC, KianBadie commented on _guide-pages/creating-kanban-project.html
> +short-description: Each of Hack for LA’s GitHub project repositories (repos) use issues to track and organize ideas, enhancements, and tasks. All team members will use GitHub issues to communicate in
Was the short-description property implemented for a specific purpose? I wasn't able to see it mentioned on the issue, unless it came up during discussion.

2020-09-14 22:21 UTC, KianBadie commented on _guide-pages/github-issues.html
> +short-description: Each of Hack for LA’s GitHub project repositories (repos) use <a href="https://guides.github.com/features/issues/">issues</a> to track and organize ideas, enhancements, and tasks.
Same point as the 2FA page, I am not sure how I feel about having HTML tags in the guide pages. What do you think?

2020-09-14 22:21 UTC, KianBadie commented on toolkit.html
> +    <div class="toolkit-flex-container">
Are we able to keep all the guide pages under 1 div? As in put the 2 loops into a single div? I feel like it is clearer structurally to have all the guide pages in the same containing divs, sort of like how we have all the project cards in the same div even though they have different statuses. Thoughts?

2020-09-14 22:21 UTC, KianBadie commented on toolkit.html
> +<div class="toolkit-header__text-group">
It appears that this banner text is off-centered vertically and a bit of a thicker font than the figma. Would we be able to make this look more like the figma?

2020-09-14 22:21 UTC, KianBadie commented on toolkit.html
> +                <h3 class="toolkit-flex-item-header"><a href={{ item.provider-link }}>{{ item.title }}</a></h3>
It appears that on the figma, coming soon are not underlined (which I am assuming means unclickable, please correct me if I am wrong). With the current code, coming-soon guides are clickable, and bring the user back to the toolkit page. I think in order to reflect the figma as closely as possible, those links should not be clickable. Would we be able to add that logic? (ex: if no link -> no <a> tag)

2020-09-14 22:21 UTC, KianBadie commented on toolkit.html
> +        </div>
The resource cards are missing the "external link" icon from the figma in the lower righthand corners. Would you be able to add those? If you need some more information with svg's, please let me know.

2020-09-14 22:21 UTC, KianBadie commented on toolkit.html
> +                <h3 class="toolkit-resource-header"><a href="{{item.provider-link}}">{{ item.title }}</a></h3>
It looks like the loop is trying to access a property called `provider-link`, but I think in the toolkitResources collection, the files use a `url` property. Right now, none of the resource links go to their respective sites. Was the `url` property intended to be used here instead?

2020-09-14 22:21 UTC, KianBadie commented on toolkit.html
> +                <h3 class="toolkit-flex-item-header"><a href={{ item.provider-link }}>{{ item.title }}</a></h3>
It looks like in the figma, the titles were left justified. Would we please be able to replicate this?

2020-09-14 22:21 UTC, KianBadie commented on toolkit.html
> +        <div class="suggest-guide-group"><h3>Guides(We Made These!)</h3><button class="toolkit-button btn btn-primary">Suggest a guide</button></div>
Nitpick: can we please add a space before the parenthesis and remove the space after the "!" in order to make a closer match to the figma? "Guides(We Made These! )" -> "Guides (We Made These!)"

2020-09-14 22:21 UTC, KianBadie commented on toolkit.html
> +                <p class="status-text">{{ item.status }}</p>
It looks like the figma displays coming soon as "coming soon" without a "-" in between. Could we make that minor change to match the figma please?

2020-09-14 22:21 UTC, KianBadie commented on _guide-pages/survey-reporting-dashboard-guide.html
>  ---
The guide card for this has 2 images on it overlaying. Do you know what behavior in the code is leading to this? 
![Screenshot from 2020-09-14 15-00-22](https://user-images.githubusercontent.com/18221058/93142551-1ae80b00-f69b-11ea-9f98-2364d123549c.png)

2020-09-14 22:21 UTC, KianBadie commented on toolkit.html
> +                <div class="toolkit-image-container">
The images of the guide cards on the figma extend the full width of the card. It seems with the current code, there are margins on the left and right side. Would we be able to change the styling of that to better match the figma?

2020-09-14 22:21 UTC, KianBadie commented on toolkit.html
> +                <p class="toolkit-flex-item-p">{{ item.short-description }}</p>
It seems the padding/display of the guide descriptions are smaller on the figma. Can we change the styling to try to replicate that?
### Current
![Screenshot from 2020-09-14 14-57-57](https://user-images.githubusercontent.com/18221058/93142876-b0839a80-f69b-11ea-8ac0-f72bc7316c07.png)
### Figma
![Screenshot from 2020-09-14 14-58-12](https://user-images.githubusercontent.com/18221058/93142878-b11c3100-f69b-11ea-8530-c525b3237d3b.png)

2020-09-14 22:21 UTC, KianBadie commented on toolkit.html
> +                <h3 class="toolkit-resource-header"><a href="{{item.provider-link}}">{{ item.title }}</a></h3>
The figma appears to have display the description/title a bit differently (screenshots below). Would we be able to add a little styling so that it is a closer match to the figma?
### Figma
![Screenshot from 2020-09-14 15-08-04](https://user-images.githubusercontent.com/18221058/93143134-2d167900-f69c-11ea-8a32-69f152e4c9f1.png)
### Current
![Screenshot from 2020-09-14 15-08-11](https://user-images.githubusercontent.com/18221058/93143137-2daf0f80-f69c-11ea-8ecc-41798611b0ff.png)

2020-09-14 22:29 UTC, cnk commented on _toolkitResources/template.md
> +---
@KianBadie In the meeting Sunday we decided that we were going to start adding a template file in each of our collections. That way new developers could go directly to the file system to create an item - rather than needing to know that there was a template available in the wiki.

2020-09-15 21:07 UTC, KianBadie commented on _toolkitResources/template.md
> +---
@cnk ah I see. That makes total sense. I will resolve this conversation

2020-09-16 18:43 UTC, KianBadie commented
Will be meeting today at 2:30pm to discuss request changes.

2020-09-16 23:21 UTC, ruben1s commented on _config.yml
> +  toolkitPages:
removed the page from yml file

2020-09-16 23:21 UTC, ruben1s commented on _guide-pages/2FA.html
> +short-description: <p>Hack for LA requires two-factor authentication (2FA) in GitHub for all project contributors.</p>
was resolved

2020-09-16 23:21 UTC, ruben1s commented on _guide-pages/creating-kanban-project.html
> +short-description: Each of Hack for LA’s GitHub project repositories (repos) use issues to track and organize ideas, enhancements, and tasks. All team members will use GitHub issues to communicate in
was resolved

2020-09-16 23:22 UTC, ruben1s commented on toolkit.html
> +                <p class="status-text">{{ item.status }}</p>
made changes

2020-09-16 23:22 UTC, ruben1s commented on toolkit.html
> +                <h3 class="toolkit-resource-header"><a href="{{item.provider-link}}">{{ item.title }}</a></h3>
changed

2020-09-16 23:35 UTC, ruben1s commented on _guide-pages/survey-reporting-dashboard-guide.html
>  ---
im not sure

2020-09-16 23:36 UTC, ruben1s commented
I have made some changes to my branch.

2020-09-17 23:00 UTC, KianBadie commented
@ruben1s Thank you, I am going to review these. For future reference, can you please respond to each review comment with a very brief/quick summary of what you did to fix it? It makes it easier for me to know what to look for in the code and verify each review comment is resolved.

2020-09-17 23:25 UTC, KianBadie requested changes
Adding an additional review to something I noticed with the `status-text`

2020-09-17 23:25 UTC, KianBadie commented on _sass/components/toolkit.scss
> +.status-text {
I believe this class is interfering with an already existing `status-text` class used for the project cards (image below with status text on project cards. See "Submit your pitch" button). Can we please rename this? Maybe something like "guide-status" or whichever you feel is appropriate.
![Screenshot from 2020-09-17 16-07-13](https://user-images.githubusercontent.com/18221058/93537275-f50f7000-f8ff-11ea-8eeb-f93409046a4c.png)

2020-09-17 23:29 UTC, KianBadie commented on _guide-pages/github-issues.html
> +short-description: Each of Hack for LA’s GitHub project repositories (repos) use <a href="https://guides.github.com/features/issues/">issues</a> to track and organize ideas, enhancements, and tasks.
For now, I am going to say html tags in the markdown is fine until we come up with a for sure way to implement stuff like this. This is also a thing for project cards.

2020-09-17 23:31 UTC, KianBadie commented on _guide-pages/survey-reporting-dashboard-guide.html
>  ---
@ruben1s would you please be able to troubleshoot it while you revise the page?

2020-09-17 23:33 UTC, KianBadie commented on toolkit.html
> +        <div class="suggest-guide-group"><h3>Guides(We Made These!)</h3><button class="toolkit-button btn btn-primary">Suggest a guide</button></div>
It appears the space is gone before the closing parenthesis ")", however there is still no space between "Guides" and the opening parenthesis "(" .

2020-09-17 23:47 UTC, KianBadie commented on toolkit.html
> +                <h3 class="toolkit-resource-header"><a href="{{item.provider-link}}">{{ item.title }}</a></h3>
I would say there still is a noticeable difference between the figma and the toolkit page for the resource cards. If you look at them sided by side, do you agree?

2020-09-17 23:51 UTC, KianBadie commented on _guide-pages/2FA.html
> +short-description: <p>Hack for LA requires two-factor authentication (2FA) in GitHub for all project contributors.</p>
@ruben1s I discussed with cnk and we decided the HTML in markdown tags would be ok for now. However, I noticed the other guide pages have no `<p></p>` tags surrounding the short description, but this one does. This results in an empty `<p></p>` tag in the DOM. If it is not necessary, can we remove the <p> tags?

2020-09-17 23:56 UTC, KianBadie commented
Some of the review comments were resolved with the latest commit. There are still unresolved issue comments that need attention that were not attended to in the last commit.

2020-09-18 19:47 UTC, ruben1s commented on _sass/components/toolkit.scss
> +.status-text {
renamed to toolkit-status-text

2020-09-18 19:57 UTC, ruben1s commented on _guide-pages/survey-reporting-dashboard-guide.html
>  ---
fixed. had to change the one of the svg <path>

2020-09-18 19:58 UTC, ruben1s commented on _guide-pages/2FA.html
> +short-description: <p>Hack for LA requires two-factor authentication (2FA) in GitHub for all project contributors.</p>
let me remove them

2020-09-18 19:59 UTC, ruben1s commented on _guide-pages/2FA.html
> +short-description: <p>Hack for LA requires two-factor authentication (2FA) in GitHub for all project contributors.</p>
removed

2020-09-18 20:55 UTC, ruben1s commented
I made some of the changes mentioned. Here are the screenshots of the current state.
![screencapture-localhost-4000-toolkit-2020-09-18-13_54_23](https://user-images.githubusercontent.com/33906590/93644321-9bb64800-f9b6-11ea-8c48-574b76d0e700.png)
![Uploading screencapture-localhost-4000-toolkit-2020-09-18-13_53_47.png…]()

2020-09-18 20:58 UTC, ruben1s commented on toolkit.html
> +                <p class="toolkit-flex-item-p">{{ item.short-description }}</p>
changed svg to cover entire width of card

2020-09-18 20:58 UTC, ruben1s commented on toolkit.html
> +                <div class="toolkit-image-container">
changed svg to cover entire width of the card

2020-09-18 20:59 UTC, ruben1s commented on toolkit.html
> +                <p class="status-text">{{ item.status }}</p>
changed the class to toolkit-status-text

2020-09-18 21:00 UTC, ruben1s commented on _data/navigation/main.yml
> -- name: Hack Nights
again it was mentioned on the issue by alex. it is supposed to temporarily take place of the hacknights link until the hacknights page is completed.

2020-09-19 00:40 UTC, KianBadie commented on _data/navigation/main.yml
> -- name: Hack Nights
@ruben1s For sure sounds good :+1:

2020-09-19 00:49 UTC, KianBadie commented on toolkit.html
> +                <div class="toolkit-image-container">
Would you be able to provide some screenshots? I pulled from the branch and the svg images still have left and right margins like this for me. Do they look different for you?
![Screenshot from 2020-09-18 17-48-30](https://user-images.githubusercontent.com/18221058/93655280-48a0bd00-f9d7-11ea-9483-060da6693117.png)

2020-09-19 00:51 UTC, KianBadie commented on toolkit.html
> +                <p class="toolkit-flex-item-p">{{ item.short-description }}</p>
Thank you @ruben1s, the purpose of this review comment was to change the styling of the guide descriptions so that it better matches the figma. Would we be able to add that?

2020-09-19 01:55 UTC, KianBadie submitted a review, later dismissed

2020-09-19 01:55 UTC, KianBadie commented on toolkit.html
> +                    {% include {{ item.link-svg }} %}
Thank you for adding this. Do you think it would be cleaner to include the svg directly with something like
```
{% include svg/outer-link.svg %}
```
and remove the link-svg property from each resource card? Since the link svg will always be displayed for each resource card, I figured we could access directly in this line. What do you think?

2020-09-19 02:56 UTC, ruben1s commented on toolkit.html
> +        <div class="suggest-guide-group"><h3>Guides(We Made These!)</h3><button class="toolkit-button btn btn-primary">Suggest a guide</button></div>
changed the text

2020-09-19 03:07 UTC, ruben1s commented on toolkit.html
> +                <h3 class="toolkit-flex-item-header"><a href={{ item.provider-link }}>{{ item.title }}</a></h3>
addressed it with not-clickable class

2020-09-19 03:09 UTC, ruben1s commented on toolkit.html
> +                <h3 class="toolkit-flex-item-header"><a href={{ item.provider-link }}>{{ item.title }}</a></h3>
addressed. changed headers to be left aligned

2020-09-19 03:26 UTC, ruben1s commented on toolkit.html
> +<div class="toolkit-header__text-group">
addressed and pushed.

2020-09-19 03:28 UTC, ruben1s commented on toolkit.html
> +                <div class="toolkit-image-container">
i am not able to fix that. the padding is at 0. if you look at the mobile views, the svgs are full width. I think it is an issue with using flexbox. I can troubleshoot it if you would like. I am not going to beat a dead horse.

2020-09-19 03:28 UTC, ruben1s commented on toolkit.html
> +                <p class="toolkit-flex-item-p">{{ item.short-description }}</p>
Did it as best as i could.

2020-09-19 03:29 UTC, ruben1s commented on toolkit.html
> +                    {% include {{ item.link-svg }} %}
Im not too sure.

2020-09-19 03:36 UTC, ruben1s commented
here are the latest screenshots:
![screencapture-localhost-4000-toolkit-2020-09-18-20_36_03](https://user-images.githubusercontent.com/33906590/93658233-adb3dd00-f9ee-11ea-89c6-98044271eaff.png)
![screencapture-localhost-4000-toolkit-2020-09-18-20_35_45](https://user-images.githubusercontent.com/33906590/93658235-ae4c7380-f9ee-11ea-9f47-51458ce67f3c.png)
![screencapture-localhost-4000-toolkit-2020-09-18-20_29_39](https://user-images.githubusercontent.com/33906590/93658236-aee50a00-f9ee-11ea-9077-2a64faf8c016.png)

2020-09-19 20:35 UTC, KianBadie commented on toolkit.html
> +<div class="toolkit-header__text-group">
@ruben1s I pulled the latest commits and it appears to still be offcentered and a different font
![Screenshot from 2020-09-19 13-33-55](https://user-images.githubusercontent.com/18221058/93688735-d1256900-fa7c-11ea-8f21-00e68fc75452.png)

2020-09-19 20:43 UTC, KianBadie commented on toolkit.html
> +                <h3 class="toolkit-flex-item-header"><a href={{ item.provider-link }}>{{ item.title }}</a></h3>
It is non clickable now. Thank you for the changes @ruben1s. However, the font size is now different. I will create a new review comment for that.

2020-09-19 23:22 UTC, KianBadie commented
Me and @ruben1s are working on the last visual touch ups today and tomorrow morning. I intend on having this merged before tomorrow's meeting based purely on matching the figma visually. I think there are some structural changes that should happen to the code, but I think it is more important to get this page out.

2020-09-20 16:49 UTC, KianBadie commented
See my comment [here](https://github.com/hackforla/website/issues/555#issuecomment-695808828) for progress

2020-09-25 20:15 UTC, KianBadie commented
Last action items needed before merging:

Action items since 9/20 meeting:
- [ ] Continue to fix visual bugs and move styling towards figma
- [ ] Make "coming soon" guide cards have black titles, so that it is clear they are not clickable
- [ ] Add dynamic padding to with for text within resource/guide cards
- [ ] Increase size of svg's so that they scale better on desktop
- [ ] Fix comingsoon text so that it displays properly (responsive)
- [ ] Make sure font sizes of recourse and guide pages are same

An action item that I personally think should be checked
- [ ] Verify that resource/guide cards do display dynamically (as screen size changes, more or less cards will appear in a given row)

2020-09-26 23:23 UTC, ruben1s commented
Update:
![screencapture-0-0-0-0-4000-toolkit-2020-09-26-16_23_15](https://user-images.githubusercontent.com/33906590/94352018-a2773780-0014-11eb-9ec9-8a5e7406b933.png)
![screencapture-0-0-0-0-4000-toolkit-2020-09-26-16_23_03](https://user-images.githubusercontent.com/33906590/94352019-a30fce00-0014-11eb-8b8e-0aa251fb5b49.png)
![screencapture-0-0-0-0-4000-toolkit-2020-09-26-16_22_46](https://user-images.githubusercontent.com/33906590/94352021-a3a86480-0014-11eb-90e6-da86eb6f729a.png)

2020-09-27 15:33 UTC, KianBadie commented
New pr #750 will replace this one

2020-09-27 15:33 UTC, closed without merging