Fix bug in "Schedule Friday" workflow
hackforla/website pull request #7323
Opened 2024-08-20 22:35 UTC by t-will-gillis

Fixes #7322

### What changes did you make?
  - In `add-label.js`, removed the section after "check if label exists on issue before attempting to remove it" from  the `removeLabels()` function 
  - Changed the `try...catch` block by adding a check if `err.status === 404`

### Why did you make the changes (we will use this info to test)?
  - The section noted was extraneous. The `github.request` will delete the label if it exists or return a "404" if it does not. The `try...catch` block can listen for the `err.status === 404` and log that the label does not exist, or post the full error for any other.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
- Does not affect website visuals
- [Log from repo](https://github.com/t-will-gillis/website/actions/runs/10479730394/job/29025945744) showing successful run by removing the correct labels and posting the message that the label does not exist if so.

2024-08-27 07:00 UTC, mrodz commented
**Availability** MW 6:30-9pm, TThF 4-9pm, Weekends 9am-5pm
**ETA** EOD 8/27

2024-08-28 04:12 UTC, mrodz requested changes
Hi @t-will-gillis, your changes look good and the commits appear to fix the problem associated with the workflow. It is wise to check for the `pull_request` property—good choice to filter PRs.

I agree that the issue label fetch is superfluous; removing this check will also help manage our organization's token rate limit.

### A few comments
- Any non-404 error message will not be logged. I will request changes just because it is a trivial fix. https://github.com/hackforla/website/blob/0c135f96a476602463eac8503fd496d61914688f/github-actions/trigger-schedule/add-update-label-weekly/add-label.js#L241
- The edits to this debug statement no longer include the issue number. If you are trying to remove the verbosity of the logs or match the style of the other debug messages, ignore this comment.
  - New: https://github.com/hackforla/website/blob/0c135f96a476602463eac8503fd496d61914688f/github-actions/trigger-schedule/add-update-label-weekly/add-label.js#L236
  - Old: https://github.com/hackforla/website/blob/806c8b9635cdbdfbc8c44469faf874add5a343ad/github-actions/trigger-schedule/add-update-label-weekly/add-label.js#L244

 Besides this, everything looks up to par. I was able to follow through why you made your changes, and your changes make sense intuitively. 

Good stuff Will! Thank you for including me on this review :)

2024-08-28 21:40 UTC, t-will-gillis commented
Hey @mrodz  I edited the `console.error()` message in `removeLabels()` to log `err` as it did previously. For the message shown in new line 236, it was intentional to remove `issueNum` - I believe that it reads better in the workflow logs without it. But now that you brought it up, I edited the log statement within `addLabels()` (at line 263) for consistency with the others.

Thanks for reviewing this! Please let me know if there is anything else you see.

2024-08-28 23:54 UTC, mrodz approved these changes
Awesome! Thank you @t-will-gillis. Approving now.

2024-08-29 02:05 UTC, t-will-gillis commented
Thanks @mrodz!

2024-08-29 02:05 UTC, merged