Added info and link to VRMS guide for updating meeting details
hackforla/website pull request #7325
Opened 2024-08-21 02:17 UTC by 8alpreet

Fixes #7273

### What changes did you make?
- I removed 
<details>
  <summary><strong>Click here</strong> to see image of existing format</summary>
  <p><strong>Entried are hard to distinguish</strong></p>
  <img width="955" border="green 5px" alt="preview of template on Github" src="https://github.com/user-attachments/assets/e145693c-3ec1-45e1-ac39-433a06a55089">
</details>

  - I added a note under the _Resources_  section regarding updates to meeting details in the file: `.github/ISSUE_TEMPLATE/communities-of-practice-information-updates.yml`
  - Link to file in my repo: LINK.

### Why did you make the changes (we will use this info to test)?
  - The changes were made to help users of the "communities of practice information updates" template. The note informs users how and where they can make updates to meeting details.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
- No visual changes to website.

2024-08-22 23:22 UTC, 8alpreet commented
@roslynwythe Ready for review!

2024-08-25 17:22 UTC, tamara-snyder commented
**Review ETA:** End of day 8/25/2024
**Availability:** 2-5PM Sunday

2024-08-25 19:49 UTC, tamara-snyder requested changes, later dismissed
Hi Balpreet, nice work on this! I think you did a bit more than what was called for, so I left some comments on what needs to be changed back. You really only need to add that one line as shown in the second action item of #7325, and everything else should stay the same as it was before. Thanks!

2024-08-25 19:49 UTC, tamara-snyder commented on .github/ISSUE_TEMPLATE/communities-of-practice-information-updates.yml
> +          ### Resources
Hi Balpreet, thanks for working on this! I believe a few lines of code were removed here that were not specified in this issue's instructions:
```
  - type: markdown
    attributes:
      value: "### Resources"
```
Can you please bring them back to the way they were before?

2024-08-25 19:49 UTC, tamara-snyder commented on .github/ISSUE_TEMPLATE/communities-of-practice-information-updates.yml
> +          1. Folder where files are in the repo: https://github.com/hackforla/website/tree/gh-pages/_data/internal/communities
I appreciate your initiative here! However, I didn't see turning this list into a numbered list or changing these lines in the issue's instructions. Can you please revert lines 78-79 to how they were before?

2024-08-25 19:49 UTC, tamara-snyder commented on .github/ISSUE_TEMPLATE/communities-of-practice-information-updates.yml
> +          3. If you need to update your meeting times, names, dates, or frequency, please see the [VRMS User Guide](https://github.com/hackforla/VRMS/wiki/User-Guide). The HackforLA.org website gets
Line 80 looks good! This is the only line in the file that should change at the end of this issue — just make sure it's part of an unordered list as opposed to numbers. Nice work!

2024-08-25 21:35 UTC, 8alpreet commented
Hi @tamara-snyder, thanks for your review! I acknowledge that the changes were not specified in the issue, but I think they are sensible and warranted. I briefly discussed the changes with @roslynwythe before submitting my PR. Let's wait for her review.

2024-08-27 02:45 UTC, tamara-snyder commented
@8alpreet fair enough! I agree the changes make sense and I was just going off of what I read in the issue instructions. If the other changes are fine with Roslyn then I'm happy too.

2024-09-02 18:20 UTC, t-will-gillis reviewed
Hey @8alpreet The combining of the two `-type: markdown` entries appears to work just fine and simplifies the code, so I think this is a good change!

Regarding the edits to the "Resources": I agree that there should be some list element here. Although we are inconsistent throughout the templates, I believe that the bullets are preferable to numbers only because there is one other template I see using numbers in the "Resources" (`image-tag-refactor...`) but four using bullets (`alt-text-audit..`, `creating-a-yml...`, `design-sys-admin...`, and `spell-check-audit..`). )There are 8-12 with nothing.

2024-09-02 18:40 UTC, 8alpreet commented
Hi @t-will-gillis 

Thank you for your review and being open to changes not outlined in the issue. I have switched the numbers to bullet points.

2024-09-02 18:43 UTC, 8alpreet commented
@tamara-snyder

Hi Tamara, thank you for your thorough review earlier. Also, thanks for your patience and thanks in advance for reviewing again.

2024-09-02 18:50 UTC, t-will-gillis commented
Hi @8alpreet - one more minor request: although this doesn't change the appearance of the template, would you please revise the indentation from the current four spaces to two spaces to match the indentation of the rest of the file

2024-09-03 15:30 UTC, 8alpreet commented
@t-will-gillis 

Okay, I removed the extra spaces.

2024-09-03 16:05 UTC, t-will-gillis approved these changes
@8alpreet Looks good!

2024-09-04 02:38 UTC, tamara-snyder approved these changes
@8alpreet Looks good to me as well!

2024-09-04 03:48 UTC, merged