refactor the img tag
hackforla/website pull request #7341
Opened 2024-08-22 08:04 UTC by blaycoder

Fixes #replace_this_text_with_the_issue_number

### What changes did you make?
  - I changed an img HTML tag ending with a slash (<img.../>) to an img tag without an ending slash (<img...>).
  -
  -

### Why did you make the changes (we will use this info to test)?
  - So that the codebase is consistent with how we use img HTML tags.
  - https://github.com/blaycoder/website/blob/refactor-img-tag-7094/CONTRIBUTING.md
  -

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

![image](Paste_Your_Image_Link_Here_After_Attaching_Files)

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
![image](Paste_Your_Image_Link_Here_After_Attaching_Files)

</details>

2024-08-24 03:07 UTC, daras-cu requested changes
Hi @blaycoder, thanks for working on this issue!

- The branches are set up correctly and the original issue is linked in your PR
- You explained the changes you made and why
- No visual changes to the website and CONTRIBUTING.md displays correctly on your branch

A couple minor things to change:
- It looks like when you edited the img tag you also added a space at the beginning of the line. This should be removed so that the indentation is consistent with the preceding lines
- I would probably make your PR title and description a little more specific by including the file and section the changes were made in, similar to the title of the original issue (#7094)

Overall good work on this issue, let me know in a comment or re-request a review when you've made adjustments.

2024-08-28 16:39 UTC, blaycoder commented
Hi @daras-cu 
Thank you so much for the observation, I have made the changes and equally pushed to the branch. 
Kindly review

2024-08-28 18:53 UTC, mSharifHub reviewed
I have not approved but I pointing out a readability issue to what line of code node is referring too. Is just an observation. Overall,  I do not see no issues.

2024-08-28 18:53 UTC, mSharifHub commented on CONTRIBUTING.md
>  **Note:** It should create a URL that looks like the following -> `https://github.com/<your_GitHub_user_name>/website`.
If this comment belongs to the `<img src="https://user-images.githubusercontent.com/21162229/137045294-3d46b28c-edbb-410c-98f1-13940ecc5c5f.jpg">` then would be more clear by commenting on top of the line of code.

2024-08-29 00:46 UTC, daras-cu approved these changes
Hi @blaycoder, thanks for adjusting the whitespace. The changes look good in your branch, thanks for working on this issue!

2024-08-29 04:02 UTC, vorleakyek commented
Review ETA: 8/29   
Availability: M-F evening

2024-08-30 02:53 UTC, vorleakyek approved these changes
Nice work! It looks correct. 

Verified that the image is showing up with this testing environment.  
https://github.com/blaycoder/website/blob/refactor-img-tag-7094/CONTRIBUTING.md

2024-08-31 21:59 UTC, merged