Add tyler thome GitHub handle 7175
hackforla/website pull request #7346
Opened 2024-08-23 20:07 UTC by ihop-56

Fixes #7175 

### What changes did you make?
- Added the `github-handle:` field under `name: Tyler Thome` in the `_projects/home-unite-us.md` file. This field was added without a value as per the issue's instructions.

### Why did you make the changes?
- The change was made to prepare the project file for future enhancements, reducing redundancy by standardizing the GitHub handle field.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
No visual changes to the website.

2024-08-23 21:06 UTC, bexux commented
Review ETA: 8 PM pacific 8/24/24
Availability: 5-8 PM Friday, Noon - 8PM Saturday

2024-08-23 21:35 UTC, bexux commented on _projects/home-unite-us.md
> +    github-handle: tylerthome
Almost there - Should be `github-handle:` with no value present yet.

2024-08-23 21:39 UTC, bexux requested changes
This is very close to being done! Looks like you had the code correct on your first commit, but then the second commit, `Changes before switching branches` added in value that is not needed for this issue. 

The PR description reads well, branching done correctly, and issue attached correctly. Just need the small change.

2024-08-23 23:08 UTC, bexux commented
@ihop-56  I noticed you have a second PR - [7309](https://github.com/hackforla/website/pull/7309) pushed up to address issue 7175. I assume this PR is in response to @codyyjxn's feedback to have the issue number in the branch name?

2024-08-23 23:23 UTC, ihop-56 commented
Yes, that's right

On Fri, Aug 23, 2024, 7:08 PM Rebecca ***@***.***> wrote:

> @ihop-56 <https://github.com/ihop-56> I noticed you have a second PR -
> 7309 <https://github.com/hackforla/website/pull/7309> pushed up to
> address issue 7175. I assume this PR is in response to @codyyjxn
> <https://github.com/codyyjxn>'s feedback to have the issue number in the
> branch name?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/hackforla/website/pull/7346#issuecomment-2307910575>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BA5P266COG2VWL65OYY4UXLZS66GZAVCNFSM6AAAAABNAZKFPCVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGMBXHEYTANJXGU>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-08-25 14:05 UTC, ihop-56 commented
Hi @bexux,

I've made the requested changes:
- Removed the value from `github-handle` for Tyler Thome as per your feedback.

Please review and let me know if any further adjustments are needed.

Thank you for your guidance!

2024-08-25 15:39 UTC, t-will-gillis commented
HI @ihop-56 please don't forget to re-request a review by selecting the chasing arrows next to the reviewer's handle when you make changes to address a reviewer's comments:
<img width="472" alt="Screenshot 2024-08-25 083845" src="https://github.com/user-attachments/assets/c9930585-5c6d-49c9-9a8a-4bb9d8e9479a">

2024-08-25 21:39 UTC, codyyjxn approved these changes
Nice @ihop-56 this looks great

2024-08-25 21:46 UTC, 8alpreet approved these changes
Hi @ihop-56,

Thanks for making changes in accordance to feedback on this and the previous PR. 

### Opinion:
* The PR looks good, but I would encourage you to do one last thing: squash the commits. I'm not sure if this is practice on this project, but merging three commits will pollute the the commit history unnecessarily.

### Nitpick:
* Not necessary, but you could capitalize "Tyler Thome" in the PR title.

I am approving, but urge you to squash the commits.

2024-08-26 04:45 UTC, t-will-gillis commented
Hey @8alpreet and @ihop-56 FYI the commits are squashed when we merge the PRs, thus we do not ask anyone to squash their commits. Devs can if they would like to, but since we 'squash and merge' it is not needed for the PR

2024-08-26 15:08 UTC, bexux approved these changes
Looks great! Thank you for making the changes.

2024-08-26 21:58 UTC, 8alpreet commented
> Hey @8alpreet and @ihop-56 FYI the commits are squashed when we merge the PRs, thus we do not ask anyone to squash their commits. Devs can if they would like to, but since we 'squash and merge' it is not needed for the PR

Got it, thanks @t-will-gillis!

2024-08-27 15:55 UTC, kgold2018 approved these changes
Hi  @ihop-56 ! Looks good! Thank you for making the changes.

2024-08-27 17:01 UTC, merged