Implemented check for changes in Wins-form (Responses) spreadsheet within Wins Data automation
hackforla/website pull request #7409
Opened 2024-09-07 22:17 UTC by iancooperman

Fixes #4134 
### What changes did you make?
  
  -  Added a check that compares the current content of `_wins-data.json` to that of Wins-form (Responses) to see if any changes have been made (e.g. new win, hiding of win, etc.)
 
### Why did you make the changes (we will use this info to test)?
  
  - To halt the creation of unnecessary pull requests when no significant changes have been made
  - To eliminate the need to examine daily commits for changes
 
### Screenshots of Proposed Changes To The Website (if any, please do not include screenshots of code changes)
 
- No direct visual changes to the website

2024-09-07 22:21 UTC, iancooperman commented
Proposed changes to Wins Form Admin Guide: https://docs.google.com/document/d/1UTv4msXoThx7AwX7g2c8WgBLnwIJeRkaHePvbvI_3sg/edit?usp=sharing

2024-09-07 22:35 UTC, iancooperman commented on google-apps-scripts/gh-requests/Code.js
> +  const [sha, content] = getWins(fileName);
This function can be removed without harm. It is temporarily left there in case more testing needs to occur involving `getWins()` in `gh-requests`.

2024-09-09 08:18 UTC, roslynwythe requested changes
Thank you @iancooperman for your work on this complex issue.  On the first line of the PR, the issue number (after "Fixes") is incorrect,  Please correct that so the PR will be linked correctly to the issue.  Thank you.

2024-09-09 22:16 UTC, codyyjxn requested changes
@iancooperman Thank you for taking on this issue. The branch name looks good only thing is that I am confused which issue you fixed please correct that if possible. Other than that everything seems to be concise.

2024-09-10 03:01 UTC, iancooperman commented
@roslynwythe There was a small typo in the linked issue number. Thanks for catching that. Let me know if anything else needs to be done.

2024-09-12 01:20 UTC, codyyjxn approved these changes, later dismissed

2024-09-21 10:45 UTC, roslynwythe requested changes
Hi @iancooperman I'm still testing but I need to ask you to update line 62

2024-09-21 10:45 UTC, roslynwythe commented on google-apps-scripts/gh-requests/Code.js
> +    "head": "iancooperman:update-wins-data",
Please change this back to elizabethhonest

2024-09-22 04:18 UTC, roslynwythe commented on google-apps-scripts/wins-form-responses/Code.js
>      console.log('Ending script...')
Please make the console log output message more descriptive

2024-09-22 04:33 UTC, roslynwythe requested changes
Hi @iancooperman so far the code looks great but
commit 003c4361a95158abbd547ea1f7c0e9dd3ff3873e includes changes to google-apps-scripts/gh-requests/Code.js, which we do not want included in the git repository.

2024-09-22 04:33 UTC, roslynwythe commented on google-apps-scripts/wins-form-responses/Code.js
> +      console.log('Ending script...')
Please make the console log output message more descriptive

2024-09-22 17:05 UTC, iancooperman commented on google-apps-scripts/wins-form-responses/Code.js
> +      console.log('Ending script...')
@roslynwythe Just to confirm, you're saying to remove the changes to `appscript.json`, right? Your initial comment says `Code.js` but the commit you linked is to `appscript.json`.

2024-09-25 01:25 UTC, iancooperman commented on google-apps-scripts/wins-form-responses/Code.js
> +      console.log('Ending script...')
> @roslynwythe Just to confirm, you're saying to remove the changes to `appscript.json`, right? Your initial comment says `Code.js` but the commit you linked is to `appscript.json`.

I have assumed this is the case and reverted commit [003c436](https://github.com/hackforla/website/commit/003c4361a95158abbd547ea1f7c0e9dd3ff3873e).

2024-10-09 02:04 UTC, iancooperman commented
@roslynwythe I would appreciate your rereview.

2024-10-13 18:27 UTC, t-will-gillis commented
Hey @roslynwythe Do you have any additional comments on this PR? Please let us know-thanks!

2024-10-18 23:08 UTC, roslynwythe approved these changes
Great job @iancooperman on this issue which involved an extensive setup and analysis to determine the best strategy to detect changes in the wins data
- Code changes are clean and correct
- PR is well-formed and descriptive
- Changes have been tested in a test repository
I created a test environment in `HfLA website Admin/HfLA website Admin/testing_PR_7409`and tested the PR against the production repository, in order to confirm that `_wins-data.json` is pushed to the the elizabethonest/website repository only when there are changes compared to the current contents of that repository. 

Your work completing this issue will help us be more efficient in managing wins data updates.  Thank you!

2024-10-18 23:34 UTC, merged