Removing instances of "test" as a substring in the events page - #6369
hackforla/website pull request #7464
Opened 2024-09-16 03:12 UTC by dcotelessa

Fixes #6369

### What changes did you make?
  
  - Created new function to filter VRMS data based on "test" found in the entry name (case-insensitive)
  - Applied the function to the VRMS data
  - Checked the events page to see test entried removed

### Why did you make the changes (we will use this info to test)?
  
  - On `/assets/js/utility/vrms-events.js`, the code-block rendering events from the VRMS to the website contain "test" events
  - These test events are idenitified by "test" found in the entry name (case-insensitive)
  - On Docker, the filtering of "test" events can be seen on http://localhost:4000/events/

### Screenshots of Proposed Changes To The Website (if any, please do not include screenshots of code changes)
 

<details>
<summary>Visuals before changes are applied</summary>

![image](https://github.com/user-attachments/assets/65b3e01e-ab56-47f4-810e-203d9535d1fc)

</details>

<details>
<summary>Visuals after changes are applied</summary>

![image](https://github.com/user-attachments/assets/1f3a6c65-02a1-4686-b888-2f50cc66fbc9)

</details>

2024-09-16 18:29 UTC, dcotelessa commented
ETA: 2 hrs
Availability: 3-5pm M-F

2024-09-17 06:34 UTC, vorleakyek commented
Review ETA: by Thursday (9/19) or Friday (9/20) 
Availability: M-F evening

2024-09-18 00:58 UTC, codyyjxn approved these changes, later dismissed
@dcotelessa Great job on taking on this issue. The changes are clear and the title is also concise on the tings that were changed. I ran the test and everything seemed to work as intended.

2024-09-19 03:40 UTC, vorleakyek requested changes
Nice work on adding the `vrmsDataFilter` function. But, we should update the variable name "vrmsData" to "vrmsDataFilter" in the comment to avoid any confusion later.

2024-09-19 03:40 UTC, vorleakyek commented on assets/js/utility/vrms-events.js
>  /* vrmsDataFetch calls sortByDate function and passes vrmsData variable, current page which can either be "events" for the right-col-content.html page or
@dcotelessa, do you think "passes vrmsData variable" should be changed to "passes filteredVrmsData variable" since you updated the variable name in the sortByDate function?

2024-09-19 21:23 UTC, dcotelessa commented on assets/js/utility/vrms-events.js
>  /* vrmsDataFetch calls sortByDate function and passes vrmsData variable, current page which can either be "events" for the right-col-content.html page or
I think that is more consistent.

2024-09-20 19:11 UTC, dcotelessa commented
Wanted to mention this is only `/events` page and not `/events-check` page that also uses `vrmsData` to show events.

2024-09-21 05:02 UTC, vorleakyek commented on assets/js/utility/vrms-events.js
> +const vrmsDataFilter = (vrmsData) => vrmsData.filter(data => data.name.match(/(?<=\W|^)(test(ing)?)(?=\W|$)/i) === null);
@dcotelessa, regular expression is not my strong area, but do you think replacing `/(?<=\W|^)(test(ing)?)(?=\W|$)/i` with a simpler condition such as `/\btest(ing)?\b/i` would work? I did a few tests and they both show the same result. I think what you have is fine, but it just seems a bit more complicated to understand at first.

2024-09-21 20:14 UTC, codyyjxn commented on assets/js/utility/vrms-events.js
> +const vrmsDataFilter = (vrmsData) => vrmsData.filter(data => data.name.match(/(?<=\W|^)(test(ing)?)(?=\W|$)/i) === null);
Yes they both do test the same. One is of course much easier to read.

2024-09-21 20:32 UTC, codyyjxn submitted a review, later dismissed
@dcotelessa Nice work! 
1. The function you developed is clear and easy to follow.
2. You applied it to the VRMS data accurately.
3. Including the before-and-after process effectively highlights the changes made.
4. Your thoughtful approach makes it easy for others to understand your work.

2024-09-22 05:39 UTC, dcotelessa commented on assets/js/utility/vrms-events.js
> +const vrmsDataFilter = (vrmsData) => vrmsData.filter(data => data.name.match(/(?<=\W|^)(test(ing)?)(?=\W|$)/i) === null);
I tested with \b as well .Yeah, that is easier to read (I wanted to include dashes and I used a previous regex that didn't figure that.) Will update. Thanks!

2024-09-23 16:56 UTC, codyyjxn approved these changes

2024-09-23 19:28 UTC, vorleakyek approved these changes
Verified that "Test-EventName" is no longer showing up on the events page on the Hack for LA website. Thanks!

2024-09-24 00:49 UTC, merged