Change the label that is added when dev attempts to open multiple issues
hackforla/website pull request #7466
Opened 2024-09-17 01:46 UTC by izma-mujeeb

Fixes #7300

### What changes did you make?
  
  - I added three main changes for this issue. I changed the variable name of "ready for dev lead" with the variable of "ready for prioritization". I then had to change any code that utilized the previous variable with the new variable. Lastly, I had to change JSDoc comment to better reflect the description of the new variable. 

### Why did you make the changes (we will use this info to test)?
  
  - The main purpose of this change was to make it easier when a developer self-assigns an issue, when they are already working on an issue that hasn't been completed or merged. Typically, when a developer assigns an issue and they are still working on an another issue, the "Issue Trigger" workflow is triggered. This trigger un-assigns the developer from the second issue and moves it to the "New Issue Approval" column and applies the ready for dev lead label. We need the trigger to apply the ready for prioritization label instead, so that Bonnie can re-prioritize the issue as appropriate. This issue helps  with applying the correct labels to the issue.  

### Screenshots of Proposed Changes To The Website (if any, please do not include screenshots of code changes)
 

- No visual changes to the website

2024-09-17 21:31 UTC, k-cardon requested changes
Looks good! The one change I've requested is to remove the comment on line 81, for clarity; otherwise everything looks in order and I confirmed no visual changes to site.

2024-09-17 21:31 UTC, k-cardon commented on github-actions/trigger-issue/add-preliminary-comment/preliminary-update-comment.js
> +      await addLabel(READY_FOR_PRIORITIZATION); // Add 'ready for dev lead' label
For clarity, please remove the comment here that says `// Add 'ready for dev lead' label` , since the label has now been changed (also was mentioned on the issue). Otherwise looks good!

2024-09-18 01:43 UTC, 8alpreet commented
Availability: weekdays 3 - 7pm
ETA: Sep 18 7pm

2024-09-18 03:03 UTC, mmcclanahan commented
Availability: 9am - 1pm
ETA: 9/17 9pm

2024-09-18 06:29 UTC, mmcclanahan approved these changes
Nice Work!

correct:
from/to branch 
PR title is clear
What/Why is descriptive 
Changes made match required changes from issue
No physical changes to website

Good work!

2024-09-18 17:50 UTC, k-cardon approved these changes
Great--looks correct now, without that extraneous comment. Approved!

2024-09-18 18:29 UTC, 8alpreet approved these changes
Hi @izma-mujeeb,

Great job on the issue! You've done all the standard items such as:
* good branch name
* descriptive PR title
* correct lines of code changed

Specifically, you did an excellent job with the PR comment by providing all the necessary details.

In the spirit of continuous improvement, here are two opinions and nitpicks:
1. Similar to how you used quotes "New Issue Approval" you could use them for "ready for dev lead" or even use backticks so that it looks like this: `ready for dev lead`. Again this is just an opinion and a very minor improvement.
2. I think the title is descriptive but not concise or precise; though, it certainly gets the job done. I used an LLM to brainstorm a bit and came up with "Modify Issue Trigger Workflow: Change label for multiple issue self-assignment". Again just an opinion, your title does the job.

2024-09-18 18:32 UTC, 8alpreet commented on github-actions/trigger-issue/add-preliminary-comment/preliminary-update-comment.js
> +      await addLabel(READY_FOR_PRIORITIZATION); // Add 'ready for dev lead' label
Feedback was applied and @k-cardon approved the PR. This needs to be marked as resolved so the PR can proceed.

2024-09-19 03:07 UTC, merged