first commit, updated leadership
hackforla/website pull request #7498
Opened 2024-09-19 21:31 UTC by NolaDodd

Fixes #7497 

### What changes did you make?
  - deleted the original "leadership" variable as shown in the issue in file _data/internal/communities/ops.yml
  - replaced with the new "leadership" variable that was given 

### Why did you make the changes (we will use this info to test)?
  - We need to keep project information up to date so that visitors to the website can find accurate information. The leaders for the DevOps team needed to be updated.

### Screenshots of Proposed Changes To The Website (if any, please do not include screenshots of code changes)

<details>
<summary>Visuals before changes are applied</summary>
![Screenshot 2024-09-19 142506](https://github.com/user-attachments/assets/c2c5c130-0242-4859-9cb8-bdbd353952d8)

</details>

<details>
<summary>Visuals after changes are applied</summary>
![Screenshot 2024-09-19 142751](https://github.com/user-attachments/assets/0577f2de-715e-44d9-8377-2b4e631c10d8)

</details>

2024-09-19 23:17 UTC, FamousHero commented
availability: 5-6pm Mon-Fri
eta: EOD 9/23

2024-09-20 00:51 UTC, codyyjxn requested changes
@NolaDodd Thank you for taking on this issue.

### I noticed a few things regarding the recent updates:

- [x] The branch name includes an incorrect issue number. The correct issue is linked in the title, but it would be great if the branch name could reflect that as well.

- [ ] I ran your branch locally and compared it to the current state of the Communities of Practice website. It seems there aren't any visual changes between the two. Could you double-check to ensure the updates were applied correctly?

- [ ] The issue mentions adding the [Insert name of project] page, so this should be reflected in the title as well. Instead of "First commit, updated leadership," could you revise the title to better align with the task?

If you have any questions or anything that needs to be clarified please feel free to message me back. Thanks!

2024-09-20 00:51 UTC, codyyjxn commented
availability: 5am-6pm Mon>Sun
eta: EOD 9/19

2024-09-20 06:40 UTC, terrencejihoonjung commented
availability: Mon-Sun, 5pm-9pm PST
eta: 9/20/24, 11:59pm PST

2024-09-20 19:13 UTC, terrencejihoonjung requested changes
Hi @NolaDodd 

What you did correctly:
- clearly stated changes made and why they were made
- displayed visual changes for before and after

Requested changes:
- your branch is incorrectly named by its issue # 
- the PR title is slightly unclear and could be improved to better describe the changes you are made! I suggest keeping your branch name and PR title similar as well.

Other than that, you did great! Let me know if you have any questions.

2024-09-21 03:02 UTC, FamousHero commented
Hi @NolaDodd, thanks for taking on this issue!

Things you did great:

- Screenshots accurately show changes from current site to proposed changes
- Correctly linked issue in PR
- Accurate description of changes made w/ reference to file location
- Excellent description of why you made these changes

Things to work on:

- More descriptive branch name. The currently name makes unclear whether you're adding or removing something. Try something more in like with your reason as to why you made the changes 
- Use present tense in your PR title

Congrats on your first commit! Please ask for a re-review when these changes are done!

2024-09-21 03:02 UTC, FamousHero requested changes
Hi @NolaDodd, thanks for taking on this issue!

Things you did great:

-  Screenshots accurately show changes from current site to proposed changes
-  Correctly linked issue in PR
-  Accurate description of changes made w/ reference to file location
- Excellent description of why you made these changes

Things to work on:

-  More descriptive branch name. The currently name makes unclear whether you're adding or removing something. Try something more in like with your reason as to why you made the changes
-  Use present tense in your PR title

Congrats on your first commit! Please ask for a re-review when these changes are done!

2024-09-21 19:02 UTC, NolaDodd commented
I'm gonna go ahead and make a new pull request to correct some of the changes since I also need to change the branch name. Thanks for the feedback everyone!

2024-09-21 19:02 UTC, closed without merging