Update wins.js so the Wins page uses icon-github.svg
hackforla/website pull request #7569
Opened 2024-10-08 00:22 UTC by izma-mujeeb

Fixes #6911 

### What changes did you make?
  
  - In the wins.js page, I replaced the image that was initially being used, with the image that used an svg tag. This image has a name of "icon-github.svg" 

### Why did you make the changes (we will use this info to test)?
  
  - I had to change the image because using the original image was causing a redundancy in the number of images. By using an image with the svg tag, I am ensuring that there are no duplicate images. 

### Screenshots of Proposed Changes To The Website (if any, please do not include screenshots of code changes)
 
- No visual changes made to the website

2024-10-08 01:40 UTC, codyyjxn commented
Availability: M > F
ETA: EOD

2024-10-08 01:51 UTC, codyyjxn approved these changes
Hi @izma-mujeeb  Thank you for taking on this issue!

- The branch name is correct but I recommend you include the issue number for future reference. 
- The issue is linked correctly 
- The changes are correct I checked on my end I was able to see the changes using docker. 
- The title and description are accurate to understand what the task/change. 

Great Job! Thanks for your contribution.

2024-10-08 19:47 UTC, 8alpreet commented
Availability: 3-7pm, Mon-Fri
ETA: EOD Tue, Oct 8

2024-10-09 01:18 UTC, 8alpreet commented
I am testing these changes locally and the icon is not displaying for me. Does it display for both of you @izma-mujeeb and @codyyjxn?

2024-10-09 16:08 UTC, codyyjxn commented
> I am testing these changes locally and the icon is not displaying for me. Does it display for both of you @izma-mujeeb and @codyyjxn?
> 
> I'm still doing research, but all other instances of the `_includes/svg/icon-github.svg` use the `include` tag or are within a .yml file (which I don't know the internals of). I haven't found any instances of a .svg from `_includes` being used with an `img` tag. Jekyll does not treat files in the `_includes` directory as static assets, so we should not be able to use it as the value of the src attribute in an image.

Hey @8alpreet yea just check and for some reason I cant see the icon either. I think maybe the svg isn't rendering correctly.

2024-10-09 16:12 UTC, codyyjxn requested changes
Hey @izma-mujeeb I was looking into the code and @8alpreet actually brought up a good point but we arent able to see the github icon. I believe you deleted the svg that you are using. Please provide screenshots of what you are seeing on your end. The before and after you fix the code. Thank you ! If you have any question feel free to message any of us.

2024-10-11 04:54 UTC, k-cardon requested changes
In case it's helpful--here's the error message that came up when I ran the docker container locally:

`hfla_site  | [2024-10-11 04:41:18] ERROR '/wins/_includes/svg/icon-github.svg' not found.`

I also can't see the icon, so there's definitely a bug. Is `wins/_includes` the correct path?

2024-10-19 23:05 UTC, t-will-gillis commented
Hey @izma-mujeeb @8alpreet @k-cardon @codyyjxn I took a stab at figuring this out also- I am getting no further than you are. The path `_includes/svg/icon-github.svg` appears correct. 

I do not know Liquid, but I am thinking that maybe(?) Liquid wants these assets to be in the `/assets/` folder. There is the [footer.html](https://github.com/hackforla/website/blob/gh-pages/_includes/footer.html) that uses the same GitHub icon. I am not certain but to me it doesn't look like there is a simple 'swap-out-the-new-path' substitution. 

@roslynwythe do you know more about this?

2024-10-22 02:16 UTC, FamousHero commented
Hi @izma-mujeeb, thanks for taking on this issue!

In terms of pull request formatting, everything looks great! I do agree with @codyyjxn that the issue number should be included on the branch name but besides that there are no issues. Like others have said, I'm having issues seeing the changes on my machine. I'm unsure what the exact issue is but Jekyll has great documentation and if not mistaken should have a section on static assets and includes 

**[Jekyll Docs](https://jekyllrb.com/docs/)**

2024-10-22 02:17 UTC, FamousHero requested changes
Hi @izma-mujeeb, thanks for taking on this issue!

In terms of pull request formatting, everything looks great! I do agree with @codyyjxn that the issue number should be included on the branch name but besides that there are no issues. Like others have said, I'm having issues seeing the changes on my machine. I'm unsure what the exact issue is but Jekyll has great documentation and if not mistaken should have a section on static assets and includes

[Jekyll Docs](https://jekyllrb.com/docs/)

2024-11-11 23:52 UTC, roslynwythe requested changes

2024-11-11 23:52 UTC, roslynwythe commented on assets/js/wins.js
> +			cloneCardTemplate.querySelector('.github-icon').src = GITHUB_ICON;
The liquid statement {% include svg/icon-github.svg %} is correct but it cannot be used in the same way that GITHUB_ICON was used previously.  GITHUB_ICON was assigned to the `src` attribute of an `img` tag, but the liquid statement will instead result in the inclusion of the svg inline, and so we need to modify the html template and remove the `img` tag.

2024-11-18 23:57 UTC, roslynwythe commented
- The issue has been edited to reduce scope to replacing the GitHub icons in the wins cards, which appear on page load.  When the wins card is expanded ("See More"), an overlay appears.  Initially this issue was intended to address the overlay, but instead I have created a new issue #7727 to address the overlay. 
- The issue has also been edited to include a reference with sample code for making the `svg` accessible
- The issue has also been edited to include mention and references to the wins card html template.

2024-12-01 15:47 UTC, k-cardon commented
@izma-mujeeb could you resolve the conflicts in `assets/js/wins.js`?

2024-12-10 20:03 UTC, mchait18 commented
Review ETA: 12 PM 12/10/24
Availability: 9-3 EST mon-thurs

2025-01-10 03:12 UTC, k-cardon requested changes
Resolve merge conflicts so that we can see the changes on the site, please!

2025-01-10 03:12 UTC, k-cardon commented on assets/js/wins.js
>  		} else {
Please resolve merge conflicts in these lines -- I tried to review the changes but right now it won't compile.

2025-01-11 03:17 UTC, izma-mujeeb commented
@k-cardon Thank you for your patience. Please let me know if it works now.

2025-01-19 22:57 UTC, k-cardon approved these changes

2025-01-19 22:58 UTC, k-cardon commented
Great, thanks for making those changes! I confirmed that the GitHub logo svg is displaying correctly! Looks like everything is fixed now.

2025-01-31 00:56 UTC, jphamtv commented
Hi @roslynwythe, @8alpreet, @FamousHero, @codyyjxn - @izma-mujeeb made changes and resolved merge conflicts and the PR is ready for your re-review. Please provide ETA for your review or if you cannot re-review, please comment and remove yourself from the Reviewers section. Thanks!

2025-02-11 17:53 UTC, mugdhchauhan commented
Review ETA: 11 Feb 2025 @ 8 PM (GMT)
Availability: Daily @ 6 PM - 8 PM (GMT)

2025-02-11 17:55 UTC, mugdhchauhan approved these changes
Hey @izma-mujeeb, thank you for working on this. Nice work!

### Kudos 

- The pull request is made with the correct branch.
- The pull request post contains a linked issue, what changes you made and why are clear, and the screenshots section is complete.
- The changes you have made to the files are accurate.
- You have claimed the orginiating issue well (#6911) and worked well to resolve the errors you had.
- I can see the changes in my local environment.

### Suggested changes

- [ ] In the PR post, you could use backticks ``(`)`` to enclose the files such as `_includes/wins-page/wins-card-template.html`.
- [ ] You could also add the "CodeQL Alerts" section of the PR post, and check off the relevant box(es).

I have approved this PR because the GitHub logo svg is displaying correctly.

Nice one, thank you for your contribution! Feel free to reach out if you need help with anything.

2025-02-17 23:35 UTC, DrAcula27 approved these changes
@izma-mujeeb Great job on your `Medium Issue`! Your code passed the ABC's, including:
- PR is made from the correct branch
- PR links to the correct issue:
  - #6911
- The correct files were edited:
  - `_includes/svg/icon-github.svg`
  - `_includes/wins-page/wins-card-template.html`
  - `assets/js/wins.js`
- No unnecessary extra edits were made
- Appearance of the website is unchanged (Chrome and Firefox)
- It seems everything is working, and the icon shows on my end. Approved, pending the answer to my question on the HTML element name.

2025-02-17 23:35 UTC, DrAcula27 commented on _includes/wins-page/wins-card-template.html
> +              <div role = "img" class = "github-icon">
- Per the first action item in the issue, #6911, the GitHub icon should be displayed using an `svg` HTML element. @roslynwythe @t-will-gillis Should this `div` be changed to `svg` or is the Liquid statement good enough?

2025-03-17 20:02 UTC, daras-cu commented on assets/js/wins.js
> +			cloneCardTemplate.querySelector('.github-icon').alt = `Github profile for ${card[name]}`;
@izma-mujeeb please change `Github` back to `GitHub` here, then I believe this should be ready to merge.

2025-03-21 14:47 UTC, Cloid commented
Availability: Weekdays 5:30pm - 10pm PST
ETA: EOD March 23

2025-03-25 19:25 UTC, Cloid approved these changes
Hi there,

Looking at the code, they all seem like reasonable changes that address the issue. Everything is in order from correctly linking the issue to following the action items. From what I tested via Firefox and Chrome, there doesn't seem to be any visual changes and behavior seems the same. Approving on my end. There is follow-up questions from other reviewers that should be addressed soon though.

2025-04-04 21:43 UTC, jphamtv commented on _includes/wins-page/wins-card-template.html
> +              <div role = "img" class = "github-icon">
@DrAcula27 - The Liquid statement {% include svg/icon-github.svg %} is good enough. It inserts the contents of icon-github.svg into the HTML as an svg element.

2025-04-04 22:36 UTC, jphamtv requested changes
Hi @izma-mujeeb, I noticed this PR has been open for a while with considerable feedback, so I wanted to provide a focused review with clear action items to help move it forward. Please reach out on Slack if you have any questions. 

Here's what I observed:

- The GitHub icon is not responsive in mobile view and stays the same size as desktop view (image below). 
- The aria-label is not applied to the div element wrapping the SVG as described in [making SVGs WCAG compliant](https://github.com/hackforla/website/issues/6653#issuecomment-2086713272) guide
- The GITHUB_ICON variable in `wins.js` isn't used anymore and can be removed along with any code that references it

Action items:

- [ ] Change 'Github' to 'GitHub' (with proper capitalization) as noted by @daras-cu
- [ ] Update `wins.js` by:  
  - [ ] Removing the unused GITHUB_ICON variable and any code referencing it
  - [ ] Modifying the query selector to apply the aria-label attribute (instead of alt) to the div element wrapping the Liquid statement
- [ ] Update the CSS file to ensure the GitHub icon size matches the LinkedIn icon next to it and is resized properly in mobile view . The Resource Card in one of the projects (example: https://www.hackforla.org/projects/311-data) might give a clue how to size the icon since it uses the same SVG file.

<img width="357" alt="Screenshot 2025-04-04 at 15 32 45" src="https://github.com/user-attachments/assets/797bf17b-3769-46e6-a4c1-abf848912369" />

2025-05-02 01:50 UTC, jphamtv commented
Hi @izma-mujeeb - Could you let us know if you're still planning to work on this? If so, please share your ETA for completion. If we don't hear back, we'll unassign the issue so someone else can pick it up. Thanks!

2025-07-01 04:39 UTC, daras-cu commented
Closing as original dev is inactive, the original issue will be reassigned.

2025-07-01 04:39 UTC, closed without merging