Update pr template codeql 5196
hackforla/website pull request #7616
Opened 2024-10-21 17:55 UTC by santisecco

Fixes #5196 

### What changes did you make?
  
  - Modified PR template `pull_request_template.md` adding CodeQL instructions section. Please refer to the links below. Added more changes to the ones proposed in #5196 after conversation in dev meeting to add further clarity to the PR's instructions.

### Why did you make the changes (we will use this info to test)?
  
  - We need developers to check the PR for annotations/comments resulting from CodeQL scanning. This will ensure better Security and Code Quality and give the chance of fixing changes before they are merged.

### Screenshots of Proposed Changes To The Website (if any, please do not include screenshots of code changes)
 
No visual changes to the website itself. 
Even though, the following links are there to preview the changes to the Pull Request template.

- Previous PR template: https://github.com/hackforla/website/blob/gh-pages/.github/pull_request_template.md

- Updated PR template: https://github.com/santisecco/website/blob/update-pr-template-codeql-5196/.github/pull_request_template.md

2024-10-21 19:38 UTC, pluto-bell submitted a review, later dismissed
Thank you for the descriptive PR, in which you indicated why there are additional changes made that are not found in the original issue. I also appreciate the before and after links to the template files. 

Overall, great work on this PR.

2024-10-22 02:26 UTC, FamousHero commented
Availability: 5-7pm, Mon-Fri
ETA: EOD Tues, Oct 21

2024-10-22 20:07 UTC, Thinking-Panda commented
@santisecco Were these suggestions from you approved by any of the dev leads?
https://github.com/hackforla/website/issues/5196#issuecomment-2386677854

2024-10-22 21:08 UTC, santisecco commented
> @santisecco Were these suggestions from you approved by any of the dev leads? [#5196 (comment)](https://github.com/hackforla/website/issues/5196#issuecomment-2386677854)

Yes, I had highlighted that in "What changes did you make?" section 👍

2024-10-23 20:54 UTC, k-cardon commented
Availability: evenings / weekends
ETA: EOD Thursday

2024-10-24 20:21 UTC, codyyjxn approved these changes, later dismissed
@santisecco Great Job! Thank you for taking on this issue .
- The branch name is correct 
- The issue is linked correctly
- The description is clear and concise. 

Thank you for your contribution! Keep it up

2024-10-25 01:48 UTC, k-cardon requested changes
Branch, PR description, and code all look correct; screenshots of before and after template are helpful, thanks! I am requesting changes because the syntax of the added text is confusing--I know that's language from the original issue, but I think it would be helpful to fix at this stage before merging. I'll mark inline the changes I'm requesting.

2024-10-25 01:53 UTC, k-cardon requested changes
1/2 changes requested (clarify complexity)

2024-10-25 01:53 UTC, k-cardon commented on .github/pull_request_template.md
> +If your issue has a CodeQL alert and is complexity: medium or higher, please let us know that you have checked and resolved.  Please do not dismiss alerts.
Could we clarify how they'll know whether the complexity is medium or higher? I couldn't see that info on the screenshot anywhere. Is this something the developer will judge when they see the alert?

Also, the colon doesn't belong here. Would be clearer to say "and is of complexity medium or higher" with no colon.

2024-10-25 01:56 UTC, k-cardon commented on .github/pull_request_template.md
> +- [ ] I have checked this PR for CodeQL alerts.  If CodeQL alerts were found:
2/2 changes requested:

This could also be clearer if the conditional weren't on the same line as the check, maybe like this:

- [ ] I have checked this PR for CodeQL alerts.
   - [ ] No alerts found
- If CodeQL alerts were found:
[add the other options here]

2024-10-25 05:40 UTC, FamousHero approved these changes, later dismissed
LGTM
Things you did well:
- Description clear
- Issue # in PR and branch name
- Reasoning for going deviating from Actionable Items
- Providing before and after

Things to work on:
- N/A

Keep up the good work!

2024-10-25 18:28 UTC, t-will-gillis commented on .github/pull_request_template.md
> +If your issue has a CodeQL alert and is complexity: medium or higher, please let us know that you have checked and resolved.  Please do not dismiss alerts.
See note below

2024-10-25 18:28 UTC, t-will-gillis commented on .github/pull_request_template.md
> +- [ ] I have checked this PR for CodeQL alerts.  If CodeQL alerts were found:
Hi @k-cardon

@santisecco and I have chatted about ways to make this message clearer. Regarding the first comment, the reference to "complexity: medium" is meant to read that if your PR has a CodeQL alert and "...your issue is labelled `Complexity: Medium` or larger..."

However, combined with your second note (which I agree with), here is a proposed revision for this section:
```
Please let us know that you have checked for CodeQL alerts. **Please do not dismiss alerts.**
- [ ] I have checked this PR for CodeQL alerts and none were found.
- [ ] I found CodeQL alert(s), and:
   - [ ] I have resolved the CodeQL alert(s) as noted
   - [ ] I believe the CodeQL alert(s) is a false positive (Merge Team will evaluate)
   - [ ] I have followed the Instructions below, but I am still stuck (Merge Team will evaluate)

<details><summary>Instructions for resolving CodeQL alerts</summary>
```  
@santisecco and @k-cardon, please feel free to comment/ suggest other things

2024-10-25 18:42 UTC, t-will-gillis commented on .github/pull_request_template.md
> +- [ ] I have checked this PR for CodeQL alerts.  If CodeQL alerts were found:
Also @santisecco If you are planning to attend the meeting this Sunday the 27th, it would be a good idea to have Bonnie take a look and OK the final suggested changes.

2024-10-25 19:58 UTC, santisecco commented on .github/pull_request_template.md
> +- [ ] I have checked this PR for CodeQL alerts.  If CodeQL alerts were found:
Yes @t-will-gillis I'll be there.

2024-10-25 20:15 UTC, santiseccovidal commented on .github/pull_request_template.md
> +If your issue has a CodeQL alert and is complexity: medium or higher, please let us know that you have checked and resolved.  Please do not dismiss alerts.
@k-cardon thanks for your comment.
The text:
"Check the PR's comments. If present on your PR, the CodeQL alert looks similar as shown" and the screenshot is the only new added the original from the issue. Just to clarify.

I think I get your point though. We are saying twice "Check" Perhaps we could say:
"Read the PR's comments. If present on your PR, the CodeQL alert looks similar as shown"

The important thing is that CodeQL alerts only appear as a comment from the bot from what I understand. So it's important to "check" the comments and see if the bot comments on the issue.

2024-10-26 21:09 UTC, k-cardon commented on .github/pull_request_template.md
> +If your issue has a CodeQL alert and is complexity: medium or higher, please let us know that you have checked and resolved.  Please do not dismiss alerts.
@santisecco yes I saw that this was text from the original issue, not text you added, but just thought it would be helpful to change it at this stage so it is clear when it's added! 

I don't think it's an issue to say "check" twice. What was unclear to me here is that the complexity refers to the assigned complexity of the issue, not the complexity of the codeQL alert. 

So I would simply rephrase this line as:

"If your issue has a CodeQL alert, and if your issue is categorized as complexity medium or higher, please let us know that you have checked and resolved. Please do not dismiss alerts."

2024-10-26 21:12 UTC, k-cardon commented on .github/pull_request_template.md
> +- [ ] I have checked this PR for CodeQL alerts.  If CodeQL alerts were found:
Yes, thanks, this is much clearer! I think this revised version works. Thanks for looking into this.

2024-10-26 21:12 UTC, k-cardon commented on .github/pull_request_template.md
> +- [ ] I have checked this PR for CodeQL alerts.  If CodeQL alerts were found:
We could add, just so it's clear they're not expected to check all boxes:

Please let us know that you have checked for CodeQL alerts. **Please do not dismiss alerts.**
- [ ] I have checked this PR for CodeQL alerts and none were found.
- [ ] I found CodeQL alert(s), and (select one):
   - [ ] I have resolved the CodeQL alert(s) as noted
   - [ ] I believe the CodeQL alert(s) is a false positive (Merge Team will evaluate)
   - [ ] I have followed the Instructions below, but I am still stuck (Merge Team will evaluate)

<details><summary>Instructions for resolving CodeQL alerts</summary>

2024-10-27 17:03 UTC, santisecco commented
<!--  Important! Add the number of the issue you worked on  --> 
Fixes #replace_this_text_with_the_issue_number

### What changes did you make?
<!-- Note: add lines if needed, and remove any unused lines -->  
  - 
  - 
  - 

### Why did you make the changes (we will use this info to test)?
<!-- Note: add lines if needed, and remove any unused lines -->  
  - 
  - 
  - 

<h3>CodeQL Alerts</h3>


After the PR has been submitted and the resulting GitHub actions/checks have been completed, developers should check the PR for CodeQL alert annotations.


<details><summary>Check the PR's comments. If present on your PR, the CodeQL alert looks similar as shown</summary>
  
![Screenshot 2024-10-15 153738](https://github.com/user-attachments/assets/90b6ef81-bff7-410a-a961-7bea51f4a4d0)

</details>

If your issue has a CodeQL alert and is complexity: medium or higher, please let us know that you have checked and resolved.  Please do not dismiss alerts.
- [ ] I have checked this PR for CodeQL alerts.  If CodeQL alerts were found:
   - [ ] I have resolved CodeQL alerts 
   - [ ] I believe this CodeQL alerts is a false positive (merge team will evaluate)
   - [ ] I am stuck (after reading instructions below)

<details><summary>Instructions</summary>

If CodeQL alert/annotations appear, refer to [How to Resolve CodeQL alerts](https://github.com/hackforla/website/issues/6463#issuecomment-2002573270).  

In general, CodeQL alerts should be resolved prior to PR reviews and merging

</details>

### Screenshots of Proposed Changes To The Website (if any, please do not include screenshots of code changes)
<!-- Notes: 
  - If there are no visual changes to the website, delete all of the script below and replace with "- No visual changes to the website"
  - If there are visual changes to the website, include the 'before' and 'after' screenshots below. 
  - If your images are too big, use the <img src="" width="" length="" />  syntax instead of ![image](link) to format the images
  - If images are not loading properly, you might need to double check the syntax or add a newline after the closing </summary> tag 
 --> 

<details>
<summary>Visuals before changes are applied</summary>

![image](Paste_Your_Image_Link_Here_After_Attaching_Files)

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
![image](Paste_Your_Image_Link_Here_After_Attaching_Files)

</details>

2024-10-27 17:55 UTC, k-cardon commented
This looks great @santisecco! Could you update the branch and I'll approve it?

2024-10-28 19:01 UTC, santisecco commented
@FamousHero @pluto-bell @codyyjxn I requested again your reviews. I don't know if that could have been skipped had I changed the code differently.

Basically I added what @t-will-gillis and @k-cardon suggested and a new screenshot showing one alert instead of two which was asked by Bonnie in the meeting.

2024-10-28 22:53 UTC, t-will-gillis approved these changes
Hey @santisecco This looks great- thanks for asking the questions and working with everyone to improve this issue!

2024-10-28 23:17 UTC, k-cardon approved these changes
Looks great, very clear now, thanks!

2024-10-29 02:25 UTC, t-will-gillis commented
@FamousHero @pluto-bell @codyyjxn FYI I will merge this since you previously Approved this PR

2024-10-29 02:25 UTC, merged