Update Docker info in CONTRIBUTING.md Section 2.7.b
hackforla/website pull request #7631
Opened 2024-10-23 22:58 UTC by jenjenkayi

Fixes #7576

### What changes did you make?
  
  - Update Docker information in CONTRIBUTING.md Section 2.7.b per draft instructions at #3488

### Why did you make the changes (we will use this info to test)?
  
  - To add instructions for keeping the local Docker image up to date by pulling updates from Dockerhub

For Reviewers: Do not review changes locally, rather, review changes at https://github.com/jenjenkayi/website/blob/update-contributing.md-7576/CONTRIBUTING.md.

### Screenshots of Proposed Changes To The Website (if any, please do not include screenshots of code changes)
 - No visual changes to the website

2024-10-24 02:36 UTC, codyyjxn reviewed
@jenjenkayi  Thank you for taking on this issue. 
I'm not sure why I am not able to see the changes through the link that you provide in the pr. 
It seems like you made the correct changes. Are you able to see the changes on your end from the url that you provided ?

2024-10-24 18:25 UTC, pluto-bell requested changes
Great work, everything looks solid 👍 and the link you provided did work for me.

The one thing I noticed is that the hyperlinks at the top of the `CONTRIBUTING.md` page no longer work for sections `2.7b` and `i` due to the title name changes. 

My suggestion is to:

- [ ]  edit the hyperlinks at the top of the `CONTRIBUTING.md` file so that they reference the new title names for `2.7b` and its subsection `i` so they can continue to be easily accessible via the table of contents hyperlinks. 

- [ ] after completing this change double-check your work to ensure that clicking each of those hyperlinks redirect you to sections `2.7b` and `i`, respectively. 

If you have any questions don't hesitate to reach out.

2024-10-24 21:20 UTC, pluto-bell commented
> Great work, everything looks solid 👍 and the link you provided did work for me.
> 
> The one thing I noticed is that the hyperlinks at the top of the `CONTRIBUTING.md` page no longer work for sections `2.7b` and `i` due to the title name changes.
> 
> My suggestion is to:
> 
> * [ ]   edit the hyperlinks at the top of the `CONTRIBUTING.md` file so that they reference the new title names for `2.7b` and its subsection `i` so they can continue to be easily accessible via the table of contents hyperlinks.
> * [ ]  after completing this change double-check your work to ensure that clicking each of those hyperlinks redirect you to sections `2.7b` and `i`, respectively.
> 
> If you have any questions don't hesitate to reach out.


Thanks for making the adjustments, @jenjenkayi! 

I'll let someone who has more authority than me take a look at these notes and make the final decision on subsection `i`:

-  It looks like `2.7.b` subsection `i` isn't getting properly connected still due to the link inside the full string: 
    - `new title:` i. To test your issue branch locally, run the command "docker-compose up" from a terminal window. The website will then be accessible at http://localhost:4000/ . A few notes regarding Docker:
- My thought is to make subsection `i` more like an actual title so we can still easily hyperlink it
   - `previous title:` What if you cannot see your changes locally within Docker?
- Since I don't have jurisdiction, just putting in my 2 cents (:

2024-10-24 21:29 UTC, jenjenkayi commented
@pluto-bell Thank you for reviewing! I have checked both links, they are working now.

2024-10-24 21:31 UTC, jenjenkayi commented
@codyyjxn Thank you for reviewing! Yes, the changes are up to date from the url provided.

2024-10-25 22:28 UTC, santisecco commented
Review ETA: 2 PM 10/26/24
Availability: Friday-Saturday 11 AM-3 PM

2024-10-26 19:46 UTC, santisecco commented
-Change "the Docker Desktop application..." with "The Docker Desktop application..." in the first bullet point.

-I would personally keep the last two bullet points from the previous version and add them at the end.

- If the above steps did not resolve your issue, run through the first three steps again, but try resetting your browser's cache before restarting docker (you can also try running http://localhost:4000 in another browser).

- If you still do not see your changes after trying these steps, please feel free to reach out to the team in the #hfla-site Slack channel, or bring up your issue in a dev meeting.

-In the new Docker version when clicking the three dots, I don't see the option "View details" instead I see the option "View packages and CVEs" I would add that just in case.
I don't know if I would add the screenshot also of the new version or just the text.
![Screenshot 2024-10-26 161622](https://github.com/user-attachments/assets/79b3dc3a-0ed4-4b29-8876-05fc6d0f46f4)

2024-10-29 21:33 UTC, jenjenkayi commented
@santisecco Updated per your comments. Please review. Thank you!

2024-10-31 14:50 UTC, santisecco approved these changes, later dismissed
Hi @jenjenkayi thank you for the updates and adding the screenshot for the new version of docker. It looks great.
Thanks for working on this.

2024-10-31 14:50 UTC, santiseccovidal commented on CONTRIBUTING.md
> +- the Docker Desktop application must be running, otherwise `docker-compose up` will not work
Here I meant to capitalize "the" with "The"

2024-11-01 19:45 UTC, jenjenkayi commented
@pluto-bell I have updated the changes. Please review it again. Thank you

2024-11-05 22:19 UTC, codyyjxn commented
@jenjenkayi  Thank you for making the changes. Please request a review so i can approve this.

2024-11-05 23:55 UTC, codyyjxn approved these changes, later dismissed
@jenjenkayi  Thank you for taking this issue on. Keep it up !

2024-11-10 22:37 UTC, t-will-gillis requested changes
Hi @jenjenkayi Thank you for working on this! Everything is looking great and it appears that you have satisfied the original issue. There are a couple of edits, however, that I believe we will want to make:
- As @pluto-bell had mentioned earlier, I agree that the header for 2.7.i  should be a title, and currently this reads as a paragraph. I think that the best solution is to change the text on line 55 to something like (and please check that this is formatted correctly):  
  ```  
  - [**i. A few notes regarding Docker:**](#i-a-few-notes-regarding-docker)  
  ```  
  and line 249 to (please remove the space between the link and the period):  
  ```  
  ##### **i. A few notes regarding Docker:**   

  - To test your issue branch locally, run the command "docker-compose up" from a terminal window. The website will then be accessible at http://localhost:4000. 
  ```  
- Also, on line 552 there is a misspelling "...which enables Docker to built the website locally..." Here "built" should be "build"

Again, you followed the issue correctly but would you please make these edits?
Thanks!

2024-11-13 23:30 UTC, t-will-gillis approved these changes
Hey @jenjenkayi This looks great! Thanks for making the edits.

2024-11-13 23:31 UTC, merged