Replace label in project-profile-card-review-and-update.yml #7606
hackforla/website pull request #7660
Opened 2024-10-29 16:46 UTC by ihop-56

Fixes #7606 

### What changes did you make?
  - Updated the issue template to replace ready for dev lead with ready for merge team in the project-profile-card-review-and-update.yml file.
 
### Why did you make the changes (we will use this info to test)?
  - The change was requested to streamline issue review processes, allowing the merge team to handle more issue reviews effectively.

<h3>CodeQL Alerts</h3>

After the PR has been submitted and the resulting GitHub actions/checks have been completed, developers should check the PR for CodeQL alert annotations.

<details><summary>Check the PR's comments. If present on your PR, the CodeQL alert looks similar as shown</summary>
  
![Screenshot 2024-10-28 154514](https://github.com/user-attachments/assets/ea66c586-c14c-45fd-8705-1c116224e704)

</details>

Please let us know that you have checked for CodeQL alerts. **Please do not dismiss alerts.**
- [] I have checked this PR for CodeQL alerts and none were found.
- [ ] I found CodeQL alert(s), and (select one):
   - [ ] I have resolved the CodeQL alert(s) as noted
   - [ ] I believe the CodeQL alert(s) is a false positive (Merge Team will evaluate)
   - [ ] I have followed the Instructions below, but I am still stuck (Merge Team will evaluate)

<details><summary>Instructions for resolving CodeQL alerts</summary>

If CodeQL alert/annotations appear, refer to [How to Resolve CodeQL alerts](https://github.com/hackforla/website/issues/6463#issuecomment-2002573270).  

In general, CodeQL alerts should be resolved prior to PR reviews and merging

</details>

### Screenshots of Proposed Changes To The Website (if any, please do not include screenshots of code changes)
- No visual changes to the website

2024-10-30 02:22 UTC, dcotelessa commented
ETA: 1 hour
Availability: 4-6 W Th F

2024-10-31 04:46 UTC, codyyjxn commented
ETA: EOD
Availability: M > F

2024-10-31 20:12 UTC, dcotelessa commented
Good job!
- project-profile-card-review-and-update template label was updated.
- No new CodeQL errors.
- Straightforward label image change.

2024-10-31 20:12 UTC, dcotelessa approved these changes, later dismissed

2024-11-01 04:34 UTC, siyunfeng commented
Review ETA: 11/1/2024 Friday
Availability: 7-10 PM Weekdays (EDT)

2024-11-01 05:15 UTC, siyunfeng requested changes
Thank you for working on this issue, @ihop-56 !

The branch you work on is accurate. I appreciate you provided your ETA and availability in the original issue, and included the original issue number in this PR. I'd suggest removing the extra space before the context you replaced by following the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) in the file. 

Before making the change, you may need to ensure your branch is up to date. The issue template is **Project Profile Card review and update** according to the `project-profile-card-review-and-update.yml` file. 

### Project Profile Card review and update template

![Project Profile Card review and update template](https://github.com/user-attachments/assets/0854fb26-9d9d-4940-ad3e-4c8098f71d3a)

You may need to create new labels from your GitHub if you don't see the corresponding labels in the `project-profile-card-review-and-update.yml` file shown in the template. 

Please provide the issue template creation URL and update it to the `For Reviewers` section without creating the issue.

2024-11-03 20:01 UTC, codyyjxn requested changes
@ihop-56 
**Things that went well:**

- You made the correct changes
- The description is very detailed and concise
- The issue is linked correctly

**Things that need to be improved**
- [ ] Please fix the `For Reviewers` section. The url that is provided is not properly set.

2024-11-13 04:18 UTC, siyunfeng commented
Hi @ihop-56 , please make the changes we requested. Feel free to reach out if you have any questions.

2024-11-17 18:58 UTC, ihop-56 commented
Hi @siyunfeng and team, the requested changes have been made:
- Fixed the extra space in the syntax to align with the existing front matter block.
- I'm not sure how to update the "For Reviewers" section with the correct issue template URL. Could you please help me with this?

2024-11-17 19:04 UTC, t-will-gillis commented
Hello @ihop-56 Please provide an update on when you will be able to wrap up this PR. 
Thanks

2024-11-17 20:32 UTC, ihop-56 commented
> Hello @ihop-56 Please provide an update on when you will be able to wrap up this PR. Thanks

End of this week

2024-11-18 22:01 UTC, siyunfeng commented
> Hi @siyunfeng and team, the requested changes have been made:
> 
> * Fixed the extra space in the syntax to align with the existing front matter block.
> * I'm not sure how to update the "For Reviewers" section with the correct issue template URL. Could you please help me with this?

> Fixed the extra space in the syntax to align with the existing front matter block.

I still can see the extra spaces in line 353.

> I'm not sure how to update the "For Reviewers" section with the correct issue template URL. Could you please help me with this?

The file you made the change on was `.github/ISSUE_TEMPLATE/project-profile-card-review-and-update.yml`. Its corresponding issue template should be [Project Profile Card review and update](https://github.com/hackforla/website/issues/new?assignees=&labels=P-Feature%3A+Project+Info+and+Page%2Crole%3A+back+end%2FdevOps%2Crole%3A+front+end%2CComplexity%3A+Small%2Csize%3A+0.5pt%2Ctime+sensitive&projects=&template=project-profile-card-review-and-update.yml&title=Update+Project+Profile%3A+%5BProject+Name%5D), and the issue template you used was `Project Profile leader updates - Add`. 

I don't see the `Project Profile Card review and update` issue template in your repo, it could be an issue from when you forked from the original repo.

2024-11-22 21:21 UTC, ihop-56 commented
@siyunfeng Hi, Can you check again? I have fixed the extra space and I'm not able to find the Project Profile Card review and update template in my repo

2024-11-22 22:21 UTC, siyunfeng commented
> @siyunfeng Hi, Can you check again? I have fixed the extra space and I'm not able to find the Project Profile Card review and update template in my repo

Hi @ihop-56 , I can see the [Project Profile Card review and update](https://github.com/ihop-56/website/issues/new?assignees=&labels=P-Feature%3A+Project+Info+and+Page%2Crole%3A+back+end%2FdevOps%2Crole%3A+front+end%2CComplexity%3A+Small%2Csize%3A+0.5pt%2Ctime+sensitive&projects=&template=project-profile-card-review-and-update.yml&title=Update+Project+Profile%3A+%5BProject+Name%5D) issue template in your repo. You can double-check your template and ensure the changes apply to the updated template. 

Because the original issue is missing the instructions for creating corresponding labels for the template, you will need to complete this PR with the following steps: 
- Browse to the Issues page, then click Labels
  <details><summary>Screenshot - creating labels in the test Repo</summary>

  ![image](https://github.com/hackforla/website/assets/5314153/208e1b07-2478-4ed3-98a1-207de58d25c5)

  </details> 
- Create labels corresponding to each label that was listed in the updated issue template. The color of the labels doesn't have to match those on the `hackforla/website` repository, but the text of the labels must match exactly.  

Once you create all the labels listed in the file `/.github/ISSUE_TEMPLATE/project-profile-card-review-and-update.yml` in your repo, you should be able to see the corresponding labels appear in the issue template. 

You can re-request me to review your PR once you complete the steps above.

2024-12-01 17:44 UTC, ihop-56 commented
@siyunfeng  I'm not sure how to do this. Can I take up a new issue to work on?

2024-12-02 01:21 UTC, siyunfeng commented
> @siyunfeng I'm not sure how to do this. Can I take up a new issue to work on?

Hi @ihop-56 , you can follow the steps from my previous [comment](https://github.com/hackforla/website/pull/7660#issuecomment-2494968923) and you should be able to resolve it. Don't hesitate to comment on this PR if you have any questions.

2024-12-10 05:59 UTC, siyunfeng commented
Hi @ihop-56 , please provide an update on when you can wrap up this PR.

2024-12-10 16:53 UTC, mchait18 commented
Review ETA: 12 PM EST 12/11/24
Availability: 10-3 EST Mon-Thurs

2024-12-10 20:00 UTC, mchait18 requested changes
Hello @ihop-56 ,
Things you did well:
- The code changes look good
- The issue is linked correctly
- The description is clear and concise

Things you need to chane:
- Check off the CodeQL alerts section
- as @siyunfeng mentioned, the URL is pointing to the wrong Issue creation page. It needs to create the project-profile-card-review-and-update issue, not the Update Project Profile - Add issue. Therefore the labels are incorrect as well. As soon as you correct these changes, I'll be happy to re-review!

2024-12-11 19:53 UTC, ihop-56 commented
Hi @siyunfeng, I created a new issue template as you described above. Can you pls check if I have done it right?

2024-12-12 04:26 UTC, siyunfeng commented
> Hi @siyunfeng, I created a new issue template as you described above. Can you pls check if I have done it right?

@ihop-56 , as I mentioned in the previous comment, you don't need to create a new issue. 

I can see the correct issue template in your repo, please update the [`Project Profile Card review and update`](https://github.com/ihop-56/website/issues/new?assignees=&labels=P-Feature%3A+Project+Info+and+Page%2Crole%3A+back+end%2FdevOps%2Crole%3A+front+end%2CComplexity%3A+Small%2Csize%3A+0.5pt%2Ctime+sensitive&projects=&template=project-profile-card-review-and-update.yml&title=Update+Project+Profile%3A+%5BProject+Name%5D) issue template URL to the `For Reviewers` section.

Please carefully read the [comment](https://github.com/hackforla/website/pull/7660#issuecomment-2494968923) and complete all the steps. 

I'll be happy to review it once you're done.

2025-01-23 22:33 UTC, jphamtv commented
Hi @ihop-56 - please let us know if you are still working on this issue and your ETA for the requested changes. Thanks!

2025-01-31 01:18 UTC, jphamtv commented
Hi @ihop-56 - I left a [comment](https://github.com/hackforla/website/issues/7212#issuecomment-2626068335) on your Skills Issue. Please respond, or we'll need to unassign this issue so someone else can work on it. Thanks!

2025-01-31 02:05 UTC, ihop-56 commented
Hi, please unassign me from this issue. I want to take up something else.

On Thu, Jan 30, 2025, 8:18 PM Jacques Pham ***@***.***> wrote:

> Hi @ihop-56 <https://github.com/ihop-56> - I left a comment
> <https://github.com/hackforla/website/issues/7212#issuecomment-2626068335>
> on your Skills Issue. Please respond, or we'll need to unassign this issue
> so someone else can work on it. Thanks!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/hackforla/website/pull/7660#issuecomment-2626074797>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BA5P264ZZDYCT43YNLGRBET2NLFPDAVCNFSM6AAAAABQ2JNZT2VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDMMRWGA3TINZZG4>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2025-02-09 22:16 UTC, t-will-gillis commented
Hi @ihop-56 I left a message on what I believe was your Slack. 

You have almost completed this PR. Please feel free to contact me or anyone else on the Merge Team and we would be happy to talk you through the remaining steps.

2025-02-13 03:08 UTC, t-will-gillis commented
Closing- Dev cannot get to this and is asking to be removed.

2025-02-13 03:08 UTC, closed without merging