Update spell-check-audit.md label and issue template
hackforla/website pull request #7713
Opened 2024-11-09 23:57 UTC by aswutmaxcy

Fixes #7601

### What changes did you make?
  
  - ln 5 and 21 in spell-check-audit.md changed "ready for dev lead" to "ready for merge team"

### Why did you make the changes (we will use this info to test)?
  
  - made requested changes from issue
  
 ### For Reviewers
- Use this URL to check the updated issue template: https://github.com/aswutmaxcy/website/issues/new?assignees=&labels=Complexity%3A+Small%2C+feature%3A+spelling%2C+ready+for+merge+team%2C+role%3A+back+end%2FdevOps%2C+role%3A+front+end%2C+size%3A+0.5pt&projects=&template=spell-check-audit.md&title=Run+VS+Code+Spell+Checker+on+%5BINSERT+FILE+HERE%5D
- 
### Screenshots of Proposed Changes To The Website (if any, please do not include screenshots of code changes)
<!--  Notes: 
  - No visual changes to the website

2024-11-11 02:54 UTC, siyunfeng commented
Review ETA: 11/11/2024 Monday
Availability: 6-10 PM Weekdays (EDT)

2024-11-11 23:14 UTC, siyunfeng requested changes
Thank you for working on this issue, @aswutmaxcy .

- The branch you made change on is correct
- The linked issue number is included
- Availability and ETA are provided in the original issue
- The change you made in the related file is accurate

**Improvements**: 
- Address the question `Why did you make the changes (we will use this info to test)?` with specific detail based on the original issue
- Respond to `Screenshots of Proposed Changes To The Website (if any, please do not include screenshots of code changes)`, provide related screenshots if any, otherwise, keep the answer `No visual changes to the website` from your PR template

**Reminder**: 
- After PR is merged, be sure to change your default branch back to gh-pages and to disable Issues feature

### Changes you need to make: 
- [ ] Fix the labels in the issue template you linked in the **For Reviewers** section (there aren't any labels showing up)

2024-11-12 01:30 UTC, aswutmaxcy commented
> ### Changes you need to make:
> 
>     * [ ]  Fix the labels in the issue template you linked in the **For Reviewers** section (there aren't any labels showing up)

Aren't the labels specific to the repo? As in, I won't have them on my clone of the repo, but they'll show up on the main hfla repo

2024-11-12 01:34 UTC, jennisung commented
Review completion by: Nov. 12
Availability: 6-12 pm from Monday to Fridays (EST)

2024-11-12 01:37 UTC, aswutmaxcy commented
> Review completion by: Nov. 12 Availability: 6-12 pm from Monday to Fridays (EST)

Could I get a reply to my previous comment about the labels before you complete your review please?

2024-11-12 14:18 UTC, tamara-snyder commented
**Review ETA:** End of day Thursday, Nov 14
**Availability:** Afternoons

2024-11-14 19:43 UTC, jennisung commented
To: @aswutmaxcy 
Comments: I see that the corrections were made in the correct branch, and the link to the issue has been added in the comments. Also, the corrections related to the issue have been applied.

Corrections/Suggestions: I don’t see screenshots of the changes in the comments. Please add these to provide visual confirmation of the updates. Maybe just a screenshot of the spell-check-audit.md page. Thank you!

2024-11-14 19:44 UTC, jennisung requested changes
To: @aswutmaxcy
Comments: I see that the corrections were made in the correct branch, and the link to the issue has been added in the comments. Also, the corrections related to the issue have been applied.

Corrections/Suggestions: I don’t see screenshots of the changes in the comments. Please add these to provide visual confirmation of the updates. Maybe just a screenshot of the spell-check-audit.md page. Thank you!

2024-11-14 20:32 UTC, aswutmaxcy commented
@siyunfeng can you please respond to my question about the labels
@jennisung the section for screenshots of visual changes are for the website specifically, there is also a link to the issue template to demonstrate the changes.

2024-11-14 21:00 UTC, siyunfeng commented
> > ### Changes you need to make:
> > ```
> > * [ ]  Fix the labels in the issue template you linked in the **For Reviewers** section (there aren't any labels showing up)
> > ```
> 
> Aren't the labels specific to the repo? As in, I won't have them on my clone of the repo, but they'll show up on the main hfla repo

Hi @aswutmaxcy , since the issue template involves changing the labels, we should make sure all the correct labels show up in the test issue template on your branch.

2024-11-14 22:12 UTC, aswutmaxcy commented
> > > ### Changes you need to make:
> > > ```
> > > * [ ]  Fix the labels in the issue template you linked in the **For Reviewers** section (there aren't any labels showing up)
> > > ```
> > 
> > 
> > Aren't the labels specific to the repo? As in, I won't have them on my clone of the repo, but they'll show up on the main hfla repo
> 
> Hi @aswutmaxcy , since the issue template involves changing the labels, we should make sure all the correct labels show up in the test issue template on your branch.

@siyunfeng the issue doesn't involve changing labels, but the text in the template. You can create labels to show up, but that isn't testing the labels at all, it would just be me creating labels for show.

2024-11-15 03:17 UTC, tamara-snyder reviewed
@aswutmaxcy Great work on this. I can see that you've replaced dev lead with merge team in the two required places.

As mentioned by @siyunfeng, I think it would be worthwhile to know that the labels will appear as expected before merging this, if possible. However, I don't fully understand the flow of how these comma-separated labels turn into issue labels. Is this controlled by a GitHub action, or is it a default functionality of GitHub? Is there a feasible way to test this in a personal repo?

2024-11-15 04:52 UTC, aswutmaxcy commented
> @aswutmaxcy Great work on this. I can see that you've replaced dev lead with merge team in the two required places.
> 
> As mentioned by @siyunfeng, I think it would be worthwhile to know that the labels will appear as expected before merging this, if possible. However, I don't fully understand the flow of how these comma-separated labels turn into issue labels. Is this controlled by a GitHub action, or is it a default functionality of GitHub? Is there a feasible way to test this in a personal repo?

@tamara-snyder yeah, that's what I'm trying to figure out too, I can't get them to come up naturally unless I just manually add them on my repo (which doesn't test anything, it'd just be for show). 

I'm guessing the labels are controlled by the repo owners or people with the access to write/edit labels on the actual repo. Which leads me to believe labels are repo specific, unsure though... All I know is I can't get them to come up on my side.

2024-11-15 07:15 UTC, siyunfeng commented
> > > > ### Changes you need to make:
> > > > ```
> > > > * [ ]  Fix the labels in the issue template you linked in the **For Reviewers** section (there aren't any labels showing up)
> > > > ```
> > > 
> > > 
> > > Aren't the labels specific to the repo? As in, I won't have them on my clone of the repo, but they'll show up on the main hfla repo
> > 
> > 
> > Hi @aswutmaxcy , since the issue template involves changing the labels, we should make sure all the correct labels show up in the test issue template on your branch.
> 
> @siyunfeng the issue doesn't involve changing labels, but the text in the template. You can create labels to show up, but that isn't testing the labels at all, it would just be me creating labels for show.

I confirmed with @roslynwythe in the meeting. The issue instruction is missing the steps of creating labels on your branch. To create the labels,  I recommend using this [Testing issue templates](https://github.com/hackforla/website/issues/4786#issuecomment-1670584024) as reference: 

- Browse to the Issues page, then click Labels
  <details><summary>Screenshot - creating labels in the test Repo</summary>

  ![image](https://github.com/hackforla/website/assets/5314153/208e1b07-2478-4ed3-98a1-207de58d25c5)

  </details> 
- Create labels corresponding to each label that was listed in the updated issue template. The color of the labels doesn't have to match those on the `hackforla/website` repository, but the text of the labels must match exactly.  

Once you create all the labels listed in the file `/.github/ISSUE_TEMPLATE/spell-check-audit.md` in your repo, the issue template should show the labels.

2024-11-16 02:04 UTC, aswutmaxcy commented
@siyunfeng okay, got the labels in, the url should be updated and good to go, lemme know if it shows up on your side with the labels as well

2024-11-16 02:05 UTC, aswutmaxcy commented
@jennisung I added a screenshot of the issue template page as well

2024-11-16 04:13 UTC, jennisung approved these changes
UPDATED Comments: I see that the corrections were made in the correct branch, and the link to the issue has been added in the comments. Also, the corrections related to the issue have been applied. Assignee added the screenshots of the changes in the comments that showed that he corrected the .md page with the correct wording.

2024-11-16 04:17 UTC, siyunfeng approved these changes
Nice job adding the labels to the issue template, @aswutmaxcy .

- I can see the labels in the updated issue template match those listed in the file `/.github/ISSUE_TEMPLATE/spell-check-audit.md`.
- The screenshot helps show the changes

**Things to improve**:
- You can refer to the `Overview` section from the original issue #7601 to address the question `Why did you make the changes (we will use this info to test)?`.

**Reminder**: 
- After PR is merged, be sure to change your default branch back to `gh-pages` and disable the `Issues` feature

Thank you for your contribution! Keep it up.

2024-11-18 03:00 UTC, merged