Update Project Profile Adding Nilakshi Sahai
hackforla/website pull request #7714
Opened 2024-11-10 00:04 UTC by belunatic

Fixes #7648

### What changes did you make?
  - I added Nilakshi Sahai to the current Project Team Section

### Why did you make the changes (we will use this info to test)?
  
  - To update the Current Project Team Members

<h3>CodeQL Alerts</h3>

After the PR has been submitted and the resulting GitHub actions/checks have been completed, developers should check the PR for CodeQL alert annotations.

<details><summary>Check the PR's comments. If present on your PR, the CodeQL alert looks similar as shown</summary>
  
</details>

Please let us know that you have checked for CodeQL alerts. **Please do not dismiss alerts.**
- [ ] I have checked this PR for CodeQL alerts and none were found.
- [ ] I found CodeQL alert(s), and (select one):
   - [ ] I have resolved the CodeQL alert(s) as noted
   - [ ] I believe the CodeQL alert(s) is a false positive (Merge Team will evaluate)
   - [ ] I have followed the Instructions below, but I am still stuck (Merge Team will evaluate)

<details><summary>Instructions for resolving CodeQL alerts</summary>

If CodeQL alert/annotations appear, refer to [How to Resolve CodeQL alerts](https://github.com/hackforla/website/issues/6463#issuecomment-2002573270).  

In general, CodeQL alerts should be resolved prior to PR reviews and merging

</details>

### Screenshots of Proposed Changes To The Website (if any, please do not include screenshots of code changes)
 

<details>
<summary>Visuals before changes are applied</summary>

![FireShot Capture 070 - LA TDM Calculator - Hack for LA - localhost](https://github.com/user-attachments/assets/50a35e0d-bb3b-4df6-b72e-a66be59a35e0)

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
![FireShot Capture 071 - LA TDM Calculator - Hack for LA - localhost](https://github.com/user-attachments/assets/bb6d8a9b-77f8-44b4-b0c9-b6706b84db5a)

</details>

2024-11-12 17:41 UTC, codyyjxn requested changes
@belunatic thank you for taking on this issue.
## Suggestions 
- You need to respond to the bot in the comments below on the original issue. 
- You need to fix the conflict

2024-11-12 19:13 UTC, belunatic commented
updated image after resolving the conflict

![FireShot Capture 072 - LA TDM Calculator - Hack for LA - localhost](https://github.com/user-attachments/assets/54ece179-dae4-4608-b9d4-0e0342db7bd6)

2024-11-14 04:05 UTC, codyyjxn approved these changes, later dismissed
@belunatic  Great job fixing the merge conflict! Thank you for your contribution keep it up !

2024-11-14 18:35 UTC, belunatic commented
Thank you @codyyjxn, I appreciate you!

2024-11-15 01:02 UTC, jphamtv commented
Hi @belunatic - Please let team members self-assign PR reviews. Available reviewers will pick up PRs from the queue when they can work on them. This helps us maintain an efficient review process where available reviewers can schedule their workloads. Thanks!

2024-11-15 17:34 UTC, belunatic commented
@jphamtv I appreciate you! Have a great weekend!

2024-11-15 19:20 UTC, ExperimentsInHonesty approved these changes, later dismissed
This looks good.  Its ready for merge.  I just made one change to her title.  Changed it 
from: Lead UX Design Lead
to: UX Design Lead

2024-11-15 19:20 UTC, ExperimentsInHonesty commented on _projects/tdm-calculator.md
> +    role: Lead UX Design Lead
```suggestion
    role: UX Design Lead
```

2024-11-15 19:24 UTC, ExperimentsInHonesty commented
I am merging this to reduce confusion, since it already had two reviews.

2024-11-15 19:24 UTC, merged