Project Page css update
hackforla/website pull request #941
Opened 2021-01-15 01:08 UTC by martham0

Updated CSS of dropdown and project header. Add spacing between .project-header and .project-pitch. Added padding to the right of the filter item so the text does not overlap the label arrow

2021-01-15 02:50 UTC, martham0 commented
<img width="741" alt="Screen Shot 2021-01-14 at 6 48 08 PM" src="https://user-images.githubusercontent.com/69860036/104674898-486cb180-5699-11eb-99eb-5d53f379459c.png">

2021-01-15 15:35 UTC, trtincher approved these changes
Looks great!

2021-01-17 18:02 UTC, jbubar commented
This looks, Good. Hoping to talk about it in the meeting. Thanks for your patience

2021-01-17 19:31 UTC, jbubar requested changes

2021-01-17 19:31 UTC, jbubar commented on _sass/components/_project-filter.scss
> +  padding-right: 30px;
do a margin-right: auto or something here instead

2021-01-17 19:31 UTC, jbubar commented on _sass/components/_project-filter.scss
> +  padding-right: 30px;
https://www.hackforla.org/

![Screen Shot 2021-01-17 at 11 31 10 AM](https://user-images.githubusercontent.com/53061723/104853721-8c3d0200-58b7-11eb-97c6-6dca2a1dd737.png)

2021-01-18 17:56 UTC, martham0 commented on _sass/components/_project-filter.scss
> +  padding-right: 30px;
The spacing has been corrected. It was actually within the _project.scss file that required editing to align the project pitch to the right.

2021-01-18 17:57 UTC, martham0 commented
![Screen Shot 2021-01-18 at 9 57 37 AM](https://user-images.githubusercontent.com/69860036/104949311-9b818580-5973-11eb-8ee8-7340645e7429.png)

2021-01-18 20:23 UTC, trtincher approved these changes
Looks good!

2021-01-20 22:21 UTC, jbubar commented
![Screen Shot 2021-01-20 at 2 17 46 PM](https://user-images.githubusercontent.com/53061723/105248045-97e42f00-5b2a-11eb-9ca0-0742f80f0b4b.png)
Sorry to be nitpicky, but we have run into another error, where at a certain screen width, the dropdowns extend off the screen

2021-01-22 18:53 UTC, martham0 commented
> ![Screen Shot 2021-01-20 at 2 17 46 PM](https://user-images.githubusercontent.com/53061723/105248045-97e42f00-5b2a-11eb-9ca0-0742f80f0b4b.png)
> Sorry to be nitpicky, but we have run into another error, where at a certain screen width, the dropdowns extend off the screen

Problem fixed! Instead of adding padding increased the screen max-width for the class ul.filter-list which creates 2 rows and 2 columns.
![image](https://user-images.githubusercontent.com/69860036/105532683-04346f00-5ca0-11eb-95ae-2debeef205fc.png)

2021-01-24 18:30 UTC, jbubar commented
Accidentally pulled changes into this branch from danielles pr

2021-01-24 18:30 UTC, jbubar commented
Cannot merge this until this is fixed

2021-01-25 18:25 UTC, martham0 commented
Danielle's changes have been removed. Ready to merge!

2021-01-27 03:17 UTC, merged