Readme Update
hackforla/website pull request #945
Opened 2021-01-17 18:14 UTC by martham0

Added instructions on status updates and how to edit existing pull requests.

2021-01-17 19:40 UTC, jbubar requested changes

2021-01-17 19:40 UTC, jbubar commented on README.md
> +1. Progress: "Added verticals to all the existing md files. Now need to create the reamining files and add verticals."
Use the quoted area to explain what you are supposed to put there

2021-01-17 19:40 UTC, jbubar commented on README.md
> +1. Progress: "Added verticals to all the existing md files. Now need to create the reamining files and add verticals."
Or indicate that it is an example some way

2021-01-17 19:42 UTC, jbubar commented on README.md
> +available. Make sure to include pictures of any visual changes made to the site and document your edits on the PR so that the reviewer can understand the changes made.  Review the changes that will b
use full word pull request

2021-01-17 19:47 UTC, jbubar commented on README.md
> +1. Go to your pull request
Lets rewrite this to for best practice:
update it on your branch locally and push it to your origin remote and it will be updated on your pr

2021-01-18 19:23 UTC, martham0 commented on README.md
> +1. Progress: "Added verticals to all the existing md files. Now need to create the reamining files and add verticals."
I decided to write an explanation over an example.

2021-01-18 19:24 UTC, martham0 commented on README.md
> +available. Make sure to include pictures of any visual changes made to the site and document your edits on the PR so that the reviewer can understand the changes made.  Review the changes that will b
Revised it and made sure not to use the abbreviation.

2021-01-18 19:24 UTC, martham0 commented on README.md
> +1. Go to your pull request
Completed.

2021-01-22 19:24 UTC, merged