Update record clearance project
hackforla/website pull request #952
Opened 2021-01-20 04:07 UTC by TeddyTelanoff

Fixes #949

2021-01-20 15:13 UTC, trtincher approved these changes
Looks good to me. I believe the process is to get one more reviewer to approve then it is ready for squash and merge. So you might reach out to david or josh or someone to do the final review for you.

2021-01-20 20:53 UTC, jbubar commented
Great job Teddy, one small change
If you look at issue #853, it looks like we want our slack url's to have hackforla in it rather than app.

Could you make those changes on the same branch that you did these changes on, then push it?

2021-01-20 20:54 UTC, jbubar requested changes

2021-01-20 20:54 UTC, jbubar commented on _projects/record-clearance-project.md
> +      slack: 'https://app.slack.com/team/U01GC5HU9AB'
Can you change the url from 'https://app.slack.com/team/U01GC5HU9AB' to 'https://hackforla.slack.com/team/U01GC5HU9AB'

2021-01-21 01:51 UTC, merged

2021-01-21 01:51 UTC, jbubar commented
Nicely done Teddy!!
Lets get you a new pull request!