Accessibility fixes 75
hackforla/website pull request #96
Opened 2019-05-08 03:38 UTC by seanholahan

fixes 3 accessibility issues brought up by "Wave" chrome extension
1. delete empty h3 inside of hacknights location
2 added aria-label to social media icons
3. No label for "send us a message" input

2019-05-08 04:07 UTC, thekaveman requested changes

2019-05-08 04:07 UTC, thekaveman commented on _includes/hack-nights.html
>                      <strong>{{ item.title }}</strong> {{ item.event-date }}
I'm actually thinking that the `<h3>` was supposed to wrap `{{ item.title}}` instead of the `<strong>` - can you do that instead?

2019-05-08 06:22 UTC, abregorivas commented on _includes/hack-nights.html
>                      <strong>{{ item.title }}</strong> {{ item.event-date }}
Actually The original code looked as shown below. If you add the title into the h3 you loose the bold and the title will be a block item vs an inline tag. I think removing the h3 is the way to go.
<div class="location-details"><h3 class="location-header"></h3>
<strong>Westside</strong> Mondays at 6:00 pm<address>
</div>

2019-05-09 05:29 UTC, thekaveman approved these changes

2019-05-09 05:32 UTC, merged