Sitemap Page
hackforla/website pull request #977
Opened 2021-01-30 00:01 UTC by martham0

fixes #595

Created the sitemap page. It is almost ready for deployment. Need to figure out a few spacing issues and class names. Questions found in scss page.
<img width="1199" alt="Screen Shot 2021-01-29 at 3 59 07 PM" src="https://user-images.githubusercontent.com/69860036/106339333-1dfb2680-624b-11eb-9ed9-93c6e23f1653.png">
<img width="1199" alt="Screen Shot 2021-01-29 at 3 59 25 PM" src="https://user-images.githubusercontent.com/69860036/106339335-1f2c5380-624b-11eb-8cbe-2f6ce4b26123.png">
<img width="378" alt="Screen Shot 2021-01-29 at 3 59 50 PM" src="https://user-images.githubusercontent.com/69860036/106339338-22bfda80-624b-11eb-886e-6ea879f059e1.png">
<img width="378" alt="Screen Shot 2021-01-29 at 4 00 01 PM" src="https://user-images.githubusercontent.com/69860036/106339341-23f10780-624b-11eb-86a5-7fcb61145b59.png">
<img width="378" alt="Screen Shot 2021-01-29 at 4 00 09 PM" src="https://user-images.githubusercontent.com/69860036/106339344-25bacb00-624b-11eb-9b60-f7db0176365a.png">

2021-01-30 23:42 UTC, daniellex0 commented on _sass/components/_sitemap.scss
> +  //following figma color but this is different from the rest of the site(#f7f5f5)
This should indeed be the standard color (#f7f5f5), I'm not sure why or where that other color is in Figma!

2021-01-30 23:46 UTC, daniellex0 commented on _sass/components/_sitemap.scss
> +//¿¿Do I need to create my own page specific class for the page cards or can I copy & paste the following notes left by Danielle?
Yes please use the page card classes that I included in the notes (if they work for you)- they will eventually be in a common shared scss file, but in the meantime these can live in your page's scss file

2021-02-01 14:35 UTC, trtincher requested changes
Looks like there is a padding issue on mobile cards (pic below)
![Screen Shot 2021-02-01 at 8 30 55 AM](https://user-images.githubusercontent.com/35665684/106472159-06e55000-6468-11eb-9488-f2cc2be380f3.png)

2021-02-01 14:35 UTC, trtincher commented on _sass/components/_sitemap.scss
> +---------------------------*/
I'm concerned that these base classes are not nested. My understanding  is this could cause unpredictable effects on other pages.

2021-02-03 00:16 UTC, daniellex0 commented
@martham0 the page is looking fantastic, great job- it's so close!

I have some edits- it's easiest for me to communicate them via Figma, so I wrote them down with screenshots to the the right of the my previous notes on the [sitemap page Figma file](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3164%3A18). Yes even more of my crazy notes, sorry! Let me know if you have any questions or if any of them don't make sense..

2021-02-05 18:46 UTC, martham0 commented on _sass/components/_sitemap.scss
> +---------------------------*/
Those classes are only temporarily there until @daniellex0 standardizes the page card classes. Do you believe it will still be an issue if I leave it as is until the classes get standardized?

2021-02-05 18:49 UTC, martham0 commented
The page has been updated with the edits mentioned above. Please look it over once more and let me know if you have any comments on the page @daniellex0 @trtincher.


Thanks, Danielle for the extra notes/pictures on Figma. They were really helpful.

2021-02-07 10:15 UTC, daniellex0 requested changes
Wow this looks perfect, good job!! 🙌

My only nit-picky edit (I'm so sorry to do this) is that in mobile the paragraph text should be max-width 300px (it's currently 311px - this is the case on some other pages devs are working on right now so this might be some kind of bigger issue..). Is there any way to make the paragraph text max 300px width in mobile? I'm really sorry, I know this seems very minor but it affects legibility in mobile when the text is too close to the margins, and a few pixels make the difference.. but this is literally the ONLY edit I see, otherwise it's all fantastic.

2021-02-07 18:12 UTC, martham0 commented
Updates have been made @daniellex0 . Thanks for the notes!

![image](https://user-images.githubusercontent.com/69860036/107155400-04359f80-692d-11eb-9cca-567688135693.png)

2021-02-09 19:41 UTC, drubgrubby requested changes
@martham0 - Really nice work!  This page looks great.  I just have a couple of small comments and then we're ready to merge.

2021-02-09 19:41 UTC, drubgrubby commented on _sass/elements/_containers.scss
> -    padding: 40px;
The class ".header-container" is used on other pages (about-us, events, getting started). If you make a change here it will impact all of those pages.  I'm sure at some point Danielle will re-vamp all of the container classes, but in the meantime it seems better not to change the padding here, but to put a second class in "_sitemap.scss" that modifies this. 

```
.header-container--sitemap {
     padding: 64px;
}
```
Or you could move the class to sitemap.scss and nest it to limit it's scope.

2021-02-09 19:41 UTC, drubgrubby commented on _sass/elements/_containers.scss
> -    padding: 40px;
As I get further in I see that you already have that class with the changed padding, so you can change this class back to what it was originally.   (If you use it as .header-container somewhere else that I haven't gotten to yet, then use the above suggestion to make a secondary class for that.

2021-02-09 19:41 UTC, drubgrubby commented on sitemap.html
> +<div class=" header-container--sitemap">
There's an extra space after the quote, before the class name. (Nitpicky, yes, but while you're in there you might as well clean that up.)

2021-02-09 19:41 UTC, drubgrubby commented on sitemap.html
> +            <a href="https://github.com/hackforla/website/wiki"><button class="btn btn-primary btn-md-long-2">Check out
I'm assuming that we want these buttons to open in a new tab.  (@daniellex0)

2021-02-09 19:41 UTC, drubgrubby commented on sitemap.html
> +            <a
I'm assuming that we want these buttons to open in a new tab.  (@daniellex0)

2021-02-10 00:15 UTC, daniellex0 commented on sitemap.html
> +            <a href="https://github.com/hackforla/website/wiki"><button class="btn btn-primary btn-md-long-2">Check out
@drubgrubby @martham0 Yeah, that would be great!

2021-02-10 00:16 UTC, daniellex0 commented
@martham0 Visual review done, looks fantastic! 👍

2021-02-10 00:16 UTC, daniellex0 approved these changes

2021-02-10 03:14 UTC, martham0 commented
Changes made and ready to deploy. 

https://github.com/hackforla/website/issues/595#issuecomment-776408207

2021-02-10 04:32 UTC, merged