added environment on vertical to project cards
hackforla/website pull request #986
Opened 2021-02-03 01:35 UTC by DanielekPark

fixes issue #894
Added environment to vertical on tdm-calculator.md file on line 76, to public-tree-map.md on line 58, and to metro-ontime.md on line 58

2021-02-03 02:48 UTC, drubgrubby requested changes
You did this exactly right.  Good job. However, the issue wasn't quite clear that it should have single quotes around 'Environment'.   If you can add the single quote marks it will be perfect.

2021-02-03 02:48 UTC, drubgrubby commented on _projects/metro-ontime.md
> +vertical: Environment
The word Environment should be contained in single quotes: 'Environment'.  This was not clear in the issue, but it is the standard.  (I'm going to edit the issue now to show that).

2021-02-03 02:48 UTC, drubgrubby commented on _projects/public-tree-map.md
> +vertical: Environment
Please change to: 'Environment'

2021-02-03 02:48 UTC, drubgrubby commented on _projects/tdm-calculator.md
> +vertical: Environment
Please change to: 'Environment'

2021-02-03 02:51 UTC, drubgrubby commented
Also, the top line should read: "Fixes #894" , without the word "issue".

2021-02-05 02:29 UTC, DanielekPark commented
Fixes #894 added quotes to Environment for metro-ontime.md on line 36, public-tree-map.md on line 58, and on line 76 to td-calculator.md

2021-02-05 17:57 UTC, drubgrubby commented
@DanielekPark - Hey Daniel.  I only see the original commit on this PR; I don't see the changes where you added the quotes.   Usually if you push to the same branch it will add it to the PR.  Can you check to see if pushed to the same branch as your previous commit, or if you pushed to a new branch, or perhaps haven't pushed the changes yet?  We can look at this on Sunday if it's not clear.

2021-02-07 02:42 UTC, drubgrubby commented
Daniel and I discussed this on Slack.  He has completed the changes, but seems to have pushed it to a new branch so it's not showing up here.  We will go over this at the dev meeting on Sunday.

2021-02-08 17:44 UTC, merged